### ISSUE TITLE
[BUG] Missing "back" menu items on 2.1.x using BigTreeTech SKR Mini E3 3.0 w/ stock Ender 3 display & encoder.

### ISSUE THREAD

**Issue by jwsmart** [MarlinFirmware/Marlin#24701] opened 2022-08-27 18:37 UTC
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

After compiling marlin for the Ender 3 w/ BigTreeTech SKR Mini E3 3.0 from the 2.1.x bugfix branch, with an appropriate example config from the matching 2.1.x bugfix branch of the configuration repo, there were no "back" menu items for the LCD:
![Marlin2 1Menu](https://user-images.githubusercontent.com/13633691/187041358-61350b10-190e-4938-a028-a1ecb08db5cf.png)
This made menu navigation impossible.

After compiling 2.0.x bugfix with an equivalent configuration (sourced from the 2.0,x bugfix branch of the configuration repo) , the menu items appeared as expected:
![Marlin2 0Menu](https://user-images.githubusercontent.com/13633691/187043797-425d828c-4af2-4cfb-a4c1-75e58d5bf87b.png)

I don't believe it's an issue with the example configurations, because they don't seem to be different in any important way that I could see.

### Expected behavior

Expected the normal "back" menu items as the topmost item in every Marlin menu when using a CR10 style LCD & Encoder.

### Actual behavior

No "back" menu items were available.

### Version of Marlin Firmware

2.1.x bugfix

### Printer model

Creality Ender 3

### Electronics

BigTreeTech SKR Mini E3 3.0

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[broken-2.1.x-bugfix-configuration.zip](https://github.com/MarlinFirmware/Marlin/files/9438414/broken-2.1.x-bugfix-configuration.zip)
[working-2.0.x-bugfix-configuration.zip](https://github.com/MarlinFirmware/Marlin/files/9438416/working-2.0.x-bugfix-configuration.zip)

**Comment by thisiskeithb** [comment] 2022-08-27 18:43
Duplicate of https://github.com/MarlinFirmware/Marlin/issues/24689

**Closed as completed by thisiskeithb** 2022-08-27 18:43 UTC
