### ISSUE TITLE
[2.0.x] Compile error TMC2130 with enabled ENDSTOP_INTERRUPTS_FEATURE

### ISSUE THREAD

**Issue by mat100** [MarlinFirmware/Marlin#12153] opened 2018-10-19 12:06 UTC
Hi,

since the commit c3229e1b3461b6da8373e7a24a7eeb131912a15b (Migrate to a new TMC library) I can not compile firmware with ENDSTOP_INTERRUPTS_FEATURE enabled. I get the following error...

```
SoftwareSerial.cpp.o (symbol from plugin): In function `SoftwareSerial::read()':
(.text+0x0): multiple definition of `__vector_9'
.pioenvs/rambo/src/src/module/endstops.cpp.o (symbol from plugin):(.text+0x0): first defined here
SoftwareSerial.cpp.o (symbol from plugin): In function `SoftwareSerial::read()':
(.text+0x0): multiple definition of `__vector_11'
.pioenvs/rambo/src/src/module/endstops.cpp.o (symbol from plugin):(.text+0x0): first defined here
SoftwareSerial.cpp.o (symbol from plugin): In function `SoftwareSerial::read()':
(.text+0x0): multiple definition of `__vector_10'
.pioenvs/rambo/src/src/module/endstops.cpp.o (symbol from plugin):(.text+0x0): first defined here
collect2.exe: error: ld returned 1 exit status
*** [.pioenvs\rambo\firmware.elf] Error 1
```

if is ENDSTOP_INTERRUPTS_FEATURE disabled, compilation runs without errors

**Comment by kAdonis** [comment] 2018-10-19 13:58
Look at #12078

**Comment by thinkyhead** [comment] 2018-10-26 08:23
Duplicate of #12078

**Closed as completed by thinkyhead** 2018-10-26 08:23 UTC
