### ISSUE TITLE
[BUG] SENSORLESS_HOMMING not work in axis I,K,J.

### ISSUE THREAD

**Issue by Sherensberk** [MarlinFirmware/Marlin#23278] opened 2021-12-08 18:00 UTC
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

I recently acquired a BTT OCTOPUS V1.1 that supports up to nine motors being normally (X, Y, Z, Z2, E0, E1, E2, E3), being Z and Z2, connected to the same driver, but I would like to use all three standard marlin axes (X,Y,Z) along with the new ones (I,J,K).
And it worked, after a few hours solving compilation problems, since the pin file 'pins_btt_octopu_v1_common.h' doesn't have the necessary values for I,J,K only (E0 >>> E4), I was able to move each axis in this way independent. The problem is that, as I am using a TMC5160 driver, I would like to use the 'sensorless' option, for all axes, since in the advanced settings there are blocks:
""
X_STALL_SENSITIVITY,
Y_STALL_SENSITIVITY,
Z_STALL_SENSITIVITY,
I_STALL_SENSITIVITY,
J_STALL_SENSITIVITY,
K_STALL_SENSITIVITY
""
it is assumed that the axes (I,J,K) support this, but when executing the command 'G28 A', and holding the motor preventing it from moving, the axis continues forcing until the printer activates the 'kill_pin' for ending the homming. This occurs on any of the new three axes, (I,J,K). (X,Y,Z) work properly, in whatever driver I configure them.

### Bug Timeline

new, 6/12/21

### Expected behavior

The axes (I,J,K or A,B,C) must act in the same way as (X,Y,Z), after the command 'G28' if any one of them collides or suffers sufficient resistance, the signal pin of the driver must be activated, causing the axis to stop.

### Actual behavior

Even if you lock/hold the axis after the G28 command, it continues to move (or try) until the machine turns off.
This only happens on the axes (I,J,K or A,B,C).
The (X,Y,Z) axes work properly

### Steps to Reproduce

1. Enable 6 linear axes in the settings.
2. Configure the necessary parameters of the new axes, (speed, acceleration, etc.)
3. Enable the 'SENSORLESS_HOMING' option, and set the sensitivity of each axis (2 worked fine for me)
4. Edit the pin file ('pins_btt_octopus_v1_common.h') and add the "DIAG", "STOP", "MAX","ENABLE", "STEP","DIR" and "CS" pins for each axis new, (I recommend renaming the extruders (E1->E4)) or using the pin file that I'll keep attached.
5. Send the homming command to the 'X' axis, (G28 X) and hold it with your hands. Note that it will stop as if it had reached a limit switch, repeat the same process with all axes, and you will see that only the axes (I,J,K, called A,B,C) continued to be move even after hitting.

### Version of Marlin Firmware

Marlin 2.0.9.2

### Printer model

Big Tec Tree Octopus V1.1

### Electronics

TMC5160 drivers

### Host Software

SD Card (headless)

### Additional information & file uploads

English is not my main language, soo i used google translator, if something does not make sense, please inform.

[log.txt](https://github.com/MarlinFirmware/Marlin/files/7677917/log.txt)
[log_pins.txt](https://github.com/MarlinFirmware/Marlin/files/7677918/log_pins.txt)
[Config.zip](https://github.com/MarlinFirmware/Marlin/files/7677938/Config.zip)
![20211208_145811](https://user-images.githubusercontent.com/76601292/145259488-9fdc1cfc-c560-41f3-b6cb-674577731ba9.jpg)

**Comment by ellensp** [comment] 2021-12-08 21:20
Duplicate of https://github.com/MarlinFirmware/Marlin/issues/22649

**Closed as completed by ellensp** 2021-12-08 21:20 UTC
