### ISSUE TITLE
[BUG] Ender 5 Plus - Sample configurations fail to build - DGUS problems

### ISSUE THREAD

**Issue by CRCinAU** [MarlinFirmware/Marlin#22334] opened 2021-07-11 02:35 UTC
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

When building bugfix-2.0.x with the latest Configurations example for Ender 5 Plus, the following compile errors occur:

```
Marlin/src/lcd/extui/dgus/origin/DGUSDisplayDef.cpp:277:1: error: no matches converting function 'GetVariable' to type 'void (*)(struct DGUS_VP_Variable&, void*)'
 };
 ^
In file included from Marlin/src/lcd/extui/dgus/origin/DGUSDisplayDef.cpp:32:0:
Marlin/src/lcd/extui/dgus/origin/../DGUSDisplay.h:76:15: note: candidate is: template<class T, void (* Setter)(float, T), T selector> static void DGUSDisplay::GetVariable(DGUS_VP_Variable&, void*)
   static void GetVariable(DGUS_VP_Variable &var, void *val_ptr) {
               ^~~~~~~~~~~
Compiling .pio/build/mega2560/src/src/module/probe.cpp.o
*** [.pio/build/mega2560/src/src/lcd/extui/dgus/origin/DGUSDisplayDef.cpp.o] Error 1
Marlin/src/lcd/extui/dgus/origin/DGUSScreenHandler.cpp: In static member function 'static void DGUSScreenHandler::DGUSLCD_SD_ResumePauseAbort(DGUS_VP_Variable&, void*)':
Marlin/src/lcd/extui/dgus/origin/DGUSScreenHandler.cpp:88:20: error: 'MKSLCD_SCREEN_PAUSE' was not declared in this scope
         GotoScreen(MKSLCD_SCREEN_PAUSE);
                    ^~~~~~~~~~~~~~~~~~~
Marlin/src/lcd/extui/dgus/origin/DGUSScreenHandler.cpp:88:20: note: suggested alternative: 'DGUSLCD_SCREEN_UNUSED'
         GotoScreen(MKSLCD_SCREEN_PAUSE);
                    ^~~~~~~~~~~~~~~~~~~
                    DGUSLCD_SCREEN_UNUSED
*** [.pio/build/mega2560/src/src/lcd/extui/dgus/origin/DGUSScreenHandler.cpp.o] Error 1
```

### Bug Timeline

Unknown

### Expected behavior

Compilation completes.

### Actual behavior

See failure.

### Steps to Reproduce

1. Checkout bugfix-2.0.x
2. Copy config files from: https://github.com/MarlinFirmware/Configurations/tree/bugfix-2.0.x/config/examples/Creality/Ender-5%20Plus
3. Build.

### Version of Marlin Firmware

bugfix-2.0.x

### Printer model

Creality Ender 5 Plus

**Comment by thisiskeithb** [comment] 2021-07-11 02:36
Duplicate of https://github.com/MarlinFirmware/Marlin/issues/21576

**Closed as completed by thisiskeithb** 2021-07-11 02:36 UTC
