### ISSUE TITLE
Problem with ADVANCED_PAUSE_FEATURE on 1.1.3

### ISSUE THREAD

**Issue by JanVelleman** [MarlinFirmware/Marlin#7057] opened 2017-06-14 10:24 UTC
Just put 1.1.3 on my delta that previously had 1.1.0-1.

The filament change routine worked previously but now then pressing "resume print" the head returns to the previous print position but to immediately return to the "park position" wich is 50mm higher (per my config) and continue printing from there in the air... ?

Any Ideas?

**Comment by JanVelleman** [comment] 2017-06-14 11:30
I found if I comment the "set_current_to_destination();" in line 6084 in the Marlin_main.cpp.
This behavior is resolved. I cross checked version 1.1.0-1 with 1.1.3 and this line seemed to be added but does not need to be here??

So I'm happy as my 1.1.3 version is working (filament change and pause print) as I want it know but does anybody have an idea if this line was an error or needs to be here??

sincerely

**Comment by tcm0116** [comment] 2017-06-15 04:25
Hmm. When I combined M125 and M600, that line got added because it was in `move_back_on_resume()`, which was used by M125. However, the similar portions of the M600 code did not call `set_current_to_destination()`.

I know calling `set_current_to_destination()` after `planner.buffer_line_kinematic()` works for kinematic machines, so maybe the best option would be to move it to within the `#if IS_KINEMATIC` section right after the call to `planner.buffer_line_kinematic()`.

I'm not that familiar with how all of the planner movement commands work, so maybe @thinkyhead or @Roxy-3D can chime in with their thoughts.

**Comment by thinkyhead** [comment] 2017-06-18 22:44
The current (and perhaps previous) versions of `M125`/`M600` don't alter the `current_position` when they do their moves, and I guess this is by design. Note that if bed compensation is active, these moves _will_ include bed compensation.

As long as none of the code involved with `M125` and `M600` ever alters `current_position`, and as long as `resume_position` is the same as the starting position, then there's no need to set `current_position` from `destination`.

However, it may be better in the long run to alter the code so it does update `current_position` after each move, so that these functions can be made cancellable. The problem is, if you decide to cancel a filament change or the active print job in the middle of `M125` or `M600`, the `current_position` will be lost if it's not updated after each move.

Alternatively, it should be safe to use `set_current_from_steppers_for_axis(ALL_AXES)` after any cancellation. This function should now be very reliable — though maybe not fully for UBL yet, as it is still not integrated with `Planner::unapply_leveling` AFAIK.

**Comment by tcm0116** [comment] 2017-06-19 02:06
> Note that if bed compensation is active, these moves will include bed compensation.

I would think that this is what we want to ensure the nozzle doesn't crash into the print while moving to the park position. The nozzle is lifted some amount before moving, but I think having the leveling applied is good. 

> As long as none of the code involved with M125 and M600 ever alters current_position, and as long as resume_position is the same as the starting position, then there's no need to set current_position from destination.

For the purposes of fixing this issue I'm the short term, it seems like just removing the call to `set_current_to_destination()` is the best option. We could then revisit this after the code rework. Work for you?

**Comment by Roxy-3D** [comment] 2017-06-19 03:28
> For the purposes of fixing this issue I'm the short term, it seems like just removing the call to set_current_to_destination() is the best option. We could then revisit this after the code rework. Work for you?

I will load up any Pull Request you do and provide test information on a Cartesian printer with a BL-Touch probe.   I'll help any way I can.

**Comment by thinkyhead** [comment] 2017-06-19 03:57
> just removing the call to set_current_to_destination() is the best option.

Ok, I will add that change to my other PR.

**Comment by thinkyhead** [comment] 2017-06-19 05:27
The change has been merged (#7079). If it resolves the issue with no side-effects, then we can close this issue.

**Closed as completed** 2017-06-19 17:55 UTC
Labels: Bug: Confirmed !
