### ISSUE TITLE
Linear Advance Calibration Pattern website doesn't work in Chrome

### ISSUE THREAD

**Issue by hahnpv** [MarlinFirmware/Marlin#17372] opened 2020-04-01 18:17 UTC
Clicking "Generate gcode" does not generate gcode. I am not smart enough to debug javascript. 

https://marlinfw.org/tools/lin_advance/k-factor.html

Thank you,
philip

**Comment by thisiskeithb** [comment] 2020-04-01 18:30
Duplicate of #17366

**Comment by thinkyhead** [comment] 2020-04-01 20:40
Duplicate of #17357.

**Closed as completed by thinkyhead** 2020-04-01 20:40 UTC
