### ISSUE TITLE
[BUG] enabling AUTO_BED_LEVELING_3POINT + PROBE_MANUALLY results in a compile error

### ISSUE THREAD

**Issue by Omeric** [MarlinFirmware/Marlin#21765] opened 2021-05-01 15:31 UTC
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

compilation failure when AUTO_BED_LEVELING_3POINT and PROBE_MANUALLY are enabled

### Bug Timeline

first instance of the new 2.0.8 build (30/04/2021)

### Expected behavior

software to compile without errors

### Actual behavior

Compiling .pio\build\mega2560\src\src\gcode\config\M302.cpp.o
In file included from Marlin\src\gcode\bedlevel\abl\../../../inc/MarlinConfig.h:55:0,
                 from Marlin\src\gcode\bedlevel\abl\G29.cpp:27:
Marlin\src\gcode\bedlevel\abl\G29.cpp: In static member function 'static void GcodeSuite::G29()':
Marlin\src\gcode\bedlevel\abl\G29.cpp:476:69: error: 'class G29_State' has no member named 'abl_points'; did you mean 'abl_probe_index'?
         SERIAL_ECHOPAIR("point ", _MIN(abl.abl_probe_index + 1, abl.abl_points));
                                                                     ^
Marlin\src\gcode\bedlevel\abl\../../../inc/../core/serial.h:174:57: note: in definition of macro '_SEP_2'
 #define _SEP_2(PRE,V)     serial_echopair_PGM(PSTR(PRE),V)
                                                         ^
Marlin\src\gcode\bedlevel\abl\../../../inc/../core/serial.h:172:27: note: in expansion of macro '__SEP_N'
 #define _SEP_N(N,V...)    __SEP_N(N,V)
                           ^~~~~~~
Marlin\src\gcode\bedlevel\abl\../../../inc/../core/serial.h:198:31: note: in expansion of macro '_SEP_N'
 #define SERIAL_ECHOPAIR(V...) _SEP_N(NUM_ARGS(V),V)
                               ^~~~~~
Marlin\src\gcode\bedlevel\abl\G29.cpp:476:9: note: in expansion of macro 'SERIAL_ECHOPAIR'
         SERIAL_ECHOPAIR("point ", _MIN(abl.abl_probe_index + 1, abl.abl_points));
         ^~~~~~~~~~~~~~~
Marlin\src\gcode\bedlevel\abl\G29.cpp:477:39: error: 'class G29_State' has no member named 'abl_points'; did you mean 'abl_probe_index'?
         SERIAL_ECHOLNPAIR(" of ", abl.abl_points);
                                       ^
Marlin\src\gcode\bedlevel\abl\../../../inc/../core/serial.h:235:62: note: in definition of macro '_SELP_2'
 #define _SELP_2(PRE,V)     do{ serial_echopair_PGM(PSTR(PRE),V); SERIAL_EOL(); }while(0)
                                                              ^
Marlin\src\gcode\bedlevel\abl\../../../inc/../core/serial.h:233:28: note: in expansion of macro '__SELP_N'
                            ^~~~~~~~
Marlin\src\gcode\bedlevel\abl\../../../inc/../core/serial.h:265:33: note: in expansion of macro '_SELP_N'
 #define SERIAL_ECHOLNPAIR(V...) _SELP_N(NUM_ARGS(V),V)
                                 ^~~~~~~
Marlin\src\gcode\bedlevel\abl\G29.cpp:477:9: note: in expansion of macro 'SERIAL_ECHOLNPAIR'
         SERIAL_ECHOLNPAIR(" of ", abl.abl_points);
         ^~~~~~~~~~~~~~~~~
Marlin\src\gcode\bedlevel\abl\G29.cpp:570:37: error: 'class G29_State' has no member named 'abl_points'; did you mean 'abl_probe_index'?
       if (abl.abl_probe_index < abl.abl_points) {
                                     ^~~~~~~~~~
                                     abl_probe_index
*** [.pio\build\mega2560\src\src\gcode\bedlevel\abl\G29.cpp.o] Error 1
================================================================================================== [FAILED] Took 9.28 seconds ================================================================================================== 

Environment    Status    Duration
-------------  --------  ------------
mega2560       FAILED    00:00:09.284

### Steps to Reproduce

get latest 2.0.8 marlin 
get example configs for bq / witbox
enable AUTO_BED_LEVELING_3POINT
enable PROBE_MANUALLY

run compilation

### Version of Marlin Firmware

2.0.8

### Printer model

bq witbox

### Electronics

ramps 1.4

### Your Slicer

Simplify3D

### Host Software

SD Card (headless)

**Comment by ellensp** [comment] 2021-05-02 00:09
Duplicate of https://github.com/MarlinFirmware/Marlin/issues/21693

**Closed as completed by ellensp** 2021-05-02 00:09 UTC
