### ISSUE TITLE
[BUG] remaining time bugges printer

### ISSUE THREAD

**Issue by Skyllaer** [MarlinFirmware/Marlin#17339] opened 2020-03-30 19:02 UTC
Bug Description

after ending a print, the LCD keeps cycling between active printed time / remaining print time
[config.zip](https://github.com/MarlinFirmware/Marlin/files/4404853/config.zip)

### My Configurations

uploaded, using 2.0.5.2

### Steps to Reproduce

slice a hollow cube with 1 wall, no bottom and top layers.
In cura post proces add show remaining time
Print the cube

**Expected behavior:** 

Finishing the cube, the printer would go back in the ready state.

**Actual behavior:** 

Timings between the cura / printers remaining timer are way off. Cura's timer is correct.
After the print is finished, the printer get's stuck in the "active / remaining time" and doesn't get into the ready state again.

#### Additional Information
![image0](https://user-images.githubusercontent.com/61694339/77951087-c78b2780-72c9-11ea-9a2a-9c2f95d98ff7.jpg)

**Comment by thinkyhead** [comment] 2020-05-01 05:59
Please test the [`bugfix-2.0.x` branch](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.0.x.zip) to see where it stands. If the problem has been resolved then we can close this issue. If the issue isn't resolved yet, then we should investigate further.

**Comment by boelle** [comment] 2020-06-20 23:05
Lack of Activity
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.

**Closed as completed by boelle** 2020-06-20 23:05 UTC
