### ISSUE TITLE
M303 Bed PID Autotune fails

### ISSUE THREAD

**Issue by brisma** [MarlinFirmware/Marlin#12468] opened 2018-11-18 09:40 UTC
### Description

Hi, after the latest changes on the M303 GCODE there is a problem with the PID Autotune of the bed. It seems to use the E0 temperature/heater instead of E-1.

### Steps to Reproduce

1. Do a M303 E-1 S60 C6
2. Watch the temperature of Bed and Hotend
3. The autotune of the bed will fails

Or

1. Set the temperature of hotend to 200°C
2. Do a M303 E-1 S60 C6
3. The autotune fails at start with the message "Too hot".

**Comment by neoxm3** [comment] 2018-11-18 12:02
i have exactly the same problem...
 M303 E-1 S60 C6  or  M303 P0 - 1 -2 - 3.... (i tryed all for see what happens)  heats the extruder, and not the bed.
Electronics: Melzi , only one extruder.

**Comment by RudyBenner** [comment] 2018-11-18 16:45
#define PIDTEMPBED

//#define BED_LIMIT_SWITCHING

**Comment by neoxm3** [comment] 2018-11-18 17:37
> 
> 
> #define PIDTEMPBED
> 
> //#define BED_LIMIT_SWITCHING

i have it this way...

**Comment by gloomyandy** [comment] 2018-11-18 18:01
When asking for help please make sure that you upload your configuration files. It also helps if you provide details of exactly which version of Marlin you are using (and if a bugfix build when you downloaded it).

**Comment by ghulands** [comment] 2018-11-18 22:24
I am having this issue too on the bugfix-2.0.x branch. I did a quick investigation of the issue and the problem is because of this line. https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/Marlin/src/gcode/temperature/M303.cpp#L40

The byteval() method is a constrained value between 0-255. I have fixed it locally by introducing a ubyteval() method, updating all calls from byteval to ubyteval and then having a byteval method that is constrained between -255 and 255... though i think it should probably be -254 to 254.

Let me know if you'd like a PR for it.

**Comment by kAdonis** [comment] 2018-11-18 22:52
I already submitted a PR #12471  changing byteval() back to intval()
its working for me

**Comment by ghulands** [comment] 2018-11-18 22:54
👍

**Comment by kAdonis** [comment] 2018-11-19 00:10
should be fixed now

**Comment by brisma** [comment] 2018-11-19 08:58
Ok, now is working correctly.

**Closed as completed** 2018-11-19 08:59 UTC

**Comment by reloxx13** [comment] 2019-01-13 01:58
seems not to work, im on latest marlin 2.0.x from today

> Send: M303 E-1 S60 C8 U
> Recv: PID Autotune failed! Bad extruder number
> Recv: ok


Ender 3 and here are my configs:
https://github.com/reloxx13/Marlin/tree/my-marlin/Marlin

i checked the m303.cpp and its
`const int8_t e = parser.intval('E');`

EDIT: i just saw 
`//#define PIDTEMPBED`
-_- sorry

EDIT2:
maybe we can get a note in the docs
"if its not enabled it will not find the E settings" or sth like this
http://marlinfw.org/docs/gcode/M303.html
