### ISSUE TITLE
Hard Reset on long extrusions when commanded by a Gcode file verses manual request.

### ISSUE THREAD

**Issue by cobramike41** [MarlinFirmware/Marlin#10938] opened 2018-06-05 14:18 UTC
### Description

I updated the advanced configeration tab to allow for longer extrusions due to my color switching bowden setup having to pull/push 500mm of filament to change colors. I can manually extrude 500 mm with no issues using octoprint and repeater. EX: M83, G1 E500 F3000. However when printing if the GCODE tries to do this EX: G1 X15 E490 F1562, the printer hard resets and the print is lost.

### Steps to Reproduce

1. Using Slic3R 1.4 Beta PE, slice the model with the Pruge tower on using at least 2 colors.
2. Send to OCTOPRINT
3. Print

**Expected behavior:**
Printer follows the below commands
G1 X# E20 F1256
G1 X# E490 F1563
G1 X# E20 F1256
G1 X# E10 F200

The feed rates are variable based on whatever math Slic3r uses to do a purge.

**Actual behavior:** [What actually happens]
Printer Runs
G1 X# E20 F1256
Printer starts
G1 X# E490 F1563
then hard resets at about 60% of that extrusion.

#### Additional Information

I can get around this by post-processing the GCode to replace G1 X# E490 F1563 with the following commands G1 X# E100 F3000, G1 E100 F3000, G1 E100 F3000, G1 E100 F3000, G1 E190 F3000.

This solution was confermed on a 2-color print which switched colors aproximatly 15 times, however I would like to not have to post process.

**Comment by thinkyhead** [comment] 2018-06-08 01:28
> the printer hard resets and the print is lost

This is usually caused by too much load on the processor. Keep reducing your maximum feedrate for the E axis until you no longer get a reboot. If you're using 32x micro-stepping for E, reduce it to 16x.

**Comment by boelle** [comment] 2019-02-20 13:40
@cobramike41 

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to to a bug in Marlin, then you should post a bug report.
Before posting a bug report please test with `bugfix-2.0.x` to check if problem is gone

**Comment by boelle** [comment] 2019-03-13 21:43
@thinkyhead think we can close this one

**Closed as completed** 2019-03-13 23:57 UTC
Labels: T: Question
