### ISSUE TITLE
Compilation error when selecting the russian language for reprap discount graphics controller

### ISSUE THREAD

**Issue by SkyFlyer2** [MarlinFirmware/Marlin#1633] opened 2015-03-18 07:36 UTC
The code not compile - we get an error

language_ru.h:47:45: error: 'LCD_STR_THERMOMETER' was not declared in this scope
 #define MSG_BED                             LCD_STR_THERMOMETER " РљСЂРѕРІР°С‚СЊ"

Selection any other possible language is ok - successful compilation.

Ramps 1.4 with mega 2560 & Reprap Discount Full Graphics Controller

**Comment by GrandK** [comment] 2015-03-19 05:19
Change  'LCD_STR_THERMOMETER'  to  'STR_THERMOMETER'  in language_ru.h

**Comment by SkyFlyer2** [comment] 2015-03-19 05:45
Now compiled. However, no Russian characters, special symbols instead.

**Comment by AnHardt** [comment] 2015-03-19 08:10
@SkyFlyer2 
Russian language support needs special hardware (http://store.comet.bg/download-file.php?id=466) to work on 20x4  displays.
When #1622 is applied Russian language will be supported for all the 12864 displays.

**Comment by SkyFlyer2** [comment] 2015-03-19 08:18
Thanks, now it is clear for me. Will wait, is not so important.

**Comment by thinkyhead** [comment] 2015-03-28 03:47
The Big Language Pack has been merged, and the code seems very stable. Most likely this issue is all fixed!

**Closed as completed** 2015-03-31 10:51 UTC

**Comment by SkyFlyer2** [comment] 2015-03-31 12:48
This issue was not solved completely, the code still not compile.

If I comment this line - the code can be compiled. The cyrillic characters are present and ok.

#define MSG_BED                             LCD_STR_THERMOMETER " Кровать"

**Comment by AnHardt** [comment] 2015-03-31 13:58
@SkyFlyer2 
I'm sorry but i can't reproduce the error. Could you please load up your Configuration.h and the, maybe defect, language file somewhere.

**Comment by SkyFlyer2** [comment] 2015-03-31 14:21
Sorry, i used the old pre-configured file "configuration.h" with my printer settings, from previous commit. 

Now it is ok, the code can be compiled, i am used the configuration.h from last commit.

What to change to get the small fonts?

**Comment by AnHardt** [comment] 2015-03-31 14:41
@SkyFlyer2 
Ether comment in line 46 in 'dogm_lcd_implementation.h' or 
#define USE_SMALL_INFOFONT 
somewhere in your 'Configuration.h'.

**Comment by AnHardt** [comment] 2015-03-31 14:51
@SkyFlyer2 
How many of your other problems are solved by the new Configuration.h? :-)

**Comment by SkyFlyer2** [comment] 2015-03-31 15:24
Авто уровень по-прежнему не функционируют.)

Трудно с каждым новым совершить двигаться настройки принтера на новый configuration.h

**Comment by SkyFlyer2** [comment] 2015-03-31 15:25
Auto level is still non-functional.)

It is hard with each new commit move the printer settings to the new configuration.h

**Comment by AnHardt** [comment] 2015-03-31 15:50
@SkyFlyer2 
Pardon? I can't read Cyrillic nor i understand Russian.

**Comment by SkyFlyer2** [comment] 2015-03-31 15:58
Now in English)

Auto level is still non-functional, everything else looks fine.
It is hard with each new commit move the my printer settings to the new configuration.h

**Comment by AnHardt** [comment] 2015-03-31 16:01
Oh, sorry.
I expected something like a minor error in the language file. :-)

**Comment by thinkyhead** [comment] 2015-04-01 02:27
@SkyFlyer2 For updating configs (and other files) a good diff-and-merge tool is essential.
