### ISSUE TITLE
Using Latest Marlin 2.0.5.3 with power loss recovery does not function at all.

### ISSUE THREAD

**Issue by astro-smart** [MarlinFirmware/Marlin#18261] opened 2020-06-11 17:12 UTC
### Bug Description

Using the latest build release and hourly build release as of 6/11/2020, this feature does not function at all  when enabled. When power off during print, no menu returns on power up to continue print.

### My Configurations

[Configs.zip](https://github.com/MarlinFirmware/Marlin/files/4766251/Configs.zip)

### Steps to Reproduce
With proper settings enabled for power loss recovery, I try to print, turn power off and wait for menu to resume. No menus every show up. SD card has no files on it either.

**Expected behavior:** [What you expect to happen]

Menu to appear on re powering printer.

**Actual behavior:** [What actually happens]

No menu appears

#### Additional Information

* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.

**Comment by yanfoo** [comment] 2020-06-11 23:06
You may want to edit your title to "bugfix-2.0.x", Your config files are not 2.0.5.3
It is still a bug, but for the beta.

I am using 2.0.5.3 stable and power loss recovery works as intended tested on an Ender 3 with SKR 1.3 board (set to onboard SDcard). You may want to go with the stable version if you want.
I did not specify a loss_pin and a pin state on my setup, try commenting theses out and see if it works.

**Comment by boelle** [comment] 2020-06-21 00:38
@astro-smart still an issue?

**Comment by astro-smart** [comment] 2020-06-21 20:30
Ive determined the only way to get this to work without the sd card being written to every 2 seconds is to use the power pin method instead. You need to get a mini ups for this to work as without it, the board powers off far to quickly for the states to be written the the sd card only with loss of power and power pin.. I ordered a mini ups for about 3 bucks each. When I get it, I will try the option and let you know. Currently, the software SD method does work but its too many writes to the sd card to use for a viable solution. After about a month, Im sure the 100k writes will kill the card. If fact I noticed even when not printing the SD card is written too. That part is a bug I would expect.

**Comment by sjasonsmith** [comment] 2020-06-30 06:08
Duplicate of #17378

@astro-smart, I'm consolidating a bunch of nearly identical issues involving power-loss recovery into one. Any further conversation can occur on the linked issue.

I'm going to quote you in a comment in that other issue. I'm not personally experienced with Power-Loss recovery, and I hope someone else will be able to contribute with what proper expectations should be for power-loss recover.

**Closed as completed by sjasonsmith** 2020-06-30 06:08 UTC

**Comment by thinkyhead** [comment] 2020-07-03 17:27
Duplicate of #17378
