### ISSUE TITLE
[2.0.x] Virtual extruder problem

### ISSUE THREAD

**Issue by orhaan68** [MarlinFirmware/Marlin#12409] opened 2018-11-12 13:06 UTC
Dear friends, i just flash my 3D printer (ramps 1.4) with marlin bugfix 2.0.x . Previously i was using marlin 1.1.9 and i have problems with diamond hotend and mixing extruder. At 1.1.9 I used mixing ratio at repetier host with M163 and M164 commands. But steppers moves more than command at mixing. At bugfix 2.0.x steppers move as command at mixing just with M165 command. M163 and M164 do not works. When I select virtual extruder T0 or T1 etc, it said unknown command.
repetier host virtual extruder code;
Ext1;
```gcode
M163 S0 P1.0
M163 S1 P0.0
M163 S2 P0.0
M164 S0
```
Ext2;
```gcode
M163 S0 P0.0
M163 S1 P1.0
M163 S2 P0.0
M164 S1
```
Ext3;
```gcode
M163 S0 P0.0
M163 S1 P0.0
M163 S2 P1.0
M164 S2
```

. . .

Ext15;
```gcode
M163 S0 P0.33
M163 S1 P0.33
M163 S2 P0.34
M164 S15
```

**Comment by AnHardt** [comment] 2018-11-12 16:47
Configs please.
Exact error message please.
Exact command before the error please.

**Comment by orhaan68** [comment] 2018-11-13 05:44
The configuration file is attached.
[Configuration.txt](https://github.com/MarlinFirmware/Marlin/files/2574748/Configuration.txt)

**Comment by AnHardt** [comment] 2018-11-13 10:04
Are you sure your version is newer than #12375.

**Comment by AnHardt** [comment] 2018-11-13 10:52
You might want to test #12417

**Comment by orhaan68** [comment] 2018-11-16 06:22
I am using repetier host. When change color (virtual extruder) it send command, for me T0 for red. Then command replied as "echo: T0 invalid extruder"
```
T0
echo:T0 Invalid extruder
```

**Comment by thinkyhead** [comment] 2018-11-16 10:42
I'm unable to reproduce the issue, using the current `bugfix-2.0.x`. `T0`-`T15` give no error, but `T16` is out of range.

**Comment by AnHardt** [comment] 2018-11-16 18:03
Default number of v-tools is 16 - so T0 to T15 is correct.
If all is as planned, the 'auto retraction tool', if defined, gets T16 - but is unselectable on purpose.

Probably fixed by merged #12417.

**Comment by boelle** [comment] 2019-02-21 19:43
@orhaan68 problem solved?

**Comment by orhaan68** [comment] 2019-02-22 05:07
Yes i solve problem. Tank you for your kind helps.

Android’de Yahoo Postadan gönderildi 
 
  22:43’’21e’ 21 Şub 2019 Per tarihinde, Bo Herrmannsen<notifications@github.com> şunu yazdı:   
@orhaan68 problem solved?

**Comment by boelle** [comment] 2019-02-22 06:49
@orhaan68 click green close button below

**Closed as completed** 2019-02-22 08:06 UTC
Labels: Bug: Potential ?, Needs: More Data
