### ISSUE TITLE
[BUG] LPC1769 SKR 1.4 Turbo fails to compile

### ISSUE THREAD

**Issue by mochoandre** [MarlinFirmware/Marlin#17731] opened 2020-04-26 14:39 UTC
I Am trying to compile latest 2.0.x bugfix for LPC1769 SKR 1.4 Turbo in vscode platformio but it fails to compile.
USing tmc2209, BLtouch, filament sensor and power loss detection config

`> Executing task in folder Marlin-bugfix-2.0.x: C:\Users\mocho\.platformio\penv\Scripts\platformio.exe run <

Processing LPC1769 (platform: https://github.com/p3p/pio-nxplpc-arduino-lpc176x/archive/0.1.2.zip; board: nxp_lpc1769; framework: arduino)
-----------------------------------------------------------------------------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/nxplpc-arduino-lpc176x/nxp_lpc1769.html
PLATFORM: NXP Arduino LPC176x 0.1.1 > NXP LPC1769
HARDWARE: LPC1769 120MHz, 31.97KB RAM, 464KB Flash
DEBUG: Current (cmsis-dap) On-board (cmsis-dap) External (blackmagic, jlink)
PACKAGES:
 - framework-arduino-lpc176x 0.2.2
 - toolchain-gccarmnoneeabi 1.90201.191206 (9.2.1)
Converting Marlin.ino
LDF: Library Dependency Finder -> http://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ off, Compatibility ~ strict
Found 13 compatible libraries
Scanning dependencies...
Dependency Graph
|-- <Servo> 1.0.0
|-- <LiquidCrystal> 1.0.0
|-- <U8glib-HAL> 0.4.1
|-- <TMCStepper> 0.6.2
|-- <Adafruit NeoPixel> 1.3.0
|-- <SailfishLCD>
Building in release mode

Unable to find destination disk (Autodetect Error)
Please select it in platformio.ini using the upload_port keyword (https://docs.platformio.org/en/latest/projectconf/section_env_upload.html) or copy 
the firmware (.pio/build/LPC1769/firmware.bin) manually to the appropriate disk

Compiling .pio\build\LPC1769\src\src\HAL\LPC1768\HAL_SPI.cpp.o
Compiling .pio\build\LPC1769\src\src\feature\babystep.cpp.o
Compiling .pio\build\LPC1769\src\src\feature\backlash.cpp.o
Compiling .pio\build\LPC1769\src\src\feature\baricuda.cpp.o
Compiling .pio\build\LPC1769\src\src\feature\bedlevel\abl\abl.cpp.o
Compiling .pio\build\LPC1769\src\src\feature\bedlevel\bedlevel.cpp.o
Compiling .pio\build\LPC1769\src\src\feature\bedlevel\mbl\mesh_bed_leveling.cpp.o
Compiling .pio\build\LPC1769\src\src\feature\bedlevel\ubl\ubl.cpp.o
Compiling .pio\build\LPC1769\src\src\feature\bedlevel\ubl\ubl_G29.cpp.o
Compiling .pio\build\LPC1769\src\src\feature\bedlevel\ubl\ubl_motion.cpp.o
Compiling .pio\build\LPC1769\src\src\feature\binary_protocol.cpp.o
Compiling .pio\build\LPC1769\src\src\feature\bltouch.cpp.o
Compiling .pio\build\LPC1769\src\src\feature\cancel_object.cpp.o
Compiling .pio\build\LPC1769\src\src\feature\caselight.cpp.o
**Marlin\src\HAL\LPC1768\HAL_SPI.cpp:216:6: error: no declaration matches 'void SPIClass::beginTransaction(SPISettings)'
  216 | void SPIClass::beginTransaction(SPISettings cfg) {
      |      ^~~~~~~~
In file included from Marlin\src\HAL\LPC1768\HAL_SPI.cpp:52:
Marlin\src\HAL\LPC1768\include/SPI.h:42:10: note: candidate is: 'void SPIClass::beginTransaction(const SPISettings&)'
   42 |     void beginTransaction(const SPISettings&);
      |          ^~~~~~~~~~~~~~~~
Marlin\src\HAL\LPC1768\include/SPI.h:39:7: note: 'class SPIClass' defined here
   39 | class SPIClass {
      |       ^~~~~~~~
Compiling .pio\build\LPC1769\src\src\feature\closedloop.cpp.o
*** [.pio\build\LPC1769\src\src\HAL\LPC1768\HAL_SPI.cpp.o] Error 1
============================================================ [FAILED] Took 4.89 seconds ============================================================**

Environment               Status    Duration
------------------------  --------  ------------
mega2560                  IGNORED
mega1280                  IGNORED
rambo                     IGNORED
FYSETC_F6_13              IGNORED
FYSETC_F6_14              IGNORED
sanguino644p              IGNORED
sanguino1284p             IGNORED
melzi                     IGNORED
melzi_optiboot            IGNORED
at90usb1286_cdc           IGNORED
at90usb1286_dfu           IGNORED
DUE                       IGNORED
DUE_USB                   IGNORED
DUE_debug                 IGNORED
DUE_archim                IGNORED
DUE_archim_debug          IGNORED
LPC1768                   IGNORED
LPC1769                   FAILED    00:00:04.893
STM32F103RC               IGNORED
STM32F103RC_fysetc        IGNORED
STM32F103RC_btt           IGNORED
STM32F103RC_btt_USB       IGNORED
STM32F103RC_btt_512K      IGNORED
STM32F103RC_btt_512K_USB  IGNORED
STM32F103RE               IGNORED
STM32F103RE_btt           IGNORED
STM32F103RE_btt_USB       IGNORED
STM32F4                   IGNORED
STM32F7                   IGNORED
ARMED                     IGNORED
STM32F103VE_GTM32         IGNORED
STM32F103VE_longer        IGNORED
mks_robin_mini            IGNORED
mks_robin_nano            IGNORED
mks_robin                 IGNORED
mks_robin_pro             IGNORED
mks_robin_e3              IGNORED
mks_robin_lite            IGNORED
mks_robin_lite3           IGNORED
jgaurora_a5s_a1           IGNORED
STM32F103CB_malyan        IGNORED
malyan_M300               IGNORED
chitu_f103                IGNORED
STM32F401VE_STEVAL        IGNORED
FLYF407ZG                 IGNORED
FYSETC_S6                 IGNORED
STM32F407VE_black         IGNORED
BIGTREE_SKR_PRO           IGNORED
BIGTREE_GTR_V1_0          IGNORED
BIGTREE_BTT002            IGNORED
teensy31                  IGNORED
teensy35                  IGNORED
esp32                     IGNORED
linux_native              IGNORED
SAMD51_grandcentral_m4    IGNORED
rumba32_f446ve            IGNORED
rumba32_mks               IGNORED
include_tree              IGNORED
======================================================= 1 failed, 0 succeeded in 00:00:04.893 =======================================================
The terminal process terminated with exit code: 1

Terminal will be reused by tasks, press any key to close it.
`

**Comment by hamster65** [comment] 2020-04-26 16:05
duplicate of https://github.com/MarlinFirmware/Marlin/issues/17724

**Comment by mochoandre** [comment] 2020-04-26 17:01
Sorry did not see that

**Comment by ellensp** [comment] 2020-04-27 03:20
Please close this issue.

**Comment by Talha909** [comment] 2020-04-27 07:52
How you slove this issue

**Comment by sjasonsmith** [comment] 2020-04-27 08:01
@Talha909 look at the pull request linked above. Only a few small changes are needed to fix it. Hopefully it will be merged soon.

**Comment by sjasonsmith** [comment] 2020-05-29 07:11
@mochoandre, this issue could be fixed. Can you verify with bugfix-2.0.x and close this issue?

**Comment by boelle** [comment] 2020-06-21 00:11
Lack of Activity
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.

**Closed as completed by boelle** 2020-06-21 00:11 UTC
