### ISSUE TITLE
[BUG] strange behavior with SD-card access on BTT v1.4

### ISSUE THREAD

**Issue by thomas374b** [MarlinFirmware/Marlin#19243] opened 2020-09-03 11:40 UTC
### Bug Description

When copying files from PC to the SD card via the USB-storage mechanism, those files can't be printed.
The reason is that two SD cards are independently accessed. Files copied via USB go to one SD-card. Marlin searches for files from the other.

The bug appears with Bigtreetech SKR v1.4 Turbo but it is probably not constraint to this board and might affect all configurations using a LPC176x CPU and platformio framework. 

### My Configurations

Marlin-2.0.x  or bugfix-2.0 branch, BigTreetech SKR v1.4 Turbo, external SD-card connected via LCD

### Steps to Reproduce

1. The external SD card needs to be configured in Configuration_adv.h
     #define    SDCARD_CONNECTION     LCD
2. recompile, flash, 
3. mount the external SD-card-reader
4. put two SD-cards into the system (one on the onboard-socket, one at the socket on the LCD)
5. reboot, connect USB to PC
6. in Marlin go to the "print files"-menu and look which files are visible
7. release SD-card via menu => should appear on the PC as external storage
8. look on the PC which files are visible on the recently added storage

**Expected behavior:** [What you expect to happen]

Same set of files should appear on both Marlin Print-Menu and PC USB-storage. 
Files should be copied to the card on the LCD. Since this is the configured SD-Card connection

**Actual behavior:** [What actually happens]

USB-storage shows files from the card in the onboard-socket. Marlin shows the files from the card on the LCD-socket.
Marlin can't print files that were copied from the PC via USB

#### Additional Information

The bug can be clearly identified by reviewing the code. There is redundant/duplicate code for accessing files.
Marlin takes the code from "src/sd/" subdirectory while the USB-Handler takes the code from the platformio framework
subdirctory "system/CMSIS/lib/chanfs" .

Access to onboard media is hardcoded in the platformio framework code.

If this is considered to be a feature, please remove the locking mechanism if external LCD is used. They don't share the same SPI interface on this architecture and therefore can work concurrently . There is no need to release the media.

**Comment by AnHardt** [comment] 2020-09-03 12:39
As far as i remember this is not a bug but kind of a feature.
It's about preventing writes from both sides, not knowing about each other, and potentially corrupting the file system. Since Marlins ancient sd-library can't do file- or directory-locks the used strategy is to make a kind of disk-lock - trying to prevent the different access channels have a chance to access at the same time.
It's also about to prevent situations like, Marlin is printing a file and the USB-MSD is trying to delete the file/directory.

Yes - it's crude.

**Comment by boelle** [comment] 2020-09-04 08:43
Configurations, please
Please ZIP up your `Configuration.h` and `Configuration_adv.h` files (as
requested in the Issue template) and drop them into your next reply.
We'll check them over and see if anything is amiss.

Please test the [`bugfix-2.0.x branch`](https://github.com/MarlinFirmware/Marlin/tree/bugfix-2.0.x) to see where it stands. If the problem has been resolved then we can close this issue. If the issue isn't resolved yet, then we should investigate further.

**Comment by boelle** [comment] 2020-09-15 20:22
no config's
template not followed
no response

closing

**Closed as completed by boelle** 2020-09-15 20:22 UTC

**Comment by thomas374b** [comment] 2020-09-17 14:23
> no config's
> template not followed
> no response
> 
> closing

Why did you close this ?

From my POV there is no need for any configuration.h file. And there is no need to test anything.

The BUG (or call it "feature") _will_ persist until the redundant code is removed (and this is not likely to happen).

The bug should be confirmed and left open for documentation purposes.

**Comment by sjasonsmith** [comment] 2020-09-17 15:05
Configuration files are required for all bugs, even if you don’t think they are needed. I disagree that you did not follow the template, you did far better than most, you just need to attach your configs.

As for copying files directly to the LCD SD, you can achieve this using the experimental binary protocol which can be enabled in Configuration.h. That is easy to do through Octoprint with the plugin available for it. Not so easy if you are copying from a host computer.

> please remove the locking mechanism if external LCD is used. They don't share the same SPI interface on this architecture and therefore can work concurrently . There is no need to release the media.

I’m willing to reopen the issue based on this, once you attach configs. This won’t be possible for all boards, but requiring manual acquire/release does seem incorrect in some cases. Since you have already been investigating I encourage you to contribute a pull request if you are able to devise a solution.

>The bug should be confirmed and left open for documentation purposes.

That’s not really what is done. Open bugs are things developers/volunteers need to actively look at and work on. If something will never be fixed it should not remain open. The greater the number of open bugs, the smaller the chance any particular bug will receive attention.

**Comment by thomas374b** [comment] 2020-09-17 16:51
[cfgs.zip](https://github.com/MarlinFirmware/Marlin/files/5240775/cfgs.zip)

OK, I agree the bug can be closed if someone states in the docs (maybe somewhere near SDCARD_CONNECTION in Configuration_adv.h) that

- using an external SD card connection(*) on LPC17xx based boards will produce this weird behaviour (i.e. files copied via USB-storage can't be printed since they are laying on a different card)

- ONLY use of internal (aka onboard) SD card connection is currently supported by Marlin when LPC176x-based board is used. This might be ruled out also in inc/Configuration_post.h by placing an appropriate assert (#undef, #warning #error) into it.

(*) SD card holder on LCD or custom defined SD-card SPI-pins

**Comment by thomas374b** [comment] 2020-09-17 17:05
[SD_warning.zip](https://github.com/MarlinFirmware/Marlin/files/5240903/SD_warning.zip)

> [...] Since you have already been investigating I encourage you to contribute a pull request if you are able to devise a solution.

OK, but give me some time on it. I will provide the asserts in Configuration_post.h to let the compiler spit out a warning if those settings are choosen.

May I send a simple diff for it ?
