### ISSUE TITLE
Incorrect filament width sensor calculation on 3.3v boards

### ISSUE THREAD

**Issue by feketeimre** [MarlinFirmware/Marlin#15121] opened 2019-08-31 19:20 UTC
### Description

Using the filament width sensor feature on a 3.3v analog input pin (For example on an LPC1768 board) results in an incorrect calculation of the filament diameter because of the follow line:

https://github.com/MarlinFirmware/Marlin/blob/85c82ab28e13cb25043ae166062785bff39434b9/Marlin/temperature.cpp#L1053-L1056

The multiplication with 5.0f volts is incorrect for 3.3v boards.

### Steps to Reproduce
0. This is for bugfix-2.0.x, not sure about the other branches.
1. Enable filament width sensor feature on a board that has 3.3v max analog input.
2. The reported filament width is incorrect.

**Expected behavior:** The reported filament diameter should be close to the correct value.

**Actual behavior:** The reported filament diameter is larger than the actual.

Should be an easy fix by dividing with the correct adc voltage instead of a constant 5.0f for example with a board specific defined constant. Except i dont know if this type of definition already exists in marlin. Creating one from scratch would be a huge task i feel.

**Comment by thisiskeithb** [comment] 2019-08-31 19:32
This is a duplicate of https://github.com/MarlinFirmware/Marlin/issues/14680

**Closed as completed** 2019-08-31 20:21 UTC
