### ISSUE TITLE
[BUG] Broken MP SCARA homing

### ISSUE THREAD

**Issue by gnmrc-s** [MarlinFirmware/Marlin#24075] opened 2022-04-23 12:59 UTC
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

Error while trying to home MP_SCARA

### Bug Timeline

old issue that people were able to solve with old marlin 2.0 variants

### Expected behavior

I expected it to home x than y and finally z

### Actual behavior

It homed only the z axis

### Version of Marlin Firmware

`bugfix-2.0.x`

### Printer model

Custom SCARA machine

### Electronics

creality v 4.2.7 board

### Add-ons

none

### Bed Leveling

MBL Manual Bed Leveling

### Your Slicer

Cura

[Configuration files.zip](https://github.com/MarlinFirmware/Marlin/files/8547358/Configuration.files.zip)

**Comment by ellensp** [comment] 2022-04-23 13:01
please update subject and attach your config files.

**Comment by ellensp** [comment] 2022-04-23 13:02
also what does a M119 say when no endstops are being triggered?

**Comment by gnmrc-s** [comment] 2022-04-23 14:01
M119 command says open endstops
I also tried an old configuration with an older bugfix 2.0 that I have compiled, in that configuration motors move but x and y endstops aren't  working while homing.
The old configuration uses the "how to mechatronic" SCARA laser engraver turn around method.

**Comment by thisiskeithb** [comment] 2022-04-23 14:47
Homing has been broken since 1.x: https://github.com/MarlinFirmware/Marlin/issues/10089

**Comment by thisiskeithb** [comment] 2022-04-23 14:47
Duplicate of https://github.com/MarlinFirmware/Marlin/issues/10089

**Closed as completed by thisiskeithb** 2022-04-23 14:47 UTC
Labels: K: SCARA

**Comment by gnmrc-s** [comment] 2022-04-23 14:52
I've read the other bug and it's not the same.
And also other people have made marlin 2.0 homing work.

**Comment by gnmrc-s** [comment] 2022-04-23 14:53
https://github.com/MarlinFirmware/Marlin/issues/20764

**Comment by thisiskeithb** [comment] 2022-04-23 14:54
> https://github.com/MarlinFirmware/Marlin/issues/10089

That's the long-standing "homing doesn't work on SCARA" thread, so let's use that.

**Comment by gnmrc-s** [comment] 2022-04-25 14:00
I've made a post about this problem on #10089, please when you have time go and check it out, it's 2 months tham I'm struggling trying to home my SCARA.
