### ISSUE TITLE
[BUG] Z = 1 after G28 on delta

### ISSUE THREAD

**Issue by Glodigit** [MarlinFirmware/Marlin#15495] opened 2019-10-09 10:33 UTC
I git pulled the latest 2.0 and after G28 on my delta, the Z height is set to 1mm instead of the delta height.

### Steps to Reproduce

1. Pull latest marlin
2. Send G28

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/3706821/Configuration.zip)

**Comment by tincatinca** [comment] 2019-10-09 15:46
Strange because I came on here because I have the same problem except my Z = 5 been using ver 2 successfully for 2 weeks but now has developed this problem

**Comment by Glodigit** [comment] 2019-10-09 16:26
Ok I've determined that the Z is correct when bed levelling is turned "Off". When it is turned back on again and auto homed, Z = 1 again.

**Comment by tvixen** [comment] 2019-10-10 08:37
Seems to be the same issue as #15494
You could try the dev-2.1.x version.

**Comment by Glodigit** [comment] 2019-10-10 12:24
Updated to dev 2.1 with the same issues.

**Comment by Studna3D** [comment] 2019-10-10 16:58
I have the same problem after bed leveling. When I start printing, runs G28 and G29, but after Z axis not moving, it's only Z=5 over the bed and prints only at this height.

**Comment by RMN9** [comment] 2019-10-12 20:26
If we i #define AUTO_BED_LEVELING_**LINEAR**
G28 give Z 10 and then G29 give Z 10->1mm

If we i #define AUTO_BED_LEVELING_**BILINEAR**
G28 give Z 10 and then G29 give Z 10

**Comment by Glodigit** [comment] 2019-10-17 10:38
Plugged into MatterControl, I get X: -0.34 Y: -0.22 Z:1.00 with bed leveling on. With it off, I get X:0, Y:0, Z:230.94

**Comment by Glodigit** [comment] 2019-10-17 10:53
Looks like there's a sync_plan_position that causes the values to change.

[LP_print_log.txt](https://github.com/MarlinFirmware/Marlin/files/3738819/LP_print_log.txt)

**Comment by Evgeny-SPB** [comment] 2019-10-20 01:12
I have the same problem on prusa like printer. 
The problem is in "void Planner::apply_leveling(xyz_pos_t &raw)" in planner.cpp and concerns only ABL_PLANAR levelling (in my case 3 point levelling).
Function "apply_rotation_xyz(bed_level_matrix, d.x, d.y, raw.z);" always returns Z = 1.0

**Comment by Glodigit** [comment] 2019-10-21 14:11
#15610 seems to work. Now I need to get my TMC5160 to extrude so that I can see if bed levelling is applied.

**Comment by Evgeny-SPB** [comment] 2019-10-24 17:17
Issue is probably solved with PR #15636, which is already merged.

**Comment by boelle** [comment] 2019-10-26 12:22
will close this one as it prob fixed by https://github.com/MarlinFirmware/Marlin/pull/15636

we can always reopen

**Closed as completed by boelle** 2019-10-26 12:22 UTC
Labels: Bug: Confirmed !
