### ISSUE TITLE
[BUG] Layer shifting during the print

### ISSUE THREAD

**Issue by daniDevKr** [MarlinFirmware/Marlin#23257] opened 2021-12-04 16:53 UTC
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

During the print the layer is shifted by the machine.

### Bug Timeline

The bug has occurred with the latest version of the "Marlin2.0-Firmware"

### Expected behavior

I expected that the printed object have not shifted layers.

### Actual behavior

During the print the layer is shifted by the machine.

### Version of Marlin Firmware

Marlin 2.0.9.2

### Printer model

an home made machine

### Electronics

The machine have a "MKS Robin Nano V 1.2" as controller, A4988 stepper motor drivers, nema17 motors, BLTouch

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Cura

### Host Software

SD Card (headless)

### Additional information & file uploads

[configurations.zip](https://github.com/MarlinFirmware/Marlin/files/7654265/configurations.zip)
[model.zip](https://github.com/MarlinFirmware/Marlin/files/7654272/model.zip)
![1638635651709](https://user-images.githubusercontent.com/29796059/144717674-684f9f12-f141-489c-8703-3a0a393468d6.jpg)
![1638635651694](https://user-images.githubusercontent.com/29796059/144717688-5d4720db-3000-45d2-8903-b0fd6ad2113f.jpg)

**Comment by thisiskeithb** [comment] 2021-12-04 17:44
Duplicate of https://github.com/MarlinFirmware/Marlin/issues/22967

**Closed as completed by thisiskeithb** 2021-12-04 17:44 UTC
