### ISSUE TITLE
Compilation error if #define EXTRUDER_AUTO_FAN_SPEED not equal 255 on MKS GEN 1.4

### ISSUE THREAD

**Issue by oangelo** [MarlinFirmware/Marlin#11557] opened 2018-08-15 16:37 UTC
I am trying to use the digital pin 7 (MOSFET_D_PIN) of a MKS GEN 1.4 to control the fan, because I am using 24V to power a 12V fan, I need to set the fan speed to less than 255.
Using branch 1.1.x "bugfix" I am receiving this error:
```
In file included from sketch/fastio.h:50,
                 from sketch/HAL.h:33,
                 from sketch/MarlinConfig.h:39,
                 from sketch/G26_Mesh_Validation_Tool.cpp:27:
fastio_1280.h:118: error: non-constant condition for static assertion
 #define DIO7_PWM    &OCR4BL
                     ^
sketch/fastio.h:91:31: note: in expansion of macro 'DIO7_PWM'
 #define _GET_TIMER(IO)        DIO ## IO ## _PWM
                               ^~~
sketch/fastio.h:103:31: note: in expansion of macro '_GET_TIMER'
 #define GET_TIMER(IO)         _GET_TIMER(IO)
                               ^~~~~~~~~~
sketch/SanityCheck.h:1364:19: note: in expansion of macro 'GET_TIMER'
     static_assert(GET_TIMER(E0_AUTO_FAN_PIN), "E0" AF_ERR_SUFF);
                   ^~~~~~~~~
fastio_1280.h:118: error: reinterpret_cast from integer to pointer
 #define DIO7_PWM    &OCR4BL
                     ^
sketch/fastio.h:91:31: note: in expansion of macro 'DIO7_PWM'
 #define _GET_TIMER(IO)        DIO ## IO ## _PWM
                               ^~~
sketch/fastio.h:103:31: note: in expansion of macro '_GET_TIMER'
 #define GET_TIMER(IO)         _GET_TIMER(IO)
                               ^~~~~~~~~~
sketch/SanityCheck.h:1364:19: note: in expansion of macro 'GET_TIMER'
     static_assert(GET_TIMER(E0_AUTO_FAN_PIN), "E0" AF_ERR_SUFF);
                   ^~~~~~~~~
exit status 1
non-constant condition for static assertion
```

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

#### Additional Information

* Include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/contributing.md#how-can-i-contribute) for additional guidelines.

**Comment by thinkyhead** [comment] 2018-08-21 15:43
Duplicate of #11468

**Closed as completed by thinkyhead** 2018-08-21 15:43 UTC
