### ISSUE TITLE
[BUG] (2.0.6) FILAMENT_RUNOUT_SENSOR/NOZZLE_PARK_FEATURE issue

### ISSUE THREAD

**Issue by wolfgangmauer** [MarlinFirmware/Marlin#19057] opened 2020-08-17 18:33 UTC
### Bug Description

With a filament change, filament is unloaded and loaded, move back do original position and start nozzle heating.
This will ruin the print !!!

### My Configurations
[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/5086146/Marlin.zip)
### Steps to Reproduce

1. Filament runout

**Expected behavior:** [What you expect to happen]
Go to park position, unload, load, **nozzle heating, return to print position**, continue printing.

**Actual behavior:** [What actually happens]
Go to park position, unload, load, **return to print position, nozzle heating**, continue printing.

**Comment by thisiskeithb** [comment] 2020-08-17 18:36
Duplicate of https://github.com/MarlinFirmware/Marlin/issues/19033

**Comment by thisiskeithb** [comment] 2020-08-17 18:37
This behavior was changed in the latest `bugfix-2.0.x`.

**Closed as completed by thisiskeithb** 2020-08-17 18:36 UTC
