### ISSUE TITLE
[BUG] Robin Nano v1.2 with Marlin Color UI display mirrored (left/right) on 3.2 screen

### ISSUE THREAD

**Issue by alexeyzel** [MarlinFirmware/Marlin#19834] opened 2020-10-21 09:40 UTC
### Bug Description

After installing the latest Marlin release 2.0.7.2 on my Flsun Q5 with MKS Robin Nano v1.2 board with 3.2-inch screen I get my screen flipped (mirrored) horizontally.

### My Configurations

[Config.zip](https://github.com/MarlinFirmware/Marlin/files/5414866/Config.zip)
### Steps to Reproduce

1. Install Marlin via SD card
2. Try to turn printer off and on again

**Expected behavior:** 
Normal screen position.

**Actual behavior:** 
Screen is flipped horizontally.
#### Additional Information
May be related to https://github.com/MarlinFirmware/Marlin/issues/19603 but in my case printer rebooting don't help.
Looks like this:
![121998302_634143467227245_6366863072250752205_n](https://user-images.githubusercontent.com/50808386/96702210-35985880-139a-11eb-857f-5c88aa6baf85.jpg)

**Comment by ellensp** [comment] 2020-10-21 09:43
Please test the [`bugfix-2.0.x` branch](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.0.x.zip) to see where it stands. If the problem has been resolved then we can close this issue. If the issue isn't resolved yet, then we should investigate further.

**Comment by alexeyzel** [comment] 2020-10-21 09:48
Thank you, I will test it today and write back.

**Comment by thisiskeithb** [comment] 2020-10-21 09:48
The `bugfix-2.0.x` branch has a `MKS_ROBIN_TFT32` define now and you shouldn't need to modify your pins file.

**Comment by alexeyzel** [comment] 2020-10-21 10:39
Tested in bugfix-2.0.x - screen is aligned properly. Thank you!

**Comment by boelle** [comment] 2020-10-21 15:13
@alexeyzel if problem solved please click green close button

**Closed as completed** 2020-10-21 18:16 UTC
