### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by notsatisfied** [MarlinFirmware/Marlin#9583] opened 2018-02-11 05:05 UTC
### Bug Report
I can run any commands through pronterface, but I cannot get Marlin with ramps 1.4 and an arduino mega to actualy start printing. 

Load obj stl or gcode file into pronterface, press begin printing after slicing is complete through slicer. Printer runs homing and stops, heating is complete and stays hot. does nothing else for hours.

[config files.zip](https://github.com/MarlinFirmware/Marlin/files/1714052/config.files.zip)

**Comment by Lyr3x** [comment] 2018-02-11 19:15
did you tried to print via sd-card?

**Comment by notsatisfied** [comment] 2018-02-12 00:53
I have not as I positioned pieces of my printer in a not so bright way where my bed would clip the sd card in its movement during the print

**Comment by Lyr3x** [comment] 2018-02-12 08:35
Maybe you should try this First to be sure that the problem isnt just pronterface or sth else. 

Also: your issue title isnt very specific. When you open an issue there is a template for bug reports

**Comment by notsatisfied** [comment] 2018-02-12 23:32
sorry about that, I thought thats what it meant in the template.  I just talked to a coworker today who said it may be issues with waiting for the heated bed to reach temperature. I will try this, and if it does not fix the issue I will dismount the lcd and print from sd.

**Comment by Lyr3x** [comment] 2018-02-13 10:15
no problem 👍 also it will be helpful if you provide some more information about your printer :)

**Comment by thinkyhead** [comment] 2018-02-20 09:59
Please test with the latest `bugfix-1.1.x` (and/or `bugfix-2.0.x`) branch to see where it stands. If the problem has been resolved then we can close this issue. If you still see the bad behavior we should investigate further.

**Comment by boelle** [comment] 2019-02-20 01:06
@notsatisfied Please test with the latest `bugfix-2.0.x`

**Comment by boelle** [comment] 2019-03-06 11:23
@thinkyhead i think we can close this one

**Comment by boelle** [comment] 2019-06-22 09:47
@thinkyhead Another one that needs to be closed. Sorry, I got bored.

**Closed as completed** 2019-07-06 04:28 UTC
Labels: T: Question
