### ISSUE TITLE
Add BigTreeTech SKR 1.4 Turbo 

### ISSUE THREAD

**Issue by Docomar750** [MarlinFirmware/Marlin#16484] opened 2020-01-06 19:49 UTC
Hi 
Can the BigTreeTech SKR 1.4 Turbo be added to Marlin it uses the same pins as a standard 1.4 board but uses a LPC1769 chip (120mhz)

Cheers

Darren

**Comment by tatusah** [comment] 2020-01-06 19:55
Already there, set environment as LPC1769 in platformio.ini

**Comment by thisiskeithb** [comment] 2020-01-06 21:45
This is a dupe of https://github.com/MarlinFirmware/Marlin/issues/16324, but as noted above this board has already been added.

**Comment by boelle** [comment] 2020-01-06 22:46
board has been added and this is a dube of #16324, closing

**Closed as completed by boelle** 2020-01-06 22:46 UTC

**Comment by stantond** [comment] 2020-02-05 18:11
I've just had the same problem, though rather than "add the SKR 1.4 Turbo board", it's "make it clear that the SKR 1.4 Turbo board is supported". It's listed as a MOTHERBOARD option, but it would be really helpful to have SKR 1.3/1.4/1.4 Turbo added to the platform.ini file as comments above their appropriate environment options. Currently, searching for SKR in platform.ini shows several other BTT boards, but the boards I've listed aren't listed, so it does give the impression that, by their absence, they're not fully supported. Although I now know this isn't the case, it would save other users moving to these boards some time.
