### ISSUE TITLE
[BUG] Changes in pins.h/pins_RAMPS.h breaks pin mapping for MSK GEN L

### ISSUE THREAD

**Issue by drug123** [MarlinFirmware/Marlin#23478] opened 2022-01-08 19:52 UTC
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

Default pin mapping for heaters and fan on MKS GEN L V1.0 in 2.0.9.2 and earlier was corresponding to silkscreen on the board as the following:
- E0 = 10
- E1 = 7
- BED = 8
- FAN = 9
Default mapping in the 2.0.9.3 (incl. bugfix) is the following:
- E0 = 10
- E1 = 9
- BED = 8
- FAN = 4
This leads to improper functioning of existing builds and the absence of a proper connector on D9 makes an impossible to connect a second extruder to the board w/o modifying the code.

### Bug Timeline

2.0.9.3

### Expected behavior

Mapping should be as in prev. version:
- E0 = 10
- E1 = 7
- BED = 8
- FAN = 9

### Actual behavior

Default mapping in the 2.0.9.3 (incl. bugfix) is the following:
- E0 = 10
- E1 = 9
- BED = 8
- FAN = 4

### Steps to Reproduce

N/A

### Version of Marlin Firmware

2.0.9.3

### Printer model

Creality Ender 3

### Electronics

MKS GEN L

### Add-ons

Custom dual extruder

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Simplify3D

### Host Software

OctoPrint

**Comment by ellensp** [comment] 2022-01-08 23:56
This looks to work from my testing

In Marlin/src/pins/ramps/pins_MKS_GEN_L.h

delete 
#define MOSFET_D_PIN 7

add
#define MOSFET_B_PIN 7
#define MOSFET_C_PIN 8
#define FAN_PIN 9

**Comment by drug123** [comment] 2022-01-09 00:20
@ellensp thanks, as a temporary fix for myself I had to add a board check in pins.h to disable FET_ORDER_ defines:
`#if !defined BOARD_MKS_GEN_L
  #if NONE(FET_ORDER_EEF, FET_ORDER_EEB, FET_ORDER_EFF, FET_ORDER_EFB, FET_ORDER_SF)`

**Comment by borland1** [comment] 2022-01-09 18:19
In `Configuration_adv.h` have enabled

```
#define FAN_PIN -1
#define E0_AUTO_FAN_PIN 9 
```

 so there is no difference if I change in pins file pins_MKS_GEN_L.h, from

`line 38   #define MOSFET_D_PIN 7`
to
`line 38   #define MOSFET_D_PIN 9`

However if I change to

`line 38   #define FAN_PIN 9`

I get a complier error in PlatformIO.   `"You cannot set E0_AUTO_FAN_PIN equal to FAN_PIN"`

Why is that?

My `Configuration.h` :

```
#define MOTHERBOARD BOARD_MKS_GEN_L
#define IS_RAMPS_EFB
```

**Comment by drug123** [comment] 2022-01-09 18:57
@borland1 This is totally unrelated to described bug.

PS: You have an issue because you confusing Extruder Fan and Cooling Fan. They cannot be connected to the same pin. If you wish to use auto fan feature you should have only one extruder (this is the case OPPOSITE to described setup) and connect extruder fan to E1 connector on MKS GEN_L and then use `#define E0_AUTO_FAN_PIN`. Also do not change MOSFET_D_PIN value, IS_RAMPS_EFB should be enough.

**Comment by ellensp** [comment] 2022-01-09 23:41
@borland1 FAN_PIN is a gcode controlled fan (ie M106/M107) can be turn on/off at any time.
E0_AUTO_FAN_PIN is an auto fan, turns when hotend is over a certain temperature.
These are mutually exclusive functions.

**Comment by descipher** [comment] 2022-01-16 04:12
> IS_RAMPS_EFB

IS_RAMPS_EFB is now FET_ORDER_EFB

**Comment by borland1** [comment] 2022-01-16 04:35
>  IS_RAMPS_EFB is now FET_ORDER_EFB

Yes,  thanks.  Still on v2.07.2, but will change that when updating to later version.

**Comment by Charmandrigo** [comment] 2022-03-01 03:40
This issue also affected the MKS Gen 1.4, fans stopped working on this update,
the temporal fix from ellensp brought back the function

**Comment by thinkyhead** [comment] 2022-04-10 11:33
Please test the [`bugfix-2.0.x` branch](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.0.x.zip) to see where this stands. If the problem has been resolved then we can close this issue. If the issue isn't resolved yet, then we should investigate further.

**Comment by thisiskeithb** [comment] 2023-04-20 15:50
Fixed in https://github.com/MarlinFirmware/Marlin/pull/25717

**Closed as completed by thisiskeithb** 2023-04-20 15:50 UTC
Labels: Bug: Confirmed !, C: Boards/Pins
