### ISSUE TITLE
Problems with Z offset using Bilinear auto bed leveling option Marlin V1.1.0

### ISSUE THREAD

**Issue by Part0** [MarlinFirmware/Marlin#6641] opened 2017-05-08 13:08 UTC
Hi,
I’m having problems with the Bilinear auto bed levelling. Having set up auto levelling and attempt to run a print, I can see that the autoleveling is working in that the Z axis is constantly correcting within each layer but the first layer height results with auto levelling is worse than I can achieve by manually adjusting my four bed screws. Below is the output from tests run. All the steps below were done in direct sequence as listed. 

My printer is a hybrid cnc type Cartesian, running Marlin firmware 1.1.0. Electronics is Generation 7 1.5 board. I’m using an infrared proximity sensor EE-SPY402 for the Z probe. Slicer is Simplify 3D. I had the same problems with RC8. I have added questions at the appropriate point in the output below. I have attached my config files at the end.

<details><summary>Log 1</summary>

```
SENT: M501
READ: echo:V37 stored settings retrieved (517 bytes)
V37 stored settings retrieved (517 bytes)
READ: echo:  G21 ; Units in mm
G21 ; Units in mm
READ: echo:Filament settings: Disabled
Filament settings: Disabled
READ: echo:  M200 D3.00
M200 D3.00
READ: echo:  M200 D0
M200 D0
READ: echo:Steps per unit:
Steps per unit:
READ: echo:  M92 X11.94 Y13.93 Z500.00 E129.70
M92 X11.94 Y13.93 Z500.00 E129.70
READ: echo:Maximum feedrates (units/s):
Maximum feedrates (units/s):
READ: echo:  M203 X300.00 Y300.00 Z5.00 E25.00
M203 X300.00 Y300.00 Z5.00 E25.00
READ: echo:Maximum Acceleration (units/s2):
Maximum Acceleration (units/s2):
READ: echo:  M201 X3000 Y3000 Z100 E10000
M201 X3000 Y3000 Z100 E10000
READ: echo:Acceleration (units/s2): P<print_accel> R<retract_accel> T<travel_accel>
Acceleration (units/s2): P<print_accel> R<retract_accel> T<travel_accel>
READ: echo:  M204 P500.00 R3000.00 T500.00
M204 P500.00 R3000.00 T500.00
READ: echo:Advanced: S<min_feedrate> T<min_travel_feedrate> B<min_segment_time_ms> X<max_xy_jerk> Z<max_z_jerk> E<max_e_jerk>
Advanced: S<min_feedrate> T<min_travel_feedrate> B<min_segment_time_ms> X<max_xy_jerk> Z<max_z_jerk> E<max_e_jerk>
READ: echo:  M205 S0.00 T0.00 B20000 X5.00 Y5.00 Z0.40 E5.00
M205 S0.00 T0.00 B20000 X5.00 Y5.00 Z0.40 E5.00
READ: echo:Home offset:
Home offset:
READ: echo:  M206 X0.00 Y0.00 Z0.00
M206 X0.00 Y0.00 Z0.00
READ: echo:Auto Bed Leveling:
Auto Bed Leveling:
READ: echo:  M420 S0 Z0.00
M420 S0 Z0.00
READ: echo:PID settings:
PID settings:
READ: echo:  M301 P15.00 I0.68 D52.99
M301 P15.00 I0.68 D52.99
READ: echo:  M304 P76.44 I3.17 D461.06
M304 P76.44 I3.17 D461.06
READ: echo:Z-Probe Offset (mm):
Z-Probe Offset (mm):
READ: echo:  M851 Z-5.80
M851 Z-5.80
SENT: G28
READ: X:0.00 Y:0.00 Z:15.80 E:0.00 Count X:0 Y:0 Z:7900
READ: echo:endstops hit:  Z:5.80
endstops hit:  Z:5.80
SENT: G29 V4
READ: G29 Auto Bed Leveling
READ: Bed X: 15.000 Y: 38.000 Z: 1.938
READ: Bed X: 56.000 Y: 38.000 Z: 1.990
READ: Bed X: 97.000 Y: 38.000 Z: 1.726
READ: Bed X: 138.000 Y: 38.000 Z: 2.028
READ: Bed X: 179.000 Y: 38.000 Z: 1.732
READ: Bed X: 179.000 Y: 73.000 Z: 1.972
READ: Bed X: 138.000 Y: 73.000 Z: 2.012
READ: Bed X: 97.000 Y: 73.000 Z: 1.954
READ: Bed X: 56.000 Y: 73.000 Z: 1.650
READ: Bed X: 15.000 Y: 73.000 Z: 1.092
READ: Bed X: 15.000 Y: 108.000 Z: 1.756
READ: Bed X: 56.000 Y: 108.000 Z: 1.410
READ: Bed X: 97.000 Y: 108.000 Z: 1.754
READ: Bed X: 138.000 Y: 108.000 Z: 1.572
READ: Bed X: 179.000 Y: 108.000 Z: 2.036
READ: Bed X: 179.000 Y: 143.000 Z: 1.180
READ: Bed X: 138.000 Y: 143.000 Z: 1.404
READ: Bed X: 97.000 Y: 143.000 Z: 1.678
READ: Bed X: 56.000 Y: 143.000 Z: 1.812
READ: Bed X: 15.000 Y: 143.000 Z: 1.690
READ: Bed X: 15.000 Y: 178.000 Z: 0.940
READ: Bed X: 56.000 Y: 178.000 Z: 1.358
READ: Bed X: 97.000 Y: 178.000 Z: 1.220
READ: Bed X: 138.000 Y: 178.000 Z: 1.444
READ: Bed X: 179.000 Y: 178.000 Z: 0.468
READ: Bilinear Leveling Grid:
READ:       0      1      2      3      4
READ:  0 +1.938 +1.990 +1.726 +2.028 +1.732
READ:  1 +1.092 +1.650 +1.954 +2.012 +1.972
READ:  2 +1.756 +1.410 +1.754 +1.572 +2.036
READ:  3 +1.690 +1.812 +1.678 +1.404 +1.180
READ:  4 +0.940 +1.358 +1.220 +1.444 +0.468
READ: X:179.00 Y:142.00 Z:14.60 E:0.00 Count X:2137 Y:1978 Z:7900
SENT: M114
READ: X:179.00 Y:142.00 Z:14.60 E:0.00 Count X:2137 Y:1978 Z:7900
```
</details>

This is where I’m confused. My questions are 
- I would have expected the matrix of values resulting from G29 to be close to Zero. Does the output matrix above not represent the Z endstop position to which the Z offset is then applied??
- What is the significance of values I got close to +2mm? 
- The last value in the matrix above is +0.463 taken at X179.00 Y142.00 with a reported Z value of 14.60 yet the count is reported as 7900. My Z axis has 500 counts /mm. A count of 7900 should result in a reported vertical height of 7900/500= 15.8mm which is what I would expect. 7900 count is the result I got after running G28 when the Z height was reported as 15.8 mm above the bed but here it is different. Can someone explain why???

I then tried testing the probe repeatability at the above XY position.

<details><summary>Log 2</summary>

```
SENT: M48 P20 V4
READ: M48 Z-Probe Repeatability Test
READ: Positioning the probe...
READ: Bed X: 179.000 Y: 178.000 Z: 0.484
READ: 1 of 20: z: 0.466 mean: 0.4660 sigma: 0.000000 min: 0.466 max: 0.466 range: 0.000
READ: 2 of 20: z: 0.520 mean: 0.4930 sigma: 0.027000 min: 0.466 max: 0.520 range: 0.054
READ: 3 of 20: z: 0.514 mean: 0.5000 sigma: 0.024166 min: 0.466 max: 0.520 range: 0.054
READ: 4 of 20: z: 0.492 mean: 0.4980 sigma: 0.021213 min: 0.466 max: 0.520 range: 0.054
READ: 5 of 20: z: 0.484 mean: 0.4952 sigma: 0.019783 min: 0.466 max: 0.520 range: 0.054
READ: 6 of 20: z: 0.532 mean: 0.5013 sigma: 0.022676 min: 0.466 max: 0.532 range: 0.066
READ: 7 of 20: z: 0.508 mean: 0.5023 sigma: 0.021123 min: 0.466 max: 0.532 range: 0.066
READ: 8 of 20: z: 0.484 mean: 0.5000 sigma: 0.020664 min: 0.466 max: 0.532 range: 0.066
READ: 9 of 20: z: 0.518 mean: 0.5020 sigma: 0.020287 min: 0.466 max: 0.532 range: 0.066
READ: 10 of 20: z: 0.490 mean: 0.5008 sigma: 0.019580 min: 0.466 max: 0.532 range: 0.066
READ: 11 of 20: z: 0.538 mean: 0.5042 sigma: 0.021515 min: 0.466 max: 0.538 range: 0.072
READ: 12 of 20: z: 0.492 mean: 0.5032 sigma: 0.020872 min: 0.466 max: 0.538 range: 0.072
READ: 13 of 20: z: 0.516 mean: 0.5042 sigma: 0.020343 min: 0.466 max: 0.538 range: 0.072
READ: 14 of 20: z: 0.500 mean: 0.5039 sigma: 0.019632 min: 0.466 max: 0.538 range: 0.072
READ: 15 of 20: z: 0.474 mean: 0.5019 sigma: 0.020376 min: 0.466 max: 0.538 range: 0.072
READ: 16 of 20: z: 0.490 mean: 0.5011 sigma: 0.019937 min: 0.466 max: 0.538 range: 0.072
READ: 17 of 20: z: 0.492 mean: 0.5006 sigma: 0.019461 min: 0.466 max: 0.538 range: 0.072
READ: 18 of 20: z: 0.462 mean: 0.4984 sigma: 0.020876 min: 0.462 max: 0.538 range: 0.076
READ: 19 of 20: z: 0.492 mean: 0.4981 sigma: 0.020370 min: 0.462 max: 0.538 range: 0.076
READ: 20 of 20: z: 0.524 mean: 0.4994 sigma: 0.020641 min: 0.462 max: 0.538 range: 0.076
READ: Finished!
READ: Mean: 0.499400 Min: 0.462 Max: 0.538 Range: 0.076
READ: Standard Deviation: 0.020641
READ: X:179.00 Y:142.00 Z:0.00 E:0.00 Count X:2137 Y:1978 Z:7900
SENT: M114
READ: X:179.00 Y:142.00 Z:0.00 E:0.00 Count X:2137 Y:1978 Z:7900
```
</details>

At this point, from a visual check the nozzle appeared to be about 15mm above the bed. (given that the count for Z above is 7900 this would come out at 15.8mm) I issued a G1 Z0 and the nozzle went to within approx. 2mm of the bed. I confirmed this value to be 1.5mm, by lowering the nozzle in steps of 0.1 mm towards the bed until I could just move a piece of paper under the nozzle. See below.

<details><summary>Log 3</summary>

```
SENT: G1 Z0
SENT: G91
SENT: G1 Z-0.100 F1200
SENT: G90
SENT: G91
SENT: G1 Z-0.100 F1200
SENT: G90
SENT: G91
SENT: G1 Z-0.100 F1200
SENT: G90
SENT: G91
SENT: G1 Z-0.100 F1200
SENT: G90
SENT: G91
SENT: G1 Z-0.100 F1200
SENT: G90
SENT: G91
SENT: G1 Z-0.100 F1200
SENT: G90
SENT: G91
SENT: G1 Z-0.100 F1200
SENT: G90
SENT: G91
SENT: G1 Z-0.100 F1200
SENT: G90
SENT: G91
SENT: G1 Z-0.100 F1200
SENT: G90
SENT: G91
SENT: G1 Z-0.100 F1200
SENT: G90
SENT: G91
SENT: G1 Z-0.100 F1200
SENT: G90
SENT: G91
SENT: G1 Z-0.100 F1200
SENT: G90
SENT: G91
SENT: G1 Z-0.100 F1200
SENT: G90
SENT: G91
SENT: G1 Z-0.100 F1200
SENT: G90
SENT: G91
SENT: G1 Z-0.100 F1200
SENT: G90
```
</details>

Sending `M114` at this point gave the following.
```
SENT: M114
READ: X:179.00 Y:142.00 Z:0.00 E:0.00 Count X:2137 Y:1978 Z:-148
```
-148/500 = -0.296mm????????
Hope someone can make sense of what’s going on here because I’m certainly confused.

[Config files.zip](https://github.com/MarlinFirmware/Marlin/files/983273/Config.files.zip)

**Comment by knobik** [comment] 2017-05-08 13:22
i have the same problem as you, doing G1 Z0 after G29 (everything preheated) then its moving to a good distance between bed and hotend, but as soon as i start printing, it looks like the mesh is inverted OR not active at all...

**Comment by tcm0116** [comment] 2017-05-08 21:50
> Does the output matrix above not represent the Z endstop position to which the Z offset is then applied??

It's not a matrix in the math-sense, but each number does represent the distance between the Z endstop position (Z=0) and the Z position at each point that was probed when the probe was triggered.

> What is the significance of values I got close to +2mm?

I suspect that when your probe is being triggered, the nozzle is roughly 2mm above the bed, which you appear to have confirmed:

> I issued a G1 Z0 and the nozzle went to within approx. 2mm of the bed.

There's a new feature in Configuration_adv.h called `BABYSTEP_ZPROBE_OFFSET`. If you enable it along with `BABYSTEPPING`, then you'll be able to adjust the Z-Offset in the Control/Motion menu on the LCD (or via the `M851 `command) and it will cause the nozzle to raise or lower accordingly. Here's the process I usually follow when first setting up the Z-Offset:

1. Heat the bed if you have a heated bed.
2. Set the Z-Offset to 0.0mm.
3. Run `G28 `and then `G29` to home and collect the leveling grid.
4. Move the nozzle to the center of the bed (`G1 X100 Y100 F6000`).
5. Incrementally lower the nozzle until you get to Z=0 or the nozzle touches the bed.
6. If the nozzle touches the bed, set the Z-Offset to the current Z position, which should raise the nozzle by that amount, and then repeat step 5.
7. If the nozzle is above the bed when Z=0, then decrease the Z-Offset until the nozzle grabs a piece of paper between it and the bed.
8. Print a test cube and adjust the Z-Offset during the first layer to perfection (don't forget to add G28 to your slicer's start G-Code after the G28).
9. Save settings.

**Comment by Part0** [comment] 2017-05-09 09:27
Thanks tcm0116 for the feedback. Can you try the sequence below on your printer with auto bed disabled and the Z probe as the Z end stop, which I take it is your setup. I'm running firmware V1.1.0

- Turn off Auto bed leveling with `M420 S0`. Not sure if this is necessary but just to be sure.
- Issue `G28` to home all axes.
- Send the Z axis nozzle to `Z0` with `G1 Z0` command. The nozzle moves to the correct height to print the first layer.
- Move to `X10`mm `Y10`mm and `Z10`mm.
- Send the Z axis nozzle to `Z0`. The nozzle moves to the correct height to print the first layer.
- Issue home Z only command `G28 Z0`.
- Send the Z axis nozzle to `Z0` with `G1 Z0` command. This time the nozzle moves to about 2mm above the glass ????????
- Issue `M114`. This gives the Z axis as 0. But it’s not.!!!!

I have only moved 10mm across the glass so there is no possibility that there is any change in bed height. 
Here's my printout in response to the sequence.
```
READ: ok
SENT: M420 S0
READ: echo:Bed Leveling Off
Bed Leveling Off
READ: ok
SENT: G28
READ: X:0.00 Y:0.00 Z:15.80 E:0.00 Count X:0 Y:0 Z:7900
READ: ok
READ: echo:endstops hit:  Z:5.80
endstops hit:  Z:5.80
SENT: G1 Z0
READ: ok
SENT: G1 X10 Y10 Z10 F1000
READ: ok
SENT: M114
READ: X:10.00 Y:10.00 Z:10.00 E:0.00 Count X:119 Y:139 Z:5000
READ: ok
SENT: G1 Z0
READ: ok
SENT: G28 Z0
READ: X:10.00 Y:10.00 Z:15.80 E:0.00 Count X:119 Y:139 Z:7900
READ: ok
READ: echo:endstops hit:  Z:5.80
endstops hit:  Z:5.80
SENT: G1 Z0
READ: ok
SENT: M114
READ: X:10.00 Y:10.00 Z:0.00 E:0.00 Count X:119 Y:139 Z:0
READ: ok
```

**Comment by thinkyhead** [comment] 2017-05-14 21:17
> I would have expected the matrix of values resulting from G29 to be close to Zero.

When the Z probe offset is well-tuned, that will be the case. If **every point** in the matrix is off by some minimum amount, then you need to adjust your Z probe Z offset by that amount.

Since every point in your mesh is at least 1mm, you may want to try `M851 Z-4.8`.

> infrared proximity sensor
> above the glass

Well that might be your problem. You should use `Z_SAFE_HOMING` and home near the middle of the bed to avoid any diffusion of reflected IR near the edge of the bed throwing off the sensor. If using a glass bed, put blue tape all over it, otherwise the IR will reflect from the _opposite side_ of the glass.

**Comment by Part0** [comment] 2017-05-15 14:08
Thanks thinkyhead for your comments.  Based on what you said I tried the following three tests ;
1) Run G29 with an A4 white printing paper sheet clipped on top of 6mm glass plate on heated bed.
READ: Bilinear Leveling Grid:
READ:       0      1      2      3      4
READ:  0 +0.338 +0.236 +0.324 +0.088 +0.098
READ:  1 +0.356 +0.130 +0.170 +0.084 +0.014
READ:  2 +0.168 +0.060 +0.202 +0.122 +0.122
READ:  3 -0.100 +0.016 +0.208 -0.016 +0.058
READ:  4 -0.062 +0.146 +0.212 +0.202 +0.082

2) Run G29 with A4 sheet under glass.
READ: Bilinear Leveling Grid:
READ:       0      1      2      3      4
READ:  0 +1.030 +1.116 +0.894 +0.918 +0.494
READ:  1 +0.676 +0.570 +0.982 +1.064 +0.982
READ:  2 +0.948 +0.574 +0.262 +0.552 +0.894
READ:  3 +0.544 +1.078 +0.822 +0.524 +0.238
READ:  4 +0.096 +0.606 +0.424 +0.854 -0.464

3) Rub G29 on bare glass plate.
READ: Bilinear Leveling Grid:
READ:       0      1      2      3      4
READ:  0 -2.268 -1.942 -2.278 -2.040 -2.350
READ:  1 -2.756 -2.408 -2.190 -1.988 -1.982
READ:  2 -2.356 -2.746 -2.320 -2.438 -1.998
READ:  3 -2.398 -2.206 -2.306 -2.574 -2.966
READ:  4 -3.142 -2.686 -2.826 -2.590 -3.548

Thanks for your help. Hopefully by covering my bed as you suggest this will solve my issues.

**Closed as completed** 2018-02-06 04:14 UTC
Labels: C: Configuration, F: Calibration
