### ISSUE TITLE
[FR] Almost all new Creality boards ship with GD32 processors. Please add official support.

### ISSUE THREAD

**Issue by Wreck-3D** [MarlinFirmware/Marlin#26005] opened 2023-06-22 03:21 UTC
### Is your feature request related to a problem? Please describe.

The various versions of the Ender 3 are the most common printer on the market by far, and the new models come with a GD32F303RET6 SOC instead of the STM32. Even BTT is using G32 processors on their boards now. Despite this, Marlin still does not support these boards. Can this please be fixed? I admit I'm far from an expert on coding, but it seems it would be fairly easy to do (I may be mistaken).

### Are you looking for hardware support?

Yes: GD32F303RET6 processor on Creality boards such as the v4.2.2

### Describe the feature you want

Support for **GD32F303RET6** on Creality boards (such as the 4.2.2). Currently Marlin does not work on these boards. Some people reported getting it to work with STM32 Maple, but this does not seem to always work (did not work for my printer).

**Comment by thisiskeithb** [comment] 2023-06-22 03:46
Duplicate of https://github.com/MarlinFirmware/Marlin/discussions/24985

**Closed as completed by thisiskeithb** 2023-06-22 03:46 UTC
Labels: T: Feature Request

**Comment by Wreck-3D** [comment] 2023-06-22 23:54
This is not a duplicate of #24985. For one, the boards were rare then, now GD32's are common, as in the #1 board shipping today. 2. he was requesting GD32F103RET6, this is a request for GDF**3**03RET6. Similar boards, but not the same. You are essentially just trying to silence requests for this. Why are you so against adding support for this? And you wonder why you struggle to even get 5 sponsors of Marlin?

**Comment by thisiskeithb** [comment] 2023-06-23 00:48
> You are essentially just trying to silence requests for this. 

We’re not silencing anyone. Please use that thread as the single place to discuss GD32 support. We don’t need multiple threads asking for every individual variant.

> Why are you so against adding support for this?

We’re not. Until someone submits a PR to add support, they won’t be fully supported.

**Comment by wclearyf5** [comment] 2023-06-23 02:28
A ? For programmers. Can and how do I change the firmware(g codet prevent the Zaxis home from lifting 10 mm after homing? Just asking. I want to learn tySent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Wreck-3D ***@***.***> Date: 6/22/23  7:55 PM  (GMT-05:00) To: MarlinFirmware/Marlin ***@***.***> Cc: Subscribed ***@***.***> Subject: Re: [MarlinFirmware/Marlin] [FR] Almost all new Creality boards ship with GD32 processors. Please add official support. (Issue #26005) 
This is not a duplicate of #24985. For one, the boards were rare then, now GD32's are common, as in the #1 board shipping today. 2. he was requesting GD32F103RET6, this is a request for GDF303RET6. Similar boards, but not the same. You are essentially just trying to silence requests for this. Why are you so against adding support for this? And you wonder why you struggle to even get 5 sponsors of Marlin?
