### ISSUE TITLE
[FR] Remining time in Color UI

### ISSUE THREAD

**Issue by ghost** [MarlinFirmware/Marlin#21215] opened 2021-02-27 17:35 UTC
I use color SPI (ili9341) display. When i enable TFT_CLASSIC_UI then is see the remaining time in display.
If i enable the TFT_COLOR_UI then is can not see the remaining time.

THX

**Comment by thisiskeithb** [comment] 2021-02-27 17:58
Duplicate of https://github.com/MarlinFirmware/Marlin/issues/19780

**Closed as completed by thisiskeithb** 2021-02-27 17:58 UTC
Labels: T: Feature Request
