### ISSUE TITLE
[BUG] Y and Z axis stop working after bed leveling

### ISSUE THREAD

**Issue by EzeKoren** [MarlinFirmware/Marlin#22338] opened 2021-07-11 22:35 UTC
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

After performing an `AUTO_BED_LEVELING_LINEAR`, be it from the LCD or from a `G29`, both Y and Z motors will stop responding. They're still powered and therefore cannot be moved by hand. X and E motors work just fine, and will operate without any issues. Y and Z motors will stop working until the mainboard (Arduino Mega with a RAMPS shield) is reset

### Bug Timeline

Between 2.0.8 and 2.0.9.2 release tags 

### Steps to Reproduce

1. Turn on the printer
2. Manually move the motors through the "Move axis" menu on the screen 
3. Home all axis
4. Manually move the motors again
5. Level bed using AUTO_BED_LEVELING_LINEAR

Up until this point, all motors operated normally, but any movement after the last probing point will not cause any movement on neither the Y and Z motors at all

### Version of Marlin Firmware

2.0.9.1

### Printer model

Anet A8

### Electronics

RAMPS 1.6, DRV8825 stepper motors

### Your Slicer

Simplify3D

### Host Software

OctoPrint

### Additional information & file uploads

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/6797768/Marlin.zip)

**Comment by ellensp** [comment] 2021-07-12 00:55
Duplicate of https://github.com/MarlinFirmware/Marlin/issues/22128

**Closed as completed by ellensp** 2021-07-12 00:55 UTC
