### ISSUE TITLE
Adjustment marlin 1.1.5 mini kossel inductive sensor

### ISSUE THREAD

**Issue by petitbrochet** [MarlinFirmware/Marlin#7848] opened 2017-10-05 11:23 UTC
bonjour
Après avoir installé marlin 1.1.5, fait l'autocalibration et avoir renté le décalage de la buse par rapport au capteur.
L'impression débute toujours a 2.48mm du plateau.
J'ai beau faire différent réglage mais toujours le même problème.
Qui pour m'aider?
Merci d'avance

**Comment by teemuatlut** [comment] 2017-10-05 16:12
In English? It'll be hard to help you if we don't know what you're saying.

**Comment by petitbrochet** [comment] 2017-10-05 18:35
Hello
After installing marlin 1.1.5, the autocalibration is performed and the nozzle offset relative to the sensor.
Printing always starts at 2.48mm from the tray.
Although I do different setting but still the same problem.
Who to help me?
thank you in advance

**Comment by petitbrochet** [comment] 2017-10-06 18:32
Good evening
person to help me?
Please

**Comment by thinkyhead** [comment] 2017-11-15 09:39
Sorry this issue was missed. It has been a very busy Autumn.

Please try `bugfix-1.1.x` and see if the issue is cleared up.

**Comment by boelle** [comment] 2019-02-19 21:49
@petitbrochet did you try the latest bugfix 2.0?

**Comment by boelle** [comment] 2019-03-06 10:51
@thinkyhead i think we can close this one

**Comment by Phr3d13** [comment] 2019-06-10 21:46
@thinkyhead Another one that needs to be closed. Sorry, I got bored.

**Comment by boelle** [comment] 2019-06-22 09:01
@thinkyhead Another one that needs to be closed. Sorry, I got bored.

**Comment by boelle** [comment] 2019-07-21 00:21
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.

**Closed as completed by boelle** 2019-07-21 00:21 UTC
