### ISSUE TITLE
Opt-in MarlinFirmware / Marlin repo to participate in Hacktoberfest?

### ISSUE THREAD

**Issue by Gamester17** [MarlinFirmware/Marlin#19629] opened 2020-10-05 20:43 UTC
Any plans to allow this MarlinFirmware Marlin repo to participate in Hacktoberfest to try to encourage more code pull requests? 

If so then this year you need to opt-in by classifying this repository with the hacktoberfest topic, see

https://hacktoberfest.digitalocean.com/hacktoberfest-update

Please also consider doing so with the MarlinFirmware Configurations repo as well:

https://github.com/MarlinFirmware/Configurations

Home Assistant core team has certainly embraced the concept and its project seems to have benefited from it for many years  👍

https://www.home-assistant.io/blog/2020/10/01/hacktoberfest-2020/

https://github.com/home-assistant/core/pulls?q=is%3Apr+is%3Aopen+label%3AHacktoberfest

https://github.com/home-assistant/frontend/pulls?q=is%3Apr+is%3Aopen+label%3Ahacktoberfest

https://github.com/home-assistant/home-assistant.io/pulls?q=is%3Apr+is%3Aopen+label%3AHacktoberfest

**Comment by thisiskeithb** [comment] 2020-10-05 20:50
I think we’re doing OK [without the spam](https://www.theregister.com/2020/10/01/digitalocean_hacktoberfest_pull_request_spam/) 🙂

**Comment by Gamester17** [comment] 2020-10-05 21:21
Reduced spam is the reason why they updated the labels, etc., read -> https://hacktoberfest.digitalocean.com/hacktoberfest-update

**Comment by ellensp** [comment] 2020-10-06 01:20
This is just more work the for the admin. waste of time. Not a bug report, not even a FR.closing.

**Closed as completed by ellensp** 2020-10-06 01:20 UTC
Labels: T: Question

**Comment by ellensp** [comment] 2020-10-06 01:30
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
