### ISSUE TITLE
Firmware retract not working with mixer setup

### ISSUE THREAD

**Issue by sangthip** [MarlinFirmware/Marlin#4752] opened 2016-09-02 10:27 UTC
Firmware retraction problem exists if using mixing setup  with 3 extruders.
problem if only using 2 extruders all 3 extruders retract but the one not being used will not recover the retracted amount where as the other two do.
This leads to the unused extruder being left with no filament and the other two forcing their filaments back up the unused side.

This causes under extrusion and massive clog ups thet need the hot end be disassembled to unblock them if it has been happening for some time.

I hope this explains the problem

**Comment by thinkyhead** [comment] 2016-09-02 11:53
That makes sense. So basically it sounds like I forgot to handle retract/recover properly in the implementation. I will look at this soon and patch it up asap.

BTW are you using `FWRETRACT`? Are you using `LIN_ADVANCE`? Have you tested the latest `RCBugFix` to see if the problem still exists?

**Comment by sangthip** [comment] 2016-09-02 12:35
I am using the latest Bugfix;  Please explain what LIN_ADVANCE does I have seen the option but have no idea how it works of if it will help so it has not been enabled.

**Comment by thinkyhead** [comment] 2016-09-02 12:41
LIN_ADVANCE decouples the E axis so that it is not linear-interpolated along with the XYZ axes, but instead operates to produce the right amount of material pressure at the proper instants. This prevents ooze at the end of lines and allows better extrusion at the start of lines.

**Comment by sangthip** [comment] 2016-09-02 13:55
Sounds usefull Ill enable , recompile test and get back to you when tested.. It may take a few days !

**Comment by sangthip** [comment] 2016-09-02 15:08
Back so soon... not good news
Enabling LIN_ADVANCE throws error on compile

```
Arduino: 1.6.9 (Mac OS X), Board: "Arduino/Genuino Mega or Mega 2560, ATmega2560 (Mega 2560)"

/var/folders/y2/jx1h1b7x11vf3nqcq422ds600000gn/T/build38ee351eb3f96c2b2cb8074b479b6407.tmp/sketch/stepper.cpp: In static member function 'static void Stepper::isr()':
stepper.cpp:397: error: 'counter_m' was not declared in this scope
             counter_m[j] += current_block->steps[E_AXIS];
             ^
Using library U8glib at version 1.19.1 in folder: /Volumes/Raptor/Documents/Arduino/libraries/U8glib 
exit status 1
'counter_m' was not declared in this scope
```

PS #define ADVANCE throws the same error

**Comment by thinkyhead** [comment] 2016-09-02 16:32
Hmm. Somehow half of the `counter_m` are called `counter_M`. Patching!

**Comment by sangthip** [comment] 2016-09-06 12:43
Immmm Back
This is weird.  enable LIN_ADVANCE or ADVANCE with FWRETRACT leads to nothing being extruded ??
Turn them off  FWRETRACT still on still works the same as when this was started (mixing extruder using 2 all 3 retract only 2 recover.
Turning off FWRETRACT with LIN_ADVANCE or ADVANCE also off, it prints 1 2 or 3 extrudes as mixing without problem

**Comment by thinkyhead** [comment] 2016-09-07 09:46
Sounds like it will be fun to figure out and fix. I hope I can find the time this week to look into it.

**Comment by boelle** [comment] 2016-11-02 13:53
@sangthip is the issue still present in the latest RCBugfix ?

**Comment by thinkyhead** [comment] 2016-11-03 02:46
I believe this is fixed now, but will await confirmation from @sangthip.
`LIN_ADVANCE` should also be more compatible now.

**Comment by boelle** [comment] 2016-11-11 20:45
@sangthip still with us ?

**Comment by boelle** [comment] 2016-11-19 14:30
@sangthip ??

**Comment by boelle** [comment] 2016-11-26 11:07
@thinkyhead 

since  @sangthip  have replied over the last 24 days can we safely assume that either the problem is fixed or he/she have lost interest?

**Closed as completed** 2016-11-26 12:01 UTC
Labels: Bug: Potential ?
