### ISSUE TITLE
[FR] EXTRUDER_AUTO_FAN_SPEED from console?

### ISSUE THREAD

**Issue by forkoz** [MarlinFirmware/Marlin#10807] opened 2018-05-21 11:23 UTC
I bought an 8CFM fan for printing at 250c+. For PLA I don't need all 8cfm. I could not find a command to set the fan speed from the console. Is there not one? It would sure be nice. Or maybe scale the fan with extruder temperature.

**Comment by braga-dev** [comment] 2018-05-22 12:30
You can use M106 to set fan speed, like "M106 S255" will set the fan speed to his maximum.

I believe new version of Cura does auto scale the fan with the layer height, I dont know if it does with extruder temperature

**Comment by braga-dev** [comment] 2018-05-23 09:34
I just noticed, are you talking about the piece blower or the extruder fan?

**Comment by forkoz** [comment] 2018-05-24 02:18
Extruder fan.

**Comment by thinkyhead** [comment] 2018-05-24 06:53
This feature does not exist at this time.

**Comment by ellensp** [comment] 2022-04-24 05:44
duplicate of https://github.com/MarlinFirmware/Marlin/issues/10280

**Closed as completed by ellensp** 2022-04-24 05:44 UTC
Labels: T: Feature Request
