### ISSUE TITLE
[FR] Dual Heat Bed Support

### ISSUE THREAD

**Issue by Shadeling3D** [MarlinFirmware/Marlin#7710] opened 2017-09-22 01:15 UTC
Building a printer driver board to run Marlin, I need support for 2 heat beds with Therm support please

**Comment by Shadeling3D** [comment] 2017-10-12 14:54
Under Pins.h:
```cpp
#define BED_PINS HEATER_BED_PIN, marlinAnalogInputToDigitalPin(TEMP_BED_PIN)

#define SENSITIVE_PINS { 0, 1, \
    X_STEP_PIN, X_DIR_PIN, X_ENABLE_PIN, X_MIN_PIN, X_MAX_PIN, \
    Y_STEP_PIN, Y_DIR_PIN, Y_ENABLE_PIN, Y_MIN_PIN, Y_MAX_PIN, \
    Z_STEP_PIN, Z_DIR_PIN, Z_ENABLE_PIN, Z_MIN_PIN, Z_MAX_PIN, Z_MIN_PROBE_PIN, \
    PS_ON_PIN, HEATER_BED_PIN, FAN_PIN, FAN1_PIN, FAN2_PIN, CONTROLLER_FAN_PIN, \
    _E0_PINS _E1_PINS _E2_PINS _E3_PINS _E4_PINS BED_PINS \
    _H0_PINS _H1_PINS _H2_PINS _H3_PINS _H4_PINS \
    _X2_PINS _Y2_PINS _Z2_PINS \
    X_MS1_PIN, X_MS2_PIN, Y_MS1_PIN, Y_MS2_PIN, Z_MS1_PIN, Z_MS2_PIN \
  }
```
would changing to the following help me? am I looking in the correct direction?
```cpp
#define BED_PINS HEATER_BED0_PIN, marlinAnalogInputToDigitalPin(TEMP_BED0_PIN)
#define BED_PINS HEATER_BED1_PIN, marlinAnalogInputToDigitalPin(TEMP_BED1_PIN)

#define SENSITIVE_PINS { 0, 1, \
    X_STEP_PIN, X_DIR_PIN, X_ENABLE_PIN, X_MIN_PIN, X_MAX_PIN, \
    Y_STEP_PIN, Y_DIR_PIN, Y_ENABLE_PIN, Y_MIN_PIN, Y_MAX_PIN, \
    Z_STEP_PIN, Z_DIR_PIN, Z_ENABLE_PIN, Z_MIN_PIN, Z_MAX_PIN, Z_MIN_PROBE_PIN, \
    PS_ON_PIN, HEATER_BED0_PIN, HEATER_BED1_PIN, FAN_PIN, FAN1_PIN, FAN2_PIN, CONTROLLER_FAN_PIN, \
    _E0_PINS _E1_PINS _E2_PINS _E3_PINS _E4_PINS BED_PINS \
    _H0_PINS _H1_PINS _H2_PINS _H3_PINS _H4_PINS \
    _X2_PINS _Y2_PINS _Z2_PINS \
    X_MS1_PIN, X_MS2_PIN, Y_MS1_PIN, Y_MS2_PIN, Z_MS1_PIN, Z_MS2_PIN \
  }
```

**Comment by thinkyhead** [comment] 2017-11-15 09:45
It would take a lot more than that to add support for 2 heated beds to Marlin. It is hard-coded to support only a single bed at this time.

**Comment by Shadeling3D** [comment] 2017-11-21 21:43
Thank you for the update, I'm leaving it as usable future expansion for now

**Comment by sjasonsmith** [comment] 2020-11-10 08:06
Duplicate of #5098

**Closed as completed by sjasonsmith** 2020-11-10 08:06 UTC
Labels: T: Feature Request

**Comment by sjasonsmith** [comment] 2020-11-29 22:33
Duplicate of #4112
