### ISSUE TITLE
[BUG] Printer keeps rebooting after upgrading to Marlin 2.1.2.1

### ISSUE THREAD

**Issue by andystoc** [MarlinFirmware/Marlin#26009] opened 2023-06-23 03:07 UTC
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Printer keeps rebooting after upgrading to the latest version of marlin.

### Bug Timeline

Constant reboot

### Expected behavior

.

### Actual behavior

.

### Steps to Reproduce

.

### Version of Marlin Firmware

2.1.2.1

### Printer model

artillery x1

### Electronics

SKR 2 / STM32F429

### Add-ons

bltouch 

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Cura

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/11843562/Marlin.zip)

**Comment by ellensp** [comment] 2023-06-23 03:13
English version: Printer keeps rebooting after upgrading to the latest version of marlin

### Bug Description

Printer keeps rebooting after upgrading to the latest version of marlin. It has a skr 2 f429 plate on it

**Comment by rq3** [comment] 2023-06-23 15:17
Sounds just like my bug report #25852.

**Comment by eoyilmaz** [comment] 2023-07-17 21:58
Is that rebooting on startup or rebooting while printing?

**Comment by rq3** [comment] 2023-08-03 22:19
> Is that rebooting on startup or rebooting while printing?

Re-boots every 3 seconds on start-up.

**Comment by thinkyhead** [comment] 2023-08-07 23:15
Duplicate of #25852

**Closed as completed by thinkyhead** 2023-08-07 23:15 UTC
