### ISSUE TITLE
[FR] Working NOZZLE_TO_PROBE_OFFSET when PROBE_MANUALLY and MESH_BED_LEVELING enabled.

### ISSUE THREAD

**Issue by kricud** [MarlinFirmware/Marlin#19381] opened 2020-09-13 18:10 UTC
Enable NOZZLE_TO_PROBE_OFFSET when using PROBE_MANUALLY with MESH_BED_LEVELING and LCD_BED_LEVELING, Probe offset would allow to use dial indicator for precise bed level measurements. Paper and feeler gauge are good but they are subjective and not repeatable.

Plan B would be to use Lever Dial Indicator with fixture that allows position measuring tip under nozzle. 
Nowhere close to elegant solution.

dial indicator: https://en.wikipedia.org/wiki/Indicator_(distance_amplifying_instrument)

**Comment by thisiskeithb** [comment] 2022-04-09 09:57
Duplicate of https://github.com/MarlinFirmware/Marlin/issues/17640

**Closed as completed by thisiskeithb** 2022-04-09 09:57 UTC
Labels: T: Feature Request
