### ISSUE TITLE
PLEASE CHECK LETEST MARLIN BUGFIX 2.0.X FOR MIXING EXTRUDER

### ISSUE THREAD

**Issue by nayim12** [MarlinFirmware/Marlin#22199] opened 2021-06-22 14:46 UTC
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

IN LETEST MARLIN-BUGFIX-2.0.X 
MIXING STEPPERS NOT WORKING 

### Version of Marlin Firmware

Marlin-bugfix-2.0.x

### Host Software

Pronterface

**Comment by ellensp** [comment] 2021-06-22 14:49
Duplicate of https://github.com/MarlinFirmware/Marlin/issues/22198

**Closed as completed by ellensp** 2021-06-22 14:49 UTC
