### ISSUE TITLE
Wrongly defined pins In file: pins_MKS_GEN_L.h 

### ISSUE THREAD

**Issue by tavi79** [MarlinFirmware/Marlin#25607] opened 2023-03-31 15:05 UTC
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

CONFIGURATION_H_VERSION 02010300
SHORT_BUILD_VERSION "bugfix-2.1.x"
STRING_DISTRIBUTION_DATE "2023-03-31"

Wrongly defined pins In file: pins_MKS_GEN_L.h 

#define MOSFET_A_PIN                           9  // HE0
#define MOSFET_B_PIN                           8  // HE1
#define MOSFET_C_PIN                          10  // HBED
#define FAN0_PIN                               7

to function properly I had to define:

#define MOSFET_A_PIN                          10  // HE0
#define MOSFET_B_PIN                           7  // HE1
#define MOSFET_C_PIN                           8  // HBED
#define FAN0_PIN                               9

### Version of Marlin Firmware

bugfix-2.1.x

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

**Comment by thisiskeithb** [comment] 2023-04-01 04:38
Which version of the Gen L do you have? It’d help if you could post clear / HD photos of the front and back of the board.

Also, please attach a ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

**Comment by tavi79** [comment] 2023-04-01 05:48
MKS Gen_L V1.0

On Sat, Apr 1, 2023 at 7:38 AM Keith Bennett ***@***.***>
![20230401_083959](https://user-images.githubusercontent.com/129529322/229268170-4b805a62-6c2b-4ede-b572-e52bb47fb16e.jpg)
[Conexiuni Placa de baza MKS GEN-L.pdf](https://github.com/MarlinFirmware/Marlin/files/11128540/Conexiuni.Placa.de.baza.MKS.GEN-L.pdf)

wrote:

**Comment by tavi79** [comment] 2023-04-01 05:54
![20230401_083959](https://user-images.githubusercontent.com/129529322/229268312-88855ffa-f592-406a-be23-cd2377c829a7.jpg)
[Conexiuni Placa de baza MKS GEN-L.pdf](https://github.com/MarlinFirmware/Marlin/files/11128551/Conexiuni.Placa.de.baza.MKS.GEN-L.pdf)
[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/11128552/Marlin.zip)

**Comment by tavi79** [comment] 2023-04-01 06:28
Symptoms: When I tried to heat the HE0 extruder, THERMAL PROTECTION Was Triggered

**Comment by sjasonsmith** [comment] 2023-04-01 16:08
MKS documentation agrees with the changes recommended here.

![image](https://user-images.githubusercontent.com/20053467/229301807-f15c9476-0772-4c57-ac67-71adf3bed3dd.png)

**Comment by sjasonsmith** [comment] 2023-04-01 16:55
Whatever is done for this should probably address and close #23478 at the same time.

**Comment by thisiskeithb** [comment] 2023-04-01 20:52
Duplicate of https://github.com/MarlinFirmware/Marlin/issues/23478

**Closed as completed by thisiskeithb** 2023-04-01 20:52 UTC
Labels: Bug: Potential ?, C: Boards/Pins
