### ISSUE TITLE
[BUG] MKS Robin tft V2.0 don't work

### ISSUE THREAD

**Issue by fizga** [MarlinFirmware/Marlin#15532] opened 2019-10-12 13:32 UTC
Hello, I have a problem with Robin TFT V2.0 (3.2'') connected to the motherboard MKS Robin 2.4 I use Marlin 2.0!  compilation is going well, I put the file Robin.bin on the SD card but when I turn on the screen shows the progress bar, it arrives at 100% then displays COMPLETE then it stays like that.  there is just a blue LED flashing on motherboard.

**Comment by boelle** [comment] 2019-10-12 14:31
where are your config files, the issue template says to attach them

**Comment by tpruvot** [comment] 2019-10-13 15:59
cp config/examples/Mks/Robin/Configuration* Marlin/

i guess... :p

**Comment by fizga** [comment] 2019-10-13 16:51
Sorry, I'm traveling this weekend, I'll give all the files tomorrow

**Comment by fizga** [comment] 2019-10-14 06:20
here are the files


[config.zip](https://github.com/MarlinFirmware/Marlin/files/3723166/config.zip)

**Comment by fizga** [comment] 2019-10-14 09:18
for more details, the blinking blue led is the one connected to PB2.

**Comment by tpruvot** [comment] 2019-10-14 19:48
yes, the heartbeat/watchdog led... Is there any other user of this mks robin able to flash and use a serial connection ? Still not shipped, after a week...

**Comment by boelle** [comment] 2019-10-14 20:00
you just love china stuff :-D
ni hao

**Comment by tpruvot** [comment] 2019-10-14 20:06
well, delivery time is another issue then, but that help a bit when they ship it without delay... first

**Comment by boelle** [comment] 2019-10-14 20:08
shipping is one thing
customer service is a city in the center of siberia
quality is sometimes a joke

**Comment by tpruvot** [comment] 2019-10-14 20:17
![image](https://user-images.githubusercontent.com/145119/66780124-55b45280-eed0-11e9-9e51-72172da201d4.png)

Louphoque...

**Comment by fizga** [comment] 2019-10-15 09:48
I tried again to upload by serial link but I still have an error.
yet when I look at serial port on platforio I see USB-SERIAL CH340
for the serial monitor the bauderate must be 250000?

**Comment by fizga** [comment] 2019-10-15 09:56
![screen2](https://user-images.githubusercontent.com/12665447/66821168-42da6600-ef42-11e9-90b3-af70ad47deca.png)
here what i have in serial monitor
and here when i try to upload 
![screen1](https://user-images.githubusercontent.com/12665447/66821517-d6ac3200-ef42-11e9-84ce-470854cf321e.png)

**Comment by boelle** [comment] 2019-10-24 22:12
are you sure this is not due to a bad made board? ie hardware failure?

**Comment by fizga** [comment] 2019-10-25 17:18
I'm sure that the hardware works, when I load the original firmware it works well but I am limited in options

https://github.com/makerbase-mks/MKS-Robin 

After installing marlin 2.0 I still have screen that does not work!  So I tried to communicate in serial with s3d and it works, I have a return of the temperatures

**Comment by github051** [comment] 2019-10-25 17:35
HI Fizga,
Can you share your entire marlin 2.0 complied folder ?

**Comment by tpruvot** [comment] 2019-10-25 19:04
ok, so its only a tft communication or init issue... i received it, but still have to wire some cables to make some backup with the stlink before... if its even possible... edit: ok wired but read protected sigh... well... forced to use a sdcard to update so

**Comment by tpruvot** [comment] 2019-10-25 19:58
so indeed, i can reproduce the issue... that stay on "Complete", heartbeat led is working, touchscreen also doing beeps when you click on the bottom of the screen, but nothing more displayed, look like some missing tft reset or such

**Comment by boelle** [comment] 2019-10-25 20:06
have changed labels to reflect this

**Comment by tpruvot** [comment] 2019-10-25 20:09
yep, uncommenting PF6 make a white screen, we can see the small reset trick on "menu enter/bottom right click", but initial data transfert may be problematic... will need more time to be able to debug that, trace some lcd id value over serial...

**Comment by tpruvot** [comment] 2019-10-25 22:50
so, for now, i can say the 3.2" TFT V2.0 is a ST7789V (0x8552 TFT Identifier)... Tried various changes on [original repo](https://github.com/makerbase-mks/MKS-Robin/blob/master/MKS%20Robin/firmware/Marlin2.0-MKS-Robin/Marlin/src/HAL/HAL_STM32F1/u8g_com_stm32duino_fsmc.cpp) (like reducing the init delay to 50ms, and changing the DMA2 channel CH4&CH5 so, to match the longer3D board, without issue... on their repo)

Touchscreen seems well calibrated by default... also... no issue about it, unrelated to the problem i think... so.

Its kinda weird there is not even a pixel changed, even on reinit...

**Comment by tpruvot** [comment] 2019-10-25 23:25
ok, i think i found the issue, -DSTM32_XL_DENSITY is not automatically set by the framework, unlike -DSTM32_HIGH_DENSITY

**Comment by tpruvot** [comment] 2019-10-25 23:49
fixed in PR #15675

![image](https://user-images.githubusercontent.com/145119/67610461-4caa6780-f793-11e9-80c7-3803f663acc4.png)

**Comment by github051** [comment] 2019-10-26 04:43
HI all,

Thanks for every one in this loop. Finally i'm able to complie the fw in single shot and the best part is it's working nice including SD card printing.

Thanks to all once again.

![Mks robin](https://user-images.githubusercontent.com/38275035/67614303-5acea700-f7d8-11e9-935b-3ef9262bdf8e.jpeg)

**Comment by boelle** [comment] 2019-10-26 08:08
oki will close this one as fixed, 

we can always reopen

**Closed as completed by boelle** 2019-10-26 08:08 UTC
Labels: Bug: Confirmed !, C: LCD & Controllers

**Comment by fizga** [comment] 2019-10-26 08:16
Thank you all nice job
