### ISSUE TITLE
[BUG] The first screen is showing some horizontal lines, appearing to be broken

### ISSUE THREAD

**Issue by souza-david** [MarlinFirmware/Marlin#15855] opened 2019-11-09 15:41 UTC
### Description

We are using the branch dev-2.1.x and the first screen of Marlin is showing some horizontal lines, appearing to be broken.

![image](https://user-images.githubusercontent.com/5842083/68531100-a6f80c00-02ed-11ea-8a85-ad4fba0262ac.png)

After 3 seconds, appears the boot screen and everything works normally.

![image](https://user-images.githubusercontent.com/5842083/68531106-b6775500-02ed-11ea-8d35-b90c1aa4c709.png)

### Steps to Reproduce
ZIP file containing the `Configuration.h` and `Configuration_adv.h` files. 
[marlin_config_files.zip](https://github.com/MarlinFirmware/Marlin/files/3827441/marlin_config_files.zip)

**Comment by GMagician** [comment] 2019-11-09 16:28
Better to try 2.0 bugfix it's more updated. AFAIK the 2.1 is not yet "active" its just prepared to be used when 2.0 will be released

**Comment by AnHardt** [comment] 2019-11-09 18:06
Disable `#define SHOW_CUSTOM_BOOTSCREEN`.

**Comment by sl1pkn07** [comment] 2019-11-10 11:16
> Disable `#define SHOW_CUSTOM_BOOTSCREEN`.

same here with you tip

(ReARM+cr10_stock lcd)

**Comment by RMN9** [comment] 2019-11-10 12:06
These squares appear during the firmware process. Apparently the firmware is loaded from the memory card each time.

Resolve problem - `//#define SHOW_CUSTOM_BOOTSCREEN`

**Comment by ellensp** [comment] 2019-11-11 06:01
This is not SHOW_CUSTOM_BOOTSCREEN. 
I also get this on a skr1.3 with SHOW_CUSTOM_BOOTSCREEN disabled
I just presumed this is what you get pre screen initialization.  
It takes a while to setup everything and read the sd card looking for a new firmware.bin 
I deliberately enabled SHOW_CUSTOM_BOOTSCREEN as a test, and it did as I suspected it would It displays the two bars of junk data, then after a short time it displays the Custom boot screen, then it displays the Marlin screen.

**Comment by souza-david** [comment] 2019-11-11 22:24
We have tried with:
`//#define SHOW_CUSTOM_BOOTSCREEN`
it did not solve the problem.

We are going to try the branch 2.0 bugfix and we let you guys know the result.

**Comment by souza-david** [comment] 2019-11-12 00:47
> Better to try 2.0 bugfix it's more updated. AFAIK the 2.1 is not yet "active" its just prepared to be used when 2.0 will be released

We tried bugfix 2.0, but it gives the same error. Even a totally new code, just configuring the card and the screen, the error is the same.

**Comment by HPparanhos** [comment] 2019-11-13 22:50
I am having the same problem with the bugfix 2.0 and the board BIGTREE_SKR_V1_3

**Comment by LinFor** [comment] 2019-11-14 10:35
I have the same issue on each power-up (not only when flashing new firmware).
No SHOW_CUSTOM_BOOTSCREEN defined.
I'm not uncomfortable with the problem, but if someone will undertake to solve it...

PS: LPC1768, SKR1.3, REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER

**Comment by souza-david** [comment] 2019-11-15 12:55
The first time the firmware is loading the "firmware.bin", those horizontal lines do not appear, but when it is loading the "FIRMWARE.CUR" it does appear on each power-up.

**Comment by HPparanhos** [comment] 2019-11-15 13:04
We have checked the power supply.
We have wrapped the "flat cable" in aluminum foil and ground everything correctly.
We have deleted the "firmware.bin" and it did not solve the problem.

**Comment by ellensp** [comment] 2019-11-15 14:49
@dvdsouza It doesn't ever load FIRMWARE.CUR. It looks for firmware.bin, if it is on the sdcard it loads firmware.bin and copies it to the flash and then renames the file to fimware.cur. It never looks at firmware.cur again.  Boot loader firmware https://github.com/triffid/LPC17xx-DFU-Bootloader look in main.c   NB if remove the sd card, you still get the bars.

**Comment by souza-david** [comment] 2019-11-15 15:01
@ellensp you are right, even without the sd card, we still get the bars.
Currently, we are looking for the error in the firmware boot section.

**Comment by ellensp** [comment] 2019-11-15 15:12
I think the bug is in the bootloader. the bootloader was designed for a smootieboard which has 5 LEDs. LED1 = P1_18  and this line is activated by the bootloader to indicate the status of the bootloader. Now along comes the skr1.3 and they dropped the leds and connected  1.18 to LCD_EN pin. Once this line is active any activity on the SPI bus is read into the LCD as display data.   I think we need a modified boot-loader that doesn't try and set the non existing LED pins.     
Edit: Nope.  I moved the LCD_EN to a few other pins (P0.00, P2.00) and the bars persisted.

**Comment by shitcreek** [comment] 2019-11-15 23:30
I think I might have stumbled upon the solution but I cannot be sure what exactly it was that resolved this issue for me. I think it was when I updated the library.
I deleted this folder: **.platformio\packages\framework-arduino-lpc176x** when I was getting the missing **header:const_functions.h** error, then I deleted the **.pio** folder and launched vscode and updated all platformIO libraries and cleared the cache. Recompiled and flashed the machine. The scrambled bars appear on first boot up when it is flashing the new firmware, but no longer does any time afterwards. It does appear for a split second though. Could someone test this out?

**Comment by blueeagle69** [comment] 2019-11-16 01:23
@shitcreek 
I just tried what you said.
If I hit the reset button, I get a faint horizontal line on my screen for about a second or so and then the main Marlin logo appears.
If I power-cycle my printer then those two horizontal bars appear.
Can't really tell if the time they are displayed is any shorter.

(SKR 1.3 with custom_bootscreen disabled.)

**Comment by souza-david** [comment] 2019-11-19 00:11
@shitcreek 
We have tried it out, but it did not solve the problem.
Now we are debugging the "bootloader" and "idle" function, to see whether the boot timing has any problem.

**Comment by souza-david** [comment] 2019-11-22 21:45
Hey guys, does anyone have anything new about this? We tried a few things, but that didn't solve the problem.

**Comment by boelle** [comment] 2019-11-24 12:56
@dvdsouza have you tried to ask for help any of these places?

RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
[Tom's 3D Forums](https://discuss.toms3d.org/)
Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
[Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
Marlin Discord server. Join link: https://discord.gg/n5NJ59y

**Comment by ellensp** [comment] 2019-11-27 07:18
After a long fight with my J-Link I managed to get debugging working. Now I can only do soft restart with this so you don't get the full screen of garbage, you just get a few lines (same as when you press reset vs full power off)  But it is already on screen before main() is called.

**Comment by souza-david** [comment] 2019-11-27 22:24
@ellensp yeah, it is already on screen before main() is called.
We were debugging the idle() function, but we were unsuccessful.

**Comment by ellensp** [comment] 2019-11-28 12:19
Making some headway.  Ill make some notes here in case it helps others quicker than me to find the issue. How I got this far. Firstly disable USE_WATCHDOG in configuration_adv.h, you also have to comment out watchdog_init(); in DebugMonitor.cpp to stop the watchdog rebooting the controller during debugging.  using a j-link set debug_init_break = tbreak Reset_Handler in platformio.ini start debugging. Replug the GLCD. (this puts garbage in its display buffer)  Display is clean until the line     SysTick_Config(SystemCoreClock / 1000); // Start millisecond global counter in framework-arduino-lpc176x/cores/arduino/main.cpp  after this line you have garbage on the LCD until the real first screen is displayed.  This looks like a  @p3p thing to me.

**Comment by p3p** [comment] 2019-11-28 15:47
Not sure why starting the Systick could cause noise on the display .. its just an internal timer interrupt

**Comment by rflulling** [comment] 2019-11-29 05:33
If you compile with Arduino. Can you try to roll back to version of Arduino that you know worked and try to compile again? I have seen a similar issue in certain newer versions of Arduino IDE when compiled with.

**Comment by HPparanhos** [comment] 2019-11-29 12:49
@ellensp We will test these settings here.

**Comment by ellensp** [comment] 2019-11-30 15:37
I replaced the boot loader on my SKR 1.3 and the bars are gone.  Can someone else confirm? 
The source for the modified boot loader can be found here https://github.com/ellensp/LPC17xx-DFU-Bootloader  The only change is that I removed all references to the LED's and the setup of those IO pins. 
The already compiled files can be found here https://github.com/ellensp/LPC17xx-DFU-Bootloader-build    
To replace the boot loader follow this guide https://reprap.org/forum/read.php?13,863336 but use the new bootloader.
NB this will wipe your current firmware.  So you have to put a firmware.bin on the sd card directly as the USB port on the SKR 1.3 isn't active yet.

**Comment by boelle** [comment] 2019-12-02 20:30
@dvdsouza tried what @ellensp suggested ?

**Comment by souza-david** [comment] 2019-12-03 00:59
The test will be held tomorrow or Wednesday night, we look forward to trying it, we just don't have the correct board at this time.

**Comment by boelle** [comment] 2019-12-07 12:43
@dvdsouza what did the test say?

**Comment by boelle** [comment] 2019-12-07 14:00
@dvdsouza since 2.0 was just released a few days ago has this changed this issue at all?

**Comment by souza-david** [comment] 2019-12-08 23:07
@ boelle We have tried the 2.0 release and nothing has changed.

@ellensp Unfortunately, right now we don't have an extra board available to change the boot loader, the ones we have are already on the sold machines and we don't want to risk changing the boot loader. If it was inside Marlin, there would be no problem.

**Comment by boelle** [comment] 2019-12-24 12:05
is the issue still the same with all the updates in the last 16 days?

**Comment by boelle** [comment] 2019-12-24 13:56
btw, who can confirm there is an issue? use the same configs as OP and the same hardware if possible

**Comment by blueeagle69** [comment] 2019-12-24 14:34
Yep I have the same issue.
For now I have been ignoring it and carrying on.
Merry Christmas!

**Comment by boelle** [comment] 2019-12-24 14:47
what happens if you wait like 30 sec when booting?

**Comment by blueeagle69** [comment] 2019-12-24 17:32
The board boots up fine after showing the white lines and carries on as normal.  At least it does for me.  Dont know what others are experiencing  :)

**Comment by sl1pkn07** [comment] 2019-12-24 21:21
> The board boots up fine after showing the white lines and carries on as normal.

this lines is the problem

**Comment by rado79** [comment] 2019-12-26 10:34
same problem here - broken white stripes - since coming to 2.0 from 1.1.9 - skr 1.3 - all versions/bugfixes
with or without custom bootscreen
reset after firmware flash = clear bootscreen with a little 1mm "-" on screen
on power up = broken lines

**Comment by souza-david** [comment] 2019-12-26 14:08
> is the issue still the same with all the updates in the last 16 days?

Yes, the issue still the same with all the updates!

**Comment by boelle** [comment] 2020-01-08 16:04
@dvdsouza  still no good news with the latest bugfix 2.0.x?

**Comment by souza-david** [comment] 2020-01-10 00:22
@boelle  We have no BIGTREE_SKR_V1_3 board at this moment to test the bugfix 2.0.x. We'll have a board on Monday and I'll let you know.

**Comment by rado79** [comment] 2020-01-10 21:02
@boelle no good news, SKR 1.3

**Comment by Dracrius** [comment] 2020-01-11 21:27
Oh I see the same thing on an SKR mini e3 1.2 at bootup!

**Comment by souza-david** [comment] 2020-01-13 22:57
@boelle  , no good news!

**Comment by boelle** [comment] 2020-01-30 21:50
a lot of updates and fixing has happend in the last week, is the problem still there?

**Comment by souza-david** [comment] 2020-02-10 19:39
@boelle , repo updated and the problem still there.

**Comment by thinkyhead** [comment] 2020-02-11 10:51
This is not something that can be addressed in the firmware. Case closed.

**Closed as completed by thinkyhead** 2020-02-11 10:51 UTC
Labels: Bug: Confirmed !, A: LPC176x
