### ISSUE TITLE
Solution for Cant falsh ender 6 doesnt work... adding ../ to the ccp makes is too many ../'s and will complie error

### ISSUE THREAD

**Issue by sparksplur** [MarlinFirmware/Marlin#22282] opened 2021-07-02 02:32 UTC
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

When you try to flash marlin to ender 6 u just get stuck on loading screen

### Bug Timeline

still same issue

### Expected behavior

expect it to load

### Actual behavior

doesnt load

### Version of Marlin Firmware

Newest bug fix 2.0

### Additional information & file uploads

You marked it as duplicate but it wasnt... also in the solution you linked where your adding a extra ''../'' for the feature/powerloss.h'' will just yieild a cannot find source file. So that solution also doesnt work.

**Comment by thisiskeithb** [comment] 2021-07-02 03:43
Duplicate of #21274

**Comment by thisiskeithb** [comment] 2021-07-02 03:44
Please stop creating new issues. Ender-6 discussions should happen in the linked issue.

**Closed as completed by thisiskeithb** 2021-07-02 03:43 UTC

**Comment by sparksplur** [comment] 2021-07-02 04:07
ohhhh sorry XD i didnt realize what was going on
    On Thursday, 1 July 2021, 08:44:35 pm GMT-7, Keith Bennett ***@***.***> wrote:  
 
 


Please stop creating new issues. Ender-6 discussions should happen in the linked issue.
