### ISSUE TITLE
LCD_TRAMMING_WIZARD does not Deploy Magnetic Probe

### ISSUE THREAD

**Issue by AustinTylerDean** [MarlinFirmware/Marlin#25398] opened 2023-02-18 01:08 UTC
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Was wondering if this would be a bug, or feature request, but if you use the tramming wizard without manually deploying the magnetic probe, the tool head keeps seeing an open circuit from the z endstop and continues to cycle point to point, raising 4mm at each point until I assume it runs out of Z height.

Would be nice if the wizard checked for probe, fetched the probe, and returned the probe like it does in other functions.

### Bug Timeline

New, Since Mag Probes were written in.

### Expected behavior

I expected either the banner to report z-probe error, or ideally fetch the probe and return it after tramming.

### Actual behavior

Moves to four corners of bed, climbing 4mm of z-height at each corner indefinitely.

### Steps to Reproduce

1. Have Mag-Probe Installed
2. Use Bed Tramming Without Deploying First

### Version of Marlin Firmware

2.1.2

### Printer model

Ender 3

### Electronics

KevinAKASam Belted Z, EnderKlacker (mag probe), v4.2.7 board

### Add-ons

Mag Probe

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Cura

### Host Software

OctoPrint

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Config_&Adv.zip](https://github.com/MarlinFirmware/Marlin/files/10772699/Config_.Adv.zip)

**Comment by thisiskeithb** [comment] 2023-02-18 01:13
Duplicate of https://github.com/MarlinFirmware/Marlin/issues/24728

**Closed as completed by thisiskeithb** 2023-02-18 01:13 UTC
