### ISSUE TITLE
[FR] Reversal of E stepper using G-code

### ISSUE THREAD

**Issue by DrumClock** [MarlinFirmware/Marlin#21247] opened 2021-03-04 07:39 UTC
Would it be possible to define a G-code for reversing the rotation of the stepper motor for the extruder (E0-En)? 

`E.g.  as when using  M605 S3  -  initiate mirrored movement.`

**Comment by thisiskeithb** [comment] 2021-03-04 07:55
Duplicate of https://github.com/MarlinFirmware/Marlin/issues/16550

**Comment by thisiskeithb** [comment] 2021-03-04 07:56
While not a 1:1 duplicate feature request, both features are related and should be discussed in the linked issue above.

**Closed as completed by thisiskeithb** 2021-03-04 07:55 UTC
Labels: T: Feature Request
