### ISSUE TITLE
Extruder values go out of range 

### ISSUE THREAD

**Issue by gmossy** [MarlinFirmware/Marlin#2867] opened 2015-12-22 21:17 UTC
Testing Marlin RC3BugFix,  a print was going for 2hours, and started clicking.  I canceled the print from cura and when to play with the Extruder control on the LCD, and the values were out of range, and funny characters,  i.e..such as *?--.    I have seen this problem a number of times now, also on RC2.  
3UP printer, RAMPS 1.4, Marlin RC3BugFix, EDV6 Extruder, REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER
Glenn

**Comment by gmossy** [comment] 2015-12-23 00:32
Additional erratic behavior of Extruder control, after a print was stopped, Extruder read +660 then I rotated the extruder on the LCD to remove filament and then Marlin reloaded.

**Comment by bradanlane** [comment] 2016-01-21 14:33
I may be seeing similar:

My print ran for approximately 20 minutes and extruder started clicking. The flow became erratic and under extruded. I will run the test again and check the LCD values. 

If I run the same gcode print with Marlin 1.0.? (jcrocholl) I complete the print without the extruder clicking.

**Comment by bradanlane** [comment] 2016-01-22 17:52
I ran two tests today and I am not seeing the corrupted extruder values that you mentioned. I did see that the values reported through the LCD did not match what I had in my configuration. This is the second case where I have seen EEPROM values not match what were set in the configuration.h file. (I do have `#define EEPROM_SETTINGS`)

**Comment by bradanlane** [comment] 2016-01-25 15:18
@gmossy - when you mentioned "**funny characters, i.e..such as *?--.**" were refering to the entire LCD panel or just extruder settings?

I ask because I was printing with RC3BugFix yesterday and - while the print completed successfully - the LCD panel showed the following display for the at least last hour (of a two hour print)

![image of corrupt LCD](http://thesalmonfarm.org/wp-content/blogs.dir/1/uploads/2016/01/img_1887-320x121.jpeg)

**Comment by gmossy** [comment] 2016-01-25 16:01
The characters were only on the Extruder motion adjustment screen.  ?_.? etc.  and I've only seen it on RC2 so far.  Never had any problem the LCD panel using RC3BugFix so far.  
As far the EEPROM settings, I think there is an issue and I'll examine it closer.  Mine didn't match the configuration.h, I had set the values to lower values before I flashed the firmware to RC3BugFix and then the new firmware didn't update them.  I manually did a memory default and save from the LCD screen, but I had assumed that was expected behavior.  I believe uploading a new arduino sketch won't clear the eeprom and I"m familiar with having to run an eeprom sketch to clear out the memory.  Question to the developers here what behavior is expected for the EEPROM.

**Comment by bradanlane** [comment] 2016-01-25 16:54
I am also seeing the EEPROM settings not updating. I'v reverted to using an **auto0.g** file on the SD card to insure all important settings are correct for the printer.

**Comment by KiteLab** [comment] 2016-01-25 17:24
@gmossy 
The number to string conversion currently used for displaying the E axis is `ftostr31()`.
This is good for numbers between -999.9 and +999.9. If the current_position[E_AXIS] value is smaller or larger garbage may appear on the display. That does not explain other malfunctions.
current_position[E_AXIS] is a float - can be nearly infinite big - is an absolute value - but usually is reset to 0 by a G92 per layer by the slicer. Nerveless it can be much larger than 999.9.

There was a real error in that area of the menu, fixed in the current RCBugFix.

In the current RCBugFix you could additionally try to replace `ftostr31(` with `ftost51(` in the lines 836 and 873 in ultralcd.cpp

@gmossy & @bradanlane 
The EEPROM settings overrule the config. settings by purpose. To store your new config. setting in the EEPROM use:

> M502 - Revert to the default "factory settings". You still need to store them in EEPROM afterwards if you want to.
> M500 - Store parameters in EEPROM

Than check with 

> M501 - Read parameters from EEPROM (if you need reset them after you changed them temporarily).
> M503 - Print the current settings (from memory not from EEPROM). Use S0 to leave off headings.

**Comment by bradanlane** [comment] 2016-01-25 17:34
Thanks. My problem was misinterpreting the comment in the configuration file.

```
// EEPROM
// The microcontroller can store settings in the EEPROM, e.g. max velocity...
//define this to enable EEPROM support
```

I read the comments to mean "'set the #define to store configuration.h settings in EEPROM".

**Comment by KiteLab** [comment] 2016-01-25 17:34
@bradanlane 
Usually you can restore a corrupted status screen by clicking the encoder twice. Entering the menu contains a software reinitialisation of the display. 
Usually the corruption, your picture shows, is caused by, static electricity, or noise on the display lines, or a to tight timing, or a combination of these.
In some cases it needs a hardware reset, or power down, to come out of this.

**Comment by bradanlane** [comment] 2016-01-25 17:36
It could easily be noise on/over/near the display lines. I will try to "double tap" if I see this again. IF it reoccurs, I will reroute some signal lines and see if that helps.

**Comment by thinkyhead** [comment] 2016-03-11 14:52
@gmossy This should be all fixed now in `RCBugFix`. We had a stack corruption issue associated with axis movement from the LCD. Please give the latest code a try and let us know if it's still an issue.

**Comment by jbrazio** [comment] 2016-04-28 19:02
Thank you for your interest making Marlin better and reporting this issue but this topic has been open for a long period of time without any further development. Marlin has been under heavy development for the past couple of months and moving to it's last mile to finish the RC cycle and release **Marlin v1.1.0**. We suggest you to try out the latest [RCBugfix](https://github.com/MarlinFirmware/Marlin/archive/RCBugFix.zip) branch and reopening this issue if required.

**Closed as completed by jbrazio** 2016-04-28 19:02 UTC
Labels: Bug: Potential ?
