### ISSUE TITLE
[BUG] Extruder stops working during printing

### ISSUE THREAD

**Issue by Diogo24P** [MarlinFirmware/Marlin#22624] opened 2021-08-24 12:39 UTC
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

I'm having a problem with my 2.0.9.1 firmware.
When a print starts, the extruder engine stops working, it may be at the end of the print, as in the beginning, there is no right time.
It only goes back to work if it pauses printing and then resumes, it then works until the printer is turned off.
When I start the printer, I have to start printing, pause and resume to print without stopping the extruder motor.
I tried with another version 2.0.9.1 and didn't have this problem with the same g-code file.
I recently installed the Extruder orbiter, but even before installing this extruder, I already have this problem.

What is generating this?

### Expected behavior

Work without stopping .

### Actual behavior

The extruder stops. To get back to work I have to pause and then resume while printing. 

### Steps to Reproduce

Turn on the printer.
Start 1 impression .

### Version of Marlin Firmware

2.0.9.1

### Printer model

Sapphire Plus V2

### Electronics

TMC 2225, Extruder orbiter or original extruder, same problem in 2, Moquito Clone, Bltouch

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Simplify3D

### Host Software

SD Card (headless)

### Additional information & file uploads

I had to create a new topic, because the moderator simply closed the topic if he read it. 
[Marlin-2.0.x.zip](https://github.com/MarlinFirmware/Marlin/files/7039126/Marlin-2.0.x.zip)

**Comment by thisiskeithb** [comment] 2021-08-24 12:42
Duplicate of https://github.com/MarlinFirmware/Marlin/issues/22622

**Comment by thisiskeithb** [comment] 2021-08-24 12:42
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).

**Closed as completed by thisiskeithb** 2021-08-24 12:42 UTC
