### ISSUE TITLE
[BUG - 2.0.x bugfix] LPC1769 EEPROM values not loaded on boot

### ISSUE THREAD

**Issue by klcjr89** [MarlinFirmware/Marlin#14487] opened 2019-07-03 00:05 UTC
Whatever code changes were made in the past 24 hours has broken the loading of EEPROM values on my Azteeg X5 mini board on boot.

Not sure why things have become more broken lately when it was pretty solid.

**Comment by thinkyhead** [comment] 2019-07-03 06:02
Duplicate of #14470

**Closed as completed by thinkyhead** 2019-07-03 06:02 UTC

**Comment by klcjr89** [comment] 2019-07-03 17:25
This is still broken and I have no idea why.
