### ISSUE TITLE
[BUG] problem with build firmware SKR 1.3

### ISSUE THREAD

**Issue by joneggg** [MarlinFirmware/Marlin#19362] opened 2020-09-12 17:02 UTC
Hello, when trying to flash skr 1.3, it gives this:

![67620703-6D77-4A4B-B393-AB4D1B261AE4](https://user-images.githubusercontent.com/71187057/93000630-86bb5e00-f54b-11ea-9c08-d5fbf82f6532.png)

Windows 10, Latest VSCode, latest platformio, github desktop ,marlin the old one that I used with the first firmware (august 2019)

can this be repaired somehow?

**Comment by ellensp** [comment] 2020-09-12 17:34
Please test the [`bugfix-2.0.x` branch](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.0.x.zip) to see where it stands. If the problem has been resolved then we can close this issue. If the issue isn't resolved yet, then we should investigate further.

**Comment by boelle** [comment] 2020-09-12 17:37
you are missin a package for vscode/platform.io (red text)

**Comment by joneggg** [comment] 2020-09-12 21:45
I just download latest marlin and problem solved

**Closed as completed** 2020-09-12 21:46 UTC
