### ISSUE TITLE
Commented DEACTIVATE_SERVOS_AFTER_MOVE servo still deactivates

### ISSUE THREAD

**Issue by c3D-Dan** [MarlinFirmware/Marlin#17969] opened 2020-05-11 23:50 UTC
### Bug Description

Deactivate servo after move DEACTIVATE_SERVOS_AFTER_MOVE has been commented out, servo is deactivated after approximately 10 seconds.

### My Configurations

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/4612645/Marlin.zip)

### Steps to Reproduce

1. Comment out DEACTIVATE_SERVOS_AFTER_MOVE in configuration.h
2. T0 to move to servo position 1
3. Wait 10 seconds.  Servo becomes deactivated.  Same with T1

**Expected behavior:** Servo should remain active
**Actual behavior:** Servo Deactivates

**Comment by thinkyhead** [comment] 2020-05-12 03:55
- Do you see the same issue with another board?
- Have you ruled out a hardware issue?

Please test the [`bugfix-2.0.x` branch](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.0.x.zip) to see where it stands. If the problem has been resolved then we can close this issue. If the issue isn't resolved yet, then we should investigate further.

**Comment by c3D-Dan** [comment] 2020-05-12 04:12
Sorry guys.  Jumped the gun.  Issue was with servo.  Doesn't occur with another servo.

**Closed as completed** 2020-05-12 04:12 UTC
