### ISSUE TITLE
Cambio LCD anet A8 con lcd 12864 anet

### ISSUE THREAD

**Issue by bera99** [MarlinFirmware/Marlin#16714] opened 2020-01-29 11:17 UTC
Ciao a tutti, dopo aver installato Marlin guardando questa guida 
https://youtu.be/wRODgnAqp1A e sbloccando la scheda con usbasp ho voluto cambiare schermo LCD dell'anet mettendo quello 12864 dell'anet A6 guardando questa guida https://youtu.be/uMsIb4Gwm3o ma dopo aver caricato lo sketch questo è come si vede sullo schermo nuovo, come risolvo?
![IMG-20200128-WA0003](https://user-images.githubusercontent.com/60176733/73352342-3085fd00-4291-11ea-9bc2-1c448f7d73ea.jpeg)
![IMG-20200128-WA0001](https://user-images.githubusercontent.com/60176733/73352352-34198400-4291-11ea-8c0a-b31be695bea9.jpeg)

**Comment by boelle** [comment] 2020-01-29 11:44
please use english

Configurations, please
Please ZIP up your `Configuration.h` and `Configuration_adv.h` files (as
requested in the Issue template) and drop them into your next reply.
We'll check them over and see if anything is amiss.

**Comment by ellensp** [comment] 2020-01-29 12:13
google translate failed to identify the Italian on this page...  had to force it.
In Configuration.h 

Find
#define REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER
Add
#define ST7920_DELAY_1 DELAY_NS(125)
#define ST7920_DELAY_2 DELAY_NS(125)
#define ST7920_DELAY_3 DELAY_NS(125)

eg https://github.com/MarlinFirmware/Configurations/blob/master/config/examples/Anet/A6/Configuration.h#L2004

**Comment by boelle** [comment] 2020-01-29 12:26
so this is a support q and not a bug?

**Comment by ellensp** [comment] 2020-01-29 12:49
Yes.

**Comment by boelle** [comment] 2020-01-29 12:52
closing it, should have been posted in discord

adress/join link is in the pinned post

**Closed as completed by boelle** 2020-01-29 12:52 UTC
