### ISSUE TITLE
Thermal Runaway Toggle for 8-Bit Display

### ISSUE THREAD

**Issue by Lobuttomize** [MarlinFirmware/Marlin#22402] opened 2021-07-19 22:44 UTC
### Is your feature request related to a problem? Please describe.

My Ender 3 Pro shuts down due to thermal runaway when changing nozzles at max temp.

### Are you looking for hardware support?

Ender 3 Pro Board 4.2.2

### Describe the feature you want

Somewhere in the menu, probably under config or advanced config, if possible, it would be nice to have a "disable thermal runaway" option that you could use and then have it change to "enable thermal runaway" which would allow you to re-enable it after you're done doing whatever you needed to disable it for. 

If this does already exist somewhere and I just didn't see it or it's commented out by default, where would I be able to enable it?

**Comment by thisiskeithb** [comment] 2021-07-19 23:37
Duplicate of https://github.com/MarlinFirmware/Marlin/issues/10506

**Closed as completed by thisiskeithb** 2021-07-19 23:37 UTC
Labels: T: Feature Request
