### ISSUE TITLE
Marlin config file for Geetech A10T is not correct.  Please check

### ISSUE THREAD

**Issue by ace1966** [MarlinFirmware/Marlin#21565] opened 2021-04-08 14:39 UTC
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

Marlin does not display on screen.   Printing form USB cable only.

### Bug Timeline

No

### Expected behavior

None

### Actual behavior

Prints only with USB cable.  No wording on LCD, but it does lite up.

### Steps to Reproduce

Tuen the machine,  
No wording comes on but screen lites up.

### Version of Marlin Firmware

Bugfix 2.0x

### Printer model

Geetech A10T

### Electronics

Stock

### Add-ons

None

### Your Slicer

Cura

### Host Software

Cura

I have tried installing the firmware upgrade for the A10T  with no luck.  The config file I don't believe contains the correct info.
After installing the firmware the LCD screen lights up but contains no wording.   The printer will print from USB cable only.

I have not made any modifications to this printer except for trying to upgrade firmware.

**Comment by Vertabreak** [comment] 2021-04-08 15:32
Did you use the base version config or the yhcb version if you have a v4.1 board you need yhcb. boards less then v4.1 use the base config not yhcb. Chances are you have the older screen defined and not the new yhcb screen.

**Comment by ace1966** [comment] 2021-04-08 15:39
Can I reinstall it now with the correct version?

**Comment by Vertabreak** [comment] 2021-04-08 15:43
Switch from discount reprap lcd to yhcb disable one enable other reflash. Both examples are provided in examples. Geeetech is notorious for secret changes to there printers over time this was one such change older versions have 2004lcd newer have the yhcb2004.

**Comment by ace1966** [comment] 2021-04-08 15:48
Sorry I am new to 3d printing,  could you tell me where I can find the yhcb versionthanks for your fast response.
    On Thursday, April 8, 2021, 11:32:45 AM EDT, Vert ***@***.***> wrote:  
 
 


Did you use the base version config or the yhcb version if you have a v4.1 board you need yhcb.

**Comment by Vertabreak** [comment] 2021-04-08 15:54
https://github.com/MarlinFirmware/Configurations/tree/bugfix-2.0.x/config/examples/Geeetech/A10T

**Comment by ace1966** [comment] 2021-04-08 17:27
I can't get any of the A10T config files to work, they all come up with error message.I guess I'm too old for this stuff (73)Thanks for Your help.
    On Thursday, April 8, 2021, 11:54:46 AM EDT, Vert ***@***.***> wrote:  
 
 


https://github.com/MarlinFirmware/Configurations/tree/bugfix-2.0.x/config/examples/Geeetech/A10T

**Comment by Vertabreak** [comment] 2021-04-08 17:29
what error? i just successfully compiled both the stock & yhcb version. 
make sure your cleaning your build between compiles.

**Comment by ace1966** [comment] 2021-04-08 20:19
Thanks for all your help, I think I am getting it now.

**Comment by Vertabreak** [comment] 2021-04-08 20:24
if the issue is solved you can close the issue.
here is a hand prepared copy i have compile checked to rule out any confusion.
[Marlin-bugfix-2.0.x-a10t-yhcb.zip](https://github.com/MarlinFirmware/Marlin/files/6281259/Marlin-bugfix-2.0.x-a10t-yhcb.zip)

**Comment by thisiskeithb** [comment] 2021-04-08 21:58
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server

**Closed as completed by thisiskeithb** 2021-04-08 21:58 UTC

**Comment by ace1966** [comment] 2021-04-08 23:06
Sorry new to the site.


    On Thursday, April 8, 2021, 05:58:54 PM EDT, Keith Bennett ***@***.***> wrote:  
 
 


This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on this page.) For best results getting help with configuration and troubleshooting, please use the following resources:
   
   - Marlin Documentation hosted on MarlinFW.org
   - Marlin Forum hosted on RepRap.org
   - Marlin Firmware Facebook Group
   - Marlin Firmware for 3D Printers Facebook Group
   - Marlin Configuration on YouTube
   - Marlin Firmware Discord server

**Comment by ace1966** [comment] 2021-04-09 11:31
I really appreciated your help on getting my 3d printer back to working.   I would of never gotten it working again without your help.Thanks
    On Thursday, April 8, 2021, 04:24:33 PM EDT, Vert ***@***.***> wrote:  
 
 


if the issue is solved you can close the issue.
