### ISSUE TITLE
G29 command not working properly. 

### ISSUE THREAD

**Issue by mrah** [MarlinFirmware/Marlin#10577] opened 2018-04-30 12:59 UTC
### Description

Hello, today i flashed my firmware and installed **Marlin-bugfix-1.1.x**. But i have problem with ABL feature. G29 command process working slow. There is too much delay between probing. You can see in video. I have no problem with Marlin 1.1.x.

**Update:**
Now i freshly download Marlin 1.1.x and reconfigured without copying any parameter. ABL working correctly. I added a video and configuration files.

#### Additional Information
My configuration files for bugfix-1.1.x
[bugfix-1.1.x.zip](https://github.com/MarlinFirmware/Marlin/files/1960721/bugfix-1.1.x.zip)

My configuration files for 1.1.x
[1.1.x.zip](https://github.com/MarlinFirmware/Marlin/files/1960709/1.1.x.zip)

Video
Part: 1
https://youtu.be/VA7VZRxYn38
Part: 2
https://youtu.be/FF_54ccANiM
Part: 3 (40 minutes later)
https://youtu.be/HwgOblUK72k
Part: 4 (Marlin 1.1.x)
https://youtu.be/zJen3XAAoZg

**Comment by Zwaubel** [comment] 2018-04-30 14:03
I can confirm the same behavior on my machine and I'm pretty sure this problem was introduced by the commit 071387bace113c10be90f8b0a99306bbbc7d591d (bugix-1.1.x) and 4dfc011d86b8a271fca23b42a8cb73902d622fb2 (bugfix-2.0.x) of @thinkyhead. The problem probably is caused by a double conversion of the slow z feed rate from mmm to mms somewhere in the code.

**Comment by mylife4aiurr** [comment] 2018-04-30 16:55
Upgraded this morning to commit 071387bace113c10be90f8b0a99306bbbc7d591d. Delta machine.

Homing G28 works fine.
Movements in Octoprint work fine. ie home z, move any direction 100mm works fine.

However G33 autodeltaconfig. G33 P3 V2 F6
Starts at z max. Starts moving toward bed fast, then switch to super slow speed to probe the bed. I end up sending M112 because its so slow.

This happened between
commit b4ddee8bebead400142fe45edc3bc41bea4ecb16 Working ok
commit 071387bace113c10be90f8b0a99306bbbc7d591d Probing super slow

**Comment by Zwaubel** [comment] 2018-04-30 19:03
Checkout @MagoKimbra PR: #10576
This addresses the super slow homing issue and fixed the problem for me.

**Comment by mylife4aiurr** [comment] 2018-04-30 20:26
@Zwaubel confirmed fixed with the commit you referenced.

**Comment by thinkyhead** [comment] 2018-04-30 21:37
Thanks! Feedrates for both homing and probing moves should now be consistent.

**Closed as completed by thinkyhead** 2018-04-30 21:37 UTC
Labels: Bug: Confirmed !, S: Solved
