### ISSUE TITLE
BLTouch probing fails to reach bed, but G28 probe reaches bed

### ISSUE THREAD

**Issue by buncopter** [MarlinFirmware/Marlin#11844] opened 2018-09-16 13:19 UTC
### Description

Firmware: Marlin 1.1.9 
Hardware: Anycubic I3 Mega modified with BLTouch - Using the Trigorilla Board
Problem: When using G28, the bed is able to home correct on X, Y and Z axis
When performing G29, Z probe deploys, but then the Hotend and Probe ascends along Z axis roughly 2cm above bed. The Hotend box with the Probe descends 5mm or so from its current position to attempt a probe maneuver, but fails, Octopi reports 'Probing failed'. G29 fails. 
 
- No matter what Z offset is set at using M851 and subsequent M500 to save settings, the probe is never able to go closer than 2cm or so from the bed. 
- Dual Z axis endstops function correction on M119
- G28, probe and hotend are able to make contact with the bed
- M502 does not rectify the problem

#### Additional Information
[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/2387390/Marlin.zip)
I've attached the entire Marlin uncompiled firmware if further interrogation if required

Video of what is happening is attached as well. 
https://youtu.be/xC-1RLEK2hQ

Any help would be much appreciated. I've been trying to trouble shoot this for hours with no success.

**Comment by thinkyhead** [comment] 2018-09-17 08:02
Please test the `bugfix-1.1.x` and/or `bugfix-2.0.x` branches to see whether it helps. If the problem has been resolved then we can close this issue. If the issue isn't resolved in either of those branches yet, then we should investigate further.

**Comment by buncopter** [comment] 2018-09-17 08:06
> Please test the `bugfix-1.1.x` and/or `bugfix-2.0.x` branches to see whether it helps. If the problem has been resolved then we can close this issue. If the issue isn't resolved in either of those branches yet, then we should investigate further.

I'm using bugfix-1.1.x. already

**Comment by thinkyhead** [comment] 2018-09-17 08:13
> Firmware: Marlin 1.1.9

> I'm using bugfix-1.1.x. already

Ah, good to know!

I don't see anything wrong with your configurations.

Usually when there's an unexpected raise of the probe, it's because the probe is being read as triggered. You can try testing with `M401`, `M402`, and `M119` to see that the probe state is being properly detected.

**Comment by buncopter** [comment] 2018-09-17 08:39
If I use M280 P0 S10 and M280 P0 S90 (using a bltouch clone) both report open when using M119, but that could just be due to such a short pulse it can't be picked up. However, when leveling, if I press on the probe to trigger it, the hotend moves to the next location and repeats attempt at probe.

**Comment by thinkyhead** [comment] 2018-09-17 08:41
The thing that `M119` can catch is a stuck-triggered (or error) state, so it's ok if the probe shows "open."

What error does OctoPrint report?

**Comment by buncopter** [comment] 2018-09-17 08:43
Recv: Error:Probing failed
WARNING! Received an error from the printer's firmware, ignoring that as configured but you might want to investigate what happened here! Error: Probing failed
Recv: X:0.00 Y:10.00 Z:12.74 E:0.00 Count X:0 Y:800 Z:5097
Recv: ok

**Comment by thinkyhead** [comment] 2018-09-17 08:49
See what happens if you set `Z_PROBE_LOW_POINT` to -100.
_**(Stand by the reset button to prevent probe damage!)**_

**Comment by buncopter** [comment] 2018-09-17 09:11
Recv: Error:Probing failed
WARNING! Received an error from the printer's firmware, ignoring that as configured but you might want to investigate what happened here! Error: Probing failed
Recv: X:0.00 Y:10.00 Z:12.75 E:0.00 Count X:0 Y:800 Z:5101

**Comment by buncopter** [comment] 2018-09-20 11:05
Anyone have any ideas please?

**Closed as completed** 2018-09-25 05:35 UTC

**Comment by italocjs** [comment] 2018-11-03 20:23
Not sure what was the cause, but i:

Enabled servo (using bltouch)
Increased #define Z_PROBE_LOW_POINT          -5 // Farthest distance below the trigger-point to go before stopping

**Comment by HuguesDug** [comment] 2018-12-09 17:26
Same problem with Anet A8 and an inductive sensor. 

Increased #define Z_PROBE_LOW_POINT -5 

Fixed the problem... but I don't know the root cause !

**Comment by clairvoyan** [comment] 2018-12-27 03:43
> Same problem with Anet A8 and an inductive sensor.
> 
> Increased #define Z_PROBE_LOW_POINT -5
> 
> Fixed the problem... but I don't know the root cause !

Worked for me too

**Comment by cpm64** [comment] 2019-07-22 06:32
It seems it doesn't work for me. It is stopping randomly above one of these positions of the 5x5 matrix: 3, 8, 13, 18 or 23, very very rarely in other points. So , most of the time is on the middle of X. 
The head position above the point, the probe is extended (blue LED), Z starts to move down but after a few millimeters it stops and is raised back to the initial Z position above the point. The probe is still extended and blue LED still on. The probe nor the head is reaching the bed. OctoPi is reporting 'probe error' and M119 reports everything as OPEN. The mechanical Z stop is not reached even if the screws are very close to the switch.
The probe seems to be OK as it passes all the tests (M280 Px Sy) but it cannot perform a reliable G29.

- I tried with other shielded cables , re routed to not touch the rest of the wires. I eliminated the bad wiring assumption.
- I also disabled fans and heaters when probing
- Increased delay to 1000ms
- Increased Z_PROBE_LOW_POINT to -100. 
- Adjusted the mechanical limit switches to allow the head to be below the bed thus eliminating mechanical stops triggering.
- The Z-Offset is -2.80

My setup:
- Latest 1.1.9 which contains all the 1.1.x reports to date from here https://github.com/MNieddu91/Marlin-AI3M-BLTouch (based on davidramiro's work)
- TMC2208 , TMC2208 UART on E0 with TX on D14 and RX on D15

Any idea?

**Comment by italocjs** [comment] 2019-07-22 12:40
@cpm64 , i had my share of issues with bltouch, most of them were fault cables, one i needed to remove the metal probe, sand it and place it back (rough surface), i'm now using single flat to drive X, E0, T0, 2 fans and bltouch) i had to place a 100nf (104) ceramic capacitor between - and s inside the bltouch to avoid the steppers interference,  Might be your case. (i also add 100nf cap in the endstops just to be safe)

One thing i like to do is to put a multimeter in diode/buzzer (that annoying sound) in series with the the cables, so i can move them around and hear if there is a broken wire somewhere.

**Comment by cpm64** [comment] 2019-07-22 13:31
@italocjs : thanks, I tried with shielded cables not routed with the rest of the FAN/Hotend cables. As far as I learned BLTV3.0 has the capacitor already mounted. For the endstops I can see an SMD cpacitor on the endstop PCB not sure is the one you are talking about. 

Usually when endstops are triggered M119 should report them as triggered. 

In my case, if I issue M119 just after the 'probe error' it will reports everything as OPEN.:
x_min: open
y_min: open
z_min: open
z_probe: open
filament: open


I will try to activate the end-stop buzz sound to see if they are triggered.

**Comment by italocjs** [comment] 2019-07-22 13:58
Try something, power your board using a good phone charger (over USB) and see if this issue still happens, if it works it might be a weak voltage regulator, 

Did you tried using other firmware version right? i'm skipping all software issues here believing you tried them already.  The logic of the bltouch is described in the datasheet, i dont remember it well, you might want to take a look.

**Comment by cpm64** [comment] 2019-07-22 15:20
@italocjs : It seems there are other people with this issue and also one person who reports a possible fix: https://github.com/MNieddu91/Marlin-AI3M-BLTouch/issues/12#issuecomment-499090765 and the config is 2 posts underneath (it is for 2.0 branch) . I will give that config a try: I don't understand why he activated #define Z_MIN_PROBE_ENDSTOP_INVERTING true // set to true to invert the logic of the probe.

**Comment by cpm64** [comment] 2019-07-22 19:56
Switched to Marlin 2.0 - it seems to fix the problem. I can see the probe failing sometime by unexpected pin on/off (EMI?) or the probe entering alarm mode when reaching the bed . However the firmware retries the action and everything is fine. This never happened in 1.1.9, the probe never performed unexpected pin on/off nor entering alarm mode.

**Comment by vallettea** [comment] 2020-01-10 13:42
setting Z_PROBE_LOW_POINT fix the problem
