### ISSUE TITLE
Keep Power supply ON on connect

### ISSUE THREAD

**Issue by a0s** [MarlinFirmware/Marlin#5241] opened 2016-11-17 17:18 UTC
I have Rumba (with 1.1.0-RC7 of Marlin) board and ATX power supply. PS_ON rumba's pins connected to PS_ON power supply's pins. Also i have OctoPrint server (CubieBoard 2) powered from same ATX (from regular 5V line, i don't want use standby lines, it has limited max current). 

By default PS_ON on Rumba is active (PS_DEFAULT_OFF is disabled), so Rumba and OctoPrint working ok after power on. 

But after press Connect in OctoPrint's interface Rumba's PS_ON breaks, ATX turn off and OctoPrint turn off. How to prevent it? I think setup_powerhold() working incorrectly in my case. Am i right?

OctoPrint not send M80 nor M81 during connection.
```
Changing monitoring state from 'Offline' to 'Detecting serial port'
Serial port list: ['/dev/ttyACM0']
Connecting to: /dev/ttyACM0
Connecting to: /dev/ttyACM0
Changing monitoring state from 'Detecting serial port' to 'Opening serial port'
Connected to: Serial<id=0xaff0dc70, open=True>(port='/dev/ttyACM0', baudrate=115200, bytesize=8, parity='N', stopbits=1, timeout=10.0, xonxoff=False, rtscts=False, dsrdtr=False), starting monitor
Changing monitoring state from 'Opening serial port' to 'Connecting'
Send: N0 M110 N0*125
Recv: start
Send: N0 M110 N0*125
Recv: echo: External Reset
Recv: Marlin 1.1.0-RC7
Recv: echo: Last Updated: 2016-07-31 12:00 | Author: (none, default config)
Recv: Compiled: Sep 19 2016
Recv: echo: Free Memory: 5141  PlannerBufferBytes: 1232
Recv: echo:V24 stored settings retrieved (398 bytes)
Recv: echo:Steps per unit:
Recv: echo:  M92 X160.85 Y160.85 Z5120.00 E1105.08
Recv: echo:Maximum feedrates (mm/s):
Recv: echo:  M203 X160.00 Y160.00 Z5.00 E50.00
Recv: echo:Maximum Acceleration (mm/s2):
Recv: echo:  M201 X800 Y400 Z80 E5000
Recv: echo:Accelerations: P=printing, R=retract and T=travel
Recv: echo:  M204 P800.00 R5000.00 T800.00
Recv: echo:Advanced variables: S=Min feedrate (mm/s), T=Min travel feedrate (mm/s), B=minimum segment time (ms), X=maximum XY jerk (mm/s),  Z=maximum Z jerk (mm/s),  E=maximum E jerk (mm/s)
Recv: echo:  M205 S0.00 T0.00 B20000 X5.00 Z0.40 E5.00
Recv: echo:Home offset (mm)
Recv: echo:  M206 X0.00 Y0.00 Z0.00
Recv: echo:PID settings:
Recv: echo:  M301 P23.81 I1.11 D127.20
Recv: echo:  M304 P114.45 I10.20 D321.13
Recv: echo:Filament settings: Disabled
Recv: echo:  M200 D3.00
Recv: echo:  M200 D0
Recv: echo:Z-Probe Offset (mm):
Recv: echo:  M851 Z-7.50
Recv: ok
Changing monitoring state from 'Connecting' to 'Operational'
Send: N0 M110 N0*125
Recv: ok
Send: M115
Recv: FIRMWARE_NAME:Marlin 1.1.0-RC7 (Github) SOURCE_CODE_URL:https://github.com/MarlinFirmware/Marlin PROTOCOL_VERSION:1.0 MACHINE_TYPE:Rumba EXTRUDER_COUNT:1 UUID:8ee39833-9115-4961-a1e8-dbb1a5da35b6
Recv: ok
Send: M105
Recv: ok T:22.4 /0.0 B:22.2 /0.0 @:0 B@:0
```

**Comment by thinkyhead** [comment] 2016-11-17 17:41
The `setup_powerhold` function is only called by `setup` and it does work for you on the initial power-up. Then `setup` is called again when connecting to a host also. So the power pin is being set the same way in both cases. (Looking at `RCBugFix`, but I assume this code hasn't changed.)

First, try connecting a different host (such as the "dumb" serial terminal in Arduino IDE). My thinking is that Octoprint is actually turning off the power. Maybe Octoprint contains an option for the initial on/off state, or has an on-connect GCode script that you can edit.

If that's not the case then try moving the `setup_powerhold();` line to the very end of the `setup` function and see if it makes any difference.

**Comment by a0s** [comment] 2016-11-17 18:39
-- Try moving the setup_powerhold function to the very end of the setup function and see if it makes any difference.
Nothing change

-- called by setup and it does work for you on the initial power-up.
Can't find point of initial call of setup(). 

`OUT_WRITE(PS_ON_PIN, PS_ON_AWAKE)` always break pin state without testing current state, why?

i don't know C language well :(

**Comment by thinkyhead** [comment] 2016-11-17 19:49
No evidence that Octoprint is turning off the power?

**Comment by thinkyhead** [comment] 2016-11-17 19:51
> Can't find point of initial call of `setup()`

It's called automatically. https://www.arduino.cc/en/Reference/Setup

**Comment by thinkyhead** [comment] 2016-11-17 20:01
> always break pin state without testing current state

In code-world this is considered silly:

``` cpp
if (!my_bool) my_bool = true;
```

It's just as efficient, and uses less code, to simply do:

``` cpp
my_bool = true;
```

**Comment by a0s** [comment] 2016-11-17 20:46
Ok, i tried something like

```
bool awake_already = false;

void setup() {
...
if (!awake_already) {
    setup_powerhold();
    awake_already = true;
  }
...
}
```

without any result, hmm

**Comment by a0s** [comment] 2016-11-17 20:58
> No evidence that Octoprint is turning off the power?

Pronterface and OctoPrint have same behaviour, Marlin resets while connecting.

I found https://github.com/MarlinFirmware/Marlin/issues/4041#issuecomment-226082542 :(

**Comment by thinkyhead** [comment] 2016-11-18 04:27
> Ok, i tried something like…

When the board resets, all memory is cleared. Marlin starts over completely. The default state of the power pin on a rebooting Arduino is OFF, so if you were to skip `setup_powerhold` it would simply not turn on the power.

> Pronterface and OctoPrint have same behaviour, Marlin resets while connecting.

Ok, so you find that Pronterface also turns off the 12V power when connecting?

**Comment by boelle** [comment] 2016-11-18 22:03
i just discovered the same

did a flowrate test print and disconnected... nothing happened

but when i connected again marlin resets and power goes off.

its a bit anoying since i dont have a touch probe yet so will have to set height each time :-/

**Comment by thinkyhead** [comment] 2016-11-19 04:50
> but when i connected again marlin resets and power goes off.

Peculiar. It's certainly being turned on in `setup()` whether it's a reboot or a serial connect. I wonder why it works in the one case, but not the other.

You're not using a RUMBA also, are you @boelle? And you also find it does this when connecting through the Arduino IDE's built-in "dumb" serial terminal?

I note that the pin states for each type of PSU are opposite. I don't know if this has any bearing on the issue.

``` cpp
  #if (POWER_SUPPLY == 1)     // 1 = ATX
    #define PS_ON_AWAKE  LOW
    #define PS_ON_ASLEEP HIGH
  #elif (POWER_SUPPLY == 2)   // 2 = X-Box 360 203W
    #define PS_ON_AWAKE  HIGH
    #define PS_ON_ASLEEP LOW
  #endif
```

**Comment by boelle** [comment] 2016-11-19 06:00
nope i use Ramps 1.4 

it did this when connecting from pronterface... ie it resets and 
1) everything is lost 
2) power goes off even if on

i have not tried serial monitor from the IDE but will check later today

EDIT: same if doing serial monitor, it resets

would start to call this a bug instead

and then again...

  #if (POWER_SUPPLY == 1)     // 1 = ATX
    #define PS_ON_AWAKE  LOW
    #define PS_ON_ASLEEP HIGH

is it in ASLEEP state after a reset? if so that part is logical enough as HIGH would make it go off.
as such this would be ok as you dont want it to be on after a reset but only when its told to be on

i would more start to figure why it resets at connect, is that by design?

**Comment by boelle** [comment] 2016-11-19 06:07
maybe this helps... maybe not

```
start
echo: External Reset
Marlin 1.1.0-RCBugFix

echo: Last Updated: 2016-07-26 12:00 | Author: (none, default config)
Compiled: Nov 18 2016
echo: Free Memory: 3121  PlannerBufferBytes: 1200
echo:Hardcoded Default Settings Loaded
```

**Comment by thinkyhead** [comment] 2016-11-19 06:09
On reset or serial connect the same code is run:

``` cpp
    #if ENABLED(PS_DEFAULT_OFF)
      OUT_WRITE(PS_ON_PIN, PS_ON_ASLEEP);
    #else
      OUT_WRITE(PS_ON_PIN, PS_ON_AWAKE);
    #endif
```

Do you find that Marlin 1.0.2-2 also powers off on serial connect?

**Comment by boelle** [comment] 2016-11-19 06:31
So yes... if set to default off it will be off... nothing wrong there. could just change that setting

But why does it reset? should not do that just because the user disconnects and connect 5 sec after

out for a few hours but have the whole weekend for testing

**Comment by thinkyhead** [comment] 2016-11-19 07:54
My comment had nothing to do with `PS_DEFAULT_OFF`. Let me put it another way:

> On reset or serial connect the same code is run:
> 
> ``` cpp
> OUT_WRITE(PS_ON_PIN, PS_ON_AWAKE);
> ```

**Comment by Blue-Marlin** [comment] 2016-11-19 10:33
You'll never get it to work if you try it in software.
It's the same problem as the on heaters during reset with the RAMPS_FD - but in reverse.

During reset the `PS_ON_PIN` is an input - so neither HIGH nor LOW.
The power supply needs a HIGH/LOW to be on.
A 'external' pull up/down resistor likely could solve that.

**Comment by boelle** [comment] 2016-11-19 12:37
yeah but why does it also reset?

**Comment by Blue-Marlin** [comment] 2016-11-19 14:44
The Arduino Mega, and several other boards, are designed that way.
Otherwise you'd have to push a button to flash them.

Google for "Arduino Mega RESET-EN"

https://www.google.de/search?q=Arduino+Mega+RESET_EN&rlz=1C1CHBF_deDE717DE717&oq=Arduino+Mega+RESET_EN&aqs=chrome..69i57j69i64.18215j0j7&sourceid=chrome&ie=UTF-8#q=Arduino+Mega+RESET-EN

**Comment by boelle** [comment] 2016-11-19 15:41
ahh.... thanks. i was paranoid enough that it was a software error

**Comment by a0s** [comment] 2016-11-19 23:42
> The Arduino Mega, and several other boards, are designed that way.

Can i prevent this behaviour (for Rumba) by changing bootloader? Or removing it completly?

**Comment by Blue-Marlin** [comment] 2016-11-20 00:34
If you are really good in soldering try to open the circuit at this capacitor and put a switch in series.
![rrd-rumba_schematics](https://cloud.githubusercontent.com/assets/17075493/20459425/0b3c1154-aec1-11e6-98ef-4e9273368a2c.png)
![rrd-rumba_pcblayer](https://cloud.githubusercontent.com/assets/17075493/20459430/273bc98a-aec1-11e6-932a-d7e144e5d1c5.PNG)
![rrd-rumba](https://cloud.githubusercontent.com/assets/17075493/20459432/2b02190c-aec1-11e6-882c-45c09fadc044.JPG)
**NO** warranty for anything!

**Comment by a0s** [comment] 2016-11-20 12:10
@Blue-Marlin i can but i do not want :)
What if i disable RESET line in usb-serial firmware (http://reprap.org/wiki/File:RRD-RUMBA_SRC_16U2_FIRMWARE.zip) 

```
diff --git a/RUMBA_16U2_USB2Serial/ARDUINO-SERIAL/Arduino-usbserial.c b/RUMBA_16U2_USB2Serial/ARDUINO-SERIAL/Arduino-usbserial.c
index 8e6b0ae..74ca498 100755
--- a/RUMBA_16U2_USB2Serial/ARDUINO-SERIAL/Arduino-usbserial.c
+++ b/RUMBA_16U2_USB2Serial/ARDUINO-SERIAL/Arduino-usbserial.c
@@ -170,10 +170,10 @@ void SetupHardware(void)
 //DEL  TCCR0B = (1 << CS02); //CLOCK/256
 //     TCCR0B = (1 <<CS01) | (1 << CS00); //CLOCK/64
        TCCR0B = (1 << CS01); //CLOCK/8
-
+
        /* Pull target /RESET line high */
-       AVR_RESET_LINE_PORT |= AVR_RESET_LINE_MASK;
-       AVR_RESET_LINE_DDR  |= AVR_RESET_LINE_MASK;
+       // AVR_RESET_LINE_PORT |= AVR_RESET_LINE_MASK;
+       // AVR_RESET_LINE_DDR  |= AVR_RESET_LINE_MASK;
 }
@@ -272,10 +272,10 @@ void EVENT_CDC_Device_ControLineStateChanged(USB_ClassInfo_CDC_Device_t* const C

        if (CurrentDTRState)
        {
-         AVR_RESET_LINE_PORT &= ~AVR_RESET_LINE_MASK;
+         // AVR_RESET_LINE_PORT &= ~AVR_RESET_LINE_MASK;
        }
        else
        {
-         AVR_RESET_LINE_PORT |= AVR_RESET_LINE_MASK;
+         // AVR_RESET_LINE_PORT |= AVR_RESET_LINE_MASK;
        }
 }
```

am i on the right way?

**Comment by a0s** [comment] 2016-11-20 12:15
The one thing that i not understand is why it's named PORTD in the source code 

```
<Value>AVR_RESET_LINE_PORT=PORTD</Value>
<Value>AVR_RESET_LINE_DDR=DDRD</Value>
<Value>AVR_RESET_LINE_MASK=(128)</Value>
```

but connected to port B (PB0) on the schema

**Comment by Blue-Marlin** [comment] 2016-11-20 12:44
Sorry never messed with the software of the usb-serial-converters.

But while tracing the connection between 16U2 and the capacitor, i assumed to have counted wrong.
In the red picture i counted pin 13. That would be Port D Bit 7 - like in the software.
I assume the first picture is wrong or out dated.

However. Your board is what counts.

**Comment by Blue-Marlin** [comment] 2016-11-20 12:51
Looking at your software changes:
I'd leave the initialisation in. Otherwise you have a undefined state again. 

EDITED:
You can leave out the initialisation! There is this pull down resistor.

EDITED:
Or not - if pulling down causes the reset.
Just try it.

**Comment by a0s** [comment] 2016-11-20 12:54
@Blue-Marlin I found more actual schema https://raw.githubusercontent.com/Aus3D/RUMBA-Plus/master/Schematic.png with right reset pin

**Comment by Blue-Marlin** [comment] 2016-11-20 12:58
Oh - nice. So i can count. ;-)
My source was the RepRap Wiki.

**Comment by orangeudav** [comment] 2016-11-20 16:57
@Blue-Marlin i compiled firmware with disabled RESET, but dfu-programmer (and FLIP too) dont want flush it to atmega16u2 :(
[RUMBA_16U2_USB2Serial.hex.zip](https://github.com/MarlinFirmware/Marlin/files/602170/RUMBA_16U2_USB2Serial.hex.zip)

**Comment by a0s** [comment] 2016-11-21 12:35
~Ok, now i can prevent External Reset on host reconnecting, but first connection still causes power down.~
```
diff --git a/RUMBA_16U2_USB2Serial/ARDUINO-SERIAL/Arduino-usbserial.c b/RUMBA_16U2_USB2Serial/ARDUINO-SERIAL/Arduino-usbserial.c
index 8e6b0ae..32d9ad9 100755
--- a/RUMBA_16U2_USB2Serial/ARDUINO-SERIAL/Arduino-usbserial.c
+++ b/RUMBA_16U2_USB2Serial/ARDUINO-SERIAL/Arduino-usbserial.c
@@ -276,6 +276,6 @@ void EVENT_CDC_Device_ControLineStateChanged(USB_ClassInfo_CDC_Device_t* const C
        }
        else
        {
-         AVR_RESET_LINE_PORT |= AVR_RESET_LINE_MASK;
+         //AVR_RESET_LINE_PORT |= AVR_RESET_LINE_MASK;
        }
 }
```
[RUMBA_16U2_USB2Serial.hex.zip](https://github.com/MarlinFirmware/Marlin/files/603534/RUMBA_16U2_USB2Serial.hex.zip)
~and if we disable first external reset too, octoprint cant complete handshake on connecting~

upd: it is not working as expecting and broke octoprint's handshake procedure

By the way, arduino ide generates wrong command line for ArduinoISP. True commands are
atmega16u2:
```
avrdude -C avrdude.conf -vvv -p m16u2 -c avrisp -P /dev/cu.usbmodem1421 -b 19200 -e -U flash:w:RUMBA_16U2_USB2Serial.hex:i
```
atmega2560:
```
avrdude -C avrdude.conf -vvv -p m2560 -c avrisp -P /dev/cu.usbmodem1421 -b 19200 -U flash:w:Marlin.ino.hex:i -U lfuse:w:0xff:m -U hfuse:w:0x10:m -U efuse:w:0xfd:m
```

**Comment by ntoff** [comment] 2016-11-21 12:58
The easy way to disable the Mega's auto reset is to whack a capacitor between reset and ground

http://forum.arduino.cc/index.php?topic=28167.msg208351#msg208351

Worked for me

**Comment by macst34** [comment] 2016-11-23 18:28
I have a mega 2560 and ramps 1.4 setup. This issue that orangeudav pointed out bothered me to no end since the mega resets whenever I a) plug in usb or when I b) open cura or anything else connects to the 2560's com port.

Now this doesn't matter if the printer is idle, but if I am printing from the sdcard at that moment, it stops printing in its tracks resulting in a failed print.

I did this mod by adding a 10uF as ntoff suggested. I also added a tiny switch so I can change behavior on the fly in case i need to flash the firmware some more without having to time the reset button push. 

Since I didn't really want to solder on the mega, I wirewrapped some connections to RESET and GND on the underside of the ramps and put the switch on a little pcb that I fixed to ramps by soldering on longer pins for Aux3 so they extend to the underside of ramps (the connection is only physical, I just didn't want to have the switch separate from the ramps board and I definitely didn't want to drill the ramps or kludge and hotglue the pcb on)

here are some pix:

before:
![2016-11-22 11 19 27](https://cloud.githubusercontent.com/assets/5762387/20573099/3032412e-b1e9-11e6-85ee-6815d4fdce74.jpg)

after:
![2016-11-24 00 04 47](https://cloud.githubusercontent.com/assets/5762387/20573102/35640f42-b1e9-11e6-9bbc-568a145fe011.jpg)
the little round pcb under the LCD connection has the 10uF cap and a switch to select behavior.

I'd show you the underside, but i'd have to take it apart again when I just put it back together.

Anyways, the wiring is so simple:

RST----10uF---switch---GND

Anyways, for the rumba, I'd try blue_marlins's advice and tombstone that cap and rig a switch inline. You could probably mount the switch by soldering it to the micro usb grounding pads.

For added fun: If you look closely, you'll see single pin headers for PS_ON, VCC and GND because I added a relay to my elcheapo 12v power supply so I can turn it on using marlin's PS_ON capability from the LCD or with M80.

happy hacking,
macst34

**Comment by thinkyhead** [comment] 2016-11-26 04:53
For OctoPrint, I note that you can supply commands to be sent to the printer [when connected](http://docs.octoprint.org/en/master/configuration/config_yaml.html#events) by editing its configuration file. You can just add an `M80` for `event: Connected`, if hacking the hardware is too much trouble.
```yaml
events:
  subscriptions:
    # example event consumer that prints a message to the system log if the printer is disconnected
    - event: Disconnected
      command: "logger 'Printer got disconnected'"
      type: system

    # example event consumer that queries printer information from the firmware, prints a "Connected"
    # message to the LCD and homes the print head upon established printer connection, disabled though
    - event: Connected
      command: M115,M117 printer connected!,G28
      type: gcode
      enabled: False
```

**Comment by macst34** [comment] 2016-11-26 05:02
@thinkyhead.... if octoprint connects, the rumba resets because of DTR being sent over USB. Issuing a m80 from the octoprint would not be possible because the reset causes the power supply to switch off which cuts power to the rumba and the Octo.

This is why this has devolved into soldering and switches for this issue.

Michael

**Comment by thinkyhead** [comment] 2016-11-26 09:48
@macst34 I see. I'm used to boards with a diode allowing concurrent 5V and 12V power. It's interesting that we now have setups where `M80` can never be used.

**Comment by macst34** [comment] 2016-11-26 19:40
What follows is a summary and what I beleive is the is the definitve answer(s) to close this issue.

@thinkyhead dual power supplies still does not prevent this issue totally. Default behavior of the MEGA 2560 and derivatives is to reset when DTR is encountered. The issue arises when you use a power supply that heeds the PS_ON pin and you are powering your logic off the same PS. When the Mega/Rumba is reset, PS_ON is momentarily pulled high which cuts off the board's own power supply.  This happens regardless if you define PS_DEFAULT_OFF or not in Marlin's configuration.h, because after the reset, nothing is parsed because there is no power to anything. 

In some setups, the board may be still powered by the ATX PS's standby 5v. In this case, if PS_DEFAULT_OFF is defined, PS_ON stays high and the PS continues to be off. If PS_DEFAULT_OFF is not defined, PS_ON gets pulled low and the PS turns on. But this step never executes in @orangeudav's scenario since the power to everything is already off and this logic is never run.

Like @Blue-Marlin said, you can prevent the default reset behavior of the MEGA by cutting the RESET_EN trace, but this means you have to hit the reset button yourself when you are flashing a MEGA with RESET_EN cut. This is a pain in the ass, but doable. For @orangeudav, this does not apply because the rumba has no reset trace on that board (though you can unsolder the C16 resistor that @Blue-marlin mentioned which I believe is equivalent to cutting RESET_EN on the MEGA.)

Hey @orangeudav, what @thinkyhead said got me thinking, there is probably another solution for you. Power your octoprint/cubieboard and the rumba (just for the logic) with a separate 5V PS since you don't want to use the standby 5V from the ATX PS.  That way you can connect to the octoprint and then issue a M80 to the rumba which should kick your ATX PS on. The diode protection that @thinkyhead mentioned should let you run both power supplies concurrently.

This comes with with one caveat, if you are printing something, it's gonna fail when you connect to the rumba from octoprint/cubieboard since DTR is still sent and the rumba resets. At least in this case, you can turn the 12V PS back on remotely since octoprint can still talk to your rumba. For me, I didn't really care about the reset behavior, except(!) when it broke my in-process print. So I went the route of adding a switch and cap to prevent the default behavior of the board when encountering a DTR. If you don't care about the rumba resetting, just get another 5v power supply for the cubieboard and rumba. If you don't want printing to stop like me, you still got to break out the soldering iron and do some

happy hacking,
Michael

ps. @orangeudav, you probably seen this before, but if you didn't, it's pretty close to what you want. 
Just remember to add the secondary always-on 5v PS and  :%s/Ramps/Rumba/ | %s/PI/cubieboard/
https://github.com/foosel/OctoPrint/wiki/Control-your-printer's-ATX-PSU-through-a-RAMPS-board-using-OctoPrint

**Comment by a0s** [comment] 2016-11-26 22:31
Good summary, @macst34, thank you!

> Power your octoprint/cubieboard and the rumba (just for the logic) with a separate 5V PS since you don't want to use the standby 5V from the ATX PS.

Yep, this is my starting point for this topic ;) The problem is that i have bad quality of 220V/110V AC power, and sometimes OctoPrint randomly (after switching off the motor of the refrigerator :) ) hung and broke current printing, but ATX PS feels good in the same time.

As i understand, another option to prevent USB's resets is ... not using USB completely (exclude usb-serial 16u2, who generate resets signals)! I have hardware UART on the OctoPrint's host. And i can solder wires directly to atmega2560's tx/rx pins. And, perhaps, i need a levels converter.

**Closed as completed** 2016-11-26 22:32 UTC
Labels: C: Hosts & Protocols

**Comment by Blue-Marlin** [comment] 2016-11-26 22:44
An other way could be to invert the PS_ON signal between Arduino output and ps-input and then changing the config to a X-Box-ps witch has the reverse logic.

**Comment by thinkyhead** [comment] 2016-11-27 00:24
> if you are printing something, it's gonna fail when you connect 

For me this has always been expected behavior. It is the norm with most RepRaps.

**Comment by Andrei-Pozolotin** [comment] 2017-06-02 03:51
try 
```
stty -F /dev/ttyACM0 -hupcl
```
to disable CTS -> RESET action
