### ISSUE TITLE
MaxFeedrate not being enforced by Marlin 2

### ISSUE THREAD

**Issue by bryanhunwardsen** [MarlinFirmware/Marlin#19020] opened 2020-08-14 07:05 UTC
### Bug Description

Marlin FW configured max feedrate is not being applied causing extruder skipping.

### My Configurations

I have replicated this on Ender3V2 with stock Creality Board running 2.0.6 release, I then swapped in an SKR mini E3 V2.0 with its stock Ender firmware and the problem remains. M203 shows an E value of 50, Sending G1 E150 F300 to the printer results in extruder skipping as the hotend cannot keep with that feedrate.

### Steps to Reproduce
1) Preheat to 210 for PLA
2) Send printer: G1 E150 F300
**Expected behavior:** [What you expect to happen]
1) FW limits extrusion to a Feed rate of 50 (or whatever is stored on the printer for E)
**Actual behavior:** [What actually happens]
Extrusion happens at 300 feedrate well over the maxfeedrate value set in Marlin
#### Additional Information
N/A

**Comment by ellensp** [comment] 2020-08-14 07:36
Duplicate of 19021

**Closed as completed by ellensp** 2020-08-14 07:36 UTC
