### ISSUE TITLE
Power input requirement

### ISSUE THREAD

**Issue by sarf2k4** [MarlinFirmware/Marlin#3590] opened 2016-04-22 04:46 UTC
This isn't much of an issue though, it's only based on what I experienced.

I have the following setup for my 3d printer
- ramps 1.4
- towerpro sg9s servo for auto bed leveling
- 12v system
- e3d v6 + fan hooked on ramps 1.4
- pwm fan setup
- RRD 2004 lcd
- heated bed

When I was using rc2-rc3, my major issues was to have the printer start to print right after g29. So I did power my mega with additional usb power input from usb charger or my laptop just to get the printer started printing after g29 command.

After upgraded to rc4/rc5 (I think currently rc5 for sure), I noticed that I didn't need the extra usb power input anymore just to get the printer start printing right after g29. My assumption is that some of the codes inside might be messed up that were cleaned somewhere rc4-rc5 to optimize the power requirement for the board.

I thought at first it is a common thing to have such setup that I would need extra power but I was wrong. I wonder if anyone able to confirm this?

**Comment by jbrazio** [comment] 2016-04-22 09:40
Could you please show us a serial log when it refuses to print after a `G29` ?

**Comment by sarf2k4** [comment] 2016-04-22 09:54
There are no logs (as far as I know of), because the printer doesn't want to move. I often do sd card printing. If I use pronterface it means I'm giving extra usb power input to the main board and the printer will move normally the way it should be

**Comment by jbrazio** [comment] 2016-04-22 11:00
You should connect a serial terminal like the Arduino IDE serial monitor and start the SD printing.

**Comment by Blue-Marlin** [comment] 2016-04-22 11:15
Could be caused by a defect D1 diode on the RAMPS.

**Comment by sarf2k4** [comment] 2016-04-22 11:32
I don't know though, but it's okay already since using rc5

**Comment by jbrazio** [comment] 2016-05-04 15:43
Thank you for your interest making Marlin better and reporting this issue but this topic has been open for a long period of time without any further development. Marlin has been under heavy development for the past couple of months and moving to it's last mile to finish the RC cycle and release **Marlin v1.1.0**. We suggest you to try out the latest [RCBugfix](https://github.com/MarlinFirmware/Marlin/archive/RCBugFix.zip) branch and reopening this issue if required.

**Closed as completed by jbrazio** 2016-05-04 15:43 UTC
Labels: T: Question
