### ISSUE TITLE
[BUG] V-Tool T1 is set to 0:0%

### ISSUE THREAD

**Issue by iatwalrus** [MarlinFirmware/Marlin#17709] opened 2020-04-25 19:08 UTC
When attempting to print **not** using virtual extruders in GCode, but using tool change references (T0, T1, etc.), the printer will lockup when selecting T1 as the extruder to print from. I noticed in the Mixer menu, if you set Active V-Tool to 1, the mix is set to 0:0%, and this needs to default to 0:100%. It can be manually adjusted and saved, but the default should be edited. All other tools have an appropriate default percentage. This way when the firmware is installed, manual configuration of this setting is not required and it will work using tool references in GCode instead of virtual

**Comment by firepower9966** [comment] 2020-04-29 15:45
I also can confirm this bug. end up editing my cura post processing scrips to set correct mix ratio for T1 to 0:100% when T1  was found in Gcode.

**Comment by lterrill** [comment] 2020-04-30 12:04
Duplicate of #17635, patched in bugfix-2.0.x branch

**Closed as completed** 2020-06-20 22:59 UTC
