### ISSUE TITLE
[2.0.X] DUE with MAX6675 compile error

### ISSUE THREAD

**Issue by pbrgle1** [MarlinFirmware/Marlin#8789] opened 2017-12-15 13:37 UTC
I'm getting the following compile error. I attached my config files below.
```
Arduino: 1.8.5 (Windows 10), Board: "Arduino Due (Programming Port)"

In file included from sketch\src\module\temperature.cpp:35:0:

sketch\src\module\../libs/private_spi.h: In static member function 'static uint8_t SPIclass<50u, 51u, 52u>::receive()':

sketch\src\module\../libs/private_spi.h:50:7: error: 'SPDR' was not declared in this scope

       SPDR = 0;

       ^

In file included from sketch\src\module\thermistor/../../inc/MarlinConfigPre.h:27:0,

                 from sketch\src\module\thermistor/../../inc/MarlinConfig.h:26,

                 from sketch\src\module\thermistor/thermistors.h:26,

                 from sketch\src\module\temperature.h:30,

                 from sketch\src\module\temperature.cpp:27:

sketch\src\module\../libs/private_spi.h:51:19: error: 'SPSR' was not declared in this scope

       for (;!TEST(SPSR, SPIF););

                   ^

sketch\src\module\thermistor/../../inc/../core/macros.h:101:22: note: in definition of macro 'TEST'

 #define TEST(n,b) (((n)&_BV(b))!=0)

                      ^

sketch\src\module\../libs/private_spi.h:51:25: error: 'SPIF' was not declared in this scope

       for (;!TEST(SPSR, SPIF););

                         ^

sketch\src\module\thermistor/../../inc/../core/macros.h:99:24: note: in definition of macro '_BV'

   #define _BV(n)  (1<<(n))

                        ^

sketch\src\module\../libs/private_spi.h:51:14: note: in expansion of macro 'TEST'

       for (;!TEST(SPSR, SPIF););

              ^

exit status 1
Error compiling for board Arduino Due (Programming Port).


[Configuration_adv.txt](https://github.com/MarlinFirmware/Marlin/files/1562789/Configuration_adv.txt)
[Configuration.txt](https://github.com/MarlinFirmware/Marlin/files/1562790/Configuration.txt)
```

**Comment by thinkyhead** [comment] 2017-12-15 21:24
It appears you are using a MAX6675 Thermocouple with a DUE board. I'm not sure if that's been made to work yet.

**Comment by pbrgle1** [comment] 2017-12-16 17:38
It's actually the MAX31855.

Now i have a new issue. I changed the sensort to Semitec (sensor 5) and the second extruder reads 488. (actually 12°C). When i unplug it reads 499. I think it's just reversed because of the 12 difference. I tried swapping the first end second sensor but it's always T1 that reads 488...

**Comment by thinkyhead** [comment] 2018-02-11 02:05
Has the 32-bit brigade made any progress here?

**Comment by DarioX7** [comment] 2018-08-12 20:27
Will this problem be fixed? I have a new board for Arduino DUE with 2 pieces of MAX6675 and I have the same problem with the compilation.

**Comment by xarwell** [comment] 2018-08-16 19:26
I also have the same problem.

**Comment by DvDriel** [comment] 2018-10-25 13:05
Same here, any progress?

**Comment by thinkyhead** [comment] 2018-10-26 10:37
I picked up a clue from http://forum.arduino.cc/index.php?topic=267937.0

> "`SPDR` on the Uno is `REG_SPI0_RDR` on the Due and `SPSR` on the Uno is like `REG_SPI0_SR` on the Due."

…So we just need to experiment with those by doing this in the Due HAL:
```cpp
#define SPDR REG_SPI0_RDR
#define SPSR REG_SPI0_SR
```
…and figuring out where to connect things up. Not sure what `SPIF` is yet.

**Comment by DarioX7** [comment] 2019-02-05 22:44
> 
> 
> I picked up a clue from http://forum.arduino.cc/index.php?topic=267937.0
> 
> > "`SPDR` on the Uno is `REG_SPI0_RDR` on the Due and `SPSR` on the Uno is like `REG_SPI0_SR` on the Due."
> 
> …So we just need to experiment with those by doing this in the Due HAL:
> 
> ```c++
> #define SPDR REG_SPI0_RDR
> #define SPSR REG_SPI0_SR
> ```
> 
> …and figuring out where to connect things up. Not sure what `SPIF` is yet.

Hey.
So, whether it is known under which register is assigned `SPIF` ?

**Comment by thinkyhead** [comment] 2019-02-06 02:03
See if the issue is resolved by the above-linked PR.

**Comment by DarioX7** [comment] 2019-02-06 20:34
> 
> 
> See if the issue is resolved by the above-linked PR.

Thank you for fast help.
I downloaded the new version of Marlin 2.0 (bugfix) with your patches where I imported to PlatformIO IDE for Atom.
In the Configuration.h file for the quick test, I set only the board definitions (based on DUE3DOM).
https://pastebin.com/TGWxF22A
And I set the MAX6675 type for hotend E0.
The compilation was successful, the firmware uploaded correctly, but unfortunately Arduino DUE all the time resetting itself over and over again. The display showed only the start logo.
https://pastebin.com/MD6r2802
I will try to somehow debug it, why it happens.
```
> start
> echo: Software Reset
> Marlin busmatch (EEPROM=? Marlin=V64)
> echo:Hardcoded Default Settings Loaded
> mory: 82140  PlannerBufferBytes: 1600
> echo:EEPROM version mismatch (EEPROM=? Marlin=V64)
> echo:Hardcoded Default Settings Loaded
> start
> echo:PowerUp
> Marlin bugfix-2.0.x
> 
> echo: Last Updated: 2018-01-20 | Author: @brandstaetter, @grbd
> echo:Compiled: Feb  7 2019
> echo: Free Memory: 82140  PlannerBufferBytes: 1600
> echo:EEPROM version mismatch (EEPROM=? Marlin=V64)
> echo:Hardcoded Default Settings Loaded
> start
> echo: Watchdog Reset
> Marlin bugfix-2.0.x
> 
> echo: Last Updated: 2018-01-20 | Author: @brandstaetter, @grbd
> echo:Compiled: Feb  7 2019
> echo: Free Memory: 82140  PlannerBufferBytes: 1600
> echo:EEPROM version mismatch (EEPROM=? Marlin=V64)
> echo:Hardcoded Default Settings Loaded
> start
> echo: Watchdog Reset
> Marlin bugfix-2.0.x
> 
> echo: Last Updated: 2018-01-20 | Author: @brandstaetter, @grbd
> echo:Compiled: Feb  7 2019
> echo: Free Memory: 82140  PlannerBufferBytes: 1600
> echo:EEPROM version mismatch (EEPROM=? Marlin=V64)
> echo:Hardcoded Default Settings Loaded
> start
> echo: Watchdog Reset
> Marlin bugfix-2.0.x
> 
> echo: Last Updated: 2018-01-20 | Author: @brandstaetter, @grbd
> echo:Compiled: Feb  7 2019
> echo: Free Memory: 82140  PlannerBufferBytes: 1600
> echo:EEPROM version mismatch (EEPROM=? Marlin=V64)
> echo:Hardcoded Default Settings Loaded
```

**Comment by DarioX7** [comment] 2019-02-24 11:26
I give up.
I do not have that knowledge to find the reason for reboots.
Anyone help?

**Comment by thinkyhead** [comment] 2019-03-03 10:58
For additional help with configuration and troubleshooting, please use the following resources:

- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

**Comment by asdjkljlf** [comment] 2019-05-03 06:33
> I give up.
> I do not have that knowledge to find the reason for reboots.
> Anyone help?


If you enable //SDSUPPORT, Watchdog Reset will not occur.
But when I moved or heated, "Printer Kill halted" occurred (max6675)
"Short to GND" error occurred in max31855

**Comment by boelle** [comment] 2019-06-22 09:17
@thinkyhead Another one that needs to be closed. Sorry, I got bored.

**Closed as completed** 2019-07-06 03:58 UTC
Labels: T: HAL & APIs
