### ISSUE TITLE
exit status 1 pasting "/* SPI Master In Slave Out pin*/" and "_DDR" does not give a valid preprocessing token

### ISSUE THREAD

**Issue by REVIEWGAMINGMAN** [MarlinFirmware/Marlin#11712] opened 2018-09-03 12:16 UTC
### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

#### Additional Information

* Include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/contributing.md#how-can-i-contribute) for additional guidelines.

**Comment by cjsoong** [comment] 2018-09-03 13:22
@REVIEWGAMINGMAN Do not use arduino ide v1.86 to change back to V1.85

**Comment by brandstaetter** [comment] 2018-09-03 18:20
if you move the comments to their own line, it compiles successfully #workaround

**Comment by oakdesign** [comment] 2018-09-04 08:25
Known Bug in Arduino v1.8.6 gcc 
https://github.com/MarlinFirmware/Marlin/pull/11647

**Comment by thinkyhead** [comment] 2018-09-04 08:38
Duplicate of #10862

**Closed as completed by thinkyhead** 2018-09-04 08:38 UTC
Labels: C: Build / Toolchain
