### ISSUE TITLE
[BUG] MKS Robin Nano V2 timer conflict

### ISSUE THREAD

**Issue by trashypopashy** [MarlinFirmware/Marlin#20527] opened 2020-12-20 23:37 UTC
### Bug Description

When trying to compile the latest Marlin bugfix 2.0.x, I am running into the Issue:
"Marlin\src\HAL\STM32\timers.cpp:281:41: error: static assertion failed: One or more timer conflict detected
  281 | static_assert(verify_no_duplicate_timers(), "One or more timer conflict detected")"

This happens, when using "default_envs = mks_robin_nano35_stm32" in platformio.ini(because i have a Robin Nano V2). When I try compiling with "default_envs = mks_robin_nano35", it shows no errors.

I have not tried to flash the compilable firmware with "default_envs = mks_robin_nano35", as I am afraid of bircking the board.

### Configuration Files

[config-files.zip](https://github.com/MarlinFirmware/Marlin/files/5721708/config-files.zip)

My configurations-files, I uploaded have many changes, but the behaviour was not occurnig when I compiled my firmware 5 months ago.

### Steps to Reproduce

Use my config.files.

**Expected behavior:**

Should compile fine.

**Actual behavior:**

shows error: "Marlin\src\HAL\STM32\timers.cpp:281:41: error: static assertion failed: One or more timer conflict detected
  281 | static_assert(verify_no_duplicate_timers(), "One or more timer conflict detected")"

**Comment by trashypopashy** [comment] 2020-12-20 23:41
Here's the .zip
[config-files.zip](https://github.com/MarlinFirmware/Marlin/files/5721694/config-files.zip)

**Comment by rhapsodyv** [comment] 2020-12-20 23:44
Duplicate of #20387

**Closed as completed by rhapsodyv** 2020-12-20 23:44 UTC
