### ISSUE TITLE
Compilation error when EXTRUDERS 2

### ISSUE THREAD

**Issue by clefranc** [MarlinFirmware/Marlin#1523] opened 2015-02-21 21:12 UTC
Just downloaded the latest development version, default configurations:

EXTRUDERS 1 & PIDTEMP = compilation OK
EXTRUDERS 2 & PIDTEMP = compilation error
EXTRUDERS 2 & no PIDTEMP = compilation OK

Error detail:

```
temperature.cpp: In function 'void manage_heater()':
temperature.cpp:721:1: error: unable to find a register to spill in class 'POINTER_REGS'
 }
 ^
temperature.cpp:721:1: error: this is the insn:
(insn 98 97 100 4 (set (reg/v:SF 103 [ pid_input ])
        (mem:SF (post_inc:HI (reg:HI 141 [ ivtmp.170 ])) [4 MEM[base: _101, offset: 0B]+0 S4 A8])) temperature.cpp:505 99 {*movsf}
     (expr_list:REG_INC (reg:HI 141 [ ivtmp.170 ])
        (nil)))
temperature.cpp:721: confused by earlier errors, bailing out
Error compiling.
```

**Comment by thinkyhead** [comment] 2015-02-22 02:29
@clefranc Just fixed some typos in temperature.cpp that might have been causing that. Try the very latest Development head.

**Comment by clefranc** [comment] 2015-02-22 03:04
@thinkyhead Nope

```
temperature.cpp: In function 'void manage_heater()':
temperature.cpp:719:1: error: unable to find a register to spill in class 'POINTER_REGS'
 }
 ^
temperature.cpp:719:1: error: this is the insn:
(insn 98 97 100 4 (set (reg/v:SF 103 [ pid_input ])
        (mem:SF (post_inc:HI (reg:HI 147 [ ivtmp.209 ])) [4 MEM[base: _113, offset: 0B]+0 S4 A8])) temperature.cpp:503 99 {*movsf}
     (expr_list:REG_INC (reg:HI 147 [ ivtmp.209 ])
        (nil)))
temperature.cpp:719: confused by earlier errors, bailing out
Error compiling.
```

**Comment by thinkyhead** [comment] 2015-02-22 03:20
Hmm, any other settings involved? If I do `PIDTEMP` and `EXTRUDERS 2` alone I don't get the error. I'll poke around...

**Comment by clefranc** [comment] 2015-02-22 03:35
Downloaded the whole firmware, just change EXTRUDERS from 1 to 2, get compile error. Removing PIDTEMP gives no error.

Arduino 1.5.8 / Windows 7 x64

**Comment by thinkyhead** [comment] 2015-02-22 03:36
Internet forums suggest there may be funky characters messing with the compiler. Try replacing the end of manage_heater with freshly-pasted code and see if it fixes it.

```
//code for controlling the extruder rate based on the width sensor
#ifdef FILAMENT_SENSOR
if (filament_sensor) {
  meas_shift_index = delay_index1 - meas_delay_cm;
  if (meas_shift_index < 0) meas_shift_index += MAX_MEASUREMENT_DELAY + 1;  // loop around buffer if needed
  // get the delayed info and add 100 to reconstitute to a percent of
  // the nominal filament diameter then square it to get an area
  meas_shift_index = constrain(meas_shift_index, 0, MAX_MEASUREMENT_DELAY);
  float newvm = pow((measurement_delay[meas_shift_index] + 100.0) / 100.0, 2);
  if (newvm < 0.01) newvm = 0.01;
  volumetric_multiplier[FILAMENT_SENSOR_EXTRUDER_NUM] = newvm;
}
#endif
```

**Comment by clefranc** [comment] 2015-02-22 03:46
Tried the code above: error.
Copied entire .cpp from github: error.

Will downgrade the IDE now...

EDIT: mean upgrade

**Comment by clefranc** [comment] 2015-02-22 03:53
Arduino 1.6.0, still compile error!

**Comment by thinkyhead** [comment] 2015-02-22 06:00
Hmm, what if you do some tweaking to the text, such as de-tabbing, and changing the line-endings to Windows, then to Unix, to get them all consistent... Does that make any difference? I suppose there could be something like a missing close-parenthesis, but it's just such a weird error...

(I'm using 1.5.2 on OS X.)

**Comment by clefranc** [comment] 2015-02-22 11:23
In temperature.cpp, there is no error if I comment line 530 & 533.

**Comment by thinkyhead** [comment] 2015-02-22 11:54
How about [this one](https://github.com/thinkyhead/Marlin/blob/cleanup_temperature/Marlin/temperature.cpp)?

**Comment by clefranc** [comment] 2015-02-22 12:38
Tried your branch on my computer and another computer: same error
Tried the official development branch on my computer and another computer: same error

Just saw the new issue https://github.com/MarlinFirmware/Marlin/issues/1529

I uncomment the Thermal Runaway Protection, compilation error gone...

**Comment by Vi3jo** [comment] 2015-02-24 13:50
Arduino 1.6.0, 1 extruder: no error
Arduino 1.6.0, >1 extruder: error
Arduino 1.0.6, 1 extruder: no error
Arduino 1.0.6, >1 extruder: no error

Possibly problem is in the compiler Arduino

**Comment by thinkyhead** [comment] 2015-02-24 19:30
@Arandir That is my conclusion, as well. It's too bad that 1.6.0 is displaying this behavior. Maybe if we share this with @Arduino they can find and fix the compiler issue, but I am sure it's a tricky bug to find. In the meantime, try rearranging the code, running filters on it to remove whitespace, extra line-endings, and invisible characters.... Anything to coerce the compiler into choking differently or (ideally) not choking.

**Comment by nophead** [comment] 2015-02-24 20:47
Changing whitespace, line endings, etc will have no effect. This is back end compiler bug where it is trying to fit instructions and registers to the semantic representation of the code, long after lexical and syntax analysis. The only thing that will work around it is code changes that mean it needs less registers.

**Comment by emartinez167** [comment] 2015-02-24 21:41
I have been doing some searches and this bug is not exclusive to Arduino,
but rather to the toolset behind it. Try googling it!

**Comment by thinkyhead** [comment] 2015-02-24 22:14
@nophead Sometimes these errors really are spurious, but I am certainly willing to look closely at the scope where this error is arising and count registers. I'm dubious, because I actually do not get these errors. Moreover I have yet to find a reference via Google where this _wasn't_ spurious, but actually, _traceably_, caused by too many registers. Also, I can't see why the implicated code region _would_ require more registers than other, more complex code regions.

@emartinez167 I thought, as I was writing, that this is really a gcc problem, and really the Arduino geeks probably don't want to go there!

**Comment by nophead** [comment] 2015-02-25 09:57
@thinkyhead,
  Yes they are always spurious because they are a compiler bug in the back end that is specific to the AVR. What I mean is it is at the last part of the compiler where it is fitting instructions and allocating registers. Changes to white space, etc, won't affect it because the representation the compiler is working in on at that stage is register transfer logic. White space doesn't even get the the AST.

See http://en.wikibooks.org/wiki/GNU_C_Compiler_Internals/GNU_C_Compiler_Architecture_3_4#Main_Representations

Things that will affect it is the complexity of the code after it is has been converted to RTL and optimised and the number of pointers it needs to keep live at the same time.

**Comment by emartinez167** [comment] 2015-02-25 10:02
Are there any compiler flags we can set to change the optimization, or is
that going to break even more stuff?

**Comment by thinkyhead** [comment] 2015-02-26 05:23
@nophead @emartinez167 An interesting problem to solve, anyway… and weird that I don't get the compile bug with 1.0.5 or 1.5.2. (About to try 1.6.0.)

Well, I will mess with it now, as I'm re-flashing my RAMPS, and see what happens…

**Comment by nophead** [comment] 2015-02-26 13:01
Are you using the same version of gcc as the OP? A big problem is when you run Arduino on Windows you use the version bundled with it but on Linux you use the version of AVR installed system wide.

**Comment by thinkyhead** [comment] 2015-02-27 00:13
@nophead I'm using OS X and on this platform every version of Arduino comes with its own build of gcc (and other tools) inside the application bundle. I presume that Arduino is using the gcc that it comes bundled with.

**Comment by nophead** [comment] 2015-02-27 08:24
Well as this is a compiler bug and if you don't get it with the same source
code the most likely explanation is you are using a different version of
the compiler or different command line flags.

**Comment by thinkyhead** [comment] 2015-02-27 15:20
@nophead I have confirmed that Arduino is building using the toolchain in its bundle, as it should. I won't paste the build log here, but in verbose mode it's quite clear.

Using the settings `EXTRUDERS == 2 && PIDTEMP` I get no error when building with Arduino 1.5.2, Arduino 1.0.5, or UECIDE 0.8.7z36, but I do get an error consistently with Arduino 1.6.0.

FWIW The only trick I have found to get rid of the error is to comment out lines 529-535 in temperature.cpp. Make of that what you will! I haven't found any way to tweak those lines (so far) that eliminates the error. Perhaps someone else can mess with them and see if anything makes a difference.

**Comment by chron0** [comment] 2015-03-02 10:48
Had the same issue and "worked" on temperature.cpp with dos2unix and tabs to spaces -> spaces to tabs. Afterwards it compiled, can you check if that solves your issues too? https://github.com/apollo-ng/Marlin/commit/fb75a9272da33ea0a9f2793a1fc89b69428d103c

**Comment by Dimonira** [comment] 2015-03-08 15:53
I did so. File temperature.cpp.
1. Uncomment this lines:

```
// static float pid_input[EXTRUDERS];
// static float pid_output[EXTRUDERS];
```

and edit their (delete [EXTRUDERS]):

```
static float pid_input;
static float pid_output;
```
1. Comment out or delete line(s) in manage_heater() function:
   
    float pid_input, pid_output;

That's all.

**Comment by chron0** [comment] 2015-03-08 16:03
It's already been fixed by @thinkyhead in a heavy rework of temperature.cpp which is already merged and tested in pr-felix, that's why it was reverted :)

**Comment by thinkyhead** [comment] 2015-03-09 04:08
@Dimonira Are you getting the same compiler issue with the latest Development code? Or, are you getting a different error?

**Comment by Dimonira** [comment] 2015-03-09 13:50
@thinkyhead 
Yes, with the latest Development code and EXTRUDERS=2 (nothing else is changed) and Arduino 1.6.0 I get this same error:

```
Arduino: 1.6.0 (Windows 8), Плата"Arduino Mega or Mega 2560, ATmega2560 (Mega 2560)"

temperature.cpp: In function 'void manage_heater()':
temperature.cpp:726:1: error: unable to find a register to spill in class 'POINTER_REGS'
 }
 ^
temperature.cpp:726:1: error: this is the insn:
(insn 103 102 105 4 (set (reg/v:SF 105 [ pid_input ])
        (mem:SF (post_inc:HI (reg:HI 140 [ ivtmp.169 ])) [4 MEM[base: _98, offset: 0B]+0 S4 A8])) temperature.cpp:543 99 {*movsf}
     (expr_list:REG_INC (reg:HI 140 [ ivtmp.169 ])
        (nil)))
temperature.cpp:726: confused by earlier errors, bailing out
```

It is noteworthy that in the latest version (download right now), my version of the "patch" does not help.

**Comment by Dimonira** [comment] 2015-03-09 15:29
After these changes Arduino 1.6.0 was compiled without error. I moved part of the code from the for-loop to the separate function get_pid_output(int e) (variable pid_input replaced its value current_temperature[e] in new function and current_temperature_bed in manage_heater()):

``` cpp
float get_pid_output(int e)
{
  float pid_output;
  #ifdef PIDTEMP
    #ifndef PID_OPENLOOP
      pid_error[e] = target_temperature[e] - current_temperature[e];
      if (pid_error[e] > PID_FUNCTIONAL_RANGE) {
        pid_output = BANG_MAX;
        pid_reset[e] = true;
      }
      else if (pid_error[e] < -PID_FUNCTIONAL_RANGE || target_temperature[e] == 0) {
        pid_output = 0;
        pid_reset[e] = true;
      }
      else {
        if (pid_reset[e] == true) {
          temp_iState[e] = 0.0;
          pid_reset[e] = false;
        }
        pTerm[e] = PID_PARAM(Kp,e) * pid_error[e];
        temp_iState[e] += pid_error[e];
        temp_iState[e] = constrain(temp_iState[e], temp_iState_min[e], temp_iState_max[e]);
        iTerm[e] = PID_PARAM(Ki,e) * temp_iState[e];

        //K1 defined in Configuration.h in the PID settings
        #define K2 (1.0-K1)
        dTerm[e] = (PID_PARAM(Kd,e) * (current_temperature[e] - temp_dState[e])) * K2 + (K1 * dTerm[e]);
        pid_output = pTerm[e] + iTerm[e] - dTerm[e];
        if (pid_output > PID_MAX) {
          if (pid_error[e] > 0) temp_iState[e] -= pid_error[e]; // conditional un-integration
          pid_output = PID_MAX;
        }
        else if (pid_output < 0) {
          if (pid_error[e] < 0) temp_iState[e] -= pid_error[e]; // conditional un-integration
          pid_output = 0;
        }
      }
      temp_dState[e] = current_temperature[e];
    #else
      pid_output = constrain(target_temperature[e], 0, PID_MAX);
    #endif //PID_OPENLOOP

    #ifdef PID_DEBUG
      SERIAL_ECHO_START;
      SERIAL_ECHO(MSG_PID_DEBUG);
      SERIAL_ECHO(e);
      SERIAL_ECHO(MSG_PID_DEBUG_INPUT);
      SERIAL_ECHO(current_temperature[e]);
      SERIAL_ECHO(MSG_PID_DEBUG_OUTPUT);
      SERIAL_ECHO(pid_output);
      SERIAL_ECHO(MSG_PID_DEBUG_PTERM);
      SERIAL_ECHO(pTerm[e]);
      SERIAL_ECHO(MSG_PID_DEBUG_ITERM);
      SERIAL_ECHO(iTerm[e]);
      SERIAL_ECHO(MSG_PID_DEBUG_DTERM);
      SERIAL_ECHOLN(dTerm[e]);
    #endif //PID_DEBUG

  #else /* PID off */
    pid_output = 0;
    if (current_temperature[e] < target_temperature[e]) pid_output = PID_MAX;
  #endif
  return pid_output;
}

void manage_heater() {

  if (!temp_meas_ready) return;

  updateTemperaturesFromRawValues();

  #ifdef HEATER_0_USES_MAX6675
    float ct = current_temperature[0];
    if (ct > min(HEATER_0_MAXTEMP, 1023)) max_temp_error(0);
    if (ct < max(HEATER_0_MINTEMP, 0.01)) min_temp_error(0);
  #endif //HEATER_0_USES_MAX6675

  unsigned long ms = millis();

  // Loop through all extruders
  for (int e = 0; e < EXTRUDERS; e++) {

    #if defined (THERMAL_RUNAWAY_PROTECTION_PERIOD) && THERMAL_RUNAWAY_PROTECTION_PERIOD > 0
      thermal_runaway_protection(&thermal_runaway_state_machine[e], &thermal_runaway_timer[e], current_temperature[e], target_temperature[e], e, THERMAL_RUNAWAY_PROTECTION_PERIOD, THERMAL_RUNAWAY_PROTECTION_HYSTERESIS);
    #endif

    float pid_output = get_pid_output(e);    //****************************************************

    // Check if temperature is within the correct range
    soft_pwm[e] = current_temperature[e] > minttemp[e] && current_temperature[e] < maxttemp[e] ? (int)pid_output >> 1 : 0;

    #ifdef WATCH_TEMP_PERIOD
      if (watchmillis[e] && ms > watchmillis[e] + WATCH_TEMP_PERIOD) {
        if (degHotend(e) < watch_start_temp[e] + WATCH_TEMP_INCREASE) {
          setTargetHotend(0, e);
          LCD_MESSAGEPGM(MSG_HEATING_FAILED_LCD); // translatable
          SERIAL_ECHO_START;
          SERIAL_ECHOLNPGM(MSG_HEATING_FAILED);
        }
        else {
          watchmillis[e] = 0;
        }
      }
    #endif //WATCH_TEMP_PERIOD

    #ifdef TEMP_SENSOR_1_AS_REDUNDANT
      if (fabs(current_temperature[0] - redundant_temperature) > MAX_REDUNDANT_TEMP_SENSOR_DIFF) {
        disable_heater();
        if (IsStopped() == false) {
          SERIAL_ERROR_START;
          SERIAL_ERRORLNPGM(MSG_EXTRUDER_SWITCHED_OFF);
          LCD_ALERTMESSAGEPGM(MSG_ERR_REDUNDANT_TEMP); // translatable
        }
        #ifndef BOGUS_TEMPERATURE_FAILSAFE_OVERRIDE
          Stop();
        #endif
      }
    #endif //TEMP_SENSOR_1_AS_REDUNDANT

  } // Extruders Loop

  #if HAS_AUTO_FAN
    if (ms > extruder_autofan_last_check + 2500) { // only need to check fan state very infrequently
      checkExtruderAutoFans();
      extruder_autofan_last_check = ms;
    }
  #endif       

  #ifndef PIDTEMPBED
    if (ms < previous_millis_bed_heater + BED_CHECK_INTERVAL) return;
    previous_millis_bed_heater = ms;
  #endif //PIDTEMPBED

  #if TEMP_SENSOR_BED != 0

    #if defined(THERMAL_RUNAWAY_PROTECTION_BED_PERIOD) && THERMAL_RUNAWAY_PROTECTION_BED_PERIOD > 0
      thermal_runaway_protection(&thermal_runaway_bed_state_machine, &thermal_runaway_bed_timer, current_temperature_bed, target_temperature_bed, 9, THERMAL_RUNAWAY_PROTECTION_BED_PERIOD, THERMAL_RUNAWAY_PROTECTION_BED_HYSTERESIS);
    #endif

    #ifdef PIDTEMPBED
      #ifndef PID_OPENLOOP
        pid_error_bed = target_temperature_bed - current_temperature_bed;
        pTerm_bed = bedKp * pid_error_bed;
        temp_iState_bed += pid_error_bed;
        temp_iState_bed = constrain(temp_iState_bed, temp_iState_min_bed, temp_iState_max_bed);
        iTerm_bed = bedKi * temp_iState_bed;

        //K1 defined in Configuration.h in the PID settings
          #define K2 (1.0-K1)
          dTerm_bed = (bedKd * (current_temperature_bed - temp_dState_bed))*K2 + (K1 * dTerm_bed);
        temp_dState_bed = current_temperature_bed;

        pid_output = pTerm_bed + iTerm_bed - dTerm_bed;
        if (pid_output > MAX_BED_POWER) {
          if (pid_error_bed > 0) temp_iState_bed -= pid_error_bed; // conditional un-integration
          pid_output = MAX_BED_POWER;
        }
        else if (pid_output < 0) {
          if (pid_error_bed < 0) temp_iState_bed -= pid_error_bed; // conditional un-integration
          pid_output = 0;
        }

      #else
        pid_output = constrain(target_temperature_bed, 0, MAX_BED_POWER);
      #endif //PID_OPENLOOP

      soft_pwm_bed = current_temperature_bed > BED_MINTEMP && current_temperature_bed < BED_MAXTEMP ? (int)pid_output >> 1 : 0;

    #elif !defined(BED_LIMIT_SWITCHING)
      // Check if temperature is within the correct range
      if (current_temperature_bed > BED_MINTEMP && current_temperature_bed < BED_MAXTEMP) {
        soft_pwm_bed = current_temperature_bed < target_temperature_bed ? MAX_BED_POWER >> 1 : 0;
      }
      else {
        soft_pwm_bed = 0;
        WRITE_HEATER_BED(LOW);
      }
    #else //#ifdef BED_LIMIT_SWITCHING
      // Check if temperature is within the correct band
      if (current_temperature_bed > BED_MINTEMP && current_temperature_bed < BED_MAXTEMP) {
        if (current_temperature_bed >= target_temperature_bed + BED_HYSTERESIS)
          soft_pwm_bed = 0;
        else if (current_temperature_bed <= target_temperature_bed - BED_HYSTERESIS)
          soft_pwm_bed = MAX_BED_POWER >> 1;
      }
      else {
        soft_pwm_bed = 0;
        WRITE_HEATER_BED(LOW);
      }
    #endif
  #endif //TEMP_SENSOR_BED != 0

  // Control the extruder rate based on the width sensor
  #ifdef FILAMENT_SENSOR
    if (filament_sensor) {
      meas_shift_index = delay_index1 - meas_delay_cm;
          if (meas_shift_index < 0) meas_shift_index += MAX_MEASUREMENT_DELAY + 1;  //loop around buffer if needed

      // Get the delayed info and add 100 to reconstitute to a percent of
      // the nominal filament diameter then square it to get an area
      meas_shift_index = constrain(meas_shift_index, 0, MAX_MEASUREMENT_DELAY);
      float vm = pow((measurement_delay[meas_shift_index] + 100.0) / 100.0, 2);
      if (vm < 0.01) vm = 0.01;
      volumetric_multiplier[FILAMENT_SENSOR_EXTRUDER_NUM] = vm;
    }
  #endif //FILAMENT_SENSOR
}
```

Full edited temperature.cpp: http://1drv.ms/1BYPc9q

**Comment by Dimonira** [comment] 2015-03-09 15:41
Sory, how to separate code from text?

**Comment by thinkyhead** [comment] 2015-03-09 17:32
Are these useful changes, apart from working around that error? I don't want to change behavior if it can be avoided, unless there's a real benefit. The things is, other changes can also eliminate this compiler error, because it isn't entirely a result of the code. Such changes as changing the order of lines, making statics to replace autos, and even replacing spaces with tabs, are all known to eliminate the error message.

**Comment by Dimonira** [comment] 2015-03-09 21:29
@thinkyhead 
My changes don't change the behavior.
Marlin coding style is very bad: a huge number of preprocessor directives, a large number of global variables, too much complex code in one function and "for" loop, C++ isn't used, etc.
Therefore there is no reason to worry. All Marlin code is better to rewrite ;) Sory.

**Comment by thinkyhead** [comment] 2015-03-10 08:41
@Dimonira Marlin's architecture has some method behind it. It's not all ad-hoc madness. There are good reasons why it uses compiler directives to limit the code compilation, and for using globals also. At this point I don't see that Marlin for AVR stands to gain much from encapsulating its procedures in C++ classes, because it doesn't have any evident inheritance chain, and with very limited resources malloc/free and new/delete are pretty much verboten. You could take the existing code and wrap it up in classes, but it would pretty much look the same. Instead of globals you'd just have statics, etc.

The existing code is being cleaned up, redundancies are being reduced, and a separate codebase is being developed for ARM, which has more luxury to be fully OOP with the additional resources available on the faster boards.

**Comment by boelle** [comment] 2015-03-10 22:04
has this passed the mark where we can call it verified?

**Comment by thinkyhead** [comment] 2015-03-11 23:49
@boelle Well, it's still kind of spurious. The errors come and go as changes are made to the code. The workaround by @Dimonira happens to also be a code cleanup, so I might merge it. But I do expect to see this kind of error pop up again occasionally.

**Comment by boelle** [comment] 2015-03-12 07:09
if it does... well i'm tempted to close this one... then again....

**Comment by clefranc** [comment] 2015-03-13 11:51
I don't know about others, but every single PR I've tried to compile since we reported this "potential bug" failed with the same error (only the line number changes from time to time).

@thinkyhead @boelle The @Dimonira code is the only one compiling without error.

**Comment by thinkyhead** [comment] 2015-03-14 02:51
#1603 moves the code for pid outputs into separate functions to shorten `manage_heater`, and hopefully this stops the linker from choking. Move discussion to that PR.

**Closed as completed by thinkyhead** 2015-03-14 02:51 UTC
