### ISSUE TITLE
[FR] (MKS Robin E3 E3D set separately in the platfromio.ini file and support Neopiexl lights)

### ISSUE THREAD

**Issue by makerbase-mks** [MarlinFirmware/Marlin#17863] opened 2020-05-04 02:13 UTC
### Description
- MKS Robin E3 E3D are different motherboards
- They can be set individually in the platformio.ini file
- Support Neopiexl lights

### Feature Workflow

1. Add env: mks_robin_e3d in platformio.ini file
2. MKS Robin E3 and E3D board support Neopiexl lights, need remove Adafruit NeoPixel in lib_ignore and add "Adafruit NeoPixel=https://github.com/makerbase-mks/Adafruit_NeoPixel/archive/master.zip" to lib_deps path
![image](https://user-images.githubusercontent.com/12979070/80931957-ad27fa80-8def-11ea-9334-1e6e682b7b74.png)

#### Additional Information
MKS Robin E3 and E3D platfromio.ini set link: https://github.com/makerbase-mks/MKS-Robin-E3-E3D/blob/master/firmware/marlin2.0%20for%20Ender3/platformio.ini

**Comment by thisiskeithb** [comment] 2020-05-04 05:34
It looks like both use the same MCU and build scripts, so what benefit would splitting up build environments bring?

You could also rename the environment to `STM32F103RC_mks` similar to what was done for the BigTreeTech SKR Mini E3 boards that share the same MCU to make it more generalized.

https://github.com/MarlinFirmware/Marlin/blob/5e23fd6ef1bfda86fb79ede937b62e45085ea590/platformio.ini#L304-L325

Updating the NeoPixel exclude would be easy enough to do.

**Comment by sjasonsmith** [comment] 2020-09-11 19:22
@makerbase-mks is this still an issue? I assume this is work you could contribute yourself in a pull request?
I agree that they should continue sharing the same environment, but if there are changes needed it seems like you may be the best person to do so?

**Comment by sjasonsmith** [comment] 2020-11-12 11:12
These boards are present in the platformio file. I'm going to call this a duplicate of another NeoPixel feature request for STM32F1 boards.

**Comment by sjasonsmith** [comment] 2020-11-12 11:12
Duplicate of #19800

**Closed as completed by sjasonsmith** 2020-11-12 11:12 UTC
Labels: T: Feature Request
