### ISSUE TITLE
[BUG] Printer Scraping on Print (forced layer shift)

### ISSUE THREAD

**Issue by Komak57** [MarlinFirmware/Marlin#15503] opened 2019-10-10 09:35 UTC
### Description

Printer scrapes across print. With solid prints, this is unnoticable. On large scale prints with holes, this causes the extruder to get lodged in the hole for a brief period of time before resuming, creating a layer shift far exceeding printability (full print failure).

### Steps to Reproduce

1. Create medium sized model of a case with small holes in the middle of the bottom plate
2. Slice with known working settings on Cura
3. ...
4. Profit?

**Expected behavior:**

Honestly, I expected to have this SKR 1.3 model done, but have failed 2 prints in a row.
#### Additional Information
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/3711489/Configuration.zip)

#### Things I've Tried ####

- Setup was an Anet A8 printer. Replaced board with an SKR 1.3 and 5x TMC2130 drivers.
- Powered by a modified 325W Desktop PSU (12v Rail) - Tried 2x lines, made no difference. The gauges can push significant power without problem.
- The Anet display doesn't work. Research suggests it won't work with the 5 button control. Don't require it. Unplugged
- Printer DOES have dual Z axis which has been calibrated excessively. Motors and Rods have been calibrated for minimum friction (loosen, raise, tighten, spin for wobble, align with rod, do another spin wobble test, slide rod down and ensure it slides in without force).
- TMC2130 drivers were originally set at 1.3v, too hot. Reduced to 1.0v for all but E0 (extruder). Adjusted in config
- Modules got hot. Applied a 120mm fan to 12v output rails on SKR 1.3 until case can be printed for better thermal control
- Bed Center Offset found to be 33mm Left, and 5mm Down. Set in X_MIN_POS and Y_MIN_POS (did nothing) Currently setting offset in Cura [BUG]?

I've done a 20mm Cube test and the print showed very close to ideal. Cube is barely larger than 20mm and 100mm extrusion test came out perfect.

New Calibration:
> #define DEFAULT_AXIS_STEPS_PER_UNIT   { 97.42, 97.51, 398.9, 100 }

Also printed a Sitting Pikachu model which came out almost flawless.

![20191010_053258](https://user-images.githubusercontent.com/3423637/66557211-80dd2180-eb1f-11e9-8a3a-1c9cc5b7a1bb.jpg)

First print appeared to have some weird slicing issues. Adjusted the faces, converted to tris, converted to quads with strict limitations, back to tris, shade flat, reprint. Fixed the weird extrusion angles from first print. 

![20191010_051040](https://user-images.githubusercontent.com/3423637/66555348-81c08400-eb1c-11e9-815e-3a01a3475424.jpg)

I do NOT believe this is particularly a bug with Marlin, but something with my current setup.

**Comment by reloxx13** [comment] 2019-10-10 11:22
if u dont set a zhop in ur slicer, it will touch since it stays on the same layer while moving...

hard to tell but looks like nozzle too close, those "rills" left and right of the nozzle will appear cause of squishing and those are higher then ur current layer.

**Comment by Komak57** [comment] 2019-10-10 11:30
Z Hop When Retracted, Z Hop Only Over Printed Parts, Z Hop Height, and Z Hop After Extruder Switch all enabled. Z hop When Retracted currently not set in print settings.

It's weird that I'm only now having these problems, when Merlin on the Anet board ran fine? Perhaps there was a pre-configured configuration. Will try with 1mm and report back after some sleep.

**Comment by boelle** [comment] 2019-10-12 12:43
@Komak57 still having issues? is this a slicer problem and not a firmware problem?

**Comment by Komak57** [comment] 2019-10-12 13:14
The zhop slicer setting does prevent it from hanging on itself causing failed prints. I haven't been able to do many tests, since after reconnecting all the wires under a lack of sleep, I failed to double check the polarity of the input, and blew a fuse. Rather than risk damaging the board by shorting it, I'm trying to find time to go grab a new fuse to continue my prints. I'm curious as to why this would be scraping across the prints, as it's a new problem for me with the new board. I had assumed my calibration was off, but that doesn't seem to be the case. I wonder if it's the lack of printer nozzle size settings (default 0)?

In any case, the print looks good, and 1mm was more than enough zhop to avoid future calamities.

**Comment by boelle** [comment] 2019-10-12 13:16
check that its not loose screws etc that is the problem, or printed parts that has bend or broken

**Comment by Komak57** [comment] 2019-10-12 13:26
Print was firmly planted on the taped bed. I've learned to identify a level bed more from how the first layer goes down better than paper tests.

All bolts and screws are firm enough to sustain the structure, but not so firm as to damage the cheap plastic given vibrations. Might look into aluminum casing as time goes on.

Could it have anything to do with the TMC2130 in SPI mode with stealth chop? Not sure the specifics on how this works, so I'm not familiar with the pitfalls of what could go wrong with such a setup. I replaced the board because the stock board was far too loud to ever print in evening hours. New board is silent enough I've been able to move it into my bedroom and sleep while it prints! No cabinet or shell!

**Comment by boelle** [comment] 2019-10-12 13:30
not sure as i use tmc2100 and drv8825, but one thing that is important with all TMC's is they need active cooling, a 80mm pc fan can do the trick

if not you risk they get so hot they start to shut down and then strange thing can happen

**Comment by Komak57** [comment] 2019-10-12 13:45
I noticed that on my first Pikachu print, along with the motors. The new case is designed for a 30mm fan I salvaged from an old spare parts Dreamcast. Takes a 5v source. Would be nice if I could output a 5v auto fan instead of 12v. Only have 5v relays around, so for the time, it's just 100% on with the printer.

For now, I'll consider the problem (nozzle scraping on print) solved, but not fixed (as avoiding the problem doesn't really fix it). I'll have to do some more research into stealth chop.

Have other oddities that happen with the printer that won't really be suited for this bug topic if you don't mind private messages? Non harmful to the prints, but seen as abnormal.

**Comment by boelle** [comment] 2019-10-22 07:01
given no activevity and that the problem is solved i will close this one


> For now, I'll consider the problem (nozzle scraping on print) solved

**Closed as completed by boelle** 2019-10-22 07:01 UTC

**Comment by Komak57** [comment] 2019-10-23 07:24
Oof, Just found additional information that might help in debugging the root cause. I started looking into the Stealth Chop mode of my TMC2130 drivers, and decided to play around to see if these were the cause. I left X and Y on stealth (because those get noisy) and enabled SpreadCycle for Z1 Z2 and E. These are the 3 motors that are already silent through a print, and don't need additional processing for a print.

`M569 S1 E`
`M569 S1 I0 Z`
`M569 S1 I1 Z`
`M569 ;Report Modes`

Result? An ear-destroying high pitched ringing that sounds like a bad timing belt on an engine. The print, although at a far lower degree, still rubs against various parts of the model, and will inevitably be the end of my hot-end tip if I don't solve it.

**Comment by Komak57** [comment] 2019-10-26 02:20
Confirmed Problem. 700 @ 1v was too low for my Z drivers, and 800 @ 1.14v was too high for my X/Y Drivers. Split accordingly, printer no longer scraping against the print. Not sure why 700 was too low when in dual-z stepper mode. I've seen people config as low as 0.9v

**Comment by boelle** [comment] 2019-10-26 08:13
stepper motors are not the same, and the vref depend on the stepper, how tight belts are etc etc
and everything have tolerance's so you cant compare directly

you cant compare temps either as tolerance on hardware can be 3% or more
