### ISSUE TITLE
#define E_DUAL_STEPPER_DRIVERS, E1 do not obey microstepping

### ISSUE THREAD

**Issue by thephantom1492** [MarlinFirmware/Marlin#27127] opened 2024-05-25 04:20 UTC
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Using a dual E stepper setup via:
#define E_DUAL_STEPPER_DRIVERS
The second stepper uses a fixed 8 microsteps setup, ignoring what was set for E0 or better: E1.

My setup used a 64 microsteps for all steppers.
Due to this bug I needed to revert E0 to 8 microsteps

Also, by design or not, you can not set different current for E0 and E1, which can be quite usefull in some setup.

### Bug Timeline

Atleast since git of 2023-12-05

### Actual behavior

Expected to follow the same microstepping. 

### Steps to Reproduce

1. #define E_DUAL_STEPPER_DRIVERS
2. extrude
3. clean up the filament mess on the gears that grinded on the filament due to over advancement of the pusher motor.

### Version of Marlin Firmware

Git of 2024-05-24

### Printer model

Heavy modified Ender 5 Plus

### Electronics

BTT SKR3

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Prusa Slicer

### Host Software

OctoPrint

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[config.zip](https://github.com/MarlinFirmware/Marlin/files/15441654/config.zip)

**Comment by thisiskeithb** [comment] 2024-05-25 05:07
Duplicate of https://github.com/MarlinFirmware/Marlin/issues/25787

**Closed as completed by thisiskeithb** 2024-05-25 05:07 UTC
