### ISSUE TITLE
[Request] Prusa Mk3 laser sensor available on aliexpress now .. need implementation (new)

### ISSUE THREAD

**Issue by studiodyne** [MarlinFirmware/Marlin#11719] opened 2018-09-04 11:49 UTC
Hi , thanks for all are interested 
_**This sensor has a lot of problems when asked to measure distances according to filament types, but I suggest you do not use it to measure or count the filament, but just to detect when it stops. This is more than enough to prevent the firmware that there is an extrusion problem.
If we know 'with a reasonable threshold of tolerance' when the filament is stopped, we can save the print. That's why, I propose that the competent people here, work on the implementation of this sensor, and with time and experience will improve the system.**_

The laser sensor of the prusa MK3 is sold on aliexpress 
[here](https://fr.aliexpress.com/item/Prusa-i3-MK3-3D-Imprimante-Filament-Capteur-D-tecter-Coinc-Filament-Et-Offrir-L-utilisateur-une/32907430687.html?spm=a2g0w.search0303.3.1.3d0e7a65BKY717&ws_ab_test=searchweb0_0%2Csearchweb201602_0_10084_100031_10083_451_10304_10821_10843_452_10307_10618_10065_10068_10059_10103_10696_10820_10302%2Csearchweb201603_0%2CppcSwitch_0&algo_pvid=de99257e-d850-425e-9849-be82a0a4b45b&algo_expid=de99257e-d850-425e-9849-be82a0a4b45b-0)

Someone to implement PRUSA code in 2.0 ?
This sensor have so many advantages 
- No contact , no braking , no friction 
- Light weight and size , to be installed close to the gear in the carriage
- Can inform about  all bad movements , clogged , jammed , runout , cold nozzle , sanding of filament , and the print can be saved without it being too late

Thks for all that want to work on it
_The code is already written adapted and debugged for marlin on the PRUSA MK3 Firmware_
![1set-prusa-i3-laser-sensor-3d-printer-filament-sensor-detect-stuck-filament-offer-user-an-option jpg_640x640](https://user-images.githubusercontent.com/42887851/44946350-1c6b7100-adfb-11e8-9e08-fc6cbe9e9f9c.jpg)

**Comment by comps** [comment] 2018-09-04 19:14
Duplicate of #11693 with removed discussion.

Please don't do this - it's rude and makes you seem very "needy" for attention.

**Closed as completed** 2018-09-08 16:50 UTC
