### ISSUE TITLE
z axis homing speed much too high while probing for auto bedlevel

### ISSUE THREAD

**Issue by derletztename** [MarlinFirmware/Marlin#1045] opened 2014-08-24 10:06 UTC
There is no differentiation between the x/y axis homing speed and the z axis speed. This causes problems with many printers as their z-axis couldn't move that fast. Original code as Comment:

963.	static void do_blocking_move_to(float x, float y, float z) {
964.	    float oldFeedRate = feedrate;
965.	
966.	    feedrate = XY_TRAVEL_SPEED;
967.	
968.	    current_position[X_AXIS] = x;
969.	    current_position[Y_AXIS] = y;
970.	    current_position[Z_AXIS] = z;
971.	    plan_buffer_line(current_position[X_AXIS], current_position[Y_AXIS], current_position[Z_AXIS], current_position[E_AXIS], feedrate/60, active_extruder);
972.	    st_synchronize();
973.	
974.	    feedrate = oldFeedRate;
975.	}

Better like this maybe:

937.	static void do_blocking_move_to(float x, float y, float z) {
938.	float oldFeedRate = feedrate;
939.	
940.	feedrate = homing_feedrate[Z_AXIS];
941.	
942.	current_position[Z_AXIS] = z;
943.	plan_buffer_line(current_position[X_AXIS], current_position[Y_AXIS], current_position[Z_AXIS], current_position[E_AXIS], feedrate/60, active_extruder);
944.	st_synchronize();
945.	
946.	feedrate = XY_TRAVEL_SPEED;
947.	
948.	current_position[X_AXIS] = x;
949.	current_position[Y_AXIS] = y;
950.	plan_buffer_line(current_position[X_AXIS], current_position[Y_AXIS], current_position[Z_AXIS], current_position[E_AXIS], feedrate/60, active_extruder);
951.	st_synchronize();
952.	
953.	feedrate = oldFeedRate;
954.	}

**Comment by boelle** [comment] 2015-03-11 08:55
is this still an issue with a fresh copy of marlin and IDE updated to latest non-beta?

**Comment by boelle** [comment] 2015-03-17 17:18
will close this one as there was no active response... please comment if the issue is still there

**Closed by boelle** 2015-03-17 17:18 UTC
Labels: Potential bug
