### ISSUE TITLE
[BUG] Closed bug not solved. Y and Z not working after 3-Point leveling

### ISSUE THREAD

**Issue by roel8032** [MarlinFirmware/Marlin#22393] opened 2021-07-18 22:06 UTC
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

Bug also mentioned in #22338 and #22128. Still exists.

### Expected behavior

Y and Z to move by manual control and in print mode.

### Actual behavior

Y and Z dont move.

### Version of Marlin Firmware

2.0..9.1 and bugfix version july 19

### Printer model

Infitary M508

### Your Slicer

Cura

**Comment by ellensp** [comment] 2021-07-19 00:55
Is a duplicate of https://github.com/MarlinFirmware/Marlin/issues/22128 which is still open

**Closed as completed by ellensp** 2021-07-19 00:55 UTC
