### ISSUE TITLE
[BUG] When using Robin NanoV1.2/V2, there will be occasional lost steps when Y/Z occurs

### ISSUE THREAD

**Issue by ghost** [MarlinFirmware/Marlin#23506] opened 2022-01-12 09:00 UTC
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

When using RobinNanoV1.2/V2, if you use LVGL UI, you will suddenly lose steps during the printing process, but there is no such phenomenon when using Color UI. When losing steps, the amplitude of lost steps is relatively large, and more of them appear on the Y-axis. Of course, under my repeated tests, the Z-axis also exists, but it is very small. I've tried changing to a different machine, but the problem persists, so I can rule out a machine problem. I've used NanoV3 + LVGL UI and this has never happened, so I don't think it has much to do with LVGL. After I switched back to the Maple environment, the effect was significantly improved, and there was almost no lost step. I printed it nearly 60 times, and once there was a lost step, but the magnitude was very small. So I think this is related to the reason of abandoning maple and using STM32 HAL? In my opinion, the STM32 HAL library is very convenient, but it is only limited to cases where there is no high requirement for execution efficiency. I think the execution efficiency of the STM32 HAL library is very low. Why not use the LL library?

### Bug Timeline

It should have been there a long time ago, discovered more than a month ago

### Version of Marlin Firmware

2.0.9.3

### Printer model

Creality Ender 3 or ...

### Bed Leveling

ABL Linear grid

### Your Slicer

Cura

### Host Software

SD Card (headless)

**Comment by thisiskeithb** [comment] 2022-01-12 09:39
Duplicate of https://github.com/MarlinFirmware/Marlin/issues/22967

**Closed as completed by thisiskeithb** 2022-01-12 09:39 UTC
