### ISSUE TITLE
[BUG] Additional retract when linear advance is on.

### ISSUE THREAD

**Issue by aghfars** [MarlinFirmware/Marlin#19982] opened 2020-11-01 13:01 UTC
i have problem on 0.2 mm nozzle and 0.1 mm layer height.
[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/5470852/Marlin.zip)
Marlin 2.0.7.1
![image](https://user-images.githubusercontent.com/24976773/97803320-ad9a3480-1c5e-11eb-8165-efa35e2a436c.png)
And I tried to fix this problem, which worked properly by deleting the original retract, but then it crashed due to other retractions.
the slicer is cura 4.7.1

**Comment by boelle** [comment] 2020-11-01 22:20
is this not a problem with cura that makes the Gcode?

**Comment by aghfars** [comment] 2020-11-02 06:42
> is this not a problem with cura that makes the Gcode?

cura make the Gcode and the Gcode seems to be correct
so why when i remove the first retract it works fine?
and i test the relative and absolute extruder and nothing change.

**Comment by boelle** [comment] 2020-11-02 16:05
i use relative extrusion.... 

so you remove an retract after G1 F1500 E0 ?? or are you removing G1 F1500 E0?

please attach not working code and the working one

but if all you change is the gcode then its cura that outputs wrong gcode and the problem is not related to marlin

**Comment by aghfars** [comment] 2020-11-02 16:10
[Working code.zip](https://github.com/MarlinFirmware/Marlin/files/5476295/Working.code.zip)
[Not Working Gcode.zip](https://github.com/MarlinFirmware/Marlin/files/5476358/Not.Working.Gcode.zip)
i change the Not working gcode

**Comment by boelle** [comment] 2020-11-02 16:15
Not working code.zip does not extract, please attach again and make sure its not empty zip

**Comment by aghfars** [comment] 2020-11-02 16:30
Unretract is acting as retract after every retact unless the retract is been deleted
[Not Working Gcode.zip](https://github.com/MarlinFirmware/Marlin/files/5476431/Not.Working.Gcode.zip)

**Comment by boelle** [comment] 2020-11-02 16:40
![image](https://user-images.githubusercontent.com/3832239/97894513-dee43480-1d32-11eb-9d24-90d7169bdcd0.png)


the start looks very strange

you have 3 lines (25,26 and 27) with G92 E0 only one is needed

and you remove G1 F1500 E-2

that one should be there so it prevents ozze when you move from priming to the skirt

**Comment by boelle** [comment] 2020-11-02 16:48
so how i would read this stump of code:


- reset extrusion count
- prime extruder with 5.4mm extrusion
- reset extrusion count
- reset extrusion count
- reset extrusion count
- retract 2mm
- switch off all fans
- set acc. to 500
- move to X145.705 Y140.863 Z0.15
- set acc to 200
- unretract 2mm (becaused it is retracted 2mm)

**Comment by boelle** [comment] 2020-11-02 16:52
this is my start gcode, i only reset extrusion count 2 times, once before prime and one after prime just before print starts. i do not do a retract as i do not have a problem with ooze

- M420 S1; Load bed level mesh
- G28 Z F750; Home Z
- G28 Y F750; Home Y
- G28 X F750; Home X
- G92 E0 ; zero the extruded length
- G1 X50 Y0 F750 ; go to the corner of the front
- G1 Z0.1 ; get close to the bed
- M190 S[first_layer_bed_temperature] ; wait for bed temp
- M109 S[first_layer_temperature] ; wait for extruder temp
- G1 X100 E10 F200 ; make a thick line to prime extruder
- G92 E0 ; zero the extruded length
- G1 Z0.3 ; lift Z
- G4 S2   ;wait 2 sec to bleed off excess pressure

**Comment by aghfars** [comment] 2020-11-02 16:55
> so how i would read this stump of code:
> 
> * reset extrusion count
> * prime extruder with 5.4mm extrusion
> * reset extrusion count
> * reset extrusion count
> * reset extrusion count
> * retract 2mm
> * switch off all fans
> * set acc. to 500
> * move to X145.705 Y140.863 Z0.15
> * set acc to 200
> * unretract 2mm (becaused it is retracted 2mm)

yes but Actually the unretract after retract acting as retract again
and retract at the start of gcode is not the only one in the gcode

**Comment by boelle** [comment] 2020-11-02 17:00
i looked at your configs

/*
======================================================================================================================================================
edited files:
platformio.ini
Marlin\Configuration.h done
Marlin\Configuration_adv.h done
Marlin\_Bootscreen.h done
Marlin\_Statusscreen.h done
Marlin\pins\ramps\pins_RAMPS.h done
Marlin\src\lcd\dogm\dogm_Bootscreen.h done
Marlin\src\inc\Conditionals_LCD.h done
Marlin\src\inc\Version.h done
Marlin\src\core\language.h done
======================================================================================================================================================
*/

is that added by you? should normally not be there

**Comment by boelle** [comment] 2020-11-02 17:05
i'm not expert so someone else will have to chime in @ellensp @rhapsodyv 

but i would suggest you use bugfix 2.0.x and only change configuration.h, configuration_adv.h and platformio.ini

just to rule things out

**Comment by aghfars** [comment] 2020-11-02 17:06
> i looked at your configs
> 
> # /*
> # edited files:
> platformio.ini
> Marlin\Configuration.h done
> Marlin\Configuration_adv.h done
> Marlin_Bootscreen.h done
> Marlin_Statusscreen.h done
> Marlin\pins\ramps\pins_RAMPS.h done
> Marlin\src\lcd\dogm\dogm_Bootscreen.h done
> Marlin\src\inc\Conditionals_LCD.h done
> Marlin\src\inc\Version.h done
> Marlin\src\core\language.h done
> */
> 
> is that added by you? should normally not be there

yes i add this because of my handmade OLED and another text or something like that and Every time a new version comes, I do not forget which parts I have to change

**Comment by boelle** [comment] 2020-11-02 17:09
have you tried bugfix?

**Comment by aghfars** [comment] 2020-11-02 17:10
> i'm not expert so someone else will have to chime in @ellensp @rhapsodyv
> 
> but i would suggest you use bugfix 2.0.x and only change configuration.h, configuration_adv.h and platformio.ini
> 
> just to rule things out

I can test in three days because I have an exam

**Comment by ellensp** [comment] 2020-11-06 01:23
You need to attach all files you edited.. I would suspect a pin conflict, something else is conflicting the extruder direction pin.

**Comment by aghfars** [comment] 2020-11-06 05:00
[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/5499177/Marlin.zip)
I put all the files
I found the problem
This problem occurs when I enable the LIN_ADV feature even on bugfix even i set it to zero.

**Comment by boelle** [comment] 2020-11-06 07:30
if you truely mean the issue is fixed then click the green close button below

**Comment by aghfars** [comment] 2020-11-06 07:51
> if you truely mean the issue is fixed then click the green close button below

i want to use LIN_ADV What should I do?

**Comment by sjasonsmith** [comment] 2020-11-07 08:30
It sounds like you might seeing one retract from your G-code, and also the "Linear reverse" after an E movement with Linear Advance enabled.

Linear Advance works by advancing extra filament when starting E movement. It pulls back that extra filament when the extruder slows down. I suspect you are seeing this, followed by the -2 retract in your GCode.

**Comment by boelle** [comment] 2020-11-08 22:01
> i want to use LIN_ADV What should I do?

enable it, and as @sjasonsmith said you will see extra retract, that is not a bug but LIN_ADV working its magic

**Comment by sjasonsmith** [comment] 2020-11-08 22:10
Based on previous comments, I don't think there is actually an issue here and will go ahead and close this.

**Closed as completed by sjasonsmith** 2020-11-08 22:10 UTC
Labels: Bug? False Alarm
