### ISSUE TITLE
Vase mode weird behavior

### ISSUE THREAD

**Issue by kaijrock23** [MarlinFirmware/Marlin#13725] opened 2019-04-16 16:44 UTC
Hi, when I print in vase mode this happen
https://youtu.be/8rhoIhAdOjY
It happen only in vase mode tried cura and simplify same behavior with both.
Marlin 2.0 with preconfigured ender 3 files.
I always printed fine until today, vase mode too.

**Comment by shitcreek** [comment] 2019-04-17 06:14
Have you checked your connections?

**Comment by kaijrock23** [comment] 2019-04-17 10:08
Yes i did, I tried 3 different sd cards and other gcodes in vase mode, same results, I tried with USB connection and it printed without problem, just stopped for 1 sec for two time randomly but I read it is a simplify behavior glitch.

**Comment by kaijrock23** [comment] 2019-04-17 10:08
So I think that the sd slot is the problem.

**Comment by robbycandra** [comment] 2019-04-17 15:48
Ha.... @kaijrock23 , i know you print woman body from thingiverse. I print it with marlin 2.0 and no problem.
I guess it is your SD card problem, check sdcard Reader speed setting and speed class of your SDCard.

**Comment by kaijrock23** [comment] 2019-04-17 15:57
I will contact creality and have a new motherboard, clearly it's the card reader that suddenly stopped working, any suggestion for a good SD card for the ender 3?

**Comment by robbycandra** [comment] 2019-04-18 09:34
Try to change the SD Card first.

**Comment by kaijrock23** [comment] 2019-04-18 11:21
Done, same results.

**Comment by Tymek** [comment] 2019-05-19 21:48
I have the same problem with SKR v1.1, (bugfix-2 branch). Weird stuff.. Only _spiralize mode_ prints this way - other `.gcode`s work fine. (from Cura & Slic3r) If switching card solves this I will let you know.

**Comment by Tymek** [comment] 2019-05-20 22:13
It worked. I reconnected everything today and sliced with stock settings where only printing mode was changed. "cannot reproduce :| "

**Comment by boelle** [comment] 2019-07-21 14:14
will close this one as it seems to have been a hardware issue

**Closed as completed by boelle** 2019-07-21 14:14 UTC
