### ISSUE TITLE
Virgin Marlin install crashes when the Z axis is moved via LCD rotary encoder

### ISSUE THREAD

**Issue by Nerveasy** [MarlinFirmware/Marlin#1166] opened 2014-12-03 09:31 UTC
When I install marlin on a atmega2560 derived board with an ultipanel clone and go to the ->prepare->move axis->1mm->Z axis and turn the rotary encoder fast up towards the max Z value (I have homed earlier) the lcd either goes blank and restarts or it freezes and the Z axis goes down forever until it hits it's physical limits. I tried different step per units for the Z axis, different values for the encoder steps, and increasing or decreasing the bufsize but it still crashes when you continuously turn the rotary encoder in that menu... The workaround is to turn the encoder in small increments so the Z axis can keep up with the change so you can still reach the max position of the Z axis.

**Comment by boelle** [comment] 2015-03-11 08:59
is this still an issue with a fresh copy of marlin and IDE updated to latest non-beta?

will close this one soon as there have not been any activity since my last Q

**Comment by Nerveasy** [comment] 2015-03-19 09:09
Hi, This is still an issue with a clean install 1.0.2 version of Marlin... I use this board: http://manuals.velleman.eu/article/12-mounting-the-mainboard-12.html

It still has the same bug...

**Comment by boelle** [comment] 2015-03-19 09:16
use current code... lot has happened since 1.0.2

Den torsdag den 19. marts 2015 skrev Nerveasy notifications@github.com:

**Comment by Nerveasy** [comment] 2015-03-19 09:19
Do I use the Development branch?

**Comment by tonnico** [comment] 2015-03-19 09:39
When I recognize this correctly:

using a Host:
Marlin says send me stuff
Host sends move
Marlin says buffer is full
Host waits until buffer is free

using the Display:
sends move until buffer is full
but there is nothing to check or decline

**Comment by Nerveasy** [comment] 2015-03-19 09:44
I think it's something like that but increasing buffersizes doesn't really change a whole lot.
Probably just delaying the inevitable.

**Comment by boelle** [comment] 2015-03-19 10:49
yes, we only have one branch... development

1.0.2 is a release

Den torsdag den 19. marts 2015 skrev Nerveasy notifications@github.com:

**Comment by Nerveasy** [comment] 2015-03-19 12:14
Hmm, With the Development version only the Y axis responds to encoder movements, X and Z just show static value and nothing changes when turning the encoder. (The fan that is configured to start as soon there is a motor movement does start however but no real movement on the motors except on Y axis.

**Comment by boelle** [comment] 2015-03-19 13:51
think i will upgrade this to potential problem and then if others can confirm then to verified issue...

then its up to the coders to figure where the culprit is

**Comment by boelle** [comment] 2015-03-19 13:52
you did use this one right: https://github.com/MarlinFirmware/Marlin/archive/Development.zip

that link always give you the current code

**Comment by Nerveasy** [comment] 2015-03-19 13:56
Yes that is the one I used this afternoon. I'll also try to figure out what's wrong exactly.

**Comment by tonnico** [comment] 2015-03-19 14:51
This issue should be still exist. I have an idea to solve it.
Maybe I have time this afternoon for it.

**Comment by Nerveasy** [comment] 2015-03-19 15:06
Thank you :)

**Comment by boelle** [comment] 2015-03-19 15:11
@Wurstnase if you get it fixed please upload an PR and mention this issue number so we can merge and close it :-D

**Comment by tonnico** [comment] 2015-03-19 16:21
Sure :)

**Comment by tonnico** [comment] 2015-03-19 16:51
Well, I think you don't want to hear that, but I can't reproduce that. I set my Encoder to 1mm for Z and turn it like crazy from 0 to 100mm and the axis just move down.

**Comment by AnHardt** [comment] 2015-03-19 17:08
@Wurstnase 
#1521 changed the behavior of the encoders. 'turn it like crazy' may avoid the problem because less but bigger steps are produced.

**Comment by AnHardt** [comment] 2015-03-19 17:11
Thinking about it - one could try to remove the complete 10mm, 1mm, 0.1 mm menu.

**Comment by Nerveasy** [comment] 2015-03-20 07:36
Today I'll try to flash a stock ultimaker one with the latest firmware as I did have the same problem with that board/printer.

**Comment by thinkyhead** [comment] 2015-03-20 10:48
Some more recent changes have been made to the menu code in `ultralcd.cpp`, so it could use a fresh look. It's always possible there are still some kinks to work out.

**Comment by boelle** [comment] 2015-04-01 18:53
Should we close this one as fixed or upgrade it to verified issue?

**Comment by thinkyhead** [comment] 2015-04-02 00:42
@boelle I think it's verified enough. We may want to make the movement menu items smarter. For example, if the Z is moving away from the current value in the menu, kill the current plan and start a new one.

**Comment by dantman** [comment] 2015-06-05 19:22
@thinkyhead That sounds like a good idea. Though how hard is it to implement? This is pretty much the only milestone bug I can find that isn't related to something like auto bed leveling I can't test.

From what I can tell, after figuring out the destination the LCD code just hands off the work to `plan_buffer_line (planner.cpp)` which handles the moves. And I can't seem to see any command in the planner that would tell it to abort its current moves and reset the buffer (so we could tell it to move in the other direction instead).

**Comment by thinkyhead** [comment] 2015-06-11 23:00
@dantman I'll take a look at the planner code and see if there's some way that it can be made interruptible without losing track of the `current_position` (which is ahead of the planner). The lcd movement functions need to be able to work in conjunction with g-code movement commands without any loss of accuracy. It's less important when the current position is unknown, as before homing, but nevertheless vital.

**Comment by boelle** [comment] 2015-06-29 10:34
I will close this one, we have not heard from the OP in 3 months and no one else have been able to reproduce the issue since

**Comment by ghuser2** [comment] 2015-09-28 12:52
I still get this bug on 1.0.2

Just requires a few knob turns when raising Z or when extruding E

**Comment by spaelectronics** [comment] 2015-09-28 13:16
Actually, I have had this issue a couple times myself on the latest RC Release.

When I move E very fast (fast turning of the knob), it will sometimes freeze up, overheating the hotend.

With Z, I've had similar issues, but slightly different. If I turn the knob fast, the numbers on the LCD will go up, then suddenly jump back down.

"Turning Knob Fast to increase Z... Z jumps from say 90mm to 30mm...

To avoid this issue, I find myself increasing it 10mm at a time, waiting, then another 10mm, etc.

However, I've never had Z freeze the unit, only E.

And also, this seems to be an intermittent problem, it does not always occur.

**Comment by ghuser2** [comment] 2015-09-29 10:40
Yes mine overheated too once; it said 245/0 but was burning, and after restart it said 550/0

**Comment by spaelectronics** [comment] 2015-09-29 13:12
I caught mine before it got to that point. I would of thought watchdog would of prevented that, but I guess it wasn't really stuck in a loop.. More like ignored the hotend temperature.

**Comment by Deniskain3D** [comment] 2015-12-21 05:47
Hi! I found what the problem was.
configuration_adv.h: 
#define MAX_CMD_SIZE 64
#define BUFSIZE 32
With these parameters in the terminal indicated echo: Free Memory: 1547  PlannerBufferBytes: 1488
It's enough to turn the encoder at any speed. This is right for my mega2560. Enjoy )

**Comment by ghuser2** [comment] 2016-01-03 19:36
My 1.0.2 currently says:

#define MAX_CMD_SIZE 96
#define BUFSIZE 4

Are you saying this is not correct, and that yours fixes the problem?

**Comment by thinkyhead** [comment] 2016-02-19 02:51
Is this bug still showing up in RCBugFix right now? If so, we'll have to take a closer look. We have some pending patches to prevent immediate commands from being injected at odd times. Those might fix this issue, or at least prevent Marlin from crashing.

**Comment by Blue-Marlin** [comment] 2016-02-20 18:57
This could be a memory overflow.
All moves in the menus end in `_lcd_move()` calling `line_to_current(axis);`.
`line_to_current(axis);` calls `plan_buffer_line()`.
As long the planner buffer is full `plan_buffer_line()` calls `idle()`.
`idle()` calls `lcd_update()`.
`lcd_update()` calls `(*currentMenu)();` - in this case one of the move menus.
The move menu in effect calls `_lcd_move()`.
And so on.

A way out of this could be to check if `block_buffer_tail == next_buffer_head`  (buffer full) and drop the move in that case. `_lcd_move()` could be the right place to do this, because we there can prevent `current_position` from changing.

```
static void _lcd_move(const char* name, AxisEnum axis, int min, int max) {
+  if (block_buffer_tail == next_buffer_head) return;
  if (encoderPosition != 0) {
    refresh_cmd_timeout();
    current_position[axis] += float((int)encoderPosition) * move_menu_scale;
```

**Comment by Blue-Marlin** [comment] 2016-02-20 19:41
I doubt altering `MAX_CMD_SIZE` and/or `BUFSIZE` can help with this - they are not involved in the moves from the menu. Increasing `BLOCK_BUFFER_SIZE` helps because the relevant buffer is filled up later.

**Comment by thinkyhead** [comment] 2016-02-21 07:02
@Blue-Marlin I think that's probably the key — the stack is growing too large while the planner keeps waiting for the previous long moves. But we do want `idle()` to occur and for new moves to be added, if possible. This brings me back to the idea of having new moves simply abort existing ones. But we don't have a flag or a function in place to abort planner moves in progress, currently. It might be a bit of a challenge.

Your idea of checking if `block_buffer_tail == next_buffer_head` (buffer full) and dropping the move — or just delaying the call to `plan_buffer_line` until there's a free slot — is probably the easiest fix. Another option is to add a `bool` argument to `lcd_update` telling it not to call `plan_buffer_line` (because it's being called from `plan_buffer_line`).

**Comment by Blue-Marlin** [comment] 2016-02-21 12:03
@thinkyhead 
We are already idling when in the menu. All we have to do is avoiding an other recursion. 

`plan_discard_current_block()` ends the current block.

```
while (blocks_queued()) plan_discard_current_block();
```

empties the complete planner buffer (see quickStop()).

But that's an immediate stop - likely with loosing steps.
What you are looking for is more a delete from the other side.of the buffer.

~~Or, how about not piling up moves with st_synchronize() ??
But that would result in single accelerated/deaccelerated moves instead of smoothly concatenated ones.~~
Crap - also calls idle().

Just waiting to accept the next move seems to be advisable here.

**EDITED**

**Comment by Blue-Marlin** [comment] 2016-02-21 12:29
To decrease the delay between changing the direction with the knob and changing the direction of the tool we could ask for a number of moves in the buffer instead of buffer_full.

```
if (movesplanned() > 3) return;
```

That should be smooth and much more responsive.

**Comment by AnatoliyKube** [comment] 2016-02-27 14:43
if (movesplanned() > 3) return; not solve the problem
The fault lies in the algorithm input from the encoder values
It works on all axis X Y 
problem on the axis Z
here it is necessary to look
I do not know Ci  , I know assemblerAVR

**Comment by AnatoliyKube** [comment] 2016-02-27 15:45
if you put 
if (movesplanned() > 4) return:
 and rotate the encoder slowly ,  watching,     to the inscription on the LCD did not disappear
speed axis Z - *2

**Comment by Blue-Marlin** [comment] 2016-02-27 16:52
Here the display update should work.
The buffer's content is limited.
The change rate of the value is not limited.
We have a final position update when LCD_CLICKED.

```
static void _lcd_move(const char* name, AxisEnum axis, int min, int max) {
  if (encoderPosition != 0) {
    refresh_cmd_timeout();
    current_position[axis] += float((int)encoderPosition) * move_menu_scale;
    if (min_software_endstops && current_position[axis] < min) current_position[axis] = min;
    if (max_software_endstops && current_position[axis] > max) current_position[axis] = max;
    encoderPosition = 0;
    if (movesplanned() <= 3)
      line_to_current(axis);
    lcdDrawUpdate = 1;
  }
  if (lcdDrawUpdate) lcd_implementation_drawedit(name, ftostr31(current_position[axis]));
  if (LCD_CLICKED) {
      line_to_current(axis);
      lcd_goto_menu(lcd_move_menu_axis);
  }
}
```

**Comment by AnatoliyKube** [comment] 2016-02-27 23:24
super, everything works, no errors, thank you.
Why not put in the Projects, that people would not suffer?

question - how to extend parking  , that , 1 -  lift   axis Z  5 мм , then
perform parking    (g28  end avto homt lcd )?

2016-02-27 18:52 GMT+02:00 Makaira notifications@github.com:

**Comment by thinkyhead** [comment] 2016-03-02 12:01
> Why not put in the Projects, that people would not suffer?

#3050 is now in `RCBugFix` and might be in `RC4` — although I believe there is a better solution.

**Closed** 2016-03-02 12:01 UTC
Labels: Verified bug!
