### ISSUE TITLE
Random garbage displayed on LCD screen.

### ISSUE THREAD

**Issue by Drmaestro** [MarlinFirmware/Marlin#3830] opened 2016-05-24 11:28 UTC
Hi,

On RC6, I occasionally get random garbage displayed on the LCD screen. It always happens on the info screen and pressing the encoder button always corrects the problem (by changing the screen). Is this a bug?

Thanks.

**Comment by jbrazio** [comment] 2016-05-24 12:09
This could be bad wiring, cold solder joint or noise on the cable going to the LCD.
Do the cables go close to the stepper cables ?

**Comment by Drmaestro** [comment] 2016-05-24 12:53
The left Z stepper cable is at 2 cm distance at a certain location. 

If wiring/soldering or the stepper cable were the culprits, wouldn't it be more frequent? I only get this once in a day maybe. 

I reported this issue to see if there are other people with a similar issue. If there are none, that would mean it's a local  problem with my own system.

**Comment by jbrazio** [comment] 2016-05-24 12:59
The other report that maybe similar is this #3815

**Comment by Drmaestro** [comment] 2016-05-24 13:02
I use the 4 line LCD, not the graphic one. Would it still apply to my case?

**Comment by jbrazio** [comment] 2016-05-24 15:14
Which IDE are you using right now ?

**Comment by thinkyhead** [comment] 2016-05-25 01:04
Random garbage on the screen mostly likely indicates a communication glitch which could be caused by loose wiring to the controller, a loose SD card, or electronic noise. The data on the LCD screen comes from the Arduino board, is sent to the controller by a serial line, and is not related to external USB connectivity. If only certain items on the screen were glitching out (for example just the XYZ coordinates) then I would start to think software bug. But if it's the whole screen, it's almost certainly hardware-related.

**Comment by Drmaestro** [comment] 2016-05-25 20:27
Ok. Thank you. I'll check my connections again.
@jbrazio My IDE is 1.6.8

**Comment by jbrazio** [comment] 2016-05-30 21:09
Thank you for your interest making Marlin better and reporting this issue but this topic has been open for a long period of time without any further development. Marlin has been under heavy development for the past couple of months and moving to it's last mile to finish the RC cycle and release **Marlin v1.1.0**. We suggest you to try out the latest [RCBugfix](https://github.com/MarlinFirmware/Marlin/archive/RCBugFix.zip) branch and reopening this issue if required.

**Closed as completed by jbrazio** 2016-05-30 21:09 UTC
Labels: T: Question
