### ISSUE TITLE
Optimize heater PWM: avoid all on simultaneously as far as possible

### ISSUE THREAD

**Issue by al-65** [MarlinFirmware/Marlin#15954] opened 2019-11-20 18:09 UTC
I have just started using marlin on an A8 printer.

I hvae noticed from measurements and code, that both nozzle and bed are switched on simultaneously in the PWM code, and switched off depending on what heater power is required by the PID. However, the synchronized switch-on of all heaters can be quite a task for the power supply.

I have experimentally modified the code to invert the bed behaviour, so that it will be switched off when the nozzle goes on, and switched on depending on requested power.
During heat-up, this does not make any difference, but in stable operation, when the sum of both PWM duty cycles is below 100%, it does no longer operate nozzle and bed simultaneously, reducing peak power from the power supply. I guess this can increase component life :)

I would gladly share my temperature.cpp but I must say my mods are simple and will not work for certain configs.

**Comment by boelle** [comment] 2019-11-20 18:39
will close this one again as it's not a bug or feature request which are the only things we have on the issue list

and workarounds for bad hardware will most likely not be integrated

but i could be wrong and in this case we can reopen if @thinkyhead think we should add the temperature.cpp

**Closed as completed by boelle** 2019-11-20 18:39 UTC
