### ISSUE TITLE
[BUG] (the issue with the gd32 chip)

### ISSUE THREAD

**Issue by cavaliersrus2** [MarlinFirmware/Marlin#24965] opened 2022-11-06 22:24 UTC
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

the issue with marlin and the gd32 chip that creality use and not being able to update firm ware.

sorry if this is in wrong spot i just made my account 

i have been able to flash the firmware many times now since testing marlin firmware ... 

i noticed that creality has a firmware for the ender 3 pro i downloaded it and tested flashing it and the name is GD_Ender-3 Pro_HW_V4.2.2_SW_V2.0.8.2_20221105.bin

so what i did was build my firmware using the enviroment STM32F103RE_creality

when it saves the firmware it saves like firmware-20221106-154904.bin so what i did was copy the name GD_Ender-3 Pro_HW_V4.2.2_SW_V2.0.8.2_20221105.bin and put my firmware as GD_Ender-3 Pro_HW_V4.2.2_SW_V2.0.8.2_20221106.bin
and it worked

so then i decided to try just renaming the firmware without any --- and used ___ so my firmware is like firmware_20221106_154904.bin sometimes it works and when it does not i just rename the second to last number in the firmware to firmware_20221106_154954.bin  so just changed the last to 5 and sofar ive reflashed about 15 firmware updates to the machine now with 0 problems sofar

just wanted to let the marlin team know aswell as others having issues with the gd32 chip

### Bug Timeline

old issue

### Version of Marlin Firmware

marlin bugfix 2.1.x

### Printer model

creality ender 3 pro with 4.2.2 board

### Electronics

stock 4.2.2 board

### Add-ons

bl touch

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Cura

### Host Software

Cura

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

**Comment by thisiskeithb** [comment] 2022-11-06 22:53
Duplicate of https://github.com/MarlinFirmware/Marlin/issues/21473

**Closed as completed by thisiskeithb** 2022-11-06 22:53 UTC
