### ISSUE TITLE
[BUG] Bilinear leveling disables set grid size with G29 P_

### ISSUE THREAD

**Issue by sdaitzman** [MarlinFirmware/Marlin#18270] opened 2020-06-12 11:03 UTC
### Bug Description

When bilinear leveling is enabled, `G29 P_` cannot be used to set the grid size.

### My Configurations

https://github.com/sdaitzman/marlin

### Steps to Reproduce

1. Send G-code `G29 P5`

**Expected behavior:**
The Z-probe is used at 25 points, in a 5x5 grid, to probe the bed level.

**Actual behavior:**
The Z-probe is used at 9 points, in a 3x3 grid, to probe the bed level (this is based on the firmware setting).

**Comment by boelle** [comment] 2020-06-21 00:39
@sdaitzman still an issue?

**Comment by sdaitzman** [comment] 2020-06-21 09:59
Just merged latest bugfix-2.0.0 (fun 5am merge) and will go downstairs and flash and see ☺️

https://github.com/sdaitzman/Marlin

**Comment by sdaitzman** [comment] 2020-06-21 10:58
Still only measuring and returning a 3x3 grid, sadly

![85222881-7d778680-b38c-11ea-8622-1bc8cec698f3](https://user-images.githubusercontent.com/1499476/85222931-bd3e6e00-b38c-11ea-8916-93671c2622ec.JPG)

<img width="560" alt="Screen Shot 2020-06-21 at 6 57 52 AM" src="https://user-images.githubusercontent.com/1499476/85222890-87998500-b38c-11ea-8e60-b03e05765872.png">

**Comment by boelle** [comment] 2020-06-21 11:00
did you do M502 and M500 after the update of firmware?

**Comment by sdaitzman** [comment] 2020-06-21 11:05
When I powered on the printer it had a CRC EEPROM fail and so was reset anyway, but will try that and let you know if it changes things

**Comment by boelle** [comment] 2020-06-21 11:07
just to rule out that any stupid setting in EEprom is left to play tricks

**Comment by sdaitzman** [comment] 2020-06-21 11:11
Yeah, makes sense. I ran `M502` and `M500` and power-cycled for good measure, and `G29 P4` still probes a 3x3 grid unfortunately.

**Comment by sjasonsmith** [comment] 2020-07-04 10:37
The G29 documentation indicates that the `P` option is only available with `AUTO_BED_LEVELING_LINEAR`.
https://marlinfw.org/docs/gcode/G029-abl.html

Looking at the code I can verify that the option is only parsed when `AUTO_BED_LEVELING_LINEAR` is enabled.

LINEAR and BILINEAR operate in very different ways. With LINEAR leveling, you an probe any number of points you want, but the stored output is always a flat plane defined by three points. This means you can dynamically change the number of points without impacting the layout of the EEPROM.

With BILINEAR, even point probed has to be stored to the EEPROM. The space allocated for this is decided at compile time, and cannot be adjusted dynamically.

Since this is not a bug in Marlin, I am closing this issue report.  For additional help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org/)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).

**Closed as completed by sjasonsmith** 2020-07-04 10:37 UTC
