### ISSUE TITLE
Serial communication issue N8 G28*26

### ISSUE THREAD

**Issue by abra12** [MarlinFirmware/Marlin#11216] opened 2018-07-07 15:27 UTC
Hello, today out of a blue bug occurred with serial communication. Lets say if i send command it gets N prefix in front and gets multiplied by random number for ex, i type `G28` when i send it it becomes `N16 G28*26` and with each command number next to N gets bigger by 1 . If i print something it looks like `G1 Z0.24*20` and Z height  gets messed up and prints mid air. I tried installing latest marlin no effect also tried another usb cable without any results and also tried to install Arduino example sketch with serial communication and there was no serial issues.
I couldnt find anything on google so i have to post here :(
<a href="https://ibb.co/fFoq98"><img src="https://preview.ibb.co/eqvFbo/Capture.jpg" alt="Capture" border="0"></a>

**Comment by ManuelMcLure** [comment] 2018-07-07 21:11
The `N<number>` is a line number, and the `*<number>` is a checksum. Both of these are being generated by your host software, not by Marlin. So you need to check your host software to see where the option to send these got enabled. That said, Marlin should work just fine with those additions to the transmitted gcode - for example I'm currently printing with OctoPrint which adds the same line numbers and checksums to the transmitted gcode and everything is working fine.

**Comment by abra12** [comment] 2018-07-08 08:09
Thank you for input. It happens with octoprint and connecting directly to computer. And i cant print because my first layer should be 0.24mm and then it gets multiplied by 20 or some other checksum number and it prints mid air. I will buy new arduino

**Comment by ManuelMcLure** [comment] 2018-07-08 17:33
There's something else happening, then. Marlin doesn't do any multiplication of the checksum numbers - it just uses them to verify that the transmission was correct.

**Comment by abra12** [comment] 2018-07-17 17:36
Wow i dont know what to do im completely lost. I bough new arduino flashed marlin to it and problem is here on all host softwares. It happens on laptopt, desktop pc, and octoprint even though i didnt change anything and it wasnt happening. How the hell on earth this is possible.

<a href="https://ibb.co/hBJr3d"><img src="https://preview.ibb.co/kPCvUJ/jawdrop.jpg" alt="jawdrop" border="0"></a>

**Comment by thinkyhead** [comment] 2018-07-17 18:08
It sounds like you may just have some incorrect movement settings. So first, test with the latest `bugfix-1.1.x` (and/or `bugfix-2.0.x`) branch to see where it stands. Be sure to send `M502`, `M500` after flashing the firmware to make sure the EEPROM is reset to the settings in your configurations. If the problem is resolved by the fresh install then we can close this issue.

If the issue isn't resolved by the new install, then we should investigate further. At that point, you'll want to get the output of `M503 S0` and paste into in your reply, and you should also ZIP and attach your configuration files so we can check them for any errors.

**Comment by abra12** [comment] 2018-07-17 20:43
I will try to install latest marlin tommorrow after work and paste M503 S0 output and configuration files.
I also used M502 M500 all the time after reuploading sketch. 
Thank you for helping.

**Comment by abra12** [comment] 2018-07-17 20:44
I will try to install latest marlin tommorrow after work and paste M503 S0 output and configuration files.
I also used M502 M500 all the time after reuploading sketch. 
Thank you very much for helping.

**Comment by abra12** [comment] 2018-07-18 17:15
<details><summary>Log Output</summary>

```
18:10:46.430 : Printer reset detected - initalizing
18:10:46.431 : start
18:10:46.431 : echo:Marlin bugfix-1.1.x
18:10:46.434 : echo: Last Updated: 2018-01-20 | Author: (none, default config)
18:10:46.438 : echo:Compiled: Jul 18 2018
18:10:46.442 : echo: Free Memory: 5517  PlannerBufferBytes: 1232
18:10:46.446 : echo:EEPROM version mismatch (EEPROM=? Marlin=V55)
18:10:46.450 : echo:Hardcoded Default Settings Loaded
18:10:46.660 : N1 M110*34
18:10:46.660 : N2 M115*36
18:10:46.660 : N3 M105*36
18:10:46.660 : N4 M114*35
18:10:46.660 : N5 M111 S6*98
18:10:46.668 : N6 T0*60
18:10:46.668 : N7 M20*22
18:10:46.669 : N8 M80*19
18:10:46.669 : N9 M105*46
18:10:46.722 : N10 M220 S100*80
18:10:46.723 : FIRMWARE_NAME:Marlin bugfix-1.1.x (Github) SOURCE_CODE_URL:https://github.com/MarlinFirmware/Marlin PROTOCOL_VERSION:1.0 MACHINE_TYPE:3D Printer EXTRUDER_COUNT:1 UUID:cede2a2f-41a2-4748-9b12-c55c62f367ff
18:10:46.723 : Cap:SERIAL_XON_XOFF:0
18:10:46.725 : Cap:EEPROM:1
18:10:46.725 : Cap:VOLUMETRIC:1
18:10:46.725 : Cap:AUTOREPORT_TEMP:1
18:10:46.729 : Cap:PROGRESS:0
18:10:46.729 : Cap:PRINT_JOB:1
18:10:46.729 : Cap:AUTOLEVEL:0
18:10:46.733 : Cap:Z_PROBE:0
18:10:46.733 : Cap:LEVELING_DATA:0
18:10:46.733 : Cap:BUILD_PERCENT:0
18:10:46.737 : Cap:SOFTWARE_POWER:0
18:10:46.737 : Cap:TOGGLE_LIGHTS:0
18:10:46.741 : Cap:CASE_LIGHT_BRIGHTNESS:0
18:10:46.741 : Cap:EMERGENCY_PARSER:0
18:10:46.745 : Cap:AUTOREPORT_SD_STATUS:0
18:10:46.745 : Cap:THERMAL_PROTECTION:1
18:10:46.749 : N11 M221 S100*80
18:10:46.764 : N12 M111 S6*84
18:10:46.764 : X:0.00 Y:0.00 Z:0.00 E:0.00 Count X:0 Y:0 Z:0
18:10:46.765 : echo:DEBUG:INFO,ERRORS
18:10:46.765 : echo:Active Extruder: 0
18:10:46.765 : echo:Unknown command: "M20"
18:10:46.765 : N13 T0*8
18:10:46.765 : N14 M155 S1*85
18:10:46.765 : echo:Unknown command: "M80"
18:10:46.774 : echo:DEBUG:INFO,ERRORS
18:10:46.774 : echo:Active Extruder: 0
18:10:55.549 : N15 M502*16
18:10:55.555 : echo:Hardcoded Default Settings Loaded
18:11:01.701 : N16 M500*17
18:11:03.927 : echo:Settings Stored (655 bytes; crc 33)
18:11:06.125 : N17 M503 S0*80
18:11:06.130 : G21    ; (mm)
18:11:06.130 : M200 D3.00
18:11:06.135 : M200 D0
18:11:06.135 : M92 X80.00 Y80.00 Z4000.00 E500.00
18:11:06.139 : M203 X300.00 Y300.00 Z5.00 E25.00
18:11:06.143 : M201 X3000 Y3000 Z100 E10000
18:11:06.143 : M204 P3000.00 R3000.00 T3000.00
18:11:06.151 : M205 B20000 S0.00 T0.00 X10.00 Y10.00 Z0.30 E5.00
18:11:06.151 : M206 X0.00 Y0.00 Z0.00
18:11:06.155 : M301 P22.20 I1.08 D114.00
```
</details>

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/2206683/Configuration.zip)

**Comment by abra12** [comment] 2018-07-24 18:03
@thinkyhead Sorry to disturb you. But maybe you have any clue on what is going on here? Thank you in advance!

**Comment by thinkyhead** [comment] 2018-11-05 08:55
Presuming this is solved.

**Closed as completed by thinkyhead** 2018-11-05 08:55 UTC
Labels: C: Hosts & Protocols, T: Question
