### ISSUE TITLE
MKS Gen 1.4 + TMC 2130 Problem

### ISSUE THREAD

**Issue by Koby88** [MarlinFirmware/Marlin#20007] opened 2020-11-03 07:35 UTC
I got exact same issue with MKS Gen 1.4 and tmc2130 i tried all but it works great on marlin 1.9 but not on 2.0 exact same error like in link bellow, i dont know how to fix it.
https://github.com/MarlinFirmware/Marlin/issues/17478

**Comment by ellensp** [comment] 2020-11-03 08:30
Please attach your configuration files.
Please test the [`bugfix-2.0.x` branch](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.0.x.zip) to see where it stands. If the problem has been resolved then we can close this issue. If the issue isn't resolved yet, then we should investigate further.

**Comment by boelle** [comment] 2020-11-03 17:25
Configurations, please
Please ZIP up your `Configuration.h` and `Configuration_adv.h` files (as
requested in the Issue template) and drop them into your next reply.
We'll check them over and see if anything is amiss.

Please test the [`bugfix-2.0.x branch`](https://github.com/MarlinFirmware/Marlin/tree/bugfix-2.0.x) to see where it stands. If the problem has been resolved then we can close this issue. If the issue isn't resolved yet, then we should investigate further.

**Comment by Koby88** [comment] 2020-11-03 22:34
I hawe tested bugfix with no success. Here is my configuration and connection pictures, sorry for dirt and dust. You can see that board is not powered it is coz i take her out so i can take some pictures. I try all kind of connections with no joy, then go back to marlin 1.9 configure all and it is working without issue i hope you can help.
[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/5484466/Marlin.zip)

![20201103_164838](https://user-images.githubusercontent.com/39095326/98047704-acb6fd80-1e2c-11eb-9143-354291bc3e91.jpg)
![20201103_164901](https://user-images.githubusercontent.com/39095326/98047711-b04a8480-1e2c-11eb-8d62-1541b5509150.jpg)

**Comment by Koby88** [comment] 2020-11-03 22:47
I change topic name coz i name it by mistake Mgs Base instead Mks Gen

**Comment by ellensp** [comment] 2020-11-03 23:37
You also need to define the following in Configuration_adv.h, or they are also setup to use pin 40 and 42 
#define Z_CS_PIN          -1
#define E0_CS_PIN         -1
and add
#define E_MUX1_PIN  -1 as it also uses 42

**Comment by ellensp** [comment] 2020-11-04 02:34
Are you using vscode or arduino ide to compile?
The reason I ask is that arduino IDE you have to manually install the library TMCStepper version 0.7.1 when vscode will download and install correct version automatically.

**Comment by Koby88** [comment] 2020-11-04 11:19
If i understand you correct i just need to take of **//** before #define Z_CS_PIN -1, #define E0_CS_PIN -1 and #define E_MUX1_PIN -1 or i need do asign other pins for them ? I use vscode

**Comment by Koby88** [comment] 2020-11-05 06:35
> Are you using vscode or arduino ide to compile?
> The reason I ask is that arduino IDE you have to manually install the library TMCStepper version 0.7.1 when vscode will download and install correct version automatically.

Thanks a lot, this worked for me :) You can close the topic now

**Comment by Koby88** [comment] 2020-11-05 06:36
> You also need to define the following in Configuration_adv.h, or they are also setup to use pin 40 and 42
> #define Z_CS_PIN -1
> #define E0_CS_PIN -1
> and add
> #define E_MUX1_PIN -1 as it also uses 42

Thanks a lot @ellensp that worked for me :) You can close the topic now

**Closed as completed** 2020-11-05 06:46 UTC
Labels: Bug? False Alarm
