### ISSUE TITLE
[BUG] Power Loss Recovery does not resume

### ISSUE THREAD

**Issue by Keelan-Moore** [MarlinFirmware/Marlin#25416] opened 2023-02-22 20:41 UTC
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Powerloss recovery does not resume after turning off and restoring power manually. Unclear whether it wrote to the SD card but there is a PLR unix file on the card.

There is a stale [bug report that](https://github.com/MarlinFirmware/Marlin/issues/25128) includes some code change as a workaround but failed to resolve issues. 

### Expected behavior

I expected the following:

1. Start a print
2. Turn power off after a couple layers 
3. Turn power on
4. Marlin identifies PL and prompts to resume print
5. PRL routine follows

### Actual behavior

1. Start a print
2. Turn power off after a couple layers 
3. Turn power on
5. No prompt. Had to attach the SD card in the settings.

### Steps to Reproduce

See expected behaviour

### Version of Marlin Firmware

2.1.x bugfix

### Printer model

BIQU B1 SE Plus

### Electronics

BTT SKR 2

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Prusa Slicer

### Host Software

SD Card (headless)

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[config.zip](https://github.com/MarlinFirmware/Marlin/files/10808134/config.zip)

**Comment by thisiskeithb** [comment] 2023-02-22 20:44
Duplicate of https://github.com/MarlinFirmware/Marlin/issues/25128

**Closed as completed by thisiskeithb** 2023-02-22 20:44 UTC
