### ISSUE TITLE
[bug] Character LCD garbled custom characters

### ISSUE THREAD

**Issue by GiovanniCapizzi** [MarlinFirmware/Marlin#9741] opened 2018-02-21 01:21 UTC
Before everything I would like to know if is it dangerous to flash many times a board like a gt2560 A+ cause I'm worried that it can damage the memory ( I am at 25 flashes... Cause adjustments and tries... Many tries..)

The problem:
I have a Geeetech pro W and it has this A+ board. I mounted a BlTouch and use latest firmware 1.1.8 with a config file for this board. But the screen makes strange symbols that changes randomly..
It is a HD44780 display I suppose.

The second problem it's that moving axis function..with the stock previous marlin firmware when I used the rotary encoder with X and Y axis it always gone very smooth, now it makes pauses, it's like it lags a lot. For example if I rotate it continuously it waits me to stop before move something. It's really annoying and I don't know why it does this..

Character,video and config.h
https://drive.google.com/folderview?id=1W7VN4nO8L5BpQz2Mjra52Hx1Q1R9c1Xe

I will check 1.1.x bugfix or 2

**Comment by GMagician** [comment] 2018-02-21 08:22
As I know flash memory should permit at least 100000 write cycles.
For your real issues I can suggest to try 1.1.x-bugfix branch to see if it resolves

**Comment by gloomyandy** [comment] 2018-02-21 15:13
I've also seen the strange characters on the display (I'm using 1.1.x-bugfix, but I also saw them with 1.1.8). I think it only affects the "custom characters" used for things like "feedrate", "degreees", "hotend" etc. I suspect that the logic that is supposed to make sure that the correct custom characters are loaded for the current display has a bug. So instead of using the custom characters for the "info display" it is using the the ones designed for the menu page (or whatever). In this case instead of displaying the custom character for the "hotend temperature" it has used the custom character to go up a level in the menu system, presumably they use the same character slot.

**Comment by GiovanniCapizzi** [comment] 2018-02-21 16:01
Put the marlin 1.1.x bugfix and now characters seems fine, but bl touch doesn't work while homing. If I try the menu commands it works. I doesn't deploy the probe and it tries to go down on the bed without stopping...

The moving axis problem remain the same.. 

Another thing I saw it's the PID for bed and extruder changes. Before in my pro w I had totally other values but this new one on the config.h seems to be for mk8 and mk2a which are the ones I have

**Comment by thinkyhead** [comment] 2018-02-23 08:45
> it waits me to stop before move something. It's really annoying and I don't know why it does this..

It was a conscientious change in behavior because previously it was too easy to cause several long moves to pile up in the queue when all you wanted was one long move to a particular point on the axis.

**Comment by thinkyhead** [comment] 2018-02-23 08:47
> Another thing I saw it's the PID for bed and extruder changes.

We have another issue open about this already. If you see a lot of wavering between temperatures try lowering your `PID_MAX` and `MAX_BED_POWER` values and then re-tune your PID.

**Comment by GiovanniCapizzi** [comment] 2018-02-23 08:56
For now I'm using old pro W values, cause the bed blinked a lot. For the sleep inserted, I found in ultralcd.cpp and deactivated :P ...

For the characters, well it's not a big deal, I saw that also 1.1.x bugfix has this but it's not very important ( for now I think)

**Comment by thinkyhead** [comment] 2018-02-23 09:01
> I suspect that the logic that is supposed to make sure that the correct custom characters are loaded for the current display has a bug. 

In my limited experience, it only ever seems to affect them on the initial boot. It was fixed at one point, but the issue returned somewhere around 1.1.5 or 1.1.6.

**Comment by GiovanniCapizzi** [comment] 2018-02-23 14:28
Can I help somehow? To understand

**Comment by thinkyhead** [comment] 2018-02-24 02:56
Play with delays before/after/during character init, lcd init, screen clear, etc., until they reliably work. Then we'll know what the problem is. SPI clocks out bits to the display, and if the display isn't listening or has "static" on its lines then bits get corrupted or dropped.

**Comment by cjsoong** [comment] 2018-03-05 14:37
bugfix 2.0x also have the same problem

**Comment by Bob-the-Kuhn** [comment] 2018-03-07 11:56
The garbled characters are caused by an initialization problem,  See PR #9981 for details.

Here's the corrected 2.0.x file from the PR.
[ultralcd_impl_HD44780 2.0.x.zip](https://github.com/MarlinFirmware/Marlin/files/1788873/ultralcd_impl_HD44780.2.0.x.zip)

A 1.1.x PR will be done later Wednesday.

**Comment by Bob-the-Kuhn** [comment] 2018-03-08 04:04
The PRs have been merged.  Please see if the new code takes care of the problem.

**Comment by boelle** [comment] 2019-02-20 09:12
@GiovanniCapizzi is the problem solved with latest bugfix 2.0?

**Comment by GiovanniCapizzi** [comment] 2019-02-20 14:15
Yes, sorry I forgot to update. I've installed  the latex 1.1.x (not bugfix branch) on my Geeetech Pro W. I used the new configuration for this board (GT2560) and it seems really good. Display has never gone bad (maybe once, but never again).

**Comment by boelle** [comment] 2019-02-20 14:18
then maybe click the green close button below?

**Comment by GiovanniCapizzi** [comment] 2019-02-20 14:25
They were talking about the bugfix branch, I was expecting another question.

**Closed as completed** 2019-02-20 14:25 UTC
Labels: Bug: Confirmed !, C: LCD & Controllers
