### ISSUE TITLE
[BUG] Marlin downloads with Files Missing.

### ISSUE THREAD

**Issue by Osprey19** [MarlinFirmware/Marlin#14739] opened 2019-07-27 03:49 UTC
### Description

every time i download marlin, there are two files missing from the zip. .pioenvs and .piolibdeps.

### Steps to Reproduce

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

#### Additional Information
![image](https://user-images.githubusercontent.com/53360522/61989590-0280e100-b000-11e9-8a0b-af1566084895.png)

**Comment by thisiskeithb** [comment] 2019-07-27 04:44
Those won't show up until you open the project in your IDE/compile Marlin.

**Comment by teemuatlut** [comment] 2019-07-27 06:59
`.piolibdeps` is the folder where PlatformIO automatically downloads dependencies like external libraries.
`.pioenvs` is the folder where PlatformIO builds the Marlin project and the final binary.

Don't forget to close the issue if you have no further questions =)

**Comment by boelle** [comment] 2019-07-27 09:06
i will close this one as its clearly not a bug, if you have further questions have a look here:

https://github.com/MarlinFirmware/Marlin/issues/14694

a list of places where you should ask questions

**Closed as completed by boelle** 2019-07-27 09:06 UTC
