### ISSUE TITLE
Second temp sensor for ambient temp

### ISSUE THREAD

**Issue by Kev0123** [MarlinFirmware/Marlin#3982] opened 2016-06-08 15:18 UTC
Hi

I'm using a GT2560 and wanted to use the left over temp-in to show the ambient temp.
So I would be able to log it and you could may implement a minimum print temp?!
Is it possible?

Regards 
Kev0123

**Comment by thinkyhead** [comment] 2016-06-08 19:01
Currently all of Marlin's temperature sensing code is tied to the heated bed and hotends. So you would need to implement this as an add-on feature (perhaps `AMBIENT_TEMP_SENSOR`), making sure not to step on any settings that "imply" more hotends.

**Comment by maukcc** [comment] 2016-06-10 10:15
That would be a nice feature.
We are using the 3rd extruder to display the ambient temp at the moment, which is not ideal as you get a lot of 3rd extruder additions.

**Comment by thinkyhead** [comment] 2016-06-11 00:22
If I were to implement this (which I may) then it would automatically utilize the first unused E thermistor plug. So if you had E0 and E1 connected, you would only need to set `EXTRUDERS 2` and connect the ambient sensor to the E2 thermistor plug.

**Comment by Kev0123** [comment] 2016-06-11 07:16
Wow this would be great! Thanks for giving a thought!

**Comment by maukcc** [comment] 2016-06-11 08:26
That will be better than it is now. 
What will happen when 4 extruders are hooked up? will the ambient temp just be lost some how?(I have no problem with that for now)
Can we also set (in the pins file): 

> #define TEMP_CHAMBER_PIN           13

**Comment by thinkyhead** [comment] 2016-06-13 00:39
> What will happen when 4 extruders are hooked up?

If all the E thermistor pins are full then an override would be needed.

> Can we also set (in the pins file): `TEMP_CHAMBER_PIN`

If that were to be included in all the pins files then it would be the _only option_, and would not allow automated use of the next unused E thermistor plug. So I suggest instead to make it a disabled-by-default sub-option of the feature, then it will only be used if it set as an override.

``` cpp
//#define AMBIENT_TEMP_SENSOR
#if ENABLED(AMBIENT_TEMP_SENSOR)
  //#define TEMP_AMBIENT_PIN TEMP_1_PIN
#endif
```

If there is no override for `TEMP_AMBIENT_PIN` set, we fall back to the next available `TEMP_n_PIN`. If the fallback can't be done, then it will print a compile error "`Please set an explicit TEMP_AMBIENT_PIN.`"

**Comment by boelle** [comment] 2017-04-26 15:12
maybe add this to milestone 1.1.1, but would ambient not be the same as chamber temp?

if i remember correct i suggested that before this one.

**Comment by maukcc** [comment] 2017-05-03 11:31
I think we need to change this to CHAMBER_TEMP_SENSOR and TEMP_CHAMBER_PIN
as ambient would suggest the temp outside of the printers volume.

**Comment by fiveangle** [comment] 2017-06-26 15:49
Doesn't @MagoKimbra 's fork have this already ?

(https://github.com/MagoKimbra/MarlinKimbra):

> * Added Cooler and Hot Chamber

**Comment by fiveangle** [comment] 2017-06-26 15:51
> would ambient not be the same as chamber temp?

To me, "Ambient" implies temperature of the universe outside of the printer, while "Chamber" implies temperature inside temperature-controlled print chamber.

**Comment by thinkyhead** [comment] 2018-02-06 08:13
Dupe of #973.

**Closed as completed by thinkyhead** 2018-02-06 08:13 UTC
Labels: T: Feature Request
