### ISSUE TITLE
New algorithm Velocity Extruding for more smooth print

### ISSUE THREAD

**Issue by avaradus** [MarlinFirmware/Marlin#916] opened 2014-05-13 05:21 UTC
Request support new algorithm in Marlin.
Extruding without the E or A axis. The velocity of the extruder is linked with the velocity of the nozzle.
Width of the line (perimeter/infill) and height of the layer are set from the g-codes, and calculate the correct cross section to be extruded.

More info about:
http://basdebruijn.com/2014/05/machinekit-and-additive-manufacturing/

**Comment by whosawhatsis** [comment] 2014-05-13 06:30
This post talks about two completely different things.

The first is a method of controlling extrusion volume based on cross-sectional area multiplied by feedrate rather than sending pre-calculated volumes to the gcode interpreter, which might be a good idea, but it won't affect print quality. All the same math, you're just changing where the separation is between what is calculated in the slicer and what is calculated in the gcode interpreter.

The second, completely independent thing is the addition of an advance algorithm which attempts to reduce blobbing by pre-emptively equalizing nozzle pressure. Marlin has had one of these for years (`ADVANCE`), and there's currently a pull request pending to add one to Slic3r as well. "Velocity Extruding" is not necessary for this.

**Comment by bkubicek** [comment] 2014-05-13 06:45
i can't find the pull request, do you know which it is?
https://github.com/alexrj/Slic3r/pulls
My method cannot be implemented in anything that sends standard gcode, because it requires asynchronous moves. So it would be quite surprising if it could be put into the slicer.

Bernhard

**Comment by glx51mm** [comment] 2015-01-12 08:14
Any updates on this one? This is the most important feature for getting high speed - high quality prints. Seems strange it doesn't get much attention.

**Comment by nophead** [comment] 2015-01-12 09:57
Well for one thing the name is wrong. The speed of the extruder is already linked to the velocity of the nozzle since all axes accelerate together.

**Comment by glx51mm** [comment] 2015-01-12 11:10
I have no reason to argue with what you say but when setting low accelerations on a Marlin powered printer, the extrusion is not smooth. More material than normal (full speed) is accumulated during acceleration/deceleration. Am I missing something?

**Comment by nophead** [comment] 2015-01-12 11:18
Exactly the right volume is extruded, it is just in the wrong place because of the lag in the extruder. As it decelerates at the end of the line the flow rate of the plastic doesn't decelerate as fast, so you get too much. As it accelerates away you get too little. The number of E steps is exactly right though, and in step with the axes, so the total plastic volume is correct. The issue is it shouldn't be in step with the axes, it should be advanced.

**Comment by glx51mm** [comment] 2015-01-12 11:34
That makes sense. So considering this, the best prints you can have by using as high acceleration/jerk values as possible while keeping the speed constant. Of course this is limited by the printer mechanical construction but this in theory should give the best results. The lag should also be reduced by extruding in as low temp as possible.

**Comment by nophead** [comment] 2015-01-12 11:52
Yes high acceleration and lower speeds give better prints. I find a little over extrusion at the end of zig zag infill but that helps it bind to the perimeter.

I think actually higher temperature is better for reducing lag as the plastic is then less viscous, so the pressure is less, so it compresses less.

**Comment by alexborro** [comment] 2015-01-12 12:15
What about fixing the advance algorithm? I have heard Jetty Firmware has a
great one.

Cheers.

Alex.
Em 12/01/2015 09:53, "Chris" <notifications@github.com> escreveu:

**Comment by boelle** [comment] 2015-04-26 11:22
How many still have an interest in this one? is what we have not good enough? and how much can be gained held against the work it will require?

**Comment by thinkyhead** [comment] 2015-04-27 03:25
I think we need more charts and graphs to go forward on this one. I like to learn (for example) that high acceleration and low speeds give better quality. But also I would like to know optimal acceleration for mid-to-high speeds also. If nothing else, we can produce some better documentation on tuning the acceleration and jerk settings.

**Comment by boelle** [comment] 2015-05-31 13:35
i'm tempted to close this one as not have happened for the better part of 6 months... no one seems to have active interest

**Comment by brainscan** [comment] 2015-05-31 14:07
I have an interest but unfortunately lack the ability to help move this forward. I've been trying to look into the various methods others have worked on but I'm a long way off being able to implement something.

Maybe it's something to keep for the future, the developers have a lot on their plate at the moment from the looks of things.

**Comment by boelle** [comment] 2015-05-31 14:10
there  are a lot on the plate yes.... and we cant please all...

**Comment by boelle** [comment] 2015-06-29 10:24
@bkubicek any chance we can see a PR in the near future that implements this one?

**Comment by thinkyhead** [comment] 2015-07-03 23:01
Fingers crossed. The other firmware I looked at uses an additional timer interrupt to implement this feature. We would probably have to do it in the same interrupt used for stepper movement.

**Comment by CCS86** [comment] 2015-07-27 03:35
I agree with @whosawhatsis 

"By breaking a segment into multiple segments, it should be possible to at least approximate the effect in a way that is "better than nothing". I believe what's being proposed is to change the extrusion rate a number of millimeters before where it is supposed to change (due to a feedrate and/or extrusion width change), with that number of millimeters being determined by the magnitude of the difference between the two extrusion speeds.

I agree, though, that this type of thing is better handled after acceleration is calculated than before. Anyway, my point was simply that converting to "velocity extrusion" is not required to implement something like this."

Firmware implementation would be the best realization of accounting for the drive spring/lag effect, but take the most effort. 

On the slicer side, you could introduce a tunable "lag" parameter to decouple extruder drive moves from print head moves, in a preemptive way.

**Comment by thinkyhead** [comment] 2015-07-27 10:10
@CCS86 Among slicers, Skeinforge has the ability to both stop extrusion early (to allow built-up pressure to finish a line) and to start extrusion early (to build up a little pressure). I'm not aware of any other slicers having this feature.

**Comment by CONSULitAS** [comment] 2015-07-27 13:57
@thinkyhead
There is experimental support in Slic3r since 1.2.2 (http://slic3r.org/releases/1.2.2, `New experimental feature for Pressure Management based on the advance algorithm (#1203 #1677 #2018)`). Recent release is 1.2.9.

But I had no time to test it, because i am far to far away from my printer. :-)

**Comment by CCS86** [comment] 2015-07-27 14:13
@thinkyhead & @CONSULitAS 

Thanks for the info guys. I'm interested to check it out.

**Comment by Nandox7** [comment] 2015-07-27 14:22
Isn't that what the Advance Extrusion settings in the `Configuration_adv.h` tries to address?

**Comment by CCS86** [comment] 2015-07-27 14:24
@Nandox7 

I believe so, but from what I've read, it is broken in later versions of Marlin. I haven't tested yet.

**Comment by Nandox7** [comment] 2015-07-27 14:32
I did some tests with it but results weren't that good. The fact you can't change the params in eeprom didn't help and I ended postponing further testing.

I was also looking into the full implementation present in the sailfish fw and how to port it to Marlin. But lack of time didn't help on that task.

**Comment by thinkyhead** [comment] 2015-07-27 22:28
Please test the built-in `ADVANCE` when you get a chance. It hasn't changed (much) in a long while. I would be interested to know what state it's in.

**Comment by CCS86** [comment] 2015-07-27 22:31
It would be great to vary the coefficient via G code, to enable fast testing iterations.

**Comment by thinkyhead** [comment] 2015-07-29 03:07
@CCS86 Are you referring to the value set by `EXTRUDER_ADVANCE_K` which is `0.0` by default?

**Comment by CCS86** [comment] 2015-07-29 04:32
@thinkyhead  Yes, I was.

**Comment by Nandox7** [comment] 2015-07-30 21:04
Started looking into this.
I could be wrong but the ADVANCE code is not used, all the calculations are made but it is not actually applied.
I continuously increase the value of K and there is no visible effect.
Also in the planner and stepper code it doesn't seem to be put into use.

**Comment by thinkyhead** [comment] 2015-07-31 01:28
@Nandox7 You can try un-commenting these lines in `plan_buffer_line` to see if anything is happening…

``` cpp
/*
SERIAL_ECHO_START;
SERIAL_ECHOPGM("advance :");
SERIAL_ECHO(block->advance/256.0);
SERIAL_ECHOPGM("advance rate :");
SERIAL_ECHOLN(block->advance_rate/256.0);
*/
```

**Comment by Nandox7** [comment] 2015-07-31 12:28
@thinkyhead I did that and I can see the values it generates.

Thing is in the planner.cpp those values aren't used in any way.
The other place I see them kinda been used is in stepper.cpp.

```
#ifdef ADVANCE
  unsigned char old_OCR0A;
  // Timer interrupt for E. e_steps is set in the main routine;
  // Timer 0 is shared with millies
  ISR(TIMER0_COMPA_vect)
  {
    old_OCR0A += 52; // ~10kHz interrupt (250000 / 26 = 9615kHz)
    OCR0A = old_OCR0A;
    // Set E direction (Depends on E direction + advance)
    for(unsigned char i=0; i<4;i++) {
      if (e_steps[0] != 0) {
        E0_STEP_WRITE(INVERT_E_STEP_PIN);
        if (e_steps[0] < 0) {
          E0_DIR_WRITE(INVERT_E0_DIR);
          e_steps[0]++;
          E0_STEP_WRITE(!INVERT_E_STEP_PIN);
        }
        else if (e_steps[0] > 0) {
          E0_DIR_WRITE(!INVERT_E0_DIR);
          e_steps[0]--;
          E0_STEP_WRITE(!INVERT_E_STEP_PIN);
        }
      }
 #if EXTRUDERS > 1
```

So a timer is set that will use the the calculated values.
I'm still going over the code and understand how it works, but wouldn't be better to have the values add/subtracted to the steps of the E rather than having a timer doing it instead?

**Comment by thinkyhead** [comment] 2015-07-31 21:48
@Nandox7 Dang, you are correct. It looks like most of the pieces are in place, but not quite all together. I will need to look at some other firmwares' advance handling and see where they create and apply these values.

Then there's code like this:

``` cpp
for(int8_t i=0; i < step_loops; i++) {
  advance += advance_rate;
}
```

…which seems like it could just be:

``` cpp
advance += advance_rate * step_loops;
```

**Comment by CCS86** [comment] 2015-07-31 21:49
Awesome, keep us posted Scott!

**Comment by thinkyhead** [comment] 2015-07-31 21:52
Looking particularly at [Sailfish](https://github.com/jetty840/Sailfish-MightyBoardFirmware), which [seems to have this down](http://www.makerbot.com/sailfish/tuning#5) very well.

**Comment by CCS86** [comment] 2015-07-31 22:42
Too bad Makerbot is a turd of a company. They seem to have some good minds
over there.

**Comment by Nandox7** [comment] 2015-07-31 23:25
@thinkyhead yeah they do. I was looking at their implementation here.
https://github.com/jetty840/Sailfish-MightyBoardFirmware (JKN_ADVANCE)
As it seems up-to-date in terms of code updates.

There is also a much older implementation that seems to be the one where these originated from by Matt Roberts (http://reprap.org/wiki/Mattroberts'_Firmware).

In overall I spotted a few other things that look like it can be improved likes STEPS_MM_E that are already defined in the FW.

**Comment by Lenbok** [comment] 2015-08-01 00:17
@CCS86 @Nandox7 Don't give any of the credit to Makerbot for that -- it's due to the hard work of @dcnewman and @jetty840 who have a fantastic focus on quality and getting the little details right (rather than the Makerbot "Done Manifesto" approach)

**Comment by CCS86** [comment] 2015-08-08 19:22
@thinkyhead, have you dug any deeper on this?

Thanks

**Comment by thinkyhead** [comment] 2015-08-12 01:56
@CCS86 After we get this release done I want to get into this more. For now just consider this feature not-implemented. Let's close this here and start a new topic on the [MarlinDev issue queue](https://github.com/MarlinFirmware/MarlinDev/issues), where we can be more developer-centric.

**Closed by thinkyhead** 2015-08-12 01:56 UTC
Labels: Feature Request, On Hold During Bugfix
