### ISSUE TITLE
[BUG] bugfix-2.0.x Does not compile with Ender 6 config files

### ISSUE THREAD

**Issue by msedlak77** [MarlinFirmware/Marlin#21739] opened 2021-04-29 08:42 UTC
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

bugfix-2.0.x Does not compile with Ender 6 (Creality) config files (Configuration_adv.h, Configuration.h). 

### Bug Timeline

It compiled with the std config files. Used TH3ds version earlier for ender 6.

### Expected behavior

Complete compilation.

### Actual behavior

Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS D:\Marlin> platformio run -e STM32F103RET6_creality
Processing STM32F103RET6_creality (platform: ststm32@~12.0; board: genericSTM32F103RE; framework: arduino)
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/ststm32/genericSTM32F103RE.html
PLATFORM: ST STM32 (12.0.0) > STM32F103RE (64k RAM. 512k Flash)
HARDWARE: STM32F103RET6 72MHz, 64KB RAM, 512KB Flash
DEBUG: Current (jlink) External (blackmagic, cmsis-dap, jlink, stlink)
PACKAGES:
 - framework-arduinoststm32-maple 3.10000.201129 (1.0.0)
 - tool-stm32duino 1.0.2
 - toolchain-gccarmnoneeabi 1.70201.0 (7.2.1)
Converting Marlin.ino
LDF: Library Dependency Finder -> http://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 27 compatible libraries
Scanning dependencies...
Dependency Graph
|-- <SoftwareSerialM> 1.0.0
|-- <STM32ADC> 1.0
|-- <EEPROM>
|-- <USBComposite for STM32F1> 0.99
|-- <Wire> 1.0
|-- <Servo(STM32F1)> 1.1.2
Building in release mode
Compiling .pio\build\STM32F103RET6_creality\src\src\lcd\extui\lib\dgus\DGUSScreenHandler.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\lcd\extui\lib\dgus\origin\DGUSScreenHandler.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\module\settings.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\module\stepper.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\module\stepper\indirection.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\module\temperature.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\module\tool_change.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\sd\Sd2Card.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\sd\SdBaseFile.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\sd\SdFatUtil.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\sd\SdFile.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\sd\SdVolume.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\sd\cardreader.cpp.o
Archiving .pio\build\STM32F103RET6_creality\lib843\libWire.a
Archiving .pio\build\STM32F103RET6_creality\lib841\libServo.a
In file included from C:\Users\Micke\.platformio\packages\framework-arduinoststm32-maple\STM32F1\cores\maple/WString.h:29:0,
                 from C:\Users\Micke\.platformio\packages\framework-arduinoststm32-maple\STM32F1\cores\maple/wirish.h:47,
                 from C:\Users\Micke\.platformio\packages\framework-arduinoststm32-maple\STM32F1\cores\maple/Arduino.h:30,
                 from d:\marlin\marlin\src\hal\shared\marduino.h:36,
                 from d:\marlin\marlin\src\hal\stm32f1\hal.h:32,
                 from d:\marlin\marlin\src\hal\hal.h:30,
                 from d:\marlin\marlin\src\inc\marlinconfig.h:31,
                 from d:\marlin\marlin\src\lcd\extui\ui_api.h:45,
                 from Marlin\src\lcd\extui\lib\dgus\DGUSScreenHandler.h:30,
                 from Marlin\src\lcd\extui\lib\dgus\DGUSScreenHandler.cpp:27:
Marlin\src\lcd\extui\lib\dgus\DGUSScreenHandler.cpp: In static member function 'static void DGUSScreenHandler::HandlePIDAutotune(DGUS_VP_Variable&, void*)':
C:\Users\Micke\.platformio\packages\framework-arduinoststm32-maple\STM32F1\cores\maple/avr/pgmspace.h:29:59: error: expected primary-expression before ')' token
 #define sprintf_P(s, f, ...) sprintf((s), (f), __VA_ARGS__)
                                                           ^
Marlin\src\lcd\extui\lib\dgus\DGUSScreenHandler.cpp:564:13: note: in expansion of macro 'sprintf_P'
             sprintf_P(buf, PSTR("M303 E-1 C5 S70 U1"));
             ^~~~~~~~~
Marlin\src\lcd\extui\lib\dgus\origin\DGUSScreenHandler.cpp: In static member function 'static void DGUSScreenHandler::DGUSLCD_SD_FileSelected(DGUS_VP_Variable&, void*)':
Marlin\src\lcd\extui\lib\dgus\origin\DGUSScreenHandler.cpp:47:22: error: 'filelist' was not declared in this scope
     if (touched_nr > filelist.count()) return;
                      ^~~~~~~~
Marlin\src\lcd\extui\lib\dgus\origin\DGUSScreenHandler.cpp:47:22: note: suggested alternative: 'filepos_t'
     if (touched_nr > filelist.count()) return;
                      ^~~~~~~~
                      filepos_t
Marlin\src\lcd\extui\lib\dgus\origin\DGUSScreenHandler.cpp:48:10: error: 'filelist' was not declared in this scope
     if (!filelist.seek(touched_nr)) return;
          ^~~~~~~~
Marlin\src\lcd\extui\lib\dgus\origin\DGUSScreenHandler.cpp:48:10: note: suggested alternative: 'filepos_t'
     if (!filelist.seek(touched_nr)) return;
          ^~~~~~~~
          filepos_t
Marlin\src\lcd\extui\lib\dgus\origin\DGUSScreenHandler.cpp:50:9: error: 'filelist' was not declared in this scope
     if (filelist.isDir()) {
         ^~~~~~~~
Marlin\src\lcd\extui\lib\dgus\origin\DGUSScreenHandler.cpp:50:9: note: suggested alternative: 'filepos_t'
     if (filelist.isDir()) {
         ^~~~~~~~
         filepos_t
Marlin\src\lcd\extui\lib\dgus\origin\DGUSScreenHandler.cpp:65:87: error: 'filelist' was not declared in this scope
     HandleUserConfirmationPopUp(VP_SD_FileSelectConfirm, nullptr, PSTR("Print file"), filelist.filename(), PSTR("from SD Card?"), true, true, false, true);
                                                                                       ^~~~~~~~
Marlin\src\lcd\extui\lib\dgus\origin\DGUSScreenHandler.cpp:65:87: note: suggested alternative: 'filepos_t'
     HandleUserConfirmationPopUp(VP_SD_FileSelectConfirm, nullptr, PSTR("Print file"), filelist.filename(), PSTR("from SD Card?"), true, true, false, true);
                                                                                       ^~~~~~~~
                                                                                       filepos_t
Marlin\src\lcd\extui\lib\dgus\origin\DGUSScreenHandler.cpp: In static member function 'static void DGUSScreenHandler::DGUSLCD_SD_StartPrint(DGUS_VP_Variable&, void*)':
Marlin\src\lcd\extui\lib\dgus\origin\DGUSScreenHandler.cpp:69:10: error: 'filelist' was not declared in this scope
     if (!filelist.seek(file_to_print)) return;
          ^~~~~~~~
Marlin\src\lcd\extui\lib\dgus\origin\DGUSScreenHandler.cpp:69:10: note: suggested alternative: 'filepos_t'
     if (!filelist.seek(file_to_print)) return;
          ^~~~~~~~
compilation terminated due to -fmax-errors=5.
*** [.pio\build\STM32F103RET6_creality\src\src\lcd\extui\lib\dgus\DGUSScreenHandler.cpp.o] Error 1
*** [.pio\build\STM32F103RET6_creality\src\src\lcd\extui\lib\dgus\origin\DGUSScreenHandler.cpp.o] Error 1
================================================================================ [FAILED] Took 6.16 seconds ================================================================================

Environment             Status    Duration
----------------------  --------  ------------
STM32F103RET6_creality  FAILED    00:00:06.164
========================================================================== 1 failed, 0 succeeded in 00:00:06.164 ========================================================================== 
PS D:\Marlin> echo "done" >C:\Users\Micke\AppData\Local\Temp\ipc
PS D:\Marlin>

### Steps to Reproduce

1. Unzipped
2. Inserted Ender 6 (Creality) config files (Configuration_adv.h, Configuration.h). 
3. Used Visual Studio Code with PlatformIO and Auto Build Marlin.
4. Build it thru  Auto Build Marlin.
![marlin_page](https://user-images.githubusercontent.com/78612898/116523376-75ef0b00-a8d6-11eb-8340-4644f2378734.png)

### Version of Marlin Firmware

Marlin bugfix-2.0.x.

### Printer model

Creality Ender 6

### Electronics

Stock board

### Your Slicer

Cura

### Host Software

OctoPrint

### Additional information & file uploads

[Configurations.zip](https://github.com/MarlinFirmware/Marlin/files/6397287/Configurations.zip)

**Comment by ellensp** [comment] 2021-04-29 08:47
Duplicate of https://github.com/MarlinFirmware/Marlin/issues/21274

**Closed as completed by ellensp** 2021-04-29 08:47 UTC
