### ISSUE TITLE
REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER reverse encoder rotation 

### ISSUE THREAD

**Issue by lcfm1** [MarlinFirmware/Marlin#1840] opened 2015-04-07 03:53 UTC
Switching on the menu goes down by rotation of the wheel to the left

**Comment by TechMasterJoe** [comment] 2015-04-07 07:06
ultralcd.cpp
switch + to - and - to +
look for this at bottom

```
//manage encoder rotation
  uint8_t enc=0;
  if (buttons & EN_A) enc |= B01;
  if (buttons & EN_B) enc |= B10;
  if (enc != lastEncoderBits) {
    switch(enc) {
      case encrot0:
        if (lastEncoderBits==encrot3) encoderDiff++; // change to encoderDiff--
        else if (lastEncoderBits==encrot1) encoderDiff--; // change to encoderDiff++
        break;
      case encrot1:
        if (lastEncoderBits==encrot0) encoderDiff++; // change to encoderDiff--
        else if (lastEncoderBits==encrot2) encoderDiff--;// change to encoderDiff++
        break;
      case encrot2:
        if (lastEncoderBits==encrot1) encoderDiff++; // change to encoderDiff--
        else if (lastEncoderBits==encrot3) encoderDiff--; // change to encoderDiff++
        break;
      case encrot3:
        if (lastEncoderBits==encrot2) encoderDiff++; // change to encoderDiff--
        else if (lastEncoderBits==encrot0) encoderDiff--;// change to encoderDiff++
        break;
    }
```

**Comment by boelle** [comment] 2015-04-07 13:00
closing this one as its not a bug.... but agreed it should default be the other way round... a matter of taste maybe

**Closed as completed by boelle** 2015-04-07 13:00 UTC

**Comment by thinkyhead** [comment] 2015-04-08 01:54
The solution proposed by @TechMasterJoe will unfortunately cause edited values to go down when rotating the knob clockwise, probably not what you want. A more proper solution has been discussed, and will be implemented at some point soon.

**Comment by lcfm1** [comment] 2015-04-08 03:50
@thinkyhead, it will need to open?
