### ISSUE TITLE
Unify pin mappings

### ISSUE THREAD

**Issue by thinkyhead** [MarlinFirmware/Marlin#4410] opened 2016-07-25 20:01 UTC
One HAL to rule them all?

Assigning myself to manage the process of getting rid of the `Sd2PinMap.h` file dependencies. This is a topic to collect information to make that process go more smoothly.
- Use the `fastio.h` pin mappings where possible in the Sd2 code.
- Take a look at https://github.com/mmarchetti/DirectIO as another alternative

References: #2970

**Comment by Roxy-3D** [comment] 2016-07-25 20:42
> Use the fastio.h pin mappings where possible in the Sd2 code.

I know this is going to be a stupid question, but looking at the Sd2PinMap.h file, every value in there is known at compile time.   Why isn't it possible to move entirely over to the fastio.h pin mappings?  Why did you qualify the statement with a 'where possible' ?    There must be something I don't understand.

> Take a look at https://github.com/mmarchetti/DirectIO as another alternative

I like the DirectIO alternative!!!

**Comment by thinkyhead** [comment] 2016-07-25 22:17
> Why isn't it possible to move entirely over to the fastio.h pin mappings? 

It comes down to the three SPI pins, apparently. I'm not sure what values end up where, whether the SPI pins specified in the `pins_BOARD.h` files need to override the SPI pins set in the Sd2 files, or the other way around, and so forth. But it's only that I haven't dived into it. I hope it will all make complete sense to me soon.

**Comment by Roxy-3D** [comment] 2016-07-25 22:27
OK...  That makes some sense.   I might have just gone through a similar thing because there are many dependencies in the different .cpp files because header files get included in a different order depending on which ones get included first.

I wonder if we should consider having Marlin.h include all of the important .h files and always have the .cpp files include Marlin.h first.  (It knows what to do because it always includes Configuration.h first.)   That might help to get things more deterministic in this kind of situation.   I was pulling my hair out because of header file "out of scope" errors.

**Comment by thinkyhead** [comment] 2016-07-25 22:36
> should consider having Marlin.h include all of the important .h files

That can be fine, but tends to mask errors where a header forgot to include its own dependencies. In general, each `.cpp` / `.h` file should strive to include only the headers it needs, and `.h` files should be especially stingy about what they include. There are some good coding guidelines on the ordering of `#include` directives. (Basically, use them in an order that won't mask a forgotten `#include` elsewhere.)

**Comment by Roxy-3D** [comment] 2016-07-25 22:37
> (Basically, use them in an order that won't mask a forgotten #include elsewhere.)

Can you give me an example of how and where this can happen?   What you said doesn't make any sense to me.

**Comment by Roxy-3D** [comment] 2016-07-25 22:42
> each file should strive to include only the headers it needs, and .h files should be especially stingy about what they include.

And right now, the root cause of the problem I was fighting was the header files are including each other (and ultimately themselves) recursively.   That is why we have each header file do a first line of 

```
#ifndef MARLIN_H
#define MARLIN_H
```

That is done explicitly because none of the header files are following your 'best practices'.   So while doing:

> we should consider having Marlin.h include all of the important .h files and always have the .cpp files include Marlin.h first. 

is not perfectly clean, it gets us miles ahead of the recursive and non-deterministic behavior we have today.   It might be an easy and good first step to cleaning the header files up?    

I guess alternatively...  We could consider making our header files not include any other header files, and it would be clear which header files a given .cpp file needed to include.  If we did this, it might be wise to manually add the new #include's in the exact same order so every file behaves the same.

**Comment by AnHardt** [comment] 2016-07-25 23:12
DirectIO could be an alternative if it would support AT90USB-processors an or Teensy - but i can't find that.
Removing `Sd2PinMap.h` should be **relative** simple because the functions defined there are only used at a hand full places. 
All in all the definition of the SPI pins is a mess - if you try to follow the logic. Hardware-SPI, Software_SPI, used for display, SD-card, MAX-sensors, different SPI-ports wehter the SD-card is connected on board or at the display make it difficult to get an overview. Oh and forgot the digipots, they are using Arduinos SPI.h

Only for the hardwar SPI this is obvious because the processors we use have only one hardware SPI-port. So finding out MISO, MOSI, SCLK is the easy task.

The variety of names for the chip select (Slave Select - SS) overwhelmed me.

Digging a bit deeper into software-SPI it becomes obvious we have at least two implementations. One in u8glib and one in SD2lib. 

The ideal faster than Arduino-IO library would be:
- fast
- supporting all processors/boards
- pin number could be a variable - not only a constant (even if slower than)
- supporting analogeWrite

but up to now i could not find that all together.

**EDITED**

**Comment by thinkyhead** [comment] 2016-07-25 23:19
> Can you give me an example of how and where this can happen?

Let's say `myclass.h` forgot to include a dependency like `math.h` that the header needs for an inline function. Then in `myclass.cpp` (which also needs to use `math.h`) you have:

``` cpp
#include "math.h"
#include "myclass.h"
```

This masks the fact that `myclass.h` forgot to include `math.h`. So the correct way to do include ordering in the `.cpp` file is:

``` cpp
#include "myclass.h"
#include "math.h"
```

Now we get a compile error, because `myclass.h` forgot to include `math.h` —  so we know to fix that.

**Comment by thinkyhead** [comment] 2016-07-25 23:23
> ``` cpp
> #ifndef MARLIN_H
> #define MARLIN_H
> . . .
> #endif // MARLIN_H
> ```

These bracketing directives are good and normal practice in C and C++. Some compilers also provide the alternative:

``` cpp
#pragma once
```

In Objective-C you get a one-time include with:

``` mm
@import "myclass.h"
```

**Comment by thinkyhead** [comment] 2016-07-25 23:27
> consider making our header files not include any other header files

Header files must include the other headers that they need for the code, defines, and data types that they themselves reference. They should not include header files that are _only_ needed by their companion `.cpp` files.

**Comment by Roxy-3D** [comment] 2016-07-25 23:29
> This masks the fact that myclass.h forgot to include math.h. So the correct way to do include ordering is:

OK.  I think I ran into this issue.   I would finally get an 'out of scope' issue cleaned up, and magically a bunch of new errors happened.

> DirectIO could be an alternative if it would support AT90USB-processors an or Teensy 

The file here seems to be where the different processor types get defined: https://github.com/mmarchetti/DirectIO/blob/master/DirectIO/ports.h   Could we just generate the pin mappings for AT90USB and Teensy to resolve this issue?   

> Header files should include the other headers that they need for the code and data types that they reference. They should not include header files that are only needed by their companion .cpp files.

OK!  That helps a lot!   That makes good, solid sense.

**Comment by AnHardt** [comment] 2016-07-25 23:52
> Could we just generate the pin mappings for AT90USB and Teensy to resolve this issue?

Off course we can. But can we test that in as reasonable time? We had to revisit every time critical section in Marlin and check if we are too slow - or too fast then. I don't even know if i know about all time critical sections.

**Comment by thinkyhead** [comment] 2016-07-26 19:05
@Roxy-3D I guess we can do this now and clean up the configs: https://github.com/thinkyhead/Marlin/blob/e7302bcfa2d45f8e7330f68731ad05007e2b4999/Marlin/MarlinConfig.h

**Comment by Roxy-3D** [comment] 2016-07-26 19:55
> @Roxy-3D I guess we can do this now and clean up the configs:

I presume we should do the same thing to devel-ubl also to keep them as closely synchronized as possible?   I just ran into some more header file problems today because of different options being turned off.     Also, I wonder if devel-ubl-base should be visible?  Is there any reason right now for somebody to need that?   I'm wondering if we should remove it?

**Comment by thinkyhead** [comment] 2016-07-26 20:05
> do the same thing to devel-ubl

Well, `devel-ubl` is still 3 weeks behind `RCBugFix` and needs to be brought up-to-date with all the other changes first. Then this one would come along with those.

> header file problems

If you post the errors you're getting, I can make sure they are addressed in the current codebase also.

**Comment by Roxy-3D** [comment] 2016-07-26 20:15
OK...  I'll sit tight on making #include changes to devel-ubl.    The #include errors I dealt with today had to do with G26_Mesh_Validation_Tool.cpp    So, those issues are not a problem with the main code base.  

(but it was the nested, recursive includes that caused me to not see the problem until today when somebody tried to compile without LCD Panel support.)

**Comment by thinkyhead** [comment] 2016-07-26 20:18
Are the contents of all your `.h` files bracketed by `#ifndef`…`#endif`?

**Comment by Roxy-3D** [comment] 2016-07-26 20:23
Yes!    G29_Unified_Bed_Leveling.cpp:

```
#ifndef G29_UNIFIED_BED_LEVELING_H
#define G29_UNIFIED_BED_LEVELING_H
#include "Marlin.h"
#if ENABLED(UNIFIED_BED_LEVELING_FEATURE)
```

and the bed_leveling.h:

```
#ifndef UNIFIED_BED_LEVELING_H
#define UNIFIED_BED_LEVELING_H
#include "Marlin.h"
#include "math.h"
#if ENABLED(UNIFIED_BED_LEVELING_FEATURE)
```

**Comment by thinkyhead** [comment] 2016-07-26 20:25
So, what kind of error messages did you get?

**Comment by Roxy-3D** [comment] 2016-07-26 20:27
G26 was missing the definition for stepper motors, thermal stuff, and the planner object.     I added explicit #includes:

```
 #include "Marlin.h"
  #include "Configuration.h"
 +#include "planner.h"
 +#include "stepper.h"
 +#include "temperature.h"
  #include "G29_Unified_Bed_Leveling.h"
```

With an LCD Panel and a Z-Probe defined, Marlin.h normally gets those pulled in.  But with some option combinations, that doesn't happen.   That is why it was blowing up and needed the extra #include's.

**Comment by thinkyhead** [comment] 2016-07-26 21:04
If your `.cpp` file relies on something defined in "stepper.h" then it should have the include for it. Don't rely on "stepper.h" being included by something else you're including.

**Closed as completed** 2017-10-31 04:46 UTC
Labels: PR: Improvement, Needs: Work, T: Development
