### ISSUE TITLE
[BUG] 2.0.9.3. M32 Still nog working. Please remove from Marling Gcode list

### ISSUE THREAD

**Issue by roel8032** [MarlinFirmware/Marlin#23413] opened 2022-01-01 12:17 UTC
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

M32 not working in this and previous versions. Worked some version back.

### Bug Timeline

?

### Expected behavior

Call a subprogram. Not jumping into that file.

### Actual behavior

It stops.

### Version of Marlin Firmware

2.0.9.3

### Printer model

Anet A6, Infitary M508.

### Electronics

Stock board

### Bed Leveling

ABL 3-point

### Your Slicer

Cura

### Host Software

SD Card (headless)

**Comment by thisiskeithb** [comment] 2022-01-01 12:45
Duplicate of https://github.com/MarlinFirmware/Marlin/issues/22410

**Closed as completed by thisiskeithb** 2022-01-01 12:45 UTC
