### ISSUE TITLE
[bugfix-2.0.x] Y position disappeared from LCD

### ISSUE THREAD

**Issue by swilkens** [MarlinFirmware/Marlin#12215] opened 2018-10-25 19:44 UTC
### Description

The Y position is no longer displayed on screen, neither is a blinking "?" before homing is done. 

 - version is bugfix-2.0.x ( at e8031b115249385700006146f273bcd220394ba9)

 - Issue not present on 1.1.9

 - System is using `CR10_STOCKDISPLAY` as the interface, though I doubt it's specific to this display.

Currently doing a bisect to find the offending commit

[configuration_y_pos_missing.zip](https://github.com/MarlinFirmware/Marlin/files/2516459/configuration_y_pos_missing.zip)

**Comment by thinkyhead** [comment] 2018-10-25 20:43
Duplicate of #12178

**Closed as completed by thinkyhead** 2018-10-25 20:43 UTC
