### ISSUE TITLE
[BUG] Z position wrong when tool changes after G29

### ISSUE THREAD

**Issue by SwiftNick** [MarlinFirmware/Marlin#15641] opened 2019-10-23 07:08 UTC
After homing and bed levelling, hot end is 5mm above bed and display shows z = 5
When tool selected, Z position on screen changes to 1 but the z axis does not move.
Print starts 4mm above the bed.

The same issue occurs using Marlin-bugfix-2.0.x.
Older Marlin-bugfix-1.1.x works just fine.

**Configuration:**
  MOTHERBOARD:  BOARD_K8400
  EXTRUDERS:  2
  Z_PROBE_SERVO_NR:  0  (using a BLTouch probe)
  AUTO_BED_LEVELING_LINEAR

**Steps to reproduce**
Issue the following commands via terminal.
G28     
G29
T0

I you don't do the bed levelling the Z position is fine and does not change during a tool change.

**Comment by Evgeny-SPB** [comment] 2019-10-23 11:23
Hello! Your problem seems very similar to the one described in https://github.com/MarlinFirmware/Marlin/issues/15610
You can try to reproduce steps 
G28 
G29 
M114 D
The last command with D modifier gives coordinates before applying rotation with AUTO_BED_LEVELING_LINEAR and after.  
(Remember that for M114D to work you need to #define M114_DETAIL in Configuration_adv.h)

You have dual extruded setup. I have dual Z setup. In my case the problem was with planar bed leveling (AUTO_BED_LEVELING_LINEAR, AUTO_BED_LEVELING_3POINT), which both use the same function for rotation.

You could also try to use other methods (maybe unified bed leveling), as I understand, they use other function for applying bed levelling.

**Comment by SwiftNick** [comment] 2019-10-23 19:14
Your suggested fix in `vector_3::apply_rotation` seems to have resolved this one.
Nick

**Comment by Evgeny-SPB** [comment] 2019-10-23 19:44
I’v spent about 20 hours on this bug. I’m glad that my solution helped you 👍

**Comment by boelle** [comment] 2019-10-24 12:05
so this one is allready solved?

**Comment by Evgeny-SPB** [comment] 2019-10-24 16:46
@boelle I think issue is solved with PR https://github.com/MarlinFirmware/Marlin/pull/15636, which is already merged.

**Comment by boelle** [comment] 2019-10-24 17:25
oki, will close then

we can always reopen

**Closed as completed by boelle** 2019-10-24 17:25 UTC
