### ISSUE TITLE
Independent axis movements

### ISSUE THREAD

**Issue by f-barbato** [MarlinFirmware/Marlin#26431] opened 2023-11-16 11:25 UTC
### Describe the feature you want

I need that each axis can be run independently from others like:
- G0 X100 //move the x-axis
- G0 Y100 //move the y-axis while x-axis is running
and so on, but i haven't found any firmware configuration that can perform this.

**Comment by ellensp** [comment] 2023-11-16 11:49
This is not possible.   

Marlin is designed that moves involving multiple axis are synchronized, Otherwise move gcode is processed sequentially 
These are design requirements.

Otherwise the moves are rather non deterministic. 

Eg your example.
The X would start moving first, then the Y moves will start at a random X position. X move would eventually finish and Y would still be moving

You would get a move like the following piece of primitive ascii art

```
¯\
  |

```

This is not a feature it is a complete change in design philosophy for something other than a 3d printer.

**Comment by thisiskeithb** [comment] 2023-11-16 13:25
Duplicate of https://github.com/MarlinFirmware/Marlin/issues/24474

**Closed as completed by thisiskeithb** 2023-11-16 13:25 UTC
Labels: T: Feature Request
