### ISSUE TITLE
Layer height changing during print - Dual extruder

### ISSUE THREAD

**Issue by evertonramires** [MarlinFirmware/Marlin#11138] opened 2018-06-28 02:44 UTC
### Description

I am facing a sudden layer height change during a print, it starts printing normally then after some layers, every layer seems to be double the define in slicer.

### Steps to Reproduce

-Dual extruder head (E3DV6 Bowden, only one carriage)
-Using Cura 3.3.1
-Marlin bugfix 1.1
-Using Lin Advance
-Using UBL bed leveling
-CoreXY kinematics

-Extruders are not grinding neither missing steps.
-Only happens when using both extruders, machine works pretty fine when only one of them is used during the entire print.

![5a4066c5-6efe-45b2-9ab6-948b568383ca](https://user-images.githubusercontent.com/11058507/42010148-b09368ea-7a63-11e8-819b-54687ab32e4d.jpg)

**Comment by thinkyhead** [comment] 2018-06-28 09:37
This is a duplicate of an earlier issue. We've been trying to figure out the cause for some time now, but since none of us have the hardware to test on, it has not been solved yet.

To help narrow down the issue, try disabling the sub-options of UBL such as Z Fade (and so on) to see if there is anything that eliminates (or exacerbates) the bad behavior. Also try other forms of bed leveling to see if they exhibit the same problem.

**Comment by margaale** [comment] 2018-06-28 10:56
I've been experiencing the same issue only with higher distance between layers and using one extruder even though I have an dual extruder setup. If you deactivate UBL all goes back to normal.

**Comment by evertonramires** [comment] 2018-06-28 17:45
Ok. I had some extra time to look for other reports: #7469 #7469 #10130 #10088 
All of them seems to be related with bed leveling correction. specially UBL. Some says forcing set a Z offset between extruders like M218 T1 Z-0.01 would be a workaround for the problem.
@Roxy-3D also says if I lift Extruder 0, change tools to Extruder 1 and them put it back down, it would also kind of solve the issue for now. I think this way is easier since I can set a Z-hop when retracting and force retracting at every tool change using my slicer (Cura).

I will try disabling z fade as well as the other options and then report here if at least one of them works.

Thanks guys!

**Comment by thinkyhead** [comment] 2018-06-30 23:43
The problem is probably related to the way that UBL handles updates to the current position internally. As I understand it, you have to issue some kind of move after any change to the position so that UBL gets the new position copied into its internal shadow registers. Z hop (as part of firmware-based retraction) is one of those operations that might confuse UBL because it does some tweaking to the current position to hide the hop move from the planner. Hopefully these side-effects will get fixed as we integrate UBL more completely with the rest of Marlin.

**Comment by boelle** [comment] 2019-02-20 14:44
@GypsyRobot this is still an issue right?

**Comment by evertonramires** [comment] 2019-02-20 15:23
> @GypsyRobot this is still an issue right?

Unless this was addressed in version 1.1.9 (didn't have the time to test yet), it is still an issue.

**Comment by boelle** [comment] 2019-02-20 15:26
@margaale do you still see the problem?

**Comment by boelle** [comment] 2019-03-06 12:08
@thinkyhead i think we can close this one

**Comment by margaale** [comment] 2019-03-06 12:10
Sorry, after this i disabled UBL and never used it again. So i can't give you any feedback.

**Comment by boelle** [comment] 2019-03-06 12:15
@margaale we need @GypsyRobot to reply since he created this issue

**Comment by margaale** [comment] 2019-03-06 12:17
Sure, no problem, but i only answered your question...

**Closed as completed** 2019-05-16 22:31 UTC
Labels: Bug: Confirmed !, Needs: More Data, Needs: Patch, F: U.B.L.
