### ISSUE TITLE
[FR] Controller Fan with individualized stepper control

### ISSUE THREAD

**Issue by Protean-Man** [MarlinFirmware/Marlin#18950] opened 2020-08-07 19:20 UTC
The USE_CONTROLLER_FAN function could use addressable stepper driver access.

**Reason:** When implementing fans for stepper motors the simplest way would be to tie them to this function. The issue is that if I have an extruder motor fan (not for the heater but for the motor) on a multi-extruder machine, all of the fans turn on with this function. My goal is to have a fan on every motor - X, Y, Z, E1, E2, E3, E4, etc. Being able to assign a fan pin for each motor would be helpful. 

_For anyone wanting to do this you can attach a simple mosfet switch so that you can drive multiple fans with a chosen pin on your board._ 

**Implementation:** using the existing USE_CONTROLLER_FAN function there would be added parameters with addressable pins. They would be attached to the existing stepper definitions in Configuration.h
The USE_CONTROLLER_FAN would still function as it currently does but would need to add exemptions for defined individual stepper fans - this way you would have a controller fan still turn on when any stepper is active while a separate pin is only activated when a specific stepper is active. 

//#define X_STEPPER_FAN_PIN -1
//#define X_STEPPER_FAN_SPEED 255
//#define X2_STEPPER_FAN_PIN -1
//#define X2_STEPPER_FAN_SPEED 255
//#define Y_STEPPER_FAN_PIN -1
//#define Y_STEPPER_FAN_SPEED 255
//#define Y2_STEPPER_FAN_PIN -1
//#define Y2_STEPPER_FAN_SPEED 255
//#define Z_STEPPER_FAN_PIN -1
//#define Z_STEPPER_FAN_SPEED 255
//#define Z2_STEPPER_FAN_PIN -1
//#define Z2_STEPPER_FAN_SPEED 255
//#define Z3_STEPPER_FAN_PIN -1
//#define Z3_STEPPER_FAN_SPEED 255
//#define Z4_STEPPER_FAN_PIN -1
//#define Z4_STEPPER_FAN_SPEED 255
//#define E_STEPPER_FAN_PIN -1
//#define E_STEPPER_FAN_SPEED 255
//#define E1_STEPPER_FAN_PIN -1
//#define E1_STEPPER_FAN_SPEED 255
//#define E2_STEPPER_FAN_PIN -1
//#define E2_STEPPER_FAN_SPEED 255
//#define E3_STEPPER_FAN_PIN -1
//#define E3_STEPPER_FAN_SPEED 255
//#define E4_STEPPER_FAN_PIN -1
//#define E4_STEPPER_FAN_SPEED 255
//#define E5_STEPPER_FAN_PIN -1
//#define E5_STEPPER_FAN_SPEED 255
//#define E6_STEPPER_FAN_PIN -1
//#define E6_STEPPER_FAN_SPEED 255
//etc.

Thanks!

**Comment by thisiskeithb** [comment] 2021-11-28 08:21
Duplicate of #11253

**Closed as completed by thisiskeithb** 2021-11-28 08:21 UTC
Labels: T: Feature Request
