### ISSUE TITLE
Artifacts instead of imagesMarlin 2.0 on board BOARD_RURAMPS4D_13 with REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER

### ISSUE THREAD

**Issue by ANMay-ru** [MarlinFirmware/Marlin#14108] opened 2019-05-24 10:06 UTC
file configuration.h
#define MOTHERBOARD BOARD_RURAMPS4D_13
#define REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER
#define LCD_LANGUAGE ru 
but also with en

The build on April 15 worked fine.

Compiler Arduino 1.8.9, u8glib 1.19.1
![IMG_20190524_002642](https://user-images.githubusercontent.com/49490265/58320401-bbcb0b00-7e45-11e9-96c8-dbd64bbd9a85.jpg)

**Comment by gloomyandy** [comment] 2019-05-24 12:05
Possibly a duplicate of https://github.com/MarlinFirmware/Marlin/issues/14067

Try the fix described in that issue.

**Closed as completed** 2019-05-24 14:24 UTC

**Comment by gloomyandy** [comment] 2019-05-24 14:49
@ANMay-ru Can you confirm that the fix in that thread resolved your problem?

**Comment by ANMay-ru** [comment] 2019-05-29 08:35
By issue #14067 the problem has been solved. Thank!
