### ISSUE TITLE
Manual levelling gets stuck at 2nd probe point

### ISSUE THREAD

**Issue by paulr4** [MarlinFirmware/Marlin#6595] opened 2017-05-05 14:45 UTC
I'm running the latest version (1.1.x) on a RAMPS 1.4 single extruder setup.

I'm trying the manual bed levelling feature via the LCD, and have the following #defines enabled:

MESH_BED_LEVELING
LCD_BED_LEVELING
PROBE_MANUALLY
EEPROM_SETTINGS

I follow the instructions, but after moving to the second calibration point, the LCD continues to display 'Moving...', and gets stuck. Clicking the control knob produces a beep, but nothing happens.

**Comment by james94jeans2** [comment] 2017-05-05 15:28
Disable PROBE_MANUALLY, then it will work. Had the same issue.

**Comment by paulr4** [comment] 2017-05-05 16:57
Thanks I'll try that.

**Comment by inahas** [comment] 2017-05-08 04:48
Disabling PROBE_MANUALLY allows the procedure to continue, but no mesh data is saved or used. Doing G29 S0 says : 
Send: G29 S0
Recv: Mesh bed leveling has no data.
Recv: X:0.00 Y:0.00 Z:0.00 E:0.00 Count X:0 Y:0 Z:0

Can anyone tell me what is the latest build that had this feature working?

**Comment by kylerwinters** [comment] 2017-05-08 07:10
Can you post your config?

**Comment by paulr4** [comment] 2017-05-08 09:24
Who me?

[config.txt](https://github.com/MarlinFirmware/Marlin/files/1008142/config.txt)

**Comment by inahas** [comment] 2017-05-08 17:11
This is mine:

[Configuration.txt](https://github.com/MarlinFirmware/Marlin/files/984279/Configuration.txt)

**Comment by Fixx** [comment] 2017-05-08 20:14
I can confirm Mesh Data is not saved to EEPROM, but works for that session.

**Comment by inahas** [comment] 2017-05-09 02:13
With PROBE_MANUALLY commented out the procedure completes, but no bed leveling is applied. I checked multiple times, no z-axis movement whatsoever.

With PROBE_MANUALLY enabled, the procedure freezes after the hotend moves to the second point. 

I also tried to manually level using G29 S2 but that didn't work either.

I am using the nightly build.

**Comment by SCiunczyk** [comment] 2017-05-26 17:46
HI,

I have exactly this same symptoms as @paulr4. Version 1.1.0 works fine, but 1.1.1 and yesterday Marlin-bugfix-1.1.x and gets stuck.... displaying on LCD Moving... 

What is interesting to me, my LCD interface is in Polish, but this message "Moving... " is in English. Previous version 1.1.0 was in Polish. Maybe this information can help.

**Comment by geeksville** [comment] 2017-06-04 03:23
Anyone know of a work around without disabling PROBE_MANUALLY.  Because I'd like to keep using that ;-)

**Comment by Roxy-3D** [comment] 2017-06-04 04:15
I think we should get the Manual Probe working again for Mesh Bed Leveling!   Does anybody know where on the time line it quit working?   Because that information would help a lot in getting it fixed.

But are you aware the Mesh Bed Leveling is going way soon (5 or 6 months???).    It is a very good technology (in fact...  It ***IS*** a break through technology!), but its functionality has been absorbed into both the Bi-Linear and UBL bed leveling.

**Comment by geeksville** [comment] 2017-06-04 04:16
Actually: I poked around a bit (though I know virtually nothing about marlin).  Here's some extra info:

Marlin 1.1.1 shows this problem (where I noticed it)

However, the current Marlin-1.1.x branch does not show this problem, unfortunately that branch does not compile if you enable PROBE_MANUALLY.  it fails with the following compiler error for lcd_wait_for_move being not defined in the scope it is used.  

So I fixed this as follows: 
https://github.com/geeksville/Marlin/commit/ed9cb78fde6a197cfc420730ebd5ac7d865b3477

I'd happily send in a PR if you want it, but since the problem isn't fully fixed I'm waiting.  Should I send this in so at least the code can compile again?

Once this fix is in on master it will happily go through the 9 pts and let the user adjust the probe position at each point.  However it then hangs after it prints "Leveling Done!" 

Sad panda.  I'm looking into this hang now, but it is a long time since I futzed with avrs ;-).

**Comment by Roxy-3D** [comment] 2017-06-04 04:17
> I'd happily send in a PR if you want it, but since the problem isn't fully fixed I'm waiting. Should I send this in so at least the code can compile again?

Yes!  Please!   Even if it is a 1/2 fix....   I would appreciate seeing it.  If you want to keep using the original Mesh Bed Leveling, I will try to help you.   But I'm 101% focused on UBL Bed Leveling.  So...  it depends on how quick of response you want which way you should go.  (And...  UBL _**Does**_ work!  It may be more than you need, but it **_Does_** work!)

PS.  UBL is built on a Mesh Bed Leveling foundation.  Just to honor @epatel I want to keep the original Mesh Bed Leveling going for a long time.  The Mesh Bed Leveling is very small in size and does the job very well.   Especially since we still want to fit into 128 KB parts, it is hard to replace the original Mesh Bed Leveling!!!!

**Comment by geeksville** [comment] 2017-06-04 04:38
Sounds good.  Though when I tried turning on UBL it didn't seem to work with PROBE_MANUALLY yet.

I've learned a bit more: MESH_LEVELING crashes as I described above, however, AUTO_BED_LEVELING_BILINEAR seems to work okay with PROBE_MANUALLY (yay!).  So I'm going to change over to that (good idea?) to get my printer working with Marlin 1.1.1.

I'll also send in a PR to fix at least compilation and gathering the 9 datapoints of MESH_LEVELING+PROBE_MANUALLY.

**Comment by Roxy-3D** [comment] 2017-06-04 04:44
> AUTO_BED_LEVELING_BILINEAR seems to work okay with PROBE_MANUALLY (yay!). So I'm going to change over to that (good idea?) to get my printer working with Marlin 1.1.1.

Yes!   Bi-Linear does everything the original Mesh Leveling did.

> Though when I tried turning on UBL it didn't seem to work with PROBE_MANUALLY yet.

UBL does support Manual Probing.  It is built into UBL as a G29 P2 flavor command.   There are reports from reliable sources that you don't have to enable a real Z-Probe.  But I have never done or tested that.    Like I say...  It is reported to work.    

And in fact....  You can do a G29 P0 to create a mesh of all 0.0000's and jump straight to the G26 Mesh validation pattern.   So...   If you can get that far...   You probably don't even need to configure a Manual Probe.     

The choice is yours how you want to proceed.   I'll try to help you regardless of which path you decide.   But.... You know where I'm focused.

**Closed as completed** 2018-02-07 09:49 UTC
