### ISSUE TITLE
[BUG] (short description)

### ISSUE THREAD

**Issue by Future124** [MarlinFirmware/Marlin#19289] opened 2020-09-07 08:58 UTC
### Bug Description

after homing x and y axis move in opposite direction

### My Configurations

ill add zip file shortly 
### Steps to Reproduce

1.home axis
2.home axis again
or
3. auto level bed

**Expected behavior:** [What you expect to happen]
second homing should home| (move from current position 150,150 to start homing and move x and y to 0,0 then to the center of the bed as i have z safe homing enabled). auto bed level x and y should move from 150,150  positiion towards 0,0 to run the auto bed leveling
**Actual behavior:** [What actually happens]
upon trying to home a second time or auto bed leveling after homing  xy moves away from home position (0,0) and crashes
#### Additional Information

* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.

**Comment by thisiskeithb** [comment] 2020-09-07 09:05
Duplicate of https://github.com/MarlinFirmware/Marlin/issues/19286

**Closed as completed by thisiskeithb** 2020-09-07 09:05 UTC
