### ISSUE TITLE
MKS SBASE - Lost steps in Y and random BLTouch deployment

### ISSUE THREAD

**Issue by gauix4** [MarlinFirmware/Marlin#12239] opened 2018-10-27 15:03 UTC
Hello
brand new still this problem Marlin no compilation problem stepper well settled no problem after a while there is offset in Y...
100% sure it's a Marlin problem with other map everything works fine
1 - the BLtouch tends to deploy itself
2- the Y always shifts after a while

I use atom as a compiler

**Comment by gauix4** [comment] 2018-10-27 15:05
we see that there is a problem because the temperature varies by itself
<img width="591" alt="capture d ecran 2018-10-27 a 16 37 07" src="https://user-images.githubusercontent.com/23041016/47605715-668f5e00-da0a-11e8-8974-ee370316d14e.png">

**Comment by gauix4** [comment] 2018-10-27 15:21
<img width="1680" alt="capture d ecran 2018-10-27 a 17 20 45" src="https://user-images.githubusercontent.com/23041016/47605900-c5ee6d80-da0c-11e8-8ea3-a6672aa3abde.png">

**Comment by p3p** [comment] 2018-10-27 15:29
If you run `pio update` in the atom terminal what version of `framework-arduino-lpc176x` are you running, 

Always supply the information requested in the issue template, such as full configs. additional information about your hardware setup may also help us rather than just specifying that things that don't work.

**Comment by gauix4** [comment] 2018-10-27 15:31
<img width="1680" alt="capture d ecran 2018-10-27 a 17 29 24" src="https://user-images.githubusercontent.com/23041016/47605998-0e5a5b00-da0e-11e8-8cf3-17badd1dbd09.png">

**Comment by gauix4** [comment] 2018-10-27 15:32
<img width="757" alt="capture d ecran 2018-10-27 a 17 31 52" src="https://user-images.githubusercontent.com/23041016/47606007-3fd32680-da0e-11e8-9481-3aab4fb349f2.png">

**Comment by gauix4** [comment] 2018-10-27 15:35
@p3p 
that's what you want I have a little trouble with atom I did not know

**Comment by gauix4** [comment] 2018-10-27 15:37
<img width="717" alt="capture d ecran 2018-10-27 a 17 37 39" src="https://user-images.githubusercontent.com/23041016/47606053-064eeb00-da0f-11e8-8576-e58b79394fb7.png">

**Comment by p3p** [comment] 2018-10-27 15:39
did `framework-arduino-lpc176x` update when you ran `pio update` or were you already on 0.0.5?

**Comment by gauix4** [comment] 2018-10-27 15:45
@p3p this one was not showing at all this is the first screen shot I made by sending the command

**Comment by gauix4** [comment] 2018-10-27 15:47
but I think that's it there were a lot of things that were not up to date that went on as 
the best way to know is that i re test ^^

**Comment by p3p** [comment] 2018-10-27 15:48
I know that's why I asked, it hadn't finished at the point you took the screenshot. If it did update it may have fixed your BLTouch issues as there was a known issue with it for a few days but if you are only trying this today it's unlikely platformio downloaded the old version.

Please supply your configuration files and hardware setup, including stepper drivers and temperature sensors.

**Comment by gauix4** [comment] 2018-10-27 15:57
@p3p Driver ES-D508 Y "closed-loop"
X TMC 2208 no serie connect

I am not at all a beginner configuration.h and well configure the probes also there is really that with this card that I have problems all the others have no problem the card is new I have changed two times to be sure but still the same problems so no external problem just the marlin or update problems as you showed me

I am totally new to atom I did not know at all I always worked on IDE-Arduino
so I do not understand yet libraries and atom updates

I'm french sorry for my english who is extremely bad sorry again and again

**Comment by gloomyandy** [comment] 2018-10-27 16:10
To save you both some time, here is a previous post about this problem (see the following posts for some followup):
https://github.com/MarlinFirmware/Marlin/issues/7076#issuecomment-431604801
@guanix it would still be very useful for you to post your configuration files.

**Comment by gauix4** [comment] 2018-10-27 16:12
[dossier sans titre.zip](https://github.com/MarlinFirmware/Marlin/files/2521978/dossier.sans.titre.zip)

**Comment by gauix4** [comment] 2018-10-27 16:14
@sombre I forgot to add the link ^^

**Comment by p3p** [comment] 2018-10-27 16:14
Your stepper driver is not in general use so we do not have a default configuration for it, you need to set the values in `configuration_adv.h` to match the datasheet.

Looking at http://www.leadshine.com/UploadFile/Down/ES-D508d_V1.2.pdf (best guess on my behalf at your driver) it appears your driver needs extra long pulses compared to the usual divers (2.5us minimum), so you will need to set `MINIMUM_STEPPER_PULSE` to an appropriate value, remember 2.5us is the minimum so 3 or even 4 should guarantee you driver picks it up within a margin for error. 

I assume whatever bus driver (logic level converter) you are using is suitable for the slew and frequency requirements.

**Comment by gauix4** [comment] 2018-10-27 16:16
@p3p I did as I told you I'm not a beginner all is good
let's see that I already did everything in configuration advance that I joined you above your comment ^^

**Comment by p3p** [comment] 2018-10-27 16:18
According to your config you did not, your setup for A4988 (the default drivers), that work down to a few 100 nano second pulse width.

**Comment by gauix4** [comment] 2018-10-27 16:22
@p3p normally everything is good

<img width="815" alt="capture d ecran 2018-10-27 a 18 21 07" src="https://user-images.githubusercontent.com/23041016/47606566-41541d00-da15-11e8-916a-c1332c922e98.png">

**Comment by p3p** [comment] 2018-10-27 16:24
sometimes hardware runs outside of the spec "most of the time" doesn't mean anything. `MINIMUM_STEPPER_PULSE` should be at least 3 possibly 4.

**Comment by gauix4** [comment] 2018-10-27 16:25
@p3p if I activate the bed auto leveling does not work anymore

**Comment by p3p** [comment] 2018-10-27 16:27
I can't help from "it doesn't work" describe the situation or post build log if its a build problem.

**Comment by gauix4** [comment] 2018-10-27 16:31
@p3p I stay with the update I tell you that in 20 minutes the time that everything starts on the road

**Comment by gauix4** [comment] 2018-10-27 17:02
@p3p nothing has changed always shift in Y always the bltouch that does anything

**Comment by gauix4** [comment] 2018-10-27 17:06
@p3p I feel that because I have large dimensions
put small dimensions everything works properly 300X300X300

**Comment by gauix4** [comment] 2018-10-27 17:14
https://youtu.be/dWgYPQUOQVc

**Comment by gauix4** [comment] 2018-10-27 17:29
@p3p a compilation problem nothing but still the same problems even with a delay add

**Comment by gloomyandy** [comment] 2018-10-27 17:34
@guanix Have you used that driver successfully with any other board and/or firmware? If so which? Also have you used the level shifter that you built successfully with anything?

**Comment by gauix4** [comment] 2018-10-27 17:54
@gloomyandy 
yes
marlin 2xx no good
marlin 1.xx ok
MKS Gens 1.4 ok
lerdge S ok
lerde X ok
mks robin ok

**Comment by gauix4** [comment] 2018-10-27 17:58
that's why from the beginning I say it's 100% sure it's the marlin I never had any other worries before except the passage of Marlin 2

**Comment by p3p** [comment] 2018-10-27 18:15
What was fixed by reducing the dimensions?

We are talking about a lot of separate issues here, which is a bit confusing with your short responses, this is for the missing step on your Y axis, you are now running Marlin on a much more powerful Controller, signals that used to be slow enough for your driver because it was as fast as the AVR could produce them could now be too fast. Have you read the datasheet and made sure all the settings are correct? such as `MINIMUM_STEPPER_DIR_DELAY` that defaults to 50ns.. the datasheet specifies this needs to a much larger value of 5000ns,

I'm not saying there is nothing wrong with Marlins LPC176x platform, but there a numerous people running Marlin on the MKS Sbase so it being a general issue is unlikely we are just trying to narrow the problem down for you.

**Comment by gauix4** [comment] 2018-10-27 18:27
@p3p 
no problem I understand
MKS robin,lerdeX, lerdgeS  are boards 32bits
I read the dates of my stepper there is no problem everything is well settled more I can program them

the manipulation that is going to fix all the problems was to decrease the lengths of my printer I had put 300X300 and everything was working properly

that I put the dimensions of my printer and that I print large parts much more works at least that's what I found I can perhaps be wrong

**Comment by gauix4** [comment] 2018-10-27 19:31
I just reinstalled the gen 1.4 everything works properly...
last week I used the smoothieware software everything worked...

**Comment by gauix4** [comment] 2018-10-27 19:32
last week I used the smoothieware software everything worked...

**Comment by gloomyandy** [comment] 2018-10-27 19:45
Are you running Marlin 2.0.x on the gen 1.4? If not perhaps you can try it. Does the BL touch work on the gen 1.4 with the full bed size defined? 

Why are you trying to use Marlin rather then Smoothieware?

**Comment by gauix4** [comment] 2018-10-27 21:38
@gloomyandy  I'll have to try yes because I'm on MARLIN 1 and everything works perfectly
because we can do nothing at all with smoothie firmware
il me faut un auto bed leveling car mon imprimante est trop grosse impossible d'imprimer sans bed auto leveling  smoothie has one but it is very poorly managed

**Comment by gauix4** [comment] 2018-10-28 01:32
good marlin 1 on the gen 1.4  it does not work either it shifts Y but I've already tried it marchai good marlin 1 on the gen 1. ' it does not work either it shifts Y but I've already tried it walked
I do not understand anymore

**Comment by gauix4** [comment] 2018-10-28 01:38
test that it does not work either
check my signal 0/5 volts ok
I use booster at the
https://fr.aliexpress.com/item/LERDGE-3D-Printer-Board-Adapter-Module-External-High-Power-Switching-Module-for-Microstep-Driver-with-3D/32821023876.html


<img width="700" alt="capture d ecran 2018-10-28 a 02 35 24" src="https://user-images.githubusercontent.com/23041016/47610958-248e0880-da5a-11e8-8023-60e993726d94.png">

**Comment by gauix4** [comment] 2018-10-28 17:34
person to an idea ?

**Comment by p3p** [comment] 2018-10-28 19:45
Sorry Simon at this point without the hardware to debug with, or anyway to reproduce the problems you are having, it's difficult to help.

That stepper configuration should have more than sufficient delays for your Y stepper driver, the problem with levelling at large dimensions worries me but I have no way to test that and it's not really my area, you may have better luck with UBL rather than bilinear. 

The temperature fluctuations shouldn't be possible without huge amounts of noise as there is a lot of software filtering, but that at least I can test.

**Comment by gauix4** [comment] 2018-10-29 00:32
@p3p  I can still try anyway I am open to all at this stage I do not know what to do other than change its driver and engine  I never liked them

**Comment by gauix4** [comment] 2018-10-29 03:29
![63cac8a7-a821-4970-b32f-8d95f7922646](https://user-images.githubusercontent.com/23041016/47627936-34c5e680-db33-11e8-8a53-942941cf003b.jpeg)
![465bc64d-cdea-491e-ad01-e0bc83e2c672](https://user-images.githubusercontent.com/23041016/47627937-34c5e680-db33-11e8-9cce-9804b402cabd.jpeg)
![Uploading 862D7A83-5591-4E30-A0D4-3930FB32CC3D.jpeg…]()

**Comment by gauix4** [comment] 2018-10-29 03:30
@p3p we can see that the shift is not random

**Comment by gauix4** [comment] 2018-10-29 03:35
@p3p this is on the last 1xx Marlin it does the same thing on the 2xx marlin 
last time i tried with a former sailor one that worked fine so i think there is an update made that generates this problem when do you think?

**Comment by gloomyandy** [comment] 2018-10-29 07:40
If you think that is the case, work your way back through versions to see if you can pinpoint which change is causing the problem. Have you made any changes to your configuration since you had a working system? What about the hardware any changes to that? Are you using the same speeds wtc. as before?

**Comment by gauix4** [comment] 2018-11-01 18:47
it works according to the parts there are parts it prints across there are non parts

**Comment by gauix4** [comment] 2018-11-01 18:49
and therefore order real brushless motor (clearPath ref: CPM-SDSK-2310S-EQN) even though I think the problem will still be there
at least I will have a good brushless motor with all that goes well

**Comment by gauix4** [comment] 2018-11-22 15:08
@p3p 
I received my new clearPath engine
and nothing function so I started my research
and I realized that the problem was coming from ENABLE
the signal is not clear at all when I plug on 3.3V everything works

[IMG_2037.JPG.zip](https://github.com/MarlinFirmware/Marlin/files/2608551/IMG_2037.JPG.zip)

**Closed as completed** 2018-11-26 18:29 UTC

**Comment by emretrk** [comment] 2018-12-04 14:10
Hi everyone,

I am a student in Turkey and ı also see like that problem. My drivers are also leadshine es-d508 and es-d808. I couldn't solve this problem. Are there anyone to solve this problem ? 

actually ı solved, but my speed really low which is 20-25 mm/s. And surface quality is really bad in like sphere parts. I increased the pulses/resolution to the 5000. Thats mean, 4 mm pitch / 5000 pulse = 0.0008 mm. But surface quality in sphere parts and velocity are really bad.

3D printer is mu capstone project. ı must solve this...
