### ISSUE TITLE
[BUG] About "Z Safe Homing"...

### ISSUE THREAD

**Issue by xsuper9988** [MarlinFirmware/Marlin#19835] opened 2020-10-21 09:42 UTC
My Ver 2.0.7.1

When i use "Dual X Carriage"
The situation is
1. XY homing
2. XY move to XY center
3. Z homing
"Z Safe Homing" normal work.

PS:
When i use "Dual X Carriage" mode
#define X_MIN_POS -60
and i test edit
#define Z_SAFE_HOMING_X_POINT -60
but X axis Positioning at 0
 
 
 
When i did not use "Dual X Carriage"
The situation is
1. XY homing
2. XY did not move to XY center
3. Z homing
4. Main page XY position is center,
    but machine XY axis is in Zero position

My Configuration Link
https://github.com/xsuper9988/marlin-Configuration

**Comment by ellensp** [comment] 2020-10-21 12:02
you have //#define Z_SAFE_HOMING

**Comment by abacabie** [comment] 2020-10-21 13:16
Just looked through your Configuration.h file and you don't have #define Z_SAFE_HOMING uncommented, just uncommented, compile and your good to go.

**Comment by xsuper9988** [comment] 2020-10-21 14:33
i test three times
when homing finish
machine xy axis in zero position
but main page xy in center position
and i use manual probe(#19833)
machine xy axis will be dangerous hit
so i mark //#define Z_SAFE_HOMING

**Comment by boelle** [comment] 2020-10-21 15:15
is #19833 the same problem as this one?

**Comment by xsuper9988** [comment] 2020-10-22 03:32
Maybe some motion move function bugs at homing finish

and the bug likes #19833 

But when i did not use "Dual X Carriage" and "Z Safe Homing"

"Manual Probe" function is OK

**Comment by xsuper9988** [comment] 2020-10-22 03:34
Maybe some motion move function bugs at homing finish

and the bug likes #19833 

But when i did not use "Dual X Carriage" and "Z Safe Homing"

"Manual Probe" function is OK

**Comment by sjasonsmith** [comment] 2020-11-07 10:54
I don't really understand what the issue is in this report. Which exact behavior do you consider incorrect?
Please post the _exact_ configuration files that you use to reproduce that behavior.

**Comment by boelle** [comment] 2020-11-07 18:08
@xsuper9988 ^^^^^

**Comment by sjasonsmith** [comment] 2020-11-16 08:28
It is still not clear to me what this issue is reporting. Since no additional detail was added after my last reply, I am going to close this as not actionable.

When reporting an issue, please be sure to follow all instructions at the top of the template, including debugging steps, and leave the sections headings intact. This will help make it much easier for others to understand your issue and provide help.

For reference, these are the instructions included in the template:

### Before Reporting a Bug

1. Test with the `bugfix-2.0.x` branch to see whether the issue still exists.

2. Get troubleshooting help from the Marlin community to confirm it's a bug and not just a configuration error. Links at https://github.com/MarlinFirmware/Marlin/issues/new/choose

### Instructions

1. Fill out every section of the template below.

2. Always attach configuration files, regardless of whether you think they are involved.

3. Read and understand Marlin's Code of Conduct. By filing an Issue, you are expected to comply with it, including treating everyone with respect: https://github.com/MarlinFirmware/Marlin/blob/master/.github/code_of_conduct.md

**Closed as completed by sjasonsmith** 2020-11-16 08:28 UTC
