### ISSUE TITLE
[BUG] BIGTREE_SKR_PRO_1v1  Pins mixed: calling (pin PF7) turns on (PF8)

### ISSUE THREAD

**Issue by carl1961** [MarlinFirmware/Marlin#16158] opened 2019-12-09 06:47 UTC
### Bug Description

Found while using RGB LED after Updating Marlin 2.0.x 

Last working correctly (RGB LED)  Marlin-bugfix-2.0.x "2019-11-10"
Configuration.h

#define RGB_LED
//#define RGBW_LED

#if EITHER(RGB_LED, RGBW_LED)
  #define RGB_LED_R_PIN PF9
  #define RGB_LED_G_PIN PF8
  #define RGB_LED_B_PIN PF7
  //#define RGB_LED_W_PIN -1
#endif

#define STRING_DISTRIBUTION_DATE "2019-11-10"

C:\BIGTREETECH\Working Mega CoreXY\newer\Marlin-bugfix-2.0.x\buildroot\share\PlatformIO\variants\BIGTREE_GENERIC_STM32F407_5X

First BROKEN  Version traced back to Marlin-bugfix-2.0.x "2019-11-14"

 #define STRING_DISTRIBUTION_DATE "2019-11-14"

Pins mixed:

turning  Blue LED On (pin PF7) turns on Green LED (PF8) Blue LED never comes on so pin PF7 is not active.

I think issue started when

variants   BIGTREE_GENERIC_STM32F407_5X was updated (changed), with (to) BIGTREE_SKR_PRO_1v1

C:\BIGTREETECH\Marlin-bugfix-2.0.x\buildroot\share\PlatformIO\variants
BIGTREE_SKR_PRO_1v1\PeripheralPins.c

I have not found any other issues, printer runs fine except for these pins used for RGB LED.

### My Configurations

**Required:** Please include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
[Configuration_Files.zip](https://github.com/MarlinFirmware/Marlin/files/3938180/Configuration_Files.zip)

**working PeripheralPins.c**
[PeripheralPins.zip](https://github.com/MarlinFirmware/Marlin/files/3991833/PeripheralPins.zip)

### Steps to Reproduce

1.  Compile Firmware Marlin-2.0.x for BIGTREE_SKR_PRO  
2.  Issue  M150 B255  from Pronterface or from Display LED Menu

**Expected behavior:** 
Blue LED Light coming on (Pin PF7)
**Actual behavior:** [What actually happens]
Green LED comes on  (Pin PF8)

**EDIT: 12-9-2019 Temporary Fix**

Replacing PeripheralPins.c from C:\BIGTREETECH\Marlin-2.0.x\buildroot\share\PlatformIO\variants\BIGTREE_SKR_PRO_1v1
with  PeripheralPins.c  from Marlin-bugfix-2.0.x "2019-11-10"  

 C:\BIGTREETECH\Working Mega CoreXY\newer\Marlin-bugfix-2.0.x\buildroot\share\PlatformIO\variants\BIGTREE_GENERIC_STM32F407_5X

Everything works that I tested.
Board  BigTreeTech SKR Pro 1.1 
Firmware:  Latest Marlin-2.0.x with only file above changed (PeripheralPins.c)
BigtreeTech  TMC 5160 1.2 on X, Y, Z   LV8729 on E0
BLtouch 3.0  ( on BLTouch 4 pin header)  VCC, PA1, GND , PA2
RGB LED on the pins :
  #define RGB_LED_R_PIN PF9
  #define RGB_LED_G_PIN PF8
  #define RGB_LED_B_PIN PF7
Z-auto align (using 3 steppers)
Auto bed level
I2C eeprom Module on 4 pin I2C header  PB7 (SCA) PB6 (SCL) GND VCC
Hotend fans come on at and above 50C and go off below 50C
Printing test Cube worked fine
Auto Power on/off  PE10
X,  Endstop   PB10      Y Endstop PE12
Filament Runout Sensor  PE15

Something in latest     file PeripheralPins.c , causing pins mixed and others not working .
swapping PeripheralPins.c from older version, most likely not a correct procedure, but got me going.

**NOTE:**  for  Click to resume... Issue

also another old known not fixed issue, thing you will most likely need to do if your using the RGB is comment out some lines in "queue.cpp"
C:\BIGTREETECH\Marlin-2.0.x\Marlin\src\gcode\queue.cpp
around line 537
else {
SERIAL_ECHOLNPGM(MSG_FILE_PRINTED);
#if ENABLED(PRINTER_EVENT_LEDS)
printerEventLEDs.onPrintCompleted();
// #if HAS_RESUME_CONTINUE
// inject_P(PSTR("M0 S"
// #if HAS_LCD_MENU
// "1800"
// #else
// "60"
// #endif
// ));
// #endif
#endif // PRINTER_EVENT_LEDS
}
}
else if (n == -1)
SERIAL_ERROR_MSG(MSG_SD_ERR_READ);
so your printing does not pause at last few lines when the RGB goes to green signalling your finished . https://github.com/MarlinFirmware/Marlin/issues/15054... https://youtu.be/ipmvCMhUBXc

**Comment by arminth** [comment] 2019-12-21 18:48
Thanks a lot! I will try this now because I was struggeling with the exact same behaviour!

Will report!

**Comment by arminth** [comment] 2019-12-21 19:04
And I can confirm: YOU ARE RIGHT!! Iwas already thinking I am stoo stupid and have to give back my enigineering degree!
Finally I can use my cheapo LIDL LED strip on my printer!
Thx a lot - I hope somone fixes this ASAP in the bugfix version!

Chears
Armin

**Comment by boelle** [comment] 2019-12-24 12:54
@carl1961 is the issue still the same with all the updates in the last 15 days?

**Comment by boelle** [comment] 2019-12-24 13:31
btw, who can confirm there is an issue? use the same configs as OP and the same hardware if possible

**Comment by carl1961** [comment] 2019-12-25 03:18
soon as I get home, I will check for you.

**Comment by carl1961** [comment] 2019-12-25 12:47
@boelle  New Marlin 2.0.1 Update did not fix this issue, because the (PeripheralPins.c) file or the same. (Identical)
 **but** un-commenting Lines: 188-191 in  (Marlin 2.0.1 Update) 
Marlin-2.0.x\buildroot\share\PlatformIO\variants\BIGTREE_SKR_PRO_1v1\PeripheralPins.c  fixed this issue.
![Uncomment these](https://user-images.githubusercontent.com/3056821/71445729-d1f1c000-26e1-11ea-8529-34e857834196.png)

**Comment by boelle** [comment] 2019-12-25 13:44
@thinkyhead can you cook up a fix from the above post?

**Comment by viper93458** [comment] 2019-12-26 01:07
Confirmed to fix the generic RGB string LEDs for me as well on the SKR pro. If I used the PC9 PWM pin, then the LED channel/color connected to that PIN would work, but none of the others would. I tried various pins and pin definitions in the lines below:
#define RGB_LED_R_PIN xxx
#define RGB_LED_G_PIN xxx
#define RGB_LED_B_PIN xxx

and ultimately settled on PF9, PF8 and PF7 like the OP did since it was mentioned that those pins did indeed work a while back. I tried other pins just for experimentation.

I hope that uncommenting those lines doesn't break anything else that @LinoBarreca has been working on for the SKR Pro board!

-William

**Comment by carl1961** [comment] 2019-12-26 01:25
> Confirmed to fix the generic RGB string LEDs for me as well on the SKR pro. If I used the PC9 PWM pin, then the LED channel/color connected to that PIN would work, but none of the others would. I tried various pins and pin definitions in the lines below:
> #define RGB_LED_R_PIN xxx
> #define RGB_LED_G_PIN xxx
> #define RGB_LED_B_PIN xxx
> 
> and ultimately settled on PF9, PF8 and PF7 like the OP did since it was mentioned that those pins did indeed work a while back. I tried other pins just for experimentation.
> 
> I hope that uncommenting those lines doesn't break anything else that @LinoBarreca has been working on for the SKR Pro board!
> 
> -William

looks to be just timers for those 4 pins that is effected.

**Comment by LinoBarreca** [comment] 2020-01-02 15:24
@boelle this is duplicate with the last one we were talking on.

**Comment by LinoBarreca** [comment] 2020-01-02 15:24
@carl1961 those lines MUST be commented.

**Comment by boelle** [comment] 2020-01-02 15:25
dublicate of #16300, so closing, we only need one open with the same issue

**Closed as completed by boelle** 2020-01-02 15:25 UTC

**Comment by LinoBarreca** [comment] 2020-01-02 15:59
If you are wondering why it worked before my modifications the answer is simple:
you were using the board outside its specifications and BTT (stupidly) allowed you to do it (this was causing other issues with timers)
I didn't "break it", I just fixed a bug from BTT making the board work as intended.
### SORRY ABOUT THAT
but any software developer can't (and shouldn't) care about out-of-specs usage by the end-user.
And the end user **must not** believe that an out-of-specs usage of something will be for-ever-working.

Anyway....I realize that it could be useful to attach a RGBW strip to digital pins, though, that's why we opened a feature request for it (using SOFT-PWM). Not many boards have so many analog pwm..so it's a logical feature request....to workaround, at the moment, swap RGB and FANS and `#define FAN_SOFT_PWM`
