### ISSUE TITLE
Resume menu appearing after Stopped print

### ISSUE THREAD

**Issue by rafaellehmkuhl** [MarlinFirmware/Marlin#11144] opened 2018-06-29 16:27 UTC
### Description

After pausing a print (whit advanced pause enabled) from LCD and Stopping the print, the print stops, but when I choose some gcode from "Print from SD" menu, Marlin offers me to resume the print (which was already stopped). 

When this happens I need to Resume (if I choose "Extrude More", I need to choose to Resume after anyway) and the nozzle goes back to the print position (previous to Pause). The print does not resume from that, but starts regular "Print from SD" behaviour.
### Steps to Reproduce

1. Print something from SD card
2. Pause the print
3. Stop the print
4. Print something from SD card
5. The bug happens

**Expected behavior:**

The resume menu should not appear after a Stop.

**Actual behavior:**

The resume menu appears.

#### Additional Information

Running stable 1.1.x with ADVANCED_PAUSE enabled.

**Comment by thinkyhead** [comment] 2018-06-29 21:19
You didn't attach your configurations. So we must ask, are you using `POWER_LOSS_RECOVERY`?

**Comment by thinkyhead** [comment] 2018-06-29 21:33
Please test with the latest `bugfix-1.1.x` (and/or `bugfix-2.0.x`) branch to see where it stands. If the problem has been resolved then we can close this issue. If the issue isn't resolved yet, then we should investigate further.

**Comment by boelle** [comment] 2019-02-20 14:45
@rafaellehmkuhl did you what thinky suggested?

**Comment by boelle** [comment] 2019-03-06 12:08
@thinkyhead i think we can close this one

**Comment by 7eggert** [comment] 2019-03-10 12:24
I tested this with my (patched) bugfix-1.1.x firmware, it seems to be fixed.

**Closed as completed** 2019-03-10 14:20 UTC
