### ISSUE TITLE
Some {} got messed up with FAST_PWM_FAN

### ISSUE THREAD

**Issue by Lukelectro** [MarlinFirmware/Marlin#2759] opened 2015-11-05 21:21 UTC
In branch RCBugfix:

Marlin_main.cpp: In function ‘void setPwmFrequency(uint8_t, int)’:
Marlin_main.cpp:7167: error: a function-definition is not allowed here before ‘{’ token
Marlin_main.cpp:7208: error: expected `}' at end of input

This is because I enabled FAST_PWM_FAN, and it causes  void setPwmFrequency(uint8_t pin, int val) { to be included which is missing a }.

} // bugfix
# endif // FAST_PWM_FAN

To reproduce this bug enable FAST_PWM_FAN in configuration.h

I'll see if I can make a good pull request this time, but it is probably faster if someone else just includes that } on line 7164 in marlin_main.cpp

**Comment by AnHardt** [comment] 2015-11-05 21:43
PR #2732 is already there. Needs only one who merges that. (I really think i should not merge my own PRs)
Duplicate of https://github.com/MarlinFirmware/MarlinDev/issues/248
Already fixed in MarlinDev/master by https://github.com/MarlinFirmware/MarlinDev/pull/251

Thanks for the hint.

**Comment by Wackerbarth** [comment] 2015-11-05 21:59
PR#2732 merged

**Closed as completed by Wackerbarth** 2015-11-05 21:59 UTC

**Comment by Lukelectro** [comment] 2015-11-05 22:07
Ok, that was quick :)

Now, on to find some other bug... Hmm, Lets try M206 again...
