### ISSUE TITLE
Encoder inversion and cheap smart lcd controllers

### ISSUE THREAD

**Issue by dantman** [MarlinFirmware/Marlin#2250] opened 2015-06-04 00:50 UTC
I wonder if a lot of the complaints and troubles with the encoder could be solved with an `ENCODER_INVERTED(_PINS)` setting. And perhaps an additional `ENCODER_INVERTED_COUNTERS` (or `ENCODER_INVERTED_MENU`) define. (From the other issues where people suggest they want opposite inversions for menu navigation and the counters in “move axis”)

—-
Here’s the long story. (As sometimes happens, I ‘solved’ my own problem half way through writing a bug report.

I have a [LCD2004](http://www.robotdigg.com/product/122/RAMPS-LCD2004-with-SD-Socket) from RobotDigg and I had some issues tuning the encoder.

With default settings the the encoder was inverted (clockwise goes up the menu and decrements counters), there are some quirks in menu navigation, and incrementing counters in the move axis menu incremented numbers by 4 each time.

I attempted to edit pins.h to swap the encoder pins. But in such a large file I changed the wrong pins, got confused, and ended up on a long tangent experimenting with negative values and studying ultralcd.cpp in detail.

I first changed settings to these:

```
#define ENCODER_PULSES_PER_STEP -1
#define ENCODER_STEPS_PER_MENU_ITEM 4
```

This fixed my inversion issues and the quirks in menu navigation. (i.e.: the quirks were just because the default steps are 5 and my encoder sent 4 pulses making some turns skip inconsistently). But move axis counts still incremented by 4.

From there I thought it was an easy change to this config:

```
#define ENCODER_PULSES_PER_STEP -4
#define ENCODER_STEPS_PER_MENU_ITEM 1
```

Unfortunately I discovered that while this fixed my incrementing trouble. A strange issue showed up in the menu. With some some ticks being skipped and strange inconsistent skips when I go one way though the menu then start turning the encoder in the other direction.

After a lot of examination into Marlin’s code and writing most of this bug report I tried this config:

```
#define ENCODER_PULSES_PER_STEP 4
#define ENCODER_STEPS_PER_MENU_ITEM 1
```

My inverted encoder issue was still present of course. However all those menu issue disappeared and the incrementing trouble was gone too. Which tells me that those extra glitches I encountered were to do with using a negative pulses per step.

---

I’ve already “_solved_” the issue for myself. I discovered the correct set of pins in pins.h and swapped them then used this config:

```
#define ENCODER_PULSES_PER_STEP 4
#define ENCODER_STEPS_PER_MENU_ITEM 1
```

So this is not a troubleshooting question, but a suggestion on how to solve the inversion issue.

An `ENCODER_INVERTED(_PINS)` definition could swap the values of the `BTN_EN1` and `BTN_EN2` defines. That’s assuming it’s possible to redefine pins based on other defines from Configuration.h.
If not we could introduce something like an `EFECTIVE_BTN_EN{1,2}` (probably an abbreviation of that) that is used through the system and contains values that are swapped if `ENCODER_INVERTED(_PINS)` is true.
Or the numeric calculations inside of `ultralcd.cpp` could be inverted by the define.

An `ENCODER_INVERTED_COUNTERS` or `ENCODER_INVERTED_MENU` would involve a few tweaks to `ultralcd.cpp` that would invert calculations involved with either the counters related to axis movement or the menu navigation steps.

**Comment by AnHardt** [comment] 2015-06-04 14:57
Duplicate of #1720

**Closed as completed by AnHardt** 2015-06-04 14:57 UTC
