### ISSUE TITLE
[BUG] MKS Robin nano v2, MKS_UI compilation error

### ISSUE THREAD

**Issue by Malderin** [MarlinFirmware/Marlin#22387] opened 2021-07-18 08:45 UTC
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

When compiling, an error appears:
```
Marlin\src\lcd\extui\mks_ui\draw_error_message.cpp:42:12: error: 'disp_string' was not declared in this scope
   if (msg) disp_string((TFT_WIDTH - strlen(msg) * 16) / 2, 100, msg, 0xFFFF, 0x0000);
            ^~~~~~~~~~~
Marlin\src\lcd\extui\mks_ui\draw_error_message.cpp:42:12: note: suggested alternative: 'disp_state'
   if (msg) disp_string((TFT_WIDTH - strlen(msg) * 16) / 2, 100, msg, 0xFFFF, 0x0000);
            ^~~~~~~~~~~
            disp_state
Marlin\src\lcd\extui\mks_ui\draw_error_message.cpp:43:3: error: 'disp_string' was not declared in this scope
   disp_string((TFT_WIDTH - strlen("PRINTER HALTED") * 16) / 2, 140, "PRINTER HALTED", 0xFFFF, 0x0000);
   ^~~~~~~~~~~
Marlin\src\lcd\extui\mks_ui\draw_error_message.cpp:43:3: note: suggested alternative: 'disp_state'
   disp_string((TFT_WIDTH - strlen("PRINTER HALTED") * 16) / 2, 140, "PRINTER HALTED", 0xFFFF, 0x0000);
   ^~~~~~~~~~~
   disp_state
*** [.pio\build\mks_robin_nano35_maple\src\src\lcd\extui\mks_ui\draw_error_message.cpp.o] Error 1
 
========================= [FAILED] Took 136.88 seconds =========================
Environment             Status    Duration
----------------------  --------  ------------
mks_robin_nano35_maple  FAILED    00:02:16.884
==================== 1 failed, 0 succeeded in 00:02:16.884 ====================
```

### Version of Marlin Firmware

Latest marlin bugfix 2.x

My configs:
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/6835880/Configuration.zip)

**Comment by ellensp** [comment] 2021-07-18 08:52
Duplicate of https://github.com/MarlinFirmware/Marlin/issues/22349

**Closed as completed by ellensp** 2021-07-18 08:52 UTC
