### ISSUE TITLE
[BUG] (MKS Robin nano V2, does not load with the TMC2209 drivers)

### ISSUE THREAD

**Issue by Malderin** [MarlinFirmware/Marlin#21634] opened 2021-04-17 06:49 UTC
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

Latest marlin 2.0 bugfix.
Board: MKS robin nano v.2

After activation by the TMC2209 driver in the configuration.h, the board does not boot after reflashing. Shows just a black screen and that's it.

### Steps to Reproduce

Changed parameters in the configuration:

1. Platformio.ini:
`default_envs = mks_robin_nano35`

2. Сonfiguration.h:

```
#define SERIAL_PORT 3
#define MOTHERBOARD BOARD_MKS_ROBIN_NANO_V2
#define TEMP_SENSOR_BED 1
#define SDSUPPORT
#define MKS_TS35_V2_0
#define TFT_LVGL_UI
#define MKS_WIFI_MODULE  // MKS WiFi module
#define X_DRIVER_TYPE  TMC2209
#define Y_DRIVER_TYPE  TMC2209
#define Z_DRIVER_TYPE  TMC2209
#define E0_DRIVER_TYPE TMC2209
```

### Version of Marlin Firmware

Marlin 2.0 bugfix (latest on 16.04.2021)

[config.zip](https://github.com/MarlinFirmware/Marlin/files/6328749/config.zip)

**Comment by thisiskeithb** [comment] 2021-04-17 07:00
Duplicate of https://github.com/MarlinFirmware/Marlin/issues/21632

**Closed as completed by thisiskeithb** 2021-04-17 07:00 UTC
