### ISSUE TITLE
Skr 1.3 not able to print after updating to latest marlin

### ISSUE THREAD

**Issue by fnhhnxfn** [MarlinFirmware/Marlin#17907] opened 2020-05-07 13:13 UTC
-->

### Bug Description

hi guys this can be stupid question but i am having 3 skr1.3 running on my printers and recently i bought 5 new skr 1.3 boards and flashed latest marlin bugfix  version firmware and i am having following issues :
I cannot print over onboard sd or tft SD or via computer 
when i try to print via onboard it started print but after 30-40 min it stucked at random point and starts rebooting itself , then i tried printing via computer and same issue again , then i connected tft 35 to aux 1 and tried to start printing it heated up the extruder and didnt star the print and its same for all 5 boards 

### My Configurations

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/4593107/Marlin.zip)

### Steps to Reproduce

1. [tried changing SD cards]
2. [tried changing gcodes  and sliced files in different softwares ]
3. [and so on...]

**Expected behavior:** [What you expect to happen]
it should start printing like all other printers
**Actual behavior:** [What actually happens]
it stops at random position during printing and reboots it self
#### Additional Information

* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.

**Comment by thinkyhead** [comment] 2020-05-10 09:07
Others are able to use that hardware. So there must be something else going on. I must throw you two canned (but helpful) replies:

---

Please test the [`bugfix-2.0.x` branch](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.0.x.zip) to see where it stands. Don't forget to reset the EEPROM. If the problem has been resolved then we can close this issue. If the issue isn't resolved yet, then we should investigate further.

---

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).

**Closed as completed by thinkyhead** 2020-05-10 09:07 UTC
