### ISSUE TITLE
[bugfix-2.0.x] EEPROM datasize error

### ISSUE THREAD

**Issue by TiToMoskito** [MarlinFirmware/Marlin#10182] opened 2018-03-21 17:26 UTC
I got an  EEPROM datasize Error and i added this line to my configuration.h
**#define DEBUG_EEPROM_READWRITE**

Than i got this error on my octoprint **Field planner_extruder_advance_K mismatch.**

I have an MKS Gen 1.4 with 5 TMC2208

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/1835062/Configuration.zip)

**Comment by Roxy-3D** [comment] 2018-03-22 00:06
The problem is also in bugfix-1.1.x.     The size is off by 22 bytes.   In my case:
```
echo: Index 629 Size: 651
```
I think this happened as a result of this commit:   https://github.com/MarlinFirmware/Marlin/commit/84bbd018ab7177c44e323a25a2ec014faa4c79ef

The size changed by 22 bytes because of
```
-  uint16_t tmc_stepper_current[11];                     // M906 X Y Z X2 Y2 Z2 E0 E1 E2 E3 E4
```

@thinkyhead

**Comment by vMeph** [comment] 2018-03-22 14:36
READ: Error:EEPROM datasize error.
READ: echo:Index: 629 Size: 651



getting error latest bug fix 1.1x

Index: 629 Size: 651
READ: Unified Bed Leveling System v1.01 inactive.
READ: echo:Hardcoded Default Settings Loaded
Hardcoded Default Settings Loaded

**Comment by Roxy-3D** [comment] 2018-03-22 14:50
Yeah...   I'm looking for the 'Revert' button...  But I can't find it.

**Comment by tximy** [comment] 2018-03-22 18:10
I have same error too I make M502, M500, and at M501 receive this error (Field planner_extruder_advance_K mismatch.) at

**Comment by lienbacher** [comment] 2018-03-22 21:02
Is there any hotfix for this?

**Comment by Roxy-3D** [comment] 2018-03-23 00:26
I think it is fixed now...    But I did not test it.  (I have to run out the door....)

If it is not fixed....   Please post a message!!!!!!

**Comment by lienbacher** [comment] 2018-03-23 00:36
seems to work fine! neither firmware update nor M502 and M500 threw an error.
thanks!

**Comment by tximy** [comment] 2018-03-23 00:42
It did not work for me, I did not have TMC at this machine
echo: Last Updated: 2018-01-20 | Author: (none, default config)
echo:Compiled: Mar 23 2018
echo: Free Memory: 2897  PlannerBufferBytes: 1232
Error:Field planner_extruder_advance_K mismatch.
Error:EEPROM datasize error.
echo:Index: 673 Size: 695
Unified Bed Leveling System v1.01 inactive.
echo:Hardcoded Default Settings Loaded
echo:SD card ok
echo:EEPROM version mismatch (EEPROM= Marlin=V54)
echo:Hardcoded Default Settings Loaded
ok

**Comment by lienbacher** [comment] 2018-03-23 00:45
~~i got this error too, do a M502 and M500 and see if it works.~~ I do have a TMC though.
disregard, I overlooked the datasize error, only got the version mismatch error.

**Comment by tximy** [comment] 2018-03-23 00:49
I do M502, M500 but receive the error at M501 ;(  
and try to modify any data and save it to eeprom but at reset go to defaults
I try it over  bugfix-1.1.x.

**Comment by vMeph** [comment] 2018-03-23 01:15
i only updated the configuration_store.h file sense is the file that was update i still get error on command M501
READ: echo:EEPROM version mismatch (EEPROM=? Marlin=V53)
EEPROM version mismatch (EEPROM=? Marlin=V53)
READ: echo:Hardcoded Default Settings Loaded
Hardcoded Default Settings Loaded

and dont pops up nothing more

**Comment by Roxy-3D** [comment] 2018-03-23 04:28
> i only updated the configuration_store.h file sense is the file that was update

huh???

![image](https://user-images.githubusercontent.com/8404322/37811501-a3dbebae-2e28-11e8-8b53-5228232dd0c7.png)

Literally...  The format of the EEPROM storage changed with this data type change....   So I bumped the version number.   You can do a M502 followed with a M500 to get everything clean.

**Comment by Roxy-3D** [comment] 2018-03-23 05:12
Yikes!     We need to change this one too.  
```
      #if HAS_TRINAMIC
        #define TMC_SET_PWMTHRS(P,Q) tmc_set_pwmthrs(stepper##Q, TMC_##Q, tmc_hybrid_threshold[TMC_##Q], planner.axis_steps_per_mm[P##_AXIS])
        uint16_t tmc_hybrid_threshold[TMC_AXES];
        EEPROM_READ(tmc_hybrid_threshold);
        if (!validating) {
          #if X_IS_
```
It is very possible they really should be 16 bits...  But 32 bits is safe right now.

**Comment by thinkyhead** [comment] 2018-03-23 05:54
I'll patch this momentarily…

**Comment by thinkyhead** [comment] 2018-03-23 06:09
Got this one too:
![image](https://user-images.githubusercontent.com/698003/37814216-3bb637b6-2e3f-11e8-886c-470914dd2d7d.png)

**Comment by tximy** [comment] 2018-03-23 07:25
It work nice for me, thx.

**Comment by gecko749** [comment] 2018-03-23 17:00
Hi,

I get this Error with std Steppers. So it is not related to TMC steppers. Tried with bugfix_1.1.x.

the error seems to be linked to UBL - it disappears when I compile with BL_bilinear

**Comment by thinkyhead** [comment] 2018-04-01 04:05
@gecko749 — What error do you get, specifically?

**Comment by gecko749** [comment] 2018-04-01 09:14
Hi,

Size mismatch by 22 Bytes.

**Comment by thinkyhead** [comment] 2018-04-02 06:57
Does `M500` eliminate the error?

**Comment by gecko749** [comment] 2018-04-02 15:16
no

**Comment by thinkyhead** [comment] 2018-04-03 02:04
@gecko749 — As the original issue is fixed, please open a new issue and post your Configuration files there. Be sure to test the current `bugfix-2.0.x` branch, as there have been changes to the EEPROM code in recent days.

**Closed as completed by thinkyhead** 2018-04-03 02:04 UTC
Labels: Bug: Confirmed !, Needs: Work, Needs: Patch
