### ISSUE TITLE
[FR] LinAdv Pattern generator: Loading meshs and G28 after heating up

### ISSUE THREAD

**Issue by ikarisan** [MarlinFirmware/Marlin#11930] opened 2018-09-26 18:57 UTC
Hi

This is a feature/change request for the pattern generator found at http://marlinfw.org/tools/lin_advance/k-factor.html 

a) The generated GCODE first homes all axis and after that it heats the bed. In my opinion it makes much more sense to heat up the bed first, wait a few seconds and after that start homing all axis. Or first just home X and Y and after heating up, home Z.

b) You can use G29 to level the bed before printing the pattern. But there should be an alternative option to load a stored mesh data after homing (i.e. M420 L<SELECTED SLOT> S1).

**Comment by thinkyhead** [comment] 2018-09-28 00:28
This really belongs under https://github.com/MarlinFirmware/MarlinDocumentation/issues

**Comment by forkoz** [comment] 2018-09-29 00:57
I concur... I fixed it manually in the gcode. Also had to squeeze bed leveling in there. I think the problem is that the tool is old.

**Comment by ikarisan** [comment] 2018-09-29 19:22
@thinkyhead Scott, maybe you are right. Based on the GIT repository the JavaScript und HTML is located under "MarlinDocumentation\_tools\lin_advance". Are you able to move this toppic to that location?

Maybe I will find the time to analyse the sources, modify them and place a push request... but this may take "a few" days. :(

**Comment by boelle** [comment] 2019-02-21 19:18
@ikarisan problem solved?

**Comment by boelle** [comment] 2019-03-13 20:43
@thinkyhead think we can close this one

**Comment by ikarisan** [comment] 2019-03-13 22:32
@boelle Yes :)

**Comment by boelle** [comment] 2019-03-13 22:35
@ikarisan then click the close button below

**Closed as completed** 2019-03-14 00:01 UTC
