### ISSUE TITLE
[BUG] try to change the step/mm of Z, I get an abnormal value

### ISSUE THREAD

**Issue by colcolcheese** [MarlinFirmware/Marlin#25806] opened 2023-05-10 12:34 UTC
### Bug Description

try to change the step/mm of Z, I get an abnormal value

### Additional information & file uploads

![11_3](https://github.com/MarlinFirmware/Marlin/assets/58139092/6ba53e88-bea1-44ac-84e6-7e139cb2cdf9)

**Comment by ellensp** [comment] 2023-05-10 12:38
no configs, so no way to replicate and no way to help you.

**Comment by ellensp** [comment] 2023-05-10 12:41
seems to be a duplicate of https://github.com/MarlinFirmware/Marlin/issues/23849

**Comment by colcolcheese** [comment] 2023-05-10 12:49
[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/11441958/Marlin.zip)
I'm sorry. I forgot.
this bugfix-2.1.x
If 2.1.x is also fixed, please close it.
I am testing with the version I downloaded 2 hours ago.

**Comment by ellensp** [comment] 2023-05-10 13:20
It still happens on bugfix, but since its been reported before, this duplicate issue must be closed.   Please add a "Im getting this also" type message to https://github.com/MarlinFirmware/Marlin/issues/23849

**Closed as completed by ellensp** 2023-05-10 13:20 UTC

**Comment by colcolcheese** [comment] 2023-05-10 22:28
Thanks for your thoughtful and clear advice
