### ISSUE TITLE
[BUG] (extruder does not work with sd card connected)

### ISSUE THREAD

**Issue by gpaaaa** [MarlinFirmware/Marlin#24785] opened 2022-09-20 14:24 UTC
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

When updating the latest version of marlim, the extruder stops working when I insert the sd card.

I've tried some of the solutions mentioned in previous problems, but with no success.

Board MKS ROBIN E3D
LCD MKS MINI 12864 V3
TMC 2209 drives

### Expected behavior

for the extruder motor to work

### Actual behavior

the extruder does not work

### Steps to Reproduce

1.BOARD_MKS_ROBIN_E3D_V1_1
2.MKS MINI12864 V3
3.Enable SDSUPORT

### Version of Marlin Firmware

Marlin-bugfix-2.1.x

### Printer model

Core xz

### Electronics

BOARD_MKS_ROBIN_E3D_V1_1

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/9608496/Configuration.zip)

**Comment by gpaaaa** [comment] 2022-09-20 14:26
I already checked and it didn't work.
https://github.com/MarlinFirmware/Marlin/issues/24380

**Comment by thisiskeithb** [comment] 2022-09-22 13:40
Duplicate of https://github.com/MarlinFirmware/Marlin/issues/24380

**Closed as completed by thisiskeithb** 2022-09-22 13:40 UTC
