### ISSUE TITLE
[bugfix-2.0] incompatible TMCStepper v0.2.2?

### ISSUE THREAD

**Issue by ar0707** [MarlinFirmware/Marlin#12144] opened 2018-10-18 18:11 UTC
`WARNING: library TMCStepper claims to run on (avr) architecture(s) and may be incompatible with your current board which runs on (sam) architecture(s).`

Downloaded  today the lasted Marlin 2.0, after downloading the new TMCStepper library, this warning appear. 
After uploading the .bin to the Arduino Due with Smart Ramps, the Display is blank and I'm not able to controll the printer.

Flashing an old Marlin which uses the TMC2130 Library, everthing works.  

Thanks

**Comment by thinkyhead** [comment] 2018-10-26 10:40
Recommend you stick with the old code until @teemuatlut has completed `TMCStepper`.

**Comment by boelle** [comment] 2019-02-21 19:26
@ar0707 problem solved?

**Comment by boelle** [comment] 2019-03-06 13:35
@thinkyhead i think we can close this one

**Closed as completed** 2019-05-16 23:15 UTC

**Comment by stormy-gh** [comment] 2019-07-09 13:47
I think the problem is in `stepper_indirection.cpp` in "`restore_stepper_drivers()`".

Error condition:
In `Configuration.h` enable:
```cpp
#define X_DRIVER_TYPE  TMC2130
#define PSU_CONTROL
#define AUTO_POWER_CONTROL
```
If there is no connection with TCM2130 Marlin hangs.

Problem is that in `restore_stepper_drivers()` method `stepperX.push()` is called without any check if communication with TMC2130 is working.

**Comment by thinkyhead** [comment] 2019-07-11 11:31
> restore_stepper_drivers

@teemuatlut — What would be the proper thing to check before we try to talk to the drivers? And, if we can't talk to the drivers at boot time, as I recall we do refresh them whenever the power is enabled by `M80` (or the auto-power behavior), so … we just have to **not go into an infinite loop** if the steppers are un-powered, whether at boot or any other time.

**Comment by stormy-gh** [comment] 2019-07-11 11:54
Because this issue is closed i made a separate issue for this topic: https://github.com/MarlinFirmware/Marlin/issues/14558
