### ISSUE TITLE
[BUG] DACAI Screen Support (Reality Ender 3 v2 NEO)

### ISSUE THREAD

**Issue by JaxGM** [MarlinFirmware/Marlin#26054] opened 2023-07-05 16:53 UTC
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

I recently installed a configuration of Marlin for my Ender 3 v2 Neo. It seams that that has worked well, however the screen is having multiple issues. I have looked at these topics and have noticed the problem has to do with it being a [DACAI](https://github.com/mriscoc/Ender3V2S1/wiki/How-to-update-the-display) display: #23860 & #25464
 

### Bug Timeline

This started a few months ago but I decided to wait it out a bit until I had some free time this summer to really deep dive into this.

### Expected behavior

I expected to have the screen act in the exact same way as before but with support for Host Action Commands.

### Actual behavior

The screen looked similar to before. The text and icons were sometimes missing, others were plain funky. I haven't been able to check the Host Action Commands.

### Steps to Reproduce

1. Install a Marlin configuration on a device with a DACAI screen.

### Version of Marlin Firmware

bugfix-2.1.x

### Printer model

Reality Ender 3 v2 NEO

### Electronics

All stock

### Add-ons

N/A

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Config.zip](https://github.com/MarlinFirmware/Marlin/files/11960213/Config.zip)

**Comment by thisiskeithb** [comment] 2023-07-05 16:56
Duplicate of https://github.com/MarlinFirmware/Marlin/issues/25464

**Closed as completed by thisiskeithb** 2023-07-05 16:56 UTC
