### ISSUE TITLE
[BUG + FIX] SKR 1.1 + LCD REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER = screen garbage

### ISSUE THREAD

**Issue by TriggerMeister** [MarlinFirmware/Marlin#16304] opened 2019-12-23 13:26 UTC
[Configuration_current.zip](https://github.com/MarlinFirmware/Marlin/files/3994890/Configuration_current.zip)
[April2019working_Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/3994954/April2019working_Configuration.zip)

### Bug Description

The problem is that I'm getting "garbage" on the LCD screen.  This was working in a prior Marlin 2.0 version, but something changed in Marlin or the way Marlin is compiled?

**Hardware:**
- Marlin 
- SKR 1.1
- Z-endstop inductive / BLTouch
- REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER

**Timeline:**
**Prior to the April 2019** I was running Marlin 2.0 with inductive probe on the HEVO printer, bilinear bed leveling.  LCD was working fine.
**In April 2019** I switched to to a BL touch clone, recompiled Marlin with the necessary configurations.  LCD was working fine
**In November 2019** I decided to remove the BL touch and go back to the inductive probe.  When I tried to recompile i was presented with re-compile problems because of a PlatformIO upgrade.  Hence, I grabbed the latest copy of Marlin 2.0, updated the stock config to match my hardware, etc.  I was able to compile, but was presented a issue with Bilinear bed leveling (stopped after probing 6 out of 9 points... was listed as a open issue at the time).  Switched to another working bed leveling method that worked.  Recompiled again.  After running for several minutes the screen garbage appears and it's seems to be confined to the top section that shows the heater temp appears.  To note, I have another printer with the same type of hardware setup, running the same marlin version with a re-arm board and it does not have this screen garbage issues.  As a reminder this was working fine in a previous Marlin version on the printer in question.  I'm also building a new printer with a new SKR 1.1. and same LCD that is also experiencing this issue, just so we can rule out the "hardware".  I followed the recommendations to add/increase the delay, which seems to only delay the issue from appearing.  

### My Configurations

**Required:** Please include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.

### Steps to Reproduce
- Do a fresh git pull for Marlin
- compile with attached configuration.h
- install on SKR 1.1 board and REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER

**Expected behavior:** [What you expect to happen]
Screen should work like it did in a earlier version. 

**Actual behavior:** [What actually happens]
Garbage appears on the LCD screen after a couple minutes of running. 

Delay of 200:
![IMG_20191223_074039958](https://user-images.githubusercontent.com/16250815/71358993-e5bdea80-2558-11ea-8061-85e9d0293067.jpg)

Worst scenario:
![IMG_20191222_210117205_BURST000_COVER_TOP](https://user-images.githubusercontent.com/16250815/71358529-4cda9f80-2557-11ea-8f9c-bdc5543dcf74.jpg)

![IMG_20191223_080018356](https://user-images.githubusercontent.com/16250815/71360175-e6588000-255c-11ea-8f62-466cdb94e2ce.jpg)

P.S. the pictures are from the new printer I'm building since it was more convenient to take them, but the LDC issue is identical on both printers.

#### Additional Information

* I can continue to play with the delays, but so far I'm at 450 and it still appears. The real question is what changed that caused the LCD to no longer work out-of-the-box?

**Comment by TriggerMeister** [comment] 2019-12-25 13:53
Merry Christmas!

**Here is a X-mas update:**  To test, I removed EXP2 connection from the board & LCD and the screen is working fine with a fresh pull, fresh compile, no added delays, etc.  The screen has been stable for almost 2 hours now with no garbage **(OF COURSE MY ROTARY ENCODER IS NOT WORKING WITH EXP2 DISCONNECTED)**. So the issue seems to be connected to EXP2, like possibly a wrong pin being used for SD card or rotary encoder.  I looked at the pin config in  pins_BTT_SKR_V1_1.h and it appears that there have been some significant changes from the last working version.  I'm guessing that there is some conflict in the pin output.  It also looks like the code was split to make the SKR code more reusable.  

Below is the pin file from when it was working.  Back then it was a single file and it was named BIQU_SKR_V1.1.  Can someone take a look if the pins are now different?  

`/**
 * Marlin 3D Printer Firmware
 * Copyright (C) 2019 MarlinFirmware [https://github.com/MarlinFirmware/Marlin]
 *
 * Based on Sprinter and grbl.
 * Copyright (C) 2011 Camiel Gubbels / Erik van der Zalm
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

#ifndef TARGET_LPC1768
  #error "Oops!  Make sure you have the LPC1768 environment selected in your IDE."
#endif

#ifndef BOARD_NAME
  #define BOARD_NAME "BIQU SKR V1.1"
#endif

//
// Limit Switches
//
#define X_MIN_PIN          P1_29
#define X_MAX_PIN          P1_28
#define Y_MIN_PIN          P1_27
#define Y_MAX_PIN          P1_26
#define Z_MIN_PIN          P1_25
#define Z_MAX_PIN          P1_24

//
// Steppers
//
#define X_STEP_PIN         P0_04
#define X_DIR_PIN          P0_05
#define X_ENABLE_PIN       P4_28

#define Y_STEP_PIN         P2_01
#define Y_DIR_PIN          P2_02
#define Y_ENABLE_PIN       P2_00

#define Z_STEP_PIN         P0_20
#define Z_DIR_PIN          P0_21
#define Z_ENABLE_PIN       P0_19

#define E0_STEP_PIN        P0_11
#define E0_DIR_PIN         P2_13
#define E0_ENABLE_PIN      P2_12

#define E1_STEP_PIN        P0_01
#define E1_DIR_PIN         P0_00
#define E1_ENABLE_PIN      P0_10

//
// Temperature Sensors
//  3.3V max when defined as an analog input
//
#define TEMP_BED_PIN       0   // Analog Input
#define TEMP_0_PIN         1   // Analog Input
#define TEMP_1_PIN         2   // Analog Input

//
// Heaters / Fans
//
#define HEATER_0_PIN       P2_07
#if HOTENDS == 1
  #define FAN1_PIN         P2_04
#else
  #define HEATER_1_PIN     P2_04
#endif
#define FAN_PIN            P2_03
#define HEATER_BED_PIN     P2_05

/**
 * LCD / Controller
 * 
 * As of 20 JAN 2019 only the REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER display has
 * been tested with these settings. It can be connected to the SKR using standard cables
 * via the EXP1 and EXP2 ports. Other displays may need a custom cable and/or changes to
 * the pins defined below.
 *
 * The SD card on the LCD controller uses the same SPI signals as the LCD, resulting in
 * garbage/lines on the LCD display during SD card access. The LCD code mitigates this
 * by redrawing the screen after SD card accesses.
 */

#if ENABLED(ULTRA_LCD)
  #define BEEPER_PIN       P1_30
  #define BTN_EN1          P3_26
  #define BTN_EN2          P3_25
  #define BTN_ENC          P2_11

  #define SD_DETECT_PIN    P1_31
  #define LCD_SDSS         P1_23
  #define LCD_PINS_RS      P0_16
  #define LCD_PINS_ENABLE  P0_18
  #define LCD_PINS_D4      P0_15
#endif

//
// SD Support
//
//#define USB_SD_DISABLED     // Disable host access to SD card as mass storage device through USB
#define USB_SD_ONBOARD        // Enable host access to SD card as mass storage device through USB

//#define LPC_SD_LCD          // Marlin uses the SD drive attached to the LCD
#define LPC_SD_ONBOARD        // Marlin uses the SD drive on the control board.  There is no SD detect pin
                              // for the onboard card.  Init card from LCD menu or send M21 whenever printer
                              // is powered on to enable SD access.

#if ENABLED(LPC_SD_LCD)

  #define SCK_PIN          P0_15
  #define MISO_PIN         P0_17
  #define MOSI_PIN         P0_18
  #define SS_PIN           P1_23   // Chip select for SD card used by Marlin
  #define ONBOARD_SD_CS    P0_06   // Chip select for "System" SD card

#elif ENABLED(LPC_SD_ONBOARD)

  #if ENABLED(USB_SD_ONBOARD)
    // When sharing the SD card with a PC we want the menu options to
    // mount/unmount the card and refresh it. So we disable card detect.
    #define SHARED_SD_CARD
    #undef SD_DETECT_PIN // there is also no detect pin for the onboard card
  #endif
  #define SCK_PIN          P0_07
  #define MISO_PIN         P0_08
  #define MOSI_PIN         P0_09
  #define SS_PIN           P0_06   // Chip select for SD card used by Marlin
  #define ONBOARD_SD_CS    P0_06   // Chip select for "System" SD card

#endif

// Trinamic driver support

#if HAS_TRINAMIC
  // Using TMC devices in intelligent mode requires extra connections to each device. Unfortunately
  // the SKR does not have many free pins (especially if a display is in use). The SPI-based devices
  // will require 3 connections (clock, mosi, miso), plus a chip select line (CS) for each driver.
  // The UART-based devices require 2 pis per deriver (one of which must be interrupt capable).
  // The same SPI pins can be shared with the display/SD card reader, meaning SPI-based devices are
  // probably a good choice for this board.
  //
  // SOFTWARE_DRIVER_ENABLE is a good option. It uses SPI to control the driver enable and allows the
  // hardware ENABLE pins for each driver to be repurposed as SPI chip select. To use this mode the
  // driver modules will probably need to be modified, removing the pin used for the enable line from
  // the module and wiring this connection directly to GND (as is the case for TMC2130).
  // Using this option and sharing all of the SPI pins allows 5 TMC2130 drivers to be used along with
  // a REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER without requiring the use of any extra pins.
  //
  // Other options will probably require the use of any free pins and the TFT serial port or a
  // different type of display (like the TFT), using the pins normally used for the display and encoder.
  // Unfortunately, tests show it's not possible to use endstop and thermistor pins for chip-select.
  // Sample settings are provided below, but only some have been tested.
  //
  // Another option is to share the enable and chip-select pins when using SPI. Several users have
  // reported that this works. However, it's unlikely that this configuration will allow SPI communi-
  // cation with the device when the drivers are active, meaning that some of the more advanced TMC
  // options may not be available.

  // When using any TMC SPI-based drivers, software SPI is used
  // because pins may be shared with the display or SD card.
  #define TMC_USE_SW_SPI
  #define TMC_SW_MOSI       P0_18
  #define TMC_SW_MISO       P0_17
  // To minimize pin usage use the same clock pin as the display/SD card reader. (May generate LCD noise.)
  #define TMC_SW_SCK        P0_15
  // If pin 2_06 is unused, it can be used for the clock to avoid the LCD noise.
  //#define TMC_SW_SCK        P2_06

  #if ENABLED(SOFTWARE_DRIVER_ENABLE)

    // Software enable allows the enable pins to be repurposed as chip-select pins.
    // Note: Requires the driver modules to be modified to always be enabled with the enable pin removed.
    #if AXIS_DRIVER_TYPE_X(TMC2130)
      #define X_CS_PIN         P4_28
      #undef  X_ENABLE_PIN
      #define X_ENABLE_PIN     -1
    #endif

    #if AXIS_DRIVER_TYPE_Y(TMC2130)
      #define Y_CS_PIN         P2_00
      #undef  Y_ENABLE_PIN
      #define Y_ENABLE_PIN     -1
    #endif

    #if AXIS_DRIVER_TYPE_Z(TMC2130)
      #define Z_CS_PIN         P0_19
      #undef  Z_ENABLE_PIN
      #define Z_ENABLE_PIN     -1
    #endif

    #if AXIS_DRIVER_TYPE_E0(TMC2130)
      #define E0_CS_PIN        P2_12
      #undef  E0_ENABLE_PIN
      #define E0_ENABLE_PIN    -1
    #endif


    #if AXIS_DRIVER_TYPE_E1(TMC2130)
      #define E1_CS_PIN        P0_10
      #undef  E1_ENABLE_PIN
      #define E1_ENABLE_PIN    -1
    #endif

  #else // !SOFTWARE_DRIVER_ENABLE

    // A chip-select pin is needed for each driver.

    // EXAMPLES

    // Example 1: No LCD attached or a TFT style display using the AUX header RX/TX pins.
    //            LPC_SD_LCD must not be enabled. Nothing should be connected to EXP1/EXP2.
    //#define SKR_USE_LCD_PINS_FOR_CS
    #if ENABLED(SKR_USE_LCD_PINS_FOR_CS)
      #if ENABLED(LPC_SD_LCD)
        #error "LPC_SD_LCD must not be enabled with SKR_USE_LCD_PINS_FOR_CS."
      #endif
      #define X_CS_PIN      P1_23
      #define Y_CS_PIN      P3_26
      #define Z_CS_PIN      P2_11
      #define E0_CS_PIN     P3_25
      #define E1_CS_PIN     P1_31
    #endif

    // Example 2: A REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER
    //            The SD card reader attached to the LCD (if present) can't be used because
    //            the pins will be in use. So LPC_SD_LCD must not be defined.
    //#define SKR_USE_LCD_SD_CARD_PINS_FOR_CS
    #if ENABLED(SKR_USE_LCD_SD_CARD_PINS_FOR_CS)
      #if ENABLED(LPC_SD_LCD)
        #error "LPC_SD_LCD must not be enabled with SKR_USE_LCD_SD_CARD_PINS_FOR_CS."
      #endif
      #define X_CS_PIN      P0_02
      #define Y_CS_PIN      P0_03
      #define Z_CS_PIN      P2_06
      // We use SD_DETECT_PIN for E0
      #undef SD_DETECT_PIN
      #define E0_CS_PIN     P1_31
      // We use LCD_SDSS pin for E1
      #undef  LCD_SDSS
      #define LCD_SDSS      -1
      #define E1_CS_PIN     P1_23
    #endif

    // Example 3: Use the driver enable pins for chip-select.
    //            Commands must not be sent to the drivers when enabled. So certain
    //            advanced features (like driver monitoring) will not be available.
    //#define SKR_USE_ENABLE_CS
    #if ENABLED(SKR_USE_ENABLE_FOR_CS)
      #define X_CS_PIN      X_ENABLE_PIN
      #define Y_CS_PIN      Y_ENABLE_PIN
      #define Z_CS_PIN      Z_ENABLE_PIN
      #define E0_CS_PIN     E0_ENABLE_PIN
      #define E1_CS_PIN     E1_ENABLE_PIN
    #endif

  #endif // SOFTWARE_DRIVER_ENABLE

#endif
`

Thanks!

**Comment by aurion55** [comment] 2019-12-26 00:03
I got the same problem as above, I was using Marlin Bugfix_2.X for ages and decide to update to Marlin 2.0, I'm running a MKS Gen 1.4 board display is like above, expectt mind start straight away from boot up.
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/4000934/Configuration.zip)
[Configuration_adv.zip](https://github.com/MarlinFirmware/Marlin/files/4000935/Configuration_adv.zip)

**Comment by TriggerMeister** [comment] 2019-12-26 02:41
Still not sure why this happened after a upgrade to two SKR v 1.1 boards, but I found certain references that seems that this happens more often:

/**
 * LCD / Controller
 *
 * As of 20 JAN 2019 only the REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER display has
 * been tested with these settings. It can be connected to the SKR using standard cables
 * via the EXP1 and EXP2 ports. Other displays may need a custom cable and/or changes to
 * the pins defined below.
 *
 * The SD card on the LCD controller uses the same SPI signals as the LCD, resulting in
 * garbage/lines on the LCD display during SD card access. The LCD code mitigates this
 * by redrawing the screen after SD card accesses.
 */

It also appears that certain pins are being reused for special purposes and folks reference additional noise on the pins:

  // To minimize pin usage use the same clock pin as the display/SD card reader. (May generate LCD noise.)
  #define TMC_SW_SCK        P0_15

**Comment by TriggerMeister** [comment] 2019-12-27 05:17
Update:  I was able to make the LCD work properly with just the regular USB power supply (changed the jumper).  Anyone trying to duplicate this needs to use the internal power supply jumper setting.  It appears that for whatever reason the 5V (I measured 4.8V actually) ended up being noisier post Marlin update.  I know it will probably be dismissed as a hardware issue, but the board was running fine for long time with the same LCD.  To add to the coincidences, I have another SKR v 1.1 board with the same LCD's that has the same problem.  The LCD's have been verified on a Re-arm board and are working fine on it with the same Marlin version.

My solution to resolving the problem is to add a 100uF capacitor into the ribbon cable.  This resolved the garbled screen issue.  I still have to apply the same solution to the other board.

![IMG_20191226_234415745](https://user-images.githubusercontent.com/16250815/71502424-1db97c00-283e-11ea-989f-8e325eb4c54f.jpg)
![IMG_20191226_234400973_BURST000_COVER_TOP](https://user-images.githubusercontent.com/16250815/71502425-1db97c00-283e-11ea-8ee3-77ccc252a8e4.jpg)
![IMG_20191226_234346683](https://user-images.githubusercontent.com/16250815/71502426-1db97c00-283e-11ea-8ad7-f39cadff30b2.jpg)
![IMG_20191226_233949487](https://user-images.githubusercontent.com/16250815/71502427-1db97c00-283e-11ea-9212-91de21c401aa.jpg)

**Comment by TriggerMeister** [comment] 2019-12-27 21:54
Added a capacitor to the other printer today with the same setup.  No screen garbage so far (yeah!) on either printer.  I'm not sure why an updated/recompiled marlin after a PlatformIO update would cause more "noise" on the LCD. In a FB group someone suggested it may be caused by Intellisense and the way Marlin is compiled now after the update, which would make sense as I was not able to compile a working old version even after fixing the "upload_extra_script.py" of my previously working Marlin version.  

![IMG_20191227_150332427_BURST000_COVER_TOP](https://user-images.githubusercontent.com/16250815/71533832-01aeec80-28c9-11ea-9d59-d974cc03830f.jpg)
![IMG_20191227_140253490](https://user-images.githubusercontent.com/16250815/71533833-01aeec80-28c9-11ea-8c33-92e923eeb526.jpg)

**Comment by mtraven** [comment] 2019-12-29 21:14
Just wanted to add:  I had the same issue when upgrading to 2.0, never had the issue before.  Mine was able to be resolved in software by adding the following lines to config.h:
#define ST7920_DELAY_1 DELAY_NS(0)
#define ST7920_DELAY_2 DELAY_NS(250)
#define ST7920_DELAY_3 DELAY_NS(250)

This seems to be a fix from older version of marlin, but I never had any problems before 2.0

also, my screen did not look quite as bad as yours, so maybe there is a hardware variable to it.

mine was (and always has been) compiled by sloeber, which I am pretty sure just uses the arduino compiler, but maybe not.  I did upgrade sloeber recently, maybe that is what caused the screen glitch...

**Comment by TriggerMeister** [comment] 2019-12-29 22:34
One was worse than the other, but the capacitor solved it on both.  The delay occasionally helped, but the longer the printer ran the more likely it was going to come back.  Maybe the power converter to 5V is not as good as it is on other boards (e g. Re-arm).  Just weird that it started after a upgrade....

**Comment by mtraven** [comment] 2019-12-29 23:17
I am having other issues with 2.0 that led me to roll back to bugfix1.1.9.  Interestingly, the screen problem came back.  I guess I never flashed bugfix1.1.9, so I think the prev version I was running was just marlin 1.1.9.  Meaning the problem (for me) started at bugfix1.1.9.

The cap is a clever fix, but what exactly is it doing?  extending those delays in hardware?
also, what happens if they fix this is software, you would probably have to remove the caps, no?

it seems like, even though you have solved your problem, you still want to know what the root cause is?  I am in the same boat, feels like a band aid at this point, really would like to know exactly what changed.

**Comment by TriggerMeister** [comment] 2019-12-30 06:32
I do want to know what changed.  Frankly I would have been better off buying the TFT instead of wasting days on this.

Here is what I know:
1. I can't compile any old GitHub pulls and make it work like it used to.
2. PlatformIO changed and that forced me to get a new pull, otherwise I had compile errors.
3. If you use the USB power selection the LCD works fine.  
4. Adding a cap reduces the noise on the LCD power line and fixes the issue.

I KNOW it worked prior to this upgrade.  I don't think Marlin changed something, but there is a dependency that changed and Marlin needs to ensure that dependency is met.  I mean that the Platform IO is compiling differently and while it's fine for other boards the SKR seems to puke on the order possibly or how it is compiled.  This may throw off the timing and the LCD.... Just guessing.

No, I will not remove the cap.  There is no harm in keeping it even if Marlin is patched.  It's cheap insurance.

**Comment by Kaiwol1990** [comment] 2020-01-06 16:10
I had the same problem or at least a similar one. Mine display just worked fine if I unplugged it for a short time after marlin booted completely. For me the fix was to add the following lines to Configuration.h.

`#define ST7920_DELAY_1 DELAY_NS(0) `
`#define ST7920_DELAY_2 DELAY_NS(0)  `
`#define ST7920_DELAY_3 DELAY_NS(472)`


The 472 are from the [RepRap page](https://reprap.org/wiki/RepRapDiscount_Full_Graphic_Smart_Controller). There is noted a 63 which is for a 16 MHz MCU. Since the SKR 1.3 (I'm using) has 120 MHz, I scaled it up accordingly. This is due to a slow LCD as the mentioned on the page. 

I hope this helps some people. It may be a suitable fix to add a flag to the Configuration.h and then calculate the delay based on the MCU clock.   Something like:
`#define SLOW_LCD`

**Comment by TriggerMeister** [comment] 2020-01-07 02:00
> I had the same problem or at least a similar one. Mine display just worked fine if I unplugged it for a short time after marlin booted completely. For me the fix was to add the following lines to Configuration.h.
> 
> `#define ST7920_DELAY_1 DELAY_NS(0) `
> `#define ST7920_DELAY_2 DELAY_NS(0) `
> `#define ST7920_DELAY_3 DELAY_NS(472)`
> 
> The 472 are from the [RepRap page](https://reprap.org/wiki/RepRapDiscount_Full_Graphic_Smart_Controller). There is noted a 63 which is for a 16 MHz MCU. Since the SKR 1.3 (I'm using) has 120 MHz, I scaled it up accordingly. This is due to a slow LCD as the mentioned on the page.
> 
> I hope this helps some people. It may be a suitable fix to add a flag to the Configuration.h and then calculate the delay based on the MCU clock. Something like:
> `#define SLOW_LCD`

I think I went all the way up to 450, but then it ended coming back hours later.  So maybe I just stopped short???  I do believe that there is something with the power applied and the clock speed, as the displays worked fine on USB power.

**Comment by boelle** [comment] 2020-01-14 18:23
@TriggerMeister so this one is not solved yet? i saw some hardware mods and wonder if its a hardware problem rather than a marlin one

**Comment by TriggerMeister** [comment] 2020-01-14 22:56
I don't have more time to burn on this, but I think is very weird that so many people experienced this issue after an upgrade.  I guess nobody will try to figure out why this happened or try to trace it down.  I think it's tied to a dependency and the issue may not be directly in Marlin.  Thanks.

**Comment by italocjs** [comment] 2020-01-16 11:03
I can confirm that i have experienced the same issue, but on another board (ramps 1.4), with the same firmware i have burned dozens of times, so i guess it might be some update to the u8glib library that messed something up.  (arduino is the same, 1.8.10)

**Comment by boelle** [comment] 2020-01-21 15:29
what if vscode+platform.io extension is used?

arduino ide is filled with all sorts of options for errors

**Comment by italocjs** [comment] 2020-01-21 17:04
@boelle i'll compile it with vscode to see if it persists without adding the delays. its a good guess

**Comment by boelle** [comment] 2020-01-21 20:37
i also had all kind of problems with arduino ide, then i tried vscode and i have never looked back

**Comment by SajjadShooshtari** [comment] 2020-01-31 12:42
Hi
I changed the following data and my problem was resolved.
file:
Marlin-2.0.x\Marlin-2.0.x\Marlin\src\lcd\dogm\ultralcd_st7920_u8glib_rrd_AVR.h
line 44,45,46 :

#define ST7920_DELAY_1 DELAY_NS(0)
#define ST7920_DELAY_2 DELAY_NS(250)
#define ST7920_DELAY_3 DELAY_NS(250)

Good luck

**Comment by boelle** [comment] 2020-06-23 13:25
@TriggerMeister 

Please test the [bugfix-2.0.x branch](https://github.com/MarlinFirmware/Marlin/tree/bugfix-2.0.x) to see where it stands.

**Comment by sjasonsmith** [comment] 2020-07-04 07:50
Given the change that has occurred in Marlin since the last time this was active, I think it would be irresponsible to blindly apply new timings without having the hardware to test it.

Certainly many people are using these screens with new SKR (1.3 + 1.4) boards. If there is still a problem unique to SKR 1.1 boards, we'll need someone with the hardware to volunteer a bit of time to test a fix.

Given the silence and age of this issue, I'm going to close the issue. If you are still having to employ workarounds for this, please reply and we can re-open the issue and figure out an appropriate change to fix it.

**Closed as completed by sjasonsmith** 2020-07-04 07:50 UTC
Labels: Bug: Confirmed !, Fix Included
