### ISSUE TITLE
Not a issue but a question about thermal setting

### ISSUE THREAD

**Issue by budi67** [MarlinFirmware/Marlin#8654] opened 2017-12-04 14:39 UTC
Hello

I have modified my CR10 with an Aero Titan and a 50mm blower.
But the blower is to strong, when it engages, he lowers the temperature of almost 8 ° and a few second later the printer stops.

It's there a regulation in modifying to leave the time in the nozzle to go back up in temperature ?

A big thanks
Budi67

**Comment by Deneteus** [comment] 2017-12-04 14:49
It will only do that if you have not insulated your heat block with ceramic heater block cotton. Too much air is hitting the heater block rather than past the tip of the nozzle and the part.  https://www.amazon.com/gp/product/B01LAYCRAA?pf_rd_p=6d50e0ee-c639-41a8-91f7-8e1b816b5bf3&pf_rd_r=0NBT55ZQ71QG9EEY2CH8

**Comment by budi67** [comment] 2017-12-04 14:54
Thanks for your answer Deneteus, your link don't work.
I go even for this cotton

**Comment by Deneteus** [comment] 2017-12-04 14:55
Check this thread out. I fixed the link. For some reason, it wouldn't let me link the pic from Amazon.

http://forums.reprap.org/read.php?1,656519

**Comment by budi67** [comment] 2017-12-04 14:57
Thank you, I am going to read this thread.

**Comment by bjarchi** [comment] 2017-12-04 19:37
While I agree with @Deneteus about the root cause here - you should insulate your heat block and/or get your cooling air directed off of the block and onto the part - there is also some firmware configuration that might help get you up and running. I assume when the printer stops it's doing so because of a thermal runaway error?

**Comment by budi67** [comment] 2017-12-04 19:50
I am really stupid, I have one e3dv6 and I had not even put the shell in silicone, it is now done and the printings it passes marvelously.
Without you, I would not really have thought of it.
I am also going to revise the airflow

A big thanks !!

**Comment by bjarchi** [comment] 2017-12-09 21:38
@budi67 Sounds like everything is sorted then? If so, can you close the issue since it's resolved?

**Closed as completed** 2017-12-10 12:49 UTC
Labels: T: Question
