### ISSUE TITLE
Filament Width - Dual Extruder

### ISSUE THREAD

**Issue by boelle** [MarlinFirmware/Marlin#3838] opened 2016-05-25 11:22 UTC
_From @nio40k on May 18, 2016 15:35_

Please add the filament width sensor for a second extruder. thanks. :-)

_Copied from original issue: MarlinFirmware/MarlinDev#423_

**Comment by jbrazio** [comment] 2016-07-18 16:43
Duplicate of #3871

**Closed as completed by jbrazio** 2016-07-18 16:43 UTC
Labels: T: Feature Request
