### ISSUE TITLE
Firmware retract w/z-hop doesn't update Z position, firmware recover doesn't restore correct Z.

### ISSUE THREAD

**Issue by zarthcode** [MarlinFirmware/Marlin#10886] opened 2018-05-28 08:28 UTC
### Description

Firmware retract w/z-hop doesn't update Z position, firmware recover doesn't restore position.

### Steps to Reproduce
```gcode
M207 S6 F9000 Z1  ; G10 Retract settings
M208 S-0.05 F900 ; G11 Recover settings

G0 Z0; Move nozzle to bed
G10; Retract - Zhop occurs,
M114; Z is registered as still 0
G11; Recover occurs, but Z doesn't move back down!
```
**Expected behavior:**

G10 should update position
G11 should recover position

**Actual behavior:**

Non-existent layer adhesion. ;-)

#### Additional Information

Performed on latest bugfix, 5/28

**Comment by thinkyhead** [comment] 2018-05-28 10:15
Duplicate of #10200

**Comment by thinkyhead** [comment] 2018-05-28 10:15
Please ZIP up your `Configuration.h` and `Configuration_adv.h` files (as requested in the Issue template) and drop them into your next reply.

**Comment by zarthcode** [comment] 2018-05-29 17:35
Config placed into #10200, also referenced a potential fix there, as well - I seem to have both UBL and fwretract working. (Can't make a pull request, atm - should be able to cherry pick it, or just see if the general idea passes muster.)

**Comment by thinkyhead** [comment] 2018-05-29 17:37
Thanks @zarthcode — We like potential fixes!

**Comment by thinkyhead** [comment] 2018-05-30 04:44
As the patch totally fixes your issue I'll close this. If it crops up again we'll hit it with a bigger stick!

**Closed as completed by thinkyhead** 2018-05-30 04:44 UTC
Labels: Bug: Confirmed !, S: Solved
