### ISSUE TITLE
Extruder dosn't stop

### ISSUE THREAD

**Issue by dudman** [MarlinFirmware/Marlin#12842] opened 2019-01-06 23:12 UTC
### Description
The extrude once started just dosn't stop, this has just started since I uploaded a new firmware to change the PID's of the heated bed. Before hand I've been printing fine. Have double checked the changes to code, and can't find anything different, let alone think what config changes might have changed this. I've tried plugging in a different stepper motor, and the same behavior is there.

version 010100

[semd.zip](https://github.com/MarlinFirmware/Marlin/files/2730979/semd.zip)

**Comment by thinkyhead** [comment] 2019-01-07 00:02
Please test the `bugfix-2.0.x` branch to see where it stands. If the problem has been resolved then we can close this issue. If the issue isn't resolved yet, then we should investigate further.

**Comment by boelle** [comment] 2019-02-21 21:21
@dudman problem fixed?

**Closed as completed** 2019-03-03 14:39 UTC
