### ISSUE TITLE
[BUG] (Failed Compile)

### ISSUE THREAD

**Issue by orbela** [MarlinFirmware/Marlin#21432] opened 2021-03-24 09:00 UTC
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

In file included from Marlin\src\lcd\menu\menu_advanced.cpp:31:0:
Marlin\src\lcd\menu\menu_advanced.cpp: In function 'void menu_advanced_temperature()':
Marlin\src\lcd\menu\menu_item.h:261:40: error: no matching function for call to 'TMenuEditItem<MenuEditItemInfo_int3>::action(const char* const&, float*, int, uint16_t)'
     MenuItem_##TYPE::action(plabel, ##V);                      \
                                        ^
Marlin\src\lcd\menu\menu_item.h:272:5: note: in expansion of macro '_MENU_INNER_P'
     _MENU_INNER_P(TYPE, ##V);         \
     ^~~~~~~~~~~~~

### Bug Timeline

Old Issue 

### Version of Marlin Firmware

Marlin bugfix-2.0.x

### Printer model

Creality Ender 3 

### Electronics

BTT SKR MINI E3 V2.0

### Your Slicer

Cura

I haven't made any changes this is straight from Bugfix-2.0.x
I read this was an issue but it said it was fixed. How can I fix this?

**Comment by ellensp** [comment] 2021-03-24 09:12
Duplicate of https://github.com/MarlinFirmware/Marlin/issues/21428

**Closed as completed by ellensp** 2021-03-24 09:12 UTC
