### ISSUE TITLE
[FR] Enable Caribou3d/LDO OLED 2004 Display Support

### ISSUE THREAD

**Issue by jbyerline** [MarlinFirmware/Marlin#24838] opened 2022-10-06 20:24 UTC
### Is your feature request related to a problem? Please describe.

Currently if you plug in the Caribou3D OLED display with the Generic Discount Rep Rap 2004 LCD enabled, the screen will work initially but then once you change menus, the display will show random characters. The only way to get rid of these characters is to reboot the printer. This makes this display basically unusable as is.

### Are you looking for hardware support?

Looking to add support for OLED 2004 Display by Caribou3d + LDO for Ramps 1.4 and Einsy Rambo mainboards.

[Link to screen](https://caribou3d.com/en/electronic-boards-displays/67-oled-display-20x4-white-black-by-ldo.html)

### Describe the feature you want

The OLED screen has been made to work on modified versions of Marlin 1.0 for Prusa printers. I am not well versed in screens but I believe it has something to do with the difference in refresh rate for OLED vs LCD. This screen looks very sleek and could be an easy swap if the option was available for all Marlin printers. 

Here is a [Link](https://github.com/Caribou3d/CaribouMK3s-Firmware/blob/Caribou-MK3/Firmware/lcd.cpp) to the Caribou3d firmware that referenced the 2004 OLED.

### Additional context

[Data Sheet for 2004 OLED](https://datasheetspdf.com/pdf-file/1110077/ETC/WS0010/1)

**Comment by thisiskeithb** [comment] 2022-10-07 00:21
Duplicate of https://github.com/MarlinFirmware/Marlin/issues/18083

**Closed as completed by thisiskeithb** 2022-10-07 00:21 UTC
Labels: T: Feature Request
