### ISSUE TITLE
[Question] Request a Feature - want to dev on marlin

### ISSUE THREAD

**Issue by tuyiwen** [MarlinFirmware/Marlin#14651] opened 2019-07-17 09:39 UTC
If I want to further develop marlin, what software should I use?

**Comment by EvilGremlin** [comment] 2019-07-17 10:04
Whatever you can.

**Comment by Ketchu13** [comment] 2019-07-17 10:06
@tuyiwen 
Hello did your read this ?
[How to build Marlin](https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/README.md)

## Building Marlin 2.0

To build Marlin 2.0 you'll need [Arduino IDE 1.8.8 or newer](https://www.arduino.cc/en/main/software) or [PlatformIO](http://docs.platformio.org/en/latest/ide.html#platformio-ide). We've posted detailed instructions on [Building Marlin with Arduino](http://marlinfw.org/docs/basics/install_arduino.html) and [Building Marlin with PlatformIO for ReArm](http://marlinfw.org/docs/basics/install_rearm.html) (which applies well to other 32-bit boards).

_Edit: fix bad link_

**Comment by RudyBenner** [comment] 2019-07-17 11:19
https://github.com/MarlinFirmware/Marlin/issues/bugfix-2.0.x/README.md

seems to be a bad link.

**Comment by boelle** [comment] 2019-07-21 01:32
We're not a support group
This Issue Queue is for Marlin bug reports and development-related
issues, and we prefer not to handle user-support questions here. (As
noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/
1.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-ijust-have-a-question).) For best results getting help with configuration
and troubleshooting, please use the following resources:
RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
[Tom's 3D Forums](https://discuss.toms3d.org/)
Facebook Group ["Marlin Firmware"](https://www.facebook.com/
groups/1049718498464482/)
Facebook Group ["Marlin Firmware for 3D Printers"](https://
www.facebook.com/groups/3Dtechtalk/)
[Marlin Configuration](https://www.youtube.com/results?
search_query=marlin+configuration) on YouTube
Marlin Discord server. Join link: https://discord.gg/n5NJ59y
After seeking help from the community, if the consensus points to to a
bug in Marlin, then you should post a [bug report](https://github.com/
MarlinFirmware/Marlin/issues/new/choose).

**Comment by boelle** [comment] 2019-09-24 19:59
will close this one as its not a bug

please use the following resources:

-RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
-[Tom's 3D Forums](https://forum.toms3d.org/)
-Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
-Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
-[Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
-Marlin Discord server. Join link: https://discord.gg/n5NJ59y

**Closed as completed by boelle** 2019-09-24 19:59 UTC
Labels: T: Question
