### ISSUE TITLE
Compile Error SOLVED

### ISSUE THREAD

**Issue by DirtyDerv** [MarlinFirmware/Marlin#8530] opened 2017-11-23 15:17 UTC
When i try to compile the firmware to load onto the delta i get this error 

```
In file included from sketch\ubl.h:29:0,

                 from sketch\G26_Mesh_Validation_Tool.cpp:31:

sketch\Marlin.h: In function 'bool position_is_reachable_by_probe(const float&, const float&)':

Marlin.h:479: error: expected primary-expression before ')' token

         && position_is_reachable(rx - X_PROBE_OFFSET_FROM_EXTRUDER, ry - Y_PROBE_OFFSET_FROM_EXTRUDER);

                                                                                                      ^

exit status 1
expected primary-expression before ')' token
```

Im not sure what it wants and ive not had this before

ive inclued my configuration files
[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/1499630/Marlin.zip)

**Comment by teemuatlut** [comment] 2017-11-23 15:59
If you've solved this already, then please close the issue.

If not, the problem is that your `Y_PROBE_OFFSET_FROM_EXTRUDER` is missing a value in `configuration.h` on line 757.

**Closed as completed** 2017-11-23 16:20 UTC
