### ISSUE TITLE
[BUG] EDGE_STEPPING removes step signal on Z, but works on Z2, result is noise and missing steps

### ISSUE THREAD

**Issue by moriamoria** [MarlinFirmware/Marlin#27489] opened 2024-10-22 22:32 UTC
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Hello,

I have an ortur 3d printer with an upgrade skr 1.3 motherboard.

Z uses driver 2209, Z2 stepper uses E1 stepper driver 2209.

When  #define EDGE_STEPPING, I have a good signal on Z2, but nothing on Z.

Result Z2 stepper force on Z and create noise, and missing step.

Following the data scope from Z in yellow, Z2 in green 

![edge spepping activated](https://github.com/user-attachments/assets/6f69e1df-6022-487b-be51-0f43d1d2262c)

if I comment //#define EDGE_STEPPING then I have good signal, but not square

![edge stteping deactivated](https://github.com/user-attachments/assets/c3963396-2cc8-49c9-87cb-771ba61f2191)

notice that on branch 4.2.1.2, when I activate #define SQUARE_WAVE_STEPPING, I have the same result, no signal on Z scope signal.

Thanks helping me to solve this issue.

Regards to all

### Bug Timeline

all bugfix 2.1.X commit suffer from this issue

### Expected behavior

Move Z and Z2 synchrone.

### Actual behavior

The Z2 stepper force on Z stepper

### Steps to Reproduce

#define SQUARE_WAVE_STEPPING
move Z
[Marlin.zip](https://github.com/user-attachments/files/17482744/Marlin.zip)

### Version of Marlin Firmware

Bugfig 2.1.2. [cron] Bump distribution date (2024-10-21)

### Printer model

ortur, Z and Z2 connected

### Electronics

skr 1.3, 2209 on Z,Z2, 

### LCD/Controller

REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER

### Other add-ons

2209

### Bed Leveling

ABL Linear grid

### Your Slicer

Cura

### Host Software

SD Card (headless)

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.
[Marlin.zip](https://github.com/user-attachments/files/17482744/Marlin.zip)

**Comment by ellensp** [comment] 2024-10-23 00:49
Provided Configs has //#define Y_DRIVER_TYPE  TMC2209 which mean that Y is disabled, is this deliberate?

**Comment by anomalchik** [comment] 2024-10-23 06:18
I think this should have been written in the previous thread, and don't create new one.

**Comment by moriamoria** [comment] 2024-10-23 06:45
Hello,

I have recreate a new issue because in the LIN_ADVANCE issue I have raise before, someone ask me to recreate an issue with the good subject.

Regarding Y, I use a close loop driver mks 42C

![image](https://github.com/user-attachments/assets/21c539a4-bba8-4a19-8ecc-e7d82c337577)

Regards

**Comment by ellensp** [comment] 2024-10-23 07:11
issue https://github.com/MarlinFirmware/Marlin/issues/27341 does seem to be the same issue
https://github.com/MarlinFirmware/Marlin/issues/27457 however is specifically talking about LIN_ADVANCE vs EDGE_STEPPING

**Comment by anomalchik** [comment] 2024-10-23 19:32
@tombrazier I set #define OLD_ADAPTIVE_MULTISTEPPING and it didn't bring any results.

**Comment by tombrazier** [comment] 2024-11-04 09:01
> issue #27341 does seem to be the same issue #27457 however is specifically talking about LIN_ADVANCE vs EDGE_STEPPING

@moriamoria, the OP of #27457, discovered that LIN_ADVANCE as not the cause after all. This issue, therefore, is a duplicate but without any confusing references to LIN_ADVANCE. I plan to close #27457 unless anyone objects.

#27341 does also seem to be a duplicate.

**Comment by thisiskeithb** [comment] 2024-11-05 20:08
Closing this issue in favor of https://github.com/MarlinFirmware/Marlin/issues/27341 since it's older & there's more discussion over there.

**Closed as completed by thisiskeithb** 2024-11-05 20:08 UTC
Labels: Bug: Confirmed !, T: HAL & APIs, A: LPC176x
