### ISSUE TITLE
[BUG] GTM32 PRO SD EEPROM Emulation does not work

### ISSUE THREAD

**Issue by AluOne** [MarlinFirmware/Marlin#14560] opened 2019-07-09 21:35 UTC
### Description

SD EEPROM emulation from #14261 does not work since PR #14458

can't read or write settings

**Comment by tpruvot** [comment] 2019-08-02 09:24
Merged PR #14809 could have fixed your issue... Also, ensure you have at least one gcode file on the sdcard, else there is a problem to open the folder handle... in the shared base sdcard class

**Comment by AluOne** [comment] 2019-08-05 18:55
I test a new version of today.
I can compile everything, but the machine hangs after booting.

**Comment by boelle** [comment] 2019-09-24 14:14
@AluOne so the issue is still there?

**Comment by boelle** [comment] 2019-10-12 10:54
Lack of Activity
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.

**Closed as completed by boelle** 2019-10-12 10:54 UTC
