### ISSUE TITLE
[BUG] Z-Probe Offset Wizard works errornously when printer has Z-endstop and BL-Touch

### ISSUE THREAD

**Issue by TzOk83** [MarlinFirmware/Marlin#25550] opened 2023-03-22 09:46 UTC
### Did you test the latest `bugfix-2.1.x` code?

No, but I will test it now!

### Bug Description

I have an Ender 3 with Creality 4.2.7 board and BL-Touch probe. Z-endstop is used for homing, while BL-Touch is supposed to be used only for offsets. Each time I use Z-Probe Offset Calibration Wizard, I end up with a different Z-Offset, even if I set 0 in the Wizard. The printer starts to print in the air after a few consecutive runs of Z-Probe Offset Calibration Wizard. I'm using Marlin 2.1.1 stable release, but haven't seen any changes in the Z-Probe Offset Wizard code since that release.

### Bug Timeline

Old issue, alway was there.

### Expected behavior

Setting Offset to 0 in the Wizard, shouldn't change Z-Probe Offset in the general Settings.

### Actual behavior

Setting the offset to 0 adds a small value to Z-Probe Offset. Error accumulates after each calling of the Wizard.

### Steps to Reproduce

1. Manually level the bed.
2. Call the Z-Probe Offset Wizard.
3. Go to 0 mm.
4. Note the Z-Probe Offset.
5. Call the Z-Probe Offset Wizard again.
6. Go to 0 mm.
7. Compare the Z-Probe Offset with noted in step 4.

### Version of Marlin Firmware

2.1.1

### Printer model

Ender 3

### Electronics

Creality 4.2.7

### Add-ons

BL-Touch

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Cura

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/11038598/Marlin.zip)

**Comment by thisiskeithb** [comment] 2023-03-22 10:36
Duplicate of https://github.com/MarlinFirmware/Marlin/issues/25222

**Closed as completed by thisiskeithb** 2023-03-22 10:36 UTC
