### ISSUE TITLE
Switching extruders with two steppers

### ISSUE THREAD

**Issue by chromvis** [MarlinFirmware/Marlin#6435] opened 2017-04-24 01:24 UTC
Currently `SWITCHING_EXTRUDERS` only work with one stepper. How to modify (I believe Marlin_Main.cpp) soft to allow two stepper operation? It is very simple to make swinging extruder system from Dual Nozzle MK8 Extruder kit. Switching allow to set hotend offsets and there is no need for very careful and tedious hotend alignment, but how to control second stepper? 
It would be good to include option for TWO STEPPERS switching extruder.

**Comment by Tannoo** [comment] 2017-04-24 10:15
>Currently SWITCHING_EXTRUDERS only work with one stepper.

..at a time, I believe.

**Comment by thinkyhead** [comment] 2017-04-26 04:50
This is a duplicate of #6260 (which implements your request).

**Closed as completed by thinkyhead** 2017-04-26 04:50 UTC
Labels: T: Feature Request

**Comment by thinkyhead** [comment] 2017-04-26 04:51
> ..at a time, I believe.

@chromvis is correct. It uses a single stepper motor, but two nozzles.
