### ISSUE TITLE
[BUG] TMC5160 is compiling without errors without CS pins defined

### ISSUE THREAD

**Issue by Svatevit** [MarlinFirmware/Marlin#13734] opened 2019-04-17 07:36 UTC
### Description

I just installed TMC5160 on E0 and tried to compile firmware. It did without errors, but it's not working. When I changed E0 to TMC2130 in code, it says I don't have CS E0 pin defined.

### Steps to Reproduce

Remove/comment E0_CS_PIN from pin definitions, set TMC5160 as driver for E0.

**Expected behavior:** [E0_CS_PIN not defined error]

**Actual behavior:** [Compilation finishes succesfuly, printer dead]

**Comment by teemuatlut** [comment] 2019-04-17 17:38
Yea looks like the sanitychecks are only for TMC2130.
If you don't define it, Marlin will assign `-1` for the pin and there won't be a compile error from a missing define.

**Comment by boelle** [comment] 2019-07-21 19:09
Lack of Activity
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.

**Comment by InsanityAutomation** [comment] 2019-07-23 15:53
This may be valid as some installations bring the pin directly to ground instead of software controlling it to make it work from my understanding. @teemuatlut In your opinion should a sanity check be added?

**Comment by boelle** [comment] 2019-10-12 11:17
i would say a sanity check should be added

**Comment by boelle** [comment] 2019-10-24 11:12
i add the confirmed label as it seems pretty clear that we need the sanity check

**Comment by boelle** [comment] 2019-11-09 08:55
@thinkyhead @shitcreek @teemuatlut would a sanity check not "solve" this one?

**Comment by boelle** [comment] 2019-12-02 21:42
@thinkyhead @shitcreek @teemuatlut would a sanity check not "solve" this one?

**Comment by boelle** [comment] 2019-12-07 14:19
@Svatevit since 2.0 was just released a few days ago has this changed this issue at all?

**Comment by boelle** [comment] 2020-01-10 16:41
pr has been merged so should be fixed

**Closed as completed by boelle** 2020-01-10 16:41 UTC
Labels: Bug: Confirmed !
