### ISSUE TITLE
[ABL] (ABL leveling does ony compensate half of it)

### ISSUE THREAD

**Issue by kampfhase7** [MarlinFirmware/Marlin#20614] opened 2020-12-31 14:35 UTC
### Bug Description

I have changed the config for the orginal creality BL-Touch V3.1. All is working fine. But in the print after leveling via G29, the Z axix is moving only a half of the vaules from the BL-Touch. 
Example: BL-Touch probing the bed. X-10 to X+10 it haves a height difference of 1mm. While Printing, Z only moves this way only 0.5mm. But have to moving 1mm up. Im using Bugfix branche on my Ender 3v2 with board v4.2.2. 

Im using bilinear leveling

### Configuration Files
[configs.zip](https://github.com/MarlinFirmware/Marlin/files/5757488/configs.zip)

**Comment by FanDjango** [comment] 2020-12-31 14:42
You have `#define ENABLE_LEVELING_FADE_HEIGHT`. Check that the default of 10 isn't changed anywhere in the start gcode. That could cause less correction at a low height.

**Comment by thisiskeithb** [comment] 2020-12-31 17:26
Whenever there are homing or leveling issues, we now ask everyone to follow a standard procedure to gather more information:

- Download Marlin [`bugfix-2.0.x`](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.0.x.zip) to test with the latest code.
- Enable `DEBUG_LEVELING_FEATURE` and `M114_DETAIL` and re-flash the firmware.
- Connect to your printer from host software such as Cura, Printrun or Repetier Host.
- Send `M502` and `M500` to ensure your Configurations are applied.
- Issue the command `M111 S247` to enable maximum logging.
- Perform a `G28` to do your standard homing procedure.
- Do a `G29` to probe the bed. This will also enable bed leveling.
- Do some of the moves that revealed problems before. Take notes.
- Copy the log output into a **.TXT file** and attach it to your next reply.

Repeat this procedure, if needed, to demonstrate inconsistencies. From these logs we should hopefully get a better idea of what's going on with your machine.

**Comment by thestephenmarshall** [comment] 2021-01-07 19:45
Check that your motor currents for each stepper are identical. https://marlinfw.org/docs/gcode/M906.html

e.g. `M906 I1 Z800` + `M906 Z800`.

**Comment by domhardt** [comment] 2021-01-10 22:29
I configured and compiled the latest bugfix version and followed the instructions. Please find the log file and my configuration files attached. The printer still does not fully compensate for the offset measured by the BLTouch.

[Update]
Here is my start gCode just to make sure the fade height is the 10mm default:

`; BEGIN PrusaSlicer Custom Start G-Code version 2021-01-09
M117 Heating bed ...
M104 S[first_layer_temperature] ; set extruder temp
M140 S[first_layer_bed_temperature] ; set bed temp

G90 ; use absolute coordinates
M83 ; extruder relative mode
M106 S0 ;Turn-off fan

G28 X0 Y0 ; home x & y

M190 R[first_layer_bed_temperature] ; wait for bed temp

M117 Probing bed ...
G28 Z0 ; home z 
G29 ; auto bed mesh leveling
M420 S1 Z10.0 ; set z fade height
G0 X0 Y0 Z5 F10000.0; move to start

M109 R[first_layer_temperature] ; wait for extruder temp
M117 Purging nozzle ...
G0 F100 E15 ;extrude some material to purge the nozzle

M117 Starting print ...
; END PrusaSlicer Custom Start G-Code`

[Log+Config.zip](https://github.com/MarlinFirmware/Marlin/files/5793403/Log%2BConfig.zip)

**Comment by thestephenmarshall** [comment] 2021-01-11 18:38
**Mesh validation prints perfectly...**

I've been chasing this issue for a year now with some resolve only to have it pop right back up again. SKR v1.3 + TMC2209 drivers. I've tweaked everything in the firmware, blueprinted everything in the hardware and still out of nowhere the bug is back again. Let me just leave this information here: 

- Billinear leveling
- 3 x 3 grid
- 3 point bed and carriage mounts
- BL Touch v3.1
- `G26 H260 B100 L0.2` - mesh validation prints perfectly
- Print from the attached gcode sliced in Cura or Prusa Slicer - left side is too high every single time
- Manually adjust the the mesh `M421` on the left side - no difference (how??) - yes, I saved the mesh
- Yes, I have `M420 S1 Z10` at the start of my prints
- Octoprint latest on Raspberry Pi 4
- Print from SD - no difference, too high on left side
- `G34` - 0.0 difference left to right
- Probe repeatability test so many times I need a tattoo now - it passes every time

Has anyone ran the mesh validation command from the above list (using your own temperatures of course) and found the result to be perfect yet any gcode you print (please try mine) is borked? 

I don't know a lot about the languages that compose this firmware, but can anyone point me to where I can start to learn how ABL works? What's a good starting point? I feel like, from all of my testing, ABL is simply not compensating correctly even though it is most definitely working as I marked the lead screw couplers with a chalk pen and can see them moving as I would expect. Yes, I also did check those for snugness and well and most certainly cannot move the lead screws inside of their couplers. 

As a workaround, I have printed the attached calibration circle (100mm) in the center of the bed and simply paused the print then turned off the motors to manually adjust the left side down enough to make a decent first layer. This is a hack and I do not like it. 

**Why is it that I can run the G26 mesh validation and get perfect results but garbage results when I run the attached GCODE file?**


![IMG_2183](https://user-images.githubusercontent.com/2293844/104223611-7b007b00-5409-11eb-8081-41ec6b970963.jpg)

GCODE:
[100mm-cal-circle.gcode.zip](https://github.com/MarlinFirmware/Marlin/files/5797670/100mm-cal-circle.gcode.zip)

**Comment by NastyEwok** [comment] 2021-02-17 13:41
I seem to be experiencing similar issues.

Ill get some data together and post it

**Comment by thestephenmarshall** [comment] 2021-04-08 15:43
Let's not close this. The issue persists with a COMPLETELY NEW machine using an inductive probe and spring steel plate. I'm convinced the issue is either the LPC1768 SKR v1.3 hardware or Marlin's handling around said hardware (other hardware as well?). I am in no position to fix anything within this repo as it is not my area of coding expertise, but I will provide logs if need be despite the fact that multiple issues have been opened on this topic. I have yet to see any convincing results from others who have provided logs within this or other issues. That being said, again, I would love to know why `G26` produces perfect ABL results while prints which enable this starting GCODE:

```
G28;
G29;
M500;
M501;
M420 S1 Z1;
```

exhibit the *exact same results described in this and other tickets*. Thoughts?

**Comment by hamster65** [comment] 2021-04-08 19:24
Does your printer do anything different when running gcode and mesh validation? Different motor currents, homing procedure, more/less faster/slower z movements?

To rule out a couple of things, you could try
- A different slicer
- disable fade height
- swith on / off interpolation
- enable / disable extrapolate beyond grid
- enable / disable subdivision
- UBL instead of ABL

I had better results with UBL, tested Klipper (levelling worked) and switched back to Marlinßßß. Testing will continue once I have access to my printer again and more time.

**Comment by thestephenmarshall** [comment] 2021-04-13 20:32
@hamster65 when I try to enable UBL I get only 1 point then it says it's done. I will try again bc iirc UBL worked much better than billinear.

**Comment by thestephenmarshall** [comment] 2021-04-14 01:32
Figured that out, but with UBL now the problem side is the back instead of the right side of the bed. 🤷‍♂️

~~Using mesh bed leveling as a workaround. Can't spend any more time on this unfortunately.~~

Go figure after I say I can't spend any more time... I figured out what I've been doing wrong the whole damn time:

https://gist.github.com/thestephenmarshall/6e2a09e6e64ccdfd646246d8330ccc88

The diff above shows the changes that fixed the issue and it was all my fault. The true size of my bed (not the printable only portion) is actually 220 x 220. After properly setting up the margins, max bed size and `X_MIN_POS`, `Y_MIN_POS` along with running Level Corners, I am **finally** getting Bilinear to work as expected. [See these lines](https://gist.github.com/thestephenmarshall/6e2a09e6e64ccdfd646246d8330ccc88#file-machine-diff-L36-L51) and [these lines](https://gist.github.com/thestephenmarshall/6e2a09e6e64ccdfd646246d8330ccc88#file-machine-diff-L108-L115).

Side note: after you turn your machine off, you might have to either run `G34` to re-level your gantry or manually adjust it if you are not running dual Z in your config. This ensures you get a flat mesh compared to a tilted one when you know the bed is level via Level Corners feature.

I will leave with this closing statement. Be careful what tutorials you choose to follow as the devil is in the details when it comes to setting up your machine. I've seen a few folks suggesting to use the printable area as the bed size and that, from what I can tell, is incorrect. Also, I do sort of doubt that having an un-level bed to begin with (mine was too high in the back) will make ABL work any better. Hopefully this helps someone. Last bit of advice: when setting the `NOZZLE_TO_PROBE_OFFSET` be sure to get out that ruler and make sure that the coordinates that show on your LCD screen match what you measure X and Y. If they do not, you need to correct your offsets. Gotta learn somehow 🤷‍♂️

**Comment by GdLakeIoT** [comment] 2021-04-27 18:29
Not sure this is the same, but I have a version of Bug-Fix2.x that will correctly compensate bead leveling. The version I have is from Oct 2 2020

**Closed as completed** 2022-04-21 18:52 UTC
Labels: Bug? False Alarm
