### ISSUE TITLE
[FR] Different acceleration and deceleration

### ISSUE THREAD

**Issue by espr14** [MarlinFirmware/Marlin#26354] opened 2023-10-19 17:27 UTC
### Describe the feature you want

During acceleration motors have to overcome inertia as well as friction. On the other hand, during deceleration friction helps to stop. So the deceleration can be significantly higher which decreases printing time.

**Comment by thisiskeithb** [comment] 2023-10-19 19:17
Duplicate of #13426

**Closed as completed by thisiskeithb** 2023-10-19 19:17 UTC
Labels: T: Feature Request
