### ISSUE TITLE
stop print won't disable the steppers 

### ISSUE THREAD

**Issue by amedsoprano** [MarlinFirmware/Marlin#8875] opened 2017-12-23 18:16 UTC
I have a tevo tornado and in the stock firmware whenever i press stop print under the lcd menu the steppers are immediately released so i can pull the print away from the hot nozzle. i recently updated to the new v1.1.7 and that isn't working anymore. when i press stop, it just stops right there and i cannot pull the bed because all the steppers are still enabled.

[Tornado_Marlin-1.1.7.zip](https://github.com/MarlinFirmware/Marlin/files/1584348/Tornado_Marlin-1.1.7.zip)
[Tornado Firmware.zip](https://github.com/MarlinFirmware/Marlin/files/1584349/Tornado.Firmware.zip)

 it would also be nice to have an option to move the head out of the way when stopping (like PARK_HEAD_ON_PAUSE, but on stop)

**Comment by revilor** [comment] 2017-12-24 16:27
As far as I can tell the described  behavior is related to activating ADVANCED_PAUSE_FEATURE. In case ADVANCED_PAUSE_FEATURE is enabled the steppers will not be disabled when the printer is idle. Someone more involved in the Marlin development will have to tell if this is a bug or a feature.

**Comment by amedsoprano** [comment] 2017-12-24 16:36
i checked on the stock firmware (the one that does disable the steppers on stop) and the advanced pause settings are the same.

**Comment by revilor** [comment] 2017-12-24 18:23
I'm referring to the files you attached. In Configuration_adv.h from Tornado-Firmware.zip ADVANCED_PAUSE_FEATURE is not enabled (Configuration_adv.h Line 787), but it is in the one from Tornado_Marlin-1.1.7.zip (Configuration_adv.h Line 878)

**Comment by amedsoprano** [comment] 2017-12-24 18:47
I just read that again and it is commented, I'll test that as soon as I finish this print. I also found a setting called SD_FINISHED_STEPPERRELEASE while looking for the advanced pause, lol. I'll check that out as well when I get home.

**Comment by thinkyhead** [comment] 2017-12-25 02:28
When `SD_FINISHED_STEPPERRELEASE` is set to `true` it should cause the G-code in `SD_FINISHED_RELEASECOMMAND` to be executed 1/2 second after any quick-stop of the steppers, as with Stop Print.

**Comment by amedsoprano** [comment] 2017-12-28 18:21
I disabled advanced pause and it still doesn't disable the steppers on stop, so that isn't the cause.
SD_FINISHED_STEPPERRELEASE is set to true and it doesn't work either.

**Comment by thinkyhead** [comment] 2017-12-31 06:22
@amedsoprano Does `M18` work to turn them off? And if `M18 S2` used to set the stepper off timer (for example) does that cause the steppers to turn off after 2 seconds?

**Comment by amedsoprano** [comment] 2017-12-31 06:36
both `M18` and `M84` work with or without the `S` attribute

**Comment by msutas** [comment] 2018-03-21 11:35
I have the same issue with Marlin 1.1.8

**Comment by thinkyhead** [comment] 2018-03-29 04:22
Please test with the latest `bugfix-1.1.x` (and/or `bugfix-2.0.x`) branch to see where it stands. If the problem has been resolved then we can close this issue. If you still see the bad behavior we should investigate further.

**Comment by amedsoprano** [comment] 2018-04-08 02:47
it hasn't.
Sorry for the long wait, i've been busy upgrading to TMCs .

**Comment by thinkyhead** [comment] 2018-04-08 04:55
It appears that this is by design, to prevent things like a delta falling on the print.

**Comment by dgrat** [comment] 2018-07-06 10:13
I can believe that this behavior has an intention, but it is just annoying. Is there a fix to restore the old behavior? Is it advisable to set `DEFAULT_STEPPER_DEACTIVE_TIME` to a low value? I am sceptical :(

**Comment by thinkyhead** [comment] 2018-07-07 04:12
Current code appears to always disable all steppers:
```cpp
void CardReader::printingHasFinished() {
  planner.synchronize();
  file.close();
  if (file_subcall_ctr > 0) { // Heading up to a parent file that called current as a procedure.
    . . .
  }
  else {
    . . .
    #if ENABLED(SD_FINISHED_STEPPERRELEASE) && defined(SD_FINISHED_RELEASECOMMAND)
      planner.finish_and_disable();
    #endif
    . . .
  }
}

void Planner::finish_and_disable() {
  while (has_blocks_queued() || cleaning_buffer_counter) idle();
  disable_all_steppers();
}
```

**Comment by boelle** [comment] 2019-02-19 23:46
@amedsoprano do you still have an issue?

**Comment by boelle** [comment] 2019-03-06 11:01
@thinkyhead i think we can close this one

**Comment by Phr3d13** [comment] 2019-06-10 21:54
@thinkyhead Another one that needs to be closed. Sorry, I got bored.

**Comment by boelle** [comment] 2019-06-22 09:19
@thinkyhead Another one that needs to be closed. Sorry, I got bored.

**Closed as completed** 2019-07-06 04:00 UTC
