### ISSUE TITLE
[BUG] TFT_LVGL_UI can not compiled with setting MKS Wifi Modul

### ISSUE THREAD

**Issue by Liriel-666** [MarlinFirmware/Marlin#21601] opened 2021-04-12 14:28 UTC
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

Everytime i Use TFT_LVGL_UI and try to compile it with MKS Wifi Modul it give out this error

"
Compiling .pio\build\mks_robin_nano_v3\src\src\MarlinCore.cpp.o
Compiling .pio\build\mks_robin_nano_v3\src\src\core\serial.cpp.o
In file included from Marlin\src\lcd/extui/lib/mks_ui/draw_ui.h:84,
                 from Marlin\src\MarlinCore.cpp:72:
Marlin\src\lcd/extui/lib/mks_ui/wifiSerial.h:38:10: fatal error: libmaple/libmaple_types.h: No such file or directory
   38 | #include <libmaple/libmaple_types.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
*** [.pio\build\mks_robin_nano_v3\src\src\MarlinCore.cpp.o] Error 1
==================================================================== [FAILED] Took 813.30 seconds ====================================================================
Environment        Status    Duration
-----------------  --------  ------------
mks_robin_nano_v3  FAILED    00:13:33.296
=============================================================== 1 failed, 0 succeeded in 00:13:33.296 ===============================================================
The terminal process "C:\Users\Dark-\.platformio\penv\Scripts\platformio.exe 'run'" terminated with exit code: 1.
"

I think it is this error
Marlin\src\lcd/extui/lib/mks_ui/wifiSerial.h:38:10: fatal error: libmaple/libmaple_types.h: No such file or directory
   38 | #include <libmaple/libmaple_types.h>
this libmaple_types.h doesnt exist

### Bug Timeline

04.04.2021

### Expected behavior

it should compile without a problem

### Actual behavior

compile stoped

### Steps to Reproduce

Activate both and press build
#define TFT_LVGL_UI

#if ENABLED(TFT_LVGL_UI)
  #define MKS_WIFI_MODULE  // MKS WiFi module
#endif

### Version of Marlin Firmware

marlin2.0.X Bugfix from 10.04.2021

### Electronics

MKS Robin Nano V3

### Add-ons

3d Touch (bltouch clone) and MKS Wifi Modul

**Comment by ellensp** [comment] 2021-04-13 02:32
Duplicate of https://github.com/MarlinFirmware/Marlin/issues/21069

**Closed as completed by ellensp** 2021-04-13 02:32 UTC
