### ISSUE TITLE
[BUG] Software endstops are ignored

### ISSUE THREAD

**Issue by phate191** [MarlinFirmware/Marlin#16373] opened 2019-12-29 01:21 UTC
### Bug Description

After Homing with Software Endostops enabled, you can move out of the software endostops boundaries.

### My Configurations

Ender 3 Pro
Version 2.0.1, commit 432decd513f14d8b50ca4fec8b53e8cd9ff825b6
[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/4007646/Marlin.zip)

### Steps to Reproduce

1. M211 //Check if Software Endsotops are Enabled
2. Home XY [G91 | G28 X0 Y0 | G90]
3. M211 //Check, Still Enabled
4. G1 Y-1 F4000 // Move Y and the axis move without problem...

With Software Endstops enabled the axes after home should be stopped to go below MIN_SOFTWARE_ENDSTOP_*

From Octoprint Terminal:
> Send: M211
> Recv: echo:Soft endstops: ON  Min:  X0.00 Y0.00 Z0.00   Max:  X235.00 Y235.00 Z250.00
> Recv: ok
> [...]
> Send: G91
> Recv: ok
> [...]
> Send: G28 X0 Y0
> [...]
> Recv: echo:busy: processing
> [...]
> Recv: echo:busy: processing
> [...]
> Recv: X:0.00 Y:0.00 Z:10.00 E:0.00 Count X:0 Y:0 Z:4000
> Recv: ok
> Send: G90
> Recv: ok
> [...]
> Send: M211
> Recv: echo:Soft endstops: ON  Min:  X0.00 Y0.00 Z0.00   Max:  X235.00 Y235.00 Z250.00
> Recv: ok
> [...]
> Send: G1 Y-1 F4000
> Recv: ok

I've also tried to disable with M211 S0 and the repeat; the beavior is the same (and it's ok).

**Comment by ellensp** [comment] 2019-12-29 02:06
Endstops are ignored for all but homing commands. unless you enable
#define ENDSTOPS_ALWAYS_ON_DEFAULT in Configuration_adv.h

**Comment by phate191** [comment] 2019-12-29 12:17
Yes true, but phisical endstops must be separated from software endstops.
Theoretically they have different function.
If I remeber correctly, in old versions, software endostops if are enabled are always enforced.

EDIT:
**Also with #define ENDSTOPS_ALWAYS_ON_DEFAULT enabled**, I can go above the bed limit (bed size 235 x 235) if I use G1 Y236 F4000

**Comment by tatusah** [comment] 2019-12-30 11:41
Different board but for me soft endstops do work correctly with Marlin 2.0.1. What does M114 report as position after you issue the `G1 Y-1 F4000`?

**Comment by phate191** [comment] 2019-12-30 15:20
This is the output from Octoprint console:

> [...]
> Send: G1 Y-1 F4000
> Recv: ok
> [...]
> Send: M114
> Recv: X:0.00 Y:-1.00 Z:5.00 E:0.00 Count X:0 Y:-80 Z:2000
> Recv: ok

**Comment by tatusah** [comment] 2019-12-30 15:22
Does the LCD controls also allow going past soft endstops or is it only trough Octoprint?

**Comment by phate191** [comment] 2019-12-30 15:26
Ok I think I find the issue.
This is the ouput from octoprint if I only home X and Y:

> [...]
> Send: G91
> Recv: ok
> Send: G28 X0 Y0
> [...]
> Recv: echo:busy: processing
> [...]
> Recv: echo:busy: processing
> [...]
> Recv: X:0.00 Y:0.00 Z:10.00 E:0.00 Count X:0 Y:0 Z:4000
> Recv: ok
> Send: G90
> Recv: ok
> [...]
> Send: M114
> Recv: X:0.00 Y:0.00 Z:10.00 E:0.00 Count X:0 Y:0 Z:4000
> Recv: ok
> [...]
> Send: G1 Y-1 F4000
> Recv: ok
> [...]
> Send: M114
> Recv: X:0.00 Y:-1.00 Z:10.00 E:0.00 Count X:0 Y:-80 Z:4000
> Recv: ok

But this is the ouput after home of X, Y and **Z**:

> [...]
> Send: G91
> Recv: ok
> Send: G28 X0 Y0
> [...]
> Recv: echo:busy: processing
> [...]
> Recv: echo:busy: processing
> [...]
> Recv: X:0.00 Y:0.00 Z:10.00 E:0.00 Count X:0 Y:0 Z:4000
> Recv: ok
> Send: G90
> Recv: ok
> Send: G91
> Recv: ok
> Send: G28 Z0
> [...]
> Recv: echo:busy: processing
> [...]
> Recv: echo:busy: processing
> [...]
> Recv: echo:busy: processing
> [...]
> Recv: X:0.00 Y:0.00 Z:0.00 E:0.00 Count X:0 Y:0 Z:0
> Recv: ok
> Send: G90
> Recv: ok
> [...]
> Send: M114
> Recv: X:0.00 Y:0.00 Z:0.00 E:0.00 Count X:0 Y:0 Z:0
> Recv: ok
> [...]
> Send: G1 Y-1 F4000
> Recv: ok
> [...]
> Send: M114
> Recv: X:0.00 Y:0.00 Z:0.00 E:0.00 Count X:0 Y:0 Z:0
> Recv: ok

So, if you home only X and Y, and then you move X or Y, software and hardware endstops are ignored for ALL axis :(

**Comment by tatusah** [comment] 2019-12-30 15:57
Well, there you are correct. Sorry, did only test general G28 previously. Software endstops are not enabled until all axis are homed and thus movement past endstops is possible.

**Comment by tatusah** [comment] 2019-12-30 16:11
And I remembered that I saw this thing before also. The issue connects to a bigger picture. It was last raised here https://github.com/MarlinFirmware/Marlin/issues/16283 so I think this needs some discussion about what if anything should be done about the situation.

**Comment by kurtnelle** [comment] 2020-01-03 23:19
I have confirmed that the software endstops are on but the joystick still allows the planner to send the axis beyond the frame of the machine.

**Comment by boelle** [comment] 2020-01-07 01:09
@phate191 still an issue?

**Comment by kurtnelle** [comment] 2020-01-08 04:22
I had to update to the lastest version of marlin. I think the software endstops work now. However the behaviour with the joysticks is so erratic, that I'm not sure if it actually is working.

**Comment by kurtnelle** [comment] 2020-01-12 06:01
I've tested it some more. Its not working.

**Comment by boelle** [comment] 2020-01-18 22:55
did you test it before or after pr #16533 was merged?

**Comment by boelle** [comment] 2020-01-23 23:58
Lack of Activity
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.

we can reopen if we hear from @phate191 again

**Comment by kurtnelle** [comment] 2020-01-24 02:47
@boelle , I haven't tested it after #16533 cause I can't figure out how to merge!

**Comment by boelle** [comment] 2020-01-24 12:48
@kurtnelle just download from https://github.com/MarlinFirmware/Marlin/tree/bugfix-2.0.x

**Closed as completed** 2020-01-24 12:47 UTC

**Comment by italocjs** [comment] 2020-01-30 15:13
Sorry for reopening, but i have noticed the same issue if using G90/G91 (moving as relative coordinate), the endstops (both phisical and software) are being ignored,  while this wont affect the printer, it i try to move the head around i can crash it.
[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/4134667/Marlin.zip)

I have attached my config to see if someone can help me spot why,  this is a 2.0.x bugfix, from around 05/01/2020.

**Comment by italocjs** [comment] 2020-01-30 15:18
I have the same issue, i'll try burning the latest bugfix (from today) to verify if it was solved

**Comment by italocjs** [comment] 2020-01-30 15:35
I can confirm that #16533  has fixed the issue here!, thanks
