### ISSUE TITLE
[FR] Change GRID_MAX_POINTS_X from configuration bed leveling menu

### ISSUE THREAD

**Issue by jsimmonstx** [MarlinFirmware/Marlin#19209] opened 2020-08-31 11:06 UTC
Description: 

Instead of having to recompile the firmware to specify a different value for GRID_MAX_POINTS_X, provide a configuration menu item to let us set it there.

**Comment by AnHardt** [comment] 2020-08-31 12:08
That's difficult.
Currently Marlin is compiled with that number fixed. Making that changeable on the fly requests for the use of dynamic memory (malloc(), free()). Especially free() is not wanted because of fragmenting the heap. Alternatively one could reserve a maximum number for GRID_MAX_POINTS_X and GRID_MAX_POINTS_Y and use only a part of that. How large this maximum numbers can be without making Marlin to large for the targeted board is depending on the other constant and the rest of the configured options - so is not known before Marlin has been compiled.  It potentially is wasting lots of valuable memory.

Additional difficulties are, how to decide for what XY-combination a mesh stored in the EEPROM is for - and how many of them will fit in.

I purposely don't say - that's impossible. That only provokes someone to realize it, ignoring my concerns and increasing the mess.

**Comment by jsimmonstx** [comment] 2020-08-31 15:20
So, when the printer is turned on, it creates an array on nxn elements on the heap, where n is the value assigned to the compiler definition?

I suppose you make a valid point, re: fragmented memory, but I wasn't aware that memory was so tight on 32-bit boards.

**Comment by AnHardt** [comment] 2020-08-31 17:57
The STM32F103 with only 256KB Flash seem to be already limited. You can't simply configure 'all in' at once.  I'm currently not aware of RAM limitations with the provided configurations - but with really large buffers in RAM you can break them (Try GRID_MAX_POINTS_X 100).
All kinds off AVRs have been brought to all kinds of their limits (flash, RAM, EEPROM, speed) by me - some only purposely.

> it creates an array on nxn elements on the heap

Currently in the area for global and static variables. On top of that is the heap. Stack comes from top and grows down in direction to the heap (AVR). If made dynamic it would be reside on the heap.

**Comment by mymanjgodfrey** [comment] 2021-01-19 21:13
Would be a very handy feature to have.

**Comment by thisiskeithb** [comment] 2021-11-02 23:12
Duplicate of #10547

**Closed as completed by thisiskeithb** 2021-11-02 23:12 UTC
Labels: T: Feature Request
