### ISSUE TITLE
Prints with short segments vibrate

### ISSUE THREAD

**Issue by shampine1** [MarlinFirmware/Marlin#2525] opened 2015-07-26 18:48 UTC
When I print using the development branch (1938, 2474, and 2513), I find that all three of my printers vibrate like crazy.  Marlin seems to either be stopping completely at the end of each segment, or some other non-smooth action.  When I cut the acceleration and jerk settings way down it got significantly better, but in the release branch this sort of stuff was smooth.
I'm suspicion that there is a problem with the look-ahead algorithm, but I don't know the underlying code...

``` cpp
#define DEFAULT_MAX_ACCELERATION      {750,750,100,500}    // X, Y, Z, E maximum start speed for accelerated moves. E default values are good for Skeinforge 40+, for older versions raise them a lot.
```

Here's the pertinent settings I'm using:

``` cpp
#define DEFAULT_ACCELERATION          750    // X, Y, Z and E acceleration in mm/s^2 for printing moves
#define DEFAULT_RETRACT_ACCELERATION  3000    // E acceleration in mm/s^2 for retracts
#define DEFAULT_TRAVEL_ACCELERATION   1000    // X, Y, Z acceleration in mm/s^2 for travel (non printing) moves

// The speed change that does not require acceleration (i.e. the software might assume it can be done instantaneously)
#define DEFAULT_XYJERK                10.0    // (mm/sec)
#define DEFAULT_ZJERK                 0.4     // (mm/sec)
#define DEFAULT_EJERK                 5.0    // (mm/sec)
```

These setting worked well on the released version:

``` cpp
#define DEFAULT_MAX_ACCELERATION      {1200,1200,100,10000}    // X, Y, Z, E maximum start speed for accelerated moves. E default values are good for skeinforge 40+, for older versions raise them a lot. {SD Patch}

#define DEFAULT_ACCELERATION          1000    // X, Y, Z and E max acceleration in mm/s^2 for printing moves {SD Patch}
#define DEFAULT_RETRACT_ACCELERATION  1000   // X, Y, Z and E max acceleration in mm/s^2 for retracts {SD Patch}
// The speed change that does not require acceleration (i.e. the software might assume it can be done instantaneously)
#define DEFAULT_XYJERK                20.0    // (mm/sec)
#define DEFAULT_ZJERK                 0.4     // (mm/sec)
#define DEFAULT_EJERK                 5.0    // (mm/sec)
```

**Comment by thinkyhead** [comment] 2015-07-27 09:55
@shampine1 Remind me, what kind of printer and electronics?

**Comment by shampine1** [comment] 2015-07-27 14:38
I have seen this problem on: Emaker Huxley, Solidoodle 2, Solidoodle 3, all running Printrboard Rev D with Panelolu2.  I will build a part tonight with varying numbers of facets to see if its tied to the length of the segments.

**Comment by Nandox7** [comment] 2015-07-27 14:48
I had commented in a different bug but just to mention that I have seen this as well.
I have at least one STL where that happens that I can share.

It's hard to see but here is a video I made when I noticed it first

https://goo.gl/photos/8Z36PgDLLYruHTy4A

The filament ends up with this wavy pattern.

**Comment by shampine1** [comment] 2015-07-28 01:44
I did more testing...  It seems more like a buffer based problem.  1mm segments print nice and smoothly.  When the printer moves into an area with 0.5mm segments, it prints the first few smoothly, but then starts shuddering.  I made two test pieces to demonstrate this:  http://www.thingiverse.com/thing:944807 
SegTest will print 3/4 of the way around smoothly, but starts shuddering about half way into the 0.5 mm segments.  However, on the surface layer (which prints at about half the speed), it goes smoothly all the way around.
I hope this helps!

Update:  SegTest2 runs more smoothly even though it has 0.5mm segments; its really two surfaces with a little bonding between

**Comment by shampine1** [comment] 2015-07-28 01:51
By the way, Marvin vibrates like crazy (the official test Martian).

**Comment by tonnico** [comment] 2015-07-28 05:28
Do you have a full graphic display?

**Comment by Nandox7** [comment] 2015-07-28 09:14
In my case I do have a Full Graphics Display.

**Comment by tonnico** [comment] 2015-07-28 09:39
Disable your display and test it again.

**Comment by Nandox7** [comment] 2015-07-28 12:17
Ok, I'll try that.
I have the printer connected to Octoprint so the LCD is not even connected.

I also have the Ultipanel LCD should that one be a problem as well? I can test with it if needed as well.

**Comment by thinkyhead** [comment] 2015-07-29 01:24
@Nandox7 There are some advanced settings you might try adjusting to change the behavior of the input buffer. In Configuration_adv.h look for these settings:

``` cpp
#ifdef SDSUPPORT
  #define BLOCK_BUFFER_SIZE 16   // SD,LCD,Buttons take more memory, block buffer needs to be smaller
#else
  #define BLOCK_BUFFER_SIZE 16 // maximize block buffer
#endif

// @section more

//The ASCII buffer for receiving from the serial:
#define MAX_CMD_SIZE 96
#define BUFSIZE 4
```

Try increasing `BUFSIZE` to 5, 6, 7, 8, etc. to see if anything improves. And maybe try setting `BLOCK_BUFFER_SIZE` to 32.

**Comment by shampine1** [comment] 2015-07-29 15:00
@thinkyhead Is there any chance that this setting might help too (assuming it acts on straight lines)?  For the Solidoodles, 5 steps is 0.057mm; ridiculously small!  

```
const unsigned int dropsegments=5; //everything with less than this number of steps will be ignored as move and joined with the next movement
```

**Comment by Nandox7** [comment] 2015-07-29 15:09
@thinkyhead, I'll try changing those settings.

@shampine1, I've tried the examples you've made but I can't quite replicate the issue, maybe because the part is small and I don't notice it?
I notice some shacking but it's while doing the infill,  those are really small segments and I have it set to make them a bit faster.

**Comment by shampine1** [comment] 2015-07-29 16:03
@Nandox7 SegTest is a better test; make sure you set it with multiple shells.  The outside surface is usually smooth running (probably because it is extruded at about half speed).  The inner shells will exhibit the problem, especially in the near left quadrant.  I will upload an even tougher part with LOTS of segments and lengths varying from 1mm to 0.13 mm in length
http://www.thingiverse.com/thing:944807

**Comment by Nandox7** [comment] 2015-07-29 19:54
@shampine1 aha! That killed it. :) With that one right in the brimm the printer is stuttering a lot to a point that something it even stops for a bit.

@thinkyhead starting to test the params change now. I'll report as I have some data.

**Comment by Nandox7** [comment] 2015-07-29 21:00
Incrementally bumped BUFSIZE up to 8 (5 was the initial value) and set BLOCK_BUFFER_SIZE to 32 with no luck.
I also disabled the support for the Full Graphics display but it didn't solved the issue.

Using a Ramps 1.4 running the Development branch merged up to commit ae1df5fdb4d1fc080b98aa7cdacb23eabbc37306

**Comment by thinkyhead** [comment] 2015-07-30 23:56
> Incrementally bumped BUFSIZE…
> …also disabled the support for the Full Graphics display…

Good to know. So we can look at other things…
- Did you try raising the E Jerk, then the XY Jerk even more than before?
- If you remove all E moves from the GCode does it stop stuttering?

**Comment by Nandox7** [comment] 2015-07-31 00:46
-Did you try raising the E Jerk, then the XY Jerk even more than before?
No. Didn't touched the Jerk params.

-If you remove all E moves from the GCode does it stop stuttering?
No. Just removed all E codes from the gcode and it still does it.

(tried to attach the file here but github doesn't allow it, I can host it somewhere if it helps)

**Comment by thinkyhead** [comment] 2015-07-31 01:09
> Just removed all E codes from the GCode and it still does it.
- What kind of vibrations do you get printing at 90%, 75%, 50%, 25%, and 10%…?

> Didn't touch the Jerk params

I recommend playing with them, if only to set them really high and see if they change anything, then set them really low and see what that does. With very small moves, acceleration shouldn't really come into play. But the jerk –change in velocity– may be expressed more.

From the way these machines work (and the way Marlin handles movement) I would intuitively assume that with very small moves the machine doesn't have any time to reach full speed in any single move, so my sense is that every small move will tend to start at the jerk speed (which is the minimum jump from zero) and then hang around at that speed, perhaps oscillating the movement rate, especially on round corners. Another possibility is that very small XY moves are doing weird things, like moving X only, then moving Y only…

Along those lines, are you able to produce some movement that causes vibration in only one axis? Or, do you sense the vibration from both the X and Y motors?

Another thing is that with slower and smaller movements, stepper motors with too much current might ring in ways that they don't when moving farther and faster. So, on the outside chance that this is involved, try reducing the current on your XY motors to the bare minimum .

**Comment by Nandox7** [comment] 2015-07-31 12:39
Easier to see than to explain: https://www.youtube.com/watch?v=KJFOC0_CPTM
Gcode used in the video: http://pastebin.com/yvjMsbct
(E codes removed)

**Comment by tonnico** [comment] 2015-07-31 19:57
Are you kidding? Your segments are shorter than a human hair. Reduce the resolution of your STL. You don't need to change any setting. This short segments are not possible to print smoothly on normal speed.

**Comment by thinkyhead** [comment] 2015-07-31 20:47
@Wurstnase may be correct. Very short segments aren't handled very well due to the extra overhead. So, in your modeling software (such as OpenSCAD) it's important to set the number of arc segments to something pretty low (e.g., `$fn = 12;`), especially for smaller holes.

What happens if you remove every other G1 command from the GCode file, so that it has longer segments? You can do that using a regular expression search / replace, like so:

Search: `(G1 +X[0-9\.]+ +Y[0-9\.]+ *\n)(G1 +X[0-9\.]+ +Y[0-9\.]+ *\n)`
Replace: `$1`

You can also just remove every 3rd line, like so:

Search: `(G1 +X[0-9\.]+ +Y[0-9\.]+ *\n)(G1 +X[0-9\.]+ +Y[0-9\.]+ *\n){2}`
Replace: `$1`

If you see improvement after lengthening the lines in this manner, then it's just a matter of being more careful in how you set up your models. Some slicers may also have options to combine very small lines into longer ones, for those cases where a model is very detailed.

**Comment by tonnico** [comment] 2015-07-31 21:01
Or this py-script.
https://github.com/jcrocholl/kossel/blob/master/clean_gcode.py

I work mostly with $fn of 32. But this gcode is more something like $fn=1200.

**Comment by Nandox7** [comment] 2015-07-31 23:33
@Wurstnase remember that this was an extreme test created by @shampine1.

The part where I first noticed this is not as extreme as this one. And when I design parts I never go as close to the number of segments seen here.

Now the question is, what is causing this? @thinkyhead You mention extra overhead. As there is no enough free time to be able to process these in time as they "run" for such a short time?
Maybe it's a dumb question but, as the segments are so short, are the steppers still able to perform them? Meaning as they can't do a "full" step round makes them adjust back and forth?
Or Marlin takes care to only send "full" steps?

I'll try and remove every line or every 3rd line and see what happens.

**Comment by tonnico** [comment] 2015-08-01 07:50
I'm also using something like this to reach the limit while testing my machine.
But there are now 2 bottlenecks. 1) transfer the gcode from host to printer. 2) calculate the planner.

The planner needs a lot of time to calculate the smooth steps. Reverse, forward and the the trapezoid. You gcode needs also more calculation time than a delta.

The host protocol also need to send a 'ok' back. So this takes also time. Everything you don't have in your code.

**Comment by thinkyhead** [comment] 2015-08-03 21:23
It's also possible the command buffer is emptying so quickly that it's causing the interpreter to sit around waiting for the next commands to be transferred in. What kind of result do you see if you put an `M400` command after every single `G1` command (or every other `G1` command, etc.)?

I only wish there was some way to observe what's going on at a granular level without also affecting the results. We could send lots of log messages to the serial out, but that only adds more overhead.

**Comment by tonnico** [comment] 2015-08-03 21:35
Maybe, FYI I've got the same issues with that gcode on my Due.

**Comment by thinkyhead** [comment] 2015-08-03 21:53
@Wurstnase Well I suppose it's possible that this is an architectural problem. Something is blocking for too long. But someone will have to diligently study the code to figure that out.

**Comment by thinkyhead** [comment] 2015-08-03 21:54
See also: https://github.com/MarlinFirmware/Marlin/issues/2370

**Comment by Nandox7** [comment] 2015-08-03 23:24
Today while printing a "normal" part I noticed this same behavior again.
It was also some circles, in this case quite smaller and it was a part that I have created and I'm sure I haven't done it with multiple small segments.

@thinkyhead I was following that thread as well and wondering. A easy check would be to try and use the older version of the compiler and try? Or even add the reset line to the ISR routine.

**Comment by thinkyhead** [comment] 2015-08-04 01:03
> try and use the older version of the compiler

Not a bad idea.

I'm also curious to know at what point the behavior disappears as the feedrate is adjusted. Start out the test at 100% feedrate and keep turning down until the problem goes away. See if this has any effect, whether it affects all moves or just some…

**Comment by tonnico** [comment] 2015-08-04 14:27
@Nandox7 Can you please post that part +/- 20 lines of your gcode?

**Comment by Nandox7** [comment] 2015-08-04 15:48
@Wurstnase, here you go. A bit more than 20 lines but should do the trick.
http://pastebin.com/HpeWwLN0

![screenshot from 2015-08-04 16 47 54](https://cloud.githubusercontent.com/assets/117827/9065298/a26f88ee-3ac8-11e5-9ea6-38bfebd8c6bf.png)
(It's while printing the circles - for a size reference that part is to hold a RAMPS board)

**Comment by tonnico** [comment] 2015-08-04 16:10
You've tried to send over 100 segments per second. Maybe this is too much.

**Comment by Nandox7** [comment] 2015-08-04 16:24
That's the slider work... I'll try to reduce the feedrate that should help it.
I'll also try and slice this on the older version (I'm using Simplify3D) to see if there is any change.

Either way shouldn't the gCode sending app wait for the OK to send another line?
(I'm using Octoprint 1.2.4)

**Comment by tonnico** [comment] 2015-08-04 17:41
It's your STL-file. Not the slicer.

**Comment by Nandox7** [comment] 2015-08-05 09:04
Ok, I'll check it again. The part was done in Inventor and it's a normal circle, 3.5mm of diameter.
I used the default export settings so I didn't even asked for it to be high detail.

In regards to the test, I started lowering the feedrate it ended up having a somehow continuous flow when the feedrate was down to 15-20%.
Of course at that rate all is done veryyyy slowly, like the movement from one corner of the bed to the opposite after it finishes the G29.
But in overall the other movements remain the same, just slower like when it's doing the full infill of the first layers.

**Comment by tonnico** [comment] 2015-08-05 09:15
As far as I know you can reduce the resolution in Inventor.
Can you upload that STL-model?

**Comment by Nandox7** [comment] 2015-08-05 09:24
Can't attach STL files here so I hosted it in thingiverse: http://www.thingiverse.com/thing:956032

**Comment by AnHardt** [comment] 2015-08-05 09:42
> veryyyy slowly, like the movement from one corner of the bed to the opposite after it finishes the G29.

Good point. I assume we have then still HOMING_FEEDRATE[2] / HOMING_BUMP_DIVISOR[2] in effect. I guess we should set it to XY_TRAVEL_SPEED at the end of G29.
Or you could set a feedrate by yourself after a G29.

**Comment by tonnico** [comment] 2015-08-05 10:34
![small_hole](https://cloud.githubusercontent.com/assets/8709415/9083866/1855bfe2-3b6e-11e5-9db1-88ed847ce2da.JPG)
As I've said. Too much segments.

**Comment by tonnico** [comment] 2015-08-05 10:40
Try this instead: https://www.thingiverse.com/thing:956089

**Comment by AnHardt** [comment] 2015-08-05 10:40
Can't reproduce this super slow speeds after G29 today. But occasionally i see them.

**Comment by thinkyhead** [comment] 2015-08-07 01:34
@AnHardt Not to divert this thread too much, but what do you think about setting `feedrate` to the default (`1500.0`) at the end of `G29`? It should get capped to the `max_feedrate` on the next move.

**Comment by fjsdc** [comment] 2015-08-27 00:02
Hi

I'm building a CoreXY and have found the same problem. Making a simple speed test, and for some reason the motor stops before reaching the end of the path.
Used stable version 1.0.2 and the problem doesn't happen.

I have made several videos of this problem and uploaded to YouTube. One of the videos is in slow motion and you can see the motor stop and start again almost at the end of the path.

https://youtu.be/Umgpr_oD8qg
https://youtu.be/0wIgP4-GLs0

Contact me if you need more information.

**Comment by thinkyhead** [comment] 2015-08-27 00:53
@fjsdc This is bound to be a tricky bug to find. Do you see any difference if you insert an `M400` after each `G1` command?

I do notice that the model has a huge amount of detail in those small circles, and the slicer isn't doing anything to shorten those segments. Marlin may not handle such small segments very efficiently. If you can re-create the STL making the holes less detailed, you should get better results.

**Comment by tonnico** [comment] 2015-08-27 05:30
Just an idea.

Open your stepper.cpp. At line 752 should stay "// If current block is finished, reset pointer". 
Just before that line please copy this one:
`OCR1A = (OCR1A < (TCNT1 +16)) ? (TCNT1 + 16) : OCR1A;`

**Comment by fjsdc** [comment] 2015-08-27 09:03
I have more information that can be important to find this bug. 
With both version 1.0.2 or 1.1.0 the problem happens. The problem only start to happen when the speed increase. BUT with the stable version the problem only happens at much high speeds.
From the testes i have made, using the version 1.0.2 the problems start to appears with speed superior to "G1 F20000". With version 1.1.0 the problems start to appear with speed superior to "G1 F11000".
It can be a problem with the management of the buffer...

Hardware used:
Ramps 1.4 with mega, A4988 at 1/16.

To make the test i have used an ramps from an other printer i have, but i have already put ramps back in the printer. I waiting to receive a new ramps for my corexy. Sorry, but i will only make new testing when a receive my new ramps.

**Comment by Nandox7** [comment] 2015-08-27 10:16
I need to get more time to go back testing this.
So far from my side I noticed that the fact that I was using Octoprint to feed in the gCode it was causing some delays. The CPU would rise to 96% and the delays would start to happen.

I'm getting a second Mega2560 board to quickly iterate and test over different settings and one other thing I'll be testing is to plug the Raspi w/Octoprint connected directly over serial port and not over USB to reduce the overhead of the USB connection.

**Comment by fjsdc** [comment] 2015-08-27 10:45
In my case i was testing using an pc and pronterface directly connected with usb. Are you using an raspberry with an camera?

@Nandox7: Can you run this gcode test and check if you get the same problem i have in the next videos?

With speed increase the motor stop before reaching the end of the path and them resume.
https://www.youtube.com/watch?v=Umgpr_oD8qg
https://www.youtube.com/watch?v=0wIgP4-GLs0

Do not forget homing x and y before running the gcode...

``` gcode
G1 F6000
G1 X0 Y0
G1 X200 Y0
G1 X200 Y200
G1 X0 Y200
G1 X0 Y0
G1 X200 Y200
G1 X0 Y0
G1 X200 Y0
G1 X0 Y200
G1 X200 Y0
G1 X0 Y0

G1 F12000
G1 X200 Y0
G1 X200 Y200
G1 X0 Y200
G1 X0 Y0
G1 X200 Y200
G1 X0 Y0
G1 X200 Y0
G1 X0 Y200
G1 X200 Y0
G1 X0 Y0

G1 F18000
G1 X200 Y0
G1 X200 Y200
G1 X0 Y200
G1 X0 Y0
G1 X200 Y200
G1 X0 Y0
G1 X200 Y0
G1 X0 Y200
G1 X200 Y0
G1 X0 Y0

G1 F24000
G1 X200 Y0
G1 X200 Y200
G1 X0 Y200
G1 X0 Y0
G1 X200 Y200
G1 X0 Y0
G1 X200 Y0
G1 X0 Y200
G1 X200 Y0
G1 X0 Y0

G1 F30000
G1 X200 Y0
G1 X200 Y200
G1 X0 Y200
G1 X0 Y0
G1 X200 Y200
G1 X0 Y0
G1 X200 Y0
G1 X0 Y200
G1 X200 Y0
G1 X0 Y0

G1 X0 Y0
M84
```

**Comment by tonnico** [comment] 2015-08-27 10:59
This are 2 different issues!
The issue from @fjsdc is more this one https://github.com/MarlinFirmware/MarlinDev/issues/35

**Comment by fjsdc** [comment] 2015-08-27 11:21
@Wurstnase: i have read the issue you send me, and it appears to be the same problem. when i receive the ramps board i will try your solution of adding the code line `OCR1A = (OCR1A < (TCNT1 +16)) ? (TCNT1 + 16) : OCR1A;` and post the result.

**Comment by thinkyhead** [comment] 2015-09-01 00:50
Any progress on this issue? Timing- and interrupt-related problems can be very tricky to suss out!

**Comment by fjsdc** [comment] 2015-09-01 14:33
For my case, added the line "OCR1A = (OCR1A < (TCNT1 +16)) ? (TCNT1 + 16) : OCR1A;" was requested by Wurstnase and case solved... :)

thanks Wurstnase.

**Comment by paulusjacobus** [comment] 2015-09-01 22:26
@Wurstnase can you explain to me what this code exactly does? It seems to be a step divider routine but I haven't digged into the stepper code yet so I am just very curious. Thx!

**Comment by tonnico** [comment] 2015-09-03 09:59
I can't say why this happens, but I can say what happens.

TCNT1 is the counter of the ISR. The problem is that OCR1A is set in the end of the interrupt routine. So TCNT1 is counting upwards. Maybe allready at 5000. Just for this example.
Now OCR1A is set to 4900.
What will happen? The ISR won't trigger and run up to 65k.

What we do now? We look if TCNT1 is allready behind OCR1A and set OCR1A just some ticks behind it, so we can be sure that the ISR will trigger. And there we need some ticks to control this. Not time.

**Comment by thinkyhead** [comment] 2015-09-04 23:00
I've submitted the patch as #138 so should this issue be closed?

**Comment by jbrazio** [comment] 2016-04-23 11:38
Thank you for your interest making Marlin better and reporting this issue but this topic has been open for a long period of time without any further development. Marlin has been under heavy development for the past couple of months and moving to it's last mile to finish the RC cycle and release **Marlin v1.1.0**. We suggest you to try out the latest [RCBugfix](https://github.com/MarlinFirmware/Marlin/archive/RCBugFix.zip) branch and reopening this issue if required.

**Closed as completed by jbrazio** 2016-04-23 11:38 UTC
Labels: Needs: More Data

**Comment by lesaux** [comment] 2018-01-07 22:10
I see this vibration issue has appeared for me while upgrading from 1.1.0-rc5 to 1.1.8.
I tried to keep settings as consistent as possible between firmwares. I will test other versions to see when this difference was implemented.

**Comment by thinkyhead** [comment] 2018-01-07 22:23
@lesaux Try cutting your jerk values in half.

**Comment by lesaux** [comment] 2018-01-07 22:27
@thinkyhead Ok thanks, I will try this.

**Comment by lesaux** [comment] 2018-01-08 00:42
@thinkyhead unfortunately dividing jerk by two doesn't make a noticeable difference. I will try various versions in the upcoming days and report my findings.

**Comment by thinkyhead** [comment] 2018-01-08 02:36
> I will try various versions in the upcoming days and report my findings.

Great. I look forward to your results!

**Comment by MiddleMan5** [comment] 2018-08-27 03:44
Adding the following to stepper.h (1.1.9) in the aforementioned location seems to have fixed the stuttering issue that has plagued my PrintrBoard Rev F4
```cpp
#ifdef STUTTER_FIX
    OCR1A = (OCR1A < (TCNT1 +16)) ? (TCNT1 + 16) : OCR1A;
#endif
```
What is the status of this issue?

**Comment by thinkyhead** [comment] 2018-08-30 00:12
@ejtagle — Any comment on the proposed solution? I can see why it could work.

**Comment by ejtagle** [comment] 2018-08-30 01:05
Basically, the proposed fix is incorrect.
Line 1224 in Stepper.cpp does exactly that: Leaving some margin to avoid the described problem.
Instead of adding the proposed fix, try to increase the last value (the '8' value)

```
min_ticks = HAL_timer_get_count(STEP_TIMER_NUM) + hal_timer_t((STEPPER_TIMER_TICKS_PER_US) * 8);
```

to idk, maybe 10...

```
min_ticks = HAL_timer_get_count(STEP_TIMER_NUM) + hal_timer_t((STEPPER_TIMER_TICKS_PER_US) * 10);
```

But the 8 value was the correct one, unless the compiler has changed and the ISR epilogue is longer ...

**Comment by ejtagle** [comment] 2018-08-30 01:14
Stepper.cpp , lines 1216 to 1244 ensure exactly this same condition, but in a safer way,
What i assume here is that the Stepper ISR is overloading the AVR. Maybe the maximum step rate for AVR should be decreased.

Now that i think, with short segments, we are probably running out of processing power. Adding that line forces to reduce the step rate, giving extra processing time to the planner- But that is NOT the proper way to do it -- That WILL ruin the acceleration profile, as it creates a sudden change of acceleration, as it is capping the maximum speed!

The proper fix is to decrease the maximum step rate, so it will allow the planner to create proper acceleration/deceleration profiles.

Yes, this seems (again) as AVR struggling to keep the planner running, and running out of processing power...

**Comment by MiddleMan5** [comment] 2018-08-30 01:48
I wasn't suggesting it was an actual solution, the opposite in fact. I was just interested in learning why it had an effect in the first place, when it seemed like the code was already handling the issue. It was one of those late-night "screw it" moments and it improved the behaviour of the printer.

I'll run some tests on min_ticks and see if I can narrow in on anything

**Comment by thinkyhead** [comment] 2018-08-30 21:30
As a side note, I see we have a HAL function called `HAL_timer_restrain` that we never use. Is that now obsolete?

**Comment by thinkyhead** [comment] 2018-08-30 21:32
> Yes, this seems (again) as AVR struggling to keep the planner running, and running out of processing power...

In that case, simply reducing the feedrate slightly should eliminate the stutters. Try turning the knob to lower the feedrate @MiddleMan5 and see if it does in fact prevent stuttering.

**Comment by ejtagle** [comment] 2018-08-31 01:58
Yes @thinkyhead : ```HAL_timer_restrain ``` is obsolete.

Yes, reducing the feedrate should remove the stutters

**Comment by AnHardt** [comment] 2018-08-31 09:43
It's not the printspeed what matters - it's the steprate. So for example a lower microstepping would have the same effect.

In general the answer is already given in the question (titel).
Print larger segments. In small segments the overhead for planning a segments gets larger than its runtime - the buffer runs dry.

**Comment by AnHardt** [comment] 2020-10-09 21:36
How many lock-messages will we get until a tread is really locked?
