### ISSUE TITLE
[Help] (use M106/M107 in Marlin to control servo)

### ISSUE THREAD

**Issue by loler-later** [MarlinFirmware/Marlin#15626] opened 2019-10-22 01:55 UTC
I am a college student and my team is working on a project that uses marlin firmware to control steppers and servos. I find out that it is set to use M280P0S in Marlin to control servos, but the software I use can only generate M106/M107 or M3/M5 to turn on/off something. I am looking for someone to help me use M106 to set the servo to 30 degrees and M107 to set it to 0 degrees.

**Comment by psavva** [comment] 2019-10-22 19:13
This what you looking for?
http://marlinfw.org/docs/gcode/M280.html

**Comment by Grogyan** [comment] 2019-10-22 19:37
Those Gcodes are already assigned to other operations.
Recommend checking into your software/slicer as M280 is the correct gcode for controlling servos

**Comment by shitcreek** [comment] 2019-10-24 18:04
What sort of software are you using that can only generate M106/107 and M3 - M5?
If you are stuck with that software, a simple hack would be to remove M106/M107 from Marlin and change any mentioning of M280 to M106. Or copy the M280's codes over into M106.

**Comment by boelle** [comment] 2019-11-03 13:53
since this is not a bug with marlin going to close this one

we can reopen if there is a bug as such

**Closed as completed by boelle** 2019-11-03 13:53 UTC
Labels: help wanted
