### ISSUE TITLE
[BUG] Selecting Fan 2 edits Fan 3

### ISSUE THREAD

**Issue by Borillion** [MarlinFirmware/Marlin#19617] opened 2020-10-04 18:35 UTC
Attempting to select Fan 2 in UI to adjust fan speed selects Fan 3 for adjustment. I cannot adjust the speed of fan 2 in the UI.

I am using an SKR Pro 1.1 with three fans (1 extruders, 1 part cooling).

**ADDENDUM: This occurs during the print. I also only have one Extruder, 1 part cooling fan, 1 hotend cooling fan.**

I am running 2.0.X 20-09-2020

My Configurations
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/5324062/Configuration.zip)

Steps to Reproduce
Have 3 fans connected to printer.
Select Temperature|Fan Speed 2:
Note that Fan Speed 3 is selected.
Expected behavior: [What you expect to happen]

I expect to be able to control the speed of fan 2.

Actual behavior: [What actually happens]

Selecting "Fan Speed 2" takes me to a screen to change to change the speed of fan 3. And indeed, the speed of fan 3 is changed. Selecting "Fan Speed 3" in the UI also changes fan 3.

Additional Information
I can change fan speed 2 only via gcode, sending M106 P1 S140 for example

**Comment by XDA-Bam** [comment] 2020-10-04 18:43
This sounds very much like the bug that was fixed by #18400.

**Comment by thinkyhead** [comment] 2020-10-04 18:50
Yes, on examining the current code, I can't see anything that would cause this kind of inconsistency with the second fan item. (although it looks like those singlenozzle items do need an update).

Please test the [`bugfix-2.0.x` branch](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.0.x.zip) to see where it stands. If the problem has been resolved then we can close this issue. If the issue isn't resolved yet, then we should investigate further.

**Comment by thinkyhead** [comment] 2020-10-04 18:53
Er, on a second look, maybe there is something to fix! Please compare the behavior in the Tune menu to the behavior in the Temperature menu. I expect the Tune menu needs to catch up to the patch from 18400.

**Comment by Borillion** [comment] 2020-10-04 19:01
> Er, on a second look, maybe there is something to fix! Please compare the behavior in the Tune menu to the behavior in the Temperature menu. I expect the Tune menu needs to catch up to the patch from 18400.

This is where I am having the issue in 2.0.x bugfix. In the tune menu!. I should have been more clear this is during a print

**Comment by Borillion** [comment] 2020-10-04 19:05
I am running 2.0.X 20-09-2020, this came from the marlin firmware downloads page at https://marlinfw.org/meta/download/

**Comment by thinkyhead** [comment] 2020-10-04 19:31
Ok, I have pushed a fix to `bugfix-2.0.x` so it should work correctly now.

**Closed as completed by thinkyhead** 2020-10-04 19:31 UTC

**Comment by Borillion** [comment] 2020-10-04 20:04
Can I just clone from the latest Marlin bugfix fix or that particular
commit?

Thanks!
