### ISSUE TITLE
[BUG] Cant compile with backlash feature

### ISSUE THREAD

**Issue by italocjs** [MarlinFirmware/Marlin#16166] opened 2019-12-09 16:25 UTC
Hello, ive been trying to compile my firmware (version 2.0.0 stable which is working well with the backlash disable) but when i enable it i get some errors that i cant really understand.  any help is apreciated.

Features i'm using that i turned on/off to test, but did no effect:
-s curve
-jerk

Features i cant really turn off
-dual stepper / dual endstop for Y

I have no probe (like bl touch or servo), just a endstop on Xmin, Ymax and Zmax

Error: https://pastebin.com/NtzCvLN0

**Comment by italocjs** [comment] 2019-12-09 16:36
Update:  it has something to do with:   
//#define MEASURE_BACKLASH_WHEN_PROBING

when i disabled it i was able to compile the backlash code.  Since i wont be using the auto measuring, its ok for me,  but might be interesting to find out what is going on.

**Comment by boelle** [comment] 2019-12-09 20:07
Configurations, please
Please ZIP up your `Configuration.h` and `Configuration_adv.h` files (as
requested in the Issue template) and drop them into your next reply.
We'll check them over and see if anything is amiss.

**Comment by Vertabreak** [comment] 2019-12-10 22:36
need a probe to measure backlash when probing so this makes sense to me.

**Comment by boelle** [comment] 2019-12-10 22:39
will close this one until we have the config, the issue template says to attach them

also if you are trying to probe without a probe you have a config error and not a bug

**Closed as completed by boelle** 2019-12-10 22:39 UTC

**Comment by italocjs** [comment] 2019-12-11 12:15
@Vertabreak , makes sense, i wasnt really thinking about using the auto-probing for now, so no problem for me. i have added a 0,05mm backlash on axis X and Y and the difference was good enough.   Is there a way to display a error saying clearly:  "you didnt enabled a probe, which is needed for this feature". A lot of features shows errors like this, which really helps.  im truly noob at programming these things, but i can try if you guys point me in the right direction


Sorry for not attaching it! @boelle  Here it is (this one is working now, to replicate the issue you just need to uncomment //#define MEASURE_BACKLASH_WHEN_PROBING)

[Configuration_adv.txt](https://github.com/MarlinFirmware/Marlin/files/3950218/Configuration_adv.txt)
[Configuration.txt](https://github.com/MarlinFirmware/Marlin/files/3950219/Configuration.txt)

**Comment by nicksears** [comment] 2020-05-13 18:10
had the same issue when enabling BACKLASH_COMPENSATION
disabling #define MEASURE_BACKLASH_WHEN_PROBING
did NOT fix it because it was nested within something that was not enabled to begin with:

```cpp
#define BACKLASH_COMPENSATION
#if ENABLED(BACKLASH_COMPENSATION)
  // Define values for backlash distance and correction.
  // If BACKLASH_GCODE is enabled these values are the defaults.
  #define BACKLASH_DISTANCE_MM { 0.3, 0.6, 0 } // (mm)
  #define BACKLASH_CORRECTION    1.0       // 0.0 = no correction; 1.0 = full correction

  // Set BACKLASH_SMOOTHING_MM to spread backlash correction over multiple segments
  // to reduce print artifacts. (Enabling this is costly in memory and computation!)
  //#define BACKLASH_SMOOTHING_MM 3 // (mm)

  // Add runtime configuration and tuning of backlash values (M425)
  //#define BACKLASH_GCODE

  #if ENABLED(BACKLASH_GCODE)
    // Measure the Z backlash when probing (G29) and set with "M425 Z"
    #define MEASURE_BACKLASH_WHEN_PROBING
```

UPDATE
Attached my configs and error message since I tried the ones italocjs uploaded and reproduced his error.

will transplant my changes into his config and see when it breaks  

[Configuration.h.txt](https://github.com/MarlinFirmware/Marlin/files/4625367/Configuration.h.txt)
[Configuration_adv.h.txt](https://github.com/MarlinFirmware/Marlin/files/4625368/Configuration_adv.h.txt)
[error.txt](https://github.com/MarlinFirmware/Marlin/files/4625379/error.txt)

**Comment by nicksears** [comment] 2020-05-14 17:45
it looks like enabling BLTOUCH caused the issue. 

I tried with a fresh copy (2.0.5.3) and only enabled backlash, bltouch and Z_SAFE_HOMING, and it worked fine. Transplanted the rest of my config changes and almost back in business!
