### ISSUE TITLE
[BUG] [Bugfix 2.0.x] SKR PRO case light keeps dark

### ISSUE THREAD

**Issue by docgalaxyblock** [MarlinFirmware/Marlin#15893] opened 2019-11-13 17:30 UTC
### Description

I tried to activate the case light function at my skr pro. the case light keeps dark and after watching the compiling log I found a warning
`Marlin\src\feature\caselight.cpp:61:64: warning: unused variable 'n10ct' [-Wunused-variable]
   const uint8_t i = case_light_on ? case_light_brightness : 0, n10ct = INVERT_CASE_LIGHT ? 255 - i : i;`

### Steps to Reproduce

Used VS Code
1. setup a skr pro at marlin
2. Enable Case light and no brightness
3. Compile it -> there should be the warning at the log

#### Additional Information

I tried different commits since october and the function did not work at all commits i have tested.
Tested at other board (skr 1.3) and there it did not works too. (Used the same project only changed the board and the board specific pins) But at the ramps it works fine.

#### Update
There is a bug somewhere at the #define CASE_LIGHT_NO_BRIGHTNESS function. If you enable it you can not turn on the case light and the warning will be at the terminal

**Comment by Vertabreak** [comment] 2019-11-13 17:36
i use this feature on the gt2560 and it works correctly are you sure you configured it correctly for the board. it could very well be a issue with stm32 i have seen many issue with many stm32 boards.

**Comment by docgalaxyblock** [comment] 2019-11-13 17:39
like I said
At the SKR 1.3 and arduino mega/Ramps it works perfect

**Comment by LinoBarreca** [comment] 2019-11-13 18:02
@docgalaxyblock which pin are you using as "case light"?

**Comment by gilliands** [comment] 2019-11-13 21:17
I have an SKR 1.3 and I used to use the servo pin and two unused GPIO for PWM to drive an RGB LED strip via a buffer.
```cpp
      #define RGB_LED_R_PIN     P2_00
      #define RGB_LED_G_PIN     P3_25
      #define RGB_LED_B_PIN     P3_26
      #define RGB_LED_W_PIN     -1
```
When I boot, only the red light works and the others are zero.  I have to actively enter the LED menu and change to a colour or even just turn it off and back on again for normal operation.  Looks like only one pin is being set up for PWM after power up.
Used to work until about a week ago round the time when the platform IO updates made change to the ADC pins.  Coincidence?

**Comment by LinoBarreca** [comment] 2019-11-13 21:21
@gilliands completely unrelated to the OP

**Comment by Evg33** [comment] 2019-11-15 14:10
I use White LED Strip 24V on Heater2 as case light. Working ok.

**Comment by Evg33** [comment] 2019-11-15 14:14
I have an SKR Pro and I use the Heater2 for PWM to drive an White LED 24V strip directly from board.
The case light working.
May be not at full power. I need test it.

**Comment by LinoBarreca** [comment] 2019-11-15 14:19
@Evg33 @docgalaxyblock isn't replying since 3 days. I guess he realized he made a mistake in his config and disappeared

**Comment by docgalaxyblock** [comment] 2019-11-15 14:33
@Evg33 I have it at switchmode (no pwm) and I am using HE1
Could you send me your complee config please

**Comment by Evg33** [comment] 2019-11-15 14:43
@docgalaxyblock 

pins_BIGTREE_SKR_PRO_V1.1.h 

`#define HEATER_2_PIN       -1   // PB0
`


Configuration_adv.h
```
/**
 * M355 Case Light on-off / brightness
 */
#define CASE_LIGHT_ENABLE
#if ENABLED(CASE_LIGHT_ENABLE)
  //#define CASE_LIGHT_PIN 4                  // Override the default pin if needed
  #define CASE_LIGHT_PIN PB0 //HEATER_2_PIN 
  #define INVERT_CASE_LIGHT false             // Set true if Case Light is ON when pin is LOW
  #define CASE_LIGHT_DEFAULT_ON true          // Set default power-up state on
  #define CASE_LIGHT_DEFAULT_BRIGHTNESS 127   // Set default power-up brightness (0-255, requires PWM pin)
  //#define CASE_LIGHT_MAX_PWM 128            // Limit pwm
  #define CASE_LIGHT_MENU                   // Add Case Light options to the LCD menu
  //#define CASE_LIGHT_NO_BRIGHTNESS          // Disable brightness control. Enable for non-PWM lighting.
  //#define CASE_LIGHT_USE_NEOPIXEL           // Use Neopixel LED as case light, requires NEOPIXEL_LED.
  #if ENABLED(CASE_LIGHT_USE_NEOPIXEL)
    #define CASE_LIGHT_NEOPIXEL_COLOR { 255, 255, 255, 255 } // { Red, Green, Blue, White }
  #endif
#endif

```

**Comment by LinoBarreca** [comment] 2019-11-15 15:01
@evg33 you shouldn't modify pins file.
The logic behind this is PB0 (CPU pin) - HEATER_2_PIN (BOARD pin) - CASE_LIGHT_PIN (DEVICE pin)
If you restore pins file to default and #define CASE_LIGHT_PIN HEATER_2_PIN
you are actually saying "I connected case light wires to heater 2 port" and should work the same. Making it easier to read and maintain.

**Comment by Evg33** [comment] 2019-11-15 15:43
@LinoBarreca ok. thx.

**Comment by Evg33** [comment] 2019-11-15 15:47
@docgalaxyblock

Configuration_adv.h

```
/**
 * M355 Case Light on-off / brightness
 */
#define CASE_LIGHT_ENABLE
#if ENABLED(CASE_LIGHT_ENABLE)
  //#define CASE_LIGHT_PIN 4                  // Override the default pin if needed
  #define CASE_LIGHT_PIN HEATER_2_PIN
  #define INVERT_CASE_LIGHT false             // Set true if Case Light is ON when pin is LOW
  #define CASE_LIGHT_DEFAULT_ON true          // Set default power-up state on
  #define CASE_LIGHT_DEFAULT_BRIGHTNESS 127   // Set default power-up brightness (0-255, requires PWM pin)
  //#define CASE_LIGHT_MAX_PWM 128            // Limit pwm
  #define CASE_LIGHT_MENU                   // Add Case Light options to the LCD menu
  //#define CASE_LIGHT_NO_BRIGHTNESS          // Disable brightness control. Enable for non-PWM lighting.
  //#define CASE_LIGHT_USE_NEOPIXEL           // Use Neopixel LED as case light, requires NEOPIXEL_LED.
  #if ENABLED(CASE_LIGHT_USE_NEOPIXEL)
    #define CASE_LIGHT_NEOPIXEL_COLOR { 255, 255, 255, 255 } // { Red, Green, Blue, White }
  #endif
#endif
```

**Comment by docgalaxyblock** [comment] 2019-11-15 16:55
@LinoBarreca Thank you that you metioned that
Such a smoother and nicer way

But it did not work for me
@Evg33 Would it be possible that you send me your hole project as a zip? PN me

**Comment by Evg33** [comment] 2019-11-15 18:48
@docgalaxyblock 
zip: https://github.com/Evg33/Marlin/archive/SKR_Pro.zip
browse: https://github.com/Evg33/Marlin/tree/SKR_Pro

**Comment by davidcgu** [comment] 2019-11-16 02:41
Don't use a heat mosfet pin, use a fan pin.

**Comment by boelle** [comment] 2019-11-16 10:04
> At the SKR 1.3 and arduino mega/Ramps it works perfect

@docgalaxyblock Sure you are not having a hardware issue or using wrong type of pin?

**Comment by LinoBarreca** [comment] 2019-11-16 10:08
@davidcgu for some lights (I.e. led bars) the fan pin is not recommended since the fan transistor is too small. Tou will likely burn it. That's why the default in marlin is a heater (they are meant to suck serious power so they have adequate mosfets)

**Comment by Evg33** [comment] 2019-11-16 10:46
> Don't use a heat mosfet pin, use a fan pin.

Why?
Mosfets for heaters are designed for more current than for fans.

**Comment by boelle** [comment] 2019-11-16 10:49
> Don't use a heat mosfet pin, use a fan pin.

Dude, you are a bit wrong here, a fan pin is not able to supply enough current and you just fry the mosfet,

to everyone else: bad advise was given here

**Comment by LinoBarreca** [comment] 2019-11-16 11:12
Well...it might work in some circumstances, provided that you know what you are doing...but if you don't just avoid taking a risk.

**Comment by LinoBarreca** [comment] 2019-11-16 11:15
Just leaving my two cents here about the "it doesn't work" problem. Since you didn't give us more informations about the lights you are using I assume you are powering a led strip. In this case: are you sure you connected the cable with the right polarity? Did you try flipping it? 😂😂😂😂

**Comment by docgalaxyblock** [comment] 2019-11-16 11:49
@LinoBarreca I am using four 10W COB Led strips. Atm they are directly connected to my powersupply.
If I configure the controller Fan to use the heater 2 the it works...so no fried mosfet no hardware error.
I will try to compile @Evg33 s firmware now and do stp by step adjusting to my needs until it does not work

**Comment by LinoBarreca** [comment] 2019-11-16 11:55
>
> If I configure the controller Fan to use the heater 2 the it works...so no fried mosfet no hardware error.

I didn't understand. Are you saying that you told marlin to use fan 0 with connector heater 2 and tested that the connector works by changing the fan speed?
Also... 4*10W how many volts and connected how?

**Comment by boelle** [comment] 2019-11-16 11:57
> Atm they are directly connected to my powersupply.

**Comment by boelle** [comment] 2019-11-16 11:59
> controller Fan

that is  fan to cool of the electronics, make sure to not confuse us

**Comment by boelle** [comment] 2019-11-16 12:00
> I will try to compile @Evg33 s firmware

use a tool like winmerge to make a note of all changes he have done so you can compare and tell us what changes make it work for main marlin, forks/copies are not supported

**Comment by LinoBarreca** [comment] 2019-11-16 12:05
@boelle im pretty sure @evg33 uses a standard source with a proper configuration. I still believe that is an user error not related to marlin. By the way, does sanitycheck controls if the same board port is used for two different things?
For example "hey, you defined case light to use heater 2 but you said you have 3 heaters so there's a conflict"

**Comment by boelle** [comment] 2019-11-16 12:09
we just need to be 100% sure, 

but yeah given that so very few have a problem with case light i also think this is an config issue and not a bug

**Comment by docgalaxyblock** [comment] 2019-11-16 12:10
So my setup:
Hotend: "original" bed mosfet
Bed: external mosfet controlled by a Ext2 pin
Fan 0:  layer fan
Fan 1: E0 auto fan
Fan 2: controller fan
Heater 1&2 unesed
Heater 0 should be the case light

**Comment by boelle** [comment] 2019-11-16 12:14
that is more complicated than it has to be

**Comment by docgalaxyblock** [comment] 2019-11-16 12:16
why? its so clear and useful ^^

**Comment by LinoBarreca** [comment] 2019-11-16 12:16
Not to look rude but what the fu*k.
That isn't a 3d printer it's a rubik's cube 😂😂😂 the more you change the more risk of mistakes you have.
By the way: how do you warm the nozzle? With a lighter?

**Comment by boelle** [comment] 2019-11-16 12:18
this is more simple:

Hotend: heater 0 (hotend connector)
Bed: heater 1 (bed connector)
Fan 0: layer fan
Fan 1: E0 auto fan
Fan 2: controller fan
case light could be heater 2

you dont need an external mofet

**Comment by boelle** [comment] 2019-11-16 12:19
i agree with @LinoBarreca you are making it far more complicated for yourself and the risk of mistakes are higher

**Comment by LinoBarreca** [comment] 2019-11-16 12:22
@boelle the skr pro has 3 heaters & 1 bed (oversized) so I would simplify that too.

**Comment by docgalaxyblock** [comment] 2019-11-16 12:22
https://github.com/bigtreetech/BIGTREETECH-SKR-PRO-V1.1/blob/master/picture/BIGTREETECH-SKR-PRO-V1.1.jpg
![grafik](https://user-images.githubusercontent.com/21227087/68993059-c5bd4c00-0873-11ea-98e9-064146728b27.png)
I've got a 600W 400² heated bed connected to an external mosfet
My 50W catrige uses the original bed mosfet (picture: BED)

**Comment by LinoBarreca** [comment] 2019-11-16 12:23
That explains pretty much.

**Comment by docgalaxyblock** [comment] 2019-11-16 12:24
that is also the reason why I am using such beafy cob leds

**Comment by boelle** [comment] 2019-11-16 12:25
yes, but your setup is far more complicated than it has to be 

Hotend: E0
Bed via external mosfet connected to bed connector
Fan 0: layer fan
Fan 1: E0 auto fan
Fan 2: controller fan
case light could be any of the remaining heaters

**Comment by docgalaxyblock** [comment] 2019-11-16 12:32
Ok I found the differences between me and @Evg33 
I am using the official marlin repo, evg the BTT ones there it seems to be fixed

**Comment by boelle** [comment] 2019-11-16 12:34
you sure?

![image](https://user-images.githubusercontent.com/3832239/68993223-df5f9300-0875-11ea-8bf4-288d83b4deb1.png)

**Comment by docgalaxyblock** [comment] 2019-11-16 12:40
Not completly because I only downloaded the zip and did not take a look at the link
The conf.h looks like the one from the BTT repo not like the one from the official one

Only @Evg33 knows the answer
I need to do some work now. hopefully @Evg33 can answer this questin until I am back

**Comment by boelle** [comment] 2019-11-16 12:40
the default config prob has more extruders than you use

set extruder to 1 and then you can use any of the unused heaters for the case light

**Comment by boelle** [comment] 2019-11-16 12:41
> @Evg33 can answer this questin until I am back

look at the pic, it has the answer

**Comment by davidcgu** [comment] 2019-11-16 14:25
I'm also using cabin light and with some leds the power consumption is minimal, in worst case you can use a mosfet, give it a try and will see, will work on a fan mosfet output but not on the heaters mosfets.... but keep playing as much as u wanted....

**Comment by LinoBarreca** [comment] 2019-11-16 14:40
@davidcgu if you know that the amps used by the lights are less than the specs for the part yes. If you don't know just don't try. Or you'll fry everything.

**Comment by boelle** [comment] 2019-11-16 14:42
ultimately we need to know if this is a config/user error or not

the issue list if for bugs and feature requests only, not long debates on how to do things :-D

**Comment by docgalaxyblock** [comment] 2019-11-16 15:14
I found the "problem"
If I activate `  #define CASE_LIGHT_NO_BRIGHTNESS          // Disable brightness control. Enable for non-PWM lighting.` I am getting the warning from the topic. If I leave it deactivated I do not get it
The Printer is in use atm, will test it asap to see if I could use the case light now
If true there is a little bug at Marlin

**Comment by boelle** [comment] 2019-11-16 15:55
there is a difference between warning and fail when you compile

i also get warnings but if the compile is a success i wont worry about it

**Comment by davidcgu** [comment] 2019-11-16 16:47
I tell u.... will never work fine with the heat pins....

**Comment by sjasonsmith** [comment] 2019-11-16 18:13
@LinoBarreca could the heater pins have changed to disallow HW PWM in the changes you made? I thought you tried to keep HW PWM on both fan and heater pins.

**Comment by docgalaxyblock** [comment] 2019-11-16 18:47
@davidcgu 
Do you recommend me to use a fan pin because the Heater No.2 has strange behavior (it lights up shortly only when the case light brightness is been updated)?

I have defined HE0 as my case light pin, seems to been working fine

But there is a bug somewhere at the `#define CASE_LIGHT_NO_BRIGHTNESS` function. If you enable it you can not turn on the case light.

**Comment by davidcgu** [comment] 2019-11-16 20:10
> @davidcgu
> Do you recommend me to use a fan pin because the Heater No.2 has strange behavior (it lights up shortly only when the case light brightness is been updated)?
> 
> I have defined HE0 as my case light pin, seems to been working fine
> 
> But there is a bug somewhere at the `#define CASE_LIGHT_NO_BRIGHTNESS` function. If you enable it you can not turn on the case light.

I'm using a fan pin with a led strip, the cosumtion should be really low, if required you coul install a small mosfet (around 50 cents)  I can control the brightness and works perfect, I can not provide you deep info but het pins work on a different way than a normal PWM what makes it does not work properly, I told that many posts ago and seems nobody really believe me... test it yourself...

I have offical marlin from 9 Nov.

Regards

**Comment by Evg33** [comment] 2019-11-16 23:22
I use official marlin with changed configs.
I don't use BTT versions.
You can see all changes from official here: https://github.com/MarlinFirmware/Marlin/compare/bugfix-2.0.x...Evg33:SKR_Pro?expand=1#files_bucket

**Comment by boelle** [comment] 2019-11-26 19:23
@docgalaxyblock btw what version of marlin are you using?

**Comment by LinoBarreca** [comment] 2019-11-26 22:19
@boelle you can close this. it's definitely working on bugfix 2.0.x

**Closed as completed** 2019-11-26 22:20 UTC

**Comment by docgalaxyblock** [comment] 2019-11-27 13:04
@boelle At the moment I opend the Issue the newest bugfix
@LinoBarreca Did you enable NO_BRIGHTNESS?!
I have checked it again (Marlin v. 13:30 timezone Berlin)
And it did not work either my skr pro or skr 1.3. It only works at my ramps
If you enable the no brightness function it do not work anymore!!!
So Issue still exists
