### ISSUE TITLE
[BUG] (error compiling with TMC2209 and SKR Pro v1.1 - trinamic.cpp)

### ISSUE THREAD

**Issue by psim** [MarlinFirmware/Marlin#15538] opened 2019-10-12 16:11 UTC
### Description

Error compiling latest build. Did not have before. When compiling now you need to modify also the pins_BIGTREE_SKR_PRO_V1.1.h file in the Hardware serial part, otherwise you get an error:

#if HAS_TMC220x
  /**
   * TMC2208/TMC2209 stepper drivers
   *
   * Hardware serial communication ports.
   * If undefined software serial is used according to the pins below
   */
  //#define X_HARDWARE_SERIAL  Serial
  //#define X2_HARDWARE_SERIAL Serial1
  //#define Y_HARDWARE_SERIAL  Serial1
  //#define Y2_HARDWARE_SERIAL Serial1
  //#define Z_HARDWARE_SERIAL  Serial1
  //#define Z2_HARDWARE_SERIAL Serial1
  //#define E0_HARDWARE_SERIAL Serial1
  //#define E1_HARDWARE_SERIAL Serial1
  //#define E2_HARDWARE_SERIAL Serial1
  //#define E3_HARDWARE_SERIAL Serial1
  //#define E4_HARDWARE_SERIAL Serial1

Obviously if you modify this, printer do not work at all.

### Steps to Reproduce

**Expected behavior:** [No need to modify the pins file and no errors]

**Actual behavior:** [Compilation errors]
https://pastebin.com/TLXctqF3

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/3720890/Marlin.zip)

#### Additional Information

* Include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.

**Comment by boelle** [comment] 2019-10-12 16:33
please use pastebin for long errors, then insert link to pastebin in your post

**Comment by psim** [comment] 2019-10-12 16:53
done

**Comment by darknode** [comment] 2019-10-12 19:22
Just use ```TMCStepper=https://github.com/bigtreetech/TMCStepper``` instead of original trinamic in ```[common]``` and ```[env:BIGTREE_SKR_PRO]``` sections of platform.ini. Also you'll need to comment error in trinamic.h:
```
#if TMCSTEPPER_VERSION < 0x000500
//  #error "Update TMCStepper library to 0.5.0 or newer."
#endif
```

**Comment by boelle** [comment] 2019-10-12 19:36
you dont need the bigtree tech version

look last reply here: https://github.com/MarlinFirmware/Marlin/pull/15530

**Comment by darknode** [comment] 2019-10-12 21:33
@boelle It just don't compile.

Steps to reproduce:
* Get a fresh clone of repo, switch to branch bugfix-2.0..., do full cleanup(to make sure PIO will download fresh versions of packages and etc), you can use cleanup script like that [build_cleanup.sh.zip](https://github.com/MarlinFirmware/Marlin/files/3721153/build_cleanup.sh.zip) or do it manually.
* Apply SKR Pro + TMC2209 configuration:
** From a patch file
[skrpro_tmc2209.patch.zip](https://github.com/MarlinFirmware/Marlin/files/3721156/skrpro_tmc2209.patch.zip) with ```git apply skrpro_tmc2209.patch```
** OR manually like in attached files [configs.zip](https://github.com/MarlinFirmware/Marlin/files/3721157/configs.zip)

What you'll get is:
```
Compiling .pio/build/BIGTREE_SKR_PRO/src/src/sd/SdFatUtil.cpp.o
Marlin/src/module/stepper/trinamic.cpp: In function 'void tmc_serial_begin()':
Marlin/src/module/stepper/trinamic.cpp:296:18: error: 'class TMCMarlin<TMC2209Stepper, 'X', '0', (AxisEnum)0>' has no member named 'beginSerial'; did you mean 'HWSerial'?
         stepperX.beginSerial(115200)
```

Why? TMC library has a [commit](https://github.com/teemuatlut/TMCStepper/commit/2d14f340a0966a16ac66ecfa435434aac3dd0f7d) which assumed to fix that issue, but not released yet. So you need to switch from version to just master branch of ```TMCStepper``` lib. That switch in turn will get you next error, about absent "SoftwareSerial" (as you will see @extesy has asked about that issue), to fix it you need to get new version of ```framework-arduinoststm```(which is not part of 5.6.0 version of PIO platform for STM32 yet) like that:
```
platform_packages =
  framework-arduinoststm32@~3.10700.0
```
After that you will get issue with timers HAL and at that point I don't have any fixes at the moment :(

I'd like to get rid of BTT TMCStepper version too, but it looks like there is no way to do that at the moment.

**Comment by boelle** [comment] 2019-10-12 21:40
@extesy what do you think is wrong here?

**Comment by extesy** [comment] 2019-10-12 21:56
Here are my configs, I've just verified that it compiles on the latest Marlin code: [configs.zip](https://github.com/MarlinFirmware/Marlin/files/3721202/configs.zip)

You can also check if your build is using same versions as mine:
```
Dependency Graph
|-- <U8glib-HAL> 0.4.1   
|   |-- <Wire> 1.0       
|   |-- <SPI> 1.0        
|-- <LiquidCrystal> 1.3.4
|   |-- <Wire> 1.0       
|-- <TMCStepper> 0.5.1   
|   |-- <SPI> 1.0        
|-- <Adafruit NeoPixel> 1.2.5
|-- <LiquidTWI2>
|   |-- <Wire> 1.0
|-- <Arduino-L6470> 0.7.0
|-- <SPI> 1.0
|-- <Servo> 1.1.2
|-- <EEPROM> 2.0.1
|-- <IWatchdog> 1.0.0
|-- <Wire> 1.0
```

**Comment by darknode** [comment] 2019-10-12 22:00
@extesy It looks like drivers are not 2209:
![image](https://user-images.githubusercontent.com/809429/66708170-e108d900-ed54-11e9-8718-b6603f9964c4.png)

**Comment by extesy** [comment] 2019-10-12 22:12
No, but #15530 is also doing it for all drivers, not just 2209s.

**Comment by darknode** [comment] 2019-10-12 22:24
@extesy Sorry, just don't get it. #15530 has one changed line:
![image](https://user-images.githubusercontent.com/809429/66708295-ee26c780-ed56-11e9-91aa-b4073695eeac.png)
which is forces to use master branch of BTT, in which they bumped version to get rid of version check error:
![image](https://user-images.githubusercontent.com/809429/66708309-3a720780-ed57-11e9-9336-095c73f38ba2.png)
It works fine, but it's still BTT fork of TMCStepper :)
You've said that "It works for me without using bigtreetech's fork.", but there are no evidences that ***original*** TMCStepper lib works for Skr Pro + 2209.

_I suspect you've meant BTT's fork of Marlin, am I right?_

**Comment by boelle** [comment] 2019-10-12 22:29
change https://github.com/bigtreetech/TMCStepper#master 

to

TMCStepper@>=0.5.0,<1.0.0

you dont need  https://github.com/bigtreetech/TMCStepper#master

**Comment by darknode** [comment] 2019-10-12 22:32
@boelle It will not work as I described [here](https://github.com/MarlinFirmware/Marlin/issues/15538#issuecomment-541363235)

**Comment by extesy** [comment] 2019-10-13 00:45
@darknode I meant that #15530 will affect me because it will use a fork of TMCStepper library that will not be maintained well or updated often unlike the original TMCStepper library.

**Comment by extesy** [comment] 2019-10-13 01:43
Try uncommenting hardware serial in `pins_BIGTREE_SKR_PRO_V1.1.h` file:
```
  #define X_HARDWARE_SERIAL  Serial
  //#define X2_HARDWARE_SERIAL Serial1
  #define Y_HARDWARE_SERIAL  Serial1
  //#define Y2_HARDWARE_SERIAL Serial1
  #define Z_HARDWARE_SERIAL  Serial1
  //#define Z2_HARDWARE_SERIAL Serial1
  #define E0_HARDWARE_SERIAL Serial1
  #define E1_HARDWARE_SERIAL Serial1
```

**Comment by viper93458** [comment] 2019-10-13 02:01
While that does allow a compile it unfortunately doesn't work. At least not for me.

-William

**Comment by psim** [comment] 2019-10-13 08:04
Same here. I tried to explain when I opened this issue. If you modify pins_BIGTREE_SKR_PRO_V1.1.h file it compiles, but doesn't work.

**Comment by TB1405** [comment] 2019-10-13 09:09
same problem here. With the version a month ago and the btt libary it works but now it isnt possible to compile without error.

**Comment by hackebike** [comment] 2019-10-14 17:01
If you are trying to use the TMC 2209 for sensorless homing, it's not working, filed a bug [15496](https://github.com/MarlinFirmware/Marlin/issues/15496)

**Comment by xeddog** [comment] 2019-10-14 22:34
I have the same error for my SKR Pro V1.1 and TMC2208's (UART) as well.  Using "TMCStepper@>=0.5.0,<1.0.0" in Platformio I get the errors,  Using the BTT library compiles.

[TMC2208 Build errors.txt](https://github.com/MarlinFirmware/Marlin/files/3726642/TMC2208.Build.errors.txt)

**Comment by extesy** [comment] 2019-10-14 22:45
@teemuatlut Do you have any opinion on which component (Marlin, TMCStepper, stm32) has a problem that causes this failure?

**Comment by viper93458** [comment] 2019-10-14 22:48
ststm32 needs to be updated but when you force platform IO to use the new version, you get other marlin compile errors even though it resolves the missing software serial implementation.

-William

**Comment by hackebike** [comment] 2019-10-15 07:53
Even if you make it compile, which I have it working point the tmc library to BTT depo, for all the tests I have done, the SKR PRo v1.1 with BTT TMC 2209 sensorless homing does not work ! And if you want to use the TMC  2209 in SPI mode you need to cut a pin !

**Comment by TB1405** [comment] 2019-10-15 08:26
> Even if you make it compile, which I have it working point the tmc library to BTT depo, for all the tests I have done, the SKR PRo v1.1 with BTT TMC 2209 sensorless homing does not work ! And if you want to use the TMC 2209 in SPI mode you need to cut a pin !

2209 and SPI ?

**Comment by hackebike** [comment] 2019-10-15 08:27
yes you can but you need to cut a pin, it's in the BTT manual

**Comment by sjasonsmith** [comment] 2019-10-15 08:36
> yes you can but you need to cut a pin, it's in the BTT manual

The "cut a pin" part of the manual is to disable StallGuard. The TMC2209 does not support SPI, at least according to Trinamic.

Telling you to cut pins is pretty ridiculous, though, regardless of the reason.

**Comment by hackebike** [comment] 2019-10-15 09:03
@sjasonsmith yes you are correct, got confused with 2208 which I am testing now!
Got a marlin config from BTT for 2209 and sensorless homing, will test it and report.

**Comment by hackebike** [comment] 2019-10-16 19:50
all my tests with SKR Pro 1.1/SKR v1.3 and BTT TMC2209 v1.1/1.2 for sensorless homing failed.
So I tested on 2 different boards and 2 different 2209, setting different sensitivity, but nothing.

**Comment by hackebike** [comment] 2019-10-24 10:20
update: I got sensorless homing and probing [working](https://www.youtube.com/watch?v=UJwzSTcQslo).

**Comment by curvi** [comment] 2019-10-28 20:32
Very nice, maybe you could show how you did this? I cannot get things to run. Neither with TMCStepper from BTT, nor with 0.5.1. I've also tried numerous fixes from multiple related topics, such as [this](https://github.com/MarlinFirmware/Marlin/issues/15680) the [timer4 compile flag](https://github.com/MarlinFirmware/Marlin/pull/15655) and a ton of combinations of those.
Just downloading the newest Marlin 2.0 I can compile without issues, but as soon as I use a TMC2209 in the config -> I get errors like:
```
Marlin\src\module\stepper\trinamic.cpp: In function 'void tmc_serial_begin()':
Marlin\src\module\stepper\trinamic.cpp:296:18: error: 'class TMCMarlin<TMC2209Stepper, 'X', '0', (AxisE
num)0>' has no member named 'beginSerial'; did you mean 'HWSerial'?
         stepperX.beginSerial(115200);
                  ^~~~~~~~~~~
                  HWSerial
Marlin\src\module\stepper\trinamic.cpp:310:18: error: 'class TMCMarlin<TMC2209Stepper, 'Y', '0', (AxisE
num)1>' has no member named 'beginSerial'; did you mean 'HWSerial'?
```

I've also tried your [config (-adv) & platform files](https://github.com/hackebike/3dprinter) and it yields

```
In file included from Marlin\src\HAL\HAL_STM32\../../inc/../HAL/./HAL_STM32/HAL.h:99:0,
                 from Marlin\src\HAL\HAL_STM32\../../inc/../HAL/HAL.h:26,

                 from Marlin\src\HAL\HAL_STM32\../../inc/MarlinConfig.h:30,
                 from Marlin\src\HAL\HAL_STM32\Servo.cpp:25:
Marlin\src\HAL\HAL_STM32\../../inc/../HAL/./HAL_STM32/timers.h:122:26: error: variable or field 'Step_H
andler' declared void
 extern void Step_Handler(stimer_t *htim);
                          ^~~~~~~~
Marlin\src\HAL\HAL_STM32\../../inc/../HAL/./HAL_STM32/timers.h:122:26: error: 'stimer_t' was not declar
ed in this scope
Marlin\src\HAL\HAL_STM32\../../inc/../HAL/./HAL_STM32/timers.h:122:26: note: suggested alternative: 'ti
mer_t'
```

**Comment by hackebike** [comment] 2019-10-28 21:02
the first thing that you should do is pointing the TMC library to: https://github.com/bigtreetech/TMCStepper

do you have set this:
[env:BIGTREE_SKR_PRO]
platform = ststm32

btw I know recent Marlin has some compiling issues, mine is from Oct 15th I think.

**Comment by boelle** [comment] 2019-11-03 14:03
@psim still an issue?

**Comment by curvi** [comment] 2019-11-03 23:44
@boelle if I may answer your question: pulling the latest release as of now and compiling with SKR PRO 1.1 compiles fine, but as soon as you include TMC2209 it doesn't compile with Serial problems. Therefore, I would say at the moment the problem persists.

**Comment by sjasonsmith** [comment] 2019-11-08 07:38
@psim & @curvi, can you try again. This should be fixed.

**Comment by hackebike** [comment] 2019-11-08 08:26
if I may, I compiled Marlin 2 days ago for the SKR Pro without any changes to platform.ini and it works fine.

**Comment by boelle** [comment] 2019-11-11 13:09
@psim (and only @psim ) is the issue gone?

**Comment by boelle** [comment] 2019-11-21 20:34
Lack of Activity
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.

**Closed as completed by boelle** 2019-11-21 20:34 UTC
