### ISSUE TITLE
[2.0.x] Question : Z_max and Z_min

### ISSUE THREAD

**Issue by J-charles-C** [MarlinFirmware/Marlin#11181] opened 2018-07-02 17:08 UTC
I,

Little question.
I have plugged my Z_max optical Endstop.
With M119 command All is ok. Triggered when is close and open when, for example, Z is at the middle.

I have active  :
```cpp
#define USE_XMIN_PLUG
//#define USE_YMIN_PLUG
#define USE_ZMIN_PLUG
//#define USE_XMAX_PLUG
#define USE_YMAX_PLUG
#define USE_ZMAX_PLUG
```
Homing is ok, X & Y endstop stop the travel head. Bl-touch is OK.

When i launch G1 Z travel over the Z-Max endstop,  he don't stop bed.

best

[Archive.zip](https://github.com/MarlinFirmware/Marlin/files/2156120/Archive.zip)

**Comment by hexane360** [comment] 2018-07-02 17:15
Can you retry this with the latest firmware? I think this is a duplicate of #11158 which was fixed by reverting #11013.

**Comment by J-charles-C** [comment] 2018-07-02 17:49
I,

With the last, and #define USE_ZMAX_PLUG, it's ok. Z Travel is not interrupt by endstoP;

**when bed is at the middle travel**
```
 Send: M119
Recv: Reporting endstop status
Recv: x_min: open
Recv: y_max: open
Recv: z_min: open
Recv: z_max: open
```
**When bed is on z_max endstop :**
```
Send: M119
Recv: Reporting endstop status
Recv: x_min: open
Recv: y_max: open
Recv: z_min: open
Recv: z_max: TRIGGERED
```

[Archive.zip](https://github.com/MarlinFirmware/Marlin/files/2156248/Archive.zip)

best

**Comment by hexane360** [comment] 2018-07-02 18:45
Again, I believe this issue has recently been fixed. Download the latest bugfix-2.0.x, copy over your configurations, and reflash the printer.

**Comment by J-charles-C** [comment] 2018-07-02 19:03
Good evening,

 my second answer was obtained with the latest version downloaded just now.

There is something else to un comment except #define USE_ZMAX_PLUG ?

best

**Comment by thinkyhead** [comment] 2018-07-03 04:08
> There is something else to un comment except `#define USE_ZMAX_PLUG` ?

The `Z_HOME_DIR` setting must be 1 for a max endstop, or -1 for a min endstop.

**Comment by J-charles-C** [comment] 2018-07-03 04:29
I,

I have choose homing on Z_Min. this setting is ok.

**Comment by J-charles-C** [comment] 2018-07-03 15:03
I,

If i comment  `//#define MAX_SOFTWARE_ENDSTOP_Z`

Endstop don't interrupt Z-Travel

If i un-comment `#define ENDSTOPS_ALWAYS_ON_DEFAULT`

Endstop interrupt Z travel but, after, i can't move it with G1 command ; i must do a `G28 Z` before

best

**Comment by hexane360** [comment] 2018-07-04 00:52
When you say "i can't move it with G1 command", does that include commands both towards and away from the endstop? For example, if you run a `G1 Z200` which triggers the endstop, does a `G1 Z0` work?

**Comment by thinkyhead** [comment] 2018-07-04 00:57
> Endstop interrupt Z travel but, after, i can't move it with `G1` command

`M121` will disable endstops at any time. `M120` will turn them back on (and clear the hit state).

> If i comment `//#define MAX_SOFTWARE_ENDSTOP_Z`
> Endstop don't interrupt Z-Travel

`MAX_SOFTWARE_ENDSTOP_Z` is used to prevent movement past `Z_MAX_POS` and has nothing to do with endstop switches.

**Comment by J-charles-C** [comment] 2018-07-04 05:08
> When you say "i can't move it with G1 command", does that include commands both towards and away from the endstop? For example, if you run a G1 Z200 which triggers the endstop, does a G1 Z0 work?

No, I must execute an G28z before.

>MAX_SOFTWARE_ENDSTOP_Z is used to prevent movement past Z_MAX_POS and has nothing to do with endstop switches.

It's already ok but i want change software endstop for optical.

**Comment by hexane360** [comment] 2018-07-14 20:54
I think I have a new idea about this. Can you upload "Marlin/src/module/endstops.cpp" (or just your whole Marlin source)?

Also, try disabling software endstops completely and then uncomment `#define ENDSTOPS_ALWAYS_ON_DEFAULT`.

**Comment by J-charles-C** [comment] 2018-07-15 05:40
I,

 Also, try disabling software endstops completely and then uncomment #define ENDSTOPS_ALWAYS_ON_DEFAULT.


My commented Jul 3, 2018 :

If i comment //#define MAX_SOFTWARE_ENDSTOP_Z

Endstop don't interrupt Z-Travel

If i un-comment #define ENDSTOPS_ALWAYS_ON_DEFAULT

Endstop interrupt Z travel but, after, i can't move it with G1 command ; i must do a G28 Z before

best

**Comment by J-charles-C** [comment] 2018-07-15 05:41
My Marlin is drop on the first post (archive.zip)

**Comment by hexane360** [comment] 2018-07-15 06:34
For your first post, it wasn't clear if you did both at the same time or made each change separately.

For your second post: The zip you uploaded is just the configuration headers. I'd like to see the full source.

**Comment by workheart** [comment] 2018-08-27 08:44
You say you have zmax but you are homing to -1
#define Z_HOME_DIR -1 
Should be 1 to home up

**Comment by boelle** [comment] 2019-02-20 14:48
@J-charles-C 

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to to a bug in Marlin, then you should post a bug report.
Before posting a bug report please test with `bugfix-2.0.x` to check if problem is gone

**Comment by boelle** [comment] 2019-03-13 21:24
@thinkyhead think we can close this one

**Closed as completed** 2019-03-14 00:11 UTC
Labels: T: Question, C: Configuration
