### ISSUE TITLE
[BUG] fast_pwm.cpp:74:36: error: 'Instance' was not declared in this scope

### ISSUE THREAD

**Issue by Sonicboom247** [MarlinFirmware/Marlin#23232] opened 2021-11-29 22:09 UTC
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

fresh download of Bugfix 2.0, multiple errors in fast_pwm.cpp
first is 
Marlin\src\HAL\STM32\fast_pwm.cpp:74:36: error: 'Instance' was not declared in this scope i was not able to resolve
second
if (index == TEMP_TIMER_NUM || index == STEP_TIMER_NUM
also not declared but changing both to TIMER_NUM resolves error

### Bug Timeline

started today with new Bugfix 2.0

### Expected behavior

expected successful build as i do not edit anything in fast_pwm.cpp

### Actual behavior

failed build

### Steps to Reproduce

compile

### Version of Marlin Firmware

2.0.9.3

### Printer model

Artillery Hornet

### Electronics

Stock board and display

### Bed Leveling

MBL Manual Bed Leveling

### Your Slicer

Cura

### Host Software

SD Card (headless)

### Additional information & file uploads

Marlin\src\HAL\STM32\fast_pwm.cpp: In function 'void set_pwm_frequency(pin_t, int)':
Marlin\src\HAL\STM32\fast_pwm.cpp:74:36: error: 'Instance' was not declared in this scope
   74 |   uint32_t index = get_timer_index(Instance);
      |                                    ^~~~~~~~
Marlin\src\HAL\STM32\fast_pwm.cpp:77:16: error: 'TEMP_TIMER_NUM' was not declared in this scope; did you mean 'TIMER_NUM'?
   77 |   if (index == TEMP_TIMER_NUM || index == STEP_TIMER_NUM
      |                ^~~~~~~~~~~~~~
      |                TIMER_NUM
Marlin\src\HAL\STM32\fast_pwm.cpp:77:43: error: 'STEP_TIMER_NUM' was not declared in this scope; did you mean 'TIMER_NUM'?
   77 |   if (index == TEMP_TIMER_NUM || index == STEP_TIMER_NUM
      |                                           ^~~~~~~~~~~~~~
      |                                           TIMER_NUM
*** [.pio\build\Artillery_Ruby\src\src\HAL\STM32\fast_pwm.cpp.o] Error 1

**Comment by thisiskeithb** [comment] 2021-11-29 22:12
Duplicate of #23213

**Closed as completed by thisiskeithb** 2021-11-29 22:12 UTC
