### ISSUE TITLE
[BUG] Delta sensorless probing compile error

### ISSUE THREAD

**Issue by spotmaxdog** [MarlinFirmware/Marlin#22729] opened 2021-09-08 06:09 UTC
### Did you test the latest `bugfix-2.0.x` code?

No, but I will test it now!

### Bug Description

I am trying to compile marlin for my QQ-S Pro with an SKR 2 board and TMC2209 steppers.

For sensorless probing, I am enabling SENSORLESS_PROBING and defining my drivers as TMC2209s.

I am commenting out my Z_min endstop (old level sensor) as I want to use the 2209s to probe.

When I go to compile I get this error. I can get it to compile if I define an nonexistent Z_Min endstop but wouldn't that make sensorless probing fail?

![Screen Shot 2021-09-08 at 1 04 55 AM](https://user-images.githubusercontent.com/90303419/132455074-9002889c-a64d-423d-b4bb-5e8fa68bb27c.png)

### Expected behavior

Expected to compile with no Z_min endstop, using sensorless probing

### Actual behavior

Compiling crashed.

Can get it to compile if I go into endstops.h and comment out the line but I do not know what that does to Marlin

### Steps to Reproduce

Enable SENSORLESS_PROBING
Disable all Z_Min endstops
Compile

### Version of Marlin Firmware

2.0.9.1

### Printer model

QQ-S Pro

### Electronics

BTT SKR 2.0 with TMC 2209s

### Additional information & file uploads

[Archive.zip](https://github.com/MarlinFirmware/Marlin/files/7126290/Archive.zip)

**Comment by thinkyhead** [comment] 2021-09-08 08:47
Please test the [`bugfix-2.0.x` branch](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.0.x.zip) to see where it stands. If the problem has been resolved then we can close this issue. If the issue isn't resolved yet, then we should investigate further.

**Comment by thinkyhead** [comment] 2021-09-11 07:08
This seems to be solved if you enable `USE_ZMIN_PLUG`. If that works for you then this can be closed.

**Comment by thinkyhead** [comment] 2021-09-11 07:46
I found a more proper solution, and will push a patch shortly. Please test the `bugfix-2.0.x` branch to see where it stands. If the problem has been resolved then we can close this issue. If the issue isn't resolved yet, then we can investigate further.

**Comment by thinkyhead** [comment] 2021-09-11 07:50
You may want to enable `HOST_ACTION_COMMANDS` when updating your configurations.

**Closed as completed** 2021-09-14 02:09 UTC
Labels: C: Configuration
