### ISSUE TITLE
[BUG] Lin_Advance causes erratic extruder 

### ISSUE THREAD

**Issue by rq3** [MarlinFirmware/Marlin#27185] opened 2024-06-17 20:10 UTC
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Enabling Lin_Advance causes erratic extruder operation. The extruder appears to randomly reverse direction for a random number of steps, even if there are no retractions in the g-code.

### Bug Timeline

Appears in all 2.1.2.3 bugfixes.

### Expected behavior

The extruder should operate smoothly.

### Actual behavior

The extruder is very erratic, randomly reverses direction, and generally acts as if the stepper commands and/or stepper current were wildly incorrect.

### Steps to Reproduce

1) Download and install the latest bugfix (Jun 17, 2024).
2) Attempt to print known good g-code.
3) Hear and see inappropriate extruder action.
4) Disable Lin_Advance in configuration_adv.h
5) Compile and re-load firmware
6) Observe proper extruder action.

### Version of Marlin Firmware

latest bugfix June 17, 2024

### Printer model

Anycubic Predator

### Electronics

Trigorilla Pro (STM32F1)

### LCD/Controller

stock

### Other add-ons

none

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Configuration.zip](https://github.com/user-attachments/files/15876675/Configuration.zip)

**Comment by thisiskeithb** [comment] 2024-06-17 20:12
Duplicate of #27126

**Closed as completed by thisiskeithb** 2024-06-17 20:12 UTC
