### ISSUE TITLE
Filament runout sensor turning off

### ISSUE THREAD

**Issue by tommylux** [MarlinFirmware/Marlin#26386] opened 2023-11-02 11:39 UTC
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

I would like to re-open issue 25351 (I can't it's locked!).

My additions to the issue:
After M600 command is issued and filament has been re-loaded, there is only 'Purge More' or 'Filament Runout ON'.

Expecting to see 'Continue option', this appears briefly when you toggle 'Filament Runout' to OFF (which sets to off and continues. If you attempt to switch back on, it immediately goes into a M600 process again.

In my opinion, both 'Filament Runout' Toggle and 'Continue' commands are currently occupying line 2, 'Filament Runout' text is taking precedence over 'Continue' and both commands are run when hitting line 2

### Bug Timeline

Sort of both a new issue reporting but this happens in the older 2.0.x marlin firmware

### Expected behavior

I expect to see a Continue button option in the on screen menu.

### Actual behavior

As described above the Filament Runout sensor turns OFF

### Steps to Reproduce

Start a print and let the Filament runout sensor load the filament then the error or issue should show up in the menu screen that is displayed.

Runout sensor is triggered:
![image](https://github.com/MarlinFirmware/Marlin/assets/19841675/7f018872-2713-47ae-8823-8c182c959f4e)

After filament change it provides resume options, but no option to continue.
![image](https://github.com/MarlinFirmware/Marlin/assets/19841675/ba42c775-0418-47ed-bf05-b1e44610da8f)

Continue is only accessible when toggling runout sensor
![image](https://github.com/MarlinFirmware/Marlin/assets/19841675/ae32366c-47bc-4afe-999a-1cf58d3b9b5d)
![image](https://github.com/MarlinFirmware/Marlin/assets/19841675/74755d14-0271-4d85-a492-1ad186128ecb)

Print then continues but runout sensor is now turned off
![image](https://github.com/MarlinFirmware/Marlin/assets/19841675/494faf07-e880-4305-9eef-df47cc4510ad)

Switching to on causes another M600 process:
![image](https://github.com/MarlinFirmware/Marlin/assets/19841675/f3741aa2-d5bb-45e4-b457-e994fadbfba4)
![image](https://github.com/MarlinFirmware/Marlin/assets/19841675/6382cfc2-4e4e-4ba0-952f-79cc61e2c9d5)

### Version of Marlin Firmware

2.1.2.1

### Printer model

A20T

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.
- 
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/13238983/Configuration.zip)

Only relevant sections for filament runout script include FILAMENT_RUNOUT_SCRIPT = "M600 T%c"

### Additional information & file uploads

3 Runout sensors connected to pins 66,67,54.

**Comment by ellensp** [comment] 2023-11-02 11:50
No config files provided
~No Images of what you talking about provided~ Updated
~No details of what display your using provided~ Updated
No details on how you have the runout sensor connected

Please provide all these details.

Issue https://github.com/MarlinFirmware/Marlin/issues/25351 was closed as it looking like a support question, not a bug. It still looks like a support issue not a bug...

**Comment by tommylux** [comment] 2023-11-02 12:08
> No config files provided No Images of what you talking about provided No details of what display your using provided No details on how you have the runout sensor connected
> 
> Please provide all these details.
> 
> Issue #25351 was closed as it looking like a support question, not a bug. It still looks like a support issue not a bug...

Hopefully more info now provided in details above.

**Comment by ellensp** [comment] 2023-11-02 12:24
And your config files?  So we can attempt to reproduce this ??

**Comment by tommylux** [comment] 2023-11-02 12:36
> And your config files?  So we can attempt to reproduce this ??

Sure I will provide config files later. Perhaps a combination of multiple parameters are at play with regards to Mixing extruder or whatnot, though I wouldn't have thought so since there is nothing that can be configured to alter the behaviour of M600 in config.

**Comment by tommylux** [comment] 2023-11-02 13:09
Hopefully all infomation you require has now been provided.

My guess is something to do with
host_actions.cpp..
Case 1 -"Continue" / "Disable Runout" button. Perhaps these should be seporate.

Or maybe something to do with DRAW_Button position for Continue?

**Comment by ellensp** [comment] 2023-11-02 13:18
The provided Config files says BOARD_GT2560_V4_A20
Where as previous issue says you have BTT Octopus Pro 429

Please clarify

Also do you have a V1 or the V2 run out sensor ?

**Comment by thomasluxton** [comment] 2023-11-02 13:21
> The provided Config files says BOARD_GT2560_V4_A20 Where as previous issue says you have BTT Octopus Pro 429
> 
> Please clarify
> 
> Also do you have a V1 or the V2 run out sensor ?

I do not have a BTT Octopus Pro 429. I have a GT2560_V4. The other ticket referenced is a different user having the same issue with Marlin.

**Comment by thomasluxton** [comment] 2023-11-02 13:22
I do not know if it is a v1 or v2 run out sensor, but I can tell you that there is example Geeetech A20T config files which I always reference if that helps.

**Comment by ellensp** [comment] 2023-11-02 13:27
V1 looks like 

<img src="https://www.jacksfilament.com/media/image/product/6413/md/12036~2.jpg">

While V2 looks like 

<img src="https://cdn.shopify.com/s/files/1/0550/2209/2502/files/25_13368136-5213-4418-a15b-9e8c22027e7f.png">

**Comment by tommylux** [comment] 2023-11-02 13:38
Like this..
![image](https://github.com/MarlinFirmware/Marlin/assets/19841675/756f7b06-3f6d-4766-8515-74414e7defde)

**Comment by ellensp** [comment] 2023-11-02 13:40
Referencing the other issue has lead me astray. 
Not a Octopus controller or a BTT run out sensor

**Comment by tommylux** [comment] 2023-11-03 07:49
> Referencing the other issue has lead me astray. 
> 
> Not a Octopus controller or a BTT run out sensor   
> 
> 

I believe it is an interface issue.. ie it happens regardless of the model of the runout sensor.

In fact, I don't think it has anything to do with the runout sensor. You can trigger the behaviour with M600 regardless of the runout sensor pin. 

I would suggest that we look at M600 behaviour in the first instance as I don't believe it has anything to do with run out sensor.

I've suggested looking at certain file, the 'case 1' combines 'continue' and 'runout sensor state', which both seem to take line 2 of the UI. I believe this is the right track to troubleshoot the issue.

**Comment by tommylux** [comment] 2023-11-03 07:54
> Referencing the other issue has lead me astray. 
> 
> Not a Octopus controller or a BTT run out sensor   
> 
> 

Likewise referencing free original issue was 100% the right thing to do. It demonstrates the same behaviour when M600 is triggered, and that other people have experienced the same issue.

We're meant to search for issues first to see if they are being worked on before logging new issues.

**Comment by thinkyhead** [comment] 2023-11-05 09:04
I took a quick look at the code and pushed a possible fix at #26394 so have a look at that and see if it fixes the issue for you.

**Closed as completed** 2023-11-05 18:30 UTC
Labels: F: Filament Sensor
