### ISSUE TITLE
[FR] Set Z_MAX_POS at runtime

### ISSUE THREAD

**Issue by Heinz-Loepmeier** [MarlinFirmware/Marlin#26324] opened 2023-10-05 10:24 UTC
### Describe the feature you want

I'm using a hardware Z-max endstop for homing my Z-axis.
Currently I have no way of ajusting max Z position/ max Z travel.
Best I can do is using Homing offsets via LCD, but that only works in one direction. (Can't enter negative values, connecting via host and entering negative values into eeprom work, but I love to do that via LCD)

Other firmwares use 'Set current position as Z0.0' function, that works as well.

### Additional context

I'm using Marlin 2.1

**Comment by classicrocker883** [comment] 2023-10-05 23:40
what printer is this for? and what LCD, what UI, if you compile your own firmware can you post your config files, or link to any examples?

**Comment by Heinz-Loepmeier** [comment] 2023-10-06 06:41
> what printer is this for? and what LCD, what UI, if you compile your own firmware can you post your config files, or link to any examples?

i3 style printer with max Z enstop + 'RepRapDiscount Full Graphic Smart Controller' LCD.  
Here are the configs: https://github.com/Heinz-Loepmeier/Marlin-2.1-MKS-Gen-L-2.1  

Looks like @thinkyhead already thought about the same thing https://github.com/MarlinFirmware/Marlin/issues/863 , but forgot about us zmax endstop users.

**Comment by thisiskeithb** [comment] 2024-09-06 01:21
Duplicate of https://github.com/MarlinFirmware/Marlin/issues/25582

**Closed as completed by thisiskeithb** 2024-09-06 01:21 UTC
Labels: T: Feature Request
