### ISSUE TITLE
ABL causing Z positioning issues after M420/G29

### ISSUE THREAD

**Issue by chorca** [MarlinFirmware/Marlin#5666] opened 2017-01-06 08:59 UTC
### Overview
Running the latest RCBugfix of RC8, I'm having problems getting ABL to work properly. I'm unable to get the printer to properly print after running a Bilinear Mesh level routine. The Z axis appears to either be zeroed incorrectly, or is stepping without checking it's real location.

### Environment
My printer is a custom CoreXY design. I'm currently using Megatronics 2.0 and the associated board file, along with a BLTouch to act as a Z homing probe as well as ABL probe. Current config files can be found here: [marlinconf.zip](https://github.com/MarlinFirmware/Marlin/files/689370/marlinconf.zip)

I have ABL enabled (attempted both with and without fade enabled), BLTouch configured to a custom pin on the Megatronics board (45), and EEPROM enabled on the board. I have tested the EEPROM facilities and they are working, as is the grid readout I'm seeing from the ABL routine.

### Issue
After powering on the printer, performing a G28 to home all axis, a M501 to load EEPROM settings, an M420 S1 to enable the grid leveling matrix, and attempting a print, the Z axis begins running upwards until it hits physical limits and continues to do so past the max size of the printer. This occurs at the first G1 Zxxx command sent to the machine after a M420 S1.

At the same time, checking the printer's assumed location of the head after issuing the M420 S1 command shows that it has reset the Z axis from it's usual after-homing safe height (17mm above zero) to 0.00. The printer is instructed to move 0.07mm upwards, and it begins to drive upwards forever.

Alternatively, attempting a print immediately after issuing a G29 to perform the ABL will not result in the Z axis running upwards forever, but it does reset Z's real 17mm height to 0 and cause the printer to air print.

### Example 1
ABL Grid already created and stored via G29, M500. After reset, attempting to print
```
Send: G28
Recv: X:311.00 Y:310.00 Z:17.00 E:0.00 Count A: 99360 B:160 Z:13600
Recv: ok
```
After homing, Z is at 'safe height'
```
Send: M420 S1
Recv: echo:Bed Leveling On
Recv: ok
```
Enabled Bed Leveling from M420. The same issue occurs whether or not an M501 is issued beforehand
```
Send: M114
Recv: X:311.00 Y:310.00 Z:0.00 E:0.00 Count A: 99360 B:160 Z:13600
Recv: ok
```
Here the machine shows Z has been reset to 0, even though the motors have not moved.
```
Send: M104 S190 T0
Recv: ok
Send: M109 S190 T0
Recv:  T:187.3 /190.0 B:50.9 /50.0 @:65 B@:0 W:9
Recv:  T:187.8 /190.0 B:50.9 /50.0 @:60 B@:0 W:8
Recv:  T:188.5 /190.0 B:50.8 /50.0 @:53 B@:0 W:7
Recv:  T:189.1 /190.0 B:50.7 /50.0 @:46 B@:0 W:6
Recv:  T:189.5 /190.0 B:50.7 /50.0 @:42 B@:0 W:5
Recv:  T:190.0 /190.0 B:50.7 /50.0 @:37 B@:0 W:4
Recv:  T:190.5 /190.0 B:50.7 /50.0 @:32 B@:0 W:3
Recv:  T:191.1 /190.0 B:50.7 /50.0 @:27 B@:0 W:2
Recv:  T:191.6 /190.0 B:50.7 /50.0 @:20 B@:0 W:1
Recv:  T:191.6 /190.0 B:50.7 /50.0 @:23 B@:0 W:0
Recv: ok
Send: G92 E0
Recv: X:311.00 Y:310.00 Z:17.00 E:0.00 Count A: 99360 B:160 Z:13600
Recv: ok
Send: M114
Recv: X:311.00 Y:310.00 Z:17.00 E:0.00 Count A: 99360 B:160 Z:13600
Recv: ok
Send: G1 E-2.0000 F1500
Recv: ok
Send: M114
Recv: X:311.00 Y:310.00 Z:17.00 E:-2.00 Count A: 99360 B:160 Z:13600
Recv: ok
Send: G1 Z0.070 F1002
Recv: ok
```
Here, printer begins running Z full speed positive, I send a few M114s to see where it thinks it is
```
Send: M114
Recv: X:311.00 Y:310.00 Z:0.07 E:-2.00 Count A: 99360 B:160 Z:68659
Recv: ok
Send: M114
Recv: X:311.00 Y:310.00 Z:0.07 E:-2.00 Count A: 99360 B:160 Z:103871
Recv: ok
Send: M114
Recv: X:311.00 Y:310.00 Z:0.07 E:-2.00 Count A: 99360 B:160 Z:130731
Recv: ok
```
Count increasing, but Z height not changing.

### Example 2
Machine just reset, issuing G29 and subsequently printing:

```
Send: G28
Recv: X:311.00 Y:310.00 Z:17.00 E:0.00 Count A: 99360 B:160 Z:13600
Recv: ok
Send: G29
[...]
Recv: Bilinear Leveling Grid:
Recv:       0     1     2     3     4     5     6     7
Recv:  0 +0.56 +0.41 +0.19 +0.06 +0.00 +0.02 +0.16 +0.34
Recv:  1 +0.52 +0.38 +0.19 +0.10 -0.01 +0.04 +0.16 +0.32
Recv:  2 +0.47 +0.34 +0.21 +0.09 +0.04 +0.04 +0.14 +0.29
Recv:  3 +0.39 +0.29 +0.14 +0.01 -0.04 +0.01 +0.11 +0.25
Recv:  4 +0.35 +0.28 +0.15 +0.09 +0.01 +0.03 +0.12 +0.30
Recv:  5 +0.33 +0.27 +0.17 +0.05 +0.03 +0.03 +0.14 +0.33
Recv:  6 +0.38 +0.28 +0.13 +0.01 -0.03 +0.02 +0.18 +0.46
Recv:  7 +0.44 +0.31 +0.19 +0.06 +0.03 +0.10 +0.33 +0.69
Recv: 
Recv: Subdivided with CATMULL ROM Leveling Grid:
Recv:         0        1        2        3        4        5        6        7        8        9       10       11       12       13       14       15       16       17       18       19       20       21
Recv:  0 +0.56000 +0.51194 +0.46389 +0.40875 +0.33866 +0.26148 +0.19375 +0.14148 +0.09866 +0.06375 +0.03620 +0.01657 +0.00500 -0.00042 +0.00222 +0.01875 +0.05431 +0.10375 +0.15750 +0.21380 +0.27440 +0.33500
Recv:  1 +0.54810 +0.50142 +0.45474 +0.40130 +0.33317 +0.25828 +0.19361 +0.14693 +0.11048 +0.07796 +0.04448 +0.01494 -0.00227 -0.00392 +0.00677 +0.02856 +0.06318 +0.10890 +0.15931 +0.21381 +0.27299 +0.33218
Recv:  2 +0.53620 +0.49090 +0.44559 +0.39384 +0.32768 +0.25507 +0.19347 +0.15238 +0.12230 +0.09218 +0.05276 +0.01330 -0.00954 -0.00742 +0.01132 +0.03838 +0.07206 +0.11406 +0.16111 +0.21382 +0.27159 +0.32935
Recv:  3 +0.52250 +0.47810 +0.43370 +0.38375 +0.32102 +0.25273 +0.19500 +0.15736 +0.13028 +0.10125 +0.05931 +0.01542 -0.01000 -0.00620 +0.01606 +0.04500 +0.07708 +0.11583 +0.16000 +0.21097 +0.26736 +0.32375
Recv:  4 +0.50653 +0.46178 +0.41704 +0.36907 +0.31324 +0.25418 +0.20269 +0.16488 +0.13463 +0.10431 +0.06612 +0.02787 +0.00528 +0.00643 +0.02325 +0.04727 +0.07611 +0.11216 +0.15407 +0.20336 +0.25851 +0.31366
Recv:  5 +0.48875 +0.44319 +0.39763 +0.35176 +0.30428 +0.25650 +0.21204 +0.17192 +0.13513 +0.10222 +0.07120 +0.04407 +0.02736 +0.02378 +0.03062 +0.04634 +0.07129 +0.10511 +0.14523 +0.19289 +0.24684 +0.30079
Recv:  6 +0.46875 +0.42380 +0.37884 +0.33500 +0.29282 +0.25176 +0.21125 +0.16898 +0.12727 +0.09250 +0.06681 +0.04806 +0.03625 +0.03046 +0.03162 +0.04250 +0.06514 +0.09750 +0.13625 +0.18241 +0.23495 +0.28750
Recv:  7 +0.44444 +0.40267 +0.36091 +0.31875 +0.27573 +0.23233 +0.18958 +0.14534 +0.10174 +0.06630 +0.04174 +0.02533 +0.01634 +0.01415 +0.01938 +0.03315 +0.05682 +0.08904 +0.12685 +0.17115 +0.22104 +0.27093
Recv:  8 +0.41792 +0.38076 +0.34360 +0.30306 +0.25614 +0.20585 +0.15778 +0.11171 +0.06785 +0.03245 +0.00719 -0.00961 -0.01676 -0.01282 +0.00076 +0.02088 +0.04718 +0.08002 +0.11731 +0.15988 +0.20691 +0.25394
Recv:  9 +0.39500 +0.36231 +0.32963 +0.29125 +0.24213 +0.18731 +0.13625 +0.09074 +0.04898 +0.01500 -0.01102 -0.02926 -0.03625 -0.02884 -0.01019 +0.01375 +0.04130 +0.07412 +0.11125 +0.15380 +0.20065 +0.24750
Recv: 10 +0.37810 +0.34958 +0.32106 +0.28602 +0.23837 +0.18420 +0.13523 +0.09544 +0.06086 +0.03130 +0.00454 -0.01719 -0.02745 -0.02210 -0.00528 +0.01699 +0.04248 +0.07342 +0.11056 +0.15620 +0.20803 +0.25986
Recv: 11 +0.36481 +0.34033 +0.31584 +0.28468 +0.24019 +0.18902 +0.14449 +0.11281 +0.08776 +0.06398 +0.03644 +0.01017 -0.00505 -0.00441 +0.00729 +0.02537 +0.04741 +0.07585 +0.11333 +0.16378 +0.22328 +0.28278
Recv: 12 +0.35375 +0.33213 +0.31051 +0.28250 +0.24162 +0.19435 +0.15375 +0.12648 +0.10588 +0.08500 +0.05815 +0.03102 +0.01375 +0.01046 +0.01704 +0.03125 +0.05125 +0.07889 +0.11750 +0.17185 +0.23718 +0.30250
Recv: 13 +0.34278 +0.32251 +0.30224 +0.27657 +0.24065 +0.19932 +0.16181 +0.13154 +0.10508 +0.08130 +0.05837 +0.03812 +0.02486 +0.01926 +0.02066 +0.03139 +0.05172 +0.08138 +0.12185 +0.17724 +0.24343 +0.30963
Recv: 14 +0.33403 +0.31395 +0.29387 +0.26981 +0.23929 +0.20480 +0.16986 +0.13290 +0.09551 +0.06593 +0.04841 +0.03870 +0.03236 +0.02524 +0.02147 +0.02903 +0.05110 +0.08449 +0.12759 +0.18311 +0.24834 +0.31356
Recv: 15 +0.33250 +0.31148 +0.29046 +0.26625 +0.23769 +0.20593 +0.17125 +0.12898 +0.08380 +0.05000 +0.03565 +0.03269 +0.03125 +0.02431 +0.01889 +0.02625 +0.05134 +0.08921 +0.13625 +0.19431 +0.26153 +0.32875
Recv: 16 +0.34144 +0.31813 +0.29483 +0.26755 +0.23416 +0.19680 +0.15782 +0.11367 +0.06790 +0.03361 +0.01794 +0.01376 +0.01273 +0.00878 +0.00800 +0.02028 +0.04999 +0.09277 +0.14546 +0.21032 +0.28509 +0.35986
Recv: 17 +0.35759 +0.33088 +0.30417 +0.27204 +0.23039 +0.18332 +0.13773 +0.09306 +0.04986 +0.01667 -0.00255 -0.01177 -0.01440 -0.01364 -0.00629 +0.01389 +0.04950 +0.09794 +0.15759 +0.23166 +0.31694 +0.40222
Recv: 18 +0.37625 +0.34569 +0.31514 +0.27875 +0.23148 +0.17838 +0.12875 +0.08389 +0.04250 +0.01000 -0.01199 -0.02509 -0.02875 -0.02398 -0.00977 +0.01750 +0.05926 +0.11407 +0.18125 +0.26468 +0.36046 +0.45625
Recv: 19 +0.39667 +0.36192 +0.32718 +0.28810 +0.24077 +0.18910 +0.14051 +0.09553 +0.05363 +0.02065 -0.00206 -0.01586 -0.01894 -0.01188 +0.00588 +0.03792 +0.08580 +0.14794 +0.22315 +0.31538 +0.42068 +0.52597
Recv: 20 +0.41958 +0.38022 +0.34086 +0.29968 +0.25492 +0.20835 +0.16338 +0.11860 +0.07543 +0.04157 +0.01892 +0.00559 +0.00366 +0.01230 +0.03234 +0.06833 +0.12257 +0.19277 +0.27657 +0.37776 +0.49256 +0.60736
Recv: 21 +0.44250 +0.39852 +0.35454 +0.31125 +0.26907 +0.22759 +0.18625 +0.14167 +0.09722 +0.06250 +0.03991 +0.02704 +0.02625 +0.03648 +0.05880 +0.09875 +0.15935 +0.23759 +0.33000 +0.44014 +0.56444 +0.68875
Recv: 
Recv: X:556.00 Y:605.00 Z:0.00 E:0.00 Count A: 185760 B:-7840 Z:13600
Recv: ok
```
This shows that even though it had ended the sensing at a 'safe height' from the probe stow, Z is still set to 0, although the nozzle is actually 17mm away from the bed.
Subsequently attempting a print will cause the printer to begin printing at that height (17mm + 0.07mm for first layer)

### Tests
I have attempted to enable and disable fade, and noticed that with fade ENABLED in configuration.h and issuing a fade parameter to the M420 command, (M420 Z2 S1), Z would NOT be reset to zero (as seen via M114), but the head would still 'fly away' upon issuing a G1 Zxxx command.

Printing directly after a G29 command has different results than printing after a M420 S1 command, but both do not work.

### EEPROM settings
[eeprom.txt](https://github.com/MarlinFirmware/Marlin/files/689425/eeprom.txt)

**Comment by manianac** [comment] 2017-01-06 11:08
When you compile, how much minimum memory usage does it report?  7x7 grid w/ subdividing is pretty massive.

**Comment by chorca** [comment] 2017-01-06 19:02
```
Sketch uses 77674 bytes (30%) of program storage space. Maximum is 253952 bytes.
Global variables use 5623 bytes (68%) of dynamic memory, leaving 2569 bytes for local variables. Maximum is 8192 bytes.
```
The printer bed is 600x600mm, and has a bit of a dip to it, so that's why I'm using a large number of points.

I tried lowering the points from 8 to 7, and that seemed to change behavior:
```
Sketch uses 77734 bytes (30%) of program storage space. Maximum is 253952 bytes.
Global variables use 4995 bytes (60%) of dynamic memory, leaving 3197 bytes for local variables. Maximum is 8192 bytes.
```
Now printing is working correctly, but with bilinear enabled, it does not seem to be compensating enough.. some areas are far too low, others are too high, even after enabling leveling. Z motors are running during print moves but it does not seem like enough.
For this issue though, it seems that the memory might be the cause, will do more testing on lingering unevenness.

**Comment by manianac** [comment] 2017-01-07 00:53
Try disabling bed subdivision, even at 7 you could be running out of memory (you could check with the M100 gcode if you enable it).

Try upping your points to 10/11 after disabling subdivision as a test.

**Comment by Koshu** [comment] 2017-01-08 09:16
Same Problem here with a 5x5 Grid, biliniar bed leveling but with subdivisions disabled. M420 S1 sets Z to zero regardless of its position. Issuing a another homeing after that disables the bed leveling again.

**Comment by chorca** [comment] 2017-01-08 09:26
I'm actually not able to compile with more than 8 points, it alerts for low memory in Arduino and so I haven't attempted it.
Even at 7 points I'm running into odd issues.. M501 + M420 S1 still sets Z to 0 wherever it's at, and runs the head up forever on printing, but doing a G29 to redo the entire probing sequence and then printing seems to work.

I can try and lower it even further and see if that helps, but may not very accurately map my bed at this size.

**Comment by Koshu** [comment] 2017-01-08 09:40
Just tested again with AUTO_BED_LEVELING_LINEAR which seems fine. It only occurs if bilinear is used.

**Comment by chorca** [comment] 2017-01-08 10:28
Even more oddness. If I restart the board, do an G28 to home, G29 to probe the bed, then attempt a print, it will start printing in the air (Z reset to 0). If I then stop the print, and try and do a G28, it does not try and find safe home first, but it starts running Z negative into the bed, without moving to a safe probe deploy distance first. If Z was actually reset, it should have gone +15mm (as set in the configuration.h file) but it just instantly starts running negative.

**Comment by Koshu** [comment] 2017-01-08 10:39
Read a bit of the code. I never did any coding for marlin and i am completely unfamiliar with it. So these are not more than guesses but I found i few things seems weird to me. 

in Marlin_main.cpp function set_bed_leveling_enabled line 2240 and following:
 
```
#elif HAS_ABL

      if (enable != planner.abl_enabled) {
        planner.abl_enabled = enable;
        if (!enable)
          set_current_from_steppers_for_axis(
            #if ABL_PLANAR
              ALL_AXES
            #else
              Z_AXIS
            #endif
          );
        else
          planner.unapply_leveling(current_position);
      }

    #endif
```

The enable variable enables the ABL, however because of  if (!enable) it runs planner.unapply_leveling(current_position) the moment ABL gets enabled. Is this correct? I would had assumed that unapply_leveling should be called the moment ABL gets disabled.

Further in planner.cpp function unapply_leveling line 627 and following:
```
 #elif ENABLED(AUTO_BED_LEVELING_BILINEAR)

      #if ENABLED(ENABLE_LEVELING_FADE_HEIGHT)
        const float c = bilinear_z_offset(logical);
        logical[Z_AXIS] = (z_fade_height * (RAW_Z_POSITION(logical[Z_AXIS]) - c)) / (z_fade_height - c);
      #else
        logical[Z_AXIS] -= bilinear_z_offset(logical);
      #endif

    #endif
```

If ENABLE_LEVELING_FADE_HEIGHT is not defined (disabled) the calculated offset gets subtracted from the current position (is "logical" the current position?). However, if ENABLE_LEVELING_FADE_HEIGHT is defined (enabled) the logical position is completely overwritten. Shouldn't there be an "-=" as well? Especially if z_fade_height is set to zero, this would zero the z_position. Also i don't understand the (z_fade_height - c) part of that line. Couldn't this result in an devide by zero error?

**Comment by manianac** [comment] 2017-01-08 17:04
>The enable variable enables the ABL, however because of if (!enable) it runs planner.unapply_leveling(current_position) the moment ABL gets enabled. Is this correct? I would had assumed that unapply_leveling should be called the moment ABL gets disabled.

I could be way off, but I believe the intention there was to update current position with the leveling offset.  On my printer I have an endstop switch on the Z axis that stops above the bed, but use the probe to measure below this switch.  So when a `G28` is issued, Z0 is above the bed.  But once ABL is enabled with `M420`, `unapply_leveling` updates the logical Z position (in this case as a positive number, since we're above the bed).  That way if a move to Z0 is issued, we will now actually end up at the bed.

>Shouldn't there be an "-=" as well? Especially if z_fade_height is set to zero, this would zero the z_position. Also i don't understand the (z_fade_height - c) part of that line. Couldn't this result in an devide by zero error?

I don't think it should be a "-=" as the Z position is already in the equation, otherwise you would be subtracting the entire Z axis height from itself.  Consider this example:
```
fade height = 10
bilinear offset = 0.2
At a Z axis height of 5 it is updated to ~4.89
At a Z axis height of 9 it is updated to ~8.97
```
So the math is sound, it is fading as it should.  A "-=" operator would kill this.

I am interested in the potential divide by zero, but curious why the cpu doesn't reset or the watchdog catch it.  While I haven't found a situation for the abl grid to have the same value as the z_fade_height, it would be catastrophic.

@Koshu and @chorca, I suppose you could try with fading disabled, and see if it still occurs?

**Comment by manianac** [comment] 2017-01-08 17:05
>Even more oddness. If I restart the board, do an G28 to home, G29 to probe the bed, then attempt a print, it will start printing in the air (Z reset to 0). If I then stop the print, and try and do a G28, it does not try and find safe home first, but it starts running Z negative into the bed, without moving to a safe probe deploy distance first. If Z was actually reset, it should have gone +15mm (as set in the configuration.h file) but it just instantly starts running negative.

I was experiencing the same thing not too long back when the ABL saving to EEPROM PR was being merged.  While I never found the cause, what are you compiling with?  I had a sneaking suspicion I had a gcc bug or something odd, and had to update.

**Comment by Koshu** [comment] 2017-01-08 18:08
Unfortunatly I can't test for now because i have a problem with my probe (not related to this bug). 

However, I still don't quite understand the working of the ABL planner. 

`(z_fade_height * (RAW_Z_POSITION(logical[Z_AXIS]) - c)) / (z_fade_height - c);`

What if z_fade_height is set to zero? The result will always be zero. Especially since it is initialized as such:

```
#if ENABLED(ENABLE_LEVELING_FADE_HEIGHT)
  float Planner::z_fade_height = 0.0,
        Planner::inverse_z_fade_height = 0.0;
#endif
```

Which in regards to the documentation in the code is completely acceptable:

```
  /**
   * M420: Enable/Disable Bed Leveling and/or set the Z fade height.
   *
   *       S[bool]   Turns leveling on or off
   *       Z[height] Sets the Z fade height (0 or none to disable)
   */
```

This also fits the observation of @chorca :

> I have attempted to enable and disable fade, and noticed that with fade ENABLED in configuration.h and issuing a fade parameter to the M420 command, (M420 Z2 S1), Z would NOT be reset to zero (as seen via M114), but the head would still 'fly away' upon issuing a G1 Zxxx command.

About the divide by zero problem: It might by unlikely to happen and that's why nobody noticed it until now. However, in my experience equations that could result in a divide by zero error are a very bad idea. Because not only could it crash everything (literally), the problem already start if it gets close to zero. The result would tend to infinite. With limited precision of float this often has very weird side effects.

Edit:
P.S. While i tested the ABL i had the fading enabled in the code but never set it to an value, so it probably was always zero in my tests.

**Comment by manianac** [comment] 2017-01-08 18:23
I'm still unable to duplicate any of these concerns, with varying Z fade heights (including zero) and movements.  Maybe @thinkyhead can chime in if he has a zero check somewhere else that I'm missing, I only see one in apply_bed_leveling.

@Koshu why not add a zero-check and see if the problem still occurs?

**Comment by Koshu** [comment] 2017-01-08 18:25
Would like to but first i need a new probe :/

**Comment by manianac** [comment] 2017-01-08 18:38
My mistake, forgot you mentioned that.  You could still test it by switching the probe endstop yourself, to fill in some bogus values to the table?  Also don't forget, if you setup a manual mesh bed level table (uses the fade height code) you could test it there.

**Comment by Koshu** [comment] 2017-01-08 18:46
I was able to test something. Just noticed that the manual_bed_leveling uses the same line of code (using the manual method for now). I could reproduce the error here as well but MBL needs to be activated by M420:

```
>>> G28
SENDING:G28
echo:busy: processing
echo:busy: processing
echo:busy: processing
echo:busy: processing
>>> M114
SENDING:M114
X:0.00 Y:0.00 Z:0.00 E:0.00 Count X: 0 Y:0 Z:1600
>>> G1 Z15
SENDING:G1 Z15
>>> M114
SENDING:M114
X:0.00 Y:0.00 Z:15.00 E:0.00 Count X: 0 Y:0 Z:7214
>>> M420 S0
SENDING:M420 S0
>>> M114
SENDING:M114
X:0.00 Y:0.00 Z:18.03 E:0.00 Count X: 0 Y:0 Z:7214
>>> M420 S1
SENDING:M420 S1
>>> M114
SENDING:M114
X:0.00 Y:0.00 Z:0.00 E:0.00 Count X: 0 Y:0 Z:7214
```

Even so Z was at position 15, after disabling and re-enabling MBL it is set to zero. So enabling via M420 only works if Z is at zero to start with.

**Comment by Koshu** [comment] 2017-01-08 18:49
Update: Repeated the test with fade of 1.0. Everything works fine:

```
>>> G28
SENDING:G28
echo:busy: processing
echo:busy: processing
echo:busy: processing
echo:busy: processing
>>> M114
SENDING:M114
X:0.00 Y:0.00 Z:0.00 E:0.00 Count X: 0 Y:0 Z:1600
>>> G1 Z15
SENDING:G1 Z15
>>> M420 S0 Z1
SENDING:M420 S0 Z1
>>> M114
SENDING:M114
X:0.00 Y:0.00 Z:18.03 E:0.00 Count X: 0 Y:0 Z:7214
>>> M420 S1 Z1
SENDING:M420 S1 Z1
>>> M114
SENDING:M114
X:0.00 Y:0.00 Z:18.03 E:0.00 Count X: 0 Y:0 Z:7214
```

Edit: Sorry it doesn't look right. it should be 15 in the last line not 18.03. That also wrong but in a different way.

Edit 2: Retested with fade of 3, same result as with 1.

**Comment by Koshu** [comment] 2017-01-08 19:01
Thought about it for a moment. In my opinion there is something wrong with that line in ABL as well as in MBL. While the calculation of the fading is quite straight forward to apply it is anything but trivial to reverse, because the result of that calculation depends on the result of the same equation. That's what that line is trying to do. My gut tells me that should be more than a one-liner. One simple solution i can think of is to do another homing after M420 (like it happens at startup). 

But of course i might be completely wrong.

**Comment by chorca** [comment] 2017-01-08 19:21
> I suppose you could try with fading disabled, and see if it still occurs?

I have had fading disabled the whole time I've been testing, as I noticed the same thing @Koshu did, that with fade enabled and unset, Z was always reset to 0, ~~however, sending the fade parameter even with fade disabled (!) fixed that problem and enabled it to work.~~ However, I still experienced other issues like air printing.
EDIT: This does not seem to be true here. I was trying a lot of things and may have gotten this mixed up. I just re-tested and with fade disabled in configuration.h, sending a M420 Z2 S1 still resets zero.

> what are you compiling with?

Latest arduino package, 1.8.0, running on Win64.
Compiling using the "Export compiled binary" function.
I've included output from the compiler, nothing here seems bad.
[compile.txt](https://github.com/MarlinFirmware/Marlin/files/692388/compile.txt)

Including the Configuration.h again, just so this is for sure my current one:
[Configuration.txt](https://github.com/MarlinFirmware/Marlin/files/692389/Configuration.txt)

**Comment by Koshu** [comment] 2017-01-08 19:38
> I have had fading disabled the whole time I've been testing, as I noticed the same thing @Koshu did, that with fade enabled and unset, Z was always reset to 0, however, sending the fade parameter even with fade disabled (!) fixed that problem and enabled it to work. However, I still experienced other issues like air printing.

I think @manianac meant to disable it in the configuration.h. Or did i misunderstood?

**Comment by chorca** [comment] 2017-01-08 19:54
That's what I meant, it's disabled for bilinear ABL in configuration.h.

**Comment by Koshu** [comment] 2017-01-08 20:06
In MBL if fading is disabled in the configuration.h everything works fine. Just tested:

```
>>> G28
SENDING:G28
echo:busy: processing
echo:busy: processing
echo:busy: processing
echo:busy: processing
>>> M114
SENDING:M114
X:0.00 Y:0.00 Z:0.97 E:0.00 Count X: 0 Y:0 Z:1600
>>> G1 15
SENDING:G1 15
>>> G1 Z15
SENDING:G1 Z15
>>> M114
SENDING:M114
X:0.00 Y:0.00 Z:15.00 E:0.00 Count X: 0 Y:0 Z:7214
>>> M420 S0
SENDING:M420 S0
>>> M114
SENDING:M114
X:0.00 Y:0.00 Z:18.03 E:0.00 Count X: 0 Y:0 Z:7214
>>> M420 S1
SENDING:M420 S1
>>> M114
SENDING:M114
X:0.00 Y:0.00 Z:15.00 E:0.00 Count X: 0 Y:0 Z:7214
```

**Comment by chorca** [comment] 2017-01-08 20:26
Just did another test, this time with fade ENABLED in configuration.h, and specifying the fade height in M420, but Z just runs away from the bed forever.

**Comment by chorca** [comment] 2017-01-09 01:58
Doing some more debugging tonight, noticed this:
During the Z axis runaway, the Z 'distance to go' jumps suspiciously close to the max of a signed int:
```
Recv:   Planner FR:133.33 X:311.00 (0) Y:310.00 (0) Z:17.10 (0)
Send: G1 X-1 F9000
Recv:   Planner FR:150.00 X:310.00 (-160) Y:310.00 (0) Z:0.00 (2147469968)
```
Looks like something may be rolling over. The bilinear_z_offset routine is always returning 0.00, and i'm doing some more digging.

**Comment by manianac** [comment] 2017-01-09 03:11
I've noticed as well, as issuing `M420 S1` resetting Z to zero is the only thing I've duplicated thus far.  But its only for display, issuing a
```gcode
G28
G1 Z5
M420 S1
G1 Z5
```
causes it to only drop slightly for my abl grid, so it has not lost Z position.

**Comment by chorca** [comment] 2017-01-09 04:31
Bilinear subdivision seems to be the issue here, disabling it seems to be working, but I am still testing.

A quick overview of what might be at least one issue here:
`bilinear_z_offset`, called by `planner.unapply_leveling`, uses the `ABL_BG_SPACING` macro, which is defined as `bilinear_grid_spacing_virt` in Marlin_main.cpp.
This variable is initalized to an int array with its items set to 0. The only place it is set is in a G29 command, where it is set to `xGridSpacing/(BILINEAR_SUBDIVISIONS)`.
`bilinear_grid_spacing` is set in EEPROM along with other values, but `bilinear_grid_spacing_virt` does NOT get stored or recalled it seems, since it is not mentioned in configuration_store.cpp.
Because of this, it is never set (other than being initialized to 0), and therefore all offset calculations done without running a G29 prior to issuing will be dividing `x = RAW_X_POSITION(cartesian[X_AXIS]) - bilinear_start[X_AXIS]` by zero, like the one in `bilinear_z_offset`: `float ratio_x = x / ABL_BG_SPACING(X_AXIS)`
`bilinear_grid_spacing_virt` is only used by subdivision, not by plain bilinear mesh.

**Comment by chorca** [comment] 2017-01-10 20:31
Not sure if this is at all related, but after installing RC8, i'm getting MINTEMP errors at random times in the print, the earliest within about 10 minutes of starting. I've hooked an oscilloscope up to the thermistor lines and at 20Ms/s I'm not seeing any sort of transients or disconnects that would indicate the thermistor is the problem, not to mention this hasn't been an issue before RC8.
Looking through the code a little, but not seeing anything obvious.

**Comment by thinkyhead** [comment] 2017-04-02 14:58
Thanks, @chorca. Very good catch! I've just patched the issue.

**Closed as completed** 2017-10-31 22:36 UTC
Labels: Bug: Confirmed !, S: Solved
