### ISSUE TITLE
2nd extruder not engaging on Geeetech A20M[BUG] (bug summary)

### ISSUE THREAD

**Issue by Wakelin2** [MarlinFirmware/Marlin#22178] opened 2021-06-19 18:40 UTC
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

flash firmware to bug fix 2.0.x, now not engaging the second extruder, but still attempts to print the object (no filament comes out)

i had original firmware as i just got the geeetech now unable to find original firmware. i am currently at a stand still as i can't use the A20M until new bug is fixed 

### Bug Timeline

yesterday

### Expected behavior

i expected the update to allow both extruders to to engage still

### Actual behavior

not engaging filament blank print

### Version of Marlin Firmware

bugfix 2.0.x

### Printer model

Geeetech A20M

### Your Slicer

Cura

### Host Software

Same as my slicer

**Comment by snakesrules94** [comment] 2021-06-21 15:03
Hello,
maybe same problem as this one : https://github.com/MarlinFirmware/Marlin/issues/22166#issue-925011933

**Comment by Wakelin2** [comment] 2021-06-21 15:13
Yes but I can’t find the configuration files for 2.0.8.2 when I look into that file the 2.0.8.1 config files are in there

Sent from my iPhone

On Jun 21, 2021, at 11:03 AM, snakesrules94 ***@***.***> wrote:

﻿

Hello,
maybe same problem as this one : #22166 (comment)<https://github.com/MarlinFirmware/Marlin/issues/22166#issue-925011933>

**Comment by Wakelin2** [comment] 2021-06-21 15:21
> Hello,
> maybe same problem as this one : [#22166 (comment)](https://github.com/MarlinFirmware/Marlin/issues/22166#issue-925011933)

Do you have link to config files for 2.0.8.2

**Comment by snakesrules94** [comment] 2021-06-21 16:24
You're looking about this : https://github.com/MarlinFirmware/Configurations/archive/release-2.0.8.2.zip ?

**Comment by Wakelin2** [comment] 2021-06-21 16:29
Yes but when you look at the config files for A20M it says the config number is 2.0.8.1

**Comment by snakesrules94** [comment] 2021-06-21 18:15
I guess differences are not located in the config files and you can use the 2.0.8.2 config files with 2.08.2 firmware , even if there are still tagged 2.0.8.1.
I can confirm that both steppers for E0 & E1 are wotking fine in this version .

**Comment by slowbro** [comment] 2021-06-22 20:21
We should consolidate conversation on this topic in one thread; #22166 seems to have been the first. The problem is still under investigation.

**Comment by thisiskeithb** [comment] 2021-06-22 20:29
Duplicate of https://github.com/MarlinFirmware/Marlin/issues/22166

**Closed as completed by thisiskeithb** 2021-06-22 20:29 UTC
