### ISSUE TITLE
[BUG] MKS Nano + TFT35 — Broken Chinese (UTF)

### ISSUE THREAD

**Issue by chenxiaowei107** [MarlinFirmware/Marlin#20268] opened 2020-11-25 02:09 UTC
I used the MKS nano v1.2 motherboard and TFT35 screen，I Have _#define MKS_ROBIN_TFT35_
if i change the language to zh_CN  Chinese characters are not displayed properly. Just like this
![Cache_-48202f97c74cd0d1](https://user-images.githubusercontent.com/39343523/100173995-902b5400-2f06-11eb-9762-954a4c7afbf7.jpg)
The language English is all correct
![2222](https://user-images.githubusercontent.com/39343523/100174107-c49f1000-2f06-11eb-8536-a0534d764f83.jpg)

**Comment by ellensp** [comment] 2020-11-25 02:18
Please follow the Issue Template when filing a bug report. This includes attaching your configs:
 
```lisp
<!--

Have you read Marlin's Code of Conduct? By filing an Issue, you are expected to comply with it, including treating everyone with respect: https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/.github/code_of_conduct.md

Do you want to ask a question? Are you looking for support? Please don't post here. Instead please use the Marlin Firmware forum at http://forums.reprap.org/list.php?415 or the Marlin Facebook Group https://www.facebook.com/groups/1049718498464482/ or the Marlin Discord Server https://discord.gg/n5NJ59y.

Before filing an issue be sure to test the 1.1 and/or 2.0 "bugfix" branches to see whether the issue is already addressed.

-->

### Description

<!-- Description of the bug or requested feature -->

### Steps to Reproduce

<!-- If this is a Bug Report, please describe the steps needed to reproduce the issue -->

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

#### Additional Information

* Include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.
```

**Comment by boelle** [comment] 2020-11-25 09:31
Configurations, please
Please ZIP up your `Configuration.h` and `Configuration_adv.h` files (as
requested in the Issue template) and drop them into your next reply.
We'll check them over and see if anything is amiss.

Please test the [`bugfix-2.0.x branch`](https://github.com/MarlinFirmware/Marlin/tree/bugfix-2.0.x) to see where it stands. If the problem has been resolved then we can close this issue. If the issue isn't resolved yet, then we should investigate further.

**Comment by chenxiaowei107** [comment] 2020-11-25 14:08
Now I used bugfix-2.0.x branch ,but it's also not displayed properly
[configuration.zip](https://github.com/MarlinFirmware/Marlin/files/5597152/configuration.zip)

**Comment by rhapsodyv** [comment] 2020-12-02 20:42
@jmz52 can you take a look on this? Or point me the process to update or add a new font to color ui. 
Thanks!

**Comment by jmz52** [comment] 2020-12-03 20:03
@rhapsodyv, you need to create files with language specific glyphs for Helvetica14 and Helvetica18 fonts, define macro font name and load language specific glyphs in `MarlinUI::init_lcd()`
```
void MarlinUI::init_lcd() {
  tft.init();
  tft.set_font(MENU_FONT_NAME);
  #ifdef SYMBOLS_FONT_NAME
    tft.add_glyphs(SYMBOLS_FONT_NAME);
  #endif

// new code to load language-specific glyphs
  #ifdef TRANSLATION_FONT_NAME
    tft.add_glyphs(TRANSLATION_FONT_NAME);
  #endif
```

Character IDs should be the same as in Marlin\src\lcd\dogm\fontdata\langdata_xx.h files

**Comment by rhapsodyv** [comment] 2020-12-03 20:57
@jmz52 Thanks! 
Can you point me the direction to generate the glyphs for Helvetica? Which tool you use to select the glyphs? Or just use a standard Helvetica converted to BBX?

**Comment by rhapsodyv** [comment] 2020-12-03 21:36
Well, I don’t even know if helvética have Chinese glyphs... I need to do some research.

**Comment by jmz52** [comment] 2020-12-05 09:27
I've used Fony and bdf2u8g converter, you can find details in https://marlinfw.org/docs/development/fonts.html

You can use glyphs from other fonts if these glyphs' heigth is same or smaller than height of the main font.
See how the extra symbols are loaded from ```uint8_t Helvetica18_symbols[71]``` array.

**Comment by rhapsodyv** [comment] 2021-01-05 02:33
I had no time to work on this yet. But it must stay open.

**Comment by thinkyhead** [comment] 2021-04-15 12:17
Please test the [`bugfix-2.0.x` branch](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.0.x.zip) to see where it stands. If the problem has been resolved then we can close this issue. If the issue isn't resolved yet, then we should investigate further.

**Comment by thisiskeithb** [comment] 2022-12-08 00:25
Fixed in https://github.com/MarlinFirmware/Marlin/pull/25073

**Closed as completed by thisiskeithb** 2022-12-08 00:25 UTC
Labels: Bug: Confirmed !, C: Language, C: LCD & Controllers
