### ISSUE TITLE
[FR] Add LDO-RRLCD-A004 Screen

### ISSUE THREAD

**Issue by codiac2600** [MarlinFirmware/Marlin#17236] opened 2020-03-21 15:05 UTC
In reference to:  #17167

### Description

When trying to enable the brightness control it doesn't work with the standard REPRAP 2004 display because it doesn't have a controller for this. LDO makes an LDO-RRLCD-A004 which is a 2004 display BUT it includes the brightness adjustment capability. Prusa has enabled this in their firmware as seen here: https://github.com/prusa3d/Prusa-Firmware/pull/2270

Adding anything to enable this causes a compile error. 

My suggestion is to add the LDO screen as an option so users can enable the brightness control menu in Malrin. 

 I hope I've entered enough information to help.

### Feature Workflow

Go to the menu and change the LCDs brightness.

#### Additional Information

https://github.com/prusa3d/Prusa-Firmware/pull/2270

**Comment by ellensp** [comment] 2020-03-21 17:43
Why did you create a new FR when one already existed?   Please close this issue and add any new information to the original request.

**Comment by thisiskeithb** [comment] 2020-12-03 18:04
Duplicate of #17167

**Closed as completed by thisiskeithb** 2020-12-03 18:04 UTC
Labels: T: Feature Request
