### ISSUE TITLE
New planner.h logic broken with HAS_UBL_AND_CURVES

### ISSUE THREAD

**Issue by Roxy-3D** [MarlinFirmware/Marlin#10659] opened 2018-05-08 21:44 UTC
@thinkyhead 
I haven't looked at this other than to patch it so I can continue work on getting the RTOS under bugfix_2.0.0.    

```
    #if PLANNER_LEVELING // || HAS_UBL_AND_CURVES   // This logic is broke right now.   It results in ARG_X being undefined
                                                    // in the case HAS_UBL_AND_CURVES.  I'll leave this for now, just to get 
                                                    // the RTOS stuff workinging in bugfix_2.0.0
      /**
       * Apply leveling to transform a cartesian position
       * as it will be given to the planner and steppers.
       */
      static void apply_leveling(float &rx, float &ry, float &rz);
      FORCE_INLINE static void apply_leveling(float (&raw)[XYZ]) { apply_leveling(raw[X_AXIS], raw[Y_AXIS], raw[Z_AXIS]); }
      #if PLANNER_LEVELING
        #define ARG_X float rx
        #define ARG_Y float ry
        #define ARG_Z float rz
        static void unapply_leveling(float raw[XYZ]);
      #endif
    #else
      #define ARG_X const float &rx
      #define ARG_Y const float &ry
      #define ARG_Z const float &rz
    #endif
```

**Comment by thinkyhead** [comment] 2018-05-09 05:44
Duplicate of #10660

**Closed as completed** 2018-05-09 05:43 UTC
