### ISSUE TITLE
Mixing extruder drives only one extruder. Extruder two onwards does not move.

### ISSUE THREAD

**Issue by Decalis1979** [MarlinFirmware/Marlin#22734] opened 2021-09-09 12:07 UTC
### Did you test the latest `bugfix-2.0.x` code?

No, but I will test it now!

### Bug Description

I have a three-color mixing head. When upgrading to Marlin 2.0.9.1, only one extruder moves ("E0"). The others ("E1" and "E2") do not accept movement commands. In the previous version, it worked perfectly.

### Bug Timeline

Start with version 2.0.9.1

### Expected behavior

I expected the three of them to move

### Actual behavior

Only one moved the E0

### Version of Marlin Firmware

2.0.9.1

### Printer model

Creality Ender 3

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Cura

### Host Software

Same as my slicer

**Comment by ellensp** [comment] 2021-09-09 18:13
Duplicate of https://github.com/MarlinFirmware/Marlin/issues/22714

**Closed as completed by ellensp** 2021-09-09 18:13 UTC
