### ISSUE TITLE
[FR] Avoid G12 Nozzle Clean pass through the same brush spot

### ISSUE THREAD

**Issue by Rodrigoah** [MarlinFirmware/Marlin#18000] opened 2020-05-15 13:14 UTC
### Description

When doing a G12, be it with P1 or P2, the nozzle passes through the same spot of the brush several times, picking up rests of filament that have been already cleaned from the nozzle from the first pass

### Feature Workflow

Same as G12 but with an option in firmware to avoid return over the same path

#### Additional Information

For rectilinear movement the last stroke of the clean should be in the same direction as the first
For zig-zag movement, it should not have the second half of the movement where the nozzle backtracks its previous movement

**Comment by brucehvn** [comment] 2020-06-08 08:59
This is a duplicate of my FR #17622

**Closed as completed** 2020-06-21 00:33 UTC
