### ISSUE TITLE
[FR] (NeoPixel Background Lighting - Range)

### ISSUE THREAD

**Issue by KCGreg** [MarlinFirmware/Marlin#21768] opened 2021-05-01 20:31 UTC
### Is your feature request related to a problem? Please describe.

NO

### Are you looking for hardware support?

NO

### Describe the feature you want

First, let me say thank you!  I use Marlin on 3 3D printers as well as a CNC I built.  This is an outstanding product!  

This request is related to the NeoPixel Background Lighting Feature.  I would like to be able to define a range instead of a single NeoPixel.  I have a strip of LEDs that wraps around my z axis.  If a range could be defined instead of a single NeoPixel, I could turn on all of the NeoPixels at the top of the gantry for only overhead lighting.

Thanks for considering.

### Additional context

// Use a single NeoPixel LED for static (background) lighting
  #define NEOPIXEL_BKGD_LED_INDEX  **13**              // Index of the LED to use 
  #define NEOPIXEL_BKGD_COLOR { 255, 255, 255, 0 } // R, G, B, W
  #define NEOPIXEL_BKGD_ALWAYS_ON                  // Keep the backlight on when other NeoPixels are off
#endif

NEOPIXEL_BKGD_LED_INDEX range reference could be something like 10 - 19, for example

**Comment by ellensp** [comment] 2021-05-02 04:50
Duplicate of https://github.com/MarlinFirmware/Marlin/issues/20679

**Closed as completed by ellensp** 2021-05-02 04:50 UTC
Labels: T: Feature Request
