### ISSUE TITLE
Feature request: Export/Import settings to/from SD card txt-file

### ISSUE THREAD

**Issue by a4jp-com** [MarlinFirmware/Marlin#1185] opened 2014-12-15 12:39 UTC
Feature request: 

Can you make it so the printer can easily list all the programmed settings in a log file or export all the settings somehow?

if settings are not stored selecting the options should export settings from EEPROM first if any present there, if not take them from firmware

**Comment by boelle** [comment] 2015-04-26 12:42
This one is only doable if all the settings are stored in eeprom... initial settings should be in firmware and i dont think that you can save those? @thinkyhead ?

**Comment by CONSULitAS** [comment] 2015-04-26 21:08
@boelle @thinkyhead  I am working on a concept for storing settings in a more secure and flexible way (primary eeprom), because I had forgotten the M5xx things more than once.

Storing settings to SD is important for hardware without EEPROM. E.g. the Arduino due.

So perhaps you assign all EEPROM/settings issues to me and I think a little bit further before I will do some coding on it?

If it is clear to me, what should be the concept, I will open a new issue referencing the matching ones for discussion of the concept.

PS: There will be a small bugfix PR (and a corresponding issue) for slow main fan speeds to come. Code works well, but is in test while printing some time with it. Would like to deliver a stable solution. :-)

**Comment by thinkyhead** [comment] 2015-04-28 02:18
@CONSULitAS I just did this #1974 which is intended to make it a bit easier. Now, every option in the EEPROM has a corresponding GCode, so all you need to do is `M503 S0` and you get a blob that can be played back to reproduce all the EEPROM settings. The next trick is to make that blob save itself to SD....
- Added `M145` to set “heatup states” for the LCD menu
- Added `M420` to toggle Mesh Bed Leveling
- Added `M421` to set a single Mesh coordinate

The M420 and M421 codes could be used for any leveling equation, actually, but are currently just set up for mesh bed leveling.

**Comment by boelle** [comment] 2015-06-29 10:36
will close this one as its the same idea as in #1260

**Closed by boelle** 2015-06-29 10:36 UTC
Labels: Feature request, On Hold During Bugfix
