### ISSUE TITLE
latest bugfix-1.1.x: "Recv: ? in get_z_correction" with G29 J

### ISSUE THREAD

**Issue by 040medien** [MarlinFirmware/Marlin#7458] opened 2017-08-08 05:04 UTC
When running G29 J or G29 J2 (or J3, J4, etc.), I'm getting these error messages:
```
Recv: ? in get_z_correction(lx0=10.00, ly0=302.00)
Recv: ? in get_z_correction(lx0=197.00, ly0=302.00)
Recv: ? in get_z_correction(lx0=197.00, ly0=42.00)
Recv: ok
Recv: echo:endstops hit:  Z:0.69
```
Afterwards when I run G29 T1:
```
Send: G29 T1
Recv: Invalid Y location specified.
```

**Comment by Roxy-3D** [comment] 2017-08-08 05:12
The code in ubl_motion.cpp is complaining that you are positioning the nozzle outside of the area that the mesh knows how to correct.   As a result of this...   No correction for that move can be generated.   It looks like you are trying to probe off the mesh.

If you recompile the firmware with an appropriate bed size (and re-generate the mesh) you can make this problem go away.

> Send: G29 T1
> Recv: Invalid Y location specified.

This may be a bug.   A lot of logic was forced into ternary operators and X & Y aren't initialized all the time (any more as they should be!!!!).   This needs to be changed back to the way it was.   But resetting the machine and doing a G29 T will get you the current map.

This code was forced to look like this:  https://github.com/MarlinFirmware/Marlin/blame/bugfix-1.1.x/Marlin/ubl_G29.cpp#L1095-L1098   

The way it used to be was:  https://github.com/MarlinFirmware/Marlin/commit/3729510b1ed7d0ca4bbbedffb7600677ef4ee6fd   The way it used to be was X & Y always were set to 0 in the event the user did not specify a value.   

But because everything needs to be jammed into cryptic ternary operations, this well tested and fully working code was broken.    But I have a new strategy.  I'm going to start compressing everything possible onto one line of ternary code.   I'm going to change the way I structure code so I can facilitate the most complex logic possible onto one line of code.    That way....  It will be almost impossible for people to make changes to it....    

Here is a good example of what I'm saying.    This HAD TO BE JAMMED into a Ternary operation.

https://github.com/MarlinFirmware/Marlin/pull/7428/files/622048ffb08b716019259e56c97ff07c10a8338e#diff-e1d4995fc737943e850439c3d15e2189L195

It was too clear.  It was too easy to read and understand.   We simply can't have the average user knowing what the code does.   Let's force it into a ternary operation!

But you know what????    The person doing it couldn't even do it without making a **SERIOUS** logic mistake.   This was needed to get it back to a working state.    

https://github.com/MarlinFirmware/Marlin/pull/7430/files

I'm tied of debugging code and making sure it works correctly just to have it broken for no reason.   It is like a dog that can't walk past a fire hydrant without pissing on it.    Any piece of code that is well tested needs to be pissed on and broken.

For somebody that can't even tolerate an invisible white space at the end of a line.   For somebody that has nightmares about an extra space on the line because it makes things too difficult to understand and parse...   https://github.com/MarlinFirmware/Marlin/pull/7428#issuecomment-320023213    It think there is a question to be asked?   

What are the purposes of a 'coding standard' ?   The answer is to make the code easier to understand.   LOGIC THAT IS FORCED INTO TERNARY OPERATIONS (and don't even do what the original code did) DO NOT MAKE FOR 'BETTER CODE'.

**Comment by 040medien** [comment] 2017-08-08 05:31
Thanks. The probe points were directly on the outside perimeters of the mesh (in areas I can probe). It might make sense to document that it needs to go have an additional inset from the mesh borders.

**Comment by oysteinkrog** [comment] 2017-08-08 12:17
@Roxy-3D: I agree with you here, it's obvious that you are frustrated and I think you have a right to be.
In this case I think @thinkyhead went too far, there is no good reason to prefer ternary operators for this code.

**Comment by fiveangle** [comment] 2017-08-08 17:54
While the point can be easily made in this example that ternary operators should be used where they improve code readibility but not used where they reduce it, there are surely more constructive ways to convey this than a passive-agressive sarcastic post to a 3rd party who has no power to directly effect change (imho).

I know that when I'm working in "cleanup mode" as fast as possible on other's code, it is often easy to be temporarily blinded by the mechanics of it all.  In this case, the ternary did reduce readability below the threshold of acceptable.

If you're frustrated by the time required for Scott to respond to comments — or that he misses some, when you submit the PR to fix the regression from Scott's mistake, just change the format back (while still adhearing to the expected formatting standards) and include a line item in the PR "- returned to discrete format due to complexity of the code, for readability".  It will obviously be seen and responded to since it won't then be burried in the comments of a merged PR.  That the change to ternary reduced readibility to the point where even he made a logical mistake on it is probably evidence enough for him to surely agree :)

[insert silly Rodney King quip 😉]

**Comment by 040medien** [comment] 2017-08-21 06:04
Just wanted to bring this up again. This issue persists, rendering G29 J useless.

**Comment by Roxy-3D** [comment] 2017-08-21 14:37
Can you post your Configuration.h and Configuration_adv.h ?   (add a .txt suffix to the name)

It looks like you have stuff set up such that the nozzle is going off the mesh.

**Comment by 040medien** [comment] 2017-08-21 14:53
Sure thing:

[Configuration.h.txt](https://github.com/MarlinFirmware/Marlin/files/1239163/Configuration.h.txt)
[Configuration_adv.h.txt](https://github.com/MarlinFirmware/Marlin/files/1239162/Configuration_adv.h.txt)

**Comment by Roxy-3D** [comment] 2017-08-21 15:11
In Configuration.h you have:
```cpp
// The size of the print bed
#define X_BED_SIZE 207
#define Y_BED_SIZE 312

#define UBL_MESH_INSET 10          // Mesh inset margin on print area
```

In Configuration_adv.h you have:
```cpp
  #define UBL_MESH_MIN_X UBL_MESH_INSET
  #define UBL_MESH_MAX_X (X_BED_SIZE - (UBL_MESH_INSET))
  #define UBL_MESH_MIN_Y UBL_MESH_INSET
  #define UBL_MESH_MAX_Y (Y_BED_SIZE - (UBL_MESH_INSET))
```

  #define UBL_MESH_MIN_X 10            = 10
  #define UBL_MESH_MAX_X (207 - 10)    = 197
  #define UBL_MESH_MIN_Y UBL_MESH_INSET= 10
  #define UBL_MESH_MAX_Y (312 - 10)    = 302

Recv: ? in get_z_correction(lx0=10.00, ly0=302.00)
Recv: ? in get_z_correction(lx0=197.00, ly0=302.00)
Recv: ? in get_z_correction(lx0=197.00, ly0=42.00)

The locations it is complaining about are right on the UBL_MESH_MAX_X  and UBL_MESH_MAX_Y  locations.  If you adjust the inset to be 9 instead of 10, you will be able to go to X=197 or Y=302 

Alternatively...  You could make your X_BEDSIZE and Y_BEDSIZE slightly bigger.

> Afterwards when I run G29 T1:
> Send: G29 T1
> Recv: Invalid Y location specified.

If you load the latest bugfix-1.1.x this issue should be repaired now.   And when you do a G29 T it should tell you the MAX location of the mesh points (which will be (X,Y) = (197,302) ).

**Comment by 040medien** [comment] 2017-08-22 04:32
I'm not following

G29 J should use the three points specified here, which are all well within the mesh dimensions:

```
#define UBL_PROBE_PT_1_X 20
#define UBL_PROBE_PT_1_Y 292
#define UBL_PROBE_PT_2_X 187
#define UBL_PROBE_PT_2_Y 292
#define UBL_PROBE_PT_3_X 187
#define UBL_PROBE_PT_3_Y 52
```

**Closed as completed** 2017-11-14 07:33 UTC
Labels: F: U.B.L.
