### ISSUE TITLE
[BUG] BABYSTEP ZPROBE OFFSET not working while printing from COREXZ

### ISSUE THREAD

**Issue by trunglp** [MarlinFirmware/Marlin#22910] opened 2021-10-08 11:09 UTC
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

Today i setup voron SwitchWire CoreXZ and build Firmware Marlin 2.0.9.2

I printed and i don't control  BABYSTEP ZPROBE OFFSET, Please fix it

Thank you,

### Version of Marlin Firmware

2.0.9.2

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Prusa Slicer

### Host Software

OctoPrint

**Comment by thisiskeithb** [comment] 2021-10-11 18:47
Duplicate of #19988

**Closed as completed by thisiskeithb** 2021-10-11 18:47 UTC
Labels: F: Calibration, K: Core / H-Bot
