### ISSUE TITLE
[FR] Auto Bed Levelling for Print Area Only Just Before Print

### ISSUE THREAD

**Issue by KodeMunkie** [MarlinFirmware/Marlin#22489] opened 2021-08-02 11:49 UTC
### Is your feature request related to a problem? Please describe.

My bed tends to go out of level on a semi regular basis owing to vibration, weak springs, different bed temperatures etc etc. It is a pain to have to do a full ABL with a 81 point bed (my default Creality bed is really that bad).

### Describe the feature you want

Prior to running a print I'd like to be able to run a mini bed level probe of just the bounding box area of the print (i.e within a skirt or a skirt's bounding box area).

The smaller probing area request is due to the time required to do the BLTouch probing being excessive (at least for me with 9x9 grid). The majority of prints I assume most people do is centre of the bed, about 25% of the total bed area which would be a lot quicker and potentially more accurate due to being Just Before Print ("JBP" as acronym perhaps too? ;) )

This might be achieved by doing a partial update of the bed levelling table for the affected centre points. This is not ideal from a consistency point of view (since all the other points used by regular ABL are not normalised) so I would also suggest disabling the regular "Bed Levelling" option if JBP bed levelling is enabled.

**Comment by thisiskeithb** [comment] 2021-08-02 12:05
Duplicate of https://github.com/MarlinFirmware/Marlin/issues/10547

**Closed as completed by thisiskeithb** 2021-08-02 12:05 UTC
Labels: T: Feature Request
