### ISSUE TITLE
Can't compile Bugfix 2.0.x with MKS Robin Nano v3.0 

### ISSUE THREAD

**Issue by easotokr** [MarlinFirmware/Marlin#23222] opened 2021-11-28 22:48 UTC
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

I can't compile the latest bugfix with my MKS Robin Nano v3.0 

the error message:
Marlin\src\HAL\STM32\fast_pwm.cpp: In function 'void set_pwm_frequency(pin_t, int)':
Marlin\src\HAL\STM32\fast_pwm.cpp:74:36: error: 'Instance' was not declared in this scope
   74 |   uint32_t index = get_timer_index(Instance);
      |                                    ^~~~~~~~
Marlin\src\HAL\STM32\fast_pwm.cpp:77:16: error: 'TEMP_TIMER_NUM' was not declared in this scope; did you mean 'TIMER_NUM'?
   77 |   if (index == TEMP_TIMER_NUM || index == STEP_TIMER_NUM
      |                ^~~~~~~~~~~~~~
      |                TIMER_NUM
Marlin\src\HAL\STM32\fast_pwm.cpp:77:43: error: 'STEP_TIMER_NUM' was not declared in this scope; did you mean 'STEP_TIMER'?
   77 |   if (index == TEMP_TIMER_NUM || index == STEP_TIMER_NUM
      |                                           ^~~~~~~~~~~~~~
      |                                           STEP_TIMER
*** [.pio\build\mks_robin_nano_v3_usb_flash_drive\src\src\HAL\STM32\fast_pwm.cpp.o] Error 1

### Version of Marlin Firmware

bugfix 2.0.x

### Printer model

Creality Ender 3

### Bed Leveling

ABL Linear grid

### Your Slicer

Cura

### Host Software

OctoPrint

**Comment by thisiskeithb** [comment] 2021-11-28 22:56
Duplicate of #23213

**Closed as completed by thisiskeithb** 2021-11-28 22:56 UTC
