### ISSUE TITLE
Z_MIN_PROBE confusion

### ISSUE THREAD

**Issue by ruggb** [MarlinFirmware/Marlin#6983] opened 2017-06-08 01:48 UTC
The rhetoric for the Z_PROBE has me confused.
I configured it like I thought it might work but received this error on compile

```
In file included from sketch\MarlinConfig.h:39:0,

                 from D:\Users\Bill\Documents\#Arduino\libraries\Marlin-1.1.3-b2c20a8\Marlin\Marlin.ino:31:

SanityCheck.h:555: error: #error "Z_MIN_PROBE_ENDSTOP requires the Z_MIN_PROBE_PIN to be defined."

       #error "Z_MIN_PROBE_ENDSTOP requires the Z_MIN_PROBE_PIN to be defined."

        ^

exit status 1
#error "Z_MIN_PROBE_ENDSTOP requires the Z_MIN_PROBE_PIN to be defined."
```

This is what I changed in configuration.h
```cpp
//#define Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN //**
and
#define Z_MIN_PROBE_ENDSTOP //**
#define Z_MIN_PROBE_PIN Z_MAX_PIN //**
```
This is what is in Ramps.h
```cpp
#define Z_MAX_PIN          19
```
It would seem to me that it is defined.
So why do I get this error?????

**Comment by Bob-the-Kuhn** [comment] 2017-06-08 02:21
Because Marlin assumes Z_MIN_PIN is always going to be used.

If you're going with the probe only then it wants the probe tied to the Z_MIN_PIN via Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN

If you want to use  Z_MIN_PIN for homing  and a probe in addition then Z_MIN_PROBE_ENDSTOP is the correct option.

I thought I had a decent user oriented explanation in the Config file but it got butchered when some of the probe info went to the wiki.

**Comment by ruggb** [comment] 2017-06-08 02:42
@Bob-the-Kuhn thanks - yes, it is very confusing.
First, I need to know how the leveling works. My logic says that if I perform a leveling with a nozzle based switch, it uses that switch to record the "0" positions. Then it uses that data going forward, so the physical endstop is not used unless the system is reset. Then I must perform another level or use the physical endstop. Based on that logic, I was going to connect the probe to the Z_MAX pin so that if I didn't level it, I would still have the physical endstop to prevent a crash. Actually, I guess I need the physical endstop to do an initial home, or nothing will work. Right?
So I commented out `Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN` and uncommented 
```cpp
#define Z_MIN_PROBE_ENDSTOP
#define Z_MIN_PROBE_PIN Z_MAX_PIN
```
Does that not do what I thought it would do?

Your response seems to indicate my logic is correct, the `Z_MIN_PROBE_PIN` is defined, but I get the error. So what is the problem?

**Comment by Bob-the-Kuhn** [comment] 2017-06-08 03:57
I'm not sure how to answer your questions.  I'll try to address the areas I think you're concerned with.

----

I have not figured out how to setup a backup Z sensor to guard against the Z probe failing & causing a head crash.

Electrically you can hook them up so that the endstop is triggered if either sensor is triggered.

Mechanically I don't know how to get the two sensors aligned.

The closest I've seen to a failsafe Z sensor system is when the nozzle is the sensor.  Most of those use a mechanical switch so there's still a reasonable probability of crashes in the future.

There's been some discussion about using the smart (I2C) motor drivers to act as the endstop sensor.  In Configuration_adv.h there is a SENSORLESS_HOMING section.  Looks like only the X & Y can be setup this way.  Maybe Z isn't there because they're afraid that it'll apply enough pressure to the bed to crack the glass or bend the head.

----

A Z_MIN endstop is never used for leveling.  Creating the leveling grid/mesh/equations is always done with a probe or done manually.

With the advent of UBL, the tendency is to NOT re-do the leveling grid before each print.  So far that seems to be working.  The same reasoning would apply to all forms of leveling.

It's still a requirement to home the machine before trying to do any printing.

----

Have you played with UBL?  I was really surprised at how well it works.  The editing tools and the G26 verification system allow you to dial in the mesh.  Very nice but can be time consuming.

There's a lot of work going into creating a simplified set of instructions and a semi-automated LCD system.

The wiki contains an [UBL getting started guide](http://marlinfw.org/docs/features/unified_bed_leveling.html).  It's a good source for general info on UBL leveling.  It's not been updated in the last 2-3 weeks so some of the info is out of date.  It doesn't include the LCD only method and it doesn't include the no LCD method.  Personally I prefer the original hybrid system.

**Comment by ruggb** [comment] 2017-06-08 19:12
@Bob-the-Kuhn OMG! Now I have totally confused you!
Can you supply a flow chart of how this bed leveling works using a nozzle probe, Now I may not understand what you are referring to by "nozzle probe", but this is what I have - one that I place one the nozzle to create the map then remove to print.

So, I start the system and home all using the physical endstops.
I place the probe over the nozzle -- since I haven't gotten here yet, I am not sure what to do now.

If this "A Z_MIN endstop is never used for leveling." is true, then what is this "Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN"? OH, maybe what you are saying is the ENDSTOP is not used but the pin may be.
I think part of the problem is the definitions -- it would be less confusing if Z_MIN_PROBE was Z_PROBE period. There is no MAX to the probe, it is always detecting the MIN and it may be connected to Z_MAX_ENDSTOP.

Either my brain or these instructions need a serious adjustment.

**Comment by Bob-the-Kuhn** [comment] 2017-06-08 23:34
Serious adjustment?  I could go for that.  I think I'll grab a beer.  Thanks for the idea.

On the Z_MIN_PIN - it's always used.  If you're doing probe only (Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN) then the probe is attached to that pin.  If you're doing probe  with an endstop for homing then the endstop is attached to Z_MIN_PIN.

If you're using  Z_MIN_PROBE_ENDSTOP then the probe can be attached to any pin **except** Z_MIN_PIN.  Using Z_MAX+PIN is just usually the most convenient one to use.

You have a probe that snaps over the nozzle?  Never heard of that.  I hope the Z dimension of the combo is very repeatable.

What I mean by a nozzle probe is one where the X & Y offsets are zero.  

----

The concept of non-planar bed leveling (assumes a bed that has dips & peaks) is pretty simple.  Build a grid/mesh/array of compensation values and then apply that grid when doing moves.

When building the grid the difference between Z=0 (from homing) and the probe trigger point plus the probe Z offset is saved.  The location saved for this point is the location of the **probe**.  When applying the compensation to moves, the **nozzle** location is used.  

Example: One of the probed points was done with the **probe** at location (10, 23) and has a Z compensation value of -2.7.  When applying the compensation the **nozzle's** destination location is used.  If a G0 X10 Y-23 Z5 command is sent to the controller then the planner looks up the Z compensation value for (10, -23) and adds it to the destination Z.  The result is that the command that the planner issues to the stepper software is X10, Y-23, **Z2.3**.  In the resulting physical move the nozzle travels in a straight line from the current location to (10, -23, 2.3).

When the destination isn't exactly on one of the grid points then an interpolation is done.  Attached is a detailed explanation of how this is done in bilinear leveling.
[Bilinear Auto Bed Leveling Details 0.4.zip](https://github.com/MarlinFirmware/Marlin/files/1062638/Bilinear.Auto.Bed.Leveling.Details.0.4.zip)

----

If using planar leveling then the compensation values are derived from an equation.  

For 3 point leveling the coefficients of the equation are derived from the 3 sampled points.

For linear leveling a least squares fit is used to determine the coefficients.

**Comment by ruggb** [comment] 2017-06-08 23:51
OK, so that is what I envisioned. I figure, using the MAX pin is better since I can leave the probe connected and the MIN pin can still be used for the initial startup homing. The probe is nothing more than two pieces of foil that get pushed together by the nozzle when it hits the bed, so the offset is small - the thickness of 2 foils. This is what the probe looks like. Showing 1 for each type nozzle.
![probes](https://user-images.githubusercontent.com/12383390/26955117-beb289b6-4c82-11e7-8266-46a2c8d0d714.jpg)

Back to the original question...when I comment out
//#define Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN
that says DO NOT use Z_MIN_ENDSTOP PIN for probe
and I uncomment
#define Z_MIN_PROBE_ENDSTOP
#define Z_MIN_PROBE_PIN Z_MAX_PIN
That says USE Z_MAX_PIN for Z_MIN_PROBE_PIN
are you confused yet?

and this is already defined in Ramps.h
#define Z_MAX_PIN 19

why do I get the error
   #error "Z_MIN_PROBE_ENDSTOP requires the Z_MIN_PROBE_PIN to be defined."
?????
Z_MIN_PROBE_PIN IS defined as Z_MAX_PIN!!!!!!!!!!!

**Comment by Bob-the-Kuhn** [comment] 2017-06-09 01:50
I'm getting the same error.

I've done some work on it & apparently the RAMPS file hasn't been processed before this check is done.  

I'll have to do more work to track down the root cause.

A short term workaround is to use this line:
`#define Z_MIN_PROBE_PIN 19`

**Comment by Bob-the-Kuhn** [comment] 2017-06-09 17:17
This is being fixed on PR #7008.

**Comment by thinkyhead** [comment] 2017-06-10 00:41
My assumption has been that the preprocessor doesn't expand a define until it is used, and at that point it would find that `Z_MIN_PROBE_PIN` => `Z_MAX_PIN` => `19`, but perhaps the first substitution happens earlier, the pre-compiler considers it done, so the second substitution is never invoked. Learning a lot about this mysterious pre-processor!

Anyway, Bob's fix is a good one: use a numeric pin number. The `Z_MAX_PIN` is used by default anyway if you don't define `Z_MIN_PROBE_PIN` yourself.

**Closed as completed by thinkyhead** 2017-06-10 00:41 UTC

**Comment by nkuck** [comment] 2018-05-05 15:57
Do I need to enable this:
//#define Z_MIN_PROBE_ENDSTOP

 along with this:
#define FIX_MOUNTED_PROBE

if using a fixed probe sensor, I.e. inductive probe connected to the Z-endstop pin?

**Comment by thinkyhead** [comment] 2018-05-06 11:23
@nkuck — If the Z probe is connected to `Z_MIN_PIN`, enable `Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN`. This also causes the probe to be used for Z homing. If it's connected to `Z_MAX_PIN` then just enable `Z_MIN_PROBE_ENDSTOP` and the correct pin will be assigned. If you need to use any other pin, add a line like this to your `Configuration.h`:
```cpp
#define Z_MIN_PROBE_PIN 2 // X_MAX_PIN (RAMPS)
```
If using `Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN` then it's also helpful to enable `SAFE_HOMING`, and by default the probe will use the middle of the bed for homing.

**Comment by nkuck** [comment] 2018-05-06 11:24
Thanks.

Noel Kuck

Live simply so others can simply live!

**Comment by wa2mze** [comment] 2019-07-01 18:40
It would seem that the use of the z_max_pin IS NOT used by default if you specify Z_MIN_PROBE_ENDSTOP and DON'T specify a define for Z_MIN_PROBE_PIN since you get the error!
Also the pins.h file is NOT parsed when configuration.h is.  SO yeah, I just added  "#define Z_MIN_PROBE_PIN 19" so I can hook my inductive probe to the z_max_endstop pin and leave my z endstop connected to the Z_min_endstop pin.
BTW since I'm using a PNP type probe which sources 12v on the output wire when triggered, I use that to drive an LM78L05 to get the 5v needed on the input to the ramps, and configure that endstop to NOT have a pullup, and also configure the endstop to be NON-INVERTING.   
I'm amazed that this problem with the parsing of pins.h file is STILL outstanding as of 1.1.19!!!!

**Comment by thinkyhead** [comment] 2019-07-03 06:32
We are not patching 1.1.x any more. To get the latest updates, migrate to `bugfix-2.0.x`.

**Comment by wa2mze** [comment] 2019-07-03 13:47
>>
>> We are not patching 1.1.x any more. To get the latest updates, migrate 
>> to |bugfix-2.0.x|.

But the 1.1.x line is the STABLE release, the 2.0.x line isn't marked as 
STABLE-CURRENT yet, or is it?

**Comment by thinkyhead** [comment] 2019-07-11 15:25
There are tagged releases from the 1.1.x tree, but no tagged releases yet from the 2.0.x tree. With our limited resources we're focusing all attention on producing the first tagged 2.0.x (candidate) release, around the end of this month.
