### ISSUE TITLE
[BUG] POWER_LOSS_RECOVERY in Delta Printers - resume makes a home to bed

### ISSUE THREAD

**Issue by sergiofagundes** [MarlinFirmware/Marlin#23175] opened 2021-11-23 12:40 UTC
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

I'm using a Delta/Kossel Printer using a hardware (MKS UPS 12V) to recover from power loss during the print.

When resuming the print, the firmware makes a home to zmax (top of printer) this is good because I'm using the orbiter extruder 1.5 in the effector and when power failures occur the effector doesn't maintain it's position.

The problem is after the home to zmax, the printing goes to a fixed XY position and tries a home to zmin like a cartesian printer, then goes up and continue printing.

This home to zmin will crash to the printed object most of times. Z Safe Homing  On or Off makes no effect.

### Bug Timeline

Old

### Expected behavior

In a Delta printer resume printing with a home to zmax and continue printing.

### Actual behavior

In a Delta printer resume printing with a home to zmax, move to a fixed XY position and goes to the bed Z=0 and continue printing.

### Version of Marlin Firmware

2.0.9.2

### Printer model

Kossel Delta XL

### Electronics

Mks Robin E3D

### Add-ons

MKS UPS 12v

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Prusa Slicer

### Host Software

SD Card (headless)

### Additional information & file uploads

[Marlin_Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/7587997/Marlin_Configuration.zip)

**Comment by thisiskeithb** [comment] 2022-01-14 17:34
Duplicate of https://github.com/MarlinFirmware/Marlin/issues/19166

**Closed as completed by thisiskeithb** 2022-01-14 17:34 UTC
Labels: K: Deltabot, F: Print Recovery
