### ISSUE TITLE
bed maxtemp triggered, but hardware ok.

### ISSUE THREAD

**Issue by mamama1** [MarlinFirmware/Marlin#9730] opened 2018-02-20 00:12 UTC
Marlin 1.1.8

AM8, standard A8 hotbed, MKS gen 1.4 board (atmega2560).

many features and buffers enabled, 85% RAM used, arduino warning about high memory usage and possible instabilities triggered.

can the bed maxtemp error be triggered by an error due to high mem usage of 85%?

the hardware is ok, bed temp was at 75 degrees, maxtemp is at 85 degrees.

also: maxtemp is set to 85 degrees but i cant set more than 65 through the display. through gcode and octoprint i can set higher temps. this issue persisted already when various features weren't enabled and therefore low memory condition didn't exist.

**Comment by thinkyhead** [comment] 2018-02-20 11:46
Please test with the latest `bugfix-1.1.x` (and/or `bugfix-2.0.x`) branch to see where it stands. If the problem has been resolved then we can close this issue. If you still see the bad behavior we should investigate further.

**Comment by mamama1** [comment] 2018-02-20 12:00
thanks but if the current release is not going to be supported any further, an announcement of the next stable release would be really great. it feels like every issue gets the same answer, "use the bugfix release".

**Comment by AnHardt** [comment] 2018-02-20 12:18
@mamama1 
`bugfix-1.1.x` **is** the branch we support (fix bugs) the current release in (, plus doing some innovations).

**Comment by mamama1** [comment] 2018-02-20 12:33
so bugfix-1.1.x is considered stable/more stable than the latest release? always?

**Comment by GMagician** [comment] 2018-02-20 14:35
> so bugfix-1.1.x is considered stable/more stable than the latest release? always?

as stated by @AnHardt  this is bugfix and innovation. From bugfix side, yes it stabilizes bugs, from innovation side it may add some new bugs

**Comment by AnHardt** [comment] 2018-02-20 16:39
Ouer 'releases' are stable in the sense of 'they will not be changed'. That does not say anything about having more or less errors. Usually bugfix is the preferable branch 3-4 days after a release. Usually the release gets a bit more attention/downloads when they are fresh. Then lots of issues come in. For some fixing is simple and it's done quite fast. This could be the ideal time to download a 'bugfix' branch to get a firmware with relative few bugs. After that most of the developers return to the funny side of programming - developing and improving features.

**Comment by mamama1** [comment] 2018-02-20 17:11
i'd like to contribute before criticisibg but unfortunately my c coding skills are not good enough for this. but maybe this can be taken as constructive criticism anyway: why not concentrate solely on bugfixing in the bugfix branch and only introduce new features in some development or nightly build branch? new features often bring new bugs (also outside of the new features) and so the "user" can potentially be left with the choice between two buggy versions. either the old final release with a known fixed bug in the bugfix branch or the bugfix branch with a newly introduced, showstopping bug...

**Comment by thinkyhead** [comment] 2018-02-25 12:38
Thanks. We are on the same page.

**Comment by batata004** [comment] 2018-02-26 13:23
Guys I dont know why are you arguing about the bufix and such. To me it's clear: there is a bug. And the bug surelly is related to something very wrong.

I watched today the hotend temperature and it is very strange, it updates every 1s and sometimes (randomly) it goes from 190 to 215, then 230 to 210... all in 1 sec. Also I already opened another thread reporting this same error the OP reported here, errors like MAX TEMP and such - that thread got closed but I didnt know of this thread here, if I knew I wouldnt open it.

Finally I AM PRETTTY SURE there is something overloading arduino cause sometimes when I turn the knob it freezes for like 1 or 2 seconds and then the menu scrolls very fast to a random option. Maybe the  RAM is being used too much (I already saw other threads of people reporting too much RAM and some "smart" people said it's not a big probem having too much ram being used except if it's close to 100%).

Anyway, now with this thread opened by @mamama1 it's clear to me that something is wrong with this version. I was working fine with last version and had nos issues like this!

**Comment by mamama1** [comment] 2018-02-26 13:40
the arguing was because many issues were commented with „please try latest bugfix version“, which basically leaves the current version of the stable branch kind of unsupported...

anyways, regarding to ram usage, i too observed weird behaviour when hitting about 80% of ram usage. according to my knowledge you can use up almost any ram if you are not doing things like malloc without checking free ram first. also ram will get fragmented when using malloc which will lead to more issues because it may happen that at one point in time malloc wont find a free block in the memory which is large enough and unfragmented to accomodate the needs of the malloc call and then everythig may go boom...

**Comment by batata004** [comment] 2018-02-26 14:28
@mamama1 when I said what I said I was totally agreeing with you! 

> I dont know why are you arguing about the bufix and such

Exactly that. The bug happens with the latest stable version, so it should be fixed in that version, not in the bugfix or any other version. Makes no sense asking people to test the bug with the bugfix branch or the 2015 branch.

I am not a C programmer and I cant help with that, but what I am experience is random issues which I never had before so many times.

**Comment by thinkyhead** [comment] 2018-02-27 06:23
@batata004 You are only adding noise. Please step away.

![image](https://user-images.githubusercontent.com/698003/36713699-7fad540c-1b54-11e8-947b-839f5afa02cc.png)

**Comment by AnHardt** [comment] 2018-02-27 08:51
@mamama1 
> also: maxtemp is set to 85 degrees but i cant set more than 65 through the display. through gcode and octoprint i can set higher temps.

The limit is 15°C not 20.
https://github.com/MarlinFirmware/Marlin/blob/1.1.x/Marlin/ultralcd.cpp#L1303

This is to avoid maxtemp errors caused by overshot and not (yet) implemented for other ways to set the temperature.
Maxtemp should be set at least 15°C above the temperature you want to print with. It's mainly thought as a protection against shorted thermistor wires. Protection of the nozzle is a side effect.

**Comment by mamama1** [comment] 2018-02-27 08:53
that makes sense, thanks!

**Comment by mylife4aiurr** [comment] 2018-06-19 08:03
bugfix 1.1.x 78410b2
Reporting same strange behavior. Thermal run away reported, printer halted. 
but seems as though reporting the temp is being delayed but to cpu overload??? idk. 

Gonna try latest build and also double check wiring, if problems I'll report back.

**Comment by boelle** [comment] 2019-02-20 09:11
@mamama1 still having issues with latest bugfix 2.0?

**Closed as completed** 2019-05-16 00:12 UTC
