### ISSUE TITLE
PROBING_HEATERS_OFF conflict with PROBE_DOUBLE_TOUCH 

### ISSUE THREAD

**Issue by SphaeroX** [MarlinFirmware/Marlin#8597] opened 2017-11-29 09:29 UTC
If I let the bed level with these two settings, then it switches off the printing bed only with the first probe and with the second slow one the printing bed is on again. With the pressure nozzle everything folds out perfectly and remains so until the second measuring point.

**Comment by thinkyhead** [comment] 2018-02-09 12:44
Please test with the `bugfix-1.1.x` branch and see if the problem is fixed. In your followup reply please specify which form of bed leveling you're using.

**Comment by boelle** [comment] 2019-02-19 22:57
@SphaeroX Please test with the `bugfix-2.0`

**Comment by boelle** [comment] 2019-03-06 10:58
@thinkyhead i think we can close this one

**Closed as completed** 2019-05-16 02:19 UTC
Labels: Bug: Potential ?, Needs: More Data
