### ISSUE TITLE
Tmc2130 not working 

### ISSUE THREAD

**Issue by ISAndreiva** [MarlinFirmware/Marlin#13142] opened 2019-02-12 18:23 UTC
Description
So I changed the board of my cr-10 with a mks gen l , changed firmware to marlin 1.1.9 , everything worked good on my bench so i got an old sever case which i modified to put the components in because i did not like the original case of the cr-10 after i did all the connections everything worked good until i realized i messed up the connection of the mosfet and the thermistor ( no damage there) so i switched them how they should have been and then the TMCs from x,y, and z stopped working , the extruder one still worked  
PS: I have redone the wireing , the firmaware worked , and they are powerd by a psu 
### Steps to Reproduce

**Expected behavior:** [What you expect to happen]
Everything to work as intented
**Actual behavior:** [What actually happens]
The tmcs don't work
[configuration .zip](https://github.com/MarlinFirmware/Marlin/files/2857127/configuration.zip)

**Comment by boelle** [comment] 2019-03-06 14:45
@Andreiva13 so you have not tried bugfix 2.0?

**Comment by ISAndreiva** [comment] 2019-03-06 18:29
@boelle I checked that after I made the post

**Comment by boelle** [comment] 2019-03-13 14:56
did you try with bugfix 2.0?

**Comment by ISAndreiva** [comment] 2019-03-13 17:49
Yes I did, I think I blown the drivers.

**Comment by boelle** [comment] 2019-03-13 18:35
yep, the are easy to blow

dont connect steppers or remove steppers with power on
or move steppers fast with the hand
or put them in the wrong way

maybe close this one and open new issue if the problem is still there when you get new drivers

**Closed as completed** 2019-03-13 18:46 UTC
