### ISSUE TITLE
Robin Nano 1.2 with UART and Neopixel not working - UART is supported! - Please don't close again saying its not.

### ISSUE THREAD

**Issue by galluccib** [MarlinFirmware/Marlin#21467] opened 2021-03-28 06:04 UTC
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

Have MKS Robin Nano 1.2 with MKS 2209 V2 running Marlin current bugfix and when in standalone NeoPixels are working fine on pin PB2

### Bug Timeline

New

### Expected behavior

NeoPixel lights to work

### Actual behavior

Not working after configuring UART (Which is working fine!)

### Steps to Reproduce

After switching to UART they no longer work. If I go back to standalone they started working

### Version of Marlin Firmware

FIRMWARE_NAME:Marlin bugfix-2.0.x (Mar 26 2021 23:42:44) SOURCE_CODE_URL

### Printer model

MKS Robin Nano 1.2

### Your Slicer

Prusa Slicer

### Host Software

OctoPrint

Have MKS Robin Nano 1.2 with MKS 2209 V2 running Marlin current bugfix and when in standalone NeoPixels are working fine on pin PB2. After switching to UART they no longer work. If I go back to standalone they started working. Also tried switching to pin PC4 but that didn't work either. Only thing added to the pins file is below and configs are attached. Using five steppers so using PA5 for the fifth one.

#if HAS_TMC_UART

#define X_SERIAL_TX_PIN PA10
#define X_SERIAL_RX_PIN PA10

#define Y_SERIAL_TX_PIN PA9
#define Y_SERIAL_RX_PIN PA9

#define Z_SERIAL_TX_PIN PC7
#define Z_SERIAL_RX_PIN PC7

#define E0_SERIAL_TX_PIN PC13
#define E0_SERIAL_RX_PIN PC13

#define E1_SERIAL_TX_PIN PA5
#define E1_SERIAL_RX_PIN PA5

// Reduce baud rate to improve software serial reliability
#define TMC_BAUD_RATE 19200
#endif // HAS_TMC_UART

MKS video showing it's supported - https://youtu.be/7ShcFKXrVHo

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/6216924/Configuration.zip)

**Comment by ellensp** [comment] 2021-03-28 06:08
duplicate of the reopened https://github.com/MarlinFirmware/Marlin/issues/21466 closing.

**Closed as completed by ellensp** 2021-03-28 06:08 UTC
