### ISSUE TITLE
[bugfix-2.0.x] AXIS_IS_TMC 

### ISSUE THREAD

**Issue by frech-tech** [MarlinFirmware/Marlin#11387] opened 2018-07-27 06:14 UTC
Hey, 
in the newest bugfix the AXIS_IS_TMC function was implemented. Unfortunately the AXIS_IS_TMC doesn't return TRUE for all axis apart from XYZ. In the drivers.h the if conditions doesn't seem to work. E. g. #if ENABLED(Y_DUAL_STEPPER_DRIVERS) doesn't trigger although Y_DUAL_STEPPER_DRIVERS is enabled. 
I'm using TMC2130 on X, Y, Y2, Z, Z2 and E0.

**Comment by teemuatlut** [comment] 2018-07-27 09:29
The issue is because `drivers.h` is included before `Configuration_adv.h` in `MarlinConfigPre.h`.
The order can't be changed as there are certain sections that rely on the new macros.

**Comment by teemuatlut** [comment] 2018-08-03 13:30
https://github.com/teemuatlut/Marlin/tree/bf2_fix_smart_drivers

**Comment by thinkyhead** [comment] 2018-08-04 02:58
I've applied a patch, so please give the latest code a test and see if it's compiling properly.

**Comment by boelle** [comment] 2019-02-20 15:28
@JackDaFlow did you give latest bugfix 2.0 a go?

**Comment by boelle** [comment] 2019-03-06 12:12
@thinkyhead i think we can close this one

**Closed as completed** 2019-05-16 22:09 UTC
