### ISSUE TITLE
[bugfix-2.0.x] - "Long" pause after probing

### ISSUE THREAD

**Issue by robustini** [MarlinFirmware/Marlin#12171] opened 2018-10-21 10:45 UTC
### Description

There's way to decrease the time that elapses since the probe touches the bed and when it rises?
I can't find any parameter about that.
When the probe is activated (led turns blue) and the probe has already been retracted some time passes before the effector gets up, with Repetier there is no such boring pause.
This pause during "multitouch" creates a problem when using shifts reduced to a minimum to speed up the procedure, because the probe will deploy again when the effector is still low, resulting probing failed.
It stands still for almost half a second, and with the BLTouch (clone but also with the original) creates problems, I would like the effector to get up almost immediately.
With cartesian printer this pause is necessary for wait the BLTouch operation, but not with the Delta because the Z is really fast.

Video comparation, "M48" with "Marlin 2.0" (compiled with the latest commit of today) and "MarlinKimbra V4.3.7ß", both 32 bit.

https://youtu.be/rQ9fKRPST7k

https://youtu.be/ogVrrMDoihg

**Comment by ManuelMcLure** [comment] 2018-10-21 17:14
Do you have `PROBING_HEATERS_OFF` and `WAIT_FOR_BED_HEATER` turned on by any chance? If so, it may be waiting for the bed temperature to stabilize.

**Comment by robustini** [comment] 2018-10-22 12:57
No, i never use this options.
This issue is inside the Marlin code, in MarlinKimbra firmware this "pause" has been rightly removed by @MagoKimbra (the lead developer) only for the delta printer, where it is rightly not necessary.

**Comment by MagoKimbra** [comment] 2018-10-22 13:14
The problem is into void do_probe_move
Each time it activates and deactivates the bltouch.
```
// Deploy BLTouch at the start of any probe
#if ENABLED(BLTOUCH)
  if (set_bltouch_deployed(true)) return true;
#endif

// Retract BLTouch immediately after a probe if it was triggered
#if ENABLED(BLTOUCH)
  if (probe_triggered && set_bltouch_deployed(false)) return true;
#endif
```

And into void bltouch_command there is a delay safe_delay(BLTOUCH_DELAY);

This is useful to prevent the bltouch from being extracted before the printer can get back up, it's fine for printers with Z slow, but in the delta it's not needed.

@robustini you can try to put 0 BLTOUCH_DELAY.

**Comment by MikeLud** [comment] 2018-10-22 13:50
@robustini 

I might be how the HOMING_FEEDRATE_Z is set in the Configuration.h file

```
// Homing speeds (mm/m)
#define HOMING_FEEDRATE_XY (50*60)
#define HOMING_FEEDRATE_Z  (4*60)

```

**Comment by boelle** [comment] 2019-02-21 19:29
@robustini problem solved?

**Comment by boelle** [comment] 2019-03-06 13:36
@thinkyhead i think we can close this one

**Closed as completed** 2019-05-16 23:15 UTC
