### ISSUE TITLE
[BUG] FAN not work on MKS ROBIN E3

### ISSUE THREAD

**Issue by GoPrintTech** [MarlinFirmware/Marlin#23141] opened 2021-11-16 13:20 UTC
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

My motherboard is MKS Robin E3 ,  in configurations  i use  ZMAX_ Plug and Z_ HOME_ DIR 1

When I used Marlin 2.0. X, I found that the Z endstop not work, but the cooling fan worked fine.
When switching to bugfix-2.0. X, the Z endstop work fine, but the cooling fan cannot run,  i can't control cooling fan on  LCD12864 screen.
Therefore, the current situation is that no version of Z endstop and cooling fan can be used at the same time. I hope someone can help me
[Configuration.h.zip](https://github.com/MarlinFirmware/Marlin/files/7546500/Configuration.h.zip)
.

### Bug Timeline

first start

### Expected behavior

Z endstop work fine and cooling fan work fine.

### Actual behavior

Z endstop work fine  but  cooling fan not work

### Steps to Reproduce

1. use mks robin e3 
2. Overwrite with my uploaded config file
3. on screen start the fan but not work

### Version of Marlin Firmware

bugfix-2.0.x

### Printer model

diy i3

### Electronics

mks robin e3

### Additional information & file uploads

[Configuration.h.zip](https://github.com/MarlinFirmware/Marlin/files/7546571/Configuration.h.zip)

**Comment by ellensp** [comment] 2021-11-18 08:41
Duplicate of https://github.com/MarlinFirmware/Marlin/issues/23094
It is known and being worked on

**Closed as completed by ellensp** 2021-11-18 08:41 UTC
