### ISSUE TITLE
[BUG] UBL with PROBE_MANUALLY can crash into the bed when "Mesh Edit" or "Fine Tune All" or "Fine Tune Closest" from LCD

### ISSUE THREAD

**Issue by qurvento** [MarlinFirmware/Marlin#19804] opened 2020-10-18 21:34 UTC
### Bug Description

UBL with PROBE_MANUALLY crashes into the bed when running "Mesh Edit" or "Fine Tune All" or "Fine Tune Closest" from LCD. The printer tries twice to set Z=0 and crashes into the bed if current point's Z>0.

### My Configurations

Creality Ender-3 v4.2.2
Marlin 2.0.7.1
AUTO_BED_LEVELING_UBL, PROBE_MANUALLY, LCD_BED_LEVELING, MESH_EDIT_MENU, UBL_MESH_EDIT_MOVES_Z
[cfg.zip](https://github.com/MarlinFirmware/Marlin/files/5398203/cfg.zip)

### Steps to Reproduce

1. Select "Motion/Unified Bed Leveling/Mesh Edit" or "Motion/Unified Bed Leveling/UBL Tools/Edit Mesh/Fine Tune All" or "Motion/Unified Bed Leveling/UBL Tools/Edit Mesh/Fine Tune Closest".

**Expected behavior:** moves to mesh point's Z plus paper width

**Actual behavior:** moves Z=0, back to Z_CLEARANCE_BETWEEN_PROBES and again to Z=0.

In `unified_bed_leveling::fine_tune_mesh()`:
   0 if 'H' option is missing. Could be set to MANUAL_PROBE_START_Z instead:
```
    #if ENABLED(UBL_MESH_EDIT_MOVES_Z)
        const float h_offset = parser.seenval('H') ? parser.value_linear_units() : 0;
```
Redundant Z move after moving to start position:
```
      do_blocking_move_to_xy_z(pos, Z_CLEARANCE_BETWEEN_PROBES);  // Move to the given XY with probe clearance
      TERN_(UBL_MESH_EDIT_MOVES_Z, do_blocking_move_to_z(h_offset));  // Move Z to the given 'H' offset
```

**Comment by boelle** [comment] 2020-10-20 21:23
is this related to #19814 ?

**Comment by qurvento** [comment] 2020-10-24 11:28
no

**Comment by sjasonsmith** [comment] 2020-11-21 08:48
Don't be fooled by the "Merged" PR above, that was a similar issue that I thought might have shared a root cause with this. It is very similar, but in different code.

**Comment by sjasonsmith** [comment] 2020-11-22 10:00
@qurvento I've posted a PR with your recommended changes. Can you look at it and verify that it works how you would expect?

**Comment by Foxies-CSTL** [comment] 2020-11-22 11:23
@sjasonsmith
Hi,
I noticed the same behavior on a Delta when I edit a mesh using the menu.
    "Select "Motion/Unified Bed Leveling/Mesh Edit"

Steps to Reproduce:

After the flash with PR #20248 and #19804, I perform the following operations:
  - reset the eeprom = ok
  - launch of an auto-calibration (G33) = ok
  - Launch of a cold mesh by UBL Tools = ok
- Editing of the mesh via the menu and the two XY axes are positioned towards H - 50mm but the Z axis is positioned towards 0. I stop it before the axis motor locks at the bottom (I have no endstop mini).

Before the cut, I see a mesh screen which represents a 7x7 square.
![IMG_2060](https://user-images.githubusercontent.com/24864147/99902300-148a9680-2cbd-11eb-848c-0e922ac29219.JPG)

**Comment by sjasonsmith** [comment] 2020-11-23 09:17
@Foxies-CSTL I don't quite understand what you are desribing. Is it directly related to this issue or the PR that was just merged? This issue involves the nozzle pressing into the bed. It sounds like your issue is your carriage moving to the side? I don't think my recent change could have caused this.

**Comment by Foxies-CSTL** [comment] 2020-11-23 18:21
>  I don't quite understand what you are desribing

Okay I thought the problem is pretty well described so I'm going to do a PR to fix the bad behavior of the Z axis stepper motor when I want to edit a mesh through the menu in UBL Tools.

> I don't think my recent change could have caused this.

I thought your PR would solve my problem but it's still there.

**Comment by sjasonsmith** [comment] 2020-11-23 18:51
@Foxies-CSTL wow, I just noticed that one carriage at the bottom. I missed that in the original picture. That is definitely not related to this issue.

**Comment by Foxies-CSTL** [comment] 2020-11-23 19:25
> That is definitely not related to this issue.

No problemo ;-) I write a PR for that =>#20257

**Comment by sjasonsmith** [comment] 2020-11-28 06:37
Closing this as resolved, since we haven't heard back from @qurvento after the merged PR.

**Closed as completed by sjasonsmith** 2020-11-28 06:37 UTC
Labels: Bug: Potential ?, F: Calibration, F: U.B.L.
