### ISSUE TITLE
License violations

### ISSUE THREAD

**Issue by tonnico** [MarlinFirmware/Marlin#2613] opened 2015-09-01 07:31 UTC
Hi everyone,

do we need a single place for all violations against the license?

Just got an email from someone who told me that Mankati does not send the source code. Only a precompiled hex-file.

**Comment by Roxy-3D** [comment] 2015-09-02 04:47
My thoughts are we do need to maintain a list and keep tract of dates.   I'm thinking we send out maintenance fees and invoices given they aren't living up to their end of the contract.

**Comment by thinkyhead** [comment] 2015-09-02 04:55
We should definitely verify that Mankati is failing to comply with GPL before bothering them. I had a tense exchange with another vendor who it turned out simply wasn't understanding a user request, and I'd hate to repeat that.

**Comment by thinkyhead** [comment] 2015-09-02 06:01
Mankati does looks a little strange! Creatbot is the same company.
- Their software is simply a customized Cura with their own branding added.
- No Cura source code is supplied — [unless this is it?](https://github.com/zifengtayu/Cura)
- Their website is exceptionally slow. 45MB download will take >2 hours.
- Comments on YouTube and [reviews in forums](http://www.soliforum.com/post/59481/#p59481) are [mostly negative](http://3dprintboard.com/showthread.php?2983-Mankati-3D-printer&p=47071&viewfull=1#post47071), but some are [having fun with it](https://www.youtube.com/watch?v=1aHPHYl3bYE).
- It appears that they don't provide source for their modified Marlin (not yet confirmed that it _is_ Marlin, but is it obvious from the .hex file or startup output?), but according to GPL (as I understand it) they only have to supply it upon request and only to their customers, not necessarily to everyone on their website.

Apparently you can use vanilla Marlin since the Mankati FullScale XT has standard electronics, possibly the same as UM2.

I have written to Mankati's user account on Thingiverse, simply to inquire about the firmware and where we can get the source code. Hopefully I will have an answer soon. They seem to have been very quiet in most places since 2014.

**Comment by Roxy-3D** [comment] 2015-09-02 12:48
> (not yet confirmed that it is Marlin, but is it obvious from the .hex file or startup output?)

I would think the text from Language.h would be very easy to find in the .hex file.   I looked around and  http://forum.mankati.com/files/ was the closest thing I found to them providing firmware.   If there is a .hex file there, I didn't find it with 10 minutes of looking around.

If somebody can provide a link to a .hex file they are offering, I'll check to see if it is generated from a Marlin code base.

**Comment by tonnico** [comment] 2015-09-02 13:03
Here is the hex-file, but I will delete this file tomorrow on my drive.
~~file deleted~~

**Comment by Roxy-3D** [comment] 2015-09-02 13:25
Thank You!   I have to run to the dentist.   But in a few hours, I'll post the analysis.

**Comment by epatel99** [comment] 2015-09-02 15:01
I was curious so I did a quick check. Here is a part from running strings on the binary...

<code>
FIRMWARE_NA
E:Marlin V1; Sp
inter/grbl mash
p for gen6 FIRM
ARE_URL:http://
ww.mankati.com/
PROTOCOL_VERSIO
:1.0 MACHINE_TY
E:Mankati EXTRU
ER_COUNT:2 UUID
00000000-0000-0
00-0000-0000000
0000
Mankati O
Mankati read
Bed done.
Bed Heat
Heating don
</code>

**Comment by Roxy-3D** [comment] 2015-09-02 16:14
Thanks epatel99!   

Here are all the text strings with the associated lines of the .hex file.   It looks like Marlin without any Auto Bed Leveling stuff.   

So how do we proceed?   Should one of us give them a call and tell them they are not living up to their obligations?   ThinkyHead has experience at doing this.  Perhaps it would make sense to have a conference call so we can train more people how to handle this?   

Actually...  I was just poking around on their web site.  There is a 'Contact Us' page.  It is here:  http://www.mankati.com/contact/     Perhaps it makes sense to send them a short note and see what kind of response we get.    Any volunteers ?    Certainly anybody that has contributed code to the code base has 'standing' and should be in a position to insist the contract is honored.

``` hex
:10013000383420582059205A2045006563686F3AAA  84 X Y Z  E.echo:
:100140000043616E6E6F7420656E74657220737506  .Cannot  enter su
:10015000626469723A20004D3234004D32332025FA  bdir: .M 24.M23 %
:1001600073006175746F25692E67004572726F7236  s.auto%i .g.Error
:100170003A006572726F722077726974696E6720D7  :.error  writing 
:10018000746F2066696C65004E6F74205344207054  to file. Not SD p
:1001900072696E74696E67002F0053442070726933  rinting. /.SD pri
:1001A0006E74696E67206279746520002E00446564  nting by te ...De
:1001B0006C6574696F6E206661696C65642C20469D  letion f ailed, F
:1001C000696C653A200046696C652064656C6574ED  ile: .Fi le delet
:1001D00065643A002E006F70656E206661696C651B  ed:...op en faile
```

**Comment by thinkyhead** [comment] 2015-09-04 21:53
At this point I have simply asked the basic support question as to which firmware was used, and where the source code can be obtained, to see what their standard response will be. If it is not positive then I will tread lightly. I prefer to inform gently and help them to come over to our way of thinking rather than employ intimidation. That is of course a last resort. For all I know Creatbot/Mankati may only be a very small family outfit, and with a high margin may only care about selling 20 or 30 units a year. Or, they may be a large warehoused company with millions in sales. Either way they should be excited to support openness.

I understand the potential motivation for using Marlin on the one hand (free as in beer) and concealing your "proprietary" customizations (fearing competition) on the other hand. Their modifications are slight and not highly inventive, so I think they over-worry if that is the case. Diplomacy ahoy...

**Comment by Roxy-3D** [comment] 2015-09-04 21:58
Scott, you are always such a nice guy!

**Comment by leseaw** [comment] 2015-09-25 15:33
I become the firmware now :)
all fine for me, will make an fork here for all mankati user.
and the board is  Rumba.

**Comment by thinkyhead** [comment] 2015-09-28 13:47
Thank you @leseaw!

Here is the Mankati / Creatbot fork: https://github.com/leseaw/MarlinDev-Fullscale-XT-Plus

@leseaw The truly valuable thing will be your `Configuration.h` and `Configuration_adv.h` files configured for those specific machines. Hopefully you can have those posted in your fork soon. Otherwise it will be very hard for users to configure.

**Comment by thinkyhead** [comment] 2015-09-28 13:51
@leseaw The truly valuable thing will be your `Configuration.h` and `Configuration_adv.h` files configured for those specific machines. Hopefully you can have those posted in your fork soon. Otherwise it will be very hard for users to configure.

**Comment by leseaw** [comment] 2015-09-28 13:57
i must first learn how github work :)
my problem is, if i make an change every time he will share this with marlin ??
next days i will make a new branch with marlin dev and with tmc2100 drivers

original Firmware:
https://github.com/leseaw/Marlin-Mankati-original

**Comment by thinkyhead** [comment] 2016-02-07 10:40
Please post a new issue if this is still a problem with Mankati or anyone else. For now I'm closing this for housecleaning.

**Closed as completed by thinkyhead** 2016-02-07 10:40 UTC
Labels: Needs: Work, Needs: More Data

**Comment by ModMike** [comment] 2018-09-01 02:10
Sorry to revive such an old thread but I ordered a Creatbot DX today thinking they used Marlin.  Anyone know for sure?

**Comment by thinkyhead** [comment] 2018-09-01 04:24
Looks like it.
![image](https://user-images.githubusercontent.com/698003/44942377-fd2a0080-ad74-11e8-8f6e-18d305176f4e.png)

**Comment by ModMike** [comment] 2018-09-01 09:56
The higher models have some kind of color touch screen, kinda threw me off.

**Comment by ModMike** [comment] 2018-10-02 22:24
I've been playing with a Creatbot DX (Ultimaker clone) for a few weeks.  Exceptionally well built machine, the only place they dropped the ball was using an 8 bit processor.

I disassembled the firmware and it is almost definitely a Marlin derivative.  I managed to install Marlin without flashing a boot loader.  Alex Kenis helped me figure out it was based on a Rumba and I was able to create a config.h and pins file for it.

They changed the screen to a a serial Dwin 480 X 272 touch screen model # DMT 48270M043_02WT.  If I understand correctly, the screen is simply sending G-Codes and acting as a host.  If this is the case do I just need to select a serial port and not configure a display?

The one perplexing thing is that they use a USB key instead of an SD card.  Any tips for configuring the USB key so it can be read as an SD by Marlin?

I will create a PR for the config and pins file as soon as I finish.

**Comment by InsanityAutomation** [comment] 2018-10-02 22:51
In discussion with them on an f430, they told me it is running marlin, so I'd suspect they use it across the board.

**Comment by ModMike** [comment] 2018-10-02 22:55
Wow, you're lucky, they got skittish and refused to answer me.  Spent about 5 full days trying to reverse engineer it.  I don't understand why these companies refuse to work with the Marlin team.  Even if they Patreon Scott, it would be way cheaper than the contortions they go through.

**Comment by InsanityAutomation** [comment] 2018-10-02 23:00
I had asked before creality made headlines for it - all about timing I suppose....

**Comment by Grogyan** [comment] 2018-10-03 02:21
With the USB key, are they using a USB to UART converter inside?

**Comment by ModMike** [comment] 2018-10-03 02:39
My biggest issue right now is that the Creatbot uses a an ADC597 with a K type thermocouple.  I set T0 and T1 to -1 as instructed in the notes.  Tool 0 shows 25 degrees yet I get a MAXTEMP triggered, system stopped.  I tried changing the pins to ADC 10 and 9 but no difference.  Any ideas?

**Comment by ModMike** [comment] 2018-10-03 02:54
Looks like there was an error in the pins files.  Once I set to pin 15, it worked perfectly.  Does that sound right?

**Comment by ModMike** [comment] 2018-10-03 17:53
I assume this is not the proper forum for debugging a Creatbot so I moved it here:  

https://reprap.org/forum/read.php?13,835425,835425#msg-835425

Hope to see a few of you there!

**Comment by ModMike** [comment] 2018-10-03 17:54
@Grogyan Yes it does.  Please go to his link for complete info:

https://reprap.org/forum/read.php?13,835425,835425#msg-835425
