### ISSUE TITLE
[2.0.x] "SD init fail" "Error:volume.init failed" on Creality Ender 2

### ISSUE THREAD

**Issue by CReimer** [MarlinFirmware/Marlin#9209] opened 2018-01-16 20:06 UTC
### Bug Report
I just flashed my new Creality Ender 2 with Marlin 2.0.x to get rid of the GPL violating firmware. Unfortunately it can no longer read from SD cards.

I think this is somewhat related to #7467 and #7468. But everything mentioned there doesnt' help.
I tried all delay settings mentioned and also experimented with SPI speeds.

When I push "SD init" in the OSD or send M21 I can see a black bar on the screen with a scrolling vertical line from left to right.

I tried disabling MINIPANEL but this doesn't solve anything either.

On the serial console I see "Error:volume.init failed" and sometimes "SD init fail".

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/1636582/Configuration.zip)

Thanks

Christopher

**Comment by CReimer** [comment] 2018-01-16 20:24
Switched from my configs to the example configs in bugfix-2.0.x branch and the bugfix-1.1.x branch.
With bugfix-1.1.x I can access the SD card after several tries. Haven't tried printing just yet but after the sd card is initialized it seems pretty stable.

With bugfix-2.0.x it's impossible to initialize the SD card.

**Comment by morsyfadl** [comment] 2018-01-17 20:52
SPI speed maybe? Try 1/8 speed

**Comment by CReimer** [comment] 2018-01-17 21:17
Unfortunately no. 1/8 speed doesn't help with bugfix-2.0.x and doesn't fix the sporadically working SD card with bugfix-1.0.x. Did a whole print with bugfix-1.0.x today. It took 3 or 4 tries to detect the SD card, but afterwards the print went fine.

**Comment by Bob-the-Kuhn** [comment] 2018-01-18 00:08
Maybe the card doesn't have an SD detect signal.

Comment out all instances of "#define SD_DETECT_PIN" in the pins_YOUR_BOARD.h file.

**Comment by CReimer** [comment] 2018-01-18 17:41
After following a few includes (pins_CREALITY_ENDER.h -> pins_SANGUINOLOLU_12.h -> pins_SANGUINOLOLU_11.h) I could only find one SD_DETECT_PIN which was already set to -1. Commenting this line didn't change the overall behaviour.

Something I came up with yesterday is, that the SD card gets always detected, when I insert the card and click the initialize SD button in the main menu immediately afterwards.

I tried two different SD card which both work fine on a RAMPS 1.4 board and a RADDS board.
1. SanDisk Ultra 16GB SDHC
2. SanDisk Edge 8GB SDHC (Came with the Ender 2)

**Comment by CReimer** [comment] 2018-01-18 22:26
I tried #9109 and it didn't help at first. After I figured out how SD cards are handled in Marlin I started adding some debug log messages. As it turns out there are two different chip select pins defined in Marlin. LCD_SDSS and SDSS

LCD_SDSS is set to Pin 28 and SDSS is set to Pin 31. To cut this short pin 28 is wrong and pin 31 is right. But LCD_SDSS is prefered.

It still doesn't work right after powering on, but it works while switching sd cards and after removing the SD card once after powerup.

Changing this pin in bugfix-2.0.x didn't help. It still only works with bugfix-1.1.x. But at least I have a more or less fully working printer again.

**Comment by thinkyhead** [comment] 2018-02-02 10:26
> LCD_SDSS is set to Pin 28 and SDSS is set to Pin 31. To cut this short pin 28 is wrong and pin 31 is right. But LCD_SDSS is preferred.

Could this really be wrong for all Sanguinololu 1.1 generic character displays? Or, does this only apply to the Ender setup?

**Comment by thinkyhead** [comment] 2018-02-02 11:52
Is it possible that our `BOARD_CREALITY_ENDER` should just be dropped? The `pins_MELZI_CREALITY.h` file has the correct pin 31 assignment for `LCD_SDSS`. And maybe the other pins are also more correct.

**Comment by CReimer** [comment] 2018-02-02 17:51
The `BOARD_MELZI_CREALITY` does work with bugfix-1.1.x and I don't have to edit any pins files. Unfortunately it's still broken with bugfix-2.0.x.

> Could this really be wrong for all Sanguinololu 1.1 generic character displays? Or, does this only apply to the Ender setup?

I'm not sure. There could be multiple revisions with different layouts. But I can't find any revision markings on my board. I could disconnect everything and upload some hi-res pictures of it, if you want those.

**Comment by thinkyhead** [comment] 2018-02-16 04:43
> The BOARD_MELZI_CREALITY does work with bugfix-1.1.x and I don't have to edit any pins files. Unfortunately it's still broken with bugfix-2.0.x.

The pins should match. If not, that will be corrected shortly.

If the pins already match then the issue is not the pins file, but something specific to the 2.0 AVR HAL.

**Comment by thinkyhead** [comment] 2018-02-18 09:24
@CReimer — There have been some minor tweaks and patches to `bugfix-2.0.x` today. So give that branch a test when you have time. If you find it still doesn't work, let's see if we can hunt down the cause.

When it fails, does it just reboot the board over and over, or does it do something worse?

**Comment by thinkyhead** [comment] 2018-02-26 20:31
Duplicate of #8746

Let's move discussion to that issue.

**Closed as completed by thinkyhead** 2018-02-26 20:31 UTC
Labels: Bug: Potential ?, Needs: More Data
