### ISSUE TITLE
[BUG] Not Respecting Software End Stops

### ISSUE THREAD

**Issue by n00dl3s** [MarlinFirmware/Marlin#15588] opened 2019-10-17 06:37 UTC
Attached is my config.

With an SKR v1.3 and tmc5160's after homing just the X axis to the MIN, I am still able to completely blow by the software end stop. 

Tried a great number of things, maybe its a bug?

Thanks!

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/3737693/Configuration.zip)

<img width="1920" alt="ENSTOPS" src="https://user-images.githubusercontent.com/26827185/66983593-bc22a780-f06d-11e9-8a22-0f5d769cdee9.png">

**Comment by n00dl3s** [comment] 2019-10-17 07:10
I was able to successfully get software end stops working using this fella's code

https://github.com/serialx/Marlin/tree/mpcnc-skr13-tmc5160


closing the issue since i now believe it a miss configuration on my end.

**Comment by AnHardt** [comment] 2019-10-17 08:13
Do we need to explain better the difference between 'software endstops' (not hardware) and 'sensor less endstops' (no extra hardware switches but in the TMC stepper drivers)?

**Comment by n00dl3s** [comment] 2019-10-19 19:22
Hi AnHardt

Thanks for the reply, I believe the documentation is adequate and don't believe that to be the problem

After further testing this weekend,I found on the newer commits software end-stops are not working as advertised. Sensor less homing is not enabled, I am using Micro Limit Switches for end-stops. 

My Setup is as follows.

SKR1.3
TMC5160's
Limit Micro Switch on the X'Axis

(I have 3 different skr boards ive tried to make sure that isnt the issue, and various tmc5160's all bigtree v1.2's)

**Once homed software end-stops do not keep any axis "in bounds" allowing negative values. (see screen shot)**

made sure software end-stops are enabled (m211 s1)

**Comment by boelle** [comment] 2019-10-24 11:53
@AnHardt do you think this is just a misunderstanding in how the config should be?

**Comment by boelle** [comment] 2019-10-30 22:37
will close this one as it seems to be a misunderstanding in how config should be

we can reopen later if there is a confirmed issue

**Closed as completed by boelle** 2019-10-30 22:37 UTC

**Comment by eightheads** [comment] 2019-12-08 02:03
I am currently having issues with software endstops not working with the current Marlin 2.0 branch pulled yesterday (12/06/19) on my SKR V1.3. I have confirmed they are enabled and defined in my configuration but movement will allow me to attempt to go less than 0 and over my max defined bed size.

**Comment by PapiOrso** [comment] 2020-02-13 17:53
I also have the same problem with endstop software not working on a SKR 1.4 turbo board with TMC5160 v1.2 drivers. Even "sensorless homing" doesn't work.
This board has too many problems and Bigtreetech technical support is useless. They just say they know the bug and are sorry. They are really useless!
