### ISSUE TITLE
PRINTER_EVENT_LEDS

### ISSUE THREAD

**Issue by Decalis1979** [MarlinFirmware/Marlin#22758] opened 2021-09-11 22:28 UTC
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

Feature not working in Marlin 2.0.9.1

### Expected behavior

When you start printing it should start:
1 with a pink to red color during heating.
2 White light during printing
3 Green light at the end of printing.

### Actual behavior

The lighting sequence does not occur

### Version of Marlin Firmware

2.0.9.1

**Comment by thisiskeithb** [comment] 2021-09-11 22:43
Duplicate of #22683

**Closed as completed by thisiskeithb** 2021-09-11 22:43 UTC
