### ISSUE TITLE
[FR] Filament Length Service Intervals

### ISSUE THREAD

**Issue by serenewaffles** [MarlinFirmware/Marlin#24218] opened 2022-05-20 21:48 UTC
### Describe the feature you want

The Print Counter advanced settings includes support for up to three service intervals. I would like to be able to set a service interval based on the extruded amount instead of the time spent printing. Ideally, this could be done for each nozzle in multi-nozzle setups, but combined is fine for me. Total extruded is already tracked as part of the Print Counter.

**Comment by thisiskeithb** [comment] 2022-05-24 14:08
Duplicate of https://github.com/MarlinFirmware/Marlin/issues/9934

**Closed as completed by thisiskeithb** 2022-05-24 14:08 UTC
Labels: T: Feature Request
