### ISSUE TITLE
Upgrade to Marlin 2.x bricks Ender Silent Boards 1.1.5

### ISSUE THREAD

**Issue by lockheed** [MarlinFirmware/Marlin#17614] opened 2020-04-19 20:23 UTC
I bought Ender 5 Pro with Silent Board 1.1.5. It had some old Creality Marlin on it (something like 1.1.6) so I upgraded it to 1.1.9. I already had bootloader installed, so it was an easy process.
I used the printer this way for couple of week and then decided to give Marlin 2.0.2 a try. So I flashed it just as the previous one. And that’s where problems started:

1.	8 out of 10 power ons, printer would not boot at all. The display turned on but was completely blank. Trying to get it on works sometimes, but it often takes so many power switch actions that I start worrying about mechanical/electrical damage it could cause. Naturally, resetting EPROM does nothing – neither from menu, nor gcode commands.
Other than – that the printer prints, but after every print once it homes the hotend, it crashes with EPROM ERROR on the otherwise blank display.

2.	You would think that something went wrong during flashing and I should be able to reflash the firmware. Logical. But no such luck. ArduinoIDE can no longer communicate with the printer! So what next?

3.	Bootloader reflash! So I re-flash the bootloader on the boards, flash Marlin again – any version I want -  and voila – it boots without any issues and no errors in sight… 
Until I discovered that all three axis appear to be completely dead. 

Running autohome from menu after few seconds produces:
```
Homing failed
PRINTER HALTED
Please reset
```

Moving axis individually from menu produces zero effect.

And homing from  gcode level goes like that:

```
>>> G28
SENDING:G28
echo:busy: processing
echo:busy: processing
echo:busy: processing
echo:busy: processing
echo:busy: processing
echo:busy: processing
echo:busy: processing
echo:busy: processing
echo:busy: processing
Error:Printer halted. kill() called!
[ERROR] Error:Printer halted. kill() called!
```

Some googling suggested printer might recognise endpoints as engaged and thus not moving. But after checking status printer returns they are not engaged.
4.	Contacted the seller who had no clue about that. We put it to a freak event. Eventually, he sent me a replacement Silent Board 1.1.5. So I flashed Marlin 1.1.9 on it and all was well for couple of months. Until I decided it’s time to upgrade to the newest Marlin 2.0.4…

5.	And now I am back to point 1. 

At least I can still use the printer in some capacity (when it decides to power on after ~10-20 powerons).

**Comment by thinkyhead** [comment] 2020-04-20 02:42
Please test the [`bugfix-2.0.x` branch](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.0.x.zip) to see where it stands. If the problem has been resolved then we can close this issue. If the issue isn't resolved yet, then we should investigate further.

**Comment by lockheed** [comment] 2020-04-20 07:23
I can't try any other version because upgrade to Marlin 2.x rendered the board unable to communicate with ArduinoIDE.

**Comment by sl1pkn07** [comment] 2020-04-20 22:28
inlcude ISP (usbasp) pins?

**Comment by ellensp** [comment] 2020-04-20 23:09
Bricking the board is not very likely, The atmega1284p, like most 8 bit arduino boards, Has a section of the flash partitioned off as the bootloader. It is set in hardware that nothing can write to the bootloader area. Thus you need external hardware (ie a  avrisp) to over write it. It is much more likely that the controller has just died.  
But the board has a clearly labeled 6 pin ISP header, so the first thing is to try and put a new bootloader on it. Just to see if there is any life in the board at all. 
Also make sure to set your fuse bits correctly. Not doing this can for eg leave jtag enabled which breaks anything connected to IO pins that are stuck being a jtag.

**Comment by lockheed** [comment] 2020-04-21 11:47
I would appreciate if you guys read carefully the issue description. 
Flashing bootloader on this half-bricker board will render it completely useless, because although the software issues would go away, all axis motors will stop functioning at all, rendering half-bricked board to completely bricked.

And it does not look like a case of controller just dying, because it is already the second board with exact same issue after upgrading to Marlin.

**Comment by thinkyhead** [comment] 2020-04-23 01:08
> I would appreciate if you guys read carefully the issue description.

As time allows…. Everyone here is just like you, helping the project in their free time for fun, and life does not always allow quick turnaround.

---
What kind of messages do you get back when using PlatformIO to do the upload? These might be a little more detailed. We also have the ability to massage many build settings through PlatformIO that we cannot through Arduino IDE, so I'd recommend you grab VSCode and the Auto Build Marlin extension and use these tools going forward, and it would be interesting to see if the build behaves differently. https://marlinfw.org/docs/basics/auto_build_marlin.html

**Comment by lockheed** [comment] 2020-04-24 13:17
Thanks for pointing me to PlatformIO. I tried compiling the source (with  Ender 5 Pro config files from latest zip on Marlin download page) but what board for Silentboard 1.1.5 am I supposed to select when importing? I picked Sanguino ATMega 1284p (16Mhz), as it was the case when uploading with Arduino IDE, but build process fails with error:
https://pastebin.com/jbur1Uvd

If I try Autobulid plugin with melzi board, I get this error:
https://pastebin.com/tNJ14Mwi
And if I edit the config file as per error message, I get this error:
https://pastebin.com/2dH1tvfv

**Comment by sl1pkn07** [comment] 2020-04-24 13:37
for the creality boards is melzi or meltzi_optimboot

and you also
~~~
Marlin/src/HAL/AVR/../../inc/SanityCheck.h:499:4: error: #error "[XYZ]_HOME_BUMP_MM is now HOMING_BUMP_MM. Please update Configuration_adv.h."
   #error "[XYZ]_HOME_BUMP_MM is now HOMING_BUMP_MM. Please update Configuration_adv.h."
    ^
*** [.pio/build/mega2560/src/src/HAL/AVR/HAL.cpp.o] Error 1
~~~
needs fix your config

**Comment by lockheed** [comment] 2020-04-24 13:40
When you were responding, I edited my post to update error messages with melzi board.

**Comment by sl1pkn07** [comment] 2020-04-24 13:42
yes, but is the same, needs update your config files

please share it

**Comment by lockheed** [comment] 2020-04-24 13:45
Yes, I introduced the config  change you mentioned and I am getting error from the last link. above.

That's the full config adv: https://pastebin.com/DGNFnHXv

**Comment by sl1pkn07** [comment] 2020-04-24 13:49
hwta version you use?

because now `HOMING_BUMP_MM` is

https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/Marlin/Configuration_adv.h#L611

and you use the old method

![Screenshot_20200424_154901](https://user-images.githubusercontent.com/462213/80219700-22067200-8643-11ea-9e56-eb5a267cf486.png)

**Comment by lockheed** [comment] 2020-04-24 14:03
This one: 
![image](https://user-images.githubusercontent.com/3472480/80220892-cdfc8d00-8644-11ea-8042-f8d4c9fb9d20.png)

Anyways, replaced the file with the one you linked and it compiled. Thanks!

So here's the error when trying to upload it to the printer - it's the same one as in ArduinoIDE:
https://pastebin.com/hCA4ekB2

**Comment by sl1pkn07** [comment] 2020-04-24 15:15
with usb or through the ISP port?

**Comment by lockheed** [comment] 2020-04-24 15:23
USB port. 
ISP port? Is it something that could be done with AdruinoUNO board?

**Comment by sl1pkn07** [comment] 2020-04-24 15:31
yep

**Comment by lockheed** [comment] 2020-04-24 15:35
Ok. Is there some howto on setting this up? My googling only finds Uno Bootloader flashing, not firmware.

**Comment by ellensp** [comment] 2020-04-24 16:05
Please read this. https://reprap.org/forum/read.php?158,871425

**Comment by lockheed** [comment] 2020-04-24 22:17
I followed it but now it can't compile:
https://pastebin.com/tt3KDhV2

**Comment by lockheed** [comment] 2020-04-24 23:40
Brilliant! After some trial and error I managed to flash the firmware this way and now the printer seems to behave as it should. Thanks a lot.

Two matters, though:
1. Do you think it is wise to now try the optiboot flash? I am hesitant as the last time I flashed a bootloader (regular one using ArduinoIDE once this above problem happened on my previous board) the axis stopped working completely.

2. Upgrading Marlin though ArduinoIDE software rather than PlatformIO is, I think, much more popular due to multiple howtos on youtube. And the problem there seems to be real as it happened to two of my boards. Perhaps it is worth looking into?

**Comment by boelle** [comment] 2020-06-20 22:43
Lack of Activity
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.

**Closed as completed by boelle** 2020-06-20 22:43 UTC
