### ISSUE TITLE
[BUG] [Bugfix 2.0.x] SKR Mini E3 DIP (STM32) with TMC2130 booting issues with TMC_DEBUG enabled

### ISSUE THREAD

**Issue by AmiSMB** [MarlinFirmware/Marlin#15226] opened 2019-09-11 15:08 UTC
### Description

I have replaced my stock Creality Ender 3 main board with the SKR Mini E3 DIP with TMC2130 drivers and a BLTOUCH. Using the latest commits from bugfix-2.0 branch I have found that if TMC_DEBUG is enabled then the firmware is flashed on the first boot with the new firmware but after a power down and a reboot the firmware does not load even though there is a FIRMWARE.CUR on the SD Card which matches the firmware.bin file that was added to the card. I did compile the firmware before with the same configuration and was able to have TMC_DEBUG and use the M122 command without an issue. The only difference that I can see is that with the latest commits I now see the SD card mounted when I plugin the USB cable to my computer whereas I did not before. The PR that relates to this is #15180

### Steps to Reproduce

1. Write firmware.bin to SD card and insert into board
2. Power up board and wait just over 10 seconds for firmware to flash and load
3. Power off board
4. Power on board firmware flashes again and starts up correctly
5. Power off board
6. Power on and nothing happens on the LCD and unable to connect via serial port
7. Recompile with TMC_DEBUG disabled
8. Write firmare.bin to SD card and insert into board
9. Board flashes correctly and is fine after power cycling

**Expected behavior:** 
I expected the board to start with the firmware that is now flashed to the board via the bootloader.

**Actual behavior:**
Board does not start until I put firmware.bin back on the SD card and repeat the process and if I do not comment out the TMC_DEBUG line then I end up with a non booting board after power cycling more than twice.

#### Additional Information

I have attached my configuration files

[Ender3_SKR_E3_DIP_TMC2130_BLTOUCH.zip](https://github.com/MarlinFirmware/Marlin/files/3601454/Ender3_SKR_E3_DIP_TMC2130_BLTOUCH.zip)

**Comment by brew99** [comment] 2019-09-11 19:38
I can't even compile the latest version with my SKR mini E3 (non-DIP version)  and TMC_DEBUG enabled.  Error says something in regards to "won't fit on ROM".   Comment out TMC_DEBUG and I'm good at 26.9% DATA, and 86.2% PROGRAM.

I ran into the issue you were having about a week ago, then on Sep6 version it was OK.   Today it won't fit.

**Comment by AmiSMB** [comment] 2019-09-11 20:00
I had the same problem but the config I posted here compiles fine as I made sure I uncommented SLIM_LCD_MENUS which helps a lot.

**Comment by thisiskeithb** [comment] 2019-09-11 22:12
It's probably safe to assume that `TMC_DEBUG` and emulated `EEPROM` are not compatible on the SKR Mini line of boards.

@tpruvot: Do you have other `STM32F1` hardware with emulated `EEPROM` & `TMC_DEBUG` enabled to test if there are similar issues?

**Comment by tpruvot** [comment] 2019-09-11 22:44
TMC_DEBUG on skr mini, no issue (TMC2208 here)
DATA:    [===       ]  25.5% (used 12536 bytes from 49152 bytes)
PROGRAM: [========  ]  78.4% (used 205564 bytes from 262144 bytes)

**Comment by thisiskeithb** [comment] 2019-09-11 23:07
> TMC_DEBUG on skr mini, no issue (TMC2208 here)
> DATA: [=== ] 25.5% (used 12536 bytes from 49152 bytes)
> PROGRAM: [======== ] 78.4% (used 205564 bytes from 262144 bytes)

Have you tried emulated `EEPROM` on the Longer3D board?

**Comment by tpruvot** [comment] 2019-09-12 07:31
I use both here on it, to easily swap Marlin and a more "Stable/tested" firmware. No issue on config nor G29 mesh data but printer stats doesnt work (PRINTCOUNTER)

**Comment by YpsilonTM** [comment] 2019-09-12 18:44
Well Im having the same problem, not enought space. Could `EEPROM` emulation and `TMC__DEBUG` really be to much?

**Comment by AmiSMB** [comment] 2019-09-12 18:59
> Well Im having the same problem, not enought space. Could `EEPROM` emulation and `TMC__DEBUG` really be to much?

The issue with not enough space is not EEPROM and TMC_DEBUG. I had both enabled but as I mentioned in an earlier post I found uncommenting SLIM_LCD_MENUS fixed the space issue. I notice that Michael Laws (Teaching Tech) disables the arc feature when he compiled for the original board to make some space.

**Comment by AmiSMB** [comment] 2019-09-12 19:00
> TMC_DEBUG on skr mini, no issue (TMC2208 here)
> DATA: [=== ] 25.5% (used 12536 bytes from 49152 bytes)
> PROGRAM: [======== ] 78.4% (used 205564 bytes from 262144 bytes)

My issue is with the TMC2130 and I do not have any TMC2208 to test with at the moment.

**Comment by YpsilonTM** [comment] 2019-09-12 19:55
> > Well Im having the same problem, not enought space. Could `EEPROM` emulation and `TMC__DEBUG` really be to much?
> 
> The issue with not enough space is not EEPROM and `TMC_DEBUG`. I had both enabled but as I mentioned in an earlier post I found uncommenting SLIM_LCD_MENUS fixed the space issue. I notice that Michael Laws (Teaching Tech) disables the arc feature when he compiled for the original board to make some space.

I commented `#define SHOW_BOOTSCREEN` and i could compile to so it's a space issue. I now have `EEPROM` and `TMC_DEBUG` enable at the moment. and `SLIM_LCD_MENUS` is still disabled so it looks like its really just a space issue.

**Comment by tpruvot** [comment] 2019-09-12 22:16
there is indeed something going on, after resynching libs, my U30 firmware is now 30KB bigger, and i see many new TMC warnings... btw, not using TMC on this board, same with TMCStepper lib ignored

one of those :
```
-rw-rw-r--    4722 sept. 13 00:20 .pio/build/alfawise_U30/lib1bb/libSailfishRGB_LED.a
-rw-rw-r--    3726 sept. 13 00:20 .pio/build/alfawise_U30/lib35c/libSlowSoftI2CMaster.a
-rw-rw-r-- 1830574 sept. 13 00:20 .pio/build/alfawise_U30/lib5a7/libU8glib-HAL_ID1932.a
-rw-rw-r--   10880 sept. 13 00:20 .pio/build/alfawise_U30/lib732/libSTM32ADC.a
-rw-rw-r--   13836 sept. 13 00:20 .pio/build/alfawise_U30/lib96e/libSailfishLCD.a
-rw-rw-r--   13894 sept. 13 00:20 .pio/build/alfawise_U30/lib96f/libWire.a
-rw-rw-r--  133958 sept. 13 00:20 .pio/build/alfawise_U30/lib9fa/libUSBComposite.a
-rw-rw-r--   49270 sept. 13 00:20 .pio/build/alfawise_U30/libccd/libLiquidCrystal_ID136.a
-rw-rw-r--    9522 sept. 13 00:20 .pio/build/alfawise_U30/libe0e/libEEPROM.a
-rw-rw-r--   15286 sept. 13 00:20 .pio/build/alfawise_U30/libf52/libArduino-L6470.a
```

**Comment by tpruvot** [comment] 2019-09-12 23:51
so, issue was libUSBComposite, you need to disable it in platformio.ini to save 30KB (if needed when you enable too **many** other features) 

remove the `-DUSE_USB_COMPOSITE` in your env for that

btw i tested a bit this feature on the skr mini and cause random freeze (if you do drive properties for example in windows explorer, but seen other cases on boot/reboot)

**Comment by salacpavel** [comment] 2019-09-13 05:09
...Besides, SD card insertion is no longer detected and it needs to manually autodetected, ever since this commit.

**Comment by tpruvot** [comment] 2019-09-13 05:10
indeed, unsure it ever was auto at some point in the "real" Marlin

fun fact, the windows sd share is "mounted" :p

**Comment by thinkyhead** [comment] 2019-09-13 11:11
> SD card insertion is no longer detected

Is `SD_DETECT_PIN` being set as `-1`?

**Comment by salacpavel** [comment] 2019-09-13 15:20
> 
> 
> > SD card insertion is no longer detected
> 
> Is `SD_DETECT_PIN` being set as `-1`?

No, its set as PC4

**Comment by tpruvot** [comment] 2019-09-14 00:30
try #15255 works well on the mini if you ignore the possible hangs caused by the usb composite (unrelated to the PR). If that happens, unplug the usb on boot

**Comment by boelle** [comment] 2019-09-24 19:26
@AmiSMB still having issues?

**Comment by AmiSMB** [comment] 2019-09-25 12:46
I am going to try a pull tonight and enable TMC_DEBUG and see if the same thing happens

**Comment by AmiSMB** [comment] 2019-09-27 15:41
So after testing with different configurations this is my findings with the latest branch of bugfix-2.0.x at commit 62e4e05a1947b006dfbaa33e33a75dcd30cf993b

platformio.ini
default_envs = STM32F103R_bigtree_USB
   If TMC_DEBUG is enabled this requires SLIM_LCD_MENUS to be enabled so that the firmware is not too big. The firmware is uploaded correctly on the first power up. After powering down and turning back on again the firmware does not load and just the LCD backlight is lit. Looking at the SD card FIRMWARE.CUR is a zero byte sized file.
  I also found that if you mount the SD card under an OS then the serial connection is stopped and you cannot reconnect unless you unplug and replug in the USB cable.

platformio.ini
default_envs = STM32F103R_bigtree
   As the USB Composite is not included then the TMC_DEBUG can be enabled as well as SLIM_LCD_MENUS can be disabled as this will fit the flash size. Everything works fine apart from the fact you cannot mount the SD card under an OS, which is to be expected as USB Composite is not enabled. Firmware is uploaded on first boot and starts without a problem after every power cycle.

**Comment by TimoBre** [comment] 2019-09-28 09:07
Hi, I'm new at the GitHub, so :-)


My Comment about the wrong MCU was deleted, because it was already written here : https://github.com/MarlinFirmware/Marlin/issues/15254

**Comment by boelle** [comment] 2019-10-24 21:30
will close this one as it seems to be working

we can always reopen if its not the case

**Comment by reloxx13** [comment] 2019-10-25 13:28
> will close this one as it seems to be working
> 
> we can always reopen if its not the case

its not "working". its a space issue, if its not possible to detect it by the build script, this can be closed.
devs have to answer if they want to catch this error.
if not, we will get more "issues" asking why its not working cause it does not show its out of space.

**Comment by boelle** [comment] 2019-10-25 13:31
hehe, forgot to hit close :-D

but since its not working 100% we should keep it open

**Comment by boelle** [comment] 2019-11-06 10:39
@thinkyhead @shitcreek time to have a look here before the issue gets lost and not fixed

**Comment by boelle** [comment] 2019-11-11 12:38
@thinkyhead @shitcreek time to have a look here before the issue gets lost and not fixed

**Comment by boelle** [comment] 2019-11-21 20:27
@thinkyhead @shitcreek time to have a look here before the issue gets lost and not fixed

**Comment by AmiSMB** [comment] 2019-11-26 22:22
Have been playing around with different firmware files and I am compiling for the 256k chip but when the firmware file gets around 230k I experience issues. I have tried 512k chip builds but I think that my board has a bootloader which refuses to support this so will have to check with an ST Flasher when it arrives.

**Closed as completed** 2019-11-26 22:41 UTC
