### ISSUE TITLE
[2.0.x] Due/Radds Auto PID Tuning Large hotend / Bed Temperature swings

### ISSUE THREAD

**Issue by bruce356** [MarlinFirmware/Marlin#9449] opened 2018-02-03 04:32 UTC
Cartesian dual X Carriage printer, have done several Auto PID on both hotends and Bed.
Can not achieve sensible numbers or even temperature output (set point is 245 deg. & 90 deg.). 
Temperatures Bed & Hotend constantly fluctuates (2 to 3 degrees) until after 4 hours into a print FAILURE, with a 4 degree below set point drop in bed temperature.
(ERROR Thermal Runaway System Stopped! Heater ID: Bed.) 
Using E3d v6 hotends with 40 watt 24 volt heaters and 220 watt 24 volt heated Bed.

Same Machine with Repetier loaded and Repetier Auto PID's, temperature fluctuations are only ever +- 0.1 deg. for both hotend or bed.

Not necessarily being critical of Marlin but just using Repetier as a base reference point.

MARLIN Auto PID Results for BED:-
Kp 324.23
Ki 47.68
Kd 551.20

MARLIN Auto PID Results for HOTEND:-
Kp 16.73
Ki 1.47
Kd 47.52

REPETIER Auto PID Results for BED:-
Kp: 179.12
Ki: 23.50
Kd: 341.33

REPETIER Auto PID Results for HOTEND:-
Kp: 8.57
Ki: 0.69
Kd: 26.57

As a very rough comparison the numbers are almost half with Repetier (not sure if it is comparable).

![image](https://user-images.githubusercontent.com/209844/35762808-edd827e6-08ed-11e8-98ec-456ac18166be.png)
Graph image above shows the temperature fluctuations with MARLIN.
---------------------------------------------------------------------------------------

![image](https://user-images.githubusercontent.com/209844/35762863-166292f4-08ef-11e8-9d71-8a4c3bbd584f.png)
Graph above shows the steady temperature of the HOTEND with Repetier.
-------------------------------------------------------------------------------------

![image](https://user-images.githubusercontent.com/209844/35762886-a79e645a-08ef-11e8-8af7-c53915e8c800.png)
Graph above shows the steady temperature of the BED with Repetier.
----------------------------------------------------------------------------------

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/1691384/Marlin.zip)

Regards - bruce
As a side note with Repetier using the  "RADDS_DISPLAY" one of the screens shows the percentage of power used on heaters this would be a very useful addition in Marlin.
![radds display](https://user-images.githubusercontent.com/209844/35763272-8909b522-08f8-11e8-9b3e-f0dd3878e145.jpg)

**Comment by thinkyhead** [comment] 2018-02-17 00:48
Duplicate of #9426

**Closed as completed by thinkyhead** 2018-02-17 00:48 UTC
