### ISSUE TITLE
[FR] Add custom LCD abort print script

### ISSUE THREAD

**Issue by GameFan01** [MarlinFirmware/Marlin#20555] opened 2020-12-23 19:35 UTC
I'd like you to make it possible to customize what the printer will do if you stop the print from the LCD menu. For example to present the print by moving Y to the max position or unload filament.

Sorry if this is not the right place to post this, as this is the first time I'm writing here.
Thank you for your time.

**Comment by thisiskeithb** [comment] 2020-12-23 23:54
Duplicate of https://github.com/MarlinFirmware/Marlin/issues/20513

**Comment by thisiskeithb** [comment] 2020-12-23 23:55
You can already customize Marlin's actions when you abort a print. Just change `G28XY` to whatever you want:

https://github.com/MarlinFirmware/Marlin/blob/f74015b4e57677cd033e116dab2331478edbe2ec/Marlin/Configuration_adv.h#L1184

**Closed as completed by thisiskeithb** 2020-12-23 23:54 UTC

**Comment by GameFan01** [comment] 2020-12-24 11:51
Thanks for the info.
