### ISSUE TITLE
TM2209 - Sensorless Homing Z issue (ENDER3) SKR V1.4 Turbo

### ISSUE THREAD

**Issue by destruct123** [MarlinFirmware/Marlin#18439] opened 2020-06-27 02:22 UTC
Bug Description

Sensorless homing works for X and Y, but simply dont trigger in Z axis.

### My Configurations

[config.zip](https://github.com/MarlinFirmware/Marlin/files/4839838/config.zip)

### Steps to Reproduce

1. Open Pronterface and conect to the printer
2. Home Z axis

**Expected behavior:** [What you expect to happen]

Stop at Z0

**Actual behavior:** [What actually happens]

Keeps trying to go down.

**Comment by thisiskeithb** [comment] 2020-06-27 02:52
> Keeps trying to go down.

Sensorless probing is not recommend for machines that use a leadscrew for this very reason.

https://github.com/MarlinFirmware/Marlin/blob/8474050adbe1bd4d363397cfedefaee996ac1e98/Marlin/Configuration.h#L951-L957

**Comment by ABLomas** [comment] 2020-06-27 07:23
But what's interesting - i have disabled sensorless homing on Z-axis, enabled bltouch (comm working - i can control it from menu), merged configs from earlier version (using winmerge for only changes i need) - still only X and Y homing is working. When i try to home Z - it tries to drill trough bed.
Tested on todays bugfix, re-checking configs, but so far it looks that Z-axis is ignored (SKR 1.4 turbo)

**Comment by thisiskeithb** [comment] 2020-06-27 07:25
Did you cut/remove the diag pin on Z? You’ll have to do that when using a probe.

**Comment by ABLomas** [comment] 2020-06-27 07:26
No, i did not and it was working fine on earlier build (approx 05.20 bugfix branch, can tell exact date later). AFAIK no need to cut anything with SKR 1.4 and TMC2209...

**Comment by thisiskeithb** [comment] 2020-06-27 07:31
You’ll need to cut/remove the diag pins from any axis with traditional endstops, probes, or filament runout (E0) since BigTreeTech did away with the diag jumpers.

**Comment by ABLomas** [comment] 2020-06-27 07:37
We are talking about some different things.
I did not connected any switches on X and Y axis to board and did not cut any pins. X and Y homing works now and was working earlier.
I connected bltouch to board and Z-axis homing was working fine on earlier firmware version, i printed many small prints with it and i'm sure it was working as expected without any pins cut.
What i did - merged configs and updated to new (todays) bugfix and now Z-axis homing does not work anymore.
Maybe firmware changed in a way that cutting pins is now mandatory. 

SKR manual say, that i need to cut switch only if i'm using mechanical endstops and not using stallguard. I do not use mechanical endstops and use stallguard on XY axis (this is where it is working) and do not use stallguard on Z axis and no mechanical endstop, but probe on Z axis.

(also, i'm not OP so maybe there are different issues here)

**Comment by thisiskeithb** [comment] 2020-06-27 07:39
> (also, i'm not OP so maybe there are different issues here)

I didn't see that, so most likely.

**Comment by destruct123** [comment] 2020-06-27 10:46
> > Keeps trying to go down.
> 
> Sensorless probing is not recommend for machines that use a leadscrew for this very reason.
> 
> https://github.com/MarlinFirmware/Marlin/blob/8474050adbe1bd4d363397cfedefaee996ac1e98/Marlin/Configuration.h#L951-L957

I think i'll keep my Z-axis sensor and keep sensorless other axis. Because even with 255 set in stallguard it still don't trigger my Z-axis sensorless homing. I'm not using a probe, just leting the axis hit it's end as the other axis, and i saw that it can damage the leadscrew if you let it keep going.

**Comment by boelle** [comment] 2020-06-27 12:56
Sensorless on screws will never work, i tried it even with lower amps on the steppers they are simply have to much torque for sensorless to work

**Comment by deltaford** [comment] 2020-06-28 21:29
@boelle  It absolutely can work but depends on having a machine designed for it.

I use it with a custom built CoreXY with SKR v.1.4 TURBO and sensorless TMC2209 on X, Y & Z and it works perfectly.
Z is designed with moving bed with 4 lead screws i corners, belt driven by a single stepper.

**Comment by HunterWare** [comment] 2020-06-30 14:11
Like boelle, I have tried z with leadscrew on all sensitivities and was never able to find one that worked at all, even unreliably.

You can certainly run a setup with the SKR1.4 + BLTouch without clipping the TMC2209 pins.  On my Ender5 with SKR1.4T and BLTouch I run sensorless on X/Y, and then wired up the BLTouch as documented.

You put the two plugs into "SERVOS" and "PROBE" (you might have to switch a pin or two in the header, check the wiring).

The you set the following:
- define USE_ZMIN_PLUG
- define Z_MIN_PROBE_ENDSTOP_INVERTING true
- define Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN
- define USE_PROBE_FOR_Z_HOMING
- define Z_MIN_PROBE_PIN P0_10
- define BLTOUCH
- define NOZZLE_TO_PROBE_OFFSET { -44, -8, -1.85 } // This is for my Ender5 with Creality mount
- #define Z_MIN_PROBE_REPEATABILITY_TEST // Do the M48 test to get confidence in probe

Now you are running sensorless X/Y so you don't have to clip them.  You are running BLTouch for Z stop, and the firmware will always deploy the probe for homes and thus you don't have to clip Z since the board is using a different pin.

Side note: this seems more like a request for help than a bug report / issue.  As in, the firmware is functioning as designed but is being misconfigured.
- Sensorless is known (and documented) to not work with leadscrews
- normal endstops are known not to work with SKR1.4 + unclipped TMC2209
- Probes work fine if you use a different pin, or clip the Z TMC2209 pin and use that GPIO.
- None of this is a firmware issue...

Maybe the issue should be closed?

HTH

**Comment by thisiskeithb** [comment] 2020-06-30 14:14
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).

**Closed as completed by thisiskeithb** 2020-06-30 14:14 UTC
