### ISSUE TITLE
SD Card not working 1.1.8

### ISSUE THREAD

**Issue by RitoonL** [MarlinFirmware/Marlin#11443] opened 2018-08-03 15:07 UTC
Hi,

I tried hard but i can't make work the SDCARD on 1.1.8 (neither bugfix) with GT2650 REV A+.
The card is detected but the files won't appear, except it i remove and reinsert the card several times. When the files finally appear, they can't be selected.

This is not a hardware issue as it works perfectly on stock firmware of my machine. The printer is a geeetecht i3 pro b.

**Comment by thinkyhead** [comment] 2018-08-07 22:24
Please test with the latest `bugfix-1.1.x` (and/or `bugfix-2.0.x`) branch to see where it stands. If the problem has been resolved then we can close this issue. If the issue isn't resolved yet, then we should investigate further.

**Comment by BeppeMarnell** [comment] 2018-08-12 22:37
I had the same thing recently. Try to reflash the firmware, do a reset, turn on and off the machine or format the sd card ( FAT32 ). It has problem when it is full.

**Comment by boelle** [comment] 2019-02-20 15:33
@RitoonL tried latest bugfix 2.0?

**Closed as completed** 2019-02-20 19:47 UTC
