### ISSUE TITLE
[BUG] AUTO_POWER_CONTROL broken for SKR14T in b9ed139

### ISSUE THREAD

**Issue by Evg33** [MarlinFirmware/Marlin#21182] opened 2021-02-24 20:31 UTC
SKR14T not boot If AUTO_POWER_CONTROL defined. (bugfix-2.0.x)
Broken in https://github.com/MarlinFirmware/Marlin/commit/b9ed139546d4d35cf925926e93f76d80245db7dc
Before b9ed139 working ok. With b9ed139 not boot.

```
#define AUTO_POWER_CONTROL      // Enable automatic control of the PS_ON pin
  #if ENABLED(AUTO_POWER_CONTROL)
    #define AUTO_POWER_FANS         // Turn on PSU if fans need power
    #define AUTO_POWER_E_FANS
    //#define AUTO_POWER_CONTROLLERFAN
    //#define AUTO_POWER_CHAMBER_FAN
    #define AUTO_POWER_E_TEMP          50 // (В°C) Turn on PSU if any extruder is over this temperature
    //#define AUTO_POWER_CHAMBER_TEMP  30 // (В°C) Turn on PSU if the chamber is over this temperature
    #define POWER_TIMEOUT             180 // (s) Turn off power if the machine is idle for this duration
    //#define POWER_OFF_DELAY          60 // (s) Delay of poweroff after M81 command. Useful to let fans run for extra time.
  #endif

```

and i tested with:
```
  #define AUTO_POWER_CONTROL      // Enable automatic control of the PS_ON pin
  #if ENABLED(AUTO_POWER_CONTROL)
    //#define AUTO_POWER_FANS         // Turn on PSU if fans need power
    //#define AUTO_POWER_E_FANS
    //#define AUTO_POWER_CONTROLLERFAN
    //#define AUTO_POWER_CHAMBER_FAN
    //#define AUTO_POWER_E_TEMP          50 // (В°C) Turn on PSU if any extruder is over this temperature
    //#define AUTO_POWER_CHAMBER_TEMP  30 // (В°C) Turn on PSU if the chamber is over this temperature
    //#define POWER_TIMEOUT             180 // (s) Turn off power if the machine is idle for this duration
    #define POWER_TIMEOUT             30 // (s) Turn off power if the machine is idle for this duration
    #define POWER_OFF_DELAY          60 // (s) Delay of poweroff after M81 command. Useful to let fans run for extra time.
  #endif

```

**Comment by FanDjango** [comment] 2021-02-24 21:15
Duplicate of #21046. Temporary fix is easy

**Comment by thisiskeithb** [comment] 2021-02-25 04:44
Duplicate of #21046

**Closed as completed by thisiskeithb** 2021-02-25 04:44 UTC
