### ISSUE TITLE
[BUG] USB COMPOSITE for BTT E3 SKR DIP not working

### ISSUE THREAD

**Issue by UncleBansh** [MarlinFirmware/Marlin#15587] opened 2019-10-17 06:30 UTC
### Description
I am flash last commit, use in platformio.ini STM32F103R_bigtree_USB, but arter flashing cartreader over usb not working on my board

what I do wrong?

**Comment by reloxx13** [comment] 2019-10-17 07:29
the env is bugged, remove the non-usb block and rename the usb enviroment to the non usb name.


i did this here, you can copy this ini file over yours.
https://github.com/reloxx13/Marlin/blob/my-skr-mini-e3/platformio.ini


Duplicate:
[BUG 2.0.x]Autobuild STM32F103R_bigtree_USB not detected #15306

**Comment by UncleBansh** [comment] 2019-10-17 08:07
> the env is bugged, remove the non-usb block and rename the usb enviroment to the non usb name.
> 
> i did this here, you can copy this ini file over yours.
> https://github.com/reloxx13/Marlin/blob/my-skr-mini-e3/platformio.ini
> 
> Duplicate:
> [BUG 2.0.x]Autobuild STM32F103R_bigtree_USB not detected #15306

EEPROM works fine after that?

**Comment by reloxx13** [comment] 2019-10-17 10:37
> EEPROM works fine after that?

EEPROM in flash did not work for me. sd works.

i disabled `FLASH_EEPROM_EMULATION` in the `Marlin\src\pins\stm32\pins_BIGTREE_SKR_MINI_E3.h` file to get eeprom (on sd card) working.

**Comment by boelle** [comment] 2019-10-17 17:22
so this is maybe not a marlin bug?

**Comment by reloxx13** [comment] 2019-10-17 17:24
> 
> 
> so this is maybe not a marlin bug?

what else if the plaformio.ini or build script is wrong?

**Comment by boelle** [comment] 2019-10-17 17:30
upps... in that case yes, a PR sent to bugfix 2.0.x would be the fastest fix it

**Comment by brianredbeard** [comment] 2019-10-17 21:15
This seems to be related to the issue @Bansh1990 was experiencing in https://github.com/MarlinFirmware/Marlin/issues/15269

**Comment by UncleBansh** [comment] 2019-10-18 05:38
umm... I'm tried, 

> the env is bugged, remove the non-usb block and rename the usb enviroment to the non usb name.
> 
> i did this here, you can copy this ini file over yours.
> https://github.com/reloxx13/Marlin/blob/my-skr-mini-e3/platformio.ini
> 
> Duplicate:
> [BUG 2.0.x]Autobuild STM32F103R_bigtree_USB not detected #15306

it doesn't help me( i'm try to waiting a fix.
composite still not working.

**Comment by boelle** [comment] 2019-10-26 20:20
@Bansh1990 many updates have been done, does it still not work? and is https://github.com/MarlinFirmware/Marlin/issues/15269 a dublicate of this one?

**Comment by boelle** [comment] 2019-11-03 13:59
Duplicate of #15269

**Closed as completed by boelle** 2019-11-03 13:59 UTC
