### ISSUE TITLE
[BUG] LCD RADDS

### ISSUE THREAD

**Issue by boubouexpress** [MarlinFirmware/Marlin#16062] opened 2019-12-01 13:42 UTC
hello

during printing I can not use the LCD menu

screen turns off and on again after a few seconds if I click on the encoder button

merci
[marlin.zip](https://github.com/MarlinFirmware/Marlin/files/3908261/marlin.zip)

**Comment by shitcreek** [comment] 2019-12-02 21:42
Have you tried increasing the `BLOCK_BUFFER_SIZE`?

**Comment by boubouexpress** [comment] 2019-12-03 18:46
Yes go to 32
The screen does not turn off
From the moment the printer starts printing
I can access with a lot of latency as if I was waiting to be released.

**Comment by boelle** [comment] 2019-12-04 21:26
is this a bug or not????

![image](https://user-images.githubusercontent.com/3832239/70182924-1abae800-16e5-11ea-9f7c-4474b5e3d957.png)


the list is for bugs or feature request only, so if your issue is not a bug or feature request then please use any of these fine places:

RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
[Tom's 3D Forums](https://discuss.toms3d.org/)
Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
[Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
Marlin Discord server. Join link: https://discord.gg/n5NJ59y

**Comment by boelle** [comment] 2019-12-07 12:32
will close this one until er hear from @boubouexpress 

we need to know if this is a bug or not, and what is wrong

**Comment by boubouexpress** [comment] 2019-12-07 12:34
it's a bug
my screen does not react anymore when print and in court

**Comment by boubouexpress** [comment] 2019-12-07 12:36
functions perfectly before printing
after the hot and finish and it starts to evect the printing movement
it correctly display the information but I can not access the menu anymore

**Comment by boubouexpress** [comment] 2019-12-07 12:37
sorry for the translation

**Comment by boubouexpress** [comment] 2019-12-07 12:40
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/3935065/Configuration.zip)

**Comment by boelle** [comment] 2019-12-07 12:41
oki, that makes a bit more sense

and i say sorry for not understanding better :-)

**Comment by boubouexpress** [comment] 2019-12-07 12:47
it's normal with google translation
thank you

**Comment by AnHardt** [comment] 2019-12-07 13:33
I can hear your processor screaming, begging for mercy.

#define XYZ_MICROSTEPS 128
#define MIN_STEPS_PER_SEGMENT 1
#define BLOCK_BUFFER_SIZE 16

**Comment by boubouexpress** [comment] 2019-12-07 13:55
hello
WHAT VALUE I MUST MASTER

thank you

**Comment by AnHardt** [comment] 2019-12-07 15:36
It's not one of them. It's the combination.
All of them, plus '#define DELTA_SEGMENTS_PER_SECOND 200' contribute.

\#define XYZ_MICROSTEPS 128 keps the processor busy with stepping - having less time for the planner.
\#define MIN_STEPS_PER_SEGMENT 1 allows very short segments and many of them. Each needing its time to plan.
\#define DELTA_SEGMENTS_PER_SECOND 200 allows more and shorter segments than usual. (each only lasting 1/200 second)
\#define BLOCK_BUFFER_SIZE 16 is very short for the above combination. The display updates only when there is enough time in the buffer, so buffer is not running dry during the update..

**Comment by boubouexpress** [comment] 2019-12-07 16:37
I modify
#define XYZ_MICROSTEPS 32
#define DELTA_SEGMENTS_PER_SECOND 160
#define BLOCK_BUFFER_SIZE 32
#define MIN_STEPS_PER_SEGMENT 1


still more to do a try

**Comment by boubouexpress** [comment] 2019-12-07 20:14
hello
a big thank you it works perfectly

**Closed as completed** 2019-12-07 20:14 UTC
