### ISSUE TITLE
[BUG] (moving stepper motor like a Galvo Scanner?)

### ISSUE THREAD

**Issue by ghost** [MarlinFirmware/Marlin#22702] opened 2021-09-03 05:23 UTC
### Did you test the latest `bugfix-2.0.x` code?

No, but I will test it now!

### Bug Description

Hi
Currently I have Mega 2560 and Ramps 1.4, LCD 12864
How can I program Marlin to operate a stepper motor for 2 moving XY axes like a Galvo Scanner?
Can anyone answer and help me implement this idea on Marlin
![103466945-aa5d1b00-4d6b-11eb-832c-41119fbfe463](https://user-images.githubusercontent.com/32037463/131954451-bdf10046-2771-49dc-8a4c-1e17e275cca6.jpg)

### Bug Timeline

Unchecked

### Expected behavior

wish to control it like galvo

### Actual behavior

Unchecked

### Version of Marlin Firmware

LCD 12864

### Printer model

Laser

### Electronics

Mega 2560, Ramps

### Your Slicer

Cura

### Host Software

SD Card (headless)

**Comment by ellensp** [comment] 2021-09-03 05:28
Duplicate of https://github.com/MarlinFirmware/Marlin/issues/22693

**Closed as completed by ellensp** 2021-09-03 05:28 UTC
