### ISSUE TITLE
Skr mini v2 power loss feature do not work

### ISSUE THREAD

**Issue by Burockk** [MarlinFirmware/Marlin#22780] opened 2021-09-15 17:03 UTC
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

Power Loss feature do not work.

I defined   #define POWER_LOSS_RECOVERY
and tried 
    #define POWER_LOSS_PIN         -1
or 
   //#define POWER_LOSS_PIN         -1
but did not work

### Bug Timeline

I updated to bugfix 

### Expected behavior

Expect to resume button to resume the print

### Actual behavior

Printer starts and there is no resume button

### Steps to Reproduce

I start a print
after a few layer I pause the print
then I turn off the printer
and I turn on the printer
I expect a resume button but no there is not

### Version of Marlin Firmware

bugfix 2.0.x

### Printer model

ender 3 pro

### Electronics

BL touch - skr mini v2

### Additional information & file uploads

[Configuration.txt](https://github.com/MarlinFirmware/Marlin/files/7172023/Configuration.txt)
[Configuration_adv.txt](https://github.com/MarlinFirmware/Marlin/files/7172025/Configuration_adv.txt)

**Comment by thisiskeithb** [comment] 2021-09-15 18:10
Duplicate of https://github.com/MarlinFirmware/Marlin/issues/22341

**Closed as completed by thisiskeithb** 2021-09-15 18:10 UTC
