### ISSUE TITLE
Layer shifting

### ISSUE THREAD

**Issue by Tamonir** [MarlinFirmware/Marlin#9487] opened 2018-02-05 08:50 UTC
Hi everybody,

- Description: 
i recently switched my MKS-Base 1.4 (TEVO Tarantula) for a MKS GEN L 1.0 with FYSETC TMC2130 on all axes/E0/E1. With MKS Base, everything worked fine, even on Long Printjobs - perfectly aligned, no steplosses - of course, I did't change any mechanics when changing the board.
Yesterday, I did the final calibration (steps/mm) and printed the first 20*20*20 test cube. As you can see in the Picture attached, I got "some" issues on my y-Axis while the X-Axis is perfectly fine (20.01 mm). Z-Height of cube is 18.5 mm I will look for that later).

![img-20180204-wa0004](https://user-images.githubusercontent.com/35893932/35794974-9fd50312-0a4f-11e8-9568-88cbfcc2f188.jpeg)

Do you have any idea on what may cause the y-issues? In Detail, you can say that the whole layers are shifted so the shift is caused at the beginning of a layer. Within one layer, y-axis perfectly fits to the (shifted) Position. Shouldn't TMC2130 recognise the missmovement and compensate?

- Actual behaviour:
Whole Layers get shifted at the beginning of a layer

- Desired behaviour:
No shift :)

- Steps to reproduce:
  - MKS Gen L 1.0
  - all axes TMC 2130 (so far properly working)
  - Marlin Tarantula (1.1.8 with quick setup from here ( https://github.com/JimBrown/MarlinTarantula )
  - My current config:
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/1692639/Configuration.zip)
  - Test Cube sliced by simplify 3d with standard-Speed Settings (60 mm/s printing and 130 mm/s travel Speed ? I am not on the machine right now)

Thanks in advance

Tamonir

**Comment by Athemis** [comment] 2018-02-05 13:37
I saw something similar on my delta when I switched to TMC2130. My guess was that the driver current was too low, hence leading to skipped steps. After I increased the current, the problem went away.

**Comment by Tamonir** [comment] 2018-02-05 15:50
Hi Athemis,

thanks for your idea, I will test it today But as i dont have any step losses during the print of a layer, it cannot be a general step loss. I just talked to a colleague of mine who had the idea, that the accelleration (and thus deceleration) might be too strong to handle. This might also be related to the low current but drivers are allready getting very hot with 0.8 A. 

As this happens only when starting a new layer, the shift might be related to the high y-travel speed and hence strong accelleration. As accelleration (a) is proportional to Force (f) and force F is related to Current, I will try to decrease accelleration (which will in this case mean the same as setting a higher current). 

I will report back soon and I am open for further ideas :)

Regards

Tamonir

**Comment by ikarisan** [comment] 2018-02-05 19:36
@Tamonir I have similar problems. For me everything is working fine with 750mA... as long as the printer uses StealthShop. But when using StealthShop together with hybrid threshold (100mm/s) the layers are shifting on larger object. If I use spreadCycle instead of StealthShop the layers are not shifting.

**Comment by Tamonir** [comment] 2018-02-06 07:42
Hi everybody,

@ikarisan: Nice thought, I will try to disable hybrid mode and see what happens. Allready thought about that but forgot :)

For now, i lowered "a max X" and "a max Y" from 3000 (Standard) to 500 and that allready gave me huge improvements as you can see in the picture. Have some widening at the edges though but this might be related to the begins/ends of Extrusion which are distributed over all edges. With that low accelleration, the drives wont reach 100 mm/s so they arent changing to spreadcycle. 

![img-20180205-wa0006](https://user-images.githubusercontent.com/35893932/35847114-2b865e76-0b11-11e8-8f31-3b82ede25e62.jpeg)

I will do some further tests with old accelleration and forced stealth chop

@ikarisan: how fast can you go at 750 mA and what are your accelleration and jerk settings?

Best regards

Tamonir

**Comment by ikarisan** [comment] 2018-02-06 19:12
My values are set to:

#define DEFAULT_MAX_ACCELERATION      { 1000, 1000, 100, 10000 }
#define DEFAULT_ACCELERATION          400     // X, Y, Z and E acceleration for printing moves
#define DEFAULT_RETRACT_ACCELERATION  1000    // E acceleration for retracts
#define DEFAULT_TRAVEL_ACCELERATION   1000    // X, Y, Z acceleration for travel (non printing) moves
#define DEFAULT_XJERK                 10.0
#define DEFAULT_YJERK                 10.0
#define DEFAULT_ZJERK                  0.3

But I can see that you have the same "bleeding corner" problem as I have... :( 
https://github.com/MarlinFirmware/Marlin/issues/9494

**Comment by floyd871** [comment] 2018-02-11 17:14
I can confirm this Issue, but only the Y-Axis is affected. Increasing the current to 1000 does not help. Decreasing the acceleration seems to help.
(I3 Clone with Ramps 1.4)

**Comment by Roxy-3D** [comment] 2018-02-11 17:27
It would be helpful if you checked the .gcode file to make sure everything is reasonable and there is no shifting.    Can you feed the .gcode file into:  http://gcode.ws/# and check that it's layers don't shift?

**Comment by floyd871** [comment] 2018-02-11 17:43
Just check it the gcode with http://gcode.ws/#, all fine

**Comment by Roxy-3D** [comment] 2018-02-11 17:44
OK...   That helps isolate the problem to the machine.   Does it shift the same way if you print multiple times?   I'm wondering if the stepper motors are losing steps????

**Comment by floyd871** [comment] 2018-02-11 17:55
Yes, the shift is always the same way Y-Axis increases, never decreases. 
When i increase the current the shifting is less, but overheating warnings in the console. Decreasing the acceleration to 1000 (from 3000) help. Shifting ist gone.

**Comment by Tamonir** [comment] 2018-02-11 17:58
@ikarisan: Thanks, I will try these higher amounts soon, I am now going with 500 accelleration and its perfect (despite the bleeding corners). I had some issues though (horizontal artifacts) which were caused by some layers beeing thicker than the others. This was caused by inconsistant z move (I am using 2 z steppers). I set the current for z to 1200 (isnt moving that much...) and now it works like a charm - despite bleeding corners.

**Comment by Roxy-3D** [comment] 2018-02-11 18:04
You also might want to try reducing your Max Feed Rates to 1/2 of their current values and see if that makes things better.   If it totally fixes the problem, you can start bumping the Feed Rates up until you start seeing the problem again.

**Comment by floyd871** [comment] 2018-02-11 18:08
And the Acceleration back to default 3000!?

**Comment by Roxy-3D** [comment] 2018-02-11 18:24
I wouldn't do that...    Even with a very low acceleration, the extruder gets up to speed pretty quickly.
(But that is me...   I don't care if a print takes 4 hours...  Or if it takes 4 hours and 10 minutes.  I care more that the print finishes and is correct.)

**Comment by floyd871** [comment] 2018-02-11 18:45
I think this is really a problem with the TMC2130. Left one 800mA (skipping Z-Axis) , Right 1000mA (No skipping)
![img_20180211_194221](https://user-images.githubusercontent.com/7797850/36076968-1eb2593c-0f64-11e8-8884-931460792a8b.jpg)
I thought Z axis is not so so problem with current, because of the reducers of the leadscrew..

**Comment by Tamonir** [comment] 2018-02-11 21:22
> I thought Z axis is not so so problem with current, because of the reducers of the leadscrew..

And maybe thats the reason Maybe the very short turning of the steppers leads to stalling. Yesterday, I changed the microstep settings of y and x from 16 to 32 - so the distance got devided by 2. What was remarkable was, that the sensorless homing triggered immediately when homing (which was calibrated well for 16 steps) - as sensorless homing is provided by motor current, maybe that the load vor minor changes causes the stepper to stall. Its only a guess...

@ floys: do you have two or one z stepper?

**Comment by floyd871** [comment] 2018-02-12 06:18
Good point, yes i am using standard Ramps with two motors on one driver on the z-axis. 
So the default setting to 800mA for z-axis might not be enough....

**Comment by Lyr3x** [comment] 2018-03-29 15:16
I'm running my Z axis @700mA  without any shifting problems (nearly the same acceleration, jerk and feedrate). Do you use stealthchop or spreadcycle?

You need fairly high currents with the TMC2130 in stealthchop mode to prevent skipping steps

**Comment by boelle** [comment] 2019-02-20 01:02
@Tamonir Please post your question either on discord: https://discord.gg/n5NJ59y or on facebook: https://www.facebook.com/groups/2080308602206119/
The issue list is for bugs and feature requests only
Please close this issue once you have posted it on one of the 2 links
Thanks :-D

**Comment by boelle** [comment] 2019-03-06 11:21
@thinkyhead i think we can close this one

**Closed as completed** 2019-03-07 06:23 UTC
