### ISSUE TITLE
[BUG] "Motion -> Bed Leveling -> Level Corners" crashes after "Homing XYZ"

### ISSUE THREAD

**Issue by sustmi** [MarlinFirmware/Marlin#15789] opened 2019-11-03 17:25 UTC
### Description
After merging PR https://github.com/MarlinFirmware/Marlin/pull/15760, the _Motion_ -> _Bed Leveling_ -> _Level Corners_ menu function hangs the printer (and causes E stepper to whistle) after _Homing XYZ_ step finishes.

The screen shows :
```
Next Point?
Homing XYZ

Done     **Next**
```

I did a `git bisect` and when using the previous commit (before merge of this PR) leveling works alright.

### Steps to Reproduce
1. Turn on the printer
2. Enter menu and go to _Motion_ -> _Bed Leveling_
3. Select _Level Corners_
4. Wait for Homing XYZ to finish

**Expected behavior:** Printer head should then move to the first leveling point.

**Actual behavior:** Printer head only moves up a bit, the menu is partially redrawn (still showing "Homing XYZ"), printer control wheel/button is unresponsive, E stepper starts to whistle and the only thing I can do is turn off the printer.

#### Additional Information
- Here are my `Configuration.h` and `Configuration_adv.h` in a ZIP file: [config-files.zip](https://github.com/MarlinFirmware/Marlin/files/3802088/config-files.zip)
- Here is my `platformio.ini` file: [platformio.zip](https://github.com/MarlinFirmware/Marlin/files/3804996/platformio.zip) (`default_envs = STM32F103RC_bigtree`)

- My printer is Creality Ender 3 with [BigThreeTech SKR E3 DIP v1.0 board](https://github.com/bigtreetech/BIGTREETECH-SKR-E3-DIP-V1.0).

**Comment by sustmi** [comment] 2019-11-03 17:33
@thinkyhead: I tried to look at [your changes](https://github.com/MarlinFirmware/Marlin/pull/15760/files) and see where the problem is but the diff is too big for me to fully understand it.

The only difference I noticed that may be relevant is that `_lcd_level_bed_corners_homing()` used to call [`ui.goto_screen(menu_level_bed_corners);`](https://github.com/MarlinFirmware/Marlin/pull/15760/files#diff-f126349326f3f91ef5f520de974498e0L111) and now it contains directly the function body of `menu_level_bed_corners()`. But I do not understand the menu code enough to know whether it's the cause of this problem or not.

**Comment by boelle** [comment] 2019-11-03 19:10
will temp close this one until the information in issue template has been added

**Comment by sustmi** [comment] 2019-11-03 20:23
@boelle: Do you mean `Configuration.h` and `Configuration_adv.h` files? Or a video?
Which of these information are mandatory and which are optional?

**Comment by boelle** [comment] 2019-11-03 20:26
yes  `Configuration.h` and `Configuration_adv.h` are mandatory

**Comment by sustmi** [comment] 2019-11-03 20:29
Thanks :+1: . I updated the issue and added a ZIP with those files.

**Comment by Spartacus1066** [comment] 2019-11-03 22:42
I logged in to report the SAME issue, Tevo Tornado here. Never had this happen... 
Printer resets if using Level Corners option, does fine if I disable steppers and do it maually. Mesh leveling also worked. Thanks!

[Tevo_Tornado_config_Spartacus.zip](https://github.com/MarlinFirmware/Marlin/files/3802236/Tevo_Tornado_config_Spartacus.zip)

**Comment by Evg33** [comment] 2019-11-04 22:23
SKR 1.3
https://youtu.be/V6w1NU9C0sk

**Comment by Evg33** [comment] 2019-11-05 20:33
https://github.com/MarlinFirmware/Marlin/pull/15808
Compilation: ok
Working: fail

**Comment by manimac79** [comment] 2019-11-06 20:15
Same issue here, SKR E3 mini 1.2

**Comment by willy059** [comment] 2019-11-06 21:03
Same issue, Geeetech A10.

**Comment by shitcreek** [comment] 2019-11-07 08:23
This is now fixed with this commit: https://github.com/MarlinFirmware/Marlin/commit/84ce3a6bea0d12815261ef7fa40bd2c08f2a5573

**Comment by Evg33** [comment] 2019-11-07 20:28
The problem is solved !
It works!
Thank you !

**Comment by boelle** [comment] 2019-11-11 13:29
will close this as fixed

**Closed as completed by boelle** 2019-11-11 13:29 UTC
