### ISSUE TITLE
[BUG] M85 (kill if inactive) will kick in even when printer is awaiting user input due to filament runout.

### ISSUE THREAD

**Issue by AndKe** [MarlinFirmware/Marlin#15339] opened 2019-09-22 20:30 UTC
### Description

M85 (kill if inactive) will kick in even when printer is awaiting user input due to filament runout.

### Steps to Reproduce

configure M85 for kill after some inactive time 
run out of filament (trigger sensor)

**Expected behavior:** [What you expect to happen]
I would expect kill timer to be paused during wait for user input.

**Actual behavior:** [What actually happens]
kill timer runs out, job terminated.  

#### Additional Information
this is on 2.0-bugfix

**Comment by boelle** [comment] 2019-09-23 07:27
please attach your 2 config files, just as the issue template told you to

**Comment by AndKe** [comment] 2019-09-23 07:44
attached :)

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/3641085/Configuration.zip)

**Comment by shitcreek** [comment] 2019-10-15 18:40
M85 is functioning as it is intended. [M85](http://marlinfw.org/docs/gcode/M085.html)
Having the machine wait **indefinitely** for user input would defeat its purpose. It should be set to how long you are willing to have the machine running unattended.

Perhaps as a feature request, maybe an extra parameter could be added to have it pause the inactivity timer while there is a prompt for user input, or specifically have filament runout routine to pause the timer.

**Comment by AndKe** [comment] 2019-10-15 18:48
yes, there should be a acceptable wait time, especially for printing on beds that will release the part if allowed to cool down.

**Comment by InsanityAutomation** [comment] 2019-10-15 19:00
> 
 or specifically have filament runout routine to pause the timer.


Stepper timeout actually has a defer for filament runout explicitly, at least it did last I looked at it. I was planning to add one for the babystepping display at some point as well.

To function, you need both 
#if BOTH(ADVANCED_PAUSE_FEATURE, PAUSE_PARK_NO_STEPPER_TIMEOUT) in configuration_adv

Note pause.cpp is the only place idle(true); is used instead of just idle which sets the timeout defer.

**Comment by boelle** [comment] 2019-10-16 12:48
so the best action to take would be to close this one and open an [FR] instead?

**Comment by InsanityAutomation** [comment] 2019-10-16 14:29
@boelle the config doesnt seem to have an issue, so it would be a bug if this is occurring. The question is if the lack of park on pause is causing an incompatibility. Ill test it in that uncommon but in theory valid combination when I can.

**Comment by boelle** [comment] 2019-11-03 14:14
@InsanityAutomation did you have spare time to test this one?

**Comment by boelle** [comment] 2019-11-16 10:24
@InsanityAutomation did you have spare time to test this one?

**Comment by boelle** [comment] 2019-12-10 00:04
will close this one as M85 works as intended, if we need to change the way it works a FR would be in order just like @shitcreek said

**Closed as completed by boelle** 2019-12-10 00:04 UTC

**Comment by shitcreek** [comment] 2019-12-10 00:07
I tested the latest build with `ADVANCED_PAUSE_FEATURE` and `PAUSE_PARK_NO_STEPPER_TIMEOUT` enabled and set kill if inactive to 60 seconds (M85 S60), start a print without filament, and watched the clock. 60 seconds after the extruder heater is shut off, the screen goes blank and the heated bed shuts off.
We should expect the printer halted message at the very least.
