### ISSUE TITLE
[BUG] MSG_SD_ERR_READ is not define - SDSUPPORT (Marlin 2.0.4.4)

### ISSUE THREAD

**Issue by josephted** [MarlinFirmware/Marlin#16998] opened 2020-02-27 02:25 UTC
### My Configurations

Arduino IDE 1.8.10

### Steps to Reproduce

1. Enable SDSUPPORT in file "Configuration.h"
2. Compile end error

**Actual behavior:**
File "\src\gcode\queue.cpp" in line 530 contain:
"if (n < 0 && !card_eof) { SERIAL_ERROR_MSG(**MSG_SD_ERR_READ**); continue; }"

Variable "**MSG_SD_ERR_READ**" _not exists in all files marlin firmware_.

The correct variable would be "STR_SD_ERR_READ" according to the pattern of the variables in the file "\src\core\language.h".

MSG_SD_ERR_READ not exists in the file "\src\core\language.h".

_The error is corrected if you replace the MSG_SD_ERR_READ variable (file "\src\gcode\queue.cpp") with "STR_SD_ERR_READ"_

**Comment by GMagician** [comment] 2020-02-27 10:18
Already fixed in bugfix, please read #16992, duplicate of  #16990

**Closed as completed** 2020-06-20 21:13 UTC
