### ISSUE TITLE
[BUG] Babystepping frozes Color UI

### ISSUE THREAD

**Issue by ils15** [MarlinFirmware/Marlin#19379] opened 2020-09-13 16:03 UTC
When i use babystepping, color UI frozen and  temperature goes crazy

steps to reproduce error

Put something to print
activate babysteping

Motherboard: Mks Robin Nano V1.2

https://github.com/ils15/BlueR/tree/master/Marlin

**Comment by sjasonsmith** [comment] 2020-09-13 16:13
You need to disable `BABYSTEP_DISPLAY_TOTAL`. A check went in recently to cause a build error if that is enabled, since it is not supported with this UI yet.

**Comment by sjasonsmith** [comment] 2020-09-13 16:13
Duplicate of #19233

**Closed as completed by sjasonsmith** 2020-09-13 16:13 UTC
