### ISSUE TITLE
[BUG] Waves when printing (LPC1768)

### ISSUE THREAD

**Issue by dark184** [MarlinFirmware/Marlin#16218] opened 2019-12-14 12:03 UTC
### Bug Description
I apologize in advance for my English, it is not my native language.

Configured Marlin firmware 2.0.x for LPC1768 processor, compiled and flashed. Boards MKS sBase (DRV8825 with microstep 1/32), BigTreeTech SKR v1.3 (DRV8825 with microstep 1/32) and many others. On both boards, printing occurs in waves, as in the photo. On all photos on the left-the seal with firmware Marlin 2.0.x, on the right-Smoothieware. Cost to flash again Smoothieware, the printer once again prints perfectly.
To build the firmware, Platformio was used, with a choice in the file "Platformio.ini " LPC1768.
Both of these boards work correctly with Marlin 2.0.x firmware, with the exception of print defects.
All printouts are made exclusively on the same printer.

### My Configurations

[MarlinConfig.zip](https://github.com/MarlinFirmware/Marlin/files/3963726/MarlinConfig.zip)

### Steps to Reproduce

1. Configure the Marlin firmware 2.0.x for LPC1768 processor
2. Select in the file Configuration.h "MKS sBase" motherboard or customize for "BigTreeTech SKR V1.3" motherboard.
3. Compile firmware and flash the printer motherboard.
4. Run "Autotune" for Hotend pid controllers and heating bed. Enter the received values into the firmware, compile and flash the motherboard again.
5. Make a trial print.

**Expected behavior:** After the test printing was expecting a straight vertical wall on the model.
![Expected behavior](https://user-images.githubusercontent.com/58841226/70848403-eb913d00-1e81-11ea-82c2-95d2780cc651.jpg)

**Actual behavior:** The outer walls of the model are completely in horizontal waves. This defect is manifested exclusively with the firmware Marlin. On smoothieware firmware, the walls of the model are perfectly straight.
![Actual behavior](https://user-images.githubusercontent.com/58841226/70848407-f2b84b00-1e81-11ea-9a9d-110ee2da1c8d.jpg)

additional photo
![IMG_20190417_075434 (2)](https://user-images.githubusercontent.com/58841226/70848349-48d8be80-1e81-11ea-9944-79a33c94274c.jpg)
![P1120724](https://user-images.githubusercontent.com/58841226/70848350-48d8be80-1e81-11ea-9592-108a471c0bde.JPG)
![P1120728](https://user-images.githubusercontent.com/58841226/70848351-48d8be80-1e81-11ea-89af-eb39bd775203.JPG)
![P1120727](https://user-images.githubusercontent.com/58841226/70848352-48d8be80-1e81-11ea-9c22-cb875b78ff42.JPG)
![P1120726](https://user-images.githubusercontent.com/58841226/70848353-49715500-1e81-11ea-890a-ed42eded962d.JPG)
![P1120725](https://user-images.githubusercontent.com/58841226/70848354-49715500-1e81-11ea-9a30-ae62ce56ac1f.JPG)
![P1120721](https://user-images.githubusercontent.com/58841226/70848355-49715500-1e81-11ea-866f-bee0c2a2a4fe.JPG)

My smoothieware config for MKS sBase v1.3
[config.zip](https://github.com/MarlinFirmware/Marlin/files/3963901/config.zip)

#### Additional Information

* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.

**Comment by ellensp** [comment] 2019-12-14 14:06
Can you attach your smoothieware config, so we can also test this.

**Comment by dark184** [comment] 2019-12-14 14:14
One moment
My smoothieware config for MKS sBase v1.3
[config.zip](https://github.com/MarlinFirmware/Marlin/files/3963901/config.zip)

Additionally made in the title of the topic

Only on my printer specific settings of kinematics, it should be borne in mind.
Both firmware are configured exactly for my kinematics.
By the way, forgot to write. I'm not the only one with this problem. At least two more people with BigTreeTech SKR v1.3 motherboards. I have now installed MKS sBase, but there is also SKR v1.3 with which the same problem.

**Comment by ellensp** [comment] 2019-12-14 14:34
was more thinking of running two virtual prints of the same gcode (minus heating instructions) one using marlin, the other smoothieware. No real stepper drivers or other hardware other than a lpc1768 based controller, so kinematics don't matter.  Just log the step and direction signals.  Sadly I don't own such a device, but someone here must who is keen to get to the bottom of this....

**Comment by dark184** [comment] 2019-12-14 14:43
I can not 100% say that the problem is in the firmware. But in my opinion the problem lies precisely in the instability (or phase) of the "step" signal.

**Comment by thisiskeithb** [comment] 2019-12-14 17:23
Can you attach your Smoothieware config for the SKR 1.3 setup as well?

**Comment by sjasonsmith** [comment] 2019-12-14 17:26
This is almost certainly the issue with inaccurate step pulse times. I don’t have the existing issue number or my open PR number handy.

If you find my PR that is open you could try that, or you can set MINIMUM_STEPPER_PULSE to 3, in Configuration_adv.h.

**Comment by dark184** [comment] 2019-12-15 10:26
**sjasonsmith** thank you very much, you hit exactly the target. Increased MINIMUM_STEPPER_PULSE at once to 4 that for certain, the printing more or less normalized. It remains to calibrate the temperature of the hotend. There were printing defects, including barely noticeable shifts of layers, but everything else is 100% not related to the firmware.
Can you tell me where I can follow the progress of fixing this bug? For me, this bug is very critical, since I only use DRV8825. To date, we have to use only Smoothieware. And this firmware has many disadvantages.

**Comment by sjasonsmith** [comment] 2019-12-17 07:46
This is a duplicate of issue #11047.  @dark184, you should continue to track the issue from there.

**Comment by axl12ap** [comment] 2019-12-17 09:05
I also have the same problem reported in the initial message, yesterday I printed the superman torso with layer height 0.1mm and stopped when I saw the horizontal bands.

My current configuration is as follows:
- CoreXY kinematics with SKR 1.3 board
- TMC2208 connected in UART, stealthchop mode (also extruders)
- Marlin 2.0.X ver. 06/28/2019
- Fysetc Mini12864 display

Attacched my configurations header files, anyone can help me please? Shall I try to change the MINIMUM_STEPPER_PULSE manually?? Or something else??

[Config.zip](https://github.com/MarlinFirmware/Marlin/files/3972343/Config.zip)

![photo_2019-12-17_09-58-54](https://user-images.githubusercontent.com/31867260/70980788-24185d00-20b4-11ea-9da1-fa119cf4bd08.jpg)
![photo_2019-12-17_09-58-49](https://user-images.githubusercontent.com/31867260/70980797-27134d80-20b4-11ea-9d76-f5102577385e.jpg)
![photo_2019-12-17_09-58-37](https://user-images.githubusercontent.com/31867260/70980800-28dd1100-20b4-11ea-9d8b-89eb226d4c87.jpg)

**Comment by dark184** [comment] 2019-12-17 09:19
In my opinion this is an unstable Hotend temperature. Calibrate the hotend pid controller.

**Comment by axl12ap** [comment] 2019-12-17 09:22
> In my opinion this is an unstable Hotend temperature. Calibrate the hotend pid controller.

Just checked the hotend temperature, seem to be very stable (+-0,5°C max deviation as the bed)

In the next few hours (during my lunch) I'll try to calibrate the hotend and extruder with PID autotune, then I'll retry to print the base for checking 

BTW, any suggested change to the stepper defines (MINIMUM_STEPPER_DIR_DELAY, MINIMUM_STEPPER_PULSE, MAXIMUM_STEPPER_RATE) related to the TMC2208?

Thanks

**Comment by ellensp** [comment] 2019-12-17 09:27
@axl12ap your issue is not related...  your corners are not wavy!

**Comment by sjasonsmith** [comment] 2019-12-20 08:02
@boelle, could you close this as a duplicate of #11047?

PR #16128 has been merged into bugfix-2.0.x, which should fix the issue anyway.

**Comment by boelle** [comment] 2019-12-20 11:19
dublicate of  #11047 and fixed by pr #16128

**Comment by boelle** [comment] 2019-12-20 11:19
should #11047 also be closed?

**Closed as completed by boelle** 2019-12-20 11:19 UTC
