### ISSUE TITLE
[BUG] TMC5161 cant enable  debug option 

### ISSUE THREAD

**Issue by labotecno** [MarlinFirmware/Marlin#15001] opened 2019-08-19 20:17 UTC
hello i buy recently the new TMC5161 , i get it working with spi , but i cant get it working with debug option , 
i cant get M122 state 
plesase can you help me with this issue !

**Comment by boelle** [comment] 2019-08-19 22:37
-RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
-[Tom's 3D Forums](https://forum.toms3d.org/)
-Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
-Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
-[Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
-Marlin Discord server. Join link: https://discord.gg/n5NJ59y

**Comment by boelle** [comment] 2019-09-24 15:34
closing as this is not a bug

**Closed as completed by boelle** 2019-09-24 15:34 UTC
