### ISSUE TITLE
UBL bug, printer tries to lift the Z axis to the sky

### ISSUE THREAD

**Issue by egarrido-dev** [MarlinFirmware/Marlin#9147] opened 2018-01-11 12:14 UTC
### Bug Report
- Description: During printing, the printer suddenly starts lifting the Z-axis above the maximum limit. Helps only power down. Several tests have shown that this happens when the print is outside the measured mesh.
- Steps i do:
Measuring: M502 - M500 - M501 - G29 P1 T - G29 S
Printing: G28 - G29 A - G29 L0 - G29 J, then print... Next, everything is fine, until the print does not go beyond the grid of measurements.

[Configurations.zip](https://github.com/MarlinFirmware/Marlin/files/1622444/Marlin.zip)

**Comment by Roxy-3D** [comment] 2018-01-11 16:00
Can you increase the size of your mesh slightly?   The mesh should cover the entire area you are going to use to print.    With that said...   I am working to make it behave better when the nozzle moves off the mesh.

**Comment by egarrido-dev** [comment] 2018-01-12 08:27
> Can you increase the size of your mesh slightly?

In the axis settings, I indicated the maximum print area, as well as added MESH_INSET 10, so that the nozzle does not touch the clothespins that hold the glass.
I'm not against increasing the mesh and aligning the inaccessible points manually, but the printer does not give me such a possibility - the points are placed with the indentation of the sensor and MESH_INSET.

Update: Now I decrease MESH_INSET to 0, and the manual tests show that everything is fine. I'll try to start printing. Do I understand that MESH_INSET actually limit the print area?

**Comment by stoto** [comment] 2018-01-12 12:33
I might be having the same issue. I updated to 1.1.8 today and re-made my UBL mesh. The first thing i noticed there was no option to manually set the values for the parts where the probe can't reach (left side of the bed 38mm wide for me).

I started the G26 to verify my mesh, it totally skipped the left 38mm and started printing the patter on the rest part of the bed, however before finishing my bed started to go down (corexy), hit the bottom where i had to turn off the whole thing before anything breaks.

I pressed reset, homed, loaded mesh and tried G26 again. Printing pattern started, but after like 4-5 circles the bed started going down again. I didn't wait until it hits the bottom now, i pressed reset.

I thought it was an issue with G26, but know i am worried if it's an issue while printing as well.

**Comment by egarrido-dev** [comment] 2018-01-12 13:45
> The first thing i noticed there was no option to manually set the values for the parts where the probe can't reach...

Similarly, only with an indentation of 27mm along the X-axis and 4mm along the I-axis.
> it totally skipped the left 38mm ... however before finishing my bed started to go down

Yes, the first time the mesh was checked, the printer also suddenly started lifting the Z axis, but I thought it was a bug.
> I pressed reset, homed, loaded mesh and tried G26 again.

Today, with the new tests, it was not only raised along the Z axis, but also lowering. Only additional strengthening of the bed saved the printer from damage.

> I thought it was an issue with G26

No, the error occurs when moving with the activated UBL by command G1. I think that G0 will also cause this error.
When MESH_INSET is turned off, mesh checking and printing in areas that have not been probed, occurs without errors. So I think the problem is in MESH_INSET.

Sorry for my bad english :)

**Comment by kAdonis** [comment] 2018-01-12 18:19
I had a similar Problem
it might be Issue #8723 there is a Workaround described
uncommenting some lines in  Configuration_adv.h worked for me

**Comment by Roxy-3D** [comment] 2018-01-12 19:58
> Do I understand that MESH_INSET actually limit the print area?

Yes.   The specified number of mesh points will be distributed closer within the available area of the bed.

> I might be having the same issue. I updated to 1.1.8 today and re-made my UBL mesh. The first thing i noticed there was no option to manually set the values for the parts where the probe can't reach (left side of the bed 38mm wide for me).

You can edit them to what ever value you want.   Either G29 P4 or M421.    But most likely you want to do G29 P3 several times to invoke the 'Smart Fill'.    The values filled in will probably be 'reasonable' but you still want to do a G26 a G29 P4 R edit cycle.

**Comment by egarrido-dev** [comment] 2018-01-17 08:58
I have new bug :(
When my printer moving top right corner of a bed, hotend touches bed by about 4 mm.
`G1 X190 Y160` - prepare position
`G1 X190 Y180` - moving
While moving from `Y160` to `Y180`, Z-axis moves down by about 4 mm near `Y170` and restore position at end. But when moving back to `Y160`, Z-axis correctly change height, without touching bed.

```
Bed Topography Report:
(0,9)                                                                   (9,9)
(27,180)                                                                (190,180)
  0.080    0.043   -0.022   -0.088   -0.132   -0.186   -0.247   -0.280   -0.339   -0.387
  0.134    0.073    0.023   -0.034   -0.065   -0.118   -0.172   -0.200  [-0.239]  -0.298
  0.136    0.093    0.047   -0.008   -0.036   -0.075   -0.099   -0.123   -0.156   -0.237
  0.128    0.089    0.048    0.017   -0.001   -0.028   -0.069   -0.077   -0.112   -0.170
  0.124    0.108    0.062    0.040    0.028    0.010   -0.014   -0.008   -0.045   -0.117
  0.130    0.112    0.069    0.042    0.045    0.038    0.040    0.027   -0.002   -0.051
  0.152    0.123    0.096    0.072    0.091    0.073    0.061    0.069    0.043    0.011
  0.135    0.136    0.125    0.103    0.117    0.104    0.103    0.111    0.105    0.070
  0.133    0.145    0.131    0.125    0.128    0.138    0.125    0.139    0.129    0.094
  0.153    0.153    0.147    0.152    0.167    0.157    0.153    0.166    0.161    0.153
(27,4)                                                                    (190,4)
(0,0)                                                                     (9,0)
```

**Comment by chambm** [comment] 2018-02-02 19:27
Why does 
`MESH_INSET 10              // Mesh inset margin on print area`
default to 10 if it's supposed to cover the entire print area? I'm seeing the same 'reach for the sky' behavior and it's rather surprising (and then frustrating because you have to do an emergency stop). How come more people aren't getting this? Do you have an idea of how many people are using UBL?

**Comment by thinkyhead** [comment] 2018-02-17 00:43
Presumably this has been patched with c8d3069.

Please test with the latest `bugfix-1.1.x` (and/or `bugfix-2.0.x`) branch to see where it stands. If the problem has been resolved then we can close this issue. If you still see the bad behavior we should investigate further.

**Comment by seandop** [comment] 2018-03-11 23:17
I had this issue on 1.1.8, and it drove me crazy. I can confirm that the bugfix-1.1.x branch does fix the problem for me!

**Comment by Roxy-3D** [comment] 2018-03-11 23:25
> Presumably this has been patched with c8d3069.

Yes...  But there may still be a little more work to do.  Studiodyne suggested it would be better to not raise an addition 2.5mm (by default).   He thought it would be better to raise to 2.5mm if the Z height was below that amount.   And do nothing if the Z height is already above that value.

> I had this issue on 1.1.8, and it drove me crazy. I can confirm that the bugfix-1.1.x branch does fix the problem for me!

Thank you for the confirmation!

**Comment by evertonramires** [comment] 2018-03-20 14:16
Hey guys, can anyone please quote the lines that really fix it (or at least a workaround? I can't start a new firmware based on bugfix since I already have a 1.1.8 fully configured.
Hope I'm not asking for too much.

**Comment by Roxy-3D** [comment] 2018-03-20 15:31
The Z-Raise when you go off the mesh is multiple lines of code in several places.   Mostly in the UBL.H file.   

You can do a Visual diff between your fully configured  Configuration.h files and the current file set.   That is an easy and quick (and accurate) way to get your settings to the current file set.

**Comment by thinkyhead** [comment] 2018-03-21 09:04
> Hope I'm not asking for too much.

Far, far easier for you to update your configs for `bugfix-1.1.x` than to modify 1.1.8.

**Comment by boelle** [comment] 2019-02-20 00:09
i agree with @thinkyhead on this one

so either update to latest bugfix 2.0 or figure out on your own how to mod 1.1.8

i dont even think 1.1.8 is supported anymore

**Comment by boelle** [comment] 2019-03-06 11:05
@thinkyhead i think we can close this one

**Comment by Phr3d13** [comment] 2019-06-10 21:59
@thinkyhead Another one that needs to be closed. Sorry, I got bored.

**Comment by boelle** [comment] 2019-06-22 09:23
@thinkyhead Another one that needs to be closed. Sorry, I got bored.

**Closed as completed** 2019-07-06 04:11 UTC
