### ISSUE TITLE
Bilinear leveling not working

### ISSUE THREAD

**Issue by ghost** [MarlinFirmware/Marlin#17361] opened 2020-04-01 03:08 UTC
I'm using the latest version of Marlin bugfix-2.0

I have #define AUTO_BED_LEVELING_BILINEAR and #define RESTORE_LEVELING_AFTER_G28 enabled in Configuration.h

I have M421 S1 in my Gcode, right after G28.

I leveled the bed countless times, saving with M500 after each leveling and checking with M420 V and M420 to see if its enabled.

The nozzle hits the prints every single time. I also noticed that every time I level the bed, I have to set different values. Example, point 8 of 25 was previously +0.210 and the second time around I need to set something like -0.060. Third time will be a whole different value, and so on.

Am I missing something?

**Comment by thinkyhead** [comment] 2020-04-05 01:48
I have to close this because it's a duplicate of other issues in which the submitters included data and it doesn't contribute to the solution we are already working on.

**Closed as completed by thinkyhead** 2020-04-05 01:48 UTC
