### ISSUE TITLE
[BUG] G28 Y does not work with CoreXY and sensorless homing

### ISSUE THREAD

**Issue by Minims** [MarlinFirmware/Marlin#18391] opened 2020-06-23 19:30 UTC
### Bug Description

G28 Y does not work with CoreXY and sensorless homing
G28 X is OK
G28 Z is OK

Manually move Y axis is OK.

### My Configurations

SKR Pro 1.1
Core XY
TMC2209
XY SensorLess Homing 

[CoreXY-SKR-Pro.zip](https://github.com/MarlinFirmware/Marlin/files/4821453/CoreXY-SKR-Pro.zip)
### Steps to Reproduce

1. G28 X, confirm it's OK
2. G28 Y, No move on Y

**Expected behavior:** [What you expect to happen]

G28 Y works, (Y goes to Y Min) 

**Actual behavior:** [What actually happens]

G28 Y not working, (Y does not move) 

#### Additional Information

Works on a SKR 1.4 Turbo, 2209, SensorLess Homing, but it's a Prusa, not a CoreXY.

**Comment by boelle** [comment] 2020-06-23 19:31
what version of marlin?

**Comment by Minims** [comment] 2020-06-23 19:33
Latest bugfix-2.0.x (compile 2 hours ago)
Here is debug info, if it helps : 

```
Connecting...
Printer is now online.
>>> M111 S38
SENDING:M111 S38
echo:DEBUG:INFO,ERRORS,LEVELING
>>> G28Y
SENDING:G28Y
>>> G28
Machine Type: CoreCartesian
Probe: FIX_MOUNTED_PROBE
Probe Offset X26.40 Y21.00 Z-1.35 (Right-Back & Below Nozzle)
Auto Bed Leveling: BILINEAR (disabled)
X current: 1000 -> 350
Y current: 1000 -> 350
Raise Z (before homing) to 40.00
>>> do_blocking_move_to X0.00 Y30.00 Z40.00
<<< do_blocking_move_to
>>> homeaxis(Y)
Home 1 Fast:
>>> do_homing_move(Y, -465.00, [50.00])
<<< do_homing_move(Y)
>>> set_axis_is_at_home(Y)
Axis 89 home_offset = 0.00 position_shift = 0.00
> home_offset[Y] = 0.00
  current_position= X0.00 Y0.00 Z40.00 :
<<< set_axis_is_at_home(Y)
  current_position= X0.00 Y0.00 Z40.00 : sync_plan_position
  current_position= X0.00 Y0.00 Z40.00 : > AFTER set_axis_is_at_home
<<< homeaxis(Y)
  current_position= X0.00 Y0.00 Z40.00 : sync_plan_position
Restore driver current...
<<< G28
```

**Comment by thinkyhead** [comment] 2020-06-23 22:36
Duplicate of #18212

**Closed as completed by thinkyhead** 2020-06-23 22:36 UTC
