### ISSUE TITLE
LCD control can't change nozzle, bed or fan under Tune menu

### ISSUE THREAD

**Issue by G-Forge** [MarlinFirmware/Marlin#3115] opened 2016-03-09 10:44 UTC
using RepRapDiscount FULL GRAPHIC Smart Controller with SD enabled 
1.1.0RC3
Using the LCD menu while printing Tune then selecting Nozzle, Bed or Fan speed they all show flow and value can't be changed.

**Comment by Blue-Marlin** [comment] 2016-03-09 11:15
Duplicate of #3042 #2944 #2934 #2930 #2905 #2884. Fixed in RCBugFix since 4 Dec 2015.

**Comment by G-Forge** [comment] 2016-03-09 11:32
Thanks, apologies for not seeing that earlier.

**Closed as completed** 2016-03-09 11:33 UTC
