### ISSUE TITLE
[BUG] (bug summary)ender neo max temp error at 298 degrees

### ISSUE THREAD

**Issue by Samiamjohnson1** [MarlinFirmware/Marlin#25799] opened 2023-05-09 17:00 UTC
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

I'm new. I have an ender 3 neo. I want to print CF nylon. I upgraded my head to creality spine. Downloaded and edited marlin 2.1.2 file to change max temp. The machine gets max temp error every time at 298 degrees

### Bug Timeline

New

### Expected behavior

I need to print stable at 300 degrees for CF nylon

### Actual behavior

Every time machine hits 298 degrees either by temp setting or over run the machine shuts down.

### Steps to Reproduce

298 shuts the machine down

### Version of Marlin Firmware

2.1.2

### Printer model

Ender 3 neo

### Electronics

Stock

### Add-ons

Sprite head

### Bed Leveling

None

### Your Slicer

Cura

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

**Comment by thisiskeithb** [comment] 2023-05-09 19:33
Duplicate of https://github.com/MarlinFirmware/Marlin/issues/25790

**Comment by thisiskeithb** [comment] 2023-05-09 19:34
You can’t exceed the thermistor table’s max temperature. Once you do, Marlin halts the machine.

**Closed as completed by thisiskeithb** 2023-05-09 19:33 UTC
