### ISSUE TITLE
Reported z height different between LCD info, LCD Move Z and M114

### ISSUE THREAD

**Issue by autonumous** [MarlinFirmware/Marlin#10571] opened 2018-04-29 19:06 UTC
Maybe just a rounding issue, but i’ve noticed on multiple occasions, across multiple firmware versions that the reported Z height is inconsistent between whats reported on the LCD info screen, when moving the Z axis via the LCD/Knob and whats reported when issuing an M114.

I’ve most often noticed this when setting the bed/nozzle  position, often resulting in two 0 positions, but with the bed moving on each turn. 

with the following I’m able to reproduce 

G28
G91
G0 Z10
G92 X0 Y0 Z0   ; set current position to 0,0,0
M114  ; confirm
M211 S0 ; disable Software endstops
G0 Z 0.3
m114 ; 

**M114 shows z=0.30**
**LCD Info screen shows z=0.3**
**LCD Move Z axis shows z=+000.3**

; Using menu, select prepare -> Move Axis -> Move z -> Move 0.1mm  ->  rotate knob to lower
(display changed to **+000.1**)

**M114 shows z=0.20**
**LCD Info screen shows z=0.2**
**LCD Move Z axis shows z=+000.1** *

; Using menu, select prepare -> Move Axis -> Move z -> Move 0.1mm  ->  rotate knob to lower
(display changed to +000.0)

**M114 shows z=0.10**
**LCD Info screen shows z=0.1**
**LCD Move Z axis shows z=+000.0**

; Using menu, select prepare -> Move Axis -> Move z -> Move 0.1mm  ->  rotate knob to lower
(display changed to +000.0 - no change)

**M114 shows z=-0.00**
**LCD Info screen shows z=0**
**LCD Move Z axis shows z=+000.0**

; Using menu, select prepare -> Move Axis -> Move z -> Move 0.1mm  ->  rotate knob to lower
(display changed to -000.1)

**M114 shows z=-0.10**
**LCD Info screen shows z=-0.1**
**LCD Move Z axis shows z=-000.1**

; Using menu, select prepare -> Move Axis -> Move z -> Move 0.1mm  ->  rotate knob to lower
(display changed to -000.2)

**M114 shows z=-0.20**
**LCD Info screen shows z=-0.2**
*

#

**Comment by thinkyhead** [comment] 2018-04-29 23:23
This is due to float rounding. The value of 0.2 is sometimes 0.19999 We're working on it.

Please test with the latest `bugfix-1.1.x` (and/or `bugfix-2.0.x`) branch to see where it stands. If the problem has been resolved then we can close this issue. If the issue isn't resolved yet, then we should investigate further.

**Comment by autonumous** [comment] 2018-05-01 00:30
Assumed it was related to some sort of rounding issue.

Just tested with the latest bugfix-1.1.x f4a7531ccbc51e674ac3d228fddf0fdcc0f3132c, seems better, only getting 1 zero (0), and all three values appear to be in sync.

good to close i think...

**Closed as completed** 2018-05-01 00:30 UTC
Labels: T: Question
