### ISSUE TITLE
[BUG] No print after power loss procedure

### ISSUE THREAD

**Issue by borsegbr** [MarlinFirmware/Marlin#19662] opened 2020-10-09 00:56 UTC
### Bug Description

After reboot machine when say power loss detected kill...
marlin ask to resume print  but whe is proprely heated and go in correct position print doesn't resume

### My Configurations

skr 1.4 turbo
tft35 v3 in marlin mode

[configs.zip](https://github.com/MarlinFirmware/Marlin/files/5351998/configs.zip)

### Steps to Reproduce

1. start a print do first layer and cut off power
2. reconect power, select resume print
3. printer heat and do first move to parts correctly but not print anything

#### Additional Information
serial prompt:
```
echo:Active Extruder: 0
M106 P0 S255
echo:Bed Leveling ON
echo:Fade Height 2.00
echo:Now fresh file: /LASER~1.GCO
open failed, File: LASER~1.GCO.
//action:resume

```

**Comment by ellensp** [comment] 2020-10-09 01:00
Please attach your configuration files and fill out the template

**Comment by thisiskeithb** [comment] 2020-10-09 01:12
Duplicate of https://github.com/MarlinFirmware/Marlin/issues/19602

**Closed as completed by thisiskeithb** 2020-10-09 01:12 UTC
