### ISSUE TITLE
[bugfix_2.0.x]Due not starting up anymore

### ISSUE THREAD

**Issue by dembach** [MarlinFirmware/Marlin#9782] opened 2018-02-23 20:19 UTC
unchanged config from 04.02.2018 but something happened that my due is not starting with the bugfix_2.0.x of today anymore.
disabled all features that may interfere with advanced features like TMC2130, SPI-EEPROM and so on... but still not starting up anymore, even without Shield.

attached the config
[Configuration_adv.txt](https://github.com/MarlinFirmware/Marlin/files/1753052/Configuration_adv.txt)
[Configuration.txt](https://github.com/MarlinFirmware/Marlin/files/1753054/Configuration.txt)

**Comment by thinkyhead** [comment] 2018-02-23 20:35
Before each build, delete `.pioenvs` and `.piolibdeps` beforehand. Try the current `bugfix-2.0.x` first. Then try some earlier ones, starting with this from a day or two ago:

https://github.com/MarlinFirmware/Marlin/archive/a6b7e721cfe8876cd4ff262cb325983e8be1274b.zip

Then a bit earlier…

https://github.com/MarlinFirmware/Marlin/archive/59c98d6fd57a390cdb44983ff94e4fb622dfa6fd.zip

**Comment by dembach** [comment] 2018-02-23 21:08
@thinkyhead : 
tested both..... not working....
reverted back to 04.02.2018, working.... no config changes...working

**Comment by cjsoong** [comment] 2018-02-24 01:47
@dembach 
I use DUE + RAMPS-FD V2 + marlin 2.0x 20-02-2018 in delta mode no problem.
Do you have to re-edit the new config file? Maybe the config file version is too old
After upload firmwrec need to turn off the power re-boot, because sometimes i2c bus abnormal boot will be delayed for a long time.
process::
1. upload firmware
2. Power off
3. re power on
4. init EEPROM,
5. Restore failsafe
6. store setting

**Comment by thinkyhead** [comment] 2018-02-24 01:54
The second commit I linked above was from 21-02-2018 so it is remotely possible that a version from the 19th or 20th will be ok and something did get broken. Let's try one from the 19th and see if we end up with a working Due.

https://github.com/MarlinFirmware/Marlin/archive/6e932f979d57350125d79d76e525cd005ba142f0.zip

**Comment by dembach** [comment] 2018-02-24 08:28
@thinkyhead : that´s 1.1 you have sent in your last post...

trying this one:
https://github.com/MarlinFirmware/Marlin/tree/a823b801b8a29ec77ece133e806f3bed83c3b80d

have to add : 
```
#define X_CS_PIN 7
#define Y_CS_PIN 6
#define Z_CS_PIN 5
#define E0_CS_PIN 3
```
in configuration_adv.h
(my servos on my RAMPS-FD are disabled and beeing used for CS)

but not working... going back more.....

found something in between of my copy of 04.02.2018 and later that day....
https://github.com/MarlinFirmware/Marlin/tree/766faa05a95140a09f33d208352f766979e48ac2
this one is not working anymore.... need to find out, what´s happening...
My copy was of the morning of 04.02.2018 (CET)...config files only copied, not changed...

i will do a manual reconfigure of all the settings... (what a mess always, this must be easier in the future)

**Comment by Bob-the-Kuhn** [comment] 2018-02-24 19:45
It works if you disable **I2C_EEPROM** in **pins_RAMPS_FD_V2.h** and **PRINTCOUNTER** in **Configuration.h**.

I'll let you know when I know more.

**Comment by dembach** [comment] 2018-02-24 19:54
what a crap..... but thanks @Bob-the-Kuhn

**Comment by Bob-the-Kuhn** [comment] 2018-02-24 21:38
It's just PRINTCOUNTER.  

Seems to be hanging in the TWI bus routines within the DUE Platformio tool chain.  But that could be just because I don't have an I2C EEPROM.  Please post your working Marlin & I'll see if it hangs in the same place.  If it doesn't then I can do some more investigation.

**Comment by dembach** [comment] 2018-02-24 21:39
here it is
[Marlin-bugfix-2.0.x_2018_02_04.zip](https://github.com/MarlinFirmware/Marlin/files/1755303/Marlin-bugfix-2.0.x_2018_02_04.zip)

**Comment by Bob-the-Kuhn** [comment] 2018-02-24 23:17
As is it ran.  When I enabled **I2C_EEPROM** in **pins_RAMPS_FD_V2.h** it hung in the same place.

Should **I2C_EEPROM** be enabled?

**Comment by thinkyhead** [comment] 2018-02-25 05:11
I guess it should only be enabled if there is a real I2C EEPROM. The pins file implies it's a built-in feature. Good possibility there's a bug in our handling. Remotely possible it's a bug in the toolchain.

**Comment by thinkyhead** [comment] 2018-02-25 05:23
Is it dying right away on `Wire.begin` or later, inside `eeprom_update_block`?

**Comment by thinkyhead** [comment] 2018-02-25 05:33
Try this change to `I2cEeprom.cpp`:
```diff
- for (byte c = 0; c < n; c++) {
-   if (Wire.available()) eeprom_temp[c] = Wire.read();
-   flag |= (eeprom_temp[c] ^ *((uint8_t*)pos + c));
- }
+ uint8_t *ptr = (uint8_t*)pos;
+ for (byte c = 0; c < n && Wire.available(); c++)
+   flag |= Wire.read() ^ ptr[c];
```
It looks like the current implementation is trying to de-reference the value at `pos + c` as if it was a pointer, rather than just taking the byte.

**Comment by Bob-the-Kuhn** [comment] 2018-02-25 06:04
I know for sure that it's dying in TWI_ConfigureMaster(twi, twiClock, VARIANT_MCK); in Wire.begin

That's proably because I don't have an I2C EEPROM to test with.

**Comment by thinkyhead** [comment] 2018-02-25 06:09
Do we get a prize if we find a bug in the library?

**Comment by dembach** [comment] 2018-02-25 14:50
so there was a price for @Bob-the-Kuhn already... but he decided to get a RAMPS_FD 2.1 for himself, though there was the invitation to a 2.2 by me ;-) 
So i guess there will be more effort for @Bob-the-Kuhn to get it running, due to the RAMPS_FD 2.1 has got I2C EEPROM ....
so it is the same again like #9484 ... we should close one of these..... just wondering why the version of 04.02.2018 is booting ...
And Settings save is working as expected as you can see:
```
echo:Settings Stored (727 bytes; crc 13024)
ok
start
echo:PowerUp
Marlin bugfix-2.0.x

echo: Last Updated: 2018-01-20 | Author: (none, BiQu Kossel+)
echo:Compiled: Feb 24 2018
echo: Free Memory: 82164  PlannerBufferBytes: 1344
echo:V50 stored settings retrieved (727 bytes; crc 13024)
echo:  G21    ; Units in mm
echo:  M149 C ; Units in Celsius

```

but RAMPS_FD V2 has got a real I2C EEPROM.... why should it not be enabled ?

**Comment by Bob-the-Kuhn** [comment] 2018-02-25 22:29
@dembach - I have a couple if I2C EEPROMS coming.  I expect it'll be late this week before I can debug this problem.

**Comment by dembach** [comment] 2018-02-25 22:55
@Bob-the-Kuhn where are you from ?

**Comment by Bob-the-Kuhn** [comment] 2018-02-25 22:58
I'm in Austin Texas.

**Comment by dembach** [comment] 2018-02-25 23:10
ahh... Digikey delivers within one day to US land....  ;-)

got also I2C Eproms here.... very easy to install.... one side is only GND , other side the communication pins. so just the eeprom itself is needed... no other components.... just too easy...

**Comment by Bob-the-Kuhn** [comment] 2018-02-25 23:20
Yes - ordered them from Digikey this afternoon so they'll be here Wednesday +/- a day.

**Comment by thinkyhead** [comment] 2018-02-26 01:40
Duplicate of #9484

**Closed as completed by thinkyhead** 2018-02-26 01:40 UTC
Labels: Bug: Potential ?, Needs: More Data, T: HAL & APIs

**Comment by Bob-the-Kuhn** [comment] 2018-03-04 21:04
PR #9937 fixes this issue.
