### ISSUE TITLE
[BUG] Printer reset upon starting a print

### ISSUE THREAD

**Issue by MarioStoilov** [MarlinFirmware/Marlin#15150] opened 2019-09-03 14:22 UTC
Flashed marlin 2.0 from 2.09.2019 and wanted to print a calibration cube to adjust my z offset.
I decided to do a tethered print (how I usually do) with a windows machine running repetier host. The gcode I give it is attached.
[xyzCalibration_cube.gcode.zip](https://github.com/MarlinFirmware/Marlin/files/3569894/xyzCalibration_cube.gcode.zip)

After I launch the print job, The printer heats up, does the auto-leveling and when it starts the print (display goes to "Printing...") the printer resets, with no error message on the console. I have no idea how to debug this, so I'm looking for some guidelines.

My configs are:
[Archive.zip](https://github.com/MarlinFirmware/Marlin/files/3569890/Archive.zip)

**Comment by thisiskeithb** [comment] 2019-09-03 15:43
Duplicate of https://github.com/MarlinFirmware/Marlin/issues/15138

This has been patched, so download a fresh copy.

**Closed as completed** 2019-09-03 16:24 UTC
