### ISSUE TITLE
OVERSHOOTING NOZZLE AT 205 Degrees

### ISSUE THREAD

**Issue by Shrikant888** [MarlinFirmware/Marlin#5076] opened 2016-10-24 05:38 UTC
Hi Everybody...

I have done PID TUNING for nozzle and trying to take print model at 205 degrees...

Tried a lot but temperature is going upto 208 which is OVERSHOOTING... Manually calculated OVERSHOOTING values...

Please help me 
Shall I change PID_MAX and BANG_MAX values from MARLIN...?

**Comment by Shrikant888** [comment] 2016-10-24 06:02
![img_20161024_113117](https://cloud.githubusercontent.com/assets/22236971/19635085/72db0066-99dd-11e6-87f5-ee02c13480f3.jpg)

**Comment by Shrikant888** [comment] 2016-10-24 06:06
![img_20161024_113117](https://cloud.githubusercontent.com/assets/22236971/19635108/9843b1ea-99dd-11e6-85db-4f201bbc8b97.jpg)

**Comment by Shrikant888** [comment] 2016-10-24 06:07
![nnn](https://cloud.githubusercontent.com/assets/22236971/19635187/2b9fd66c-99de-11e6-8c59-0b998f11871e.jpg)

**Comment by thinkyhead** [comment] 2016-10-24 07:23
> Shall I change PID_MAX and BANG_MAX values from MARLIN

That sounds like a good plan. Try everything you can think of.
And don't forget to ask for help at http://forums.reprap.org

**Comment by Shrikant888** [comment] 2016-10-24 07:24
Please help me.. Since from a week I am trying. The difference is coming nearly 5-6 degrees... For 205 degree model, Its going upto 209 degrees...

**Comment by thinkyhead** [comment] 2016-10-24 07:26
Sorry, I don't know how to help you except to suggest you keep trying stuff and find someone close by who can come over and physically interact with your machine. After all, I'm just another RepRap enthusiast like yourself, and very new to all this electronics mumbo-jumbo.

**Comment by Shrikant888** [comment] 2016-10-24 07:31
I am done PID AUTOTUNING nearly 15-20 times for different different temperatures... All are coming as same...
What to do?

**Comment by Kaibob2** [comment] 2016-10-24 07:55
In Configuratin.h
https://github.com/MarlinFirmware/Marlin/blob/RCBugFix/Marlin/Configuration.h#L289-L301
try changing
`#define PID_MAX BANG_MAX` to `#define PID_MAX BANG_MAX 200`
this will reduce the current to your heater when in PID regulation
and
`#define PID_FUNCTIONAL_RANGE 10` to `#define PID_FUNCTIONAL_RANGE 30`
this will make the PID regulation kick in 30° before reaching target temperature

**And once again: OVERSHOOTING OF 5-6° ON HEATUP IS NO PROBLEM!!!** 
It is only important that the temperature stays in a few degrees range around target temperature **DURING PRINT**

**Comment by thinkyhead** [comment] 2016-10-24 07:56
@Shrikant888 I wish I knew enough to help you, but I just write the code. For the most part, the electronics side and PID integration is all voodoo to me.

While we're waiting for the cavalry to arrive, open Repetier Host and turn on temperature monitoring, then do a heat-up while watching the plotted curve up until the point where it stabilizes. Once you have a good detailed picture of the heating curve, where you can clearly see the overshoot, capture the screen and post the image here.

The way Repetier draws the graph, you can't see small fluctuations easily, so it might be hard to see them until it's been going for a few minutes. You can try having Repetier check the temperature more often so it will show more vertical detail.

Anyway, the next thing is to watch that graph. If it continually fluctuates up and down, then you may have a problem. But otherwise, you're doing fine.

If you do see continual fluctuations, capture that screen and post it here also.

**Comment by thinkyhead** [comment] 2016-10-24 08:00
> OVERSHOOTING OF 5-6° ON HEATUP IS NO PROBLEM

@KaiBob2 From the original post I'm given the impression that the temperature is staying 5 or more degrees too high throughout the print. After all, Shri has been told already, in no uncertain terms, that some overshoot is _totally normal_.

Do I have it correct, @Shrikant888 that your hot-end temperature _**never-ever**_ stabilizes?

**Comment by Kaibob2** [comment] 2016-10-24 08:09
> the impression that the temperature is staying 5 or more degrees too high throughout the print

If this is the case i have to appologise for pointing only to 

> And once again: OVERSHOOTING OF 5-6° ON HEATUP IS NO PROBLEM!!!

But looking at the cube image from the original thread i would not think, that this is caused by a 3° difference.

**Comment by thinkyhead** [comment] 2016-10-24 09:01
> i would not think, that this is caused by a 3° difference.

I agree. I think it's an issue of poor extrusion or too-few solid layers.

**Comment by Shrikant888** [comment] 2016-10-24 09:26
Ok done PID and got values nearly 1 degree difference.. that is Nozzle set for 205 but showing upto 206...

Now the problem is here...

Its dropping from 206 to 205 204 203 then coming to 205......

**Comment by Kaibob2** [comment] 2016-10-24 10:36
This is also normal! You cannot expect from the software regulation that it will EXACTLY climb to 205° and stay there perfectly. This is not possible, not with PID like implemented in Marlin. 
So, nevermind if it overshoots, and drops right after. If it will stabilize around the target temperature, 205° in your scenario, shortly after it touched the target temperature once everything works as intended!!

**Comment by Kaibob2** [comment] 2016-10-24 10:56
Only for example:
![change_with_kd](https://cloud.githubusercontent.com/assets/20832276/19643138/02c4cb2a-99e9-11e6-9433-1a17452f895e.png)
If you take a look at the red plot it describes what you're experiencing in your setup. This image is taken from the [Wikipedia PID explanation](https://en.wikipedia.org/wiki/PID_controller) so you're experiencing nothing unusual or problematic temperature behaviour.

**Comment by thinkyhead** [comment] 2016-10-24 11:23
So there you have it. Situation normal, as already explained once before. Now, I'm going to close this issue. _@Shrikant888 **Don't repost this question.**_

**Comment by thinkyhead** [comment] 2016-10-24 11:24
So there you have it. Your oven also does this.
Ask Maytag or Westinghouse!
Situation normal, as already explained once before.
Now, I'm going to close this issue.

_@Shrikant888 **Don't repost this question.**_

**Closed as completed by thinkyhead** 2016-10-24 11:24 UTC
Labels: C: Documentation, T: Question, C: Configuration, Bug? Feature!
