### ISSUE TITLE
[FR] M600 option to tool change

### ISSUE THREAD

**Issue by mtmello2003** [MarlinFirmware/Marlin#11399] opened 2018-07-28 10:54 UTC
Hello,

Could be an usefull option in M600: add the option in the display to "tool change" that run a user definied gcode script.

Nowaday we have the LCD options to "continue" and "purge more".

Tks

**Comment by plloppii** [comment] 2018-07-31 19:55
Not quite sure what you are asking for, but do you mean like switching to the second nozzle to continue printing after filament runout?

**Comment by mtmello2003** [comment] 2018-08-04 22:21
Exactly! If marlin tag #EXTRUDERS is with 2 (or more), with M600 an option to change to second extruder could be really good.

**Comment by thinkyhead** [comment] 2018-08-13 10:03
I like the idea. Marlin 2.0 is getting a reorganized LCD menu layout. Adding "tool change" as a filament change option on the LCD, especially in response to a filament runout, makes sense, as you might have filament loaded in the other extruder. In fact, there is a submission in the queue which would allow you to change to the next filament spool on runout, supporting multiple inputs to a single nozzle….

**Comment by plloppii** [comment] 2018-08-13 16:53
@mtmello2003 @thinkyhead 
So I actually implemented this feature on our Gigabots already based on Marlin 1.1.9. I was able to create a separate M601 gcode called Continuous Printing After Filament Runout.
I will clean up the code and do a pull request.

**Comment by thinkyhead** [comment] 2018-11-05 09:47
@plloppii — Looking forward to it. Previous attempts have been incomplete and poor.

**Comment by boelle** [comment] 2019-02-20 15:30
@plloppii did you make an PR?

**Comment by plloppii** [comment] 2019-02-20 17:19
Not yet, I’m not done with it yet. I also haven’t had too much time to look at it.

**Comment by boelle** [comment] 2019-06-22 13:16
missing label

**Comment by InsanityAutomation** [comment] 2019-06-22 15:59
There have been a couple runs at a flying tool change on runout. Id suggest a 2.1 label.

**Comment by Roxy-3D** [comment] 2019-06-22 18:24
> There have been a couple runs at a flying tool change on runout. Id suggest a 2.1 label.

Done...

**Comment by thinkyhead** [comment] 2019-06-28 01:05
We have a 2.1 Milestone. Labels are rather more general.

**Comment by qwewer0** [comment] 2021-01-01 19:27
Duplicate of https://github.com/MarlinFirmware/Marlin/issues/10951? One or the other can be closed.

**Comment by InsanityAutomation** [comment] 2021-01-01 22:05
This feature, though hard to use and needing more work, is implemented. See TOOLCHANGE_MIGRATION_FEATURE.

**Closed as completed by InsanityAutomation** 2021-01-01 22:05 UTC
Labels: T: Feature Request
