### ISSUE TITLE
[BUG] Nonlinear extrusion is applied for unretracts

### ISSUE THREAD

**Issue by vovodroid** [MarlinFirmware/Marlin#26808] opened 2024-02-21 06:56 UTC
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

There is big overextrusion at the line start with nonlinear extrusion enabled:

![image](https://github.com/MarlinFirmware/Marlin/assets/8691781/612ff29d-8302-4e03-8421-5be26dde8d2e)

NLE disabled:

![image](https://github.com/MarlinFirmware/Marlin/assets/8691781/bd80b3f0-85db-4a9d-8780-ced160064db4)

Code https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.1.x/Marlin/src/module/stepper.cpp#L2742

```
        if (current_block->direction_bits.e) {
          ne_fix.A = (1L << 24) * ne.A;
          ne_fix.B = (1L << 24) * ne.B;
          ne_fix.C = (1L << 24) * ne.C;
        }
        else {
          ne_fix.A = ne_fix.B = 0;
          ne_fix.C = (1L << 24);
        }
```

doesn't check for X/Y movement, thus applying correction for unretracts.

How to test:

```
M302 S0; enable cold extrude
M83; relative E

M592 C2; double extrusion

G1 E33.1 F500; extrude one gear rotation (depending on extruder)
```

Gear makes two rotations instead of one.

I tried `if (current_block->direction_bits.e && !(axis_did_move.a || axis_did_move.b))`, but it had no effect.

**Comment by vovodroid** [comment] 2024-02-21 07:10
Will 

`if (current_block->direction_bits.e && !axis_did_move.x && axis_did_move.y)`

be correct fix?

**Comment by vovodroid** [comment] 2024-02-21 20:17
@abortz, could you take a look please?

**Comment by abortz** [comment] 2024-02-23 16:06
Thanks for the heads up @vovodroid! Let me do some testing, but I think you're right that this can be a problem. I believe I may have noticed some line start blobbing myself, but it's always been so minor I've written it off.

I'm kinda hesitant to disable NLE on unretracts, since the core problem we're trying to solve exists regardless of how the extruder is being used, and unretracts are typically done at very high speeds where the problem is exacerbated. I was hoping that no NLE on retracts and NLE on unretracts would be "correct" in a sense, but perhaps not... Obviously it's far more important to get retraction dead-on right!

**Comment by vovodroid** [comment] 2024-02-23 16:16
> it's always been so minor

By mistake I swapped A and B coefficients (wrong mathematics order is very confusing, it's RepRap legacy, I guess), so result was much higher for high speed.

> unretracts are typically done at very high speeds

Yes, but most of unretract path is before orifice itself. Imagine Bowed extractor with retract 5 mm, at high unrectact speed you can easily arrive to 7-10 mm unrectact, resulting in huge blob. Probably it could be solved by applying correction to final 0.2-0.3 mm, but it's too complicated. Better is to set unretract extra length in slicer/Marlin.

**Comment by abortz** [comment] 2024-02-23 16:36
> > unretracts are typically done at very high speeds
> 
> Yes, but most of unretract path is before orifice itself. Imagine Bowed extractor with retract 5 mm, at high unrectact speed you can easily arrive to 7-10 mm unrectact, resulting in huge blob. Probably it could be solved by applying correction to final 0.2-0.3 mm, but it's too complicated. Better is to set unretract extra length in slicer/Marlin.

That is a great point! So then, since having Marlin know when the filament is and isn't actually *pushed* into the bottleneck is way too much to expect, I'm pretty convinced then disabling NLE for unretracts is the best option.

In the planner Marlin checks for retracts/unretracts here: https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.1.x/Marlin/src/module/planner.cpp#L2466
That's probably how we should do it as well, if you want to give it another stab. Haven't done any Marlin development in a while, need time to spin up the dev environment again.

**Comment by vovodroid** [comment] 2024-02-23 16:45
> In the planner Marlin checks for retracts/unretracts here: https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.1.x/Marlin/src/module/planner.cpp#L2466

But NLE is applied in interrupt service routine latter. Actually planner code checks axis steps, that's what I tried in ISR, but it doesn't work in ISR.

**Comment by abortz** [comment] 2024-02-23 17:20
> > In the planner Marlin checks for retracts/unretracts here: https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.1.x/Marlin/src/module/planner.cpp#L2466
> 
> But NLE is applied in interrupt service routine latter. Actually planner code checks axis steps, that's what I tried in ISR, but it doesn't work in ISR.

I know NLE is applied later, but I don't see why it didn't/wouldn't work the same in the scheduler there, the step count is definitely populated there.

**Comment by vovodroid** [comment] 2024-02-23 19:02
Would you like to move NLE from stepper ISR to planner? Could SERIAL debug be used there?

**Comment by abortz** [comment] 2024-02-24 02:20
Well at least part needs to live in stepper interrupts, because it needs access to the *current* feedrate factoring in accelerations etc. I hadn't thought about the per-block setup living in the planner, and sadly I have no experience with Marlin serial debug. If you're having trouble making it work, I'll spin up an environment and try my hand.

**Comment by vovodroid** [comment] 2024-02-24 17:38
> I have no experience with Marlin serial debug.

I mean just output log to serial port, but it seems doesn't work in ISR.

Actually my question why `if (current_block->direction_bits.e && current_block->steps.a == 0 && current_block->steps.b == 0)` didn't help?

Code you referred in planner

```
if (true NUM_AXIS_GANG(
      && !block->steps.a, && !block->steps.b, && !block->steps.c,
      && !block->steps.i, && !block->steps.j, && !block->steps.k,
      && !block->steps.u, && !block->steps.v, && !block->steps.w)
  ) {                                                             // Is this a retract / recover move?
    accel = CEIL(settings.retract_acceleration * steps_per_mm);   // Convert to: acceleration steps/sec^2
  }
```

checks the same.

**Comment by abortz** [comment] 2024-02-26 19:30
> Actually my question why `if (current_block->direction_bits.e && current_block->steps.a == 0 && current_block->steps.b == 0)` didn't help?

Oh, I think you've got the logic reversed. We want to apply NLE if: we are extruding forward AND we are moving any axis. Try:
`if (current_block->direction_bits.e && (current_block->steps.a || current_block->steps.b))`

**Comment by vovodroid** [comment] 2024-02-26 21:03
> I think you've got the logic reversed.

Just dummy concentration, is there facepalm smile?))) Sure you are right, it's working now!

What is the correct way to test it?

NUM_AXIS_GANG with `block->steps.*` or `didmove.*`?

**Comment by abortz** [comment] 2024-02-26 21:09
> > I think you've got the logic reversed.
> 
> Just dummy concentration, is there facepalm smile?))) Sure you are right, it's working now!

Yay!!!

> What is the correct way to test it?
> 
> NUM_AXIS_GANG with `block->steps.*` or `didmove.*`?

*shrug*

Submit a pull request and we can continue the conversation there and get some more eyes on the code. For all intents and purposes what you have there is probably fine, but the "correct" way is the way it's done in the planner, since that would work with all motion systems including unusual ones.

**Comment by thisiskeithb** [comment] 2024-02-27 10:29
Closing since you’ve opened a PR.

**Closed as completed by thisiskeithb** 2024-02-27 10:29 UTC
Labels: C: Motion
