### ISSUE TITLE
[FR] TMC Hybrid Threshold hysteresis control

### ISSUE THREAD

**Issue by sargonphin** [MarlinFirmware/Marlin#25943] opened 2023-06-07 09:45 UTC
### Is your feature request related to a problem? Please describe.

I am running into mechanical problems regarding TMC hybrid threshold. The way I could describe the printing speeds right now is that, the printer is allowed to run at extremely high speeds and acceleration when traveling (>500mm/s and 6000mm/s²) and can print very fast as well (>240mm/s same acceleration) but only when a specific set of conditions are met. A combination of slicer settings, strong Linear Advance and conservative Input Shaping settings slow down the printer to more standard speeds (around 50mm/s for very small details and not above 100mm/s for skins or other larger details). This system works incredibly well when using SpreadCycle only

Printing at this speed is not possible in StealthChop and to be honest, it would be noisier than SpreadCycle. But at low speeds, where SpreadCycle produces a soft characteristic "knock" sound when accelerating and a hiss that can be heard from far away (we print at night), StealthChop is preferable for its much softer acoustic softness. This is where Hybrid Threshold comes into place. We want the printer to switch to StealthChop when printing small details and use SpreadCycle when going haywire on the infill or traveling

Switching between both SC will always produce a knocking sound when the motor is moving. This means Hybrid Threshold produces an extreme knocking sound during acceleration, as it switches in and out of SpreadCycle/StealthChop as speed very momentarily drops in direction changes. It sounds like a stepper motor falling into tile flooring

### Are you looking for hardware support?

BTT SKR V1.4 Turbo with TMC 2209 V1.2

### Describe the feature you want

A hysteresis control on the Hybrid Threshold which is setup in a way that the stepper drivers switch to SpreadCycle more easily than switching back to StealthChop. It is VERY IMPORTANT that SpreadCycle has priority over StealthChop, as the later cannot withstand the kind of acceleration and speeds we have in our printer.

It could also be using the movement buffer to determine if it switches over in the few milliseconds the motor is at a full stop when changing directions, or just holding SpreadCycle when a queue of fast movements is planned. 

### Additional context

In our specific use case, only the Z steppers are using StealthChop as they never move fast anyway
EDIT: At the moment of testing, any form of jerk control or acceleration dampening was disabled in Slicer. The printer had no Linear Advance or Input Shaping configured. Classic Jerk was not in use

**Comment by thisiskeithb** [comment] 2023-06-07 14:00
Duplicate of https://github.com/MarlinFirmware/Marlin/issues/13316

**Closed as completed by thisiskeithb** 2023-06-07 14:00 UTC
Labels: T: Feature Request
