### ISSUE TITLE
[FR] output eeprom settings to file on SD card

### ISSUE THREAD

**Issue by Phr3d13** [MarlinFirmware/Marlin#11052] opened 2018-06-17 23:08 UTC
### Description

An option in the LCD menu to output eeprom settings to a file on the SD card. It would make updating to a new Marlin version much easier after a hard drive crash or other instance where the old configs are no longer available.

**Comment by dot-bob** [comment] 2018-06-18 16:44
Have the output the file in gcode so you could just select the file just like a print to reload the eeprom settings.

**Comment by Squid116** [comment] 2018-06-18 23:30
@dot-bob that would be awesome, then you could configure the host to save the settings on each print (so that you can backtrack and work out why benchy number 123,423 worked, but number 123,424 didn't).

**Comment by thinkyhead** [comment] 2018-06-20 08:34
Meanwhile, you can copy the output of `M503 S0` into a .gcode file and save it to disk.

**Comment by sjasonsmith** [comment] 2020-08-31 20:58
Duplicate of #12119

**Closed as completed by sjasonsmith** 2020-08-31 20:58 UTC
Labels: T: Feature Request
