### ISSUE TITLE
[BUG] (Ender 2 stock display blank screen Marlin 2.0 and Creality 4.2.7)

### ISSUE THREAD

**Issue by xnaron** [MarlinFirmware/Marlin#19337] opened 2020-09-10 22:36 UTC
### Bug Description

Ender 2 stock display does not work with Marlin 2.0 on creality 4.2.7

### My Configurations

**Required:** Please include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.

### Steps to Reproduce

1. Unzip bugfix 2.0
2. Use my supplied configuration.h and configuration_adv.h
3. Make changes to pins_creality_v4.h  to add this after line 160
// Xnaron added this
#undef DOGLCD_CS
#undef DOGLCD_A0
#undef DOGLCD_SCK
#undef DOGLCD_MOSI

//#define LCD_SDSS 31  // Smart Controller SD card reader (rather than the Melzi)
#define DOGLCD_CS PB12 // DOG CS  xnaron was mapped to 28
#define DOGLCD_A0 PB13 // DOG A0 is already defined in pins_SANGUINOLOLU_11.h xnaron was mapped to 30

#define DOGLCD_SCK PC6
#define DOGLCD_MOSI PB15

**Expected behavior:** [What you expect to happen]
Display should appear

**Actual behavior:** [What actually happens]
Blank screen
#### Additional Information
I am not sure what I am missing.  I verified those pins using a multimeter and compared to datasheet.   Also verified the firmware does get updated connecting to board with serial terminal and issuing M115.  There is nothing connected to the control board.
![Screenshot 2020-09-10 163435](https://user-images.githubusercontent.com/882989/92817195-8c664780-f383-11ea-8f21-00689f8641d4.jpg)

FIRMWARE_NAME:Marlin bugfix-2.0.x (Sep 10 2020 16:18:01) SOURCE_CODE_URL:https://github.com/MarlinFirmware/Marlin PROTOCOL_VERSION:1.0 MACHINE_TYPE:Ender-3 Pro V1.5 EXTRUDER_COUNT:1 UUID:cede2a2f-41a2-4748-9b12-c55c62f367ff
Cap:SERIAL_XON_XOFF:0
Cap:BINARY_FILE_TRANSFER:0
Cap:EEPROM:1
Cap:VOLUMETRIC:1
...

* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/5204949/Configuration.zip)

**Comment by thisiskeithb** [comment] 2020-09-11 00:32
Duplicate of https://github.com/MarlinFirmware/Marlin/issues/19336

**Closed as completed by thisiskeithb** 2020-09-11 00:32 UTC
