### ISSUE TITLE
[BUG] BLTOUCH does not work with 2.1.2.2 with Ender 3 Pro

### ISSUE THREAD

**Issue by lumapu** [MarlinFirmware/Marlin#26929] opened 2024-04-01 00:07 UTC
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

I made some changes to the `Configuration.h`

I compiled it and installed it on my printer. After installing go to `Motion -> Auto Home`. Once the printer starts to lower its z-axis touch the BLTOUCH sensor and check if it stops - for me it doesn't stop.

### Bug Timeline

not seen with Marlin `2.1.2.1`

### Expected behavior

same behaviour as with Marlin `2.1.2.1`

### Actual behavior

 `Motion -> Auto Home`. The printer does not stop once the BLTOUCH is triggering

### Steps to Reproduce

changes to the `Configuration.h`:
```diff
-#define Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN
+//#define Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN
...
-//#define BLTOUCH
+#define BLTOUCH
...
-//#define AUTO_BED_LEVELING_BILINEAR
+#define AUTO_BED_LEVELING_BILINEAR
...
-//#define RESTORE_LEVELING_AFTER_G28
+#define RESTORE_LEVELING_AFTER_G28
...
-//#define Z_SAFE_HOMING
+#define Z_SAFE_HOMING
...
-#define GRID_MAX_POINTS_X 3
+#define GRID_MAX_POINTS_X 4
```

### Version of Marlin Firmware

2.1.2.2

### Printer model

Ender-3 Pro

### Electronics

4.2.7 (OUT printed on the BLTOUCH header)

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Other (explain below)

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Config_Ender3Pro_Marlin_2.1.2.2_BLTouch.zip](https://github.com/MarlinFirmware/Marlin/files/14818033/Config_Ender3Pro_Marlin_2.1.2.2_BLTouch.zip)

**Comment by thisiskeithb** [comment] 2024-04-01 02:04
Duplicate of https://github.com/MarlinFirmware/Marlin/issues/26809

**Closed as completed by thisiskeithb** 2024-04-01 02:04 UTC
