### ISSUE TITLE
[BUG] SKR 1.3 won't boot due to invalid EEPROM values

### ISSUE THREAD

**Issue by OneOfEleven** [MarlinFirmware/Marlin#14483] opened 2019-07-02 17:41 UTC
At some point during a 1+ hour print, the SKR 1.3 eeprom settings became not what is wanted, but are apparently still valid (no CRC error it seems ?).

Due to the above, the SKR board will no longer boot due to a MAXTEMP BED error (according to the LCD) if eeprom is enabled ( #define EEPROM_SETTINGS in Configuration.h). Their is no max temp error, it's a false error.

If I disable eeprom access in the config file, re-compile etc then the board boots up fine with no errors at all. If I then re-enable eeprom access in the config file, we're back to non-booting up again :(

Unfortunately, because the board won't boot with eeprom enabled, I can't re-initialize the eeprom from either the LCD menu or command line via serial.

I've tried enabling **#define BOGUS_TEMPERATURE_FAILSAFE_OVERRIDE** with no luck. It does mean the board doesn't show a MAX TEMP error at boot-up but still won't boot, it simply stays their with the boot-up logo showing, it gets no further in the boot-up process.

Am stuck with a board that I can't use eeprom settings in Marlin :(

**Comment by cdedwards** [comment] 2019-07-02 21:33
wouldn't deleting the config.dat or whatever it's called from the SD card solve this issue?

**Comment by ManuelMcLure** [comment] 2019-07-02 21:36
There is no config.dat any more - the LPC1768 HAL (used by the SKR1.3) used the onboard flash to emulate EEPROM instead of a file on the SD card.

You can try checking out commit 18e396b102421fe7a82ae3d52f52a75aa44e6ed4 since that's the one before the fix that seems to have broken auto-loading of the EEPROM data on LPC1768.

**Comment by ManuelMcLure** [comment] 2019-07-02 21:39
See also #14470.

**Comment by thinkyhead** [comment] 2019-07-03 06:03
Duplicate of #14470

**Closed as completed by thinkyhead** 2019-07-03 06:03 UTC

**Comment by OneOfEleven** [comment] 2019-07-03 08:53
> 
> 
> You can try checking out commit [18e396b](https://github.com/MarlinFirmware/Marlin/commit/18e396b102421fe7a82ae3d52f52a75aa44e6ed4) since that's the one before the fix that seems to have broken auto-loading of the EEPROM data on LPC1768.

I can confirm that is the case. That commit works, the one after does not.

**Comment by Ohmarinus** [comment] 2019-11-14 23:39
Sorry for necromancing this one, but I just had my SKR board quit on me after killing the power and starting it again. First the SD-card wouldn't show up anymore on my computer through USB. But I could still send gcode commands through Pronterface and save and retrieve new info with M500 M501 and M503.

Now when starting the printer through 12V I get this error:
Err: "MAXTEMP: Bed
paired with loud beeping.

I cannot find a way to get out of this. Can it be this is still an issue with Marlin or is this an inherent fault in the SKR 1.3's design? Rebooting the SKR with the USB cable in my macbook pro also caused the macbook to restart. I have inspected the wires in my machine and there doesn't seem to be anything wrong so I suspect a firmware/EEPROM error. How can I find out more?

Update:
When approaching the board through USB (with the jumper set to the USB power) I still get the error. After unplugging the bed thermistor I am able to boot the SKR, which will then display -14 on the bed temperature. When it is booted I can place the bed thermistor back and it will read the exact right temperature. Rebooting with the thermistor connected again causes the error to appear.

M503 gives the following information. I will update my firmware to the latest bugfix tomorrow morning and report again:
```
>>>M503
SENDING:M503
echo:  G21    ; Units in mm (mm)
echo:  M149 C ; Units in Celsius
echo:Filament settings: Disabled
echo:  M200 D1.75
echo:  M200 D0
echo:Steps per unit:
echo: M92 X80.00 Y80.00 Z80.00 E94.78
echo:Maximum feedrates (units/s):
echo:  M203 X500.00 Y500.00 Z500.00 E1766.69
echo:Maximum Acceleration (units/s2):
echo:  M201 X9000.00 Y9000.00 Z9000.00 E10000.00
echo:Acceleration (units/s2): P<print_accel> R<retract_accel> T<travel_accel>
echo:  M204 P3000.00 R3000.00 T3000.00
echo:Advanced: B<min_segment_time_us> S<min_feedrate> T<min_travel_feedrate> X<max_x_jerk> Y<max_y_jerk> Z<max_z_jerk> E<max_e_jerk>
echo:  M205 B20000.00 S0.00 T0.00 X10.00 Y10.00 Z10.00 E353.34
echo:Unified Bed Leveling:
echo:  M420 S0
Unified Bed Leveling System v1.01 inactive
Active Mesh Slot: -1
EEPROM can hold 31 meshes.
echo:Endstop adjustment:
echo:  M666 X0.00 Y-1.33 Z-0.28
echo:Delta settings: L<diagonal_rod> R<radius> H<height> S<segments_per_s> B<calibration radius> XYZ<tower angle corrections>
echo:  M665 L210.00 R101.32 H310.92 S200.00 B70.00 X-0.14 Y0.24 Z-0.11
echo:Material heatup parameters:
echo:  M145 S0 H0 B60 F0
echo:  M145 S1 H200 B50 F0
echo:PID settings:
echo:  M301 P14.51 I0.96 D54.92
echo:  M304 P66.01 I5.72 D507.42
echo:Z-Probe Offset (mm):
echo:  M851 X-21.94 Y12.67 Z-1.00
echo:Stepper driver current:
echo:  M906 X800 Y800 Z800
echo:  M906 T0 E900
echo:Hybrid Threshold:
echo:  M913 X100 Y100 Z3
echo:  M913 T0 E0
echo:Driver stepping mode:
echo:  M569 S1 X Y Z
echo:  M569 S1 T0 E
```
Solution:
Reflashing the firmware seems to have fixed it. The machine is working correctly again. I have not updated the firmware yet, simply reflashed the firmware that was on it before. Can the EEPROM become corrupted on an SKR 1.3 when you plug in the USB cable during the boot of the SKR controller? This seems to have been the cause.

**Comment by OneOfEleven** [comment] 2019-11-15 03:53
Hi @Ohmarinus 

Check your thermistor/thermistor wiring, unplug it off the board and plug a completely new one in just to first make sure that's not the problem. That one got me.

**Comment by Ohmarinus** [comment] 2019-11-15 08:16
> Hi @Ohmarinus
> 
> Check your thermistor/thermistor wiring, unplug it off the board and plug a completely new one in just to first make sure that's not the problem. That one got me.

Reflashing the firmware fixed it. I am unsure if this is an error of Marlin but clearly something got corrupted. The drawback is that I have to completely take apart the machine in order to turn off the error. It just goes stuck into bed maxtemp error.

See the video in this topic, it shows exactly what happens:
https://reprap.org/forum/read.php?415,862138,862514#msg-862514

I have replaced bed wiring, measured all wires but nothing was wrong! It was the firmware that 'broke' itself.
