### ISSUE TITLE
[BUG] Slow LCD display and unable to get into the LCD menu

### ISSUE THREAD

**Issue by zogthegreat** [MarlinFirmware/Marlin#24349] opened 2022-06-13 20:16 UTC
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

I compiled Marlin 2.1.x and installed it on my Ender 3 Pro with a SKR Mini E3 v3.0. The firmware flashed properly, but upon boot, the LCD loaded VERY slowly:

[https://www.youtube.com/watch?v=UWKsixqjYck](url)

Also, I can't get into the menus from the LCD, I click on the knob, but it doesn't go into the menus. Here is my configuration.h

[https://pastebin.com/GD7fSPj6](url)

And my configuration.adv.h

https://pastebin.com/jz92Qq7L

### Bug Timeline

06/13/2022

### Expected behavior

I expected full control of my printer.

### Actual behavior

Slow/unresponsive LCD, Unable to enter the LCD menu. I can connect with OctoPi and control the printer via terminal.

### Steps to Reproduce

Compile Marlin as per usual
Flash the printer
Wait for bug

[Marlin-Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/8894181/Marlin-Configuration.zip)

### Version of Marlin Firmware

2.1.x

### Printer model

Ender 3 Pro

### Electronics

SKR Mini E3 v3.0

### Add-ons

Antclabs BLTouch

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Cura

### Host Software

OctoPrint

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

**Comment by thisiskeithb** [comment] 2022-06-13 20:21
Duplicate of https://github.com/MarlinFirmware/Marlin/issues/24306

**Closed as completed by thisiskeithb** 2022-06-13 20:21 UTC
