### ISSUE TITLE
IDEX UBL_G29 scope issue on tool change command

### ISSUE THREAD

**Issue by silentninja1** [MarlinFirmware/Marlin#11252] opened 2018-07-12 18:53 UTC
### Description

Compile error with UBL and Dual x carriage in UBL_G29 with current bugfix

### Steps to Reproduce
Uncomment UBL and dual x carriage
Line 297 of UBL_G29.h has the following : 
```cpp
    // Check for commands that require the printer to be homed
    if (may_move) {
      if (axis_unhomed_error()) home_all_axes();
      #if ENABLED(DUAL_X_CARRIAGE)
        if (active_extruder != 0) tool_change(0);
      #endif
    }
```
Tool change is out of scope and home_all_axes is overloaded to a blank function in ubl.h, not sure if the intention is to extend the function from marlin_main, not sure how that works in arduino ide, in which case adding tool change here would work. Tool change is out of scope as well. Other abl methods have this step in marlin_main under a g29 in progress conditional, but I didnt see a branch there for UBL. Im not near my Trex 2+ or any other machines today to confirm, but can I enqueue a command here with enqueue_and_echo_commands_P(PSTR("G28")) to home and enqueue_and_echo_commands_P(PSTR("T0")) to change tools, or is the planner blocked at this stage?

**Comment by silentninja1** [comment] 2018-07-13 19:43
Confirmed today this doesnt work, added the header to ubl.h as the home all axes command was under external references and it did not call the tool change, it just rammed the x1 carriage into the x2 carriage till it bumped its home switch then went into the g29 s1 action. Added the enqueue and echo commands and it executed after the G29, which meant t1 was moving, not t0 therefore it came down and rammed the nozzle into the bed then failed probing a bunch of times. I also tried adding the extern flag to the functions in marlin_main to no avail

**Comment by thinkyhead** [comment] 2018-07-19 01:37
The compile issue is now patched, but the actual tool change to carriage 0 has not yet been tested.

**Comment by InsanityAutomation** [comment] 2018-07-19 01:43
Sounds good, I ran out of time to mess with it, but I'll get back to it Saturday most likely and I'll give it a shot. Hopefully I'll have time to look at the excessive movement off the mesh area too, but we'll see. 

Didn't even think about just moving the prototype to .h when the external flag didn't work lol probably need to do the same for the home command right above where this is, since it winds up calling an empty function as is.

**Comment by Roxy-3D** [comment] 2018-07-19 03:46
> Hopefully I'll have time to look at the excessive movement off the mesh area too, but we'll see.

I was under the impression that the 'excessive movement off the mesh' was corrected 6 weeks ago.  Is that not true?   Can you post your configuration.h files and a G29 T W please?

The code hasn't been written yet...  But there was consensus that we should have several options for Z-Height correction when off the mesh.  One option is it should be 0.0000 mm.  Another option is it should be what ever the closest mesh point is.   And one more thought was it should be an extropolation of the bed topology near the 'off the bed' point.

**Comment by InsanityAutomation** [comment] 2018-07-19 12:04
Roxy, Chris from Tinymachines had a user report it on a build synced July 7th, so first goal is to reproduce it here! Configuration is here, both the raptor and cr10 branches have had reports.

https://github.com/InsanityAutomation/Marlin/tree/TM_Raptor

**Comment by Roxy-3D** [comment] 2018-07-19 16:09
> Chris from Tinymachines had a user report it on a build synced July 7th, so first goal is to reproduce it here!

Yeah...   I think Chris is trying to capture a machine that exhibits the problem.   Having a machine that demonstrates the problem makes it much easier to figure out and fix.

**Comment by silentninja1** [comment] 2018-07-21 18:24
So with a fresh power up, issuing a T1 followed by G29 P1 causes the machine to home then crash E0 into E1. It would seem G28 is not properly restoring the active extruder when called from ubl_g29, so the crash above is still present here.  If I reverse the order of the home command with the tool change in ubl_g29.h this functions correctly. Im going to poke through G28 and restoring the active tool a bit to see if I can find an issue there rather than hiding the issue by reversing command order.

**Comment by silentninja1** [comment] 2018-07-21 18:40
It would seem that following a G28 when T1 was active, the tool change will properly park the head for T0 after homing, however the active stepper is still T1. This occurs any time you home with T1 active, not just related to UBL.

**Comment by silentninja1** [comment] 2018-07-21 19:49
Darn this rabbit hole! LOL So from terminal, bootup , T1 then G28. Move X axis by LCD and T0 moves while T1 position changes. From bootup T1 then G28, M91 G1 X5 T1 moves as expected. Seems to be a manual move issue with selected extruder as well. LCD menu item does show select E1 / E2 as expected when tool change is issued, just still moves the wrong extruder.

**Comment by silentninja1** [comment] 2018-07-21 21:45
Ok, lcd side is working see pull request lcd idex xmove #11328

Probably something similar lurking around g28 with how it works called from the ubl code, but for the moment the race condition is avoided with this

idex crash fix #11329

Ill do a bit more testing if it still moves the wrong axis in any cases I can find tomorrow most likely, im out for the day!

**Comment by Roxy-3D** [comment] 2018-07-21 22:02
@silentninja1     I may be able to help you get closer to the root cause of the problem.   It is my belief that this problem started when some of the methods were moved into the planner object.    Specifically, I think there is an issue with regard to enabling and disabling Z-Height correction based on the location of the nozzle.

For UBL...  The way the motion is done, I'm not convinced the correction needs to be un-done for the current tool and then re-done for the new tool.   Please keep that thought in mind as you search for the cause.

**Comment by silentninja1** [comment] 2018-07-21 22:11
@Roxy-3D Sounds good, I didnt get very far on that today (assuming in reference to the z raise / lower off the mesh)  between sitting on a VPN with a PLC system and getting sidetracked on the wrong gantry moving (then again when it did it from the LCD for a totally different reason!). Hoping to get back after that one tomorrow, especially since I have plenty of stuff at home to mess with it on. Only idex stuff is in my office at the moment.

**Comment by Roxy-3D** [comment] 2018-07-21 22:26
The big problem is I don't have a Dual Nozzle machine.    But I'll help as much as I can.   And if you can figure out what needs to be changed...   I'll get that pushed into the code base.

**Comment by silentninja1** [comment] 2018-07-21 22:34
@Roxy-3D What I submitted today handles all the known dual extruder specific stuff to an extent. Shouldnt have needed to reverse command order in the second commit, but it does the trick (and probably cleaner, since then G28 isnt switching from 1 to 0, back to 1, just for UBL to come back to 0...). If something else is still lurking in there, I cant reproduce it from the terminal. I could try those commands back to back in a custom menu item and see if i can get it to show the issue though. Thats for another weekend since at least now no damage will be caused.

**Comment by Roxy-3D** [comment] 2018-07-21 22:35
And you tested tool changes after G28 with UBL too, right?

**Comment by silentninja1** [comment] 2018-07-21 22:39
Yeah, ive used that for quite awhile. Didnt really have any major issue with it until the tool change code was added and it didnt compile, then started down this rabbit hole! I do need to sit down and do more extensive step by step testing sometime. I havent intentionally tipped the bed and ensured both nozzles followed correctly yet. I did get successful dual extrusion and duplicate mode prints with ubl on. The duplicate mode I actually expected to cause more problems than it did, but I was close enough to level on my own it came out fine.

**Comment by Roxy-3D** [comment] 2018-07-23 20:42
I just changed the configuration of my printer to have two Tools.   (Even though it really only has 1 extruder)    From what I can see...  Everything is behaving properly right now.

**Comment by silentninja1** [comment] 2018-07-23 20:49
@Roxy-3D with or without the 2 commits I referenced? The issue is which stepper was pulsed. It will show the position changing for the right gantry, but the left is whats actually moving. In the case of the tool change from ubl_g29.h, the left head actually rammed into the right head trying to reach the right home before I swapped command order.

**Comment by Roxy-3D** [comment] 2018-07-23 21:10
It is with the current Bugfix_1.1.x branch.    I was getting setup to add different off mesh Z-Height correction options.    And I thought before I actually did that....  I would try to get a handle on the Tool change issues.

@thinkyhead   did a couple of changes to the Tool Change in the last few days.   I suspect he was trying to address what you are seeing.     But I have no way to address a multiple gantry machine.   I just configured my machine to have multiple nozzles (with the 2nd one being offset) to see if it did anything reasonable.    And it does.

**Comment by silentninja1** [comment] 2018-07-23 21:19
Yeah, the issues i'm looking at are exclusive to dual x carriage machines right now. They dont change anything outside of that.

The tool change fix he put in was in reference to what was originally discussed here where there was a no-compile scenario as the function was out of scope. Problem came into play that this function being called there then caused a crash, so more fixing is needed beyond the initial patch to at least make it compile.

Chimera type setup, you need to have the leveling just right regardless of UBL or the second nozzle will destroy the part as things adjust. Personally, im not sure of a good safe way to do ubl with a chimera system. Cyclops / mixing, or switching, sure. Idex, awesome.

**Comment by silentninja1** [comment] 2018-07-24 18:59
Ok, thought id get some clarity to what im doing since you dont have any dual x carriage machines. ubl_g29.h 

Before : 
https://www.youtube.com/watch?v=dPRzWsvN40I

After : 
https://www.youtube.com/watch?v=FYGcARM--fY

UltraLCD.cpp change : 
Before : 
https://www.youtube.com/watch?v=1HihDTCni2Y

After : 
https://www.youtube.com/watch?v=MLnv37BTwXs

**Comment by Roxy-3D** [comment] 2018-07-24 19:26
I watched the video's...    (I like that T-Rex machine!!!)   The dual gantry stuff works in general...  But from within UBL's G29 it fails.    Specifically...  UBL's G29 P1 moves the wrong nozzle (and probe) if the 2nd nozzle is specified.

Is that what you are saying?   Because, if so...  We should be able to hunt down the cause and fix it...

Do both of the gantry's on that machine have a probe?    Because if they do, they would both need to be at the same exact X_OFFSET_FROM_EXTRUDER and Y_OFFSET_FROM_EXTRUDER position.

But either way...   right now, it looks like the probe_pt() function is moving the wrong gantry on your machine.

**Comment by silentninja1** [comment] 2018-07-24 19:38
@Roxy-3D It happens with the rapid tool changes caused when the machine is not homed going into G29 P1. It does not occur if you are homed first. It does not occur if you are on T0 first. Only if you are on T1 and not homed. By changing the order so that you activate T0 before homing, you avoid calling tool change multiple times in a matter of milliseconds. 

The menu issue is separate, but should be pretty self explanatory there as well. You expect X2 to move, but X1 moves instead, while the position for X2 changes with it.

**Comment by silentninja1** [comment] 2018-07-24 19:42
@Roxy-3D https://github.com/MarlinFirmware/Marlin/pull/11329 This is what I did to get it to stop crashing as shown in the video for UBL G29 P1. Conditions are pretty specific to make it occur though. To be a little more specific, it calls the tool park to X2 position while moving the X1 stepper, causing it to try to go where X2 is sitting currently in that scenario. Possible a planner synch at the end of tool change as well could catch and prevent that? I can mess with it a little more but realistically a scenario calling tool change multiple times in a second should be avoided regardless.

**Comment by Roxy-3D** [comment] 2018-07-24 19:45
OK!    I'm comfortable merging #11329 even though I can't test it.     I'll make those same changes over in bugfix_2.0.0

**Comment by silentninja1** [comment] 2018-07-24 19:47
@Roxy-3D Sounds good. Did you look at #11328 at all? Thats the other scenario with the LCD. I did find depending on white spacing, if {} blocks worked better than #if #endif so I might just swap it to those quick. I found one scenario with all my echo lines that it landed on the wrong set of lines, probably from a typo putting it in and out lol

**Comment by Roxy-3D** [comment] 2018-07-24 19:52
No...  I haven't looked at that one...    But let me try to get the bugfix_2.0.0 version of the previous one compiling and merged.  Can you attach your configuration.h files ?

**Comment by silentninja1** [comment] 2018-07-24 20:14
@Roxy-3D 

[TM_TREXConfig_20180724.zip](https://github.com/MarlinFirmware/Marlin/files/2225213/TM_TREXConfig_20180724.zip)

Nothing too crazy fancy in this one

**Comment by Roxy-3D** [comment] 2018-07-24 20:27
Yeah...   But the problem is those are for 1.1.x    So I'm trying to cross over the changes 1 at a time to the bugfix_2.0.0 configuration.h files.    I'm not having good luck.

**Comment by silentninja1** [comment] 2018-07-24 20:31
@Roxy-3D That was on my plan for my next open weekend. Maker Faire here this weekend, sorry that wins over getting a 2.0 config! If I end up with some down time while im tuning a vision inspection system at a tier 1 supplier tomorrow, ill poke at it and see if I can get that finished. Build environment for 2.0 with platform io and atom is quite a bit different.

**Comment by Roxy-3D** [comment] 2018-07-24 20:32
Yeah... OK!    But I have the G29.cpp change in there.   And it might be compiling clean (for Dual Gantry Machines).

So...   At least the two code bases are synchronized.

> Build environment for 2.0 with platform io and atom is quite a bit different.

No!   You should be able to use Arduino on Bugfix_2.0.0 if you are building for an AVR platform!!!!

**Comment by silentninja1** [comment] 2018-07-25 14:27
@Roxy-3D I can, but editing is annoying since 1.9.0 beta doesnt show the whole folder tree. I can edit the config and compile without any problem though.

Scott pushed the other commit, so ill sync up a fresh copy without all my serial output statements all over and test it out again probably tomorrow. Im stuck on-site today and not near any machines.

**Comment by Roxy-3D** [comment] 2018-07-25 15:04
>  can, but editing is annoying since 1.9.0 beta doesn't show the whole folder tree. I can edit the config and compile without any problem though.

Yeah...   I guess it depends on how you do your work.   I only use Arduino to compile and link.   I use an external editor so that issue doesn't bother me.    Another 'cheat' I do is I have AstroGrep open and pointed to the top of source tree.    I can then search and find any reference to a particular item.   And from that, I can click on one of the found locations and it pops up a new editor at that location in the file (buried deep into the tree).

**Comment by silentninja1** [comment] 2018-07-25 15:55
I get annoyed switching between programs. One of these days I should see about getting eclipse configured for arduino... Been my editor of choice for a long time on other stuff and has git integration.

**Comment by silentninja1** [comment] 2018-07-25 16:08
BTW, Just noticed these couple questions : 

> Do both of the gantry's on that machine have a probe? 
No, just T0, left head

> But either way... right now, it looks like the probe_pt() function is moving the wrong gantry on your machine.

Probe pt always moved the right one, Only the tool change had the wrong one moving, and if you avoid that by either homing first or ensuring T0 was selected first, it always ran fine.

If you were working on off mesh compensation options, hopefully thatll make it in before I sit down for another round of testing. I dont mind messing with an early version of what youre working with if you want more feedback on it.

**Comment by Roxy-3D** [comment] 2018-07-25 18:47
It will take a while for any improvements to off mesh options.   Please don't wait for me!

**Comment by silentninja1** [comment] 2018-07-25 18:53
Progress waits for no man! Ill stare over your virtual shoulder till its done! Just kidding, I may focus attention on other things in the meantime. Need to circle back to some of the laser stuff I started awhile back, and I have a coreXY machine ive been working on. At a minimum ill verify a fresh clean build pulled from git with my config files works as intended before I move on so we can close this item.

**Comment by InsanityAutomation** [comment] 2018-07-26 01:18
Btw, Chris ran across more idex crash scenarios with just g28 and tool change commands. I lobbed a couple hail Mary fixes at him while I was at a customer site today, I'll be back in my office Friday with the Trex to track it down a bit more. Probably the root cause of the issue we avoided with the change in ubl_g29.h

**Comment by Roxy-3D** [comment] 2018-07-26 03:35
I sent Chris a message via Google Hangouts saying:

> Even a very small dual gantry printer would be very helpful to resolving issues.  And that would enable me to make necessary changes to the G26 code and G29 P4 code.   It is my belief it might be  beneficial to have a separate mesh for each extruder.

Currently, G26 (and for that matter G29 P1) only envision a single nozzle/bed mapping.   But obviously, that isn't accurate with multiple nozzles and especially with dual gantry machines.

If you want to hand off this issue...  I'll get it fixed ASAP if I have a test platform to code against.

**Comment by silentninja1** [comment] 2018-07-26 13:36
@Roxy-3D They ride on the same rail, just a parallel belt pulling them. If there was a separate probe, I could see another mesh, otherwise the common procedure is to set the 2 nozzle heights together with a single feeler gauge under both. The Trex uses chimera heat breaks on each side so they slide up and down.

I don't necessarily need to hand it off, but I wont complain if you get time first. My time in front of the machine is a bit limited for the next week. Id rather see you focus on the off mesh stuff since that's causing more user issues than this uncommon scenario.

Also, the trex is the only dual gantry machine Chris carries. He does have one in his shop which im sure you could take a look at if you had time to stop over one day.

**Comment by Roxy-3D** [comment] 2018-07-26 14:32
OK.   Good to know.

**Comment by silentninja1** [comment] 2018-07-27 18:29
@Roxy-3D Found it, ill have another pull request in shortly.

**Comment by silentninja1** [comment] 2018-07-27 19:02
@thinkyhead  @Roxy-3D in testing with a clean clone, found the newest bltouch commit ( #11358 ) is causing my machine to ram the nozzle into the bed and never deploy the probe. Im going to look into that as well while I get this pull request together, since I cant test it on a clean copy without fixing that first.

**Comment by silentninja1** [comment] 2018-07-27 19:26
@Roxy-3D @thinkyhead See pull request https://github.com/MarlinFirmware/Marlin/pull/11392

**Comment by silentninja1** [comment] 2018-07-27 20:02
Current also has another homing issue, where the bltouch probe is deployed and an extra raise is triggered, and it thinks its at 1.5mm when its really somewhere around 20mm. Ill dig into this one too.

**Comment by silentninja1** [comment] 2018-07-27 20:46
Fixed - see pull request #11393. Not sure what travis doesnt like is #11392 Let me know if you see an issue with it.

**Comment by Roxy-3D** [comment] 2018-07-27 21:24
It is unhappy about about x_home_pos() not being 'in scope'
```
sketch/Marlin_main.cpp: In function 'void tool_change(uint8_t, float, bool)':
Marlin_main.cpp:12012: error: 'x_home_pos' was not declared in this scope
         if(current_position[X_AXIS] != x_home_pos(active_extruder)){
                                                                  ^
exit status 1
```

**Comment by silentninja1** [comment] 2018-07-27 21:52
@Roxy-3D I moved it down to the dual x carriage conditional and added the original command in the else below it. Travis is happy now :)

**Comment by Roxy-3D** [comment] 2018-07-27 21:59
@silentninja1   We are trying to keep the bugfix_1.1.x branch and bugfix_2.0.0 branch in lock step...   Can you be troubled to make an identical Pull Request for bugfix_2.0.0 ?     And I'll merge them at the same time.

**Comment by silentninja1** [comment] 2018-07-27 22:02
Yeah, should I put all of the ones I just did into a single pull req for 2.0?

**Comment by Roxy-3D** [comment] 2018-07-27 22:07
Yes...    Pretty much, the logic will be identical.    But because of the hierarchical file layout of bugfix_2.0.0, declarations and such may end up being a little bit different.

**Comment by silentninja1** [comment] 2018-07-27 22:29
@Roxy-3D #11395 - travis is checking it now,

**Comment by InsanityAutomation** [comment] 2018-07-28 01:56
@Roxy-3D gmagician pushed a more thorough change for the bltouch homing issue. I'll get a pair of commits with just the idex issue setup tomorrow.

**Comment by silentninja1** [comment] 2018-07-28 02:47
@Roxy-3D Ended up back on my laptop tonight, so I modified #11392 and #11395 to have just the idex fix.

**Comment by Roxy-3D** [comment] 2018-07-28 05:02
Thank You!   I'll review them in the morning.

**Comment by InsanityAutomation** [comment] 2018-07-29 14:39
@Roxy-3d perhaps if that caused some issue with a different machine, maybe we can check if active extruder position plus tool clearance is beyond the soft limit. In that case we know a move can't occur. Do you know which machines had an issue and I can look at how they x carriages are designed?

**Comment by InsanityAutomation** [comment] 2018-07-29 14:49
@Roxy-3D other option if they actually park in the same position and don't need an offset, aside from offset being 0, would be a config option for extruder can park overlapping to use the old functionality. Either way, need some kind of an idea what problem it causes on what machine because it crashes pretty violently on formbot machines as is.

**Comment by Roxy-3D** [comment] 2018-07-29 15:26
Let me get some more information.   But immediately after the merge, messages came in from two different places.     It is starting to 'feel' to me like we would benefit from having an IDEX Reference Platform for Marlin.

**Comment by silentninja1** [comment] 2018-07-30 01:11
@Roxy-3D Can you run this suggestion by them : 

We currently have : 
  #define X2_MIN_POS    
  #define X2_MAX_POS

I can add the same for X1 and enforce them in the tool change command. If that wont cause a problem for them, it should be pretty universally configurable.

**Comment by Roxy-3D** [comment] 2018-07-30 03:53
Will do....       

Thank You for thinking about this!

**Comment by Roxy-3D** [comment] 2018-07-30 18:53
@silentninja1    

> I can add the same for X1 and enforce them in the tool change command. If that wont cause a problem for them, it should be pretty universally configurable.

I think this will 'fix' things...   Can we give that a try?

**Comment by InsanityAutomation** [comment] 2018-07-30 18:58
Yep I should have time to sit down and write that if not tonight, tomorrow sometime. The root functionality should be pretty simple but we may also want to take it a step further and look at soft and stops and overwrite those based on active tool as well.

**Comment by InsanityAutomation** [comment] 2018-07-31 14:30
Since the 1.1 branch is now closed, it'll take me another day or two to get a working configuration for 2. 0 on my machine here to actually test what I'm putting in. I have the stuff for the tool change script done, I finished that last night for the 1.1 branch, and was planning to get the soft stop stuff pieced together today, but since that's not going to get into 1. 1 I'll just leave it and move to 2. 0 before I continue.

**Comment by Roxy-3D** [comment] 2018-07-31 15:03
Bug fixes can still be done to 1.1.   Let's focus on 2.0.0.    But if the changes are easy to understand and low risk...   they can still be put into 1.1.

**Comment by InsanityAutomation** [comment] 2018-07-31 15:12
Yeah nothing here is going to be crazy LOL all pretty simple. I've got the code in where it works, just need to get this off stops enforced on tool change then add the new configuration options into the sanity check logic. if you want I can put in a pull request when I get to sit back down in front of my laptop with just the bare bones functioning part of it to have those two manufacturers review if it causes issues for them still then add in the rest of the stuff to make it complete if they agree with the function.

**Comment by Roxy-3D** [comment] 2018-07-31 15:42
Let's not make extra work for ourselves.    Just get it polished and tested...   And we can ask people to test and comment at that point.

**Comment by silentninja1** [comment] 2018-08-01 14:40
@Roxy-3D Was stuck working late last night on the day job, but tested and working this morning. For the sanity checks, I set it to use safe values from the machine limits and bed size as a default if not defined rather than error out. Can change that if youd prefer it to be explicitly set.

**Comment by silentninja1** [comment] 2018-08-01 15:52
@Roxy-3D And travis is all happy, if you can forward this along we can make sure it works for all parties then ill get it moved over to 2.0 before merging.

**Comment by Roxy-3D** [comment] 2018-08-01 16:44
I've asked all concerned parties to check it out...    In a day or two...   We can go add those extra #define's to the example configuration.h files if there aren't any complaints.

**Comment by InsanityAutomation** [comment] 2018-08-01 16:54
Sounds like a plan. If it's good with all parties I'll plan to do that at the same time I get a 2.0 pull request together with this. if it's not good then I suppose we'll need a bit more detail on what they're trying to do because in that case it's highly likely they're trying to do something differently then dual-x Carriage was intended to and may need a different mode option to differentiate the design. I would definitely need more information to take it farther in that case.

**Comment by Roxy-3D** [comment] 2018-08-03 19:48
No complaints with the current code.    I'm not sure how extensively it was tested.  (I suspect the testing was fairly light...  but still, they said OK)    I think we are ready to add these lines to all the configuration files and merge...
```
  #define X1_MIN_POS X_MIN_POS     // set minimum to ensure first x-carriage doesn't hit the parked second X-carriage
  #define X1_MAX_POS X_BED_SIZE    // set maximum to ensure first x-carriage doesn't hit the parked second X-carriage
```

**Comment by silentninja1** [comment] 2018-08-04 02:00
@thinkyhead Thanks for wrapping this up and getting the 2.0 version done! That opens up what I have of the weekend outside the day job to get these builds up to 2.0 and try to test for #11330 and #10749 - the first should be easy to prove / disprove and find. May also be poor backlash compensation.

**Closed as completed** 2018-08-07 18:40 UTC
