### ISSUE TITLE
[BUG] Status text not shown on Ender 3 V2 DWIN MarlinUI

### ISSUE THREAD

**Issue by The-EG** [MarlinFirmware/Marlin#23988] opened 2022-04-02 12:54 UTC
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

The status text is no longer shown on the status screen when using a genuine 'DWIN' screen shipped with the Ender 3 v2 using MarlinUI. When the status changes, it flashes briefly and then disappears. The status screen also flickers a bit.

### Bug Timeline

49539463b8ed8b15286014b122f87962b7c0f6f4 from #23949

### Expected behavior

The status text to be shown properly

### Actual behavior

The status text is no longer shown on the status screen when using a genuine 'DWIN' screen shipped with the Ender 3 v2 using MarlinUI. When the status changes, it flashes briefly and then disappears. The status screen also flickers a bit.

Reverting 49539463b8ed8b15286014b122f87962b7c0f6f4 results in expected behavior and no flickering.

### Steps to Reproduce

1. Use appropriate MarlinUI config on an ender 3 v2 with a genuine DWIN LCD with encoder.
2. Flash
3. Boot up
4. Observe status screen
5. (Optional) Send additional status messages, note not shown on LCD

### Version of Marlin Firmware

Bugfix-2.0.x as of 2022-04-02 (d98c61cafba1df39316f90af21b99d6c7183f58c)

### Printer model

Ender 3 v2

### Electronics

4.2.2 board, DWIN LCD

### Bed Leveling

UBL Bilinear mesh

### Additional information & file uploads

[ender3v2.zip](https://github.com/MarlinFirmware/Marlin/files/8402531/ender3v2.zip)

**Comment by tome9111991** [comment] 2022-04-02 13:32
I have same issue.

And also
Always refreshing/blinking text  if i'm scrolling.
https://youtube.com/shorts/iNm_I5J0zCc?feature=share

I use skr e3 turbo board 
With latest bugfix verson from now.


EDIT:
I can confirm issue is gone after revert https://github.com/MarlinFirmware/Marlin/commit/49539463b8ed8b15286014b122f87962b7c0f6f4

**Comment by thisiskeithb** [comment] 2022-04-03 01:50
@InsanityAutomation: Do you have an (original) DWIN screen and can you take a look at this? Your Ender-3 S1 PR seems have broken some things https://github.com/MarlinFirmware/Marlin/pull/23949

**Comment by thisiskeithb** [comment] 2022-04-05 02:44
> Always refreshing/blinking text if i'm scrolling.

I pinged InsanityAutomation on Discord and he confirmed the UI/screen flashing bug, but couldn't reproduce the status missing text screen bug.

Do these screens have revisions printed on them by chance? Perhaps it's a difference of hardware/DWIN features.

**Comment by thisiskeithb** [comment] 2022-04-06 19:28
@The-EG: Can you upload a video showing the status screen bug?

> Do these screens have revisions printed on them by chance?

To answer my own question, I found my E3V2 DWIN screen and couldn’t find any real markings to indicate board revisions. I’ve been busy IRL, but still plan to test this on my end.

**Comment by tome9111991** [comment] 2022-04-06 21:02
If i insert a SD card  i see the message "SD insert" for 1 sec then is status text clean.

Before the bug
I insert a SD card and i can the the message "SD insert" all the time.

**Comment by The-EG** [comment] 2022-04-07 05:09
2 videos, current bugfix and with 49539463b8ed8b15286014b122f87962b7c0f6f4 reverted:
 - turned printer on
 - waited for boot up
 - inserted SD card
 - removed SD card

_Current bugfix behavior_:
https://youtu.be/mOol4y_RkEc
![image](https://user-images.githubusercontent.com/7342077/162124414-4814656c-5073-4217-8f0d-706ec83f67f2.png)

It's worth pointing out: either I didn't notice how bad this was before or it's gotten worse in the past few days. Not only is the status text missing, some other parts of the status screen are too. Even the images shown during bootup are different.

_After reverting 49539463b8ed8b15286014b122f87962b7c0f6f4_:
https://youtu.be/O7h0h0sIxSE
![image](https://user-images.githubusercontent.com/7342077/162124494-8d1cb5f7-4d2c-4a4a-b038-3ddc5e1655db.png)

**Comment by tititopher68-dev** [comment] 2022-04-07 08:12
To fix in https://github.com/MarlinFirmware/Marlin/commit/49539463b8ed8b15286014b122f87962b7c0f6f4
Remove all `DWIN_UpdateLCD();` in PR.

**Comment by thisiskeithb** [comment] 2022-04-07 08:24
> To fix in [4953946](https://github.com/MarlinFirmware/Marlin/commit/49539463b8ed8b15286014b122f87962b7c0f6f4) Remove all `DWIN_UpdateLCD();` in PR.

I assume that'll break non-DWIN screens. @InsanityAutomation can you test this fix on your end?

**Comment by InsanityAutomation** [comment] 2022-04-07 14:20
I'll probably have some more tweaks this weekend. They're not all required, some were insurance. Looks like the above may be triggered if status scrolling is disabled, so enabling that is a workaround for the moment.

**Comment by thisiskeithb** [comment] 2022-04-09 21:34
This should be fixed in https://github.com/MarlinFirmware/Marlin/pull/24013

**Closed as completed by thisiskeithb** 2022-04-09 21:34 UTC
Labels: Bug: Confirmed !, C: LCD & Controllers, Fix Included

**Comment by The-EG** [comment] 2022-04-23 12:09
Sorry for the delay, #24013 does fix this issue.

**Comment by tome9111991** [comment] 2022-04-29 12:11
i can confirm fix works good.

only have in some menus kind of color overlay.

![IMG_20220429_140357_1](https://user-images.githubusercontent.com/57866234/165942888-fdbb106d-f1ed-4e23-bade-0fdbd25176e0.jpg)


![IMG_20220429_141507_1_1](https://user-images.githubusercontent.com/57866234/165942810-06948c33-b72e-491a-a10e-27edf582a98d.jpg)
