### ISSUE TITLE
Request: language settings in menu

### ISSUE THREAD

**Issue by lcfm1** [MarlinFirmware/Marlin#1855] opened 2015-04-08 03:42 UTC

**Comment by thinkyhead** [comment] 2015-04-08 03:56
Duplicate of #1140. [search]

**Comment by AnHardt** [comment] 2015-04-08 08:05
Too complicated & too expensive.

I will not do it. At least, not in the near future.

**Comment by boelle** [comment] 2015-06-29 11:47
since its a dublicate of #1140 i will close it

**Closed as completed by boelle** 2015-06-29 11:47 UTC
Labels: T: Feature Request, C: Language
