### ISSUE TITLE
LCD does not scroll on sd card menu, SD dectect enabled

### ISSUE THREAD

**Issue by kjdkeller** [MarlinFirmware/Marlin#4508] opened 2016-08-02 21:11 UTC
This is my 3rd Marlin install on this Cartesian printer the last was marlin rc6 bug fix.  Never had this issue.  All the lcd menus scroll up and down ok except the sd card menu.  I can see the files, I just cant scroll down to select them.  I am using the rep rap discount full graphic smart controller, on a rumba board.

I also loaded this rc7 to a delta printer with a reprap discount smart controller and the sd menu works fine.

**Comment by thinkyhead** [comment] 2016-08-03 03:05
@kjdkeller I revamped the menu code today, and it's now merged into `RCBugFix`. Can you check to see if the SD files now scroll properly? The changes seem to have fixed all scrolling issues for me.

**Comment by kjdkeller** [comment] 2016-08-03 23:05
Hi, thanks for that.  I loaded the newest bugfix, it works now.  However, the SD menu scrolls slowly like it's delayed compared to the other menus.  It is working though.  Thanks.

**Comment by Blue-Marlin** [comment] 2016-08-04 00:13
We can't buffer the complete directory (that could be some thousand bytes, we don't have). We do only store the index to a directory entry. For every directory entry we have to scan the the complete directory up to this file or its follower. Even deleted directory entries have to be read.
If you have only a few directory entries it's much faster then if you have a lot. 
Formatting your sd-card may help.
**Edited**

**Comment by thinkyhead** [comment] 2016-08-04 01:00
> We can't buffer the complete directory

This is true. I have experimented with caching the sort order in https://github.com/thinkyhead/Marlin/tree/sd_alpha_sort and it includes some options to cache the listing (if you happen to have enough extra RAM) which do speed up the display. But since it uses dynamic memory allocation, it cannot be included in release versions of Marlin.

**Comment by boelle** [comment] 2016-08-11 09:54
So this is not a bug as such? can we close this one?

**Comment by thinkyhead** [comment] 2016-08-11 20:00
@kjdkeller A "low-level format" of the SD card is known to have helped with read/write issues. Try that, or another SD card, and see if the speed improves.

**Comment by kjdkeller** [comment] 2016-08-11 23:52
The issue is resolved with the SD card scrolling. I think it's okay to close the issue.

**Closed as completed** 2016-08-12 09:39 UTC
Labels: Bug: Potential ?
