### ISSUE TITLE
Malyan M200 Impossible to build?

### ISSUE THREAD

**Issue by kajsilander78** [MarlinFirmware/Marlin#11688] opened 2018-08-31 22:01 UTC
Hi!
Found out the Malyan M200 should work with Marlin. I downloaded the newest 2.xx.xx build and 
try to build it.... I've tried to find solution to get it to build. Could someone please write steps
to get it to build? Or is it in none working condition for now? Tried all day to download diffrent recommendations and changed settings in config files but have no luck. All the other boards build fine.

/Kaj

**Comment by thinkyhead** [comment] 2018-09-01 00:27
Duplicate of #11594

**Comment by thinkyhead** [comment] 2018-09-01 00:28
…and see https://github.com/MarlinFirmware/Marlin/issues/11104#issuecomment-400078289

**Closed as completed by thinkyhead** 2018-09-01 00:27 UTC
