### ISSUE TITLE
[FR] Accommodate for skipped steps with StallGuard

### ISSUE THREAD

**Issue by Sjoerd** [MarlinFirmware/Marlin#17849] opened 2020-05-03 14:31 UTC
### Description
Because more and more 3D printers have "smart" stepper drivers (TMC21xx and TMC22xx), it would be nice to adopt @prusa3d's auto rehome function on a loose step or when you hand is stuk in the printer.

### Feature Workflow

1. Start a print
2. Get your hand stuk in the printer
3. Printer should rehome

#### Additional Information
Check this video: https://www.youtube.com/watch?v=TCw8G16Z63E

I may have some time to create a pull request for it, if not I would like to see it implemented anyway :wink:

**Comment by thinkyhead** [comment] 2020-05-05 05:19
Duplicate of #8765

**Closed as completed by thinkyhead** 2020-05-05 05:19 UTC
