### ISSUE TITLE
While is printing, the Extruder unload the material!?!??!!?

### ISSUE THREAD

**Issue by fbarcenas** [MarlinFirmware/Marlin#3368] opened 2016-04-04 06:44 UTC
This is very rare...
After work some hours and all is very well, the Extruder 0 move around -100 aprox and the filament go out and continue working....
Of course continue working in the air, because the filament is totally unload...

Also before of this, the X axis moves to search the Sensor home X-, move to X- and after return to work...

Some idea?

**Comment by jbrazio** [comment] 2016-04-04 11:01
Could you please post the g-code (as an attachment) where you saw this happening ?

**Comment by fbarcenas** [comment] 2016-04-04 11:46
[Fan.gcode.zip](https://github.com/MarlinFirmware/Marlin/files/202317/Fan.gcode.zip)

This happen also with another files.

**Comment by jbrazio** [comment] 2016-04-04 12:47
Do you have more or less an indication of when it fails, i.e. they all fail around the same print time ?
Do you have multiple extruders ?

**Comment by fbarcenas** [comment] 2016-04-04 13:02
Not.
For say something, maybe in 20%-30% but a thing is sure, ALWAYS before of this:
The axi X move in X- to sensor Home and after return to continue working, some lines after the extruder unload material and after continue working....

**Comment by fbarcenas** [comment] 2016-04-04 14:02
Sorry, i don't answer well.

> they all fail around the same print time ?
> Not.
> For say something, maybe in 20%-30% but a thing is sure,
> 
> Do you have multiple extruders ?
> yes, two. But in this jobs only use the first

**Comment by jbrazio** [comment] 2016-04-04 14:12
I understood.
Did you tried any other slicer ? I just would like to remove the slicer from the equation.

**Comment by fbarcenas** [comment] 2016-04-04 14:41
I will try another slicer, Cura and i say you comments
I am also having another problem
(Maybe is better do another new Issues ticket?)

In the Display VIKI2, when i go to menu to move the extruder, i move the extruder yes in positive and negative correctly, but i can't go exit the menu!, 
Normally i press the button and i go out the menu.... now i must wait the seconds to go automatically to first menu...

**Comment by jbrazio** [comment] 2016-04-04 14:42
> In the Display VIKI2, when i go to menu to move the extruder, i move the extruder yes in positive and negative correctly, but i can't go exit the menu!, 
> Normally i press the button and i go out the menu.... now i must wait the seconds to go automatically to first menu...

Please open another ticket for his issue.

**Comment by fbarcenas** [comment] 2016-04-05 21:31
Today happen me again... this time in a file than use the 1 and 2 extruder, while use the 2 extruder, the machine unload the material...

Some idea???

**Comment by thinkyhead** [comment] 2016-04-05 22:38
Are you printing from a host like Octoprint or Repetier over USB? Do you see the same results if you print directly from SD card?

I have seen behaviors like this due to communication problems. Try configuring the `BAUDRATE` to 115200 instead of 250000, or even slower if you still see problems.

**Comment by fbarcenas** [comment] 2016-04-06 04:19
This problem happen me in 2 machines diferently, with boards diferently
But
Always from sd card.
I never use usb or octorpint

Maybe i can do some change with sdcard?

**Comment by fbarcenas** [comment] 2016-04-06 04:48
A question: in that format must have the sd card?
Exfat?
Fat32?
Fat?

**Comment by jbrazio** [comment] 2016-04-07 10:01
FAT32 or FAT, they will both work, but using FAT you can only have 8.3 filenames.

**Comment by jbrazio** [comment] 2016-04-07 10:03
We had in the past couple of weeks at least two issues that were solved by using a fresh new SDCard, you could also try that if after formatting the old one and see if the same behavior appears.

**Comment by fbarcenas** [comment] 2016-04-07 12:04
Actually i use Transcend and Sandisk in FAT32...

**Comment by jbrazio** [comment] 2016-04-07 12:10
Did you already try re-formatting (full) them ?

**Comment by fbarcenas** [comment] 2016-04-07 12:19
Yes,
moreover in severals PCs

**Comment by thinkyhead** [comment] 2016-04-07 23:18
This problem has also happened on my machine due to a loose connection between the SD Card / LCD Controller unit and the RAMPS board. Is your SD Card directly on the electronics board, or is it in a separate unit? If it is separate, make sure that the plugs are nice and tight. It may even help to bend the pins a little and re-plug-in the unit.

**Comment by fbarcenas** [comment] 2016-04-08 11:21
The most rare thing is than happen me in two machines different, with wires different, SD cards deferents, boards differents...

Regard to the question, is in separate unit, display VIKI2.

By the way i will recheck everything.

**Comment by thinkyhead** [comment] 2016-04-09 20:40
I don't want to presume that it's your hardware, but so far I haven't seen this behavior with recent code updates. On the other hand, the longest prints I have tested are only 20-30 minutes.

One pretty sure way to find out is to start a print (just a simple one, maybe even remove your filament for the test) and while it's in progress, wiggle the wires of your LCD controller. If "weird things" happen when you do this, it's a clear indication of a connection issue.

**Comment by fbarcenas** [comment] 2016-04-09 22:11
i use the SD slot than have directly the board and also fail, is very rare, the "unload material" not happen around some days, but than the axi Y search the home yes...

**Comment by thinkyhead** [comment] 2016-04-10 01:15
This "axis Y search the home" you refer to is not a case of Marlin interrupting your print job to search for home position. It is an error in evaluating the GCode that I have seen before — when there are connection issues — that causes a strange movement. When I have seen this, there is a slow movement towards an edge, and then back over to the print, and then the print continues normally.

I think you may have some electronic noise issue going on with your board. Are you able to improve grounding and isolation?

**Comment by fbarcenas** [comment] 2016-04-10 11:49
I see is than always happen in the first or second layer...
But is very rare than happen in the >RC3 version, in the last never happen!!
From Rc3 version some change than can affect to this?

Today i have a new and super Transcend miniSD card, i am testing...

What brands use yours?

Maybe some brands work wrong!?

Regard to the electronic noise and isolation i think than not, and i can have in one machine, but in two machines totally differently?

**Comment by thinkyhead** [comment] 2016-04-11 01:47
Well I suppose it's possible that you are seeing something that is both logically wrong and spurious, but these kinds of bugs will usually show up for a lot of users.

Ideally, the code of Marlin is totally "deterministic." That is, Marlin should do exactly the same thing every time you run the same GCode file. If it does not, then there has to be some random factor being introduced.

It would be helpful if you were able to do some diagnostics and narrow down and isolate the conditions required to produce the error.

In the meantime, which version of Arduino are you using to build Marlin?

**Comment by fbarcenas** [comment] 2016-04-11 06:44
1.6.8, but i go to install 1.6.7.
Because with 1.6.7 i remember than not have this problems, maybe not have importance...
With the new sdCard transcend also fail, this time stop the bed heat... is like read a commando M140 S0.
I check the file and not have M140 S0.

**Comment by thinkyhead** [comment] 2016-04-12 01:00
I look forward to seeing more test results.

**Comment by fbarcenas** [comment] 2016-04-12 19:16
Today more info.
WITH the last RCBUGFIX in this moment.
1.6.7->Work File perfectly, not do movements rates the printer BUT the LCD display CRASH and the machine STOP
1.6.8->The display not crash, but the machine search the home...unload material....

I am talking in works of many hours...happen in the firstly 2-3hours

**Comment by jbrazio** [comment] 2016-04-13 23:49
@fbarcenas sorry to bother you.. could you try with 1.6.0 ? To see if the behavior is a new third one or matches one of the existing.

**Comment by thinkyhead** [comment] 2016-04-14 01:43
@fbarcenas We need more data-points to make any assessment. Two is not enough.

I'd like to try to eliminate or isolate the possibility that electronic noise or SD reading functions are involved. Can you try disconnecting the display and controller and printing over USB to see if any of these same issues occur? Also, when you print from SD Card with the LCD controller attached, try wiggling the wires and see if any of these behaviors occur.

**Comment by fbarcenas** [comment] 2016-04-19 14:44
This days i am really confused, i continue testing and fail when the system want...
i found exactly when happen!!!!!
at first i think than is version of arduino, sd card brand, wires.... but not...!

I explain:
 i do a file than have a lot CIRCLES, when do this CIRCLES the marlin search home X or home Y.
is horrible, each 2-3 circles search a home position!!
i attach file.
And ALWAYS HAPPEN in the FIRST layer

Happen with SDCARD and USB

Unload material not happen
Tested with 18 april RCBUGFIX and arduino 1.6.0, 1.6.8,1.6.7

Ideas?
[11198-01.gcode.zip](https://github.com/MarlinFirmware/Marlin/files/226106/11198-01.gcode.zip)

**Comment by a-sprenger** [comment] 2016-04-19 19:49
I believe I have the same problem.
After nearly 2/3 of the job, the extruder stops extruding. I don't know if it's unloading the filament, but all other axes are working until the job has been finished!

I changed the nozzles, the filament (different ABS materials), but nothing helps.

Attached pictures:
![wp_20160419_21_35_36_rich](https://cloud.githubusercontent.com/assets/18560272/14653172/03fee89a-0678-11e6-8b31-8587759acb64.jpg)
![wp_20160419_21_35_45_rich](https://cloud.githubusercontent.com/assets/18560272/14653173/04152fb0-0678-11e6-906e-c31d9bf971a5.jpg)

The good extruder carriage has been printed with my mendel (Filament and print settings are the same).
The bad one with my Prusa with RC5. The heart, too

Slic3r. honeycomb 3D, different heights(0.1/0.2mm), different infills(40/20%), Octoprint

**Comment by fbarcenas** [comment] 2016-04-19 19:53
a question.

What name you put to the file?.
Please say exactly the name, exactly letter to letter and mayus

**Comment by a-sprenger** [comment] 2016-04-19 20:47
WP_20160419_21_35_36_Rich.jpg
WP_20160419_21_35_45_Rich.jpg

both attached in a zip-file
[pictures.zip](https://github.com/MarlinFirmware/Marlin/files/226799/pictures.zip)

**Comment by fbarcenas** [comment] 2016-04-19 21:33
The name of the file gcode i want say, the file name than you send to Octoprint.

Thanks bye

**Comment by thinkyhead** [comment] 2016-04-20 02:10
I will test my own printer with your GCode later on and see what happens. If it exhibits similar issues, maybe I can isolate a cause.

**Comment by a-sprenger** [comment] 2016-04-20 09:18
Yesterday evening, my daughter told me, that she and her girlfriends like it to play with the different coloured "plastic". I'm not sure if that is the reason!
Yesterday evening I got the same problem with the old firmware!

I have to clean the nozzles and take new filament!

**Comment by fbarcenas** [comment] 2016-04-20 10:00
I do a new test....
SAME FILE, i change file name from "11198-01.gcode" to "Test.gcode" and... FAIL
i change to "fail.gcode" (all minus) and NOT FAIL

I am totally confused, problem of circles or with the name?!?!?!?!

**Comment by thinkyhead** [comment] 2016-04-21 01:36
@fbarcenas We had a problem in the past with numbers in filenames, and it's fixed now, so it's weird to see the "opposite problem" where a filename with numbers works, but a filename without them doesn't.

So it's also strange that `Test.gcode` fails while `fail.gcode` doesn't fail. Marlin doesn't see the mixed-case filename, only the DOS 8.3 filename.

Are you certain that your SD Card and your SD Card Reader are actually okay? Is the card formatted with FAT32 format? Are you able to test using a different SD Card and see if the results are the same?

It would help if, before you do any printing or testing, you could connect a console and gather all the output from Marlin so we can see what commands it's issuing. Maybe the `M23` command is mangled, or something else weird is happening.

You can use the `M111 S1` command to enable logging of every command that goes into the buffer.

**Comment by thinkyhead** [comment] 2016-04-21 03:55
@a-sprenger

Since your model is extremely large I was unable to test it on my system. The GCode is over a million lines long, and the object is arranged from around X=300 to around X=900 on the build plate. I tried just running in "Dry Run" mode, which skips all E moves and leaves the heaters off. Of course, this will conceal any problem that might exist with the E axis, but the math with E going forward is probably okay because E is reset to zero for every new set of moves.

Since this file uses `G92` a lot, I decided to do a little cleanup on the `gcode_G92` function. I did have to make a small change to prevent the E axis being synchronized with the planner more than once in some cases. I don't think this minor issue in `G92` is contributing to the problem you are seeing, so don't expect anything new after I merge that change.

We're also looking at a potential acceleration bug right now, so something we figure out there might help... #3520

**Comment by fbarcenas** [comment] 2016-04-21 06:49
I don't explain very well:
Filenames:
11198-01.gcode     FAIL
Test.gcode             FAIL
test.gcode              NOT FAIL

Tested with USB wire and different sdcards
I go to read around M111 because i don't use this never

**Comment by thinkyhead** [comment] 2016-04-21 21:28
> Tested with USB wire and different sdcards

So when you say "fail" in what way do they fail? Do they never start to print? Or does the printer quit extruding in the middle of the print?

**Comment by fbarcenas** [comment] 2016-04-21 21:41
When i say fail i want say than the machine do rare things.
Time before the rare things are: unloading material, but now the fails is always the same, the machine search home X or Y

The fail of unload material you fix in some rcbugfix version i think (maybe without you know than are fixing this...)

**Comment by fbarcenas** [comment] 2016-04-21 21:42
if the filename have a mayus or numbers, the work fail (home search X or/and Y) sure!

**Comment by thinkyhead** [comment] 2016-04-21 22:04
> if the filename have a mayus or numbers, the work fail

Well then we should look at what's going into the command buffer. Please use the `M111 S1` command to enable logging of every command that goes into the buffer, connect Pronterface, and try printing from SD as usual, then watch the output for strange things. Paste the output here if you're not sure.

**Comment by fbarcenas** [comment] 2016-05-01 15:41
Sorry for the delay, still i dont test the command M111, i will test tomorrow.
But witj the last version the marlin RESTART,
Like if you press reset button...

**Comment by thinkyhead** [comment] 2016-05-02 03:35
Looking forward to the results of your testing.

**Comment by fbarcenas** [comment] 2016-05-03 14:37
Sorry i don't understand Pronterface... 
What software i can use for log the and save the log in a file?

**Comment by thinkyhead** [comment] 2016-05-03 18:38
@fbarcenas After Pronterface (or other host) is connected, all messages from Marlin appear in its "console" region. You can use copy-and-paste as-usual to copy that text and paste it into another file, or into the browser edit field. You don't need me to explain copy-and-paste, I hope!

**Comment by fbarcenas** [comment] 2016-05-03 19:17
i am user of simplify3d and when i use pronterface i don't see like connect to the printer, i can't change the port COM... i know like do, but not work .(
For this i ask if is possible use another softs?
You know another softs?

**Comment by thinkyhead** [comment] 2016-05-03 21:29
@fbarcenas If you can't get a serial connection to your printer, there must be something wrong with your printer. You should be able to connect any host software without a problem. You can try: Cura, Repetier Host, Pronterface, and Octoprint (runs on Raspberry Pi). They should all be able to connect.

Make sure you select the correct BAUD rate, which is probably 115200 or 250000. Your printer should show up on one of the ports in Pronterface (or other host) as soon as you connect the USB cable. You may need to connect the printer first, then start the host software.

**Comment by fbarcenas** [comment] 2016-05-03 21:35
Yes yes i know like use this,
i use octoprint, cura and repetier and everything is ok, but Pronterface not work well, i am thinking than my pc windows 10 is the problem.

By the way i am printing now things and everything is ok...
But i do a change, i disable SDsupport and disable my display viki2

**Comment by a-sprenger** [comment] 2016-05-03 21:35
Hi,
well, I have no problems here. The stepper motor was damaged and the filament full of candy (from my kids). When the stepper motor became a little bit warmer it stopped totally!

**Comment by thinkyhead** [comment] 2016-05-03 21:41
@fbarcenas Ok, the only reason I brought up "Pronterface" at all was just as a suggestion, a way to get the output from Marlin. If your other host software is working, then you can use that for the same purpose. It doesn't matter which one.

**Comment by Roxy-3D** [comment] 2016-05-03 21:41
Also, make sure you don't have anything else connected to the printer.   This is the opposite problem you are having but I was banging my head on the table because I couldn't get Arduino to update the firmware on my printer yesterday.   The reason was because I had PronterFace connected to the printer.

**Comment by fbarcenas** [comment] 2016-05-04 14:05
Continue testing...
Disable SDCARD and VIKI2 lines...everything is ok...

**Comment by fbarcenas** [comment] 2016-05-04 14:41
Hello!
The problem happen and i have the log!!
The fail happen when:
RECEIVED: echo:busy: processing

Importance to: WARNING: Firmware unresponsive.  Attempting to force continue...
after of this axi X go to search HOME but crash and crash.... like the sensor not work.... after i turn off the machine...
[Fail1.txt](https://github.com/MarlinFirmware/Marlin/files/248942/Fail1.txt)

**Comment by thinkyhead** [comment] 2016-05-05 02:47
@fbarcenas You can disable the busy feedback with `M113 S0` or by enabling `DISABLE_HOST_KEEPALIVE` if it's bothersome or causing additional problems.

Checking through the log…

**Comment by fbarcenas** [comment] 2016-05-05 07:33
So Now at the first of each file i write:

``` gcode
M111 S1           ; activate logging
M113 S0           ; deactivate busy messages
```

i will say something....

**Comment by fbarcenas** [comment] 2016-05-06 07:02
Hi again, the problem happen but happen some hours before and the log don't save this...
The machine is working in another placement and the bed and hotend is cool!!

Only save some lines and i don't find.
But, why if i put: M113 S0 at start work, the machine continue say: busy: processing
????

Now, I upload the new rcbugfix with DISABLE_HOST_KEEPALIVE

A idea...?
is possible than the problem will be the 250000 baud rate?? i never touch this
Is a PC with windows 10

**Comment by thinkyhead** [comment] 2016-05-06 20:21
`M113` is pretty new. You might find it actually works with the latest bug fix code. But I will peek at it to make sure it's doing the right thing.

**Comment by thinkyhead** [comment] 2016-05-06 20:24
I can't pinpoint the source of your error, so far. I don't think it is code-related. So I recommend that you try a slower baud rate and see what happens. In fact, keep trying everything and see what effects you get. Keep reporting results, and eventually, perhaps, it will crystallize.

**Comment by fbarcenas** [comment] 2016-05-06 20:34
What baudrate you advise me?

**Comment by fbarcenas** [comment] 2016-05-07 08:35
Actually i have 250000, i don't know if is the standard or not... All people use this.
By the way, i upload the last RCBUGFIX but with DISABLE_HOST_KEEPALIVE and i send the same file.... for the moment not fail...

**Comment by fbarcenas** [comment] 2016-05-07 19:21
Someone know a software than can save the log in a file?
My problem is than the problem happen in the middle of the night so when i return to see the machine the problem happen but the log is delete, the log of simplify3D only save some last lines, and i can't find exactly the error...

**Comment by fbarcenas** [comment] 2016-05-10 11:50
More info:
with 115200 also fail. Tested with `RUMBA` and `MEGATRONICS`
`DISABLE_HOST_KEEPALIVE` is written and now the problem is
"Cold prevented extrusion"

idea?

Why turn off the machine the hotend??
What security have the firmware than can turn off this?? I have merman runway disable

**Comment by Blue-Marlin** [comment] 2016-05-10 17:45
PREVENT_DANGEROUS_EXTRUDE

**Comment by fbarcenas** [comment] 2016-05-10 18:43
disable and testing....

``` cpp
//this prevents dangerous Extruder moves, i.e. if the temperature is under the limit
//can be software-disabled for whatever purposes by
//#define PREVENT_DANGEROUS_EXTRUDE
//if PREVENT_DANGEROUS_EXTRUDE is on, you can still disable (uncomment) very long bits of extrusion separately.
//#define PREVENT_LENGTHY_EXTRUDE

//#define EXTRUDE_MINTEMP 170
//#define EXTRUDE_MAXLENGTH (X_MAX_LENGTH+Y_MAX_LENGTH) //prevent extrusion of very large distances.
```

and also:

``` cpp
// The hardware watchdog should reset the microcontroller disabling all outputs, in case the firmware gets stuck and doesn't do temperature regulation.
//#define USE_WATCHDOG
```

**Comment by fbarcenas** [comment] 2016-05-11 12:08
News:
With all this:

``` cpp
//#define PREVENT_DANGEROUS_EXTRUDE
//#define PREVENT_LENGTHY_EXTRUDE
//#define EXTRUDE_MINTEMP 170
//#define EXTRUDE_MAXLENGTH (X_MAX_LENGTH+Y_MAX_LENGTH) 
//#define USE_WATCHDOG
```

and use software Repetier instead of simplify3D, WORK!!!!!

Now.. i don't know where is the problem!
Ideas?
Can be the software???? Different config???:
I attach
<img width="764" alt="captura de pantalla 2016-05-11 a las 14 05 46" src="https://cloud.githubusercontent.com/assets/16296472/15180405/b9564be2-1781-11e6-9f79-a9d6142ba115.png">
<img width="1440" alt="captura de pantalla 2016-05-11 a las 14 07 44" src="https://cloud.githubusercontent.com/assets/16296472/15180409/c37c6700-1781-11e6-96be-7cd9ff2275e9.png">

**Comment by fbarcenas** [comment] 2016-05-11 14:33
Continue testing...
I am thinking than the problem is "Serial Cache Size" with 63 FAIL , with 127 not?
What is the best value? Than the experts talk!

**Comment by jbrazio** [comment] 2016-05-11 23:49
Shouldn't "use ping pong" be active ?
I don't know, just asking really.

**Comment by fbarcenas** [comment] 2016-05-12 10:38
I test with simplify3D and fail:
you can see the photo...:

![1797921e41ab501e6ef4ca9206b389f6](https://cloud.githubusercontent.com/assets/16296472/15211924/5735f38c-183e-11e6-9975-e062f3d39369.jpg)

**Comment by Blue-Marlin** [comment] 2016-05-12 12:37
@fbarcenas 
In your first picture, there is a dialoge named "Flow Control" where "No Flow Control" is selected. What other options can be selected?

**Comment by fbarcenas** [comment] 2016-05-12 12:42
Hardware

**Comment by Blue-Marlin** [comment] 2016-05-12 12:57
Did you try to check off "Allow command buffering"?

**Comment by fbarcenas** [comment] 2016-05-12 13:18
i don't try.

I upload photo of hardware:
<img width="282" alt="captura de pantalla 2016-05-12 a las 14 57 03" src="https://cloud.githubusercontent.com/assets/16296472/15215838/cbe0325e-1854-11e6-9502-a8b05578e857.png">

What change you want than test?

**Comment by Blue-Marlin** [comment] 2016-05-12 13:42
![b9564be2-1781-11e6-9f79-a9d6142ba115](https://cloud.githubusercontent.com/assets/17075493/15216600/05849d4e-1858-11e6-9eb2-6637fb88b67c.png)
Can you disable this?

**Comment by fbarcenas** [comment] 2016-05-12 13:45
Yes
Something more?

**Comment by Blue-Marlin** [comment] 2016-05-12 13:56
Not at the moment.

**Comment by fbarcenas** [comment] 2016-05-12 19:50
Testing....
Same file... 
Tomorrow more news..

**Comment by thinkyhead** [comment] 2016-05-12 21:06
If Marlin isn't responding to `M105` then it must not be getting the command. Strange.

**Comment by fbarcenas** [comment] 2016-05-12 21:25
The file is doing, for the moment not fail, but is a job of 28hours...
The thing more rare is than with Repetier not fail. Incredible!

**Comment by fbarcenas** [comment] 2016-05-14 07:18
The file finish correctly!
SImplify3D and like Blue-marlin say i check off "Allow command buffering".
Time 28 hours, and not errors in the log, not unload materials, not search home sensor, everything correct

I do again a new file for continue testing...

Ideas and conclusions experts of Marlin?

Why this "Allow command buffering" not work well????

**Comment by Blue-Marlin** [comment] 2016-05-14 08:21
> Why this "Allow command buffering" not work well????

Having set 'PingPong' in RepetierHost is should be the same as not having set "Allow command buffering" in simplify3D. So you can't say there is a general problem with using a more 'sophisticated' buffer strategy. I'd consider a incompatibility of simplify3D's buffer filling strategy with Marlin.

**Comment by fbarcenas** [comment] 2016-05-14 08:36
Really interesting, i dont know that say.. I continue testing and i will say results.
The question is:
If we dont use this "buffer strategy" what dissavanteges we have?

**Comment by fbarcenas** [comment] 2016-05-16 06:39
Second test with simplify3D, everything fine.
Problem solved?

**Comment by jbrazio** [comment] 2016-05-16 09:16
Well.. for you yes, for us (the devs) no.
This means we have a bug somewhere in the serial/command processor/buffer..

/cc @thinkyhead @AnHardt

**Comment by fbarcenas** [comment] 2016-05-16 09:28
i want mean:
Problem found? Yes
Solved? Not
But really:  If we dont use this "buffer strategy" what dissavanteges we have?

Of course, i continue testing.... This time with a file of 6 days!

**Comment by AnHardt** [comment] 2016-05-16 10:42
The conventional strategy for the communication is to use 'pingpong'. The host sends a line of g-code, waits for an 'ok', then sends the next line. That means, Marlin's command line buffer is ether empty or contains one line. The RX-buffer never contains more than one line. Between sending a 'ok' and receiving the next command, there is a small gap where Marlin has to wait.
The advanced strategy's try to eliminate that little waits, by pre-filling the one, the other, or both buffers (depending on the host - all hosts do that different, if configured that way, if at all).

**Comment by fbarcenas** [comment] 2016-05-16 10:45
A question
This problem of buffer.. can also happen with SDCARD?

**Comment by AnHardt** [comment] 2016-05-16 10:55
No. That's the reason why SD-printing is faster then USB-printing (when using 'pingpong'). Reading from SD is similar to reading from an filled file-size large RX-buffer.

**Comment by AnHardt** [comment] 2016-05-16 11:29
@jbrazio 
I currently don't see the need for fixes in Marlin.
All our little helpers for the more sophisticated protocols (ADVANCED_OK, NO_TIMEOUTS, HOST_KEEPALIVE_FEATURE) can be switched off. 
We do not know what is confusing S3D and can't look it up (closed source).
If S3D tries a too aggressive buffer strategy that's their problem.
S3D is payware - so they should have someone who is payed for being interested in that problem - so i'm not really interested in that - at least not, as long it's not obvious the problem is on our side of the fence.

**Comment by jbrazio** [comment] 2016-05-16 13:23
@AnHardt I agree with you mostly but I believe this specific issue hints us that we have an unknown error somewhere on the parser thus not making it strong enough, Marlin shouldn't be brought down to it's knees when the host misbehaves. I'm forced to believe that this error could be related with #3680..

**Comment by fbarcenas** [comment] 2016-05-16 14:09
In my config i have:

``` cpp
#define BAUDRATE 115200
//#define PREVENT_DANGEROUS_EXTRUDE
//#define PREVENT_LENGTHY_EXTRUDE
//#define EXTRUDE_MINTEMP 170
//#define EXTRUDE_MAXLENGTH (X_MAX_LENGTH+Y_MAX_LENGTH) 
//#define USE_WATCHDOG
//#define ADVANCED_OK
//#define NO_TIMEOUTS 1000 // Milliseconds
//#define DISABLE_HOST_KEEPALIVE
```

With
- Repetier and non-chek pin-pong WORK
- Simplify3D only work without "allow buffer" check

**Comment by fbarcenas** [comment] 2016-05-16 14:10
By the way... i don't see differences in speed or delays if i run by SDCard or by USBwire

**Comment by jbrazio** [comment] 2016-05-16 16:08
@fbarcenas I believe you may leave this:

``` cpp
#define PREVENT_DANGEROUS_EXTRUDE
#define PREVENT_LENGTHY_EXTRUDE
#define EXTRUDE_MINTEMP 170
#define EXTRUDE_MAXLENGTH (X_MAX_LENGTH+Y_MAX_LENGTH) 
#define USE_WATCHDOG
```

**Comment by fbarcenas** [comment] 2016-05-21 17:06
Hello,

i activate all things jbrazio and with Repetir and pingpong activated happen this:

```
< 15:49:21.749 : N100060 G1 X313.957 Y286.954 E37.5036*95
> 15:49:21.765 : echo:N100060 G1 X313.957 Y286.954 E37.5036*95
> 15:49:22.859 : ok
< 15:49:22.859 : N100061 G1 X311.862 Y287.929 E37.6477*82
> 15:49:22.874 : echo:N100061 G1 X311.862 Y287.929 E37.6477*82
> 15:49:23.031 : ok
< 15:49:23.031 : N100062 G1 X311.508 Y288.096 E37.6721*82
> 15:49:23.046 : echo:N100062 G1 X311.508 Y288.096 E37.6721*82
**< 15:49:24.187 : Printer reset detected - initalizing**
> 15:49:24.359 : start
< 15:49:24.359 : N1 M105*38
> 15:49:24.359 : echo:Marlin 1.1.0-RCBugFix
> 15:49:24.359 : echo: Free Memory: 4701  PlannerBufferBytes: 1360
> 15:49:24.359 : echo:V23 stored settings retrieved (396 bytes)
```

?!?!?!??!?!?!?!
Ideas?

**Comment by fbarcenas** [comment] 2016-05-22 09:48
New test:

``` cpp
#define BAUDRATE 250000
//#define PREVENT_DANGEROUS_EXTRUDE
//#define PREVENT_LENGTHY_EXTRUDE
//#define EXTRUDE_MINTEMP 170
//#define EXTRUDE_MAXLENGTH (X_MAX_LENGTH+Y_MAX_LENGTH) 
//#define USE_WATCHDOG
//#define ADVANCED_OK
//#define NO_TIMEOUTS 1000 // Milliseconds
//#define DISABLE_HOST_KEEPALIVE
```

Repetier with pingpong activated!

and result:

```
< 03:59:31.907 : N203982 G1 X395.532 Y271.798 E65.2395*87
> 03:59:31.923 : echo:N203982 G1 X395.532 Y271.798 E65.2395*87
> 03:59:32.220 : ok
< 03:59:32.220 : N203983 G1 X396.085 Y271.752 E65.2741*87
> 03:59:32.236 : echo:N203983 G1 X396.085 Y271.752 E65.2741*87
< 04:00:12.222 : Communication timeout - reset send buffer block
< 04:00:12.222 : N203984 M117 ETE 107h 28m 39s*4
< 04:00:52.260 : Communication timeout - reset send buffer block
< 04:00:52.260 : N203985 M105*18
```

**Comment by fbarcenas** [comment] 2016-05-24 08:34
I install a new board (this time RUMBA), and i test...
Happen again the problems!
Of course i change wire USB and PC.
A question: is possible than can be a problem of my stepper drivers?!?!!?
I am using external stepper drivers

**Comment by jbrazio** [comment] 2016-05-24 12:28
So far we can't pin-point any errors with Marlin, and you're the only one having this issue.. so it can either be a combination of your hardware, your host software.. 

Did you tried with another host controller ? Like Pronterface or Octoprint.

**Comment by fbarcenas** [comment] 2016-05-24 14:04
Pronterface not test
Octoprint yes Fail
Repetier yes Fail
Simplify yes Fail

**Comment by jbrazio** [comment] 2016-05-24 18:44
@fbarcenas 9 days ago

> Second test with simplify3D, everything fine.
> Problem solved?

I do not understand, it was fixed but now you have the error again ?

**Comment by fbarcenas** [comment] 2016-05-24 20:09
When i am thinking than all is solved, the printer fail again!
Is very desperate.
My actual test is with all wires separate, i am thinking than maybe i have problem of interference in the wires PULSE/DIR and interference in 24V wire of input.
Can be this?

Perhaps not is a problem of firmware?

**Comment by WZ9V** [comment] 2016-05-24 23:06
I had this happen with a filament change from the LCD menu in RC6.  It worked fine and went back to the proper place and then ejected the filament again.  I'm trying to see if I can reproduce it.

**Comment by fbarcenas** [comment] 2016-05-25 06:45
I not use LCD, i remove LCD and SD for remove possible problems.
Thanks for help

**Comment by jbrazio** [comment] 2016-06-11 13:24
Thank you for your interest making Marlin better and reporting this issue but this topic has been open for a long period of time without any further development. Marlin has been under heavy development for the past couple of months and moving to it's last mile to finish the RC cycle and release **Marlin v1.1.0**. We suggest you to try out the latest [RCBugfix](https://github.com/MarlinFirmware/Marlin/archive/RCBugFix.zip) branch and reopening this issue if required.

**Comment by xspitfire** [comment] 2017-04-07 15:54
I am having the same problem with RC8. Printing from the SD, about a hour in the printer stops, makes a few random moves and then ejects the filament. A few times it continued and a few it just stopped,
I have formatted the card (not sure how that will help), 

Printing from USB at a lower baud rate helped, but about 2 hours in the print just stopped. This was including ping pong mode.

From time to time the LCD shows garbage in the screen till you click the encoder wheel.

I used RC6 but it just reset the printer once you click to print from SD. RC8 prints from SD, but i have not been able to finish anything bigger than a small print yet.

**Comment by Bob-the-Kuhn** [comment] 2017-04-07 16:20
Please see if RCBugFix fixes the problem.  Several of these strange behaviors have been fixed.  You can download it [here](https://github.com/MarlinFirmware/Marlin/tree/RCBugFix).

You'll need to transfer your machine specific items over to the new configuration files.

Do you have a filament sensor on your printer?  I'm wondering if there's noise on that signal.

**Comment by xspitfire** [comment] 2017-04-07 17:54
I will try the RCBugFix you suggested, Thank you

I do not have a filament sensor on the printer. With SD card printing the printer started moving to random positions (not on the print area) and back a few times before ejecting the filament.

**Comment by boelle** [comment] 2017-04-26 14:28
@xspitfire 

when you test make sure the sd card is formatted with https://www.sdcard.org/downloads/formatter_4/ first

pick format full overwrite and say yes to adjust format

strange things can happen to sd cards even thou you think they are ok

**Comment by fbarcenas** [comment] 2017-04-26 16:32
All problems with the last RCBUgFix is fixed now, i think than we must close this.

**Closed as completed** 2017-10-31 07:31 UTC
Labels: Bug: Potential ?
