### ISSUE TITLE
[1.1.x] ABL-BILINEAR ignores Z offset when printing?

### ISSUE THREAD

**Issue by Festivejelly** [MarlinFirmware/Marlin#8817] opened 2017-12-17 03:22 UTC
### Bug Report
- Description: When using bi-linear bed leveling with a BL touch for example the offset between nozzle and bed seems to be ignored.
- Expected behaviour: Gap between nozzle and bed should be the same as the Z value
- Actual behaviour: Gap between nozzle and bed is greater than Z value (ignores the offset)
- Steps to reproduce:
  - Set your Z offset with M851 to Z-1.5 for example
  - Heat up the bed and home
  - Do G29
  - Go to middle of the bed and set Z to 0. Probe should be touching bed, or just about.
  - Go and do a print with G28 then G29 in the starting code.
  - Appears the nozzle starts way too high from the bed.

Ive tested this several times and it respects the offset when outside of the print. This only seems to happen during the printing phase.

Attach a ZIP of `Configuration.h` and `Configuration_adv.h` by dropping here.

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/1565288/Marlin.zip)

I've tried doing M501 to read the values from Eeprom, tweaking with M851 Z-1.5 to set the correct offset then doing M500.

As mentioned when controlling the printer via repetier and doing G29 etc then going to Z0.2 for example. The gap is 0.2. But during a print its starting much higher, like its ignoring m -1.5 offset.

I inspected the Gcode and it had the correct layer heights in there of 0.2

**Comment by Festivejelly** [comment] 2017-12-17 03:25
This has apparently already been fixed in a later release

**Comment by Festivejelly** [comment] 2017-12-17 04:02
This issue is still present in 1.1.7 and can be reproduced.

**Comment by Festivejelly** [comment] 2017-12-17 04:07
My latest updates on Configs.

Using a feeler guage, outside of printing (homing then G29 then going to centre of bed) @ Z=0.1 the feeler gage just about can squeeze under at 0.1.

When doing a print when stopping in the centre of the bed with a layer height of 0.1 the feeler gauge can fit a 0.3mm under there.

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/1565310/Marlin.zip)

**Comment by ikarisan** [comment] 2017-12-17 19:00
Hi!
Maybe we both have the same problem:

https://github.com/MarlinFirmware/Marlin/issues/8831

I am using the 1.1.x-bugfix branch

**Comment by Festivejelly** [comment] 2017-12-17 19:26
I think you could be right. I'm going to test 1.1.5 just to make sure im not going crazy. But it can reproduce it every time. Though for me the print starts higher than its supposed to rather than lower.

**Comment by ikarisan** [comment] 2017-12-17 21:43
Please test 1.1.6. This version worked for me.

**Comment by Festivejelly** [comment] 2017-12-17 22:25
1.1.6 didnt work for me nor did 1.1.7 currently testing 1.1.5

**Comment by thinkyhead** [comment] 2017-12-20 02:41
> Go to middle of the bed and set Z to 0

Set? Do you mean, using `G92 Z0`? Probably a bad idea.

> Probe should be touching bed, or just about.

If you did a `G1 Z0` then the _**nozzle**_ should be touching the bed, or just about.

**Comment by Roxy-3D** [comment] 2017-12-20 03:10
My thoughts are we should remove the `z_offset` variable and code.   It just adds complexity.

**Comment by thinkyhead** [comment] 2017-12-20 03:43
Whether the probe Z offset is constant or a variable, all code that uses the value will be the same.

Maybe getting rid of `M851` would eliminate confusion about the current value (e.g., when forgetting to save to EEPROM), but it appears that @Festivejelly has verified that the probe offset is -1.5 and still has issues. Making the probe offset unchangeable probably wouldn't help this case.

**Comment by Roxy-3D** [comment] 2017-12-20 03:52
> Maybe getting rid of M851 would eliminate confusion about the current value (e.g., when forgetting to save to EEPROM), 

No...   I'm thinking z_offset is the one that needs to go.  M851 controls the zprobe_zoffset value.   These are two different animals.
```cpp
  inline void gcode_M851() {
    SERIAL_ECHO_START();
    SERIAL_ECHOPGM(MSG_PROBE_Z_OFFSET);
    if (parser.seen('Z')) {
      const float value = parser.value_linear_units();
      if (!WITHIN(value, Z_PROBE_OFFSET_RANGE_MIN, Z_PROBE_OFFSET_RANGE_MAX)) {
        SERIAL_ECHOLNPGM(" " MSG_Z_MIN " " STRINGIFY(Z_PROBE_OFFSET_RANGE_MIN) " " MSG_Z_MAX " " STRINGIFY(Z_PROBE_OFFSET_RANGE_MAX));
        return;
      }
      zprobe_zoffset = value;
    }
    SERIAL_ECHOLNPAIR(": ", zprobe_zoffset);
  }
```

**Comment by thinkyhead** [comment] 2017-12-20 05:28
>  I'm thinking `z_offset` is the one that needs to go.

Ok, well that's been gone for a while now.

- ABL doesn't have a `z_offset`, although it accepts a Z offset parameter to `G29` (bilinear) that gets added to each mesh point. If left out, there's no offset.
- UBL used to have a `z_offset`. I removed it as obsolete a while ago, since no code was using it anymore.
- MBL is the only system that still retains a `z_offset`.

**Comment by v1ru3** [comment] 2017-12-20 15:34
I tested 1.1.5, 1.1.6 and now 1.1.7 and the z offset and bilinear bed leveling issues seem to persist. I am using an induction z probe that has the same height distance from the bed/nozzle (fixed probe).
In 1.1.4 i used to be able to set the offset using:
G28
G29
G1 Z0
;add paper between nozzle and bed and decrease height.
M851 Z-"value from above".

And that value stayed the same across all future G29s as it should.

In recent versions (1.5, 1.6 and now 1.7) the behavior is chaotic to say the least, even though the documentation says nothing changed.

In 1.5 it was a hit and miss, in 1.6 after every G29 i had to babystep-substract the previous set z offset to avoid bed scratches. In 1.7, the only way to get bilinear working is to not use z offset at all, leave it at 0 and do babystepping before the print starts.
And by the way, the z offset i measure is nothing like the babystepping value (eg, z-offset is -0.9 when i do babystepping the value is -1.050).

I am at loss, not sure what else to try. Can you please help?

PS. i think how the print starts has to do with the kind of probe used. mine is NPN so i had to reverse the detection logic:
#define Z_MIN_ENDSTOP_INVERTING true
If PNP is used, i suppose the print will start higher.

**Comment by fflosi** [comment] 2017-12-22 22:29
What I could found about this is that if I do a G29, then a G28, and reenable the leveling with "M420 S1" it starts to work perfectilly. The problem only happen when I try to test the leveling right after the G29 finishes.
It appears as if the last position of the Z axis after G29 completes is geting lost in some way.

**Comment by thinkyhead** [comment] 2017-12-25 12:44
> It appears as if the last position of the Z axis after G29 completes is geting lost in some way.

~~What is the value of Z immediately after `G29`, versus when you use `G28`, `M420 S1` ?~~

Actually, That might be hard to figure. Try this:

- After `G29` do a simple `G1 X0 Y0` move, then do `M420 S0`. What is the current Z?
- After doing `G28`, `M420 S1`, what is the current Z?

The last thing the `G29` procedure does before enabling leveling is:
```cpp
          // Unapply the offset because it is going to be immediately applied
          // and cause compensation movement in Z
          current_position[Z_AXIS] -= bilinear_z_offset(current_position);
```
You might try commenting out that line to see if it has a positive effect.

**Comment by fflosi** [comment] 2017-12-28 17:27
> You might try commenting out that line to see if it has a positive effect

Still same problem after commenting out the line. I've tested the procedures bellow with and without commenting the line. same result.

> After G29 do a simple G1 X0 Y0 move, then do M420 S0. What is the current Z?

I tried the `M420 S0` and `S1` but every time I issue an `M420 So and S1` i get a different result.
After X0 Y0 Z=1
```
S0 - Z=0.39
S1 - Z=1.04
S0 - Z=0.43
S1 - Z=1.08
S0 - Z=0.48
S1 - Z=1.12
```
> •After doing G28, M420 S1, what is the current Z?

Just after G28 Z=0
```
M420 S1 - Z=0.25
M420 S0 - Z=0.01
M420 S1 - Z=0.26
M420 S0 - Z=0.02
```
Less change than just after a G29, but still there.

**Comment by thinkyhead** [comment] 2017-12-31 09:21
I'd expect a very small amount of imprecision that could accumulate, but not to the degree that we're seeing here. I wouldn't be surprised if there is some greater element of imprecision due to the plethora of changes to the related functions.

I will have to block out time to add logging and do a lot of intensive testing…

**Comment by RoyKea** [comment] 2018-01-20 18:11
I accidentally opened another bug report for this, therefore I will close mine and simply paste it as a comment in here, as it seems that I have the same issue.

### Bug Report
**- Description:**
After issuing the `G29` command to use the Bilinear Leveling feature, the printer does not react to either the `M851` command nor to a change in the `Z_PROBE_OFFSET_FROM_EXTRUDER` setting.

I am using a modified ANET A8 with an 18mm inductive probe directly attached to the endstop pins, the motherboard of which I changed today to a RUMBA board. On the old stock ANET motherboard the probe offset worked and I could change the offset depending on the filament I used, e.g. giving PETG 0.1mm more distance from the bed. With the new motherboard I cannot adjust the offset in either direction, meaning I can neither press the filament closer to the bed nor can I give it a bit more room. Therefore, I also cannot get good adhesion on my prints.

To my embarrassment I must admit that I had this very same issue the first time I flashed Marlin 1.1.6 onto the stock ANET board, but I cannot remember for the life of me what I did to get it working again. Both boards use 1.1.6 of course, and the settings were transferred with the help of the compare feature of Notepad ++. I already reset the EEPROM and reflashed the firmware.
I have read multiple bug reports that also had problems with the combination of `G29` and `M851`, but I did not find a solution (except for the one I apparently already found before and forgot again ...). 

Here is the start GCODE I use in Slic3r:

```
M115 U3.0.10 ; tell printer latest fw version
M83  ; extruder relative mode
M140 S[first_layer_bed_temperature] ; set bed temp
M190 S56 ;
M104 S150 ;preheat nozzle
M190 S[first_layer_bed_temperature] ; wait for bed temp
M104 S[first_layer_temperature] ; set extruder temp
G1 Z7 F1000
G28 
;G29
;M501
M420 S1  ; Enable compensation using current grid/mesh
;M420 Z10 ; Gradually reduce compensation until Z=10
G1 Z2
G1 X20 Y-15 F3000.0
G1 Z0.2 F300
M109 S[first_layer_temperature] ; wait for extruder temp
G4 S2
G1 E20 F500
G1 E10 F800
G4 S2
G1 Y8 F1000.0
G1Z0.3 F300
G1 X80.0 E9.0  F1000.0 ; intro line
G1 X150.0 E12.5  F1000.0 ; intro line
```

`G29` is commented out because I store the grid in the EEPROM, which worked geat on the old motherboard and saved a lot of time, while having no negative effects on bed adhesion for me. I attached the logfile from the `M111 S247` command and my Configuration.h.

[log.txt](https://github.com/MarlinFirmware/Marlin/files/1649075/log.txt)

[Configuration.txt](https://github.com/MarlinFirmware/Marlin/files/1649110/Configuration.txt)

As a question for the other users that have this issue, does UBL work with `M851` for you? Considering the RUMBA should have enough memory to support it, I would make the switch if it works.

**Comment by thinkyhead** [comment] 2018-02-02 12:55
> the printer does not react to either the `M851` command nor to a change in the `Z_PROBE_OFFSET_FROM_EXTRUDER` setting.

@RoyKea — What kind of "reaction" are you looking for?

Try `M851 Z10` followed by `M503 S0`. Does the output show `M851 Z10.00` or has it not been changed? If it has been changed then `M851` is working!

**Comment by RoyKea** [comment] 2018-02-02 13:59
I never tried using `M503 S0`, but instead made changes through e.g. `M851 Z10.00` --˃ `M500` --˃ `M501`. This saved my changes and did output the changed value in the terminal. Is this what you were asking? In any case, even though the output showed that the value was changed, the printer didn't seem to apply it. `Z10`, `Z-4`, it didnt matter. The printer never adjusted the Z height.

In any case, I reflashed the newest 1.1.x bugfix version and now `M851` works as intended for me.

**Comment by thinkyhead** [comment] 2018-02-10 21:23
`M503 S0` tells you what your current settings are.

**Closed as completed** 2018-02-10 21:23 UTC
Labels: Bug: Potential ?, Needs: More Data

**Comment by patternseek** [comment] 2018-04-28 21:32
@thinkyhead the original issue seems to be unresolved, I'm confused as to why this is closed.

**Comment by thinkyhead** [comment] 2018-04-29 03:04
@patternseek — Please open a new issue if you're having a similar problem with the current bugfix branches. It may be a regression, it may be a configuration issue, or it may be a matter of procedure. There's nothing unique about the BLTouch Z probe offset. If there's a general problem with the M851 Z value being "ignored" we have not had widespread reports about it. For most setups ABL bilinear works as designed.

**Comment by Shadesh** [comment] 2018-07-30 09:31
Same problem here. Got a Creality Ender 3 with original BLTouch. Everything is set but when printing Marlin seems to ignore the Z Offset completely. Using the 1.1.8 Version.

**Comment by maqndon** [comment] 2018-08-28 18:06
I'm using the 1.1.8 too. The same problem. I fixed that 3 months ago but I don't remember how...

**Comment by thinkyhead** [comment] 2018-08-29 23:52
1.1.8 is no longer recommended. Marlin 1.1.9 fixes all the bugs.

**Comment by maqndon** [comment] 2018-08-30 19:23
Same problem with marlin 1.1.9...

**Comment by maqndon** [comment] 2018-08-30 19:26
I have the zoffsets just good. Then I made a m206 x0 y0 and my zoffset turn crazy again... z0 when its leveling but when print it says z4.8 or so...

**Comment by spilz87** [comment] 2018-08-30 20:54
I solved the issue for me like this in `Marlin_main.cpp`. Not sure it's the good way, but it works for me:
```cpp
    // Calculate leveling, print reports, correct the position
    if (!isnan(measured_z)) {
      #if ENABLED(AUTO_BED_LEVELING_BILINEAR)

        if (!dryrun) extrapolate_unprobed_bed_level();
        print_bilinear_leveling_grid();

        // PHR
        // moyenne locale pour l'autolevel
        report_current_position();
        const float l = (z_values[0][0] + z_values[1][0] + z_values[2][0] + z_values[0][1] + z_values[1][1] + z_values[2][1] + z_values[0][2] + z_values[1][2] + z_values[2][2]) / 9,
                  v = LOGICAL_TO_NATIVE(l, Z_AXIS),
                  d = current_position[Z_AXIS] - v;
        current_position[Z_AXIS] = d;
        update_software_endstops((AxisEnum)Z_AXIS);
        report_current_position();
        for (uint8_t i = 0; i < 3; ++i) {
          for (uint8_t j = 0; j < 3; ++j) {
            z_values[i][j] -= l;
          }
        }
        print_bilinear_leveling_grid();

        refresh_bed_level();

        #if ENABLED(ABL_BILINEAR_SUBDIVISION)
          print_bilinear_leveling_grid_virt();
        #endif
```

**Comment by spilz87** [comment] 2018-08-30 20:55
but I never try to change homing or else after bed leveling, direct print

**Comment by thinkyhead** [comment] 2018-08-30 21:48
The effects of `M206` may be unpredictable. What is it being used for?

**Comment by Hawkeye0914** [comment] 2019-02-07 20:05
Im having this exact same issue.  Is there still no fix for this?

**Comment by tomdk** [comment] 2019-03-17 22:16
Same here in Marlin 1.1.9 and 1.1.x bugfix. Have been going crazy and so happy I have found this now.

**Comment by spilz87** [comment] 2019-03-17 22:40
Hi
Did my code help ? 
If yes I have an small update if you want/need 
Else happy you found this :)

**Comment by treschlet** [comment] 2019-10-14 22:58
I just upgraded my Lulzbot TAZ 6 from 1.1.5 to 1.1.9.34 and am having this issue. z-offset is completely ignored. Doesn't matter what I set it to, from the controls on machine or with the M851 code.

**Comment by Excentertex** [comment] 2020-01-28 21:28
Oh dear! I cannot believe I spent the better part of the week finding an explanation for this problem. 

I have an Anet A8 with stock board and latest bugfix-1.1.x firmware. But it also happened on the 1.1.9 branch. I'm not entirely sure I had the problem before, because I always had to do "some" manual corrections in Cura via the Z offset plugin. However I believe it worsened considerably after I had to re-download Marlin (following a complete computer reinstall). Since then the problem has been very persistent and considerably worse.
