### ISSUE TITLE
http://marlinfw.org/tools/lin_advance/k-factor.html

### ISSUE THREAD

**Issue by plunderfest** [MarlinFirmware/Marlin#8938] opened 2017-12-28 19:58 UTC
### Bug Report
- Description: --- http://marlinfw.org/tools/lin_advance/k-factor.html
- Expected behaviour: --- compile K factor code  
- Actual behaviour: ---  Does nothing - will not compel code 
- Steps to reproduce: 

  http://marlinfw.org/tools/lin_advance/k-factor.html
Page will allow you to change values, but does nothing after pressing button to compile G-CODE

**Comment by fiveangle** [comment] 2017-12-28 20:46
Dupe of #8909

Fixed by https://github.com/MarlinFirmware/MarlinDocumentation/pull/120 (if/when it is merged)

-=dave

**Comment by chinoox** [comment] 2017-12-29 03:59
the gcode view is very small :( in chrome. In firefox it is ok

**Comment by fiveangle** [comment] 2017-12-29 22:25
close ?

**Comment by ikarisan** [comment] 2017-12-30 16:43
Maybe this Google Chrome issue should be fixed, too:
![k-factor](https://user-images.githubusercontent.com/14032966/34455883-eb9945b2-ed88-11e7-8ecb-7bea5a31a4f1.png)

**Comment by Sineos** [comment] 2017-12-30 18:52
https://github.com/MarlinFirmware/MarlinDocumentation/pull/124
Just needs merging.

**Closed as completed** 2018-02-11 07:18 UTC
