### ISSUE TITLE
Servo retraction at last point of Auto Bed Level 

### ISSUE THREAD

**Issue by Ursus63** [MarlinFirmware/Marlin#1589] opened 2015-03-10 13:28 UTC
How can i set to move up Z BEFORE retract servo at last point of ABL Grid when i use G29 E? I have an optical endstop on servo and when servo retracts after last point of grid it scratches bed.

**Comment by brainscan** [comment] 2015-03-10 17:51
Are you using the latest version of marlin? I think it should do this as standard now but I haven't checked.

**Comment by Ursus63** [comment] 2015-03-10 18:31
Downloaded Marlin today. And it don't do this. Now i just disable retraction in firmware at all and add to g-code G1 Z15 and M402 after G29 E and its work. But i think its better to do it in firmware.

**Comment by brainscan** [comment] 2015-03-10 20:54
Sorry I thought this was added with the recent update to the bed levelling. It should be the same as the one I've been using which does raise z before retracting. The code can be found at http://3dprintboard.com/showthread.php?3105-Auto_Bed_Leveling-Enhanced-G29-command 
Hope this helps.

**Comment by boelle** [comment] 2015-03-10 21:31
i have at least now added both potential bug label and needs more feedback... if 1-2 more can verify this i will upgrade it to verified bug and include it in a milestone so it can be fixed...

to me its seems pretty important that you raise Z just a bit before you swing up probe arm

of course depends much on what kind of probe... some can raise the probe without raising Z...

**Comment by Ursus63** [comment] 2015-03-11 03:12
It will be good to rize probe before retract in G28 and G30 too. G28 i'm modified as described at the link above, but i think it must be in firmware by default. And G30 i think too.

**Comment by SkyFlyer2** [comment] 2015-03-11 07:31
The best way is to add the code lifting the Z-axis before any retract servo

Please add the code to function  - static void retract_z_probe() 
I think it might look something like this:

do_blocking_move_to(current_position[X_AXIS], current_position[Y_AXIS], current_position[Z_AXIS] + Z_RAISE_BETWEEN_PROBINGS);

I  damaged already one servo without lifting Z-axis before servo retraction.

**Comment by SkyFlyer2** [comment] 2015-03-11 11:45
I tried add code to function static void retract_z_probe() - this is not correct, because it always lift Z-axis before retract, even if not required. Need to find another place in code.

**Comment by alexborro** [comment] 2015-03-11 15:45
I have added a new feature yesterday. Check this out in configuration.h:

  #define Z_PROBE_END_SCRIPT "G1 Z10 F12000\nG1 X15 Y330\nG1 Z0.5\nG1 Z10"
//These commands will be executed in the end of G29 routine. Useful to
retract a deployable probe.

Cheers.

Alex.

2015-03-11 8:46 GMT-03:00 SkyFlyer2 notifications@github.com:

> I tried add code to function static void retract_z_probe() - this is not
> correct, because it always lift Z-axis before retract, even if not
> required. Need to find another place in code.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MarlinFirmware/Marlin/issues/1589#issuecomment-78248411
> .

## 

_"Não é o mais forte da espécie que sobrevive, nem o mais inteligente. É
aquele que se adapta melhor as mudanças"  ( Charles Darwin )_

Alex Borro

**Comment by SkyFlyer2** [comment] 2015-03-11 18:04
A nice solution. I will check it.

But this is not solve same problem for commands G28, G30 and M48.  No any changes  in their code, but the same issue also present there.

**Comment by SkyFlyer2** [comment] 2015-03-12 07:11
Hmm. I've checked this changes. No useful changes. The servo retracting BEFORE lift Z-axis, as result it scratches the bed and make damage to servo.

**Comment by thinkyhead** [comment] 2015-03-13 04:22
This could be done as an enhancement to G29 or as a compile-time option, or both. I'll see where new code may help.

**Comment by avluis** [comment] 2015-03-17 05:45
@thinkyhead Can you think of implementing something similar at the end of a G28 as well - a lift of even 1mm will save many micro switches ;)

**Comment by maverikou** [comment] 2015-03-18 17:49
G29 does this:

do_blocking_move_to(current_position[X_AXIS], current_position[Y_AXIS], Z_RAISE_AFTER_PROBING);

However that same code is not in G28. Is that the bug you're seeing?

**Comment by maverikou** [comment] 2015-03-20 18:38
This is a duplicate of #1507

**Comment by thinkyhead** [comment] 2015-03-21 04:05
Let's move the discussion over to #1507 then....

**Closed as completed by thinkyhead** 2015-03-21 04:05 UTC
