### ISSUE TITLE
After printing head tries to go to {0,0,0}

### ISSUE THREAD

**Issue by alexxy** [MarlinFirmware/Marlin#4331] opened 2016-07-17 08:50 UTC
I'm using Latest RCBugFix and had new weird issue:
After printing finished head tries to go home. Instead of staying at lastHeight+5 and do homing in XY

postcode

```
M104 S0 ; turn off temperature
M140 S0 ;  turn off heatbed
G28 X0  ; home X axis
M84     ; disable motors
```

**Comment by jbrazio** [comment] 2016-07-17 12:12
Marlin never does Z+5 automatically when printing ends, it must be done in end gcode script.

**Comment by alexxy** [comment] 2016-07-17 15:33
anyway it shouldnt go to {0,0,0} after when homing only X as its done in gcode

**Comment by jbrazio** [comment] 2016-07-17 17:47
I will mark this one as duplicate of #4325.
But indeed I was able to make G28 behave oddly so we may be have a bug here.

**Closed as completed by jbrazio** 2016-07-17 17:47 UTC
