### ISSUE TITLE
[BUG] SKR MINI E3 V2 - Cooling fan does not respond to GCODE

### ISSUE THREAD

**Issue by Doormat1** [MarlinFirmware/Marlin#22318] opened 2021-07-08 20:20 UTC
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

I have a SKR Mini E3 V2 and I've updated my firmware using the latest marlin bugfix from the official marlin github, (configuration.h version ends in 901) and now my part cooling fan does not respond to gcode, it can be controlled via the lcd menu though so the fan is not broken. 
When I last updated I had the same problem and solved it by copying the platformio.ini from the BTT github however the current marlin one is completely different so that plan doesnt work. What is the fix?

### Bug Timeline

Old issue resurfacing

### Expected behavior

When gcode demands the cooling fan to start it swiches on

### Actual behavior

part cooling fan only responds to the tune menu not g code

### Steps to Reproduce

Build the bugfix (version 901) for the SKR mini E3 v2

### Version of Marlin Firmware

Bugfix 2.0.x

### Printer model

Ender 3 pro

### Electronics

SKR Mini E3 v2

### Add-ons

NA

### Your Slicer

Cura

### Host Software

OctoPrint

### Additional information & file uploads

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/6787058/Configuration.zip)

**Comment by thisiskeithb** [comment] 2021-07-08 20:38
Duplicate of https://github.com/MarlinFirmware/Marlin/issues/20670

**Closed as completed by thisiskeithb** 2021-07-08 20:38 UTC
