### ISSUE TITLE
[BUG] Custom Menus don't work in LVGL anymore since 2.0.8

### ISSUE THREAD

**Issue by Valnar8** [MarlinFirmware/Marlin#22179] opened 2021-06-19 20:57 UTC
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

The Custom Buttons in the more menu don't appear anymore since they have been changed from CUSTOM_USER_MENUS to CUSTOM_MENU_MAIN and CUSTOM_MENU_CONFIG

It just doesn't change anything if I comment the defines in as it used to do back when the menu was called CUSTOM_USER_MENUS

### Bug Timeline

2.0.8

### Expected behavior

Buttons like this one should appear in the more menu

```
  #define MAIN_MENU_ITEM_1_DESC "Home & UBL Info"
  #define MAIN_MENU_ITEM_1_GCODE "G28\nG29 W"
  //#define MAIN_MENU_ITEM_1_CONFIRM          // Show a confirmation dialog before this action
`````

### Actual behavior

The More menu doesn't contain anything but the G-code menu and a back button.
the custom config menu doesn't appear either.

### Steps to Reproduce

1. comment in #define CUSTOM_MENU_MAIN
2. upload it to the printer

### Version of Marlin Firmware

2.0.9

### Printer model

Two Trees Sapphire Pro

### Electronics

Stock electronics

### Add-ons

none

### Your Slicer

Cura

### Additional information & file uploads

I changed a few pins so it might be necessary to use the pin file I uploaded to compile successful but it shouldn't change anything about the problem.
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/6681334/Configuration.zip)

**Comment by thisiskeithb** [comment] 2021-06-19 21:03
Duplicate of #21423

**Closed as completed by thisiskeithb** 2021-06-19 21:03 UTC
