### ISSUE TITLE
LCD axis movement display

### ISSUE THREAD

**Issue by AlkalineJaunt** [MarlinFirmware/Marlin#7129] opened 2017-06-23 21:09 UTC
I notice that when using the LCD to lower the Z axis, if the endstop is triggered the axis will not go any lower. However, the relative position shown on the display continues to decrement.

That causes the display to get out of sync with real life.

**Comment by thinkyhead** [comment] 2018-02-09 09:30
Move Axis or Babystep?

**Comment by boelle** [comment] 2019-02-19 20:18
@apelly Move Axis or Babystep?

**Comment by boelle** [comment] 2019-03-06 10:37
@thinkyhead i think we can close this one

**Comment by boelle** [comment] 2019-03-16 22:19
i have tested this, i cant reproduce 
babystepping disabled in firmware

**Closed as completed** 2019-03-17 01:31 UTC
