### ISSUE TITLE
[FR] Multiple Beds Support

### ISSUE THREAD

**Issue by dragondgold** [MarlinFirmware/Marlin#8507] opened 2017-11-20 16:19 UTC
### Feature Request

Is it any plan to support multiple heat beds? In bug printers the heat bed is usually split into two or more heaters and thermistors. Being able to have 2, 3 or 4 beds would be great in this cases, right now you have to set the second bed as a second extruder.

**Comment by psavva** [comment] 2017-11-30 04:01
What hardware are you using?  Mega with a Ramps shield?

**Comment by dragondgold** [comment] 2017-11-30 10:06
@psavva Yes, I activate each zone with a GPIO connected to a transistor with a relay.

**Comment by psavva** [comment] 2017-12-06 10:10
I've checked the magnitude of changes needed to support multiple bed support (similar to multi extruder support in Marlin.  It's huge.

I suggest you stick to what you're doing now until someone (maybe myself) finds time to implement this...

**Comment by thinkyhead** [comment] 2018-02-10 22:26
Duplicate of #7710

**Closed as completed by thinkyhead** 2018-02-10 22:26 UTC
Labels: T: Feature Request

**Comment by piolo79** [comment] 2019-05-20 19:16
hi, I was also interested in adding a second bed but I had thought of using the pins of the second extruder (E1) since the stepper driver I use as second z, would it be possible?
