### ISSUE TITLE
Creality 4.2.7 & TMC2208 & Linear Advance

### ISSUE THREAD

**Issue by darkyp** [MarlinFirmware/Marlin#21463] opened 2021-03-27 19:20 UTC
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

TMC2208 on Creality 4.2.7 board might actually work

### Version of Marlin Firmware

2.0.7.2

### Printer model

Ender 3 Pro

### Electronics

Creality 4.2.7

### Your Slicer

Cura

First, please excuse me if I am posting at the wrong place. It is not actually a bug but a description of my findings that I wanted to share after searching and reading a lot of posts, discussions, datasheets, software emulation for linear advance (G-Code) solutions etc. The related TMC2208 & Linear advance issues here seem all locked or closed and that is why I am starting a new one.

My setup: Ender 3 Pro upgraded with the silent board (4.2.7). Working properly, still there is space for improvement in terms of print quality. The linear advance is one such item that might lead to improvement. I downloaded the latest (?) marlin 2.0.7.2. Built it and updated the board. Of course linear advance did not work. Yes, yes, I see you saying that TMC2208 in standalone stealthchop2 for the extruder does not work with linear advance and will probably never work. Well it seems that Klipper works with it with some advanced step queue analysis (mentioned in another issue here). Anyway I started playing with the configuration options and so far so good. My Ender started working with this feature. At first I was using 100mm/s2 acceleration and while the quality was better I still had some notes about it. Then increased the acceleration to 500mm/s2 and was way too satisfied. My current assumption is that due to the lower speed the hotend took too much time over the start and end of the paths. While I have not yet printed a multi hour job, the various quick tests went fine without the driver "hanging" and all lead to believe I might have stumbled upon a kind of solution.

My solution:
#define MINIMUM_STEPPER_PULSE 40
#define MAXIMUM_STEPPER_RATE 25000

Not sure which one actually did the trick but I will leave it like this for now and up to the others from the community to test.

**Comment by thisiskeithb** [comment] 2021-03-27 20:54
Duplicate of https://github.com/MarlinFirmware/Marlin/issues/16076

**Closed as completed by thisiskeithb** 2021-03-27 20:54 UTC
