### ISSUE TITLE
[BUG] Print timer not starting despite #define PRINTJOB_TIMER_AUTOSTART and M109 220

### ISSUE THREAD

**Issue by amp-man** [MarlinFirmware/Marlin#19718] opened 2020-10-13 15:26 UTC
### Bug Description

I am running an MKS GEN L V1.0 and an external BTT Screen, no Marlin LCD.
I am using the bugfix release of 2.0.7

In Configuration.h: `#define PRINTJOB_TIMER_AUTOSTART` 

My start g-code:
```
M190 S65
M109 S225
```
The print timer does not start automatically. If I send M31 while the print is running, I get: 
> echo:Print time: 0s

But when I insert an M75 command in the start g-code, the print timer starts and after a few seconds when I send M31, I get:
> echo:Print time: 13s

### My Configurations

[Archiv.zip](https://github.com/MarlinFirmware/Marlin/files/5372354/Archiv.zip)

### Steps to Reproduce

1. In Configuration.h: `#define PRINTJOB_TIMER_AUTOSTART` 
2. Start print and wait for M190 S65 and M109 S225
3. Run M31 after a few seconds

**Expected behavior:** [What you expect to happen]
> echo:Print time: 13s

**Actual behavior:** [What actually happens]
> echo:Print time: 0s
#### Additional Information

* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.

**Comment by amp-man** [comment] 2020-11-13 13:48
Still open

**Comment by boelle** [comment] 2020-11-22 01:19
> release of 2.0.7

Please test the [`bugfix-2.0.x branch`](https://github.com/MarlinFirmware/Marlin/tree/bugfix-2.0.x) to see where it stands. If the problem has been resolved then we can close this issue. If the issue isn't resolved yet, then we should investigate further.

**Comment by rhapsodyv** [comment] 2020-12-03 23:44
the attached configs are what are you using?
did you tested only with that two gcode you shared, manually?

I can't reproduce it. Everything is working for, following your instructions and configs.

The only difference between `M75` and `M190/M109` regarding of `PRINTJOB_TIMER_AUTOSTART` is that `M190/M109` do a check if the target temperature is greater than `BED_MINTEMP` and `EXTRUDE_MINTEMP / 2`. Nothing more than that.

One thing is weird in your report. `M190/M109` will never takes only 13s. It will take several minutes. Are you sure those are the used gcode?

**Comment by rhapsodyv** [comment] 2020-12-07 22:32
@amp-man any news here?

**Closed as completed** 2020-12-28 14:01 UTC
Labels: Bug? False Alarm, Needs: More Data
