### ISSUE TITLE
[BUG] planner.cpp error: 'maxj' was not declared in this scope (bugfix 2.0.x)

### ISSUE THREAD

**Issue by Kokorone** [MarlinFirmware/Marlin#16991] opened 2020-02-26 21:25 UTC
### Bug Description

Compiling bugfix 2.0.x with todays commits causes this error with a SKR 1.3

![image](https://user-images.githubusercontent.com/32761171/75389105-ddf12e00-589a-11ea-9d7f-2ed1eaa9d8e6.png)

### My Configurations

**Required:** Please include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/4258228/Marlin.zip)

### Steps to Reproduce

1. Configure bugfix 2.0.x with commits as of 1:23 pm PST on 2/26/2020
2. Attempt to compile 
3. View errors in terminal

**Expected behavior:** [What you expect to happen]
Compile as usual with no errors
**Actual behavior:** [What actually happens]
Fail with several errors related to maxj, axis, and extraxyjerk in planner.cpp
#### Additional Information
Only noteworthy change is using CLASSIC_JERK
* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.

**Comment by Kokorone** [comment] 2020-02-26 21:54
Recompiled firmware with CLASSIC_JERK disabled and Junction Deviation re-enabled and it compiled with no issues. 

Appears to be a bug with how CLASSIC_JERK's hooks into the rest of the firmware

**Comment by Kokorone** [comment] 2020-02-26 22:52
Appears to have been broken with this commit which references the exact lines that are erroring

[https://github.com/MarlinFirmware/Marlin/commit/263a7beeb53a619cc319be2e369ef7604f32af4d](url)

**Comment by lesstutrey** [comment] 2020-02-26 22:59
[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/4258724/Marlin.zip)
having same issue. yup classic jerk enabled.  sorry confs attached now.  This was for 2.0.4.4 though.

**Comment by lesstutrey** [comment] 2020-02-26 23:02
![marlinerror2144](https://user-images.githubusercontent.com/60524856/75396284-c2495000-58b9-11ea-8d9c-ceadecab7116.JPG)

**Comment by mak0t0san** [comment] 2020-02-27 00:30
Getting this as well.  The maxj variable was declared as a float variable, but now isn't declared at all.  Same with `axis`.  I'm using a delta printer so I can only use classic jerk as junction deviation doesn't work with delta printers.

**Comment by ellensp** [comment] 2020-03-21 09:19
This was fixed three weeks ago. Confirmed that your configuration files currently compile without issue.
Please close this issue.

**Comment by boelle** [comment] 2020-06-20 21:40
Lack of Activity
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.

**Closed as completed by boelle** 2020-06-20 21:40 UTC
