### ISSUE TITLE
[BUG] Wrong temperature shown during filament change, leading to thermal runaway

### ISSUE THREAD

**Issue by rglory** [MarlinFirmware/Marlin#23472] opened 2022-01-07 19:49 UTC
### Did you test the latest `bugfix-2.0.x` code?

Yes, problem persists

### Bug Description

After filament sensor triggers tool goes to parking and starts to unload filament. During print temperature was 220C. After parking in a second later it shows 190C (no way it could cool down so fast) and starts heating. If heating is not fast enough thermal runaway error happens. If heating is fast then after filament change and head is ready to go back into position it suddenly shows extruder temperature 240C and starts cooling.

### Bug Timeline

Seen it in 2.0.5

### Expected behavior

Expected to show proper temperature not to overheat and not provide thermal runaway error.

### Actual behavior

Shows lower temperature, overheat and may crash firmware due to thermal runaway.

### Steps to Reproduce

1. Let filament sensor trigger.
2. Watch temperature drops 30C
3. Heating back to "220C"
4. After filament change temperature shows "240C"

### Version of Marlin Firmware

2.0.9.3

### Printer model

Prism

### Electronics

BTT Skr v1.3

### Host Software

OctoPrint

### Additional information & file uploads

[config.zip](https://github.com/MarlinFirmware/Marlin/files/7831000/config.zip)

**Comment by rglory** [comment] 2022-01-07 20:44
I did some additional testing. So when during print I issue "change filament" command, it works fine, shows the same temperature as it was printing and starts to unload immediately. But if filament sensor triggers temperature drops immediatly (in this case from 210C to 188C), it starts heating and I am getting thermal runaway.

I added 2 screenshot showing the difference, first one when command is issued, second one when sensor triggers. I have video if necessary, but they are quite big.
![command](https://user-images.githubusercontent.com/64332764/148604960-43014884-4d1e-4c24-8ea1-eec57fac64ca.jpg)
![sensor](https://user-images.githubusercontent.com/64332764/148604970-f74bfc1c-89b5-4581-9cc4-95059f9fb17c.jpg)
Here is the log for sensor trigger:


> Send: N3424 G1 X94.400 Y105.173 Z2.821 E0.4043*5
Recv: ok
Send: N3425 G1 X94.171 Y105.194 Z2.821 E0.4126*12
Recv: //action:prompt_end
Recv: //action:prompt_begin FilamentRunout T0
Recv: //action:prompt_show
Recv: //action:paused filament_runout 0
Printer signalled that it paused, switching state...
Changing monitoring state from "Printing" to "Pausing"
Recv: //action:paused
Printer signalled that it paused, switching state...
Recv:  T:188.13 /210.00 B:50.00 /50.00 @:127 B@:25
Recv:  T:187.92 /210.00 B:50.00 /50.00 @:127 B@:15
Recv: X:10.00 Y:5.00 Z:20.00 E:-1.60 Count X:800 Y:400 Z:24000
Recv:  T:188.23 /210.00 B:50.00 /50.00 @:127 B@:25
Recv:  T:188.85 /210.00 B:50.00 /50.00 @:127 B@:0
Recv:  T:189.79 /210.00 B:50.00 /50.00 @:127 B@:0
Recv:  T:190.68 /210.00 B:50.00 /50.00 @:127 B@:26
Recv:  T:191.93 /210.00 B:50.00 /50.00 @:127 B@:26
Recv:  T:192.95 /210.00 B:50.00 /50.00 @:127 B@:26
Recv:  T:194.20 /210.00 B:50.00 /50.00 @:127 B@:8
Recv:  T:195.23 /210.00 B:50.00 /50.00 @:127 B@:44
Recv:  T:196.25 /210.00 B:50.00 /50.00 @:127 B@:18
Recv:  T:197.27 /210.00 B:50.00 /50.00 @:127 B@:26
Recv:  T:198.30 /210.00 B:50.00 /50.00 @:127 B@:14
Recv:  T:199.32 /210.00 B:50.00 /50.00 @:127 B@:29
Recv: echo:busy: processing
Recv:  T:200.28 /210.00 B:50.00 /50.00 @:127 B@:27
Recv:  T:201.53 /210.00 B:50.00 /50.00 @:100 B@:27
Recv:  T:202.64 /210.00 B:50.00 /50.00 @:88 B@:26
Recv:  T:203.47 /210.00 B:50.00 /50.00 @:123 B@:29
Recv:  T:204.17 /210.00 B:50.00 /50.00 @:127 B@:28
Recv:  T:205.16 /210.00 B:50.06 /50.00 @:115 B@:26
Recv: Error:Thermal Runaway, system stopped! Heater_ID: E0
Recv: 
Changing monitoring state from "Pausing" to "Cancelling"

**Comment by ellensp** [comment] 2022-01-08 00:01
Please test the [`bugfix-2.0.x` branch](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.0.x.zip) to see where it stands. If the problem has been resolved then we can close this issue. If the issue isn't resolved yet, then we should investigate further.

**Comment by rglory** [comment] 2022-01-08 06:15
I did the test with bugfix version and can confirm that problem persists.

**Comment by ellensp** [comment] 2022-01-08 07:04
Could this be a fault on your machine, ie a wiring issue on the Thermistors?
Can you try this test.  Move the hotend end somewhere centralized and safe. 
Heat the hotend to 210, wait for it to stabilize. (your display says 210) 
Move the axies to the park position, not using park or filament change code.  
check the temperature. was it constant?

**Comment by rglory** [comment] 2022-01-08 08:01
> Could this be a fault on your machine, ie a wiring issue on the Thermistors?

No this printer prints for hours I would notice bad wiring for sure. When I tested for bugfix-2.0.x I noticed that temperature dropped immediately after sensor triggered, but printer went to parking after couple seconds (was printing from buffer), so does not fit that agenda.

Again if I issue M600 manually it goes to the same parking position, but problem does not show. And it  is reproducible, it does that every time. Also if I trigger from 220C (first layer) temperature drops to 190 something, if I trigger on second+ layer from 210 then it drops to 188 and does that all the time. I can upload video where temperature changes immediatly, but stays stable. If bad wiring if would not do that.

I've seen people complaining about this bug constantly, but looks like they did not notice temperature drop.

**Comment by ellensp** [comment] 2022-01-08 08:23
I cannot see how this can happen... but am presuming it does.  let see if we can tease out some more information.
Can you enable SHOW_TEMP_ADC_VALUES and rerun test, logging the drop in tempature?

**Comment by rglory** [comment] 2022-01-08 15:09
Actually you gave me an idea about wiring. You were right, that's hardware problem - filament switch affects extruder thermistor somehow. Not sure how it is linked but will realize soon, now I know what to look for. Sorry for false alarm and thank you for your help. You can close this issue.

**Closed as completed** 2022-01-08 15:10 UTC
Labels: Bug? False Alarm
