### ISSUE TITLE
[bugfix-2.0.x] : Mesh bed leveling without segment leveled moves option compilation fail

### ISSUE THREAD

**Issue by Project-J2** [MarlinFirmware/Marlin#10708] opened 2018-05-11 19:19 UTC
Hello,

I can't compile marlin with MESH_BED_LEVELING enabled and SEGMENT_LEVELED_MOVES disabled, 
it seems that there is a problem of function declaration.
There is a mark "// Support functions, which may be embedded in the class later" at the end of the file mesh_bed_leveling.h
Can you help me solve the problem?

Thanks,
Jean

**Comment by thinkyhead** [comment] 2018-05-13 21:43
Please test with the latest `bugfix-1.1.x` (and/or `bugfix-2.0.x`) branch to see where it stands. If the problem has been resolved then we can close this issue. If the issue isn't resolved yet, then we should investigate further.

**Comment by thinkyhead** [comment] 2018-05-13 21:44
Please ZIP up your `Configuration.h` and `Configuration_adv.h` files (as requested in the Issue template) and drop them into your next reply.

**Comment by thinkyhead** [comment] 2018-05-13 21:51
Thanks for the report! This is now patched.

**Closed as completed by thinkyhead** 2018-05-13 21:51 UTC
Labels: T: Question, F: Calibration
