### ISSUE TITLE
Nozzle fall down when finished

### ISSUE THREAD

**Issue by jowa01** [MarlinFirmware/Marlin#8643] opened 2017-12-03 23:06 UTC
Nozzle fall down when finished.

When V1.1.6 is in use.
In V1.1.5 it's OK.

#define DISABLE_INACTIVE_Z is set to false.

**Comment by bjarchi** [comment] 2017-12-04 00:26
1. Is it still an issue in bugfix-1.1.x? 

2. There are separate defines you might want to check for disabling axes when not active (as opposed to when the machine is idle). Found in `Configuration.h`, look for the following block:
```
// Disables axis stepper immediately when it's not being used.
// WARNING: When motors turn off there is a chance of losing position accuracy!
#define DISABLE_X false
#define DISABLE_Y false
#define DISABLE_Z false
```
And make sure that DISABLE_Z is false there too. I'm not sure whether DISABLE_INACTIVE_Z would override this setting; it's worth checking.

**Comment by jowa01** [comment] 2017-12-04 19:55
I tried it 3 times.
New Download V1.1.6, and all Settings new.
The settings for my issue with the nozzle:

In Configuration.h
```
731  #define DISABLE_X false
732  #define DISABLE_Y false
733  #define DISABLE_Z false
```
In Configuration_adv.h
```
371  // Default stepper release if idle. Set to 0 to deactivate.
372  // Steppers will shut down DEFAULT_STEPPER_DEACTIVE_TIME seconds after the last move when DISABLE_INACTIVE_? is true.
373  // Time can be set by M18 and M84.
374  #define DEFAULT_STEPPER_DEACTIVE_TIME 120
375  #define DISABLE_INACTIVE_X true
376  #define DISABLE_INACTIVE_Y true
377  #define DISABLE_INACTIVE_Z false  // set to false if the nozzle will fall down on your printed part when print has finished.
378  #define DISABLE_INACTIVE_E true
```
End of Gcode:
```
G92 E0
G1 E-1.4000 F1800
M104 S0  
M140 S0  
G1 Z85
G1 X85 Y85
```
When the printer has finished, all driver will be deactivated immediately.
So i think it's a bug-

**Comment by AnHardt** [comment] 2017-12-04 21:43
From SD or via USB?

```
#define SD_FINISHED_STEPPERRELEASE true          // Disable steppers when SD Print is finished
#define SD_FINISHED_RELEASECOMMAND "M84 X Y Z E" // You might want to keep the z enabled so your bed stays in place.```

**Comment by revilor** [comment] 2017-12-05 03:09
Could also be the slicer adding M84 at the end of the g-code.

**Comment by Roxy-3D** [comment] 2017-12-05 03:56
If the nozzle is falling down...  It kind of sounds like the motors are being turned off.

Maybe the 'right' answer is for your end time Gcode to move the nozzle to a 'safe' corner and then turn off the motors?

**Comment by bjarchi** [comment] 2017-12-05 04:08
> Could also be the slicer adding M84 at the end of the g-code.

@jowa01 you said your end gcode was this:
>End of Gcode:
G92 E0
G1 E-1.4000 F1800
M104 S0
M140 S0
G1 Z85
G1 X85 Y85

Is that what you told your slicer to do, or have you checked a sliced file itself? Might be worth looking to make sure some revision of the slicer didn't start adding M84 regardless of whether it's in your custom postamble.

**Comment by jowa01** [comment] 2017-12-05 17:41
Printed by sd card.
No safe corner on this little printer.
Gcode is from a sliced file itself.

This line in Configuration_adv.h was the Problem.
```cpp
#define SD_FINISHED_RELEASECOMMAND "M84 X Y Z E"
```
I changed it to
```cpp
#define SD_FINISHED_RELEASECOMMAND "M84 X Y E"
```
and now the nozzle stay forever on position.

So it's not a bug but a new feature in V1.1.6

Thanks a lot!

**Comment by bjarchi** [comment] 2017-12-06 20:33
So... seems like this is resolved and not a bug? If so, could you close the issue? 

Thanks.

**Closed as completed** 2017-12-08 09:07 UTC
Labels: Bug: Potential ?, Needs: More Data

**Comment by thinkyhead** [comment] 2017-12-16 01:54
> So it's not a bug but a new feature in V1.1.6

Nope. `SD_FINISHED_RELEASECOMMAND` has been in Marlin for many years — since "1.0" before it started getting real version numbers.
