### ISSUE TITLE
[BUG] TFT_LVGL_UI all pics No data blocks for MKS robin nano V1.2 & MKS_ROBIN_TFT35 despite RGB565 images present(tryed mks_pic/mks_font/assets)

### ISSUE THREAD

**Issue by sunnydrake** [MarlinFirmware/Marlin#24442] opened 2022-07-02 17:59 UTC
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

printer Creasee CS30 
compile config thru PlatformIO/VSCode with options
#define MKS_ROBIN_TFT35
#define TFT_LVGL_UI 1
default_envs = mks_robin_nano35
copy all files to sdcard assets* Robin*.bin , make folders mks_font and mks_pic + copy corresponding bin files there
checked bin file with https://rawpixels.net/ width:117  height:88 images is there
flashed and screen is .... 
![IMG_20220702_190759 1](https://user-images.githubusercontent.com/15017432/177010907-a52911c2-c483-45fb-b25b-295d71f2e07d.jpg)

Try marlin 2.0/2.1 branches bug still persist

### Bug Timeline

2.0 branch

### Expected behavior

icons shown

### Actual behavior

text No Data

### Steps to Reproduce

1.compile with
#define MKS_ROBIN_TFT35
#define TFT_LVGL_UI 1
default_envs = mks_robin_nano35
2.flash via sdcard
3.observe screen

### Version of Marlin Firmware

2.1. bugfix branch

### Printer model

Creasee CS30

### Electronics

stock,robin nano V1.2 it seems

### Bed Leveling

MBL Manual Bed Leveling

### Your Slicer

Cura

### Host Software

OctoPrint

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/9033400/Configuration.zip)

**Comment by mrnrod45** [comment] 2022-07-04 19:14
I have the Same Issue as this upon flashing to my Elegoo Neptune 2. it is the same board type mks_robin_nano35. Here is my configuration as well.
[Configurations.zip](https://github.com/MarlinFirmware/Marlin/files/9041687/Configurations.zip)

**Comment by Sergey1560** [comment] 2022-07-06 08:34
The problem is related to the fact that the sd card is not mounted. Therefore, images are not copied.

**Comment by sunnydrake** [comment] 2022-07-06 19:20
i tried long mounting sdcard option from config - it's same :(

**Comment by rhapsodyv** [comment] 2022-07-09 03:38
This board is sdio, so maybe it’s related with our recent sdio issue.
Take a look in the ongoing PR: #24470

**Comment by thisiskeithb** [comment] 2022-07-09 16:30
https://github.com/MarlinFirmware/Marlin/pull/24470 has been merged, so please download [`bugfix-2.1.x`](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.1.x.zip) to test with the latest code and let us know if you're still having this issue.

**Comment by mrnrod45** [comment] 2022-07-16 19:28
I tested with bugfix-2.1.x and still no icons. But my printer no longer boot loops

**Comment by rhapsodyv** [comment] 2022-07-16 19:51
I just tested lastest bugfix-2.1.x and it fully worked. It loaded the assets, boot, no freeze, all icons, no boot loop.

![1F5BA85B-481C-4026-B773-1E04CD354288](https://user-images.githubusercontent.com/81722/179370047-0abe06d2-f56d-4e78-b416-0e45901f729e.jpeg)

**Comment by rhapsodyv** [comment] 2022-07-16 19:51
Try another sd or formatting this one.

**Closed as completed** 2022-07-16 19:57 UTC
Labels: C: LCD & Controllers, F: SD Card / Media
