### ISSUE TITLE
[BUG] [Bugfix 2.0.x] Button not working for pause on stow/deploy with G29 P1 (same with #13114)

### ISSUE THREAD

**Issue by robbycandra** [MarlinFirmware/Marlin#13705] opened 2019-04-15 03:43 UTC
Nothing happened when user push the button.
Problem exist in UBL, but not in ABL.
 
Problem in probe.cpp -> probe_specific_action

```
        PGM_P const ds_str = deploy ? PSTR(MSG_MANUAL_DEPLOY) : PSTR(MSG_MANUAL_STOW);
        ui.return_to_status();       // To display the new status message
        ui.set_status_P(ds_str, 99);
        serialprintPGM(ds_str);
        SERIAL_EOL();

        KEEPALIVE_STATE(PAUSED_FOR_USER);
        wait_for_user = true;
        #if ENABLED(HOST_PROMPT_SUPPORT)
          host_prompt_do(PROMPT_USER_CONTINUE, PSTR("Stow Probe"), PSTR("Continue"));
        #endif
        while (wait_for_user) idle();
        ui.reset_status();
        KEEPALIVE_STATE(IN_HANDLER);
```

same with #13114

**Comment by jackwilsdon** [comment] 2019-04-18 16:12
I can confirm this is an issue for me too.

**Comment by boelle** [comment] 2019-07-21 19:05
Lack of Activity
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.

**Comment by boelle** [comment] 2019-09-24 13:01
@robbycandra & @jackwilsdon is this still an issue in latest 2.0.x ?

**Comment by robbycandra** [comment] 2019-09-24 16:06
@boelle , never try again.

**Comment by boelle** [comment] 2019-10-12 11:20
Lack of Activity
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.

**Comment by timeburn** [comment] 2019-11-18 00:23
This is still an issue in the latest, as of today.  ABL is fine, UBL hangs at "Deploy Z-Probe"
Curiously, the deploy/stow works fine for Delta Calibration, just not UBL

**Comment by sjasonsmith** [comment] 2019-11-18 01:13
I can also confirm this issue exists, at least on delta. I didn’t realize there was already an issue reported, it was on my lift to report. @boelle, can you re-open this?

**Comment by sjasonsmith** [comment] 2019-11-18 01:15
I guess there are others open now too, so as long as one is open we should be good.

**Comment by timeburn** [comment] 2019-11-24 04:48
This was solved under issue 15927.  my bad for opening a dupe, but it's fixed now

**Comment by boelle** [comment] 2019-12-02 21:50
closing since its solved 



> This was solved under issue 15927.

**Closed as completed by boelle** 2019-12-02 21:50 UTC
Labels: Bug: Confirmed !
