### ISSUE TITLE
workaround found, please read: bugfixes-2.0.x on a DUE/RADDS: compile error with POWER_SUPPLY 1

### ISSUE THREAD

**Issue by HWiese1980** [MarlinFirmware/Marlin#11145] opened 2018-06-29 17:25 UTC
### Description

I'm on branch bugfixes-2.0. I'm getting the following compile error when I set POWER_SUPPLY to 1 in my Configuration.h. The target system is a Arduino Due with BOARD_RADDS. 

Here's the error message: https://pastebin.com/8SRHymWt

### Steps to Reproduce

1. Set target to Arduino Due, board to BOARD_RADDS in Configuration.h (haven't tried other boards)
2. set POWER_SUPPLY to 1
3. try to compile

**Expected behavior:** 
no compilation error

**Actual behavior:** 
compilation error (see link)

#### Additional Information

All I've changed in the Configuration.h is MOTHERBOARD and POWER_SUPPLY. Everything else is at commit 42f99214822cee44279d34e6523b539e057de385. 

### Update 1: 

I was able to compile everything with `POWER_SUPPLY 1` after removing **all** comments that follow in the same lines as `#define`s.

e.g. change: 

    #define PS_ON_PIN          40 // SERVO3_PIN

to 

    #define PS_ON_PIN          40

Somehow the 1.9.0 Arduino preprocessor doesn't seem to like comments right after a #define

**Comment by thinkyhead** [comment] 2018-06-29 21:06
Duplicate of several other issues. This is a known problem that has cropped up with various versions of Arduino IDE.

**Closed as completed by thinkyhead** 2018-06-29 21:06 UTC

**Comment by HWiese1980** [comment] 2018-06-30 06:40
I see, thank you very much @thinkyhead
