### ISSUE TITLE
[BUG] Z-Stepper Auto-alignment  fails in current BigFix build

### ISSUE THREAD

**Issue by bill-orange** [MarlinFirmware/Marlin#20286] opened 2020-11-26 16:43 UTC
### Bug Description : 

Z-Stepper Auto-alignment fails in current bugfix.  The carriage moves too far toward home, causing the level sensor to miss the bed and crash the extruder.  This function was working normally until my most recent build.  I suspect something changed in the last two weeks affecting this feature.  This may be a symptom of #20278 

### Configuration Files:

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/5604257/Marlin.zip)

### Steps to Reproduce

1. run Z-Stepper Auto-Alignment from a G34 or front panel
2. observe the nozzle crash after miss-positioning of the extruder in the X plane.

**Expected behavior: Normal functionality as with builds from a few weeks ago.

**Actual behavior: Extruder crash and failure warning.

#### Additional Information

In the last few days, I added a runout sensor following the Chris's Basement and Teaching Tech videos. I don't see how these configuration changes could affect this issue.  

In Configuration_adv.h `// If not defined, probe limits will be used.` Indicates that without defining limits all should be well.  That is no longer the case.  A partial solution is to use  `#define Z_STEPPER_ALIGN_XY {  {50, 110}, {195,110} }` .  This option generates a out of bounds error id a desirable high value is taken of the second X position.  I can only go to 195.  I should be able to go to 230.

**Comment by thisiskeithb** [comment] 2020-11-26 21:28
Duplicate of #20278

**Closed as completed by thisiskeithb** 2020-11-26 21:28 UTC
