### ISSUE TITLE
Manual move display shows 0 twice in a row

### ISSUE THREAD

**Issue by SpaceCadet-Code** [MarlinFirmware/Marlin#10420] opened 2018-04-15 02:27 UTC
When Manually stepping the z axis in .1 increments, the LCD shows that the axis goes to zero then the next step is also zero then negative zero point one. The axis is physically moving in the correct increments (verified by calipers and movement of the axis) but the zero is repeated on the display

The pattern is as follows 
0.1
0
0
-0.1
Whereas it should be
0.1
0
-0.1
-0.2

I have a prusa i3 on a ramps 1.4 board with the newest marlin main release installed.

**Comment by Roxy-3D** [comment] 2018-04-15 02:49
How about more data?   Please start at +.5 and go to -.5.   I'm wondering if we are seeing a floating point round off error.      Going from +.5 to -.5 will let us see more about the movement.

**Comment by SpaceCadet-Code** [comment] 2018-04-15 02:55
It moves 1.1

**Comment by Roxy-3D** [comment] 2018-04-15 03:04
Does it move 1.1 mm according to the LCD Display?   And does M114 report a 1.1 mm movement?
Because if the nozzle is moving 1.1 mm but the LCD Display gives the correct number it means your steps per unit is defined wrong.

**Comment by SpaceCadet-Code** [comment] 2018-04-15 03:08
it moves 1 mm according to the display and command but 1.1 according to using calipers to check it. When moving at zero the axis physically moves .1 but the display shows zero for both .1 movements

**Comment by SpaceCadet-Code** [comment] 2018-04-15 03:09
This only happens when moving across zero all other above and below movements and measurements are good

**Comment by Roxy-3D** [comment] 2018-04-15 03:20
And...   If you start at 0.0 mm and move .1 it still displays 0.0 mm, right?   But what happens if you move .01 more?    My guess is we are seeing a floating point math rounding issue.

Have you printed a 20mm calibration cube?   That would be helpful to have?   What are its actual dimensions?

**Comment by thinkyhead** [comment] 2018-04-15 23:56
Please test with the latest `bugfix-1.1.x` (and/or `bugfix-2.0.x`) branch to see where it stands. If the problem has been resolved then we can close this issue. If the issue isn't resolved yet, then we should investigate further.

**Comment by SpaceCadet-Code** [comment] 2018-04-16 05:38
Haven't uploaded the bugfix yet but here is the M114 output on both "zeros"
1:37:18.322: X:-28.00 Y:-5.00 Z:0.00 E:0.00 Count X:-2800 Y:-500 Z:0
1:37:33.744: X:-28.00 Y:-5.00 Z:-0.10 E:0.00 Count X:-2800 Y:-500 Z:-160

**Comment by SpaceCadet-Code** [comment] 2018-04-16 05:39
Going to try the bug fix in a minute just thought I would share that

**Comment by SpaceCadet-Code** [comment] 2018-04-16 05:49
Same issue with the bugfix
this is going from point one to the first "Zero" to the next then to negative point one
1:46:10.130: X:-28.00 Y:-5.00 Z:0.20 E:0.00 Count X:-2800 Y:-500 Z:320
1:46:20.544: X:-28.00 Y:-5.00 Z:0.10 E:0.00 Count X:-2800 Y:-500 Z:160
1:46:45.130: X:-28.00 Y:-5.00 Z:-0.00 E:0.00 Count X:-2800 Y:-500 Z:0
1:47:08.607: X:-28.00 Y:-5.00 Z:-0.10 E:0.00 Count X:-2800 Y:-500 Z:-160

**Comment by thinkyhead** [comment] 2018-04-16 07:22
Just Z or are other axes also affected?

**Comment by SpaceCadet-Code** [comment] 2018-04-16 07:25
All axis actually. Didn't check before.

**Comment by thinkyhead** [comment] 2018-04-16 07:26
And always (and only) on zero, eh? That's a clue, but a clue to what I'm not sure.

**Comment by SpaceCadet-Code** [comment] 2018-04-16 07:33
Yeah only when crossing zero. Just figured out possibly what it is. If I step it through the PC interface it goes to -.09 after it crosses zero. Above it it is okay but as soon as I hit zero it goes 0.0 then -0.09 and the same if I set it to go to -0.3 then step it through the interface it goes to .09 after crossing zero going positive.

**Comment by thinkyhead** [comment] 2018-04-16 07:36
Hmm, see if the code in this branch works any better:
https://github.com/thinkyhead/Marlin/archive/bf1_fix_and_improve.zip

**Comment by SpaceCadet-Code** [comment] 2018-04-16 07:59
Still the same.

**Comment by thinkyhead** [comment] 2018-04-16 08:06
Ok, I'll keep looking into it.

**Comment by thinkyhead** [comment] 2018-04-16 08:38
> …it goes to -.09 after it crosses zero. Above it it is okay but as soon as I hit zero it goes 0.0 then -0.09 and the same if I set it to go to -0.3 then step it through the interface it goes to .09 after crossing zero going positive.

I find this hard to comprehend. Can you restate?

**Comment by SpaceCadet-Code** [comment] 2018-04-16 08:44
I tried using repetier to step it manually instead of the encoder and LCD menu. I set the axis to .3 exactly then start moving down manually by .1. When I reach zero the next increment goes to -.09 instead of -.1  according to the displayed numbers on the main info screen on the LCD.

**Comment by thinkyhead** [comment] 2018-04-16 09:36
Ah, so it's float rounding. It's actually -0.099999. That's something I know how to fix!

**Comment by thinkyhead** [comment] 2018-04-16 09:45
Try [this](https://github.com/thinkyhead/Marlin/archive/bf1_fix_and_improve.zip) again and see if the rounding works any better.

**Comment by SpaceCadet-Code** [comment] 2018-04-23 03:02
Can't download it. Sorry for the long reply something went haywire after switching firmwares so many times. Think my EEprom was corrupted possibly anyways new ramps and arduino so I will try it whenever you get it uploaded.

**Comment by thinkyhead** [comment] 2018-04-24 14:10
Changes have been merged, so just grab the latest code.

**Comment by SpaceCadet-Code** [comment] 2018-04-28 20:28
Finally got bugfix 2.0 to work ( the compile name too long issue) but the double zero is still there..

**Comment by Bob-the-Kuhn** [comment] 2018-04-29 00:33
Try this file.

I was able to reproduce the issue when using a LCD and movig the axis in 0.1mm steps.

The LCD's float to string routine truncates the number at the last displayed digit rather than rounding.  When I added some more decimal places the display showed 
0.200
0.100
0.000
-0.099
-0.199

[utility.zip](https://github.com/MarlinFirmware/Marlin/files/1958318/utility.zip)

**Comment by SpaceCadet-Code** [comment] 2018-04-29 01:26
Yep mine does the same so I guess the better question is if this is the case is why does it do this only after crossing zero?

**Comment by thinkyhead** [comment] 2018-04-29 01:34
Because of the way floating-point works.

**Comment by thinkyhead** [comment] 2018-04-29 01:37
Because of the way floating-point works. It's a good question for IEEE.

**Comment by Bob-the-Kuhn** [comment] 2018-04-29 01:46
Did the new utility fix the problem?

**Comment by thinkyhead** [comment] 2018-04-29 02:12
To deal with it universally it's simplest to apply the updated `FIXFLOAT` macro to all the `utility.*` string conversion functions. The extra logic there won't have any major impact since these functions are used infrequently.

**Comment by SpaceCadet-Code** [comment] 2018-04-29 04:36
Sorry to be a bother but that didn't work downloaded the newest bugfix https://photos.google.com/share/AF1QipPfYc_uckSNWhqct3L-dGgoZFKGt1Zv_XIyi_VR2y7FtWPirNdAQ9gzZ9erngsFhQ?key=bXZrVDlOMGU4ZkRkRGRTRFNMM1ZyM3VPUkxDdTZn

**Comment by thinkyhead** [comment] 2018-04-29 10:29
Then… we'll just keep on tweaking it till it works.

**Comment by Bob-the-Kuhn** [comment] 2018-04-29 16:28
Just in case ...

Here's the low level routines with rounding.

[utility (2).zip](https://github.com/MarlinFirmware/Marlin/files/1958943/utility.2.zip)

**Comment by thinkyhead** [comment] 2018-04-30 00:18
Thanks! Actually yours is better (and faster) since it does the rounding in integer up to the least significant digit, whereas `FIXFLOAT` only deals with float imprecision, and operates in float.

**Comment by thinkyhead** [comment] 2018-04-30 01:31
Updated the patch, so hopefully this covers it!

**Comment by boelle** [comment] 2019-02-20 11:43
@thjubeck was the problem solved in latest bugfix 2.0?

**Comment by boelle** [comment] 2019-03-06 11:57
@thinkyhead i think we can close this one

**Comment by boelle** [comment] 2019-03-17 11:42
i cant reproduce this one

**Closed as completed** 2019-03-17 17:58 UTC
Labels: Bug: Potential ?, C: LCD & Controllers
