### ISSUE TITLE
[BUG] Probe offset wizard broken when PAUSE_BEFORE_DEPLOY_STOW is enabled

### ISSUE THREAD

**Issue by lucaf86** [MarlinFirmware/Marlin#26978] opened 2024-04-17 07:38 UTC
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Probe offset wizard doesn't work and exist just after homing all axes.
I have a fix mounted probe attached to z_min that requires a manual deploy, so I enabled  PAUSE_BEFORE_DEPLOY_STOW to interactively attach and detach the probe when need.
This seems to break the probe offset wizard because entering the menù and starting it causes the injection of G28 g-code that starts the homing procedure, which means to return to the main screen to deploy the probe, but after homing all the axis the probe offset wizard screen doesn't show up and the lcd is still on the main screen.

I narrowed down the issue in goto_probe_offset_wizard():

```
void goto_probe_offset_wizard() {
  ui.defer_status_screen();
  set_all_unhomed();

  // Store probe.offset.z for Case: Cancel
  z_offset_backup = probe.offset.z;

  #ifdef PROBE_OFFSET_WIZARD_START_Z
    probe.offset.z = PROBE_OFFSET_WIZARD_START_Z;
  #endif

  // Store Bed-Leveling-State and disable
  #if HAS_LEVELING
    menu_leveling_was_active = planner.leveling_active;
    set_bed_leveling_enabled(false);
  #endif

  // Home all axes
  queue.inject_P(G28_STR);

  ui.goto_screen([]{
    _lcd_draw_homing();
    if (all_axes_homed()) {
      z_offset_ref = 0;             // Set Z Value for Wizard Position to 0
      ui.goto_screen(prepare_for_probe_offset_wizard);
      ui.defer_status_screen();
    }
  });

}

```

after queue.inject_P(G28_STR); the printer starts the homing procedure returning to the main screen due to the interactivity required to deploy the probe with button confirmation, but then the check on all_axes_homed() in the  ui.goto_screen() is done too early and the prepare_for_probe_offset_wizard is skipped by exiting.
I tried to do a manual homing before and commented out 

```
// set_all_unhomed();
.. 
// queue.inject_P(G28_STR);
// _lcd_draw_homing();
```
 This way the probe offset wizard works as expected. This should means that the manual deploy of the probe breaks in some way the expected behaviour

### Bug Timeline

unknown

### Expected behavior

Probe offset wizard menù should come up on the lcd after homing all axes and after the probe stow confirmation happens with the button

### Actual behavior

No probe offset wizard is shown and lcd remains on the main screen

### Steps to Reproduce

1. enter Probe offset wizard menù
2. axes homing starts
3. X and Y homed
4. lcd goes to the main screen and asks to manually deploy the probe. Confirm by pressing the button when done
5. Z homing happens
6. lcd asks to stow the probe. Confirm by pressing the button when done
7. lcd stays on the main screen and nothing else happens, no probe wizard menù is shown on the lcd

### Version of Marlin Firmware

bugfix-2.1.x (245db739291155a48de777ebbdb4023e8975b61e)

### Printer model

Malyan M150

### Electronics

stock Melzi with optiboot

### LCD/Controller

stock lcd

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Simplify3D

### Host Software

SD Card (headless)

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/15007215/Marlin.zip)

**Comment by thisiskeithb** [comment] 2024-04-17 07:54
Duplicate of https://github.com/MarlinFirmware/Marlin/issues/23591

**Closed as completed by thisiskeithb** 2024-04-17 07:54 UTC
