### ISSUE TITLE
[1.1.7] Blue LED turns off at full brightness

### ISSUE THREAD

**Issue by Zacharandir** [MarlinFirmware/Marlin#8809] opened 2017-12-16 20:24 UTC
Bug Report
- Description: My blue LED light turns off when set to 255, works fine for values less than 255
- Expected behaviour:  Send M150 B255 LED strip turns blue
- Actual behaviour: Send M150 B255 Blue LED turns off 
- Steps to reproduce:
  Send M150 B255 light turns off 
  Send M150 B254 Light comes back on
OR 
  Navigate to LED Control --> Custom Lights --> Blue Intensity
  Set Blue intensity to 255

Configuration files attached:
[Configurations.zip](https://github.com/MarlinFirmware/Marlin/files/1565076/Configurations.zip)

**Comment by thinkyhead** [comment] 2017-12-16 23:46
Just the blue pin? Can you try switching the pin numbers in your configs and see if it still affects only the blue pin? Swap blue with red so it's obvious…
```cpp
#if ENABLED(RGB_LED) || ENABLED(RGBW_LED)
  #define RGB_LED_R_PIN 4 //34
  #define RGB_LED_G_PIN 5 //43
  #define RGB_LED_B_PIN 6 //35
  #define RGB_LED_W_PIN -1
#endif
```

**Comment by thinkyhead** [comment] 2017-12-16 23:48
Just the blue pin? Can you try switching the pin numbers in your configs and see if it still affects only the blue pin? Swap blue with red so it's obvious…
```cpp
#if ENABLED(RGB_LED) || ENABLED(RGBW_LED)
  #define RGB_LED_R_PIN 4 //34
  #define RGB_LED_G_PIN 5 //43
  #define RGB_LED_B_PIN 6 //35
  #define RGB_LED_W_PIN -1
#endif
```
If it changes behavior so that the red pin comes on when it's supposed to be off, that could mean a pin conflict — where pin 4 is also being used for something else.

**Comment by Tannoo** [comment] 2017-12-17 00:35
Works fine for me on bugfix-2.0.x.

**Comment by Tannoo** [comment] 2017-12-17 03:20
I would say try `bugfix-1.1.x` and see if the issue is still there.

**Comment by Tannoo** [comment] 2017-12-17 03:21
This has always been my setup:
```
  #define RGB_LED_R_PIN 4
  #define RGB_LED_G_PIN 5
  #define RGB_LED_B_PIN 6
```

**Comment by Zacharandir** [comment] 2017-12-17 05:56
I swapped pins, and it appears to be associated with Pin 4. I haven't encountered anything turning on when it's supposed to be off, only the opposite. I am looking for possible conflicting pins. Case light is also assigned to pin 4 but I have it disabled. I will try the bug fix branch when I get a chance.


EDIT:
Tried bugfix1.1.x, behavior unchanged.

**Comment by thinkyhead** [comment] 2017-12-17 06:38
> This has always been my setup

@Tannoo — With `BOARD_RAMPS_14_EEB` the fan pin gets assigned to pin 4 (as an alternative to the usual MOSFET connectors).

---
> Tried bugfix1.1.x, behavior unchanged.

@Zacharandir — Try adding to your `Configuration.h`…
```cpp
#define FAN_PIN -1
```

**Comment by Tannoo** [comment] 2017-12-17 16:21
Ah... ok. I have `BOARD_RAMPS_14_EFB`.

I also use the filament runout sensor and had to re-assign its pin to 11.

**Comment by Zacharandir** [comment] 2017-12-17 18:43
I added that and it seemed to fix my issue. Thank you for the help. Will adding that line affect the part cooling fan? I have one but I have not yet installed it.

Is there a physical difference between BOARD_RAMPS_14_EeB and BOARD_RAMPS_14_EFB or is it just a change in pin assignments? I recently had to replace my Ramps 1.4 and I'm not sure that I have an exactly identical replacement.

**Comment by Tannoo** [comment] 2017-12-17 20:09
It's just pin assignments.

**Comment by Tannoo** [comment] 2017-12-17 20:12
Those board assignments refer to the D8, D9, and D10 mosfet outputs.

EEB = Extruder, Extruder, Bed
EFB = Extruder, Fan, Bed

**Comment by thinkyhead** [comment] 2017-12-18 03:14
> Will adding that line affect the part cooling fan? I have one but I have not yet installed it.

At that time you'll change `FAN_PIN` from -1 to whatever pin your fan is attached to.

**Closed as completed** 2017-12-18 03:15 UTC
Labels: T: Question, C: Configuration
