### ISSUE TITLE
Layershift

### ISSUE THREAD

**Issue by dblatt87** [MarlinFirmware/Marlin#23327] opened 2021-12-20 22:26 UTC
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

First of all I wan't to say thanks to all the developpers, making this great firmware possible!

I have heavily layer shifts (1-2cm) even with very conservative acceleration (1500) jerk (2) or JD (0.01) settings on my coreXY Sapphire plus:
MKS Robin Nano 1.2
TMC2209 drivers

I report this as a Bug because with Marlin 2.0.8 I didn't have these problems with way more aggressive settings.

Already tested in 2.0.9.3 without sucess (with the same benchy gcode, with outcomentet extruder, @60mm/s):
- with/withou LinAdvance
- with/withou S-Curve accelaration
- Classic jerk and Junction deviation
- Stepper current 0.8-1.2A
- Stepper Timing (MINIMUM_STEPPER_PULSE / MINIMUM_STEPPER_..._DIR_DELAY)
- Spreadcycle
- no bed leveling

After X-Mas hollidays I can check the versions between to specify first occurance.
Maybe until then someone has a guess where to start.

### Bug Timeline

tested on 2.0.8 (no issue) and 2.0.9.3 (issue)

### Expected behavior

no layer shifts

### Actual behavior

layer shifts

### Version of Marlin Firmware

2.0.9.3

### Printer model

TT Sapphire Plus

### Electronics

MKS Robin Nano 1.2, TMC 2209

### Add-ons

Directdrive extruder (Orbiter)

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Cura

### Additional information & file uploads

Detailed settings in my Fork [https://github.com/dblatt87/Marlin-for-TT-Sapphire-Plus/](url).

[3DBenchy_dry.zip](https://github.com/MarlinFirmware/Marlin/files/7748244/3DBenchy_dry.zip)

**Comment by thisiskeithb** [comment] 2021-12-20 22:54
Duplicate of https://github.com/MarlinFirmware/Marlin/issues/22967

**Closed as completed by thisiskeithb** 2021-12-20 22:54 UTC
