### ISSUE TITLE
[FR] Extruder stepper direction change from lcd

### ISSUE THREAD

**Issue by esunayg** [MarlinFirmware/Marlin#21645] opened 2021-04-17 19:50 UTC
### Is your feature request related to a problem? Please describe.

Different extruders have different mechanical direction. It is possible to recompile or reverse the pins but it sometimes costs a mainboard, and hard for people with no electrical background.

### Are you looking for hardware support?

generic

### Describe the feature you want

Extruder stepper direction change without recompling or changing the ex pins via the screen.

**Comment by thisiskeithb** [comment] 2021-04-17 22:51
Duplicate of https://github.com/MarlinFirmware/Marlin/issues/16550

**Closed as completed by thisiskeithb** 2021-04-17 22:51 UTC
Labels: T: Feature Request, C: User Interface
