### ISSUE TITLE
[FR] Rewrite Mixing Extruder to allow Distinct E Factors

### ISSUE THREAD

**Issue by rsdcampos** [MarlinFirmware/Marlin#22495] opened 2021-08-02 23:57 UTC
### Is your feature request related to a problem? Please describe.

I need use my diamond nozzle with my printer, but I have distincts step motors and extruders, but Marlis dont let use distinct e factors and mixing extruder in sametime.

### Are you looking for hardware support?

I have a prusa like printer with Fysetc S6 motherboard and a diamond (3 color mixing) nozzle,

### Describe the feature you want

When I tried to build the Marlin with MIXING_EXTRUDER  and DISTINCT_E_FACTORS together, this error appears --> error: #error "MIXING_EXTRUDER can't be used with DISTINCT_E_FACTORS. But you may use SINGLENOZZLE with DISTINCT_E_FACTORS."
I see that I could use Single nozzle with 3 extruders and distinct e factor, but this way I miss the mixing feature that is very useful and I don't know why this can't be used together.

**Comment by snakesrules94** [comment] 2021-08-03 08:53
Hello , this configuration was ok in 2.0.7.2 if i'm right . After this version, indeed , the behaviour is as you decribe .
I used to have this config for my A20M in 2.0.7.2 and now , i have to comment DISTINCT_E_FACTORS and use the same steps for both steppers ( not a big deal as they are the same in my case ).

**Comment by rsdcampos** [comment] 2021-08-03 14:34
So this is not a feature request, but a feature return...
In first time I thought it was a bug, but the error log let clear that it is purposely, because of it I opened a FR.

**Comment by thinkyhead** [comment] 2021-08-03 23:44
This is intentional, to allow the handling of mixing at the steps level instead of at some higher level that would invoke more float maths. So, if a rewrite of this feature is wanted, someone will have to undertake it as a new project.

**Comment by rsdcampos** [comment] 2021-08-04 13:51
Ok, I understood, maybe some day... Thanks anyway.

**Comment by thinkyhead** [comment] 2021-08-06 04:27
Duplicate of #8145

**Closed as completed by thinkyhead** 2021-08-06 04:27 UTC
Labels: T: Feature Request
