### ISSUE TITLE
[FR] Single SCARA support?

### ISSUE THREAD

**Issue by Power3DPrinting** [MarlinFirmware/Marlin#13589] opened 2019-04-06 02:05 UTC
Hi, is single SCARA kinematics supported by Marlin as of mid 2019? if not, could anyone share how to rewrite the kinematics or add in a translator? Been curious for a while about 3D printer firmware and would really like to learn how to write my own. Thanks.

**Comment by thisiskeithb** [comment] 2022-01-21 14:14
Duplicate of https://github.com/MarlinFirmware/Marlin/issues/10089

**Closed as completed by thisiskeithb** 2022-01-21 14:14 UTC
Labels: T: Feature Request, K: SCARA
