### ISSUE TITLE
[BUG]  "One or more timer conflict detected" when trying to compile using mks_robin_nano35_stm32

### ISSUE THREAD

**Issue by th0m4sek** [MarlinFirmware/Marlin#20387] opened 2020-12-06 09:54 UTC
### Bug Description

```
`Marlin/src/HAL/STM32/timers.cpp:281:41: error: static assertion failed: One or more timer conflict detected
  281 | static_assert(verify_no_duplicate_timers(), "One or more timer conflict detected");
      |               ~~~~~~~~~~~~~~~~~~~~~~~~~~^~`
```

same configuration working fine when compiling with mks_robin_nano35
using tmc2209 with uarts connected to one pin.

### Configuration Files

[Marlinconf.zip](https://github.com/MarlinFirmware/Marlin/files/5648554/Marlinconf.zip)

### Steps to Reproduce

compile attached files

**Expected behavior:**

posibility to compile with mks_robin_nano35

**Actual behavior:**

**Comment by th0m4sek** [comment] 2020-12-08 12:13
Solution from https://github.com/MarlinFirmware/Marlin/pull/19905
```
#if defined(ARDUINO_ARCH_STM32) && !defined(STM32GENERIC)
  // Variant default conflicts with Servo timer
  #define TEMP_TIMER 5
#endif
```
worked for my MKS Robin Nano V1.2
Maybe this should be merged?

**Comment by rhapsodyv** [comment] 2020-12-08 18:38
@sjasonsmith we can merge it? or it's just a temporary hack?

**Comment by sjasonsmith** [comment] 2020-12-08 18:43
I would like to try to find a more flexible way to solve it. As more boards move to the STM32 HAL this will continue to be a problem, and it would be nice to not have to manually define the timer for each board. Not every board should use the same timers for this, due to other conflicts.

**Comment by sjasonsmith** [comment] 2020-12-20 06:14
I've updated the provided configs to reproduce the problem using the current state of bugfix-2.0.x.
I tried to preserve all the original settings, but no promises. My goal is just to reproduce the compilation issue.
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/5720601/Configuration.zip)

**Comment by th0m4sek** [comment] 2020-12-20 08:40
updated conf on current bugfix is acting as before - can be compiled with mks_robin_nano but not with mks_robin_nano_stm32

**Comment by sjasonsmith** [comment] 2020-12-20 08:49
Sorry, I wasn't suggesting that I've fixed it, I just updated them to provide failing configs that work with the current bugfix.

I think I have a more flexible solution semi-ready, but I haven't yet tried it with any hardware. I'm about to post it as a Draft pull request to see if it passes our build tests, and to solicit feedback.

**Comment by th0m4sek** [comment] 2020-12-20 08:51
i was not sure what you wanted to communicate but i wanted to show that i'm ready to help at least with testing ;)

**Comment by sjasonsmith** [comment] 2020-12-20 09:05
@th0m4sek I appreciate the willingness to help. I just posted that draft. I'll tag you again when it is ready for you to try out. I'd like to test it with some of my own hardware first.

**Comment by sjasonsmith** [comment] 2020-12-22 20:13
This conflict should now be resolved, along with several other boards with similar issues.
I'm closing this, but please let us know if you continue to see issues with the latest changes from `bugfix-2.0.x`.

**Closed as completed by sjasonsmith** 2020-12-22 20:13 UTC
