### ISSUE TITLE
Eeprom CRC Mismatch with PIDTEMPBED activated on Anet A8

### ISSUE THREAD

**Issue by chrunda** [MarlinFirmware/Marlin#10661] opened 2018-05-09 02:01 UTC
**Description**
When I uncomment the PIDTEMPBED (BED_LIMIT_SWITCHING is commented) in configuration.h file, I will get message:
READ: Error:EEPROM CRC mismatch - (stored) 18389 != 63926 (calculated)!
READ: echo:Hardcoded Default Settings Loaded
Hardcoded Default Settings Loaded

With uncommented BED_LIMIT_SWITCHING option (PIDTEMPBED commented) everything works fine.
I am using Marlin 1.1.8 stable

**Expected behavior:** EEPROM CRC match and is readable.

**Actual behavior:** EEPROM CRC mismatch

**Additional Information
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/1986161/Configuration.zip)
![eeprom crc mismatch](https://user-images.githubusercontent.com/15208329/39792211-e1606842-533f-11e8-9a9b-436385da593a.jpg)

**

**Comment by thinkyhead** [comment] 2018-05-09 05:32
Please test with the latest `bugfix-1.1.x` (and/or `bugfix-2.0.x`) branch to see where it stands. If the problem has been resolved then we can close this issue. If the issue isn't resolved yet, then we should investigate further.

**Comment by chrunda** [comment] 2018-05-09 07:23
OK, I will try, but do I have to use configuration.h and configuration_adv.h files from bugfix version and correct values for my settings again or I can use my already configured files from stable version 1.1.8 ?

**Comment by thinkyhead** [comment] 2018-05-10 01:19
> [can I] use my already configured files from stable version 1.1.8?

Drop them in place, try to compile. The compiler will throw errors, telling you to change some things. Change those things, and keep retrying until it compiles without error.

First thing to change…
```cpp
#define CONFIGURATION_H_VERSION 010109
```
and
```cpp
#define CONFIGURATION_H_ADV_VERSION 010109
```

**Comment by chrunda** [comment] 2018-05-10 05:37
Thank you, but I've rather reconfigured new files with my old values and everything works fine now. No more EEPROM CRC mismatch. I get some EEPROM version mismatch, but I've managed it by M500 and M502. Now I am thinking, where can I save some bytes in code, because I want to use ADVANCED_NOZZLE_PARK function and I am about 5000 bytes over maximum code size with it. Can you give me some advice?

**Comment by thinkyhead** [comment] 2018-05-10 05:59
5000 bytes is a lot to whittle down. Make sure all debug features like `DEBUG_LEVELING_FEATURE`, `PINS_DEBUGGING`, and so on are disabled. Turn off the `LCD_INFO_MENU`. And try `SLIM_LCD_MENUS` if not already enabled. If you don't care about verbose feedback, you can turn off `EEPROM_CHITCHAT` also.

**Closed as completed** 2018-05-10 06:00 UTC

**Comment by chrunda** [comment] 2018-05-10 06:41
Thanks for advice, I will try it in the evening.
