### ISSUE TITLE
[BUG] Display of real temperature on MKS H43

### ISSUE THREAD

**Issue by McDAK33** [MarlinFirmware/Marlin#21785] opened 2021-05-03 09:07 UTC
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

The display shows temperatures on Venus, but not on my printer. Doesn't affect everything else.

### Bug Timeline

There are several months. 

### Expected behavior

Observe real temperature

### Actual behavior

https://user-images.githubusercontent.com/80269041/116859498-bf0dca80-ac08-11eb-99a6-41fc8ddf635d.mp4

### Version of Marlin Firmware

2.0.8

### Electronics

MKS Robin Nano v3 + MKS-H43

### Additional information & file uploads

[Config.zip](https://github.com/MarlinFirmware/Marlin/files/6413726/Config.zip)

**Comment by ellensp** [comment] 2021-05-03 09:15
Seem to be a duplicate of https://github.com/MarlinFirmware/Marlin/issues/21603

**Closed as completed by ellensp** 2021-05-03 09:15 UTC
