### ISSUE TITLE
[BUG] REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER needs help

### ISSUE THREAD

**Issue by ruggb** [MarlinFirmware/Marlin#15745] opened 2019-11-01 00:24 UTC
I don't know when it changed, but in build bugfix-2.0.x.9e8021d this controller produces a scrambled screen. It may have something to do with u8glib or arduino since I have updated those recently. When I tried to go back to bugfix-2.0.x.9a515cb it was also scrambled and was not previously.
I found this on the reprap forum, I think. With those three lines added it works.

#define REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER
#define ST7920_DELAY_1 DELAY_NS(0)   //** scrambled screen without these
#define ST7920_DELAY_2 DELAY_NS(250) //**
#define ST7920_DELAY_3 DELAY_NS(250) //**

**Comment by lordwolfchild** [comment] 2019-11-01 13:10
I have experienced the same problem. I could nail down the problem somewhere between V1.1.8 and V1.1.9.

I have a MKS Gen 1.4 Motherboard and a RepRap Discount full graphic smart controller. I got 1.1.8 and 1.1.9  both downloaded and changed only the MOTHERBOARD to my Baseboard and activated defined REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER. With 1.1.8 everythings looks crispy and nice, with 1.1.9  the graphic output shows random shifted lines with each screen update. 

Adding the additional defines ruggb posted above, everything works just great with my config and 1.1.9 upwards.

**Comment by ruggb** [comment] 2019-11-08 00:52
reopened on #15833

**Comment by thisiskeithb** [comment] 2019-11-08 00:59
Providing configs and more information about your specific hardware would be helpful.

**Comment by ruggb** [comment] 2019-11-08 13:03
The bug was confirmed. What does that mean?

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/3824653/Marlin.zip)

**Comment by sjasonsmith** [comment] 2019-11-24 07:29
I finally pulled my display out of its box so I could try to reproduce this.

It is working fine for me, with both an SKR 1.3 and an Atmega2560/RAMPS.

**Comment by thisiskeithb** [comment] 2019-11-24 07:50
> It is working fine for me, with both an SKR 1.3 and an Atmega2560/RAMPS.

Same for me on a multitude of boards/configs.

**Comment by boelle** [comment] 2019-12-02 21:57
> The bug was confirmed. What does that mean?
> 
> [Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/3824653/Marlin.zip)

means that more than 1 person has the problem

**Comment by boelle** [comment] 2019-12-07 14:19
@ruggb since 2.0 was just released a few days ago has this changed this issue at all?

**Comment by facusenn** [comment] 2019-12-10 20:26
I had the same problem, a glitchy screen using Marlin bugfix 2.0 in at least 3 new arduino Mega+reprap full graphic controller, had to solve it using this solution:

Copy this and paste it somewhere in config.h outside of the conditional statements:

**#define ST7920_DELAY_1 DELAY_NS(50)
#define ST7920_DELAY_2 DELAY_NS(188)
#define ST7920_DELAY_3 DELAY_NS(50)**

**If this doesn't work try increasing the numbers inside the brackets.** 
It's a timing issue and delays are in nanoseconds.
This solution its the same as @ruggb proposed but with different numbers.
I don't know why but it seems hardware related, some screens do it and others don't.

[This video represents the issue](https://www.youtube.com/watch?v=yh-PQ7BpZl8)

**Comment by ruggb** [comment] 2019-12-11 20:48
@boelle Here are my findings. Maybe you can do something with it.
Ver 2.0 released 5103cdc
I viewed one signal as representative. 
Noise does not appear to be a factor as someone suggested.
What is a major diff is the signal frequency => no delay is 1.3MHz; with delay it is 850kHz
The pulse width is 2x with the delay. 200ns vs 400ns


X10 probe no delay
![# no delay 1](https://user-images.githubusercontent.com/12383390/70657637-2c8f1480-1c2a-11ea-805e-b0761b5e7c6c.jpg)
X10 probe no delay
![# no delay 2](https://user-images.githubusercontent.com/12383390/70657657-36b11300-1c2a-11ea-8e8e-5cfdc637a923.jpg)
X10 probe w/delay
![# delay 1](https://user-images.githubusercontent.com/12383390/70657669-3dd82100-1c2a-11ea-833f-c11ce10360d0.jpg)
X10 probe w/delay
![# delay 2](https://user-images.githubusercontent.com/12383390/70657677-403a7b00-1c2a-11ea-981d-bd47fb1c0371.jpg)

Here is something from
https://reprap.org/wiki/RepRapDiscount_Full_Graphic_Smart_Controller

Issues
Some versions of this board have the notched connectors the wrong way around. If your controller only flickers and beeps, cut off the notches on the cables and insert them upside down.
Some clones of this board use really slow LCD displays so their signal timings need adjusted.
The symptoms are that the display gets slightly corrupted. (which can also be cables to long)
In current versions of marlin (1.1.9) add the following to configuration.h to override the default settings.
add "#define ST7920_DELAY_1 DELAY_NS(0)"
add "#define ST7920_DELAY_2 DELAY_NS(0)"
add "#define ST7920_DELAY_3 DELAY_NS(63)" // this is the defaults for a 16mhz processor (ie a mega2560)
This is used as follows.
For each bit that is sent over SPI
Set the clock pin low and wait ST7920_DELAY_1
Set the data pin and wait ST7920_DELAY_2
Set the clock pin high and wait ST7920_DELAY_3
Slower LCD's seem to need ST7920_DELAY_3 increased.

**Comment by tfgcampos** [comment] 2020-05-14 23:44
I had the same issue when using Arduino IDE for compiling. Adjusting the delay worked partially, as I didn't find an optimal combination between delay_1, 2 and 3 to give me a sharp screen.

After giving a try on PlartformIO, the issue was solved. Probably related to u8glib used in Arduino IDE.

**Comment by ruggb** [comment] 2020-05-15 02:55
Maybe one of these days I will try PlatformIO but I am still trying to figure out Arduino.
But this totally worked for me since I did it.

**Comment by boelle** [comment] 2020-06-23 13:35
@ruggb 
Please test the [bugfix-2.0.x branch](https://github.com/MarlinFirmware/Marlin/tree/bugfix-2.0.x) to see where it stands.

**Comment by sjasonsmith** [comment] 2020-07-04 07:13
I am closing this issue as it is quite old and it isn't clear that any action is needed. Many users use these screens every day, and many timing fixes have gone in since this was originally reported over 8 months ago. A new issue can be opened if specific combinations are found to be problematic.

**Closed as completed by sjasonsmith** 2020-07-04 07:13 UTC
Labels: Bug: Confirmed !, C: LCD & Controllers, A: ATmega2560
