### ISSUE TITLE
TMC2130's stutter if parts fan is using PWM

### ISSUE THREAD

**Issue by SpeedGP** [MarlinFirmware/Marlin#8922] opened 2017-12-27 22:26 UTC
### Bug Report
- Description: When parts fan (D11 with Geetech fan extender) is off, or at 100%, X and Y axis's work fine, but if parts fan is at 1% - 99% X and Y stutter very badly and move at approx 1mm/s. Z axis (without TMC2130) is unaffected either way.
- Expected behaviour: Printer acts the same regardless of  parts fan speed
- Actual behaviour: Axises move slowly/stutter

[configuration.h.zip](https://github.com/MarlinFirmware/Marlin/files/1589973/configuration.h.zip)

**Comment by teemuatlut** [comment] 2017-12-27 22:57
Does it happen if you use another driver type on X/Y?
Does it happen if you use another pin than D11?
Does it happen with the parts fan and extender disconnected?
Does it happen if you disable `SENSORLESS_HOMING`?
Does it happen if you disable `STEALTHCHOP`?
Are the drivers made by Watterott or Fysetc?

**Comment by AnHardt** [comment] 2017-12-27 23:25
Hardware PWM on pin D11 uses an timer what is needed elsewhere. Try fan soft pwm.
The problem is likely independent from TMC-drivers.

**Comment by SpeedGP** [comment] 2017-12-28 00:39
fan_soft_pwm worked!

Thank you so much!

Sorry for the burden teemuatlut. 3D printing really wouldn't be what it is
today without you guys!




-James--

**Comment by psavva** [comment] 2017-12-28 05:03
Perhaps a sanity check is needed to avoid this conflict?

**Comment by thinkyhead** [comment] 2018-02-11 06:26
I'm not sure what the sanity would be, exactly. Checking every fan and heater pin to make sure it's not using a timer that's needed elsewhere… tricky to do for all targets. For AVR in 1.1.x maybe something like this would work…?

```cpp
#define _IS_TIMER(P,T) (_CAT(DIO,P) == T)
#if _IS_TIMER(FAN_PIN, OCR1A) && DISABLED(FAN_SOFT_PWM)
  #error "FAN_PIN conflicts with Timer 1. Choose a different pin or enable FAN_SOFT_PWM."
#endif
```

**Comment by boelle** [comment] 2019-02-19 23:51
@SpeedGP so your problem is solved?

maybe close this one?

**Comment by SpeedGP** [comment] 2019-02-20 01:47
It's been a long time. I think part of the issue was heat causing the
drivers to cut back, but also that pwm thing helped a lot. Changing the
frequency or something like that, I don't remember.

Thanks!

**Comment by boelle** [comment] 2019-03-06 11:02
@thinkyhead i think we can close this one

**Comment by Phr3d13** [comment] 2019-06-10 21:54
@thinkyhead Another one that needs to be closed. Sorry, I got bored.

**Comment by boelle** [comment] 2019-06-22 09:19
@thinkyhead Another one that needs to be closed. Sorry, I got bored.

**Closed as completed** 2019-07-06 04:24 UTC
