### ISSUE TITLE
Compiler error when no sdsupport

### ISSUE THREAD

**Issue by tonnico** [MarlinFirmware/Marlin#1759] opened 2015-03-31 17:48 UTC
Hi,

I got an error when SDSUPPORT is not defined.

```
\stepper.cpp: In function 'void TC3_Handler()':
\stepper.cpp:327:44: error: 'SD_FINISHED_STEPPERRELEASE' was not declared in this scope

     if ((cleaning_buffer_counter == 1) && (SD_FINISHED_STEPPERRELEASE)) enquecommands_P(PSTR(SD_FINISHED_RELEASECOMMAND));

                                            ^

In file included from \Marlin.h:14:0,

                 from \stepper.cpp:24:

\stepper.cpp:327:94: error: 'SD_FINISHED_RELEASECOMMAND' was not declared in this scope

     if ((cleaning_buffer_counter == 1) && (SD_FINISHED_STEPPERRELEASE)) enquecommands_P(PSTR(SD_FINISHED_RELEASECOMMAND));

                                                                                              ^

C:\Program Files (x86)\Arduino\hardware\arduino\sam\cores\arduino/avr/pgmspace.h:8:20: note: in definition of macro 'PSTR'

 #define PSTR(str) (str)

                    ^

Error compiling.
```

**Comment by AnHardt** [comment] 2015-03-31 18:30
@Wurstnase 
Can't reproduce this.
What version are you on? 
We have a different line-number currently. https://github.com/MarlinFirmware/Marlin/blob/Development/Marlin/stepper.cpp#L392

**Comment by tonnico** [comment] 2015-03-31 19:28
Sure, this is my Due-Fork, but most parts should be the same.
Did you comment out your display?

**Comment by AnHardt** [comment] 2015-03-31 20:14
@Wurstnase 
You have a PR: https://github.com/Wurstnase/Marlin4Due/pull/19
Please close this.

**Closed as completed** 2015-03-31 20:22 UTC

**Comment by AnHardt** [comment] 2015-03-31 20:32
Ah. Scot fixed that this morning.https://github.com/MarlinFirmware/Marlin/commit/3348b3bf0c3870a013422371281fb74650f83ff8
