### ISSUE TITLE
Firmware builder error

### ISSUE THREAD

**Issue by aallcott** [MarlinFirmware/Marlin#21851] opened 2021-05-09 12:19 UTC
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

Hi I have tried to get a custom firmware but I just get error. I have tried a few different configurations but still the same. I have an Ender 5 plus and have now fitted a silent board. Here is one of the build id’s e60f5746. Will you at some point support the silent board and will there be an Ender 5 plus on your firmware list

### Bug Timeline

02/05/21

### Expected behavior

Get a custom firmware 

### Actual behavior

Just said failed and error

### Steps to Reproduce

Tried different configurations and times

### Version of Marlin Firmware

2.0.7

### Printer model

Ender 5 plu

### Electronics

Silent board 

### Add-ons

Silent board

### Your Slicer

Cura

### Host Software

OctoPrint

### Additional information & file uploads

Fae4e88c

**Comment by ellensp** [comment] 2021-05-09 13:26
Duplicate of https://github.com/MarlinFirmware/Marlin/issues/21576

**Closed as completed by ellensp** 2021-05-09 13:26 UTC
