### ISSUE TITLE
HELP: 1.1.9 Bilinear bed leveling one side higher than the other

### ISSUE THREAD

**Issue by jamesbit** [MarlinFirmware/Marlin#12371] opened 2018-11-08 20:33 UTC
Hallo !

I have a Prusa i3 clone printer which is running Marlin v 1.1.9 and configured to use bilinear bed leveling.
After bed levelling I have one side little higher (about 0.70 babysteps) than the other side.
Is there a command ti compensate the bed like the original Prusa Firmware ?

Thank you....

**Comment by roel8032** [comment] 2018-11-09 22:32
If you use a proximity sensor, at every point it should detect the same amount of aluminium. Do not come to close to the iron of the screws.

**Comment by RudyBenner** [comment] 2018-11-10 16:33
If you have 2 drivers for the 2 Z stepper motors, you can get automatic bed levelling. Works very well. Need 2 or more Z steppers.

**Comment by ikarisan** [comment] 2018-11-13 19:30
Maybe this is a problem I was facing very often with my Anet A(M)8. Relative to the nozzle, where did you mount the sensor? On the side of the nozzle or in the back/front?

**Comment by thinkyhead** [comment] 2018-11-14 07:30
Duplicate of #9529

**Closed as completed by thinkyhead** 2018-11-14 07:30 UTC
