### ISSUE TITLE
Auto Bed Level bug

### ISSUE THREAD

**Issue by mtmello2003** [MarlinFirmware/Marlin#10575] opened 2018-04-30 11:18 UTC
Using Marlin bugfix-1.1.x and even bugfix-2.0.x, I saw this issue:

Linear BAL algorithm do something wrong: left side of the bed is lower then the right side, difficulting the bed adhesion.

When I enable LINEAR ADVANCE tag in the marlin, the linear BAL algorithm do the job with perfection.

The issue happen only with the linear advance is disabled.

**Comment by Lyr3x** [comment] 2018-04-30 11:30
Maybe same thing as in #10526 ?

**Comment by mtmello2003** [comment] 2018-04-30 11:52
Yes, looks like same issue even using linear (not bilinear from that #10526).

One point to remark is activating LINEAR ADVANCE the things looks like to be ok.

**Comment by thinkyhead** [comment] 2018-05-01 10:24
This issue is caused by a twisted X gantry or some other physical factor messing with your probe readings. This issue is most common on CR-10 and similar machines. There are various adjustments you can try, such as adjusting belt tension, adjusting the rollers, and making sure that cables and bowden tubes have adequate slack.

See: #5983, [#7673](https://github.com/MarlinFirmware/Marlin/issues/7673#issuecomment-351979822), #9529, and so on…

**Comment by thinkyhead** [comment] 2018-05-01 10:27
Duplicate of #7673

**Comment by thinkyhead** [comment] 2018-05-01 10:28
Duplicate of #5983

**Comment by thinkyhead** [comment] 2018-05-01 10:28
Duplicate of #9529

**Closed as completed by thinkyhead** 2018-05-01 10:27 UTC
Labels: T: Question, F: Calibration
