### ISSUE TITLE
[BUG] HAL_AVR fails to compile PWM under sanguino_atmega1284p

### ISSUE THREAD

**Issue by jediminer543** [MarlinFirmware/Marlin#15340] opened 2019-09-22 20:36 UTC
### Description

Attempting to compile the AVR `fast_pwm.cpp` under the `sanguino_atmega1284p` target results in an error due to the lack of OCR3C

Error: `Marlin/src/HAL/HAL_AVR/fast_pwm.cpp:100:46: error: 'OCR3C' was not declared in this scope`

### Steps to Reproduce

Enable the compilation of FastPWM.cpp (by enabling FAST_PWM_FAN or commenting out the #if)

**Expected behavior:** The file to compile for the target

**Actual behavior:** The file errors

#### Additional Information

This is an issue as the AVR HAL won't warn about FAST_PWM_FAN not being supported. Also it means the HAL is less effective.

**Comment by sjasonsmith** [comment] 2019-09-22 20:39
This is a duplicate of #13452.

**Closed as completed** 2019-09-23 00:22 UTC
