### ISSUE TITLE
Is anyone else having thermal problems in the newset 1.8 versION?

### ISSUE THREAD

**Issue by batata004** [MarlinFirmware/Marlin#9795] opened 2018-02-24 19:23 UTC
Hi, with the new version 1.8 I am having once in a while THERMAL SHUTDOWN messages, also I am seeing MAX TEMP error... all in the middle of a print.

My hysteresis values are very generous (over 3 minutes) and I am pretty sure this is not the problem. So I was wondering if anyone else if having thermal problems/errors with the newest verson?

**Comment by thinkyhead** [comment] 2018-02-26 01:34
Duplicate of #9730

**Closed as completed by thinkyhead** 2018-02-26 01:34 UTC
