### ISSUE TITLE
CoreXY Y-homing error

### ISSUE THREAD

**Issue by tonnico** [MarlinFirmware/Marlin#1610] opened 2015-03-15 17:15 UTC
Don't know if this is a problem with my ARM-version but I started again to port all new stuff. After that when I run a G28 Y the printer homes X again. Y moves work.

**Comment by alexborro** [comment] 2015-03-15 18:06
I will try that tomorrow... but last Friday it was working fine (with
latest Development version).

Cheers.

Alex.

2015-03-15 14:16 GMT-03:00 Wurstnase notifications@github.com:

> Don't know if this is a problem with my ARM-version but I started again to
> port all new stuff. After that when I run a G28 Y the printer homes X
> again. Y moves work.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MarlinFirmware/Marlin/issues/1610.

## 

_"Não é o mais forte da espécie que sobrevive, nem o mais inteligente. É
aquele que se adapta melhor as mudanças"  ( Charles Darwin )_

Alex Borro

**Comment by tonnico** [comment] 2015-03-15 18:47
Right. Last one works fine. Just tried the latest version from today.
My CoreXY has max X and max Y end stops.

**Comment by AnHardt** [comment] 2015-03-15 22:45
Depending on when you pulled today this can be caused by #1606 and is fixed by #1614.

**Comment by thinkyhead** [comment] 2015-03-15 23:20
With that merged, let me know if this is still an issue.

**Comment by tonnico** [comment] 2015-03-16 17:01
Now the old homing-bug for coreXY is back.
With max endstops on X and Y I can only home X or Y when the other endstop is free.

**Comment by alexborro** [comment] 2015-03-16 17:13
I'm working on it right now... it has been 2h and I still cannot find the
issue.. that's the reason I fear mass changes in stepper.cpp

Cheers.

Alex.

2015-03-16 14:01 GMT-03:00 Wurstnase notifications@github.com:

> Now the old homing-bug for coreXY is back.
> With max endstops on X and Y I can only home X or Y when the other endstop
> is free.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MarlinFirmware/Marlin/issues/1610#issuecomment-81808784
> .

## 

_"Não é o mais forte da espécie que sobrevive, nem o mais inteligente. É
aquele que se adapta melhor as mudanças"  ( Charles Darwin )_

Alex Borro

**Comment by tonnico** [comment] 2015-03-16 22:14
Solved again by Alex!

**Comment by boelle** [comment] 2015-03-17 21:03
so we can close this one as fixed?

**Closed as completed** 2015-03-17 21:11 UTC
