### ISSUE TITLE
[BUG] (TMC5161:Stop after moving a few times)

### ISSUE THREAD

**Issue by LT1010** [MarlinFirmware/Marlin#16422] opened 2020-01-02 11:32 UTC
Bug Description：
TMC5161 cannot move after moving several axes.
Steps to Reproduce:
1.Configuration.
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/4015568/Configuration.zip)
2.Move XYZ axis using serial screen.
**Expected behavior:**
Send command to move axis.
**Actual behavior:**
After moving a few times, the corresponding axis can't move.
#### Additional Information
Use M122 to check until the axis stops moving. The information is correct.
![before_printing](https://user-images.githubusercontent.com/56394552/71664861-a03dc080-2d95-11ea-8d82-44179410b8e8.png)
move_x:
![move_x](https://user-images.githubusercontent.com/56394552/71664870-aaf85580-2d95-11ea-88a9-211ef8881183.png)
move_x_sometimes:
![Move_x_sometime](https://user-images.githubusercontent.com/56394552/71664891-bcd9f880-2d95-11ea-8ce9-17b75c16b80d.png)
Description：This is the case for all axes. After a while, it cannot move, and the motor is not locked.
[＃16365](url)
@everybody，how to solve this problem.

**Comment by LT1010** [comment] 2020-01-02 11:33
[https://github.com/MarlinFirmware/Marlin/issues/16365](url)

**Comment by boelle** [comment] 2020-01-07 01:02
is this issue and #16365 the same?

**Comment by LT1010** [comment] 2020-01-07 02:56
> is this issue and #16365 the same?

Yes they are the same question.

**Comment by boelle** [comment] 2020-01-07 19:39
then i close this one, we only need one for the same 

and you said they are questions? so not a bug?

**Closed as completed** 2020-01-07 19:40 UTC
