### ISSUE TITLE
[BUG] LCD not responding on Z offset adjustment 

### ISSUE THREAD

**Issue by davidcgu** [MarlinFirmware/Marlin#16863] opened 2020-02-15 00:36 UTC
### Bug Description

With latest release 2.0.3 my LCD gets unresponsive when trying to adjust Z offset, I tried printing or without with same result.

I was running exactly same config with 2.0.1 with no problem at all.

### My Configurations

I have enabled options as follows:

#define BABYSTEPPING
#define DOUBLECLICK_FOR_Z_BABYSTEPPING 
#define BABYSTEP_ZPROBE_OFFSET 
#define MINIMUM_STEPPER_PULSE 2
#define SQUARE_WAVE_STEPPING

### Steps to Reproduce

Whenever trying to change Z offset value on LCD rotating  the encoder.

**Expected behavior:** [What you expect to happen]

**Actual behavior:** LCD seems unresponsive but only on this option.

#### Additional Information

Config files attached
[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/4207495/Marlin.zip)

**Comment by MangaValk** [comment] 2020-02-15 09:48
here kinda the same issue using latest commit, lcd works but z isnt moving to the offset anymore.

**Comment by thinkyhead** [comment] 2020-02-15 11:10
Duplicate of #16617

**Closed as completed by thinkyhead** 2020-02-15 11:10 UTC
