### ISSUE TITLE
[BUG] Delta X/Y movement

### ISSUE THREAD

**Issue by renzaaa** [MarlinFirmware/Marlin#26840] opened 2024-03-04 00:54 UTC
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Z movement works fine, but any X or Y movement moves all 3 axes equally down until hits the bed.
I'm tested marlin version 2.1.2.2 and X/Y movement works fine. The problem is from latest bugfix.
This problem is caused by enabled MIN/MAX software endstops.

### Printer model

Custom Delta

### Electronics

SKR_V1_4_TURBO

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

None

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Config.zip](https://github.com/MarlinFirmware/Marlin/files/14475344/Config.zip)

**Comment by ellensp** [comment] 2024-03-04 10:36
May be related https://github.com/MarlinFirmware/Marlin/issues/26792

**Comment by thisiskeithb** [comment] 2024-06-02 09:59
This should now be fixed in the latest [`bugfix-2.1.x`](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.1.x.zip), so please test with the latest code and let us know if you're still having this issue.

**Comment by lenny-chem-dat** [comment] 2024-06-25 20:13
> This should now be fixed in the latest [`bugfix-2.1.x`](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.1.x.zip), so please test with the latest code and let us know if you're still having this issue.

I can confirm that the Delta movement works fine on the version I downloaded a week ago. It didn't work before, so bug seems to be fixed. Running an FLSUN Q5 with MKS Robin Nano.

**Closed as completed** 2024-06-25 20:28 UTC
Labels: K: Deltabot, C: Motion
