### ISSUE TITLE
[FR] Bed Tramming Assist Menu - G35

### ISSUE THREAD

**Issue by ETE-Design** [MarlinFirmware/Marlin#19480] opened 2020-09-22 15:41 UTC
Would be great to have a menu direct on the LCD to be able to tram the bed with G34 without using OctoPrint or simular...
Mabye something like the GFX for Z-Offset...

**Comment by sjasonsmith** [comment] 2020-09-22 16:55
Duplicate of #18489

**Closed as completed by sjasonsmith** 2020-09-22 16:55 UTC
Labels: T: Feature Request
