### ISSUE TITLE
Z Probe Endstop Support for Rambo

### ISSUE THREAD

**Issue by MrExo3D** [MarlinFirmware/Marlin#4507] opened 2016-08-02 19:34 UTC
Currently Rambo does not have a Endstop available for the Z probe
I would like to be able to use the Z max endstop as a Z Probe endstop

Can this be set in the PINS Rambo area.

**Comment by Roxy-3D** [comment] 2016-08-02 21:15
ThinkyHead is probably the right one to answer this...  (It is very possible he will correct some of my comments)   But I'll try to help just so you can get started on the problem.   The Pins files, pretty much, documents what the board has silk screened on it.   It is a little bit complicated to use both a Z-Min-Endstop and a Z-Probe.    

I think you want to comment out the Z_MAX_PIN definition in your Rambo Pins file.  And replace it with Z_MIN_PROBE_PIN being defined on the same pin number that Z_MAX_PIN used to be on.

Once that is done, you need to very carefully setup your Configuration.h  to enable: Z_MIN_PROBE_ENDSTOP.       You also need to turn off the Safe Homing.

Do you really want to have Z-Min endstop for homing and the Z-Probe for probing?

**Comment by MrExo3D** [comment] 2016-08-03 03:36
with the Z endstop on the probe. if the probe is up.. there is no endstop that would stop the gantry from plunging.. I just assumed that having it separate would be safer.

**Comment by thinkyhead** [comment] 2016-08-03 04:11
Once #4517 is merged you should be able to get the pin you want by using the following in your `Configuration.h`:

``` cpp
#define Z_MIN_PROBE_ENDSTOP
#define Z_MIN_PROBE_PIN 30
```

**Comment by MrExo3D** [comment] 2016-08-03 04:36
Great Thanks

**Comment by dvseliteus** [comment] 2016-10-04 21:53
@thinkyhead Marlin-1.1.0-RC7 I'm having trouble getting my `FIX_MOUNTED_PROBE` to Trigger using the M119 command in Pronterface?
[Configuration.h](http://pastebin.com/RTwDu9B4)
[RAMBO.h](http://pastebin.com/L4geMMES)
I have tried the suggestions above and about everything else I can think of.
The probe was working at some point during my trials of the RCBUGFIX Marlin Version.
Any suggestions on how I can further test?

**Comment by thinkyhead** [comment] 2016-10-06 05:52
@dvseliteus According to your configuration, your probe is connected to the Z_MIN endstop pin. If you want to use a different pin, set `Z_MIN_PROBE_ENDSTOP` instead of `Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN`.

Endstop and probe testing is quite straightforward. They're just switches, either open or closed, and they register as either open or TRIGGERED. Thus if an endstop/probe isn't triggering at all, you can try setting the `ENDSTOPPULLUP` for that particular endstop/probe. If it's triggering in reverse, then you just set (or unset) the `ENDSTOP_INVERTING` for that endstop/probe. Just test the switches one at a time until you isolate the cause of the failure.

**Comment by dvseliteus** [comment] 2016-10-07 17:46
@thinkyhead Thanks for this info it really helped me dial it in. Here is what ended up working for me.

``` cpp
// coarse Endstop Settings
//#define ENDSTOPPULLUPS // Comment this out (using // at the start of the line) to disable the endstop pullup resistors

#if DISABLED(ENDSTOPPULLUPS)
  // fine endstop settings: Individual pullups. will be ignored if ENDSTOPPULLUPS is defined
  #define ENDSTOPPULLUP_XMAX
  #define ENDSTOPPULLUP_YMAX
  #define ENDSTOPPULLUP_ZMAX
  #define ENDSTOPPULLUP_XMIN
  #define ENDSTOPPULLUP_YMIN
  //#define ENDSTOPPULLUP_ZMIN
  #define ENDSTOPPULLUP_ZMIN_PROBE
#endif
```

**Closed as completed** 2016-10-09 21:36 UTC
Labels: C: Boards/Pins
