### ISSUE TITLE
Nozzle crashes into bed after autobedleveling with RC6

### ISSUE THREAD

**Issue by a-sprenger** [MarlinFirmware/Marlin#3675] opened 2016-05-04 14:47 UTC
Hi,

I used RC5 the last time. It work very fine with my Prusa (Ramps 1.4 EMF / 2 TMC2100 / 2 DRV8825
3 min endstopps, 1 inductive sensor at Pin D32, Octoprint)
Autobedleveling was active. Not ever but it worked fine

Now, with RC6, the autobedleveling process works fine, but in the end of that procedure the z-axis don't stop moving down.
When moving down the z-axis manually nothing happens when triggering the endstop or the sensor. It moves down and down until I have to switch off the printer

The console shows me with M119 all endstops and the sensor as triggered when triggered

I attach my two configuration.h files. 
Where is the mistake, or is it a bug?
[configuration.zip](https://github.com/MarlinFirmware/Marlin/files/248949/configuration.zip)

**Comment by jbrazio** [comment] 2016-05-04 15:41
Duplicate of #3575

**Comment by a-sprenger** [comment] 2016-05-04 16:07
I don't think so.
#3575 has been opened for more than 14 Days. At this time there was no RC6!
With RC5 I have no problems like that!

**Comment by jbrazio** [comment] 2016-05-04 16:35
Don't worry, I was just referencing the other one and kept this one open for evaluation.

**Comment by Blue-Marlin** [comment] 2016-05-04 17:46
What is your setting for `ENDSTOPS_ONLY_FOR_HOMING` (`Configuration_adv.h`)?
If that is active, together with your `min_software_endstops false` there is no mechanism to protect in z-min direction.
Since some time you should not need `ENDSTOPS_ONLY_FOR_HOMING` for an inductive probe anymore.

**Comment by Blue-Marlin** [comment] 2016-05-04 17:55
What do you mean with

> the autobedleveling process works fine, but in the end of that procedure the z-axis don't stop moving down.

When exactly? Is the last probe made correct? Is it during the 'virtual' stowing of the `FIX_MOUNTED_PROBE`? Is it a move downwards after `G29`?

**Comment by Blue-Marlin** [comment] 2016-05-04 18:18
For what reason is `Z_PROBE_END_SCRIPT` activated? It's an example for stowing an Allen Key Probe. Your defined max feedrate is 1,500 the ordered move in the script has F12000.

**Comment by Blue-Marlin** [comment] 2016-05-04 18:23
> Z_PROBE_OFFSET_FROM_EXTRUDER -9.93

What kind/brand/type of inductive sensor do you have? Most of them do work up to ~4mm. 1cm is enormous.

**Comment by a-sprenger** [comment] 2016-05-04 19:15
`ENDSTOPS_ONLY_FOR_HOMING` is active (it's activated in RC5, too; there it works)

Well, the last probe is correct; After that the carriage drives to the left side, and goes down. exactly then!

`Z_PROBE_END_SCRIPT` is used, because I use clambs! Oh, the F12000 will be changed, but the printer don't come to that point.

a capacitive pnp sensor is correct. 9.93 is a changed value. 
I know 7.93 is a high value, but I changed it after changing to RC5. If something happens I have a little bit more time to react!

**Comment by Grogyan** [comment] 2016-05-04 20:05
@a-sprenger can you try repeating a G28 Z0?
Does it ever go into a slow feedrate mode when doing the initial probing?

**Comment by Blue-Marlin** [comment] 2016-05-04 20:26
Please try G29 an other time. Keep an eye on, if the probing moves are stopped by the probe (LED) or the z-min-endstop. If they are stopped by the endstopp the correction G29 makes, will allow to move z 9.93mm below the bed? (keep your finger on the reset button)
`Z_PROBE_OFFSET_FROM_EXTRUDER` is not the distance between the nozzle's tip and the (yellow?) bottom surface of the probe, but the distance from the bed to the bottom surface, when the probe triggers, minus the distance from the nozzle to the bottom surface. That normally should be about a mm. A cm is a extremely unlikely value.

Pardon? What do you mean with 'clambs'? And what has the `Z_PROBE_END_SCRIPT` to do with it/them?

**Comment by scruffy4386** [comment] 2016-05-07 06:10
Could the Negative 53 mm Y offset of the z probe sensor also be a typo leading the bed leveling off from what it should be? Also in Homing at line 649 the bed center is defined however you have not defined Manual Home Position above it. And lastly, what I learned through experience is that setting the Z offset far larger than what it truly is will end up with the adjusted Z zero being below the true zero leading to a collision.

**Comment by thinkyhead** [comment] 2016-05-08 18:57
Looks like a configuration issue. If we get no feedback soon, this can be closed.

**Comment by Roxy-3D** [comment] 2016-05-08 23:06
I wonder if this is related to: #3700

**Comment by thinkyhead** [comment] 2016-05-09 02:48
@a-sprenger Try the latest `RCBugFix` and see if your configuration triggers any errors in `SanityCheck.h`.

**Comment by jbrazio** [comment] 2016-05-10 00:10
Closing this issue as it is identified as a duplicate of #3700, let's proceed the discussion there.

**Closed as completed by jbrazio** 2016-05-10 00:10 UTC
