### ISSUE TITLE
 [FR] Ad a possibility to exclude MIN_STEPS_PER_SEGMENT during manual leveling/ delta auto calibration

### ISSUE THREAD

**Issue by Hywelmartin** [MarlinFirmware/Marlin#8664] opened 2017-12-05 10:52 UTC
read https://github.com/MarlinFirmware/Marlin/issues/8568 as background
The conclusion is that if using a belt driven Z-axis the MIN_STEPS_PER_SEGMENT will gain a lower resolution, at least if manual probing is chosen.

The PROBE_MANUALLY_STEP gets obsolete due the MIN_STEPS_PER_SEGMENT(at least if lower than  (MIN_STEPS_PER_SEGMENT)*(steps/mm)

In my case with a delta as originally has 80 steps/mm will have 6 * 1/80 = 0.075mm

my current setup will get 5*1/100=0,05

**Comment by gbyczyns** [comment] 2017-12-05 11:39
Looks like a duplicate of #8606.

**Comment by Hywelmartin** [comment] 2017-12-05 12:32
oups.. I will search better in the future..
They address the same problem/feature/possibility

**Closed as completed** 2018-02-10 21:59 UTC
