### ISSUE TITLE
[BUG] FT_MOTION causes homing failure

### ISSUE THREAD

**Issue by Weresk** [MarlinFirmware/Marlin#27345] opened 2024-08-11 00:30 UTC
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

FT_MOTION causes homing failure

### Bug Timeline

When FT_motion was implemented

### Expected behavior

Normal working homing and printing

### Actual behavior

When enable FT_MOTION  printer does not see the limit switch

### Steps to Reproduce

1. enable FT_MOTION MZV shaper
2. start homing
3. failure homing (does not see the limit switch)

### Version of Marlin Firmware

2.1.3 last (check every new versions from february)

### Printer model

Creality Ender-3

### Electronics

gd32f103rc

### Bed Leveling

None

### Your Slicer

Prusa Slicer

### Host Software

SD Card (headless)

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Configuration_adv.zip](https://github.com/user-attachments/files/16571216/Configuration_adv.zip)

**Comment by thisiskeithb** [comment] 2024-08-11 03:02
Duplicate of #27082

**Closed as completed by thisiskeithb** 2024-08-11 03:02 UTC
