### ISSUE TITLE
v1.1.7 onwards Dual X Carriage T1 no longer movable & homing not working

### ISSUE THREAD

**Issue by bruce356** [MarlinFirmware/Marlin#9133] opened 2018-01-10 09:14 UTC
------------------------------------------------------------
### Bug Report
- Description: ---
Normally when homing X axis T1 homes first and then T0
In version 1.1.7 upwards T0 homes first but in the wrong direction and crashes into T1 on right hand side.
If the motor direction is reversed T0 crashes into left side endstop and stepper just continues to skip steps.
After entering T1 command T1 can not be accessed or moved.   
- Expected behaviour: ---
T1 homes first and then T0 and both T0 and T1 can be moved as normal

- Steps to reproduce:
Install Marlin 1.1.7 or 1.1.8 or beta on a Dual X Cartesian printer.
 
Attach a ZIP of `Configuration.h` and `Configuration_adv.h` by dropping here.

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/1618168/Marlin.zip)

**Comment by oysteinkrog** [comment] 2018-01-10 12:21
Duplicate of #8170 :)

**Closed as completed** 2018-02-11 09:48 UTC
