### ISSUE TITLE
Junction Deviation still rearing it's ugly stuttering head.

### ISSUE THREAD

**Issue by thierryzoller** [MarlinFirmware/Marlin#20029] opened 2020-11-04 22:26 UTC
**Version**: Latest Bugfix
**Duplicate/Related :** https://github.com/MarlinFirmware/Marlin/issues/17342

### Bug Description

Having Junction Deviation enabled leads to stuttering XY Diagonal movements. See Videos below.
Disabling JD solves the issue. 

### Configuration Files
[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/5490782/Marlin.zip)

TMC2209 UART Mode
Hybrid Threshold (doesn't change the effect)

#### Additional Information
* Video 1 : https://youtu.be/kngqQIPUP1c
_JD Enabled (See Diagonal Movement)

* Video 2 : https://youtu.be/yOadfORpKuw
_Classic Jerk Enabled (See - TMC 2209 Hybrid Threshold straight but noisy movement)_

**Comment by thisiskeithb** [comment] 2020-11-04 22:30
Duplicate of https://github.com/MarlinFirmware/Marlin/issues/17342

**Closed as completed by thisiskeithb** 2020-11-04 22:30 UTC

**Comment by thierryzoller** [comment] 2020-11-04 23:05
17342 is about a subset of calculations that I think do not apply here. So why close it? Rather I would like to see someone chime in on whether or not it is really a duplicate. Root cause may be different. I don't see how you would close this. Took 30 minutes to debug, 5 minutes for videos, etc. Only to have it closed without even a comment?

**Comment by sjasonsmith** [comment] 2020-12-20 00:18
@thierryzoller are you still having issues with this?

**Comment by thierryzoller** [comment] 2020-12-21 10:13
I disabled JD since and do not see the issue. I can try recompilig it with JD if there is reason to believe it should not reproduce

**Comment by sjasonsmith** [comment] 2020-12-21 14:46
I don’t have any reason to believe it has improved, but your configs were newer than that bug this duplicates, so could be a better starting point for anyone wanting to debug it.

I’m hoping we’ll knock out quite a few bugs over the next couple weeks, but I can’t really promise exactly which ones we can get to.
