### ISSUE TITLE
[FR] Auto set probe z offset 

### ISSUE THREAD

**Issue by mattschinkel** [MarlinFirmware/Marlin#13704] opened 2019-04-15 02:22 UTC
Every time you Change nozzle size, you need to set your z-offset if you have an auto level sensor such as bltouch.

I suggest adding a feature to auto set your z-offset by testing the height of the nozzle via pressing a button, then testing your probe and calculating the difference in height. This could be done before every print.

**Comment by robbycandra** [comment] 2019-04-15 07:43
I think this is good idea

**Comment by InsanityAutomation** [comment] 2019-04-15 16:49
This is doable if you dont use z probe as endstop. Lulzbot has configured the Taz 6 machines this way. Functionality has been supported for a long time.

**Comment by robbycandra** [comment] 2019-04-15 20:14
For user, the problem is testing the height of nozzle to the table. Need another probe to do that.

**Comment by tcm0116** [comment] 2019-04-23 20:13
If you have a button at at fixed offset relative to the bed, then you don't need a probe on the nozzle. Just have the nozzle home to the button and set your Z offset from there. If you change the nozzle, then it'll still home to the button, which has the same offset to the bed.

**Comment by mattschinkel** [comment] 2019-04-23 21:29
But them you don't have auto level

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by robbycandra** [comment] 2019-04-25 04:17
@tcm0116 , but we have 2 unfix part here. Nozzle (because we can change nozzle) and bed (because we can adjust bed corner height).

Therefore, it is difficult to have a buttoh that have fixed offset relative to bed. Cause the bed is not fixed to the frame.

**Comment by maukcc** [comment] 2019-08-09 14:27
A good solution is the G31 Zxx.x code that repetier uses.
Is the Z_PROBE_OFFSET_FROM_EXTRUDER used for anything at this moment?

**Comment by damvcoool** [comment] 2019-12-10 19:17
In the SKR Mini E3 v1.2 you can configure the Z-Endstop and Probe on different Pins, wouldnt it be possible to simply calculate the difference between the Z-Endstop and when the probe gets triggered, to set the Nozzle to Probe Z-Offset?

**Comment by qwewer0** [comment] 2021-01-01 20:10
@mattschinkel `PROBE_OFFSET_WIZARD` should be helpful to get z-offset quickly.

**Comment by sjasonsmith** [comment] 2021-01-01 20:12
> `PROBE_OFFSET_WIZARD` should be helpful to get z-offset quickly.

I am actually going to close this, since I think the probe offset wizard fulfills this request.

**Closed as completed by sjasonsmith** 2021-01-01 20:12 UTC
Labels: T: Feature Request
