### ISSUE TITLE
[FR] (To use stall detection to prevent a nozzle-to-bed crash)

### ISSUE THREAD

**Issue by muistiloppu** [MarlinFirmware/Marlin#25779] opened 2023-05-04 22:39 UTC
### Is your feature request related to a problem? Please describe.

I have experienced nozzle-to-bed crashes a few times, which were caused by a bent or broken BLtouch pin.

### Are you looking for hardware support?

Boards what has stepper controllers with a stall detection.
In the four corners of my DIY printer, there are steppers that utilize 20-tooth pulleys to drive 40-tooth gears, which in turn are connected to 1204 ball screws. I'm using 2209 drivers on the BTT GTR 1.0 board.

### Describe the feature you want

To prevent a nozzle from crashing into the bed by monitoring the motor current and detecting when the motor is stalled.

**Comment by thisiskeithb** [comment] 2023-05-05 00:31
Duplicate of https://github.com/MarlinFirmware/Marlin/issues/8765

**Closed as completed by thisiskeithb** 2023-05-05 00:31 UTC
Labels: T: Feature Request
