### ISSUE TITLE
Homing issue

### ISSUE THREAD

**Issue by NimrodQuimbus** [MarlinFirmware/Marlin#5421] opened 2016-12-07 19:31 UTC
When the printer homes at the start of the print, and Y axis will move/home even when it is at home and the limit switch is made.
I am not sure if the same is with the x of z

**Comment by macst34** [comment] 2016-12-07 20:15
Hi @NimrodQuimbus

(I believe) this is intended behavior...When a endstop is hit during homing, the axis is backed off and slowly re-engages the endstop. This happens for all homed axes.  This "check" just ensures the accuracy of your endstops in case you have some really fast homing speeds and the endstop is slightly deflected by the printhead moving towards it at high speed.

Note this is also referenced by #5418.

happy hacking,
Michael

**Comment by NimrodQuimbus** [comment] 2016-12-07 21:15
No, you misread what I said.

Y axis is homing when it is already at home, which tears the belt from its mounting.
If anything, it should check to see if an axis is at home, then if so, back off until that contact is opened, then re-home.

**Comment by macst34** [comment] 2016-12-08 02:35
Hi @NimrodQuimbus,

Sorry if I misread. If the Y axis is trying to go past the Y endstop when it is already home, that does seem to be a problem. Perhaps you can shut your steppers off, home the y-axis manually and then issue a 

`M119`

to see the status of the endstops and confirm that the issue is not mechanical. Other than that, can you tell us anymore about the issue? i.e. printer type, endstop type, configuration.h settings, etc. More information would likely be helpful since we don't have much context for the issue.

Michael

**Comment by thinkyhead** [comment] 2016-12-09 02:22
Endstops aren't tested until motion starts, but they should respond so quickly that only a few steps transpire. If it's moving more than a millimeter, then we should take a look and see what's going on.

**Closed as completed** 2017-10-31 06:04 UTC
Labels: T: Question, Bug? Feature!

**Comment by NimrodQuimbus** [comment] 2017-10-31 12:25
My Y axis will rip the belt out, but the x axis is fine.I just make sure everything is off of the stops before I print. 

    On Tuesday, October 31, 2017 2:05 AM, Scott Lahteine <notifications@github.com> wrote:
 

 Closed #5421.—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.  

   

|  | Virus-free. www.avg.com  |
