### ISSUE TITLE
[BUG] U8glib-HAL Error with BOARD_BTT_SKR_MINI_E3_V3_0 and CR10_STOCKDISPLAY

### ISSUE THREAD

**Issue by rickjs** [MarlinFirmware/Marlin#26580] opened 2023-12-28 03:48 UTC
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Yesterday downloaded Marlin 2.1.x with bugfix, used board BOARD_BTT_SKR_MINI_E3_V3_0, env STM32G0B1RE_btt, display CR10_STOCKDISPLAY, compiled no problem. Today recompiled, have error... U8glib-HAL.h:946:65: error: 'u8g_dev_ssd1309_128x64_f_i2c' was not declared in this scope. Notice other projects use U8glib-HAL@0.5.2, this Skr Mini project is using 0.5.3. Could that be the problem?

### Bug Timeline

Compiled on 12/26, failed today 12/27

### Expected behavior

To compile with no errors

### Actual behavior

.pio\libdeps\STM32G0B1RE_btt\U8glib-HAL\src/U8glib-HAL.h: In member function 'void U8GLIB_SSD1309_128X64_F::init(uint8_t, uint8_t, uint8_t, uint8_t, uint8_t)':
.pio\libdeps\STM32G0B1RE_btt\U8glib-HAL\src/U8glib-HAL.h:944:110: error: 'u8g_dev_ssd1309_128x64_f_sw_spi' was not declared in this scope; did you mean 'u8g_dev_ssd1309_128x64_sw_spi'?

### Steps to Reproduce

Using VScode, yesterday downloaded Marlin 2.1.x with bugfix, used board BOARD_BTT_SKR_MINI_E3_V3_0, env STM32G0B1RE_btt, display CR10_STOCKDISPLAY, compiled no problem. Today  downloaded Marlin 2.1.x with bugfix again recompiled, have error.

### Version of Marlin Firmware

Marlin 2.1.x with bugfix

### Printer model

BOARD_BTT_SKR_MINI_E3_V3_0

### Electronics

BTT SKR MINI E3 V3.0

### LCD/Controller

Using CR10_STOCKDISPLAY

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[btt-skr-mini error.zip](https://github.com/MarlinFirmware/Marlin/files/13783116/btt-skr-mini.error.zip)

**Comment by thisiskeithb** [comment] 2023-12-28 03:48
Duplicate of https://github.com/MarlinFirmware/Marlin/issues/26577

**Closed as completed by thisiskeithb** 2023-12-28 03:48 UTC
