### ISSUE TITLE
[FR] Distinct E-Factors for Mixing Extruder

### ISSUE THREAD

**Issue by psavva** [MarlinFirmware/Marlin#17608] opened 2020-04-19 15:49 UTC
I would like to request a new feature for the mixing extruders to allow distinct e-factors per extruder, allowing me to set the steps/mm per extruder when using Mixing Extruders

### Feature Workflow

```
/**
 * Default Axis Steps Per Unit (steps/mm)
 * Override with M92
 *                                      X, Y, Z, E0 [, E1[, E2...]]
 */
#define DEFAULT_AXIS_STEPS_PER_UNIT   { 80, 80, 4000, 500, 800 }

```
...

```
#define MIXING_EXTRUDER
#if ENABLED(MIXING_EXTRUDER)
  #define MIXING_STEPPERS 2        // Number of steppers in your mixing extruder
...
#endif

```
The request to allow E0 = 500 steps/mm, and E1 on 800 steps/mm
whilst using the Mixing Extruder as depicted above.

#### Additional Information

The advantage of this is that different extruders can be used with mixing extrudes, and calibrated more precisely.  As an extra bonus, it can be better utalized for Ceramic/Clay extrusion systems making use of Ram/Auger setup.

**Comment by thinkyhead** [comment] 2021-08-06 04:27
Duplicate of #8145

**Closed as completed by thinkyhead** 2021-08-06 04:27 UTC
Labels: T: Feature Request
