### ISSUE TITLE
[FR] add mesh/probing variables to menu for changing without recompile

### ISSUE THREAD

**Issue by MeSoLost** [MarlinFirmware/Marlin#20974] opened 2021-02-02 07:45 UTC
### Description

Adding the firmware variables MULTIPLE_PROBING and GRID_MAX_POINTS_X/Y to the menu for alteration without a recompile.

Secondary variables* XY_PROBE_SPEED, BILINEAR_SUBDIVISIONS, EXTRAPOLATE_BEYOND_GRID could also be added if making a super level menu is an option.

pre-edit: Just realized that an option to add the current Z baby step to the Z probe offset would be an intuitive option as well.

### Feature Workflow

I would imagine it would be as straight forward as using an already existing menu frame and populating it with all the mentioned variables and potentially a few more related to "extra messy" bed leveling.  At the least I believe simply adding multi probing and grid points to scan to the already existing menu with probe Z offset would help tuning between (list -_-) establishing a baseline offset faster, dialing in just how bad the warping is, time taken to probe on each print, speed/accuracy of probing.

See, for a few weeks before I got replacement parts I had a rather nasty experience where no matter what I did I was still getting bad alignment.  If the print plane is considered flat then the print head actually compensated like \___/ resulting in the left and right side trying to print in air and the center still printing as saran wrap for a flea.  I eventually figured out that my head just wasn't heavy enough to sit at the same angle after everything had almost melted off when I tried to print ABS for the first time.

Replaced a few parts and it's stable now so all is good but I'd also like an easier way to step down from double probing 5x5 points with 3 bilinear subdivisions and extrapolate beyond grid on to find just how little auto leveling I actually need.  Only a 529 point grid with 52 physical probes (2 for z min uses z probe) LOL takes a little bit to restart prints and tweak that one corner screw so that first corner line doesn't peel up.

The x/y probe speed, faster scan for tight rigs, slower for loose or shaky ones, I figure it could be added in with the BLTouch stuff.  Which leads to enabling these settings.  This speed setting I think should be on there by default settable to low/med/high, low being it's current default, hi being printers max travel speed and medium between them.  In the firmware have a setting for ENABLE_SUPER_LEVEL_MENU to enable these detailed leveling settings and change speed setting from basic low/med/hi to a settable numerical value.  

Making sure these aren't in the menu already just extra hidden before I submit and recompile another firmware and I finally found M420 so my life is easier now.

**Comment by thisiskeithb** [comment] 2023-04-16 21:59
Duplicate of https://github.com/MarlinFirmware/Marlin/issues/10547

**Closed as completed by thisiskeithb** 2023-04-16 21:59 UTC
Labels: T: Feature Request
