### ISSUE TITLE
[BUG] g28 centered, g29 is not, m206 set properly

### ISSUE THREAD

**Issue by qwksilver** [MarlinFirmware/Marlin#22565] opened 2021-08-13 16:58 UTC
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

My endstops are not exactly at x0 y0,  my m206 value is "Recv: M206 X-21.00 Y-23.00 Z0.00"
My Probe is -18,0,-1.48, My Extruder Hotends are 0 and +22.

I'm centering with Z_SAFE_HOMING defined.
g28 does x, y, and then moves the probe to dead center and finds z.
I'm doing a 3x3 grid, based on the center point of that grid, the probe is forward and left of where it should be

basically to me it seems to be ignoring the m206 values.
I also can't find anywhere to just hardcode the m206 values into the firmware so I don't have to constantly set those up

### Bug Timeline

i'm reconfiguring system, and trying to get both extruders aligned and working

### Expected behavior

I expect the center point of my grid to be the center of my bed, or at least the same center point that g28 homed on. 

### Actual behavior

the center probe point is forward and left of center

### Steps to Reproduce

have physical hardware where the endstops aren't perfect(x is 21mm left of edge, and y is 23mm off the front of edge
load firmware
m206 x-21 y-23 z0
m500
then reset and 
g28
g29

### Version of Marlin Firmware

FIRMWARE_NAME:Marlin bugfix-2.0.x (Aug 13 2021 12:04:08) SOURCE_CODE_URL:github.com/MarlinFirmware/Marlin PROTOCOL_VERSION:1.0 MACHINE_TYPE:3D Printer EXTRUDER_COUNT:2 UUID:cede2a2f-41a2-4748-9b12-c55c62f367ff

### Printer model

Creality Ender 3 Pro

### Electronics

SKR 1.4 Turbo

### Add-ons

CR-Touch, Chimera Print Head, Linear Rails, Custom X-Carriage

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Cura

### Host Software

OctoPrint

### Additional information & file uploads

Send: M115
Recv: FIRMWARE_NAME:Marlin bugfix-2.0.x (Aug 13 2021 12:04:08) SOURCE_CODE_URL:github.com/MarlinFirmware/Marlin PROTOCOL_VERSION:1.0 MACHINE_TYPE:3D Printer EXTRUDER_COUNT:2 UUID:cede2a2f-41a2-4748-9b12-c55c62f367ff
Recv: Cap:SERIAL_XON_XOFF:0
Recv: Cap:BINARY_FILE_TRANSFER:0
Recv: Cap:EEPROM:1
Recv: Cap:VOLUMETRIC:1
Recv: Cap:AUTOREPORT_POS:0
Recv: Cap:AUTOREPORT_TEMP:1
Recv: Cap:PROGRESS:0
Recv: Cap:PRINT_JOB:1
Recv: Cap:AUTOLEVEL:1
Recv: Cap:RUNOUT:0
Recv: Cap:Z_PROBE:1
Recv: Cap:LEVELING_DATA:1
Recv: Cap:BUILD_PERCENT:0
Recv: Cap:SOFTWARE_POWER:0
Recv: Cap:TOGGLE_LIGHTS:0
Recv: Cap:CASE_LIGHT_BRIGHTNESS:0
Recv: Cap:EMERGENCY_PARSER:0
Recv: Cap:HOST_ACTION_COMMANDS:0
Recv: Cap:PROMPT_SUPPORT:0
Recv: Cap:SDCARD:0
Recv: Cap:REPEAT:0
Recv: Cap:SD_WRITE:0
Recv: Cap:AUTOREPORT_SD_STATUS:0
Recv: Cap:LONG_FILENAME:0
Recv: Cap:THERMAL_PROTECTION:1
Recv: Cap:MOTION_MODES:0
Recv: Cap:ARCS:1
Recv: Cap:BABYSTEPPING:1
Recv: Cap:CHAMBER_TEMPERATURE:0
Recv: Cap:COOLER_TEMPERATURE:0
Recv: Cap:MEATPACK:0
Recv: ok
Send: M155 S2
Recv: ok
[...]
Send: M111 S247
Recv: echo:DEBUG:ECHO,INFO,ERRORS,COMMUNICATION
Recv: ok

I can make a video if you want it, but I am not sure that will be much clearer
[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/6984053/Marlin.zip)

**Comment by thisiskeithb** [comment] 2021-08-13 17:07
Duplicate of https://github.com/MarlinFirmware/Marlin/issues/22147

**Closed as completed by thisiskeithb** 2021-08-13 17:07 UTC
Labels: F: Calibration, Bug? Feature!
