### ISSUE TITLE
[BUG] MPCTEMP only works with one hotend.

### ISSUE THREAD

**Issue by SlickNickeL** [MarlinFirmware/Marlin#25257] opened 2023-01-20 19:30 UTC
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

When more than one EXTRUDER  is entered, MPCTEMP errors with (count(HOTENDS). ===HOTENDS
I looks as if a definition is needed for multi extruders as in PID.

src.  #def HOTENDS EXTRUDER

### Bug Timeline

New

### Expected behavior

Should accept at least 3 EXRTUDERS.

### Actual behavior

Will only compile without errors with 1 EXTRUDER selected.

### Steps to Reproduce

New config with RUMBA and 3 EXTRUDERS entered along with thermals. 1 Extruder works, 2&3 EXTRUDER errors

### Version of Marlin Firmware

bugfix- 2.1.x

### Printer model

Cartesian

### Electronics

RUMBA

### Add-ons

None

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

**Comment by thisiskeithb** [comment] 2023-01-20 19:57
Duplicate of https://github.com/MarlinFirmware/Marlin/issues/25075

**Closed as completed by thisiskeithb** 2023-01-20 19:57 UTC
