### ISSUE TITLE
[BUG] Mesh Edit UBL Function does not work on delta printers

### ISSUE THREAD

**Issue by pfjason** [MarlinFirmware/Marlin#10435] opened 2018-04-16 22:51 UTC
### Description

When clicking "Edit Mesh" in the UBL menu, the printer homes, then tries to send the X axis to 0, then Y to 0,  ignoring the fact that the printer is a delta and nearly breaking my rods. 

### Steps to Reproduce

On at least my Anycubic Kossel Linear Plus, but I would assume any delta printer, click "Edit Mesh" in the UBL menu.

**Expected behavior:** Functionality to edit the built mesh

**Actual behavior:** X goes to 0 position, sending the effector way outside of the towers, then Y starts to do the same and I emergency powerdown the printer.

**Comment by thinkyhead** [comment] 2018-04-17 02:23
Please test with the latest `bugfix-1.1.x` (and/or `bugfix-2.0.x`) branch to see where it stands. If the problem has been resolved then we can close this issue. If the issue isn't resolved yet, then we should investigate further.

**Comment by Roxy-3D** [comment] 2018-04-17 02:55
@pfjason    If the current bugfix doesn't resolve the problem, you should be able to use the M421 command to edit mesh points.   It is a little more complicated than using the G29 P4 interactive mesh editing...  But it will allow you to adjust the mesh points to where you need them to be.

@thinkyhead     Perhaps we should remove the UBL G29 P4 capability and make it stand alone (and optional) for any mesh based leveling system???   Kind of like the G26 was originally for UBL, but now it works for all mesh based systems.

**Comment by pfjason** [comment] 2018-04-17 03:26
My printers will be tied up for a little bit, but I'll test it when I can.

**Comment by thinkyhead** [comment] 2018-04-18 07:54
> Perhaps we should remove the UBL `G29 P4` capability and make it stand alone (and optional) for any mesh based leveling system?

- MBL wouldn't need it.
- For 3-point and planar leveling it would be overkill.
- Bilinear leveling simply uses the reachable area, interpolates for points that can't be reached on a delta, and for square beds assumes that the area outside the probed region will either flatten out (if the area is very large) or that it continues the same slope (when the area is relatively small). This seems to work for the majority of use cases, and it keeps ABL bilinear relatively small and simple. If the extrapolated points (outside the delta circle) are way off, `M421` can be used to adjust them, but this usually isn't needed.

I appreciate the way UBL works, for those who like to make the mesh span the bed, even where the probe can't reach. But I think it's also appreciated to have a leveling system that does everything automatically and doesn't require a mix of auto and manual leveling. And, it would be a pretty big re-work of ABL to combine both auto and manual leveling; essentially a total rewrite of its `G29`.

**Comment by yoch2015** [comment] 2018-04-23 15:37
I am the same problem.
If you run G29 P4, the hot end will vibrate at high speed.
bugfix-1.1.x date 2018/04/21 use.

**Comment by Roxy-3D** [comment] 2018-04-23 16:01
It might help to back up 4 or 5 months and try an older version of Marlin and see if the problem exists.   I think it probably will not exists.    If that is true, we can look at the differences between the older code and the current code with respect to G29 P4.   

The big problem is I don't have a Delta printer so it is difficult to trouble shoot problems without assistance.   I suspect the problem is something small and won't be hard to fix.   But without a little more information, it is going to be difficult to figure this out.

**Comment by yoch2015** [comment] 2018-04-24 11:01
Thank you.
Perhaps the change in # 9510 seems to be affecting, but now we are planning to change it on M421.

**Comment by thinkyhead** [comment] 2018-04-24 13:06
Reverted a part of #9510 labeled as "SHOULD NOT OCCUR" but maybe it COULD OCCUR after all…?

**Comment by yoch2015** [comment] 2018-04-25 13:31
I tested 21f5ca6.
There was no problem.
However, if the Z value drops to a certain value while editing P4, the motion to restore Z back and the motion to lower Z are executed at high speed.
It is like a vibration.

**Comment by thinkyhead** [comment] 2018-04-26 06:50
> if the Z value drops to a certain value

- What is the value of your `Z_CLEARANCE_BETWEEN_PROBES`?
- Are you using the `H` parameter to `G29 P4`?

**Comment by yoch2015** [comment] 2018-04-26 12:26
When running G29P4, the head is about 1 mm away from the glass surface, so lowering the head with the LCD dial will lower the head.
Therefore, the value of Z is close to 0.
H option not attached.

**Comment by thinkyhead** [comment] 2018-04-29 03:17
If you increase `Z_CLEARANCE_BETWEEN_PROBES` and also include `H0` it might solve the issue.

**Comment by Roxy-3D** [comment] 2018-04-29 03:35
And this is just opinion...   But I wouldn't have 1mm of clearance while running the nozzle around an uncalibrated bed.   That just sounds dangerous.    A few seconds to raise and lower the nozzle might make some sense.

**Comment by yoch2015** [comment] 2018-04-29 16:24
Thank you very much. I will check it.
It was 0.05 mm on the mesh data, but when the Z value became 0 with G 29 P 4, there was a clearance of 1 mm on the nozzle and the glass surface.

**Comment by boelle** [comment] 2019-02-20 11:58
@pfjason did you get a chance to check?

**Comment by pfjason** [comment] 2019-02-20 13:03
Way back in april, on the latest bugfix from way back then, it was not fixed. Since then I've replaced the boards in all my printers and am no longer running Marlin, so I have no idea now.

**Comment by boelle** [comment] 2019-02-20 13:05
maybe consider hitting the green close botton then?

**Comment by pfjason** [comment] 2019-02-20 13:10
Why would I do that? Just because I solved the problem by changing to a non-marlin firmware doesn't mean the bug doesn't exist in Marlin anymore. That's not how bugfixes work.

**Comment by boelle** [comment] 2019-02-20 13:13
i just think its the right thing to do since nobody else have chimed in over a year

but by all means leave it open

**Closed as completed** 2019-08-30 22:24 UTC
Labels: F: U.B.L., K: Deltabot
