### ISSUE TITLE
[BUG] ABL(UBL) Broken when using Z_MIN_PROBE_PIN and BLTOUCH. 

### ISSUE THREAD

**Issue by skellatore** [MarlinFirmware/Marlin#22274] opened 2021-07-01 06:35 UTC
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

Marlin Bugfix 2.0.x - ba29e8f6

When **NOT** using "Z_MIN_PIN" (so using Z_MIN_PROBE_PIN) and using "USE_PROBE_FOR_Z_HOMING", after homing with a Z-Probe offset set, Auto Bed Leveling will fail. ABL will try to probe the bed, but the probe barely touches the bed and therefore fails and continues to try requiring a reboot.

What I believe is happening is after the homing is done, the Z-Offset is taken into consideration to get Z0 (Correct). When ABL is activated and called, it's not considering that it actually needs to use the ignore/go to Z0 - Z-Offset to actually probe. For example, with a probe offset of -2.5, When trying to probe, the probe barely touches the bed and Z needs to lower 2.5mm more to trigger. 

FAILING CONFIGURATION:
//#define Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN
#define USE_PROBE_FOR_Z_HOMING
relevant pins.h;
#define Z_STOP_PIN P1_27
#define Z_MIN_PROBE_PIN P0_10

WORKING CONFIGURATION:
#define Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN
#define USE_PROBE_FOR_Z_HOMING
relevant pins.h;
#define Z_STOP_PIN P0_10
#define Z_MIN_PROBE_PIN P0_10

### Version of Marlin Firmware

Marlin Bugfix 2.0.x - ba29e8f6

### Printer model

Sidewinder X1

### Electronics

SKR1.4 TMC2209

### Add-ons

BLTOUCH (Genuine

### Your Slicer

Prusa Slicer

### Host Software

SD Card (headless)

**Comment by thisiskeithb** [comment] 2021-07-21 04:24
Duplicate of https://github.com/MarlinFirmware/Marlin/issues/21833

**Closed as completed by thisiskeithb** 2021-07-21 04:24 UTC
