### ISSUE TITLE
[FR] Extruder Pressure

### ISSUE THREAD

**Issue by x-stride** [MarlinFirmware/Marlin#24585] opened 2022-08-04 12:40 UTC
### Is your feature request related to a problem? Please describe.

It's always hard getting that initial layer down right. The same is true for those finishing surfaces.

When perfect, the nozzle is so close the extruder is struggling hard feeding it through. Even opaque materials are almost see-through being this thin!

### Are you looking for hardware support?

No idea to be honest :)

### Describe the feature you want

A nozzle that first jumps down to HOME, then:
The extruder senses pressure when extruding, possibly by monitoring motor current or by adding a sensor in it
Add Support for
 - Extruder Pressure. Great for **initial layers**, **surfaces**, wherever **presicion** is needed!
   This might actually increase a lot on **presicion** in general, I think.
 - GCODE's? An M something?

### First Layer
![IMG_20220804_140644_222](https://user-images.githubusercontent.com/9415790/182849263-8560ba54-58fc-4cd6-b8ac-f499f9e707b5.jpg)
### Under the microscope, getting those little "ridges" right
![20220804_150745985](https://user-images.githubusercontent.com/9415790/182855696-05699222-5c24-4112-98d7-b27ff90e2576.jpg)

**Comment by thisiskeithb** [comment] 2022-08-04 15:31
Duplicate of https://github.com/MarlinFirmware/Marlin/issues/18521

**Closed as completed by thisiskeithb** 2022-08-04 15:31 UTC
Labels: T: Feature Request
