### ISSUE TITLE
Delta bed leveling doesn't work

### ISSUE THREAD

**Issue by Enzo-Enz** [MarlinFirmware/Marlin#24128] opened 2022-05-04 16:24 UTC
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

Hello 

It's second time I'm reporting bed leveling doesn't work(first time my report closed)and the print result is awful,It's about several months that my printer is useless because of bed leveling issue 

![7d7bee87-87b2-441c-834a-ebc936f7135b](https://user-images.githubusercontent.com/75531691/166725662-8dfd8759-da4a-4f5e-a317-e42fd37353b3.jpg)
the probe I use

![58e19307-3db5-43e3-93b6-af4445be6f37](https://user-images.githubusercontent.com/75531691/166726953-8bd19a62-c512-4618-a3f3-5db34344f7f4.jpg)

the print result

### Bug Timeline

old

### Version of Marlin Firmware

2.0.9.3

### Printer model

DIY delta printer

### Electronics

skr pro v1.2/TMC2130

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Cura

### Host Software

SD Card (headless)

### Additional information & file uploads

[leveling.txt](https://github.com/MarlinFirmware/Marlin/files/8622109/leveling.txt)

[config.zip](https://github.com/MarlinFirmware/Marlin/files/8622115/config.zip)

**Comment by thisiskeithb** [comment] 2022-05-04 16:27
Duplicate of #23789

As noted by thinkyhead in that issue: 

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).

**Closed as completed by thisiskeithb** 2022-05-04 16:27 UTC
