### ISSUE TITLE
[BUG] fail sensorless x2 axis in custom IDEX with GTR Marlin 2.0.7

### ISSUE THREAD

**Issue by JAUYEB** [MarlinFirmware/Marlin#19616] opened 2020-10-04 17:15 UTC
### Bug Description

Hi, I bought a BTT GTR to replace my old Fysetc F6 1.3 board, so I wrote my old configuration in new Marlin 2.0.7 firm, and the X2 axis "sensorless endstop" doesn't work properly (UART).

### My Configurations

I attach a .zip file

### Steps to Reproduce

1. Power on
2. Home X axis with fullgraphics display control.

**Expected behavior:** 

home carriages X2 and after X1

**Actual behavior:**

X2 goes to Xmax, and the GTR X2 "endstop" led lights, but continues pushing till ERROR ocurred.

#### Additional Information

All axis work well (I can control all motors with the fullgraphics), and Y axis home, Bltouch Z home work too. If I invert the X2 endstop signal in marlin (cancel),  X1 do a home ok too.

In this links you can see a little video and some pics.

P.S: Yes, the termistor of carriage 1 is broken, I have to replace it.
P.S: I had some issues with the fullgraphics, because some little corruption appeared, but I fix editing pins_BTT_GTR_V1_0.h file (BOARD_ST7920_DELAY 250,250,600). I don't know why the LCD needs 5 seconds or so (lot of time) to boot or reboot.

Thanks a lot!

[GTR.zip]

**Comment by thisiskeithb** [comment] 2020-10-04 17:52
Duplicate of https://github.com/MarlinFirmware/Marlin/issues/19552

**Closed as completed by thisiskeithb** 2020-10-04 17:52 UTC
