### ISSUE TITLE
Marlin 2.0 Extruder motor take to hight speed

### ISSUE THREAD

**Issue by ghost** [MarlinFirmware/Marlin#11682] opened 2018-08-31 13:43 UTC
Delta printer with Mks Sbase 1.3 / Marlin2.0 last bugfix.
Configured as i think corectly. Files Atached. 
Problem with extruding feedrate. When printer go print speed of filament feedrate turn very fast, seems like speed * 2.  
Played with other function like district e/ smoothstepping/ and pulses but no different.
When printer in home position and I put filament moove he move correctly how i set 10mm.
I wath g code 
```gcode
G92 E0
G1 E10 F120 
```
So Repetier host set speed F120. But in the slicers Cura or slic3r speed set for all line of code 
like G1 x/// y/// e/// f1200
and the extruder motor give this speed but it's no correct. 

[Config.zip](https://github.com/MarlinFirmware/Marlin/files/2340223/Config.zip)

So i try to set feedrate for extruder for minimum but it's not help. 
What could be the reason ?

**Comment by ghost** [comment] 2018-08-31 14:03
Update:
I have Diamnd Nozzle.
It's trouble with mixing extruder.
When i turn off  mixing extruder and set it to first extruder, this work fine. 
So it's need to make to make 3 extruders and edit sbase pins for make same signal from tempereture and hotend. I am working for it.

**Comment by ghost** [comment] 2018-08-31 15:03
Assignment pins to one extruder not working.

**Comment by ghost** [comment] 2018-08-31 15:42
UPDATE:
It's work with Single_Nozzle

**Comment by sergiofagundes** [comment] 2018-09-01 12:21
Only repetier 0.92 works without any issues with diamond hotend. I have tested all versions of marlin and none works.

**Comment by thinkyhead** [comment] 2018-09-09 07:57
Many changes were made to the planner / stepper code for 1.1.9 by @ejtagle, myself, and a few others. Perhaps we broke the `MIXING_EXTRUDER` in the process.

Be sure to do `M502`, `M500` after any re-flash to refresh the EEPROM and current settings.

**Comment by e-Mole** [comment] 2018-09-09 12:10
The same problem in Marlin 1.1.9 (A. Mega + RAMPS) - extruder motor speed is too high if MIXING_EXTRUDER is ON (with E3D Cyclops hotend).

And second, this code will return message: "Warning: Mix factors must add up to 1.0. Scaling." Is this gcode correct or am I wrong?
M163 S0 P0.5
M163 S1 P0.5
M164 S2

**Comment by ejtagle** [comment] 2018-09-09 23:01
@e-Mole : Are you using Linear Advance ? ... It is not supported with mixing extruder ... I still have to figure out how to make it work, but it is very hard to do.
Make sure to completely disable Linear advance!

**Comment by e-Mole** [comment] 2018-09-10 06:04
@ejtagle : LIN_ADVANCE is disabled (I forgot to write that my printer is delta)

**Comment by ghost** [comment] 2018-09-10 06:52
I tried with disabled LA, Junction Deviation and S-Cruve and the same problem.

**Comment by e-Mole** [comment] 2018-09-12 16:58
@3DRaft : Do you also use a Delta printer or Cartesian printer?

**Comment by thinkyhead** [comment] 2018-09-17 08:57
Duplicate of #11310.

**Closed as completed by thinkyhead** 2018-09-17 08:57 UTC
