### ISSUE TITLE
[FR] Zoned Heated bed

### ISSUE THREAD

**Issue by MrExo3D** [MarlinFirmware/Marlin#5098] opened 2016-10-27 15:21 UTC
Zoned heated beds seem to be something that is becoming a popular feature

It could be a bed with an outer and inner heater, with separate thermistor probes to monitor each
or it could be a bed with 4 zones.. one on each corner..
or a wide bed with a left and right side.

I think adding support for separate Zones, each with PID support, Thermistor, should be considered.
also adding LCD Support to the different zone temps,

**Comment by sjasonsmith** [comment] 2020-11-29 22:33
Duplicate of #4112

**Closed as completed by sjasonsmith** 2020-11-29 22:33 UTC
Labels: T: Feature Request
