### ISSUE TITLE
[FR] Detect filament runout/jams by measuring extruder motor current?  

### ISSUE THREAD

**Issue by jmding8** [MarlinFirmware/Marlin#20540] opened 2020-12-22 04:47 UTC
### Description

Filament runout and hotend jam detection, without any additional hardware (beyond TMC stepper drivers)

### Feature Workflow

1. TMC stepper driver (for extruder motor) reports current consumption to Marlin in real-time
2. Normal operation of printer results in some level of backpressure in the extrusion system. The higher the backpressure, the higher the torque demands on the extruder motor and stepper driver. If the filament runs out, the backpressure vanishes, the current consumption drops to a very low level, Marlin detects this and runs the filament runout subroutine. 
3. Alternatively, if a filament jam occurs, the backpressure at the extruder spikes, causing a spike in current at the stepper driver. Marlin detects this, and runs the filament-jam subroutine.

#### Additional Information

This is just an initial proposal to talk through the feasibility of such a feature, and see if anyone might be interested in taking it on. The advantage of such a system is that it would not require any additional hardware which, in addition to adding cost, adds additional opportunities for failures.

**Comment by thisiskeithb** [comment] 2020-12-22 04:50
Duplicate of https://github.com/MarlinFirmware/Marlin/issues/14497

**Closed as completed by thisiskeithb** 2020-12-22 04:50 UTC
Labels: T: Feature Request
