### ISSUE TITLE
[BUG] Power loss recovery does not continue printing

### ISSUE THREAD

**Issue by cguerrero1205** [MarlinFirmware/Marlin#19602] opened 2020-10-03 16:34 UTC
### Bug Description

My Ender 3 pauses after a power outage, heats the bed and nozzle, returns to where it was before the power outage, but the nozzle stays still at that point.

### My Configurations

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/5321982/Marlin.zip)

### Steps to Reproduce

1. Start an impression.
2. I cut the power manually.
3. I turn on the machine again.
4. I click on "resume printing" in the " power loss recovery" menu.
5. The nozzle and bed begin to heat
6. After the temperature is reached, the nozzle moves to the point where it was before the power failure, but stays still at that point, the machine does not move anymore and on the LCD it says "printing", but I said before, the nozzle doesn't move anymore.

**Expected behavior:** Print needs to resume where it left off.

**Actual behavior:** It remains in an eternal pause.

#### Additional Information

* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.

**Comment by katherinehackworth** [comment] 2020-10-04 04:39
I was about to make an issue for the exact same problem. It seems like it only does a single print move after it resumes, and then hangs indefinitely. I'm on a SKR Mini E3 v1.2 with the BTT UPS 24V for power loss recovery, and it looks like you're on the stock board. Same exact issue here. Still looking around to see if this is an isolated thing or a bug in 2.0.7. I can add my config files if needed too.

**Comment by cguerrero1205** [comment] 2020-10-04 15:35
> I was about to make an issue for the exact same problem. It seems like it only does a single print move after it resumes, and then hangs indefinitely. I'm on a SKR Mini E3 v1.2 with the BTT UPS 24V for power loss recovery, and it looks like you're on the stock board. Same exact issue here. Still looking around to see if this is an isolated thing or a bug in 2.0.7. I can add my config files if needed too.

Hi Katerine.
I've been checking the configuration of the Marlin I have loaded on my printer, but I can't find any problems. I even reloaded it with the sample configuration files for Ender 3, only activating the Power Loss Recovery, but I still have the same problem.

**Comment by katherinehackworth** [comment] 2020-10-04 22:42
[I've added my config files in a Gist here for posterity's sake.](https://gist.github.com/katherinehackworth/1d8e944c5fe0655753ebb9e71b1c10d2)

**Comment by cguerrero1205** [comment] 2020-10-04 23:43
I will install some previous version of Marlin, to see if it solves the problem.

**Comment by pkfloyd** [comment] 2020-10-05 09:16
hi, 
have the tevo/homers tarantula pro, with MKS Lgen v1 and have de same problem.

**Comment by cguerrero1205** [comment] 2020-10-06 15:15
Hello. 
I still can't solve the problem. How are you doing with the problem?

**Comment by pkfloyd** [comment] 2020-10-06 18:42
hi, 
i have change the  powerloss.cpp and powerloss.h from marlin 2.0.6 to 2.0.7 and it work, now i have porwer_loss resume with no pin (always save in card)

**Comment by cguerrero1205** [comment] 2020-10-06 19:43
> hi,
> i have change the powerloss.cpp and powerloss.h from marlin 2.0.6 to 2.0.7 and it work, now i have porwer_loss resume with no pin (always save in card)

Great! I will try to do the same.

**Comment by cguerrero1205** [comment] 2020-10-06 19:47
Then the problem is in the PLR library. I will try to compare those libraries in Marlin 2.0.6 and 2.0.7, to find the error. Hopefully some official Marlin developer will see this thread and can help.

**Comment by pkfloyd** [comment] 2020-10-06 20:22
i have tried to do this, but don´t now anything about coding  :(

**Comment by pkfloyd** [comment] 2020-10-08 18:22
hi, have you find the issue?

ths file change work?

**Comment by cguerrero1205** [comment] 2020-10-08 18:31
> hi, have you find the issue?
> 
> ths file change work?

Hi, I have spent hours reviewing and comparing the powerloss files, but they made many modifications from version 2.0.6 to 2.0.7 and I haven't found the problem.
Likewise, I changed the files in the PLR library, but now the problem is that the Z axis starts from the wrong height.
As I said before: the hope is that some Marlin developer will see this thread, and hope that they will make some solution.
I've also been looking at the bugfix version, but so far they haven't talked about PLR.

**Comment by pkfloyd** [comment] 2020-10-08 18:34
the two files, its only for PLR, why change your Z axis...? strange...

**Comment by cguerrero1205** [comment] 2020-10-08 18:39
> the two files, its only for PLR, why change your Z axis...? strange...

Yes, I think it may be that, while the printer is off, the Z-axis goes down because the motor is not braked and that causes the position in the Z-axis to be lost.

At the moment, I have the printer running with PLR disabled, praying that the power does not cut again, as in recent days (I lost a print that took 20 of 22 hours).

Has PLR worked well for you after replacing the files?

**Comment by pkfloyd** [comment] 2020-10-08 19:13
the test i made yes, work great.

i will test again.

it locks the ender 3 v2 with 2.0.7 have the same issue. lets wait for news.

**Comment by cguerrero1205** [comment] 2020-10-08 19:24
Yes, it's like I told you: between the changes they made from Marlin 2.0.6 to 2.0.7, it was in PLR, they changed a lot of things, I guess something went wrong. The strange thing is that until now we have very few people reporting that problem, I don't know if it is something that doesn't affect everyone at the moment of updating.

**Comment by pkfloyd** [comment] 2020-10-08 20:07
maybe people don't notice. 
after installing 2.0.7 teste printing and runout sensor. i notice PLR bug with some lucky on the beginning of piece.

**Comment by borsegbr** [comment] 2020-10-09 01:52
Same problem with skr 1.4 turbo and btt tft35 v3.0


[configs.zip](https://github.com/MarlinFirmware/Marlin/files/5351998/configs.zip)

serial prompt say:

```
echo:Active Extruder: 0
M106 P0 S255
echo:Bed Leveling ON
echo:Fade Height 2.00
echo:Now fresh file: /LASER~1.GCO
open failed, File: LASER~1.GCO.
//action:resume

```

**Comment by pkfloyd** [comment] 2020-10-09 07:06
More people with this issue. Ok, need to wait for correction.

thanks

**Comment by borsegbr** [comment] 2020-10-09 09:23
in addition after abort resume serial say 

```
Deletion failed, File: PLR.
Power-loss file delete failed.
```

and if i try to print from media is void i have to select change media couple of time and file appears
seems that sd is not correct inizialize in resume print procedure 
maybe @thinkyhead that knows well code can help us

**Comment by pkfloyd** [comment] 2020-10-09 18:00
hi, today a test again and its work fine the PLR, (i have change the powerloss.cpp and powerloss.h from marlin 2.0.6 to 2.0.7 ) and use vscode com compile.
i have mks Lgen 32bits board and use cura 4.7.1.

don't now anything about coding.. think i have luck with the file change.

**Comment by borsegbr** [comment] 2020-10-09 23:22
> hi, today a test again and its work fine the PLR, (i have change the powerloss.cpp and powerloss.h from marlin 2.0.6 to 2.0.7 ) and use vscode com compile.
> i have mks Lgen 32bits board and use cura 4.7.1.
> 
> don't now anything about coding.. think i have luck with the file change.

not for me still not working with 2.0.6

**Comment by cguerrero1205** [comment] 2020-10-10 22:16
Today they made a PLR correction in the bugfix version. It's time to do a quick test to see if it solves our problem, although they don't mention anything about it.

https://github.com/MarlinFirmware/Marlin/pull/19676

**Comment by pkfloyd** [comment] 2020-10-11 08:50
hi, never use a bug fix.
how cant a download and test to?

**Comment by ellensp** [comment] 2020-10-11 09:13
@pkfloyd  go to https://github.com/MarlinFirmware/Marlin/tree/bugfix-2.0.x click on big green CODE icon and download zip 
Then update config file as needed. Compile and upload

**Comment by borsegbr** [comment] 2020-10-11 19:55
> Today they made a PLR correction in the bugfix version. It's time to do a quick test to see if it solves our problem, although they don't mention anything about it.
> 
> #19676

even worst, when i start printing any gcode  lcd show resume from powerloss: 3d printer halted: please reboot

**Comment by pkfloyd** [comment] 2020-10-15 20:24
hi, today i compile the marlin 2.0.7.1 and have the same issue.

PLR don't work.  wend  its turn on, say "resume" but nozzle go to piece and don`t move.

**Comment by cguerrero1205** [comment] 2020-10-15 20:47
I have already stopped testing. I am working without PLR. Play like this until the developers help us and solve the problem. I just hope I don't cut the power and lose some long impression.

**Comment by pkfloyd** [comment] 2020-10-15 20:49
think its to important, for not use, go back to version that work...

**Comment by borsegbr** [comment] 2020-10-15 20:55
> think its to important, for not use, go back to version that work...

what version work for you?

**Comment by pkfloyd** [comment] 2020-10-15 20:56
4.0.6 work fine

**Comment by cguerrero1205** [comment] 2020-10-16 01:30
4.0.6 or 2.0.6?

**Comment by katherinehackworth** [comment] 2020-10-16 02:18
I assumed @pkfloyd meant 2.0.6 because there isn't any marlin 4.0.6.

**Comment by cguerrero1205** [comment] 2020-10-16 02:26
> I assumed @pkfloyd meant 2.0.6 because there isn't any marlin 4.0.6.

I assumed the same thing. Tomorrow I will try version 2.0.6.1

**Comment by pkfloyd** [comment] 2020-10-16 06:57
Hi, sorry my bad

Marlin 2.0.6  (not 4.0.6)  

And don't have installed 2.0.6.1

**Comment by thinkyhead** [comment] 2020-10-16 07:00
Power-loss recovery is always a challenge to keep up with. We ought to get some devs on really digging into the real problems and solutions by testing this feature on their own machines, but it's always a question of free time. I put in some hours last month and made some improvements, but as they say in engineering, in any complex system there are bound to be little cracks…

**Comment by boelle** [comment] 2020-10-16 08:30
i can chime in from what i know about how prusa does it

it starts with the controller, the einsy will as soon it get the signal from the psu stop heating the bed, this is done hardware wise and you can check the schematic to verify 

this alone saves power, and gives it enough power and time to move out of the way and save progress

without this only the invisible man in the sky knows what will happen


but the takeaway is that both psu and controller needs to be up for it, if stopping powering the bed is done in software that cost extra power and it might just be what is needed

**Comment by ibrahimnadi** [comment] 2020-10-19 21:20
Hello, I am having the same problem. Did you solve the problem? What method should I follow?

**Comment by cguerrero1205** [comment] 2020-10-19 22:23
> Hello, I am having the same problem. Did you solve the problem? What method should I follow?

Hi, the only solution we have found so far is to go back to version 2.0.6, this until the developers help us, find and solve the problem.

**Comment by pkfloyd** [comment] 2020-10-20 20:31
hi, Marlin 2.0.7.2 its out, anyone have tried if this issue its corrected? 

thanks

**Comment by ibrahimnadi** [comment] 2020-10-20 20:48
I will try today. I write the result.

**Comment by borsegbr** [comment] 2020-10-20 21:08
> hi, Marlin 2.0.7.2 its out, anyone have tried if this issue its corrected?
> 
> thanks

Same issue on skr1.4 turbo

**Comment by boelle** [comment] 2020-10-20 21:19
> developers help us, find and solve the problem.

they work for free so it can take a long time

**Comment by ibrahimnadi** [comment] 2020-10-20 21:25
I've been trying to run the power loss feature for two days. I did not succeed in any version. It did not work in version 2.0.7.2 either. When I say continue printing, the printer goes to the point where it was and stops.

I am using bigtreetech ups module. not detecting power loss. Z axis does not go up. 

Couldn't compile version 2.0.6, gives error vscode. :(

**Comment by boelle** [comment] 2020-10-20 21:32
> Couldn't compile version 2.0.6, gives error vscode. :(

Configurations, please
Please ZIP up your `Configuration.h` and `Configuration_adv.h` files (as
requested in the Issue template) and drop them into your next reply.
We'll check them over and see if anything is amiss.

Please test the [`bugfix-2.0.x branch`](https://github.com/MarlinFirmware/Marlin/tree/bugfix-2.0.x) to see where it stands. If the problem has been resolved then we can close this issue. If the issue isn't resolved yet, then we should investigate further.

**Comment by ibrahimnadi** [comment] 2020-10-20 21:50
> Lütfen [`bugfix-2.0.x branch`](https://github.com/MarlinFirmware/Marlin/tree/bugfix-2.0.x)nerede durduğunu görmek için test edin . Sorun çözüldüyse, bu sorunu kapatabiliriz. Sorun henüz çözülmediyse, daha fazla araştırma yapmalıyız.

Firstly, thank you.

I also compiled and installed the 2.0 bugfix version. But it does not detect power loss. My problem is that:

I want to use Bigtreetech mini ups 2.0 module. I assembled it according to the instructions. When I turn off the power, it should detect the interruption from the Z MAX pin number 19 and raise the z-axis 5mm.

But when I turn off the power, it continues to print and then the printer turns off.

When I turn the printer back on, there is no continue message.

I've tried several marlin firmware to solve this. But I could not reach a solution.

**Comment by borsegbr** [comment] 2020-10-20 23:10
> I've been trying to run the power loss feature for two days. I did not succeed in any version. It did not work in version 2.0.7.2 either. When I say continue printing, the printer goes to the point where it was and stops.

This is point


> I am using bigtreetech ups module. not detecting power loss. Z axis does not go up.
> 
> Couldn't compile version 2.0.6, gives error vscode. :(

This Is another problem not related, here bug is print doesn't restart after successful power loss catch

**Comment by boelle** [comment] 2020-10-21 09:05
> Firstly, thank you.

Configurations, please
Please ZIP up your `Configuration.h` and `Configuration_adv.h` files (as
requested in the Issue template) and drop them into your next reply.
We'll check them over and see if anything is amiss.

**Comment by ibrahimnadi** [comment] 2020-10-21 10:53
My configuration and configuration_adv files marlin 2.0.7.2
[configuration and adv 2072.zip](https://github.com/MarlinFirmware/Marlin/files/5415306/configuration.and.adv.2072.zip)


> Please ZIP up your `Configuration.h` and `Configuration_adv.h` files

**Comment by katherinehackworth** [comment] 2020-10-22 02:12
> > Firstly, thank you.
> 
> Configurations, please
> Please ZIP up your `Configuration.h` and `Configuration_adv.h` files (as
> requested in the Issue template) and drop them into your next reply.
> We'll check them over and see if anything is amiss.

[Here are mine for 2.0.7](https://gist.github.com/katherinehackworth/1d8e944c5fe0655753ebb9e71b1c10d2)

**Comment by swanlm** [comment] 2020-10-24 05:07
> I've been trying to run the power loss feature for two days. I did not succeed in any version. It did not work in version 2.0.7.2 either. When I say continue printing, the printer goes to the point where it was and stops.
> 
> 
> 
> I am using bigtreetech ups module. not detecting power loss. Z axis does not go up. 
> 
> 
> 
> Couldn't compile version 2.0.6, gives error vscode. :(

Check whether Configuration -> Power Loss Resume is set to on in your display. If you didn't set it to default On in your configuration then you have to set via LCD or via M Command.

**Comment by katherinehackworth** [comment] 2020-10-26 03:56
There appear to be several issues here - some have power loss recovery that doesn't trigger at all on outage, some have PLR that triggers but doesn't prompt for resume on power recovery, and some (ie: myself) have PLR that after prompting for resume, heats back up, moves to the correct spot on the print, and then simply sits ad infinitum.

**Comment by pkfloyd** [comment] 2020-10-30 21:18
hi, so any news about this issue?

**Comment by hollanbri** [comment] 2020-10-30 23:21
I can confirm the main problem exists in the latest bugfix build.
I have Ender 3, with BigTreeTech SKR Mini E3 V2 mother board, BTT 24V UPS, BLTouch and Filament sensor.
I downloaded the current BugFix build and compiled with my configuration settings.
Attached are my Configuration.h Configuration_adv.h and src/pins/stm32f1/pins_BTT_SKR_MINI_E3_common.h (due to BLTouch wired to BUZZER and E0 pins - don't ask)

Upon power off the printer soon (within a second or two) starts the power off sequence with Z raising 5mm and E 10mm - then stops as it should.
Upon power resume I observe these actions:
  prompt to recover,
  head moves home
  the bed heats to temperature
  then head heats to temperature
  purge 20mm, 
  move head to where it was when power stop.
  And nothing else...
  
It just sits there - If I do a pause it will move up and on resume back, but still does not start printing.

By the way - I would like it if the bed and head heated at same time - to save my time.

As for the other 2 problems in this thread - I see Marlin detecting the power off, so double check configuration and pin state.  I see the prompt to recover.  So these features do work, at least in my configuration.
[config.zip](https://github.com/MarlinFirmware/Marlin/files/5468080/config.zip)

**Comment by cguerrero1205** [comment] 2020-10-31 04:32
Hello.

I am now in version 2.0.6.1 and PLR works well. I will stay in that version for the time being. Besides I made some modifications to add the z homing after a power loss, the z position was sometimes lost; I disabled some sub-menus, to save memory and invest it in linear advance, S-curve, filament sensor and other useful options.

At the moment, I have no complaints about version 2.0.6.

**Comment by Sergey1560** [comment] 2020-11-02 11:45
I tried it on 2.0.7.2 (2.0.x branch) and the problem is still there. I researched a little what was the matter.
Printing does not start because the M23 command cannot open the file. The trace is like this:
*M23()* call *file.open(diveDir, fname, O_READ)*
*SdBaseFile::open(SdBaseFile* dirFile, const char* path, uint8_t oflag)*  call  "return open(parent, dname, oflag);"
SdBaseFile::open(SdBaseFile* dirFile, const uint8_t dname[11], uint8_t oflag) call "p = dirFile->readDirCache();"
And, finally, at readDirCache() call to isDir() fail. The value of type_ at that mement is 0.

I could not figure out how the module SdBaseFile works with the file system, so I could not find the cause of the error. But I found a temporary solution. It is enough to add
```
card.release();
card.mount();
```
at start of PrintJobRecovery::resume() function and everything starts working.

I didn't make PR, I hope someone who knows how the module works will be able to find the cause of the error.

**Comment by cguerrero1205** [comment] 2020-11-02 11:58
> I tried it on 2.0.7.2 (2.0.x branch) and the problem is still there. I researched a little what was the matter.
> Printing does not start because the M23 command cannot open the file. The trace is like this:
> _M23()_ call _file.open(diveDir, fname, O_READ)_
> _SdBaseFile::open(SdBaseFile_ dirFile, const char* path, uint8_t oflag)* call "return open(parent, dname, oflag);"
> SdBaseFile::open(SdBaseFile* dirFile, const uint8_t dname[11], uint8_t oflag) call "p = dirFile->readDirCache();"
> And, finally, at readDirCache() call to isDir() fail. The value of type_ at that mement is 0.
> 
> I could not figure out how the module SdBaseFile works with the file system, so I could not find the cause of the error. But I found a temporary solution. It is enough to add
> 
> ```
> card.release();
> card.mount();
> ```
> 
> at start of PrintJobRecovery::resume() function and everything starts working.
> 
> I didn't make PR, I hope someone who knows how the module works will be able to find the cause of the error.

Excellent!

Everyone to try that solution and comment on the results. It may not be the final solution, but the important thing is that it is functional and allows the use of PLR in version 2.0.7.
Maybe the developers will see your comment, get an idea of what's going on and get to the bottom of the problem. Because they do understand the part of the code that you don't.
Again, thank you very much for your help and the time you spent to find a solution.

**Comment by cguerrero1205** [comment] 2020-11-02 12:03
I closed the publication by mistake, so I opened it again.

**Comment by boelle** [comment] 2020-11-02 16:06
@cguerrero1205 was this one not solved?

if there is a fix in here it should be sent in as a PR so things can be fixed faster

**Comment by Sergey1560** [comment] 2020-11-02 16:10
> @cguerrero1205 was this one not solved?
> 
> if there is a fix in here it should be sent in as a PR so things can be fixed faster

There is a workaround, but not a fix.  The PLR function will work, but the real problem has not been resolved.

**Comment by boelle** [comment] 2020-11-02 16:15
oki, workarounds does not count so yes not resolved

**Comment by pkfloyd** [comment] 2020-11-02 23:59
hello, I'm sorry but I didn't understand how the temporary solution is made.
where we put this?
card.release();
card.mount();

**Comment by cguerrero1205** [comment] 2020-11-03 03:10
> hello, I'm sorry but I didn't understand how the temporary solution is made.
> where we put this?
> card.release();
> card.mount();

Hello.
You should add those lines to the beginning of the "PrintJobRecovery::resume" function found in the "powerloss.cpp" file.

**Comment by pkfloyd** [comment] 2020-11-03 19:33
like this:

/**
 * Resume the saved print job
 */
void PrintJobRecovery::resume() {
   card.release();
   card.mount();
  char cmd[MAX_CMD_SIZE+16], str_1[16], str_2[16];

  const uint32_t resume_sdpos = info.sdpos; // Get here before the stepper ISR overwrites it

  // Apply the dry-run flag if enabled
  if (info.flag.dryrun) marlin_debug_flags |= MARLIN_DEBUG_DRYRUN;
....

**Comment by cguerrero1205** [comment] 2020-11-07 22:52
As Sergey1560 has reported, they have already scaled the solution and it was added in the MarlinFirmware:bugfix-2.0.x. Tomorrow I will try to see how it goes to me. Wish me luck.

**Comment by pkfloyd** [comment] 2020-11-07 22:55
i have read to. 
try and send feedback.

**Comment by katherinehackworth** [comment] 2020-11-09 00:51
@cguerrero1205 did it work or did you die

**Comment by noob-hart** [comment] 2020-11-10 15:13
@cguerrero1205 did you're printer set itself on fire,or does the bug fix work

**Comment by TheMatrix97** [comment] 2020-11-11 22:04
> even worst, when i start printing any gcode lcd show resume from powerloss: 3d printer halted: please reboot

I faced the same problem, something isn't working in Bugfix-2.0.x for skr mini e3 1.2. Finally I solved it overwritting powerloss.cpp and powerloss.h from version 2.6.0 (as stated at the beginning of the issue)

**Comment by cguerrero1205** [comment] 2020-11-11 22:13
Hello.
I had to leave on a trip and I haven't been able to do the tests. As soon as I return, I will do it.

**Comment by Sergey1560** [comment] 2020-11-12 10:41
No need to change powerloss.cpp and powerloss.h from version 2.6.0
The difference is in powerloss.h:
2.0.7:
    static inline bool interrupted_file_exists() { return card.fileExists(info.sd_filename); }
    static inline bool valid() { return info.valid() && interrupted_file_exists(); }

2.0.6:
   static inline bool valid() { return info.valid(); }

The difference is in card.fileExists call. 
I checked, if the file is specified without "/" ("myfile.g" instead of "/myfile.g") when recovering, then everything works (i checked this by changing the line in the debugger). Something breaks inside the fileExist function, but I haven't figured out what exactly. I continue to study, I hope to find the exact reason.

**Comment by slgorin** [comment] 2020-11-14 13:33
I am having the same issue, just upgraded to 2.0.7.2 to see if any difference and it stays in back corner doing nothing after its warmed back up.  Any progress on fixing this?

**Comment by sjasonsmith** [comment] 2020-11-14 17:11
A pull request was merged 9 days ago that may resolve this. Please be sure to test with the latest bugfix-2.0.x code.

@Sergey1560 are you still working on finding a better solution?

**Comment by swanlm** [comment] 2020-11-16 07:51
Just some feedback; I had exactly the same issue as described in this bug. Today I took the latest bug fix build and put this on my printer. I tested the power restore feature and
1. The nozzle lifts up as expected when power is removed
2. I am asked if I want to resume when power is switched back on
3. If I resume, the printer homes on X and Y, heats the bed and nozzle and then continues printing from where it left off. 

So this looks to be fixed.

**Comment by Sergey1560** [comment] 2020-11-16 08:40
> A pull request was merged 9 days ago that may resolve this. Please be sure to test with the latest bugfix-2.0.x code.
> 
> @Sergey1560 are you still working on finding a better solution?

Yes, I am trying to find the real reason. 
The problem is somewhere in the file system with fileExist funciton, not in the "powerloss".

**Comment by Aracos** [comment] 2020-11-19 10:16
Still got the same Problem ( Compiled the latest Bugfix yesterday ) for a Tronxy XY-2 Pro with V6 Board.
Goes to X Y Home, Heats up, then nothing. Touchscreen says printing.

**Comment by borsegbr** [comment] 2020-11-19 10:31
https://github.com/MarlinFirmware/Marlin/pull/20035#issue-516017686
This for me fix the problem, now work well

**Comment by Aracos** [comment] 2020-11-20 22:14
Yep. Fixed it for me too. Just found out i compiled the Release Version and not the Bugfix.

**Comment by slgorin** [comment] 2020-11-22 23:37
no, still not fixed.  When it resumes, it homes, raises z, the bltouch senses height  on the part and when the print resumes, the z height is higher than where it left off and it does not stick to the part.  have tried it twice with and without pause.

**Comment by borsegbr** [comment] 2020-11-23 00:10
> no, still not fixed. When it resumes, it homes, raises z, the bltouch senses height on the part and when the print resumes, the z height is higher than where it left off and it does not stick to the part. have tried it twice with and without pause.

this is not related to this issue

**Comment by Marlina-Marlino** [comment] 2020-11-23 00:14
Hello 
I have the same issue and I tried to figure it out.

My board is MKS SGEN L V1.0
Dirvers  MKS TMC2209 V2.0
Marlin 2.0.7.1

I noticed that there is an option in Marlin 2.07 (Advanced Configurations) which is 

#define SDCARD_CONNECTION LCD

if you specify the SDCARD location to be either onboard or in the LCD, I think this will solve the issue and help Marlin Firmware to get access to the PLR file

please use the same SDCARD SLOT you specified in your Marlin version
Please check and report back if the problem is solved

**Comment by swanlm** [comment] 2020-11-23 06:24
Hi

I have an SKR Mini E3 v2.0 and so specify:
	#define SDCARD_CONNECTION ONBOARD

That was defined long ago and still the bug existed for me. So I don’t think this would be the solution. The latest bug fix with the workaround solves the problem for me.

**Comment by boelle** [comment] 2020-11-23 09:54
> Marlin 2.0.7.1

Please test the [`bugfix-2.0.x branch`](https://github.com/MarlinFirmware/Marlin/tree/bugfix-2.0.x) to see where it stands. If the problem has been resolved then we can close this issue. If the issue isn't resolved yet, then we should investigate further.

**Comment by boelle** [comment] 2020-11-23 09:55
@cguerrero1205 when will you be back?

**Comment by cguerrero1205** [comment] 2020-11-23 15:52
Hello.
I just got back yesterday.

I just loaded the Bugfix-2.0.x version and the problem is fixed, but I still don't know whether to close this thread, as @Sergey1560 is still investigating the origin of the problem. I think that if it were necessary to close it, @thinkyhead would have closed it when he made the correction in Bugfix-2.0.x.

**Comment by sjasonsmith** [comment] 2020-11-23 17:16
Let’s give @Sergey1560 some time to investigate and get back. I believe the earlier fix was a workaround, without understanding or fixing the true root-cause.

**Comment by Sergey1560** [comment] 2020-11-24 08:49
I have not yet been able to find the exact problem, there is a slight lack of time for everything. But when it possible, I continue to work.

I have a suggestion. Maybe we should open a new issue, with a description of how to reproduce the problem in a simple way? This will possibly attract the attention of other developers. The problem is more important than it seems, it is not with the Power loss recovery module, but with the operation of the file system and may be reflected in the future in some other place.

The possible involvement of more experienced developers will help fix the problem faster.

How to reproduce the problem in a simple way, without need of Power loss recovery:
1. I add simple test function to Marlin/src/sd/cardreader.cpp:

```
// Test file read
void CardReader::check_file_read() {
  const char path[] = "/test.g";
  SdFile *diveDir;

  SERIAL_ECHOLN("Test read fucntion:");
  
  if(!card.isMounted()){
    card.mount();
  }
  
  const char * const fname = diveToFile(true, diveDir, path);
  if (!fname) return;

  if (file.open(diveDir, fname, O_READ)) {
    SERIAL_ECHOLN("First file open - Ok");
    file.close();
  }else{
    SERIAL_ECHOLN("First file open - fail");
  }

  if(fileExists(path)){
    SERIAL_ECHOLN("File exist");
  }else{
    SERIAL_ECHOLN("File not exist");
  }

  if (file.open(diveDir, fname, O_READ)) {
    SERIAL_ECHOLN("Second file open - Ok");
    file.close();
  }else{
    SERIAL_ECHOLN("Second file open - fail");
  }
}
```
This function is not for merge, just for testing the problem.

2. Revert #20035, by uncommenting "diveDir->close();" in fileExists.
3. Add call of the card.check_file_read() somewhere. I add it in the end of setup().
4. Place file "test.g" and try it. 

Output for me is:
```
Test read fucntion:
First file open - Ok
File exist
Second file open - fail
```

**Comment by Crunch69** [comment] 2020-12-02 22:44
I have been pulling my hair out for 2 days only to find many people are having the exact same problem

**Comment by nvumnov** [comment] 2020-12-05 14:07
Isn't anyone interested in this problem. The long-standing problem has not yet been solved. By the way, bugfix also has this problem.

**Comment by maxlinux2000** [comment] 2020-12-07 23:07
still occurs on marlin 2.0.7.2

**Comment by cguerrero1205** [comment] 2020-12-07 23:14
> Isn't anyone interested in this problem. The long-standing problem has not yet been solved. By the way, bugfix also has this problem.

The bugfix version should not present the problem, since they added the solution in one of their interactions.

**Comment by cguerrero1205** [comment] 2020-12-07 23:15
> still occurs on marlin 2.0.7.2

Try with bugfix version

**Comment by github051** [comment] 2020-12-08 04:58
I tried with the latest bugfix version and the issue is the same.

**Comment by borsegbr** [comment] 2020-12-08 07:34
Describe your issue and post configs file

Il mar 8 dic 2020, 05:58 github051 <notifications@github.com> ha scritto:

**Comment by github051** [comment] 2020-12-13 09:40
> I tried with the latest bugfix version and the issue is the same.

Finally, with the latest bugfix, power loss recovery is working fine. My board is MKS Robin v1.4 and to detect the power loss i'm using the MKS Power det module.

Here is my settings:
  #define POWER_LOSS_RECOVERY
  #if ENABLED(POWER_LOSS_RECOVERY)
    #define PLR_ENABLED_DEFAULT   true // Power Loss Recovery enabled by default. (Set with 'M413 Sn' & M500)
    //#define BACKUP_POWER_SUPPLY       // Backup power / UPS to move the steppers on power loss
    //#define POWER_LOSS_RECOVER_ZHOME  // Z homing is needed for proper recovery. 99.9% of the time this should be disabled!
    //#define POWER_LOSS_ZRAISE       2 // (mm) Z axis raise on resume (on power loss with UPS)
    #define POWER_LOSS_PIN         PA2 // Pin to detect power loss. Set to -1 to disable default pin on boards without module.
    #define POWER_LOSS_STATE     LOW // State of pin indicating power loss
    //#define POWER_LOSS_PULLUP         // Set pullup / pulldown as appropriate for your sensor
    //#define POWER_LOSS_PULLDOWN
    #define POWER_LOSS_PURGE_LEN   20 // (mm) Length of filament to purge on resume
    //#define POWER_LOSS_RETRACT_LEN 10 // (mm) Length of filament to retract on fail. Requires backup power.

    // Without a POWER_LOSS_PIN the following option helps reduce wear on the SD card,
    // especially with "vase mode" printing. Set too high and vases cannot be continued.
    #define POWER_LOSS_MIN_Z_CHANGE 0.05 // (mm) Minimum Z change before saving power-loss data
  #endif

**Comment by github051** [comment] 2020-12-13 10:07
I hope we can close this issue.

**Comment by boelle** [comment] 2020-12-13 11:22
It seems this has been fixed in the bugfix version, all the other versions are just frozen copies of bugfix

will close this one, we can reopen if it can be demonstrated that the issue is still there

**Closed as completed by boelle** 2020-12-13 11:22 UTC
Labels: F: Print Recovery
