### ISSUE TITLE
[FR] 2 mixing hotends support

### ISSUE THREAD

**Issue by Services8810** [MarlinFirmware/Marlin#26053] opened 2023-07-05 13:11 UTC
### Describe the feature you want

2 mixing hotends support

### Additional context

I have a custom printer with mixing hotend. I would like to ask if is it possible to add another mixing hotend next to it and configure marlin to use both hotends. Sonething like e3d kraklops, if someone has seen it, but custom made.

Thanks

**Comment by thisiskeithb** [comment] 2023-07-05 13:56
Duplicate of https://github.com/MarlinFirmware/Marlin/issues/19449

**Closed as completed by thisiskeithb** 2023-07-05 13:56 UTC
Labels: T: Feature Request
