### ISSUE TITLE
[BUG] Junction Deviation is Borked....

### ISSUE THREAD

**Issue by DaMadOne** [MarlinFirmware/Marlin#17146] opened 2020-03-13 01:38 UTC
There are numerous reports of JD affecting prints when LA is used. There has been much discussion about it and it seems the bug reports get closed due to inactivity most of the time. But something isn't right,

From left to right is Cura with JD enabled, then classic jerk. The 3rd and 4th print is Prusa Slicer both with JD enabled and without. I don't use Cura much and as such my profile is probably not that dialed in an why it doesn;t look as good..

I'm only showing it to show that the slicer used doesn't really matter much. It doesn't take a rocket scientist to see the prints with classic jerk are better.The 1st and 3rd print are jagged AF and the 2nd and 4th ones are much better.

With JD enabled the extruder goes nuts on circular prints and is very herky jerky producing the 1st and 3rd print of the Tux model that is not right.. . Without JD enabled circular prints are very smooth. Logic dictates that JD should be much better than classic jerk... but real world tests show otherwise.

I'm running an Ender 3 Pro with an SKR E3 DIP with TMC2209's. 

![image](https://user-images.githubusercontent.com/698003/76673394-7e6d7080-6572-11ea-9a02-cdfba1f4485a.png)

I printed them with the same Marlin 2.0.4.4 firmware so configuration doesn't really matter but if you want me to post my config files then let me know.

**Comment by thisiskeithb** [comment] 2020-03-13 02:10
> I printed them with the same Marlin 2.0.4.4 firmware so configuration doesn't really matter but if you want me to post my config files then let me know.

Yes, please zip up your configs and attach them for review.

**Comment by DaMadOne** [comment] 2020-03-13 04:03
Don't take my report as "talking shit"... That's not my intention at all. I hope you take a look at my configs and tell me I'm and idiot... I've spent the last couple of days making tweaks to various things and getting nowhere. For the most part my prints come out one of two ways.. looking like Tux 1&3 with JD enabled or Tux 2&4 with JD disabled.

[Marlin_config.zip](https://github.com/MarlinFirmware/Marlin/files/4327751/Marlin_config.zip)

**Comment by DaMadOne** [comment] 2020-03-13 04:15
What's weird is that it doesn't affect all circular  movements. Some circular movements don't make the extruder go crazy and come out fine...Some seem to be at too much of an angle and the extruder goes craszy.  So to me.. with my limited knowledge it seems like some sort of math issue. This particular Tux model is just the worst I've come across. The following is the thiniverse link .[https://www.thingiverse.com/thing:1809605](url) 

EDIT* I should have posted that I'm printing that model at 30% size.

**Comment by qwewer0** [comment] 2020-03-13 06:30
Printed the bottom of the model. [Here](https://imgur.com/a/vzbuuQ9) is my result.

Latest Bugfix, Ender 3, SKR Mini E3 v1.2

**Comment by thisiskeithb** [comment] 2020-03-13 13:30
@DaMadOne: You've overridden the default `MINIMUM_STEPPER_POST_DIR_DELAY`, `MINIMUM_STEPPER_PRE_DIR_DELAY`, `MINIMUM_STEPPER_PULSE`, and `MAXIMUM_STEPPER_RATE` settings.

Those are set for you automatically, so were defaults (commented out) not working on your TMC2209s?

**Comment by qwewer0** [comment] 2020-03-13 14:29
@thisiskeithb It is all disabled for me. I know that you didn't wrote it to me, just wanted to say it.

**Comment by thinkyhead** [comment] 2020-03-14 02:39
It may help to set the slicer to use minimum length segments. I'm not sure how a lot of short segments interact with these various settings versus curves with longer segments. This would be a good area of exploration.

**Comment by DaMadOne** [comment] 2020-03-14 04:09
> @DaMadOne: You've overridden the default `MINIMUM_STEPPER_POST_DIR_DELAY`, `MINIMUM_STEPPER_PRE_DIR_DELAY`, `MINIMUM_STEPPER_PULSE`, and `MAXIMUM_STEPPER_RATE` settings.
> 
> Those are set for you automatically, so were defaults (commented out) not working on your TMC2209s?

That change was made after I was already having problems. Another bug report here that was already closed but had a similar sounding issue mentioned those settings. So I looked at it and tried it. The comments pertaining to those config lines seem to suggest the settings I applied are the "best default" settings for the stepper drivers I'm using so I figured it was worth a shot. I didn't notice anything negative(or positive) from them in my testing so I left them. That same bug report did show that they used settings in the middle of all the defaults(and different from mine) and got positive results from it.. I have not tried those exact settings because the settings they said they used seemed to almost match the numbers in the commented out lines that I enabled and changed but saw no difference In my prints. So it didn't seem worth while to spend anymore time changing those.

I couldn't find it last night but another report had some videos posted in the comments. If you [watch](https://github.com/MarlinFirmware/Marlin/issues/16184#issuecomment-564683603) the before and after videos and try to filter out the other noise and just listen to the extruder then you can hear the difference. That sound it exactly what I'm seeing/hearing. 

Another model it show up on consistently is the benchy. Most of the boat hull prints well. There is a series of layers that cause this issue though. It's nowhere near as extreme as the tux model but you can't miss it when comparing LA with and without JD. Maybe someone who understands the math behind LA and JD can take a look at those models maybe have an idea of whats going on.

**Comment by DaMadOne** [comment] 2020-03-14 04:14
> It may help to set the slicer to use minimum length segments. I'm not sure how a lot of short segments interact with these various settings versus curves with longer segments. This would be a good area of exploration.



> It may help to set the slicer to use minimum length segments. I'm not sure how a lot of short segments interact with these various settings versus curves with longer segments. This would be a good area of exploration.

I will take a look at this tomorrow and will let you know the results.

**Comment by ghost** [comment] 2020-03-14 13:23
> It may help to set the slicer to use minimum length segments. I'm not sure how a lot of short segments interact with these various settings versus curves with longer segments. This would be a good area of exploration.

Could very well be, I guess OP should check how the layers are "drawn" in its slicer preview, additionally CNCKitchen has a video/semi-tutorial on youtube about this : https://www.youtube.com/watch?v=Hvw3DrVAeTA  
I found tweaking these settings gave me much smoother circles when openscad models were exported with a lot of definition ($fn >= 128)

**Comment by qwewer0** [comment] 2020-03-14 13:35
In my case there are no pausing at all, just continuous X / Y motor stuttering, that causes the rough layers/surface noticeable on the prints, but I can feel it on the stepper motors too when printing.

Edit:
By following the video, with changing Maximum Resolution 0.05 -> 0.5 and Maximum Travel Resolution 0.05 -> 0.7, it did help, but only a little. The result are better than the default with JD, but not as good with the classic jerk.

**Comment by ghost** [comment] 2020-03-14 14:21
You didn't post your configuration so it's hard to tell what could be wrong from pics with the light/seams at a different place on each pictures.  

What's your config / setup / JD value ? Bowden ? Direct drive ? Did you do the jerk to JD conversion correctly ? Did you try other values for JD ?  

I have pretty round circles on a bowden/cartesian setup with JD (0.12) / S-curve on, no LA, and :  
maximum resolution : 0.5  
max travel resolution : 0.8  
max deviation : 0.08  

print speeds from 40 to 60-65-ish, 0.1 to 0.3mm on a 0.4mm nozzle.

**Comment by qwewer0** [comment] 2020-03-14 14:41
Didn't thought that my confings too are needed, sorry.
[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/4332887/Marlin.zip)
- Direct drive
- LA = 0.17
- Acc = 500
- JD = 0.08 (0.4 * 10 * 10 / 500)
- I tried higher (18), lower (0.02) and in between a few
- Print speed = 50
- nozzle = 0.3 
- line width = 0.36

**Comment by ghost** [comment] 2020-03-14 14:58
Well, I'm not saying there is no bugs, but both you and OP has that issue with JD, so it's best to check / cross-check both of your configurations, make sure there's a legit need for marlin devs to dig deeper.  

Might be a bit of a blind shot, but did you try to use "a well known 3D printer model's config" regarding JD / accel ?  
Anet A8 examples config uses JD 0.10 and 400 accel, and it has a direct-drive and a wobbly frame, so I'd assume these values are "conservative".

**Comment by qwewer0** [comment] 2020-03-14 15:07
I "followed" the Ender 3 and BTT SKR Mini E3 v1.2 example files, and I made my own [guide](https://www.reddit.com/r/ender3/comments/e894j7/marlin_20x_guide_for_ender_3_using_skr_mini_e3_v12/).
I get a lot of questions day to day, so I rechecked my configs now a dozen-dozen times.

The annoying part is that, with Classic Jerk I get better result in that model (same gcode), and I can feel the steppers too, that they are not stutter when printing the curves.

**Comment by swilkens** [comment] 2020-03-14 18:38
A different avenue; are you printing from SD / Storage media or are you printing over the serial port? Perhaps we are seeing some automated slowdown due to buffer starvation.

**Comment by qwewer0** [comment] 2020-03-14 18:51
I print from SD card.
Don't know if it helps, but my baudrate is 115200 ([page 799](https://www.st.com/content/ccc/resource/technical/document/reference_manual/59/b9/ba/7f/11/af/43/d5/CD00171190.pdf/files/CD00171190.pdf/jcr:content/translations/en.CD00171190.pdf), 72Mhz)

**Comment by DaMadOne** [comment] 2020-03-15 17:06
I'm getting down to further testing today. I will use this post as a sort of scratch pad that I will update periodically with what I am trying and the results. 

First up today was to upgrade to 2.0.5. [HERE](https://github.com/MarlinFirmware/Marlin/files/4334621/Marlin_config.zip) are the config files as they sit right now. I cut out and am only using part of the middle of the tux model to speed up test prints. First print shows the stutter.  EDIT* I should have probably zipped up the right config files.... corrected.

Next test was to try printing the same gcode from SD since I've been using Octoprint. Stutter is still there so that should rule that out. Also before anyone asks I had octoprint disconnected when I printed this.

I've decided to try to slow things down to see if speed makes any difference. 
Test 1 was with Perimeters(P) at 60mm/s and External Perimeters(EP) at 50mm/s. I've had them set differently all of this time but I was printing with P@75 and EP@50. I'm intending to step down by 10mm/s for my tests so I wanted to get them closer together. This print has the stutter.  Getting ready to slice/print the next test.

P@50/EP@40 test is currently printing but already found something interesting. I'm printing 3 walls thick and when printing the 2 inner walls I can hear and see the extruder stuttering at 50mm/s. I have a knob on my extruder which makes it really easy to see. However, when it moves to printing the outer perimeter(40mm/s) the the audible and visual indicators from the extruder are gone or at least not noticeable. Comparing this print to the previous it definitely looks better. It's not as smooth as with JD disabled but I'm guessing that is due to the inner 2 perimeters still stuttering while printing.. so I guess my next test will be to print with both P&EP@40mm/s....

With both P&EP@40mm/s both the inner and outer perimeters sound and look to be printing smoothly. So what does this tell us? I don't know but I know that with CJ I can print at faster speeds so this doesn't really help me. Maybe this info helps one of the devs or gives someone an idea of something to tell me to try. 

@thinkyhead  mentioned to try setting the slicer to use minimum line segments. I can't find this setting or even anything that sounds like it to me in Cura or PrusaSlicer. Can you point me in the right direction? Preferably in PrusaSlicer because I don't really use Cura.

@Moyster mentioned [THIS](https://www.youtube.com/watch?v=Hvw3DrVAeTA) video. I checked it out and tried the Resolution setting in PrusaSlicer they mentioned and changing this at all (even to 0.1) makes even the preview look bad so i'm not bothering to try to print it. 
![Res_0 0](https://user-images.githubusercontent.com/5142171/76708803-15037400-66d0-11ea-9973-929474e21e18.jpg)
![Res_0 1](https://user-images.githubusercontent.com/5142171/76708805-1896fb00-66d0-11ea-8c52-9b4b998dd1bf.jpg)

Interesting... so I didn't try printing with resolution set to 0.5 since that looked really bad. However I decided to try 0.05. You can notice it in the print preview but not by much so I decided to try printing it with P@60mm/s and EP@50mms. So far printing OK. This doesn't really answer why the same gcode printed with JD enabled vs not shows serious differences. Or maybe JD is much more precise when compared to CJ and CJ was just hiding this issue? 

Well maybe not... The print finished and when compared to the Tux printed without JD the quality of the outer shell suffers with res set to 0.05. Trying again with 0.25... err.. wait.... nevermind. As I was typing it got to the point it's printing the circles and it's back to stuttering(just to be clear, by stuttering I mean it's obvious the extruder is moving back and forth really fast) so I guess I can hit cancel on that one.

Reading through comments on the video @Moyster posted and it's interesting to me that "W Boumans" also figured out he had to slow down to 40mm/s. The other poster mentioned it (messing with resolution) "solved it completely" but I can say from comparing them it does not.. only hides it at the cost of print quality.
![youtube](https://user-images.githubusercontent.com/5142171/76709936-5b110580-66d9-11ea-88e3-3adeb7f93d14.jpg)

Some more things I've tried that didn't help were.
1 - enable adaptive_step_smoothing
2 - Based on "#define DEFAULT_EJERK    5.0  // May be used by Linear Advance" I decided to try defining XY&ZJERK as well because why the hell not.. but it didn't help.  

Based on the 2nd one above with JD enabled it's not possible to tune EJERK from the menus or gcode anymore as far as I can tell. M503 does not show an M205 value for E (M205 B20000.00 S0.00 T0.00 J0.08) and it's not in the jerk menus on LCD. Or am I missing something? Is it even worth trying to mess with this value based on the issue I'm having? 

Things your probably can't tell by looking at my configs are that for the most part the mechanics of my E3Pro are pretty much stock. Bowden extruder(upgraded metal creality extruder), Capricorn Bowden tube as short as I could comfortably make it and a Micro-Swiss all metal hot end. I don't think any of that should have anything to do with my results but I've not listed that before. Based on  [tests](https://www.cnx-software.com/2019/09/05/how-to-easily-calibrate-retraction-in-3d-printers/amp/) I did I have retraction set to 2mm @ 25mm/s.

Attached is the gcode I've been printing today in case anyone wants to look at it. Plus all of the slicer settings are at the bottom if those are of any interest.
[linux_body_0.2mm_PLA_ENDER3_13m.zip](https://github.com/MarlinFirmware/Marlin/files/4335631/linux_body_0.2mm_PLA_ENDER3_13m.zip)

I'm out of ideas short of just sticking with classic jerk since I do like the benefits LA has given me when it comes to speeding up prints without definition loss. If anyone has any bright ideas for me to try or wants me to supply anymore info than I already have please let me know.

**Comment by DaMadOne** [comment] 2020-03-15 17:57
*moved this from my other comment*

Question for someone in the know. Kinda *thinking* out loud. Is the math for JD more/less/sameish to the math for CJ(classic jerk) when it comes to CPU usage? Wondering if it's possible to be hitting processing limits of the STM32's on these boards? Probably not? Since the stutter to me seems more like a ton of retracts than it does some processing problem. When the extruder is stuttering it doesn't seem like X/Y are also stuttering but maybe it's just harder to see and hear.

**Comment by qwewer0** [comment] 2020-03-17 16:15
Printed another [example](https://www.thingiverse.com/thing:3469190) piece, JD top, CJ bottom on each photo:
[Mine](https://imgur.com/a/YZoJJon)
[Helper's](https://imgur.com/sf9Lmhh)

**Comment by ghost** [comment] 2020-03-17 17:55
@DaMadOne : what thinkyhead was referring to (minimum segment length) is what the video I linked talks about.  
You should try a print with exaggerated resolution settings, see if at 50mm/s it still struggles, it could be a performance issue, or something wrong with "something something PWM pulse" when there's a lot of tiny segments.  

https://github.com/MarlinFirmware/Marlin/pull/17171  
This could maybe improve the situation ? Using a larger buffer size (64) and increasing slowdown factor to 4.

**Comment by ManuelMcLure** [comment] 2020-03-17 18:28
> Based on the 2nd one above with JD enabled it's not possible to tune EJERK from the menus or gcode anymore as far as I can tell. M503 does not show an M205 value for E (M205 B20000.00 S0.00 T0.00 J0.08) and it's not in the jerk menus on LCD. Or am I missing something? Is it even worth trying to mess with this value based on the issue I'm having?

This is correct - if you're using JD the extruder jerk is calculated according to the following formula:
```
#define GET_MAX_E_JERK(N) SQRT(SQRT(0.5) * junction_deviation_mm * (N) * RECIPROCAL(1.0 - SQRT(0.5)))
```
where ``N`` is the maximum acceleration on the extruder axis.

**Comment by qwewer0** [comment] 2020-03-17 18:39
@Moyster I changed `BLOCK_BUFFER_SIZE` to 64, and `SLOWDOWN_DIVISOR` to 4, but it [did not helped](https://imgur.com/a/KrMSd2Z).

I'm open to any ideas.

**Comment by psavva** [comment] 2020-03-17 19:19
I see you have Linear Advance, and working with Cura...  That will not work very well.  Reslice with Slicer using Lin advance, or alternatively, turn off linear advance and see if you can simulate the issue.  There is an incompatibility between Curas extrusions widths and Lin Advance...

**Comment by qwewer0** [comment] 2020-03-17 22:08
> There is an incompatibility between Curas extrusions widths and Lin Advance

Don't know how is that even makes sense, as I printed it with and without LA, and it was the same, but ok.
I resliced the [model](https://www.thingiverse.com/thing:1809605) with prusaslicer, and printed it with JD and CJ, and to my surprise the two came out the same. Both of it was better than the cura file with JD, but worse than the cura with CJ, but I think it is just my setting difference.
So, I don't know how or why, but it might be a problem only with cura and not with JD in general, and I hope others can test it too, to confirm/refute it.

**Comment by DaMadOne** [comment] 2020-03-18 01:34
> I see you have Linear Advance, and working with Cura... That will not work very well. Reslice with Slicer using Lin advance, or alternatively, turn off linear advance and see if you can simulate the issue. There is an incompatibility between Curas extrusions widths and Lin Advance...

This isn't remotely true. Is it true that Cura makes MANY assumptions? Yes it does. Does Cura break LA? then the answer is no. You can tell by reading the OP and checking out pics that I posted that the slicer doesn't matter. I can print a terribly calibrated Cura prints with LA and JD enabled and tell the difference. It's only slightly different from my better calibrated Prusa Slicer profile between JD enabled and not. It's easy enough to turn off most of Curas advanced features. 

It doesn't help to regurgitate the crap people read and hear from reddit.

**Comment by DaMadOne** [comment] 2020-03-18 01:50
On to block buffer size. I didn't mention it but things I tried didn't make a difference.

**Comment by DaMadOne** [comment] 2020-03-18 02:09
The more I dive down this rabbit hole of bug reports and Pull Requests the more I'm convinced this isn't an immediately solvable issue. LA just wasn't developed with bowden extruders in mind. So I can either jump to a direct drive system or disable LA. At this point I've decided to disable LA and dial in the parameters that I can.

**Comment by DaMadOne** [comment] 2020-03-18 02:15
@ManuelMcLure I'm a little inebriated right now but I'l check out the math tomorrow. Would be interesting to see what that ends up at. .. if it turns out that math ends up at a high jerk value that would be very telling i would think.

**Comment by psavva** [comment] 2020-03-18 04:03
> > I see you have Linear Advance, and working with Cura... That will not work very well. Reslice with Slicer using Lin advance, or alternatively, turn off linear advance and see if you can simulate the issue. There is an incompatibility between Curas extrusions widths and Lin Advance...
> 
> This isn't remotely true. Is it true that Cura makes MANY assumptions? Yes it does. Does Cura break LA? then the answer is no. You can tell by reading the OP and checking out pics that I posted that the slicer doesn't matter. I can print a terribly calibrated Cura prints with LA and JD enabled and tell the difference. It's only slightly different from my better calibrated Prusa Slicer profile between JD enabled and not. It's easy enough to turn off most of Curas advanced features.
> 
> It doesn't help to regurgitate the crap people read and hear from reddit.

Please have a look at the issue reported 3 years ago https://github.com/MarlinFirmware/Marlin/pull/5928#issuecomment-283113646

**Comment by qwewer0** [comment] 2020-03-18 07:22
> Please have a look at the issue reported 3 years ago [#5928 (comment)](https://github.com/MarlinFirmware/Marlin/pull/5928#issuecomment-283113646)

I read it through, and it is very interesting, but it doesn't explains why did I get the same bad JD result with or without LA enabled in the firmware. Is there some other advance marlin feature that is also incompatible with cura and needs to be turned off in order to test JD?

**Comment by psavva** [comment] 2020-03-18 07:41
Not that I'm aware of

**Comment by qwewer0** [comment] 2020-03-18 22:20
I sliced and printed [this model](https://www.thingiverse.com/thing:1809605)'s bottom 5mm with Cure, PrusaSlicer, and Fusion 360, and printed them with the latest bugfix, with JD and with CJ.
The results were as expected - at least for me - as all of it came out worse with JD than CJ.
It may not appear well in the [pictures](https://imgur.com/a/g8VUGbh), but in reality it can be seen well and can be feel its surface.
- The two Cura prints had the biggest difference, as the one with JD is the worse of all, but the one with CJ is the second best.
- PrusaSlicer is in between the two Cura prints, as the CJ is only helped just a little, but the JD one is still turned out worse.
- Fusion 360 with JD yielded a better result than the two PrusaSlicer print, but with CJ it become the best of all.

**Comment by qwewer0** [comment] 2020-03-19 10:44
I think this should be tested by others that don't have an SKR board, to know that this is or isn't a hardware issue.

**Comment by Seref** [comment] 2020-03-21 00:46
Hey there, I'm also using a SKR Mini E3 1.2 board and also got weird artifacts when enabling JD 
![image](https://user-images.githubusercontent.com/9627396/77215601-3243a280-6b15-11ea-8c83-c2e7629ae24a.png)

The lines are always wavy around curves, doesn't matter if I enable or disable linear advance it's always a bit wavy.
I don't get them when switching to classic jerk and enabling linear advance, which is weird.
(I got a custom printer, though it's similar to an Ender 3 and is also a Bowden style 3D Printer, and in the tests mentioned above S Curve Acceleration was also always on).

**Comment by qwewer0** [comment] 2020-03-21 13:50
If this is an issue specifically with the SKR Mini E3 v1.2 and maybe with other SKR boards too, then how can we make sure of it, then solve it?
I'm open to ideas.

**Comment by swilkens** [comment] 2020-03-21 17:45
> If this is an issue specifically with the SKR Mini E3 v1.2 and maybe with other SKR boards too, then how can we make sure of it, then solve it?
> I'm open to ideas.

Build back your original board, use the same firmware options and verify on the original board with the same gcode?

**Comment by qwewer0** [comment] 2020-03-21 18:13
> Build back your original board, use the same firmware options and verify on the original board with the same gcode?

I would have done that already, but I no longer have the original board.

**Comment by BarsMonster** [comment] 2020-03-22 22:24
Just want to leave a link to potentially relevant issue: #15473 

What I learned there is that JD with LA and optionally acceleration control in Cura makes an easily reproducible issue, but it is present even without LA/JD/acceleration control, though very rare (like once per 200 layers).

You can try to enable acceleration control in Cura (assign different accelerations for infill/perimeters/e.t.c) and see how prints will get completely wrecked. 

On the bright side, currently on SKR PRO 1.1 I see much less (if at all) of an issue. So the issue might be more reproducible on ~~slower~~  not so unnecessarily fast CPUs.

**Comment by CarlosGS** [comment] 2020-03-29 22:22
I think I'm having the same issue as @DaMadOne, tomorrow will try disabling Junction Deviation and see if those weird erratic arcs become smooth.

Marlin version: 2.0.5.2
Printer: Hephestos 2
Electronics: 8 bit
Junction deviation: enabled
Linear advance: disabled
S-curve: enabled

Follow-up: #17342

**Comment by thinkyhead** [comment] 2020-03-31 21:32
Duplicate of #17342

**Closed as completed by thinkyhead** 2020-03-31 21:32 UTC
Labels: C: Motion

**Comment by richfelker** [comment] 2020-03-31 22:04
Just saw this and the linked video:

> Could very well be, I guess OP should check how the layers are "drawn" in its slicer preview, additionally CNCKitchen has a video/semi-tutorial on youtube about this : https://www.youtube.com/watch?v=Hvw3DrVAeTA
> I found tweaking these settings gave me much smoother circles when openscad models were exported with a lot of definition ($fn >= 128)

Unfortunately this is not a solution. Even Cura's default max resolution/deviation settings are way too high to accurately reproduce fine detail, and due to numerical instability, they produce inconsistent results on consecutive layers, resulting in non-smooth surfaces. For fine detail, max deviation needs to be on the order of microstep size. There's a similar problem in Marlin firmware that compounds on top of this too, `MIN_STEPS_PER_SEGMENT`. See part of my answer at https://3dprinting.stackexchange.com/a/12075/11157 for details.

Any real viable solution of these problems needs to avoid depending on "make gigantic imprecise segments".

**Comment by thinkyhead** [comment] 2020-04-01 00:07
> they produce inconsistent results on consecutive layers

Well this really could be addressed by the slicer authors. I won't list all the potential approaches, but I can think of a few ways to mitigate this effect.

**Comment by thinkyhead** [comment] 2020-04-01 00:12
> Any real viable solution of these problems needs to avoid depending on "make gigantic imprecise segments".

The thing we're trying to look at here is the behavior of junction deviation in the presence of many small segments. In the other thread I was keen to state that we're not trying to solve the issue by this method, but to eliminate factors that could be contributing to the bad acceleration effects. I am asking testers to reduce the number of segments and give feedback so that we can see whether there is any effect and what that effect is. But the deeper investigation involves a lot of logging and doing lots of French curves and Fibonacci spirals.

**Comment by richfelker** [comment] 2020-04-01 14:02
Inconsistency between consecutive layers can be solved by slicers if they care, yes, but loss of detail can't. In any case I'm in full agreement that eliminating other factors (tiny segments) that could be involved with this JD bug is a good debugging technique. I just misunderstood the low-res slicing recommendation as a statement that high-res slicing is undesirable or unsupported in general.

**Comment by CarlosGS** [comment] 2020-04-01 14:05
To clarify, the stuttering appears for **some** arcs.
Even parallel ones, sometimes it stutters and sometimes its perfectly fluid.
So small segments can't be the only cause...

**Comment by thinkyhead** [comment] 2020-04-05 23:53
This is worth a read for anyone using 2208 and 2209… https://github.com/MarlinFirmware/Marlin/issues/11825#issuecomment-421809385

**Comment by BarsMonster** [comment] 2020-04-06 01:29
@thinkyhead I believe stealthchop issues are not relevant as it stops all extrusion permanently, while in this case it misses alot of steps. In my case TMC2209 was in SpreadCycle mode.

**Comment by qwewer0** [comment] 2020-04-06 08:38
> This is worth a read for anyone using 2208 and 2209… [#11825 (comment)](https://github.com/MarlinFirmware/Marlin/issues/11825#issuecomment-421809385)

@thinkyhead So, is it enough to just turn off StealthChop and try to print a sample with JD to test it? Because I did it and it didn't turn out any better, but was loud the whole time...

SKR Mini E3 v1.2, TMC 2209, latest bugfix.

**Comment by CarlosGS** [comment] 2020-04-06 09:38
@thinkyhead My drivers don't support [StealthChop](https://www.youtube.com/watch?v=FqWgTM4di4s) :) they are the DRV8825

**Comment by XDA-Bam** [comment] 2020-04-12 19:34
For anybody looking here, I've posted a [workaround ](https://github.com/MarlinFirmware/Marlin/issues/17342#issuecomment-612664924) in #17342 which solves the issue for me until the actual bug is fixed.

**Comment by BarsMonster** [comment] 2020-04-12 21:26
@XDA-Bam  I've tested MIN_STEPS values of 16 and 6 with JD on SKR PRO. I see hardly any differences in surface quality. MIN_STEPS 16 has slightly less "noise" on the surface, but still very far from JERK quality.

Jerk surface quality is better with all MIN_STEPS values (16, 6, 1).

![image](https://user-images.githubusercontent.com/4014665/79080399-2cf50480-7d1d-11ea-90eb-5cd308df131b.png)

**Comment by qwewer0** [comment] 2020-04-13 07:05
@BarsMonster Could you share your test file? I would like to test it too, on SKR Mini E3 v1.2.

**Comment by BarsMonster** [comment] 2020-04-13 09:40
@qwewer0 It's here:
It has very high resolution, and was sliced with "Maximum deviation" of 0.002 in Cura to intentionally produce very tiny segments in g-code. 

[Xtest-HR.zip](https://github.com/MarlinFirmware/Marlin/files/4468931/Xtest-HR.zip)

**Comment by swilkens** [comment] 2020-04-13 17:54
Apologies, didn't notice this was closed. Continuing here: https://github.com/MarlinFirmware/Marlin/issues/17342

---

Another dataset; I took the STL from @BarsMonster (https://github.com/MarlinFirmware/Marlin/issues/17146#issuecomment-612678251) and printed the same .GCODE file with JD (J=0.08) and CLASSIC_JERK. (X, Y JERK 10)

Results below. Both printed directly from SD card on SKR Mini E3 v1.2 running 2.0.5.3.

I honestly can't see a difference here. Both with `#define MIN_STEPS_PER_SEGMENT 6`

![Naamloos](https://user-images.githubusercontent.com/13329383/79145168-7e0a0480-7dc0-11ea-9f00-67e1c8810ab8.png)

**Comment by qwewer0** [comment] 2020-04-13 19:30
With @BarsMonster test file, I can't reproduce the the issue with JD. (SKR Mini E3 v1.2)

**Comment by BarsMonster** [comment] 2020-04-15 03:52
@swilkens @qwewer0 Do you have high resolution enabled in your slicer? You must have segments with length of ~0.1-0.5mm in the output to trigger the issue. With Cura you achieve that by setting Maximum Resolution ~0.2mm and maximum deviation of ~0.002mm (as an ultimate example). 

As we see in the code (https://github.com/MarlinFirmware/Marlin/issues/17342#issuecomment-613798026) , with segments of 1mm or longer - issue would not be reproduced.

**Comment by qwewer0** [comment] 2020-04-15 05:13
@BarsMonster In PrusaSlicer the "Slice gap closing radius" (Cracks smaller than 2x gap closing radius are being filled during the triangle mesh slicing) is set to 0.049, so maybe the max resolution would be 0.1.
But the JD_single_arc_test.gcode [works](https://github.com/MarlinFirmware/Marlin/issues/17342#issuecomment-613602582).
