### ISSUE TITLE
[BUG] TMC2130: axis won't move

### ISSUE THREAD

**Issue by zanvettor** [MarlinFirmware/Marlin#19435] opened 2020-09-18 14:50 UTC
### Bug Description

Hi! First time asking here, if Im doing something wrong, please let me know. 
My setup is SKR 1.3 with tmc2130 on X, Y and E + DRV8825 on Z1 and Z2. I had the same setup running until my board gave up and I got it replaced. Now I can't seem to get the 2130 to work. I checked the changes made in relation to the drivers a lot of times and still can't figure out what's wrong. 
I talked to BTT support and they manage to send me a firmware.bin file that made the axis move, so I know it's not a faulty board or stepper drivers. Unfortunatelly communicating with the support isn't easy due to language and very different time zones barriors. 

### My Configurations

**Required:** Please include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
[marlin.zip](https://github.com/MarlinFirmware/Marlin/files/5246122/marlin.zip)

### Steps to Reproduce

1. Compile Marlin with the given configuration files 
2. Send commands to move X, Y and E0

**Expected behavior:** The axis move accordingly 

**Actual behavior:** The motors don't turn nor stall

#### Additional Information

I changed the following in regard of tmc2130:
Configuration.h:  TMC2130 are set correctly on stepper drivers lines
Configuration_adv.h: 
#define TMC_USE_SW_SPI
#define SOFTWARE_DRIVER_ENABLE
#define MONITOR_DRIVER_STATUS
#define HYBRID_THRESHOLD
#define TMC_DEBUG

**Comment by thisiskeithb** [comment] 2020-09-18 15:02
Duplicate of https://github.com/MarlinFirmware/Marlin/issues/19434

**Closed as completed by thisiskeithb** 2020-09-18 15:02 UTC
