### ISSUE TITLE
[BUG] UBL - G29 P1 stops at point 57

### ISSUE THREAD

**Issue by gbkwiatt** [MarlinFirmware/Marlin#20343] opened 2020-12-01 18:13 UTC
I've seen same ticket, but closed and not resolved. 

I have SKR MINI E3 V2 board with bed size of 290x250

When I run on default UBL settings, printer HALTs on 57th point, and Mesh is invalid even after G29 P3.

 Current settings: `PROBING_MARGIN 10` and `MESH_INSET 1`.

I tried `PROBING_MARGIN 30` and `MESH_INSET 50` as as I have seen it as a solution. and it works fine.
I rather understand how to set it up to my bed.
How to calculate or set that so it probes as much bed as possible, I am struggling to understand it. 

Also at the end of G29 P1, nozzle goes to Z=0 in the middle of the bed which looks like it's touching the bed, pretty scary, is there a way to make it not to go to that position at the end of levelling?

**Comment by boelle** [comment] 2020-12-01 18:35
Configurations, please
Please ZIP up your `Configuration.h` and `Configuration_adv.h` files (as
requested in the Issue template) and drop them into your next reply.
We'll check them over and see if anything is amiss.

Please test the [`bugfix-2.0.x branch`](https://github.com/MarlinFirmware/Marlin/tree/bugfix-2.0.x) to see where it stands. If the problem has been resolved then we can close this issue. If the issue isn't resolved yet, then we should investigate further.

**Comment by gbkwiatt** [comment] 2020-12-01 18:40
[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/5624687/Marlin.zip)
Here is my configuration and I am using latest marlin bugfix-2.0.x branch

**Comment by ellensp** [comment] 2020-12-01 20:34
Whenever there are homing or leveling issues, we now ask everyone to follow a standard procedure to gather more information so that we're not just taking stabs in the dark. Here is the boilerplate:

- Download Marlin `bugfix-2.0.x` to test with the latest code.
- Enable `DEBUG_LEVELING_FEATURE` and `M114_DETAIL` and re-flash the firmware.
- Connect to your printer from host software such as Cura, Printrun or Repetier Host.
- Send `M502` and `M500` to ensure your Configurations are applied.
- Issue the command `M111 S247` to enable maximum logging.
- Perform a `G28` to do your standard homing procedure.
- Do a `G29` to probe the bed. This will also enable bed leveling.
- Do some of the moves that revealed problems before. Take notes.
- Copy the log output into a **.TXT file** and attach it to your next reply.

Repeat this procedure, if needed, to demonstrate inconsistencies. From these logs we should hopefully get a better idea of what's going on with your machine.

**Comment by gbkwiatt** [comment] 2020-12-01 20:43
I am not having an issue, just asking for advise on how to calculate parameters to set for UBL to probe as much bed as possible

**Comment by ellensp** [comment] 2020-12-01 21:00
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).

**Closed as completed by ellensp** 2020-12-01 21:00 UTC
