### ISSUE TITLE
Printer doesn't print with DUAL_X_CARRIAGE enabled

### ISSUE THREAD

**Issue by raguera** [MarlinFirmware/Marlin#7050] opened 2017-06-13 08:17 UTC
Dear Marlin Community,

I am trying to print with my 3D printer but it doesn't print after Repetier/Cura starts print.
After print command, printer makes X Y Z homing and warm hotends and bed up, but once temperature is reached, host software sends commands properly and it gets 'ok' response from firmware constantly but without moving any axis, so "supposedly" printing finishes in just few seconds, when it should take one hour.
It just happens if I enable DUAL_X_CARRIAGE, otherwise it prints well if it's disabled.

I'm using a Rumba board and Marlin version 1.1.3

Anyone knows what could happen?

Appreciate any help.

**Comment by oysteinkrog** [comment] 2017-06-13 15:55
Duplicate of issue https://github.com/MarlinFirmware/Marlin/issues/6956
I confirm this issue, works in 1.1.1
Pinging @thinkyhead as I think this is a pretty serious regression.

**Comment by raguera** [comment] 2017-06-13 17:40
You are right.
Thanks a lot!

**Comment by oysteinkrog** [comment] 2017-08-04 22:45
Hmm, for some reason my merged PR did not correctly close this, please close it now.

**Closed as completed** 2017-08-07 10:50 UTC
