### ISSUE TITLE
f4246dc Broke my Z axis

### ISSUE THREAD

**Issue by jimovonz** [MarlinFirmware/Marlin#7166] opened 2017-06-28 02:17 UTC
Downloaded the latest bugfix (after commit f4246dc) and my z axis homes OK but completely ignores G1 
commands (X & Y fine). Reverted to the previous days code and all is fine again (only preserved Configuration.h/Configuration_adv.h)

**Comment by tcm0116** [comment] 2017-06-28 03:24
I'm having the same issue. Glad it's not just me...

**Comment by tcm0116** [comment] 2017-06-28 03:38
Looks likes disabling **FASTER_GCODE_PARSER** in _Configuration_adv.h_ works as a temporary fix for this issue.

**Comment by Andrei-Pozolotin** [comment] 2017-06-28 18:12
same here

**Comment by Justinjhcs1** [comment] 2017-06-29 00:03
Mine is still broken so I went back to Sprinter No remote but at least it works.

**Comment by fiveangle** [comment] 2017-06-29 05:20
#7182 ?

**Comment by Tannoo** [comment] 2017-06-29 08:22
I'm not sure why, but it's not parsing Z correctly:
```
Got letter G at index 5 (has_num)
Set bit 7 of index 0 | param = 0x0006
Got letter Z at index 8 (has_num)
Command: G800 G0 Z10 (G800)
 args: "G "

Code 'G':
    float: 0.00
     long: 0
    ulong: 0
   millis: 0
   sec-ms: 0
      int: 0
   ushort: 0
     byte: 0
     bool: 0
   linear: 0.00
  celsius: 0.00
```

**Comment by Tannoo** [comment] 2017-06-29 09:11
I found in `gcode.h`, two changes gets Z working:
```
      const uint8_t ind = LETTER_OFF(c);
      if (ind > COUNT(param)) return;           // Only A-Z     ** CHANGED FROM ">=" to ">"
      SBI(codebits[PARAM_IND(ind)], PARAM_BIT(ind));        // parameter exists
      param[ind] = ptr ? ptr - command_ptr : 0;  // parameter offset or 0
      #if ENABLED(DEBUG_GCODE_PARSER)
        if (debug) {
          SERIAL_ECHOPAIR("Set bit ", (int)PARAM_BIT(ind));
          SERIAL_ECHOPAIR(" of index ", (int)PARAM_IND(ind));
          SERIAL_ECHOLNPAIR(" | param = ", hex_address((void*)param[ind]));
        }
      #endif
    }

    // Code seen bit was set. If not found, value_ptr is unchanged.
    // This allows "if (seen('A')||seen('B'))" to use the last-found value.
    // This is volatile because its side-effects are important
    static volatile bool seen(const char c) {
      const uint8_t ind = LETTER_OFF(c);
      if (ind > COUNT(param)) return false; // Only A-Z     ** CHANGED FROM ">=" to ">"
      const bool b = TEST(codebits[PARAM_IND(ind)], PARAM_BIT(ind));
      if (b) value_ptr = command_ptr + param[ind];
      return b;
    }
```

**Comment by Tannoo** [comment] 2017-06-29 09:33
See @Bob-the-Kuhn's response below...

**Comment by Tannoo** [comment] 2017-06-29 09:43
DEBUG now report the wrong letter..
```
Got letter G at index 5 (has_num)
Set bit 7 of index 0 | param = 0x0006
Got letter Z at index 8 (has_num)
Set bit 2 of index 3 | param = 0x0009
Command: G800 G1 Z10 (G800)
 args: "C Z "

Code 'C':
    float: 0.00
     long: 0
    ulong: 0
   millis: 0
   sec-ms: 0
      int: 0
   ushort: 0
     byte: 0
     bool: 0
   linear: 0.00
  celsius: 0.00

Code 'Z':
    float: 10.00
     long: 10
    ulong: 10
   millis: 10
   sec-ms: 10000
      int: 10
   ushort: 10
     byte: 10
     bool: 1
   linear: 10.00
  celsius: 10.00
```

**Comment by Tannoo** [comment] 2017-06-29 12:51
>Looks likes disabling `FASTER_GCODE_PARSER` in Configuration_adv.h works as a temporary fix for this issue.

Although, I had to do this also to get Repetier to work.

I can send `G1 Z10` and it work fine.. even through Repetier... But, I click the button in Repetier to do the same thing, nothing moves.

**Comment by Bob-the-Kuhn** [comment] 2017-06-29 13:25
@Tannoo  - see if changing only line 107 in gcode.h gets Z movement.
Is: `#define LETTER_OFF(N) ((N) - 'A' + 1)`
To: `#define LETTER_OFF(N) ((N) - 'A')`

I believe the root cause is the array **param** has indices 0-25 but LETTER_OFF(N) returns 1-26.

**Comment by Tannoo** [comment] 2017-06-29 13:41
That works, thank you.

**Comment by Tannoo** [comment] 2017-06-29 13:42
It now works as expected with and without `FASTER_GCODE_PARSER` and with or without Repetier.

**Comment by Tannoo** [comment] 2017-06-29 13:43
And the debug is okay again.. lol

**Comment by Bob-the-Kuhn** [comment] 2017-06-29 13:53
OK - I'll push a PR immediately.

**Comment by Bob-the-Kuhn** [comment] 2017-06-29 14:08
I've just merged PR #7183 to fix this.

**Comment by Andrei-Pozolotin** [comment] 2017-06-30 01:12
seems to work now

**Comment by boelle** [comment] 2019-02-19 20:25
@jimovonz does it also work for you now?

if so maybe consider closing the issue?

**Comment by boelle** [comment] 2019-03-06 10:38
@thinkyhead i think we can close this one

**Comment by boelle** [comment] 2019-03-16 16:12
I can't reproduce, G1 moves are OK

@Bob-the-Kuhn can you close it or has @thinkyhead  to do that?

**Closed as completed** 2019-03-17 01:30 UTC
Labels: S: Solved
