### ISSUE TITLE
MKS_LCD12864B and MKS_MINI_12864 Linking error on ESP32 (MKS Tinybee)

### ISSUE THREAD

**Issue by jesterhead82** [MarlinFirmware/Marlin#24021] opened 2022-04-10 22:05 UTC
Happens with todays (2022/04/10) 2.0X-Bugfix, does compile e.g. with 
`MKS_MINI_12864_V3`

but not with either 
```
#define MKS_LCD12864B    (<Triggers also MKS_MINI_12864) or
#define MKS_MINI_12864
```
Linking error:
```
.pio/build/mks_tinybee/src/src/lcd/dogm/u8g_dev_uc1701_mini12864_HAL.cpp.o:(.data.u8g_dev_uc1701_mini12864_HAL_2x_hw_spi+0x8): undefined reference to `u8g_eps_hw_spi_fn(_u8g_t*, unsigned char, unsigned char, void*)'
```
I dont know so much of this stuff, but:

ESP32 u8g_esp32_spi.cpp:
```cpp
#include "../../inc/MarlinConfigPre.h"

#if ENABLED(FYSETC_MINI_12864_2_1)    <--- is this correct?
#include <U8glib-HAL.h>
#include "Arduino.h"
```
_Originally posted by @jesterhead82 in https://github.com/MarlinFirmware/Marlin/issues/23776#issuecomment-1094376547_

**Comment by ellensp** [comment] 2022-04-11 02:18
MKS marlin fork has  (original source of the code) 
`#if ANY(MKS_MINI_12864, MKS_MINI_12864_V3)`

Marlin has 
`#if ENABLED(FYSETC_MINI_12864_2_1)`

As the MKS_MINI_12864_V3 has an  identical display the BTT_MINI_12864_V1 so both should work.  Ie
```
// MKS_MINI_12864_V3 and BTT_MINI_12864_V1 are identical to FYSETC_MINI_12864_2_1
#if EITHER(MKS_MINI_12864_V3, BTT_MINI_12864_V1)
  #define FYSETC_MINI_12864_2_1
#endif

```

So the code in marlin should be 

`#if ANY(MKS_MINI_12864, FYSETC_MINI_12864_2_1)`

**Comment by thisiskeithb** [comment] 2022-04-11 02:35
> So the code in marlin should be
> #if ANY(MKS_MINI_12864, FYSETC_MINI_12864_2_1)

The standard MKS Mini 12864 is very different than the newer “mini” 12864s and does not use neopixels as a backlight, so this will need some checking.

**Comment by thinkyhead** [comment] 2022-04-20 08:56
It compiles fine for me.

Please test the [`bugfix-2.0.x` branch](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.0.x.zip) to see where it stands. If the problem has been resolved then we can close this issue. If the issue isn't resolved yet, then we should investigate further.

**Comment by jesterhead82** [comment] 2022-04-20 10:38
Hello,

does only compile with todays bugfix for a MKS_MINI_12864 or MKS_LCD12864B if I apply proposed change from ellensp

So in

u8g_esp32_spi.cpp:

from 
#if ENABLED(FYSETC_MINI_12864_2_1)

to
#if ANY(MKS_MINI_12864, FYSETC_MINI_12864_2_1)

**Comment by thisiskeithb** [comment] 2022-04-21 18:43
The regular MKS Mini (V1 and V2) does not use neopixels, so grouping it with the V3 (FYSETC_MINI_12864_2_1 in our case) will enable options it doesn’t have.

**Comment by ellensp** [comment] 2022-04-23 03:27
@thisiskeithb this '#if ANY(MKS_MINI_12864, FYSETC_MINI_12864_2_1)' is a enable/disable for all code in  Marlin/src/HAL/ESP32/u8g_esp32_spi.cpp 

Ie the SPI communications side only.

It has nothing to do with if it has neopixels or not

**Comment by ellensp** [comment] 2022-04-23 04:00
Pr created.

**Closed as completed by ellensp** 2022-04-23 04:00 UTC
Labels: Bug: Confirmed !
