### ISSUE TITLE
Connect multi material unit to Marlin

### ISSUE THREAD

**Issue by FNeo31** [MarlinFirmware/Marlin#11879] opened 2018-09-20 00:35 UTC
Objective: 

Connect One Multi-Material unit to a printer with communication by Serial on pins Rx2Tx2 (MEGA + RAMPS 1.4 configuration)

What's needed:

- Make a Clone of all movements of extruder E0 to other motor (E1) same way that we can make with the Axis like Z and Z2. 
- Instead of Make some tool change, pick the T number and send it by Serial on format "T1." or "T2." or "T3." , Etc. To change the tool on multi material unit. 

- just continue the print after receive "OK." for example. 

I know, this isn't a trouble is an improve to new generations of printers with a lot of material with just one extruder noozle and with direct drive extruding with just one motor on head.

Can you help me?

If you are available to help me I'll post here all the hardware and the code of Multi Material Unit after test and check that os works well.

Best Regards

**Comment by thinkyhead** [comment] 2018-09-20 00:46
Duplicate of #11859

**Comment by thinkyhead** [comment] 2018-09-20 00:47
Please post your comment to the original issue. We don't want to keep repeating the same topics in multiple places.

**Closed as completed by thinkyhead** 2018-09-20 00:47 UTC
