### ISSUE TITLE
[FR] Support for M98..99 subprograms

### ISSUE THREAD

**Issue by fugalster** [MarlinFirmware/Marlin#23296] opened 2021-12-13 21:09 UTC
### Describe the feature you want

I need support for defining and calling subprograms. "Standard" gcode supports this via the M98 (call) and M99 (return) commands. The included image from [gcodetutor.com](https://gcodetutor.com/cnc-macro-programming/subprograms-m98-m99.html) represents the functionality well. Coordinate offsets (G53..59) are integral to making good use of subprograms, but those already exist in the Marlin firmware and are confirmed to be working properly (yay!).

![subprograms-m98-m99](https://user-images.githubusercontent.com/919051/145886126-13d7aab9-9ac6-4035-b565-9c365d2b55cb.jpg)

**Advantage #1**
In a production environment where many of the same part are being printed, it is useful to have the "main" program with header and footer code along with moving the nozzle to various points on the bed where parts should be printed and then calling the subprogram to perform the actual print. This will result in parts being printed "one-at-a-time" which is beneficial for production since print errors or cancelations only affect the active part instead of the entire partially complete bed. For example, if the filament runs out at 9 hours on a 10 hour print, one-at-a-time printing will result in 90% of the parts completed (+/- 1 part), vs all-at-once printing where 100% of the parts are only 90% complete and 0 are usable parts.

**Advantage #2**
The part of interest only has to be sliced once and stored in gcode once. While file size constraints are not what they used to be, having smaller gcode still carries some benefit. Notably, the "main" part of the program is short and compact and easily debugged, and the subprogram is the only incarnation of the part so any tweaks to the code only have to be made once.

**Advantage #3**
When it comes time to make an update to the gcode (new printer settings, print time optimizations, etc) the "main" part of the code can remain as is while replacing only the subroutine. This means the effort put into setting up the production job is carried over across design iterations, making the initial time investment that much more appealing.

In a previous life I was a CNC machinist and used M98..99 commands extensively. Not having this functionality in Marlin, especially when other firmware flavors do, is frustrating.

**Comment by thinkyhead** [comment] 2021-12-14 20:57
Duplicate of #16209

**Closed as completed by thinkyhead** 2021-12-14 20:57 UTC
Labels: T: Feature Request
