### ISSUE TITLE
[BUG] BigTreeTech SKR 1.4 Turbo + generic SSD1306 I²C 1.3" OLED : shifted display

### ISSUE THREAD

**Issue by yet-another-average-joe** [MarlinFirmware/Marlin#20289] opened 2020-11-26 18:33 UTC
### Bug Description

Brand new BTT MKS 1.4 Turbo with :
- 5x BTT TMC2209 drivers
- 2x generic NTCs
- a generic 1.3" I2C OLED (4-wire version)
- a generic click encoder
- a 12V brick for testing purpose
- vanila Marlin Bugfix (62680bb) (downloaded 2 days ago)

Test on the bench : no motors, just the drivers so marlin does not complain.

I2C pullups are on the board, and probably on the OLED (difficult to say without a microscope or the schematics, and for obvious reasons I don't want to test with an ohm-meter)

### Configuration Files

Display defineded as "OLED_PANEL_TINYBOY2" (for the encoder) 

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/5604497/Marlin.zip)

### Steps to Reproduce

Turn it ON, then wait from a few minutes to 15 minutes.

**Expected behavior:**

Informations being displayed properly, without reboots.

**Actual behavior:**

After a few minutes to 15 minutes, the text and graphics are shifted down by 8 pixels, and the bottom is displayed on top. 

I also experimented some crashes (reboots), but it is not reproductible. (and while I'm writing this, I got the first one after 1H05 !

Playing with menus makes no changes : display remains shifted. (in fact, it appears rolled)

![DSC_7822](https://user-images.githubusercontent.com/43514870/100383278-89433500-301d-11eb-9903-0e4a626f15b9.JPG)

#### Additional Information

As is, such a setup is not usable.

It seems to be a known issue, but very few are using such displays...
I also have similar issues with a generic 0.96" SSD1306 OLED (also shifted to the right). Found a fix for the horizontal shift, but not for the vertical one (tinkering with u8glib). Crashes (reboots) every 5mn or so.
These displays are good : played a lot with them, but using u8g2. They are 100% supported with u8glib2, not really with u8glib, and chances are they will never be as Marlin relies on u8glib, and u8glib support ended years ago.
Soon, I will test a third display : generic 1.54" SSD1306 OLED.

BTW, if there is no solution to this problem, are there some tiny known good SPI OLED displays (1.3 to 1.5") ? Are I²C OLEDs doomed ?

[EDIT] Forgot to say... 
For the OLEDs not to be horizontally shifted, in u8g_dev_ssd1306_128x64.c , u8g_dev_ssd1306_128x64_data_start[] has to be initialized like so (see values for lower 4 bits of the column address, 4th value) :

for the 0.96" one :

```
static const uint8_t u8g_dev_ssd1306_128x64_data_start[] PROGMEM = {
  U8G_ESC_ADR(0),           /* instruction mode */
  U8G_ESC_CS(1),             /* enable chip */
  0x010,    /* set upper 4 bit of the col adr to 0 */
  0x000,    /* set lower 4 bit of the col adr to 0  */
  U8G_ESC_END                /* end of sequence */
};
```
and for the 1.30" one :

```
static const uint8_t u8g_dev_ssd1306_128x64_data_start[] PROGMEM = {
  U8G_ESC_ADR(0),           /* instruction mode */
  U8G_ESC_CS(1),             /* enable chip */
  0x010,    /* set upper 4 bit of the col adr to 0 */
  0x002,    /* set lower 4 bit of the col adr to 0  */
  U8G_ESC_END                /* end of sequence */
};
```
This is weird...

See here for more information : https://github.com/olikraus/u8glib/issues/457

**Comment by rhapsodyv** [comment] 2020-11-27 18:35
I will close this, as it seems to be duplicated of #14431.

Thanks!

**Closed as completed by rhapsodyv** 2020-11-27 18:35 UTC

**Comment by sjasonsmith** [comment] 2020-11-28 19:08
Duplicate of #14431
