### ISSUE TITLE
[1.1.9] E stepper louder / grinding

### ISSUE THREAD

**Issue by Kazza2003** [MarlinFirmware/Marlin#11459] opened 2018-08-05 06:47 UTC
### Description

I recently updated my printer setup (Hypercube Evolution - Core X/Y, powered by a RAMPS 1.6 + DRV8825) to 1.1.9. I copied all the settings from my old 1.1.8 config and config_adv over and adjusted them for 1.1.9. Now I have the problem that the extruder (e3d Titan) makes loud noises if it retracts (grinding noise). I did not change anything at the hardware prior or after the firmware update to 1.1.9. Can it be that marlin 1.1.9 handles or calculates retraction different?

### Steps to Reproduce

1. [First Step]
Upload Marlin 1.1.9 and copy all existing settings from your old config/condig_adv
2. [Second Step]
Flash and test print

**Expected behavior:** 
A hearable but still silent retraction sound (fast moving gears).

**Actual behavior:**
A loud, grinding noise like it is overreacting.

#### Additional Information

Zip of my configs is attached.

**Comment by gloomyandy** [comment] 2018-08-05 17:09
There does not seem to be any file attached. Do you have the type of stepper configured correctly (this is a new config in 1.1.9) search for X_DRIVER_TYPE in configuration.h, you need to set this to whatever drivers you have (DRV8825?).

**Comment by Kazza2003** [comment] 2018-08-05 20:33
Yes, I already set them up for all my motors. They are properly set to DV8825. That is what confuses me.

**Comment by gloomyandy** [comment] 2018-08-06 07:00
I think if you want further help you need to upload your configuration files so folks can check to see if there is anything odd in there. Also did you enable any of the new 1.1.9 features (like S curve acceleration or junction deviation)? You may also want to try slowing your extruder acceleration/jerk and retract speeds as 1.1.9 probably implements them more accurately and your old values may not work so well.

**Comment by Kazza2003** [comment] 2018-08-06 14:01
I did attach them in a .rar file because the page didn't want to accept my config files in raw form. But I can add it again.

**Comment by Kazza2003** [comment] 2018-08-06 14:02
[Config.zip](https://github.com/MarlinFirmware/Marlin/files/2262832/Config.zip)

**Comment by ismaweb** [comment] 2018-08-12 10:48
Same problem here, with DRV8825 also
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/2280896/Configuration.zip)
My problem is with X/Y axis while extruding, not when traveling.

**Comment by ismaweb** [comment] 2018-08-12 10:56
Video showing the noise and the extruder assembly vibrating because the X axis:
[rattling.mp4.zip](https://github.com/MarlinFirmware/Marlin/files/2280901/rattling.mp4.zip)

**Comment by Kazza2003** [comment] 2018-08-12 12:09
Interesting. X and Y are super silent (relatively silent for a DRV8825) since 1.1.9 but the extruder is totally out of his mind.

**Comment by Kazza2003** [comment] 2018-08-12 12:11
Gonna check your config for a second ismaweb and see if there are any differences in ours. Maybe we can find the cause ^^.

**Comment by Kazza2003** [comment] 2018-08-12 12:35
For starters you did not assign the DRV8825 to your extruder. So no wonder it might not work properly. Also doesn't have your Printer 2 Z motors, moved by 2 different Z Stepper Motors?

**Comment by lrpirlet** [comment] 2018-08-12 16:21
In both ```configuration.h``` and ```configuration_adv.h``` search for 8825...

@Kazza2003 and @ismaweb in configuration.h, do define E0 as drv8825

@Kazza2003 in configuration_adv.h, do uncomment (remove the // ) to enable the define to take effect… I guess you changed it for DRV8825 but did not remove the //… You want to read

```C++
#define MINIMUM_STEPPER_DIR_DELAY 650
#define MINIMUM_STEPPER_PULSE 2
#define MAXIMUM_STEPPER_RATE 250000
```
instead of
```C++
//#define MINIMUM_STEPPER_DIR_DELAY 650
//#define MINIMUM_STEPPER_PULSE 2
//#define MAXIMUM_STEPPER_RATE 250000
```

**Comment by ismaweb** [comment] 2018-08-12 16:35
@Kazza2003 My board is a GT2560 which has a single controller to drive two tween Z motors.

@lrpirlet I have DRV8825 for XYZ and A4988 for E0, I think my Configuration.h is correct. Isn't it?

I´ve just swaped (the phisical controllers) X, Y and Z DRV8825 to A4988 and cofigured properly in Configuration.h:
Exact same behavior, smooth travels, and "teletype" noise while extruding.

**Comment by ismaweb** [comment] 2018-08-12 17:56
After few hours I managed to get It work smoothly:
My software, in some circumstances, not allways, was recording a 0 acceleration on the eeprom
(gcode M204 P0)
If I manually send a M204 P400, it runs like a charm.

So, @Kazza2003 check your eeprom values trough manual gcode M501 and look for weird values

**Comment by DKDarkness** [comment] 2018-08-12 18:51
I am having the same issues with retract/prime on my cartesian style printer and DRV8825 and titan extruder. Normal extrudes work fine, but when retracting/priming after retract it just makes a grinding noise and does not retract/prime. Changing between DRV8825 and A4988 setting in configuration.h does no difference. Disabling S acceleration or setting M204 P400 manually makes no difference.

**Comment by Kazza2003** [comment] 2018-08-12 19:00
@lrpirlet gonna try that first now with a test print.

@lrpirlet Did as you said. But no change to the retraction sound or the retraction problems. He still moves the hob, but for some reason doesn't move the filament. I already checked my values in M501 but with no luck.

**Comment by ismaweb** [comment] 2018-08-13 18:26
@Kazza2003, sorry, look at the output from the M503 comand which are the actual used values, M501 are the eeprom ones wich are superceded with M503 at execution time:
Find the M203 values, E value is your max extruder speed (retract also)
Then find the M204 values, R is retract acceleration.

**Comment by Kazza2003** [comment] 2018-08-13 19:11
M201 X2000 Y2000 Z100 E1000
M204 P1000.00 R1000.00 T1000.00

 I think you mistyped @ismaweb. It is M201 you wanted to know or?

**Comment by ismaweb** [comment] 2018-08-13 19:28
@Kazza2003, I want M203 (Maximum feedrates). I'm suspecting that you have a massive speed/acceleration configured that makes a step loss on retractions.

Other thing you can look at:
Have you tuned the amperage in the driver (the tiny pot)? 
Too low => loosing steps => noise
Too high => noise

**Comment by Kazza2003** [comment] 2018-08-13 20:23
@ismaweb M203 X300.00 Y300.00 Z5.00 E25.00

**Comment by ismaweb** [comment] 2018-08-13 21:50
Ok @Kazza2003, everything looks normal

**Comment by Kazza2003** [comment] 2018-08-14 18:21
@ismaweb I already pushed the vref a bit higher by 0.10. This is the maximum I can go. Else it gets too hot.

**Comment by mgaller** [comment] 2018-08-19 10:34
I have the exact same problem on my Tevo Tornado with TMC2130 on X,Y,Z and LV8729 on E0.
Worked fine with 1.1.8 before, tried several things, nothing worked.

**Comment by gloomyandy** [comment] 2018-08-19 10:44
@mgaller  can you upload your configuration files and give details of what you have tried so far.

**Comment by mgaller** [comment] 2018-08-19 12:30
The LV8729 is running in 1/32 mode with 0.9 Volt vref.
The extruder is not moving at all, just a weird noise.

[Marlin-1.1.x.zip](https://github.com/MarlinFirmware/Marlin/files/2300297/Marlin-1.1.x.zip)
So what I tried so far:
- changed MINIMUM_STEPPER_DIR_DELAY and the other two vaues for LV8729
- disabled TMC2130

In the Tevo Tornado facebook group I found a Marlin 1.1.9 with TMC2130 and LV8729.
Uploaded it, now the extruder is moving but still some noise.
Then I noticed that the steps were half my steps, so I changed the jumpers to 1/16.
Then, it was the same like before, weird noise no movement.
 I upped the vref for the LV8729 to 1.1V. Then I got movement again, but still weird noise.
Changed back to 1/32 and used again the doubled steps, only weird noise.
Tried now for like 4 hours, I give up now.
I think something is messed up with the driver control.

**Comment by mgaller** [comment] 2018-08-19 21:59
So I played a little more around, the problem seems related to MAXIMUM_STEPPER_RATE.
I if set it to 130000 "Maximum for LV8729 stepper driver" it is not working.
But I if lower it to 15000 then the extruder is working fine.
Still using LV8729 1/32 with 0.99V

**Comment by thinkyhead** [comment] 2018-08-21 13:43
@ejtagle — What do you make of this? ☝️

**Comment by ejtagle** [comment] 2018-08-22 06:33
DRV8825 requires to increase a bit the pulse width (i still have to port the timing fixes for that!) ... The retract issue is probably caused by Linear advance that does not perfectly respect maximum speed.. This is something that is very hard to fix (LA requires to fast-forward movements in order to "advance" pressure...

**Comment by DKDarkness** [comment] 2018-09-01 08:30
Tried changing the maximum feedrates with no effect. Ended up lowering the retraction speed to 20mm/s in cura 3.4.1, which seems to be about the maximum it can do. Running DRV8825@28v, 0.7A on E3D pancake stepper (0.9 degree) and Titan extruder with 3:1 ratio. Marlin 1.1.9.

**Comment by thinkyhead** [comment] 2018-09-05 11:39
Halving the number of micro-steps for E may help.

**Comment by DavidWAbrahams** [comment] 2018-10-17 05:10
I had issues similar to this after enabling linear advance in marlin 1.1.9 - extruder would skip steps a few times per model. Applying the patch from pull/11759 resolved the issue.
https://github.com/MarlinFirmware/Marlin/pull/11759

**Comment by boelle** [comment] 2019-02-20 15:36
@Kazza2003 is this still an issue when using latest bugfix 2.0?

**Comment by boelle** [comment] 2019-03-13 21:09
@thinkyhead think we can close this one

**Closed as completed** 2019-03-14 00:13 UTC
Labels: T: Question, C: Configuration

**Comment by subtyper** [comment] 2019-05-12 13:33
Hey guys,

I have just updated my marlin firmware to 1.1.9 and added a bltouch configured using teaching techs YouTube video am also using octoprint on a raspberry pi 3b+ my issue is when I move the z stepper either up or down from menu it just moves the stepper down and also the motor sounds like a teletyper really loud. Anything possible I could do to fix this
