### ISSUE TITLE
arbitrary reset the printer when printing more than 1 hour

### ISSUE THREAD

**Issue by AnatoliyKube** [MarlinFirmware/Marlin#3054] opened 2016-02-28 23:20 UTC
Printing from SD card, not connected to PC.
If printing takes longer than 50 minutes, printer stops and resets.
If you set the bed and nozzle temperature with the LCD (to warm up before printing) Several times printer reset occurs.

**Comment by AnatoliyKube** [comment] 2016-02-29 14:05
guys, check the firmware printersbrasuetsya 52-59 minutes and when printing, but the item is designed for 2 hours

**Comment by AnatoliyKube** [comment] 2016-02-29 14:09
He returned to the firmware   https://github.com/ErikZalm/Marlin - no such problems
all the RC version has a problem

**Comment by brainscan** [comment] 2016-02-29 14:19
Sorry but I can't make any sense of that. None.

**Comment by AnatoliyKube** [comment] 2016-02-29 14:32
all versions of RC has a problem
The printer prints 52-59 minutes , after - STOPS END RESETS
(version 1.1.0-rc3 ) , very unstable work, reset occur spontaneously ,

**Comment by jbrazio** [comment] 2016-02-29 14:43
Let me try to make sense of the comments..
1) Your printer resets itself when printing after 50m into the job
2) If you set pre-heat for nozzle and bed somethings it resets itself
3) This only occurs with Marlin RC version(s)

I have a couple of questions..
1) What is your hotend heater cartridge power ?
2) What is your hotbed power ?
3) What is your PSU power ?

I have the feeling you may be running close to the PSU power ratting..

**Comment by brainscan** [comment] 2016-02-29 15:02
I use rc3 and have never had this problem. Can you give more idea about your particular set up as it may be unique to you.

**Comment by AnatoliyKube** [comment] 2016-02-29 16:46
I have two printers
Power Supplies 12.3v 20 A (peak 30 А ), 5V 1 A ,specialized,stabilized voltage, air blower(fen)
bed - 1.8 OM - 6,8 A (peak)
extruder heater 4 om - 3 A
engines - 1,2 А *4 =5A
15 A peak
arduino tnd lcd -separately 5V
on the firmware version https://github.com/ErikZalm/Marlin~~pobj  -There are 10 hours a day - everything is fine
on the firmware version RC 1.1.0 - RC3 -malfunction even without heating (periodically),
printing 50-60 minutes-simply reset the printer

**Comment by jbrazio** [comment] 2016-02-29 16:54
Do you see any messages in the serial console prior to the board reset ?

**Comment by AnatoliyKube** [comment] 2016-02-29 17:10
the printer is not connected to PC , in LCD - ready , x ---- y--- z---

**Comment by AnatoliyKube** [comment] 2016-02-29 17:12
again I remind -on the firmware version https://github.com/ErikZalm/Marlin~~pobj -everything is fine

**Comment by jbrazio** [comment] 2016-02-29 17:25
Could you connect the printer to the PC just to have the debug log available ? You should still start the print job using the LCD/SD card but having a serial terminal open from the PC to store the log file.
The error you're having could be related with #2963 as @thinkyhead pointed out, the latest RC branch there are some changes related with thermal stuff.

Let's have the logs first.

**Comment by AnatoliyKube** [comment] 2016-02-29 19:28
1 -3 miin  start - error: Heating failed ,system stopped heatr id  :0

**Comment by AnatoliyKube** [comment] 2016-02-29 20:57
2 - Print time: 1 hour 06 minutes - - error: Heating failed ,system stopped heatr id :0

**Comment by Blue-Marlin** [comment] 2016-02-29 21:54
Relax

``````
  /**
   * Whenever an M104 or M109 increases the target temperature the firmware will wait for the
   * WATCH_TEMP_PERIOD to expire, and if the temperature hasn't increased by WATCH_TEMP_INCREASE
   * degrees, the machine is halted, requiring a hard reset. This test restarts with any M104/M109,
   * but only if the current temperature is far enough below the target for a reliable test.
   */
  #define WATCH_TEMP_PERIOD 30                // Seconds
  #define WATCH_TEMP_INCREASE 4               // Degrees Celsius```
``````

**Comment by Blue-Marlin** [comment] 2016-02-29 21:59
Maybe it's a good idea to protect your nozzle from the fans.
Is the printer printing a bridge right before the failure?

**Comment by AnatoliyKube** [comment] 2016-03-01 10:04
WHERE TO FIND THIS CODE ?

``` cpp
  #define WATCH_TEMP_PERIOD 30 // Секунды
  #define WATCH_TEMP_INCREASE 4 // Градусы Celsius
```

**Comment by jbrazio** [comment] 2016-03-01 10:57
`Configuration_adv.h`

**Comment by thinkyhead** [comment] 2016-03-02 10:49
> WHERE TO FIND THIS CODE ?

We have a [search box](https://github.com/MarlinFirmware/Marlin/search?q=WATCH_TEMP_PERIOD&type=Code) at the [top](#top) of this page! :grinning:

**Comment by thinkyhead** [comment] 2016-03-02 10:56
@AnatoliyKube Have you tested yet with `RCBugFix`? We've made a lot of patches since `RC3`, some of which may have an effect on your issue.

**Comment by AnatoliyKube** [comment] 2016-03-02 17:07
If you have changed RCBugFix for the last 48 hours - NO
Today again there was a failure (full stop) when printing on 42 minutes, the item is flawed

question is not on- when driving range (radius of less than 5 mm) pull is enough going on, the camera goes in spurts

**Comment by thinkyhead** [comment] 2016-03-03 07:29
> If you have changed RCBugFix for the last 48 hours - NO

Excellent. This will help narrow it.

> question is not on- when driving range (radius of less than 5 mm) pull is enough going on, the camera goes in spurts

This makes little sense. You should simply post in your native language and we will translate it ourselves.

In the meantime, through some careful questioning and experimentation we should be able to track down the problem.
- First question: Have you run the `M303` tuning procedure to calibrate your nozzle heater?
- Have you checked your thermistor to make sure it's reading the correct temperature? That's actually quite simple. When the printer is first turned on, the temperature should match room temperature.

**Comment by AnatoliyKube** [comment] 2016-03-03 11:02
The thermistor operates normally (previously installed firmware
https://github.com/ErikZalm/Marlin~~pobj  -всё worked without any issues)
м303 e0 s230 c8 - I checked, but each time it gave different values (11
+-20%, 0,56 +-20% 54+-20%)
while those that are installed by default ( 22 ........ ) , the difference in the work is not
had seen,
when heated ( 240 g ), the temperature goes up to 230 and increases smoothly , не
больше 242 гр но в низ 235, хотя при печати колебания температуры 238-241 гр
 произвольный сброс может возникнуть в любое время - нагрев принтера ,
простой принтера ,печать , в начале я это заметил при печати детали (время
более 1 часа ) - 50-59 минут , принтер просто сбрасывался  (состояние как
при включении) естественно деталь  пришлось выкинуть , потом я это заметил
при нагревании экструдера и стола - это происходило не однократно ,
блок питания 12,3 V  20A  (30A в пике  ) , 5 v 1 A , с воздушным
охлаждением , ещё раз напоминаю что на прошивке
https://github.com/ErikZalm/Marlin~~pobj  -всё работало без проблем , с
таким блоком питания (есть второй принтер )

2016-03-03 9:29 GMT+02:00 Scott Lahteine notifications@github.com:

**Comment by AnatoliyKube** [comment] 2016-03-03 12:10
сейчас заменю блок питания 12 V29,9A с вентилятором

**Comment by jbrazio** [comment] 2016-03-03 12:17
Anyone knows Russian ?

**Comment by AnatoliyKube** [comment] 2016-03-04 12:10
replaced by a more powerful power supply
printed 2 days
print time of 1.2 hours on the item
Today, when you print the item (1.5 hours) for 5 minutes full stop, not pninter riagiruet on the encoder, the inscription on LСD: THEREMAL  RUNAVAY

**Comment by Blue-Marlin** [comment] 2016-03-04 12:26
Against THEREMAL RUNAVAY tune

```
/**
 * Thermal Protection parameters
 */
#if ENABLED(THERMAL_PROTECTION_HOTENDS)
  #define THERMAL_PROTECTION_PERIOD 40        // Seconds
  #define THERMAL_PROTECTION_HYSTERESIS 4     // Degrees Celsius
```

```
/**
 * Thermal Runaway Protection protects your printer from damage and fire if a
 * thermistor falls out or temperature sensors fail in any way.
 *
 * The issue: If a thermistor falls out or a temperature sensor fails,
 * Marlin can no longer sense the actual temperature. Since a disconnected
 * thermistor reads as a low temperature, the firmware will keep the heater on.
 *
 * The solution: Once the temperature reaches the target, start observing.
 * If the temperature stays too far below the target (hysteresis) for too long,
 * the firmware will halt as a safety precaution.
 */

#define THERMAL_PROTECTION_HOTENDS // Enable thermal protection for all extruders
#define THERMAL_PROTECTION_BED     // Enable thermal protection for the heated bed
```

**Comment by AnatoliyKube** [comment] 2016-03-04 13:03
Yes, in my firmware so exposed 
/**
- Thermal Protection parameters
  */
  #if ENABLED(THERMAL_PROTECTION_HOTENDS)
  #define THERMAL_PROTECTION_PERIOD 40        // Seconds
  #define THERMAL_PROTECTION_HYSTERESIS 4     // Degrees Celsius

and
#define THERMAL_PROTECTION_HOTENDS // Enable thermal protection for all extruders
#define THERMAL_PROTECTION_BED     // Enable thermal protection for the heated bed
also

**Comment by AnatoliyKube** [comment] 2016-03-04 14:03
Again there was such a failure, the item has not been published, the temperature was normal 240gr and 95gr
do something
firmware has errors
once again I remind you that in (https://github.com/ErikZalm/Marlin~~pobj )  there is no such error

**Comment by Blue-Marlin** [comment] 2016-03-04 14:10
I remind you that relaxe/tune means
a. to change the values, 
b. flash the firmware again, 
c. test
d. begin with a. again, until it works.

If you can't make it work that way, you can deactivate THERMAL_PROTECTION_HOTENDS on your own risk.

**Comment by AnatoliyKube** [comment] 2016-03-04 14:13
так я же написал что выставил свё и перешил !!! и опять отказ

**Comment by AnatoliyKube** [comment] 2016-03-04 14:13
so I wrote it and put his alter !!! and failure again

**Comment by Blue-Marlin** [comment] 2016-03-04 14:19
Every system is different.
Do not take the default values. You have to **find** values suitable for your system

**Comment by AnatoliyKube** [comment] 2016-03-04 15:10
but how can I know which option to change? for this it is necessary to learn the ropes algorithm, and have a detailed description of each function in your code, and this appeal to you. Yes ,RC firmware better, but so many nuances in it, for the simple people gathered mechanics and electronics, to deal with the firmware without a sensible description is very difficult,
I want to note:
better graphics on LSD
layers are applied evenly
improved parking
but
circular movements became jerky , 
greater slowdown in the movement , 
and this is only the first impression

What about parking -nuzhno leave for the team g28 only parking at 0 and add a new command (control LSD) -Search 0 s in the center of the table and poluchaetsya that if I turn ENABLE_AUTO_BED_LEVELING, the SLIC3R  takes for 0 wheelbarrow exposed to define Z_SAFE_HOMING_X_POINT ( X_MAX_LENGTH / 2)
#define Z_SAFE_HOMING_Y_POINT (Y_MAX_LENGTH / 2)
 here extruder should come to a point 0 on all osyat ,

**Comment by AnatoliyKube** [comment] 2016-03-04 15:11
osyat- axes

**Comment by CONSULitAS** [comment] 2016-03-04 15:11
@Blue-Marlin i think you build to complex sentences, he does not understand you by google translate. Let me try a different way...

@AnatoliyKube 

"Thermal runaway" is for safety. It protects your machine from fire. It is needed if hotend or heatbed are damaged.

default ist too hard for your machine:

```
  #define THERMAL_PROTECTION_PERIOD 40        // Seconds
  #define THERMAL_PROTECTION_HYSTERESIS 4     // Degrees Celsius
```

try:

```
  #define THERMAL_PROTECTION_PERIOD 40        // Seconds
  #define THERMAL_PROTECTION_HYSTERESIS 6     // Degrees Celsius
```

then try:

```
  #define THERMAL_PROTECTION_PERIOD 60        // Seconds
  #define THERMAL_PROTECTION_HYSTERESIS 6     // Degrees Celsius
```

then try:

```
  #define THERMAL_PROTECTION_PERIOD 60        // Seconds
  #define THERMAL_PROTECTION_HYSTERESIS 8     // Degrees Celsius
```

use first good parameters

Bigger values are less safe.
Lower values are safer.

**Comment by CONSULitAS** [comment] 2016-03-04 15:13
@AnHardt 
Hat er einen Delta, wenn er über Performance-Probleme schreibt?

**Comment by AnatoliyKube** [comment] 2016-03-04 15:16
I understood , 
question
in firmware https://github.com/ErikZalm/Marlin~~pobj  no such function ( keine solche Funktion )?

**Comment by CONSULitAS** [comment] 2016-03-04 16:26
@AnatoliyKube 
Great!
Answer: Correct. Because it is rather new function.

Fork of ErikZalm is to old. Made more than one year ago.

**Comment by AnatoliyKube** [comment] 2016-03-04 16:45
so ,
gibt es eine falsche Entscheidung in dem Algorithmus
nichts für ungut
Neue Lösungen müssen überprüft werden
wenn ich als Designer gearbeitet (Elektronik),Wir luden eine Frau,zum Test.zhenshina weiß nicht, wie das Gerät zu benutzen
sie war auf der Suche nach Fehlern, und wir fixieren

**Comment by AnatoliyKube** [comment] 2016-03-04 16:48
so ,
gibt es eine falsche Entscheidung in dem Algorithmus
nichts für ungut
Neue Lösungen müssen überprüft werden
wenn ich als Designer gearbeitet (Elektronik),Wir luden eine Frau,zum Test. zhenshina weiß nicht, wie das Gerät zu benutzen
sie war auf der Suche nach Fehlern, und wir fixieren

so wird es die richtige Übersetzung sein

**Comment by CONSULitAS** [comment] 2016-03-04 16:54
@AnatoliyKube 
Please translate to english, because the others can follow you.
If you speak german, you are welcome, because it is my native language. But don't use a automatic russian to german translator.

No wrong decision in the algorithm!
The algorithm has to be tuned for every model. Because the physics is different. So you need different parameters.

When you tune it for example for a K8200 it is good for every user with this machine. But we don't have your machine to test.

**Comment by AnatoliyKube** [comment] 2016-03-04 17:14
I have a standard printer - ARDUINO 2650, RAMP 1.4,E3d v6 1.75mm  (I made it myself), there is no difference

**Comment by AnatoliyKube** [comment] 2016-03-04 17:15
CORE XY

**Comment by CONSULitAS** [comment] 2016-03-04 18:03
@AnatoliyKube 
If your problem is solved, please close this issue. Thanks and good luck!

**Comment by AnatoliyKube** [comment] 2016-03-05 11:28
how do you know - what causes the printer to stop -EXTRUDER or bed

**Comment by AnatoliyKube** [comment] 2016-03-05 11:31
by what principle works fire protection

**Comment by Blue-Marlin** [comment] 2016-03-05 11:44
> how do you know - what causes the printer to stop -EXTRUDER or bed

Look at the log

```
12:33:47.892 : Error:Heating failed, system stopped! Heater_ID: 0
12:33:47.893 : Error:Printer halted. kill() called!
```

Heater_ID is ether the extruder id number or "bed".

> by what principle works fire protection

a. read the descriptions.
b. read the source.

**Comment by AnatoliyKube** [comment] 2016-03-05 12:02
I read
I understood-
the system makes a decision - error , 
by condition :(temperature.cpp (638))

``` cpp
 if (degHotend(e) < watch_target_temp[e]) {
          // Stop!
          _temp_error(e, PSTR(MSG_T_HEATING_FAILED), PSTR(MSG_HEATING_FAILED_LCD));
        }
```

for the time (interval)

``` cpp
  #define THERMAL_PROTECTION_PERIOD 60        // Seconds
  #define THERMAL_PROTECTION_HYSTERESIS 8     // Degrees Celsius
```

how much, measurement provides a basis for a decision ? 
if one - if the measurement is erroneous -

**Comment by Blue-Marlin** [comment] 2016-03-05 12:46
#define OVERSAMPLENR 16

**Comment by AnatoliyKube** [comment] 2016-03-06 18:44
one more problem -
if you move a thread from lcd -prepare-move axis - move 1 mm (0,1mm) - extruder -
when the rotation of the encoder -or suspense, or reset -
-similarly as the axis z

-if you rotate the encoder slowly - in sync with the movement, the problem occurs less frequently

**Comment by thinkyhead** [comment] 2016-03-08 13:37
> if you rotate the encoder slowly - in sync with the movement, the problem occurs less frequently

We have patched this recently. Obtain the latest code for `RCBugFix` to avoid Marlin crashing while moving with the encoder wheel.

**Comment by AnatoliyKube** [comment] 2016-03-08 15:03
I'm going to try now

**Comment by AnatoliyKube** [comment] 2016-03-08 15:04
No error persists
 lcd -prepere-move axis - move 1 mm (0,1mm) - extruder -
when the rotation of the encoder - reset -

**Comment by AnatoliyKube** [comment] 2016-03-08 15:19
extruder  - try to put 300 mm, 100 mm or more there will be reset
Further
twitching occurs characters  X , Y , Z  on the screen

**Comment by thinkyhead** [comment] 2016-03-10 06:53
> twitching occurs characters X , Y , Z on the screen

Does Auto Home (G28) help that?

**Comment by thinkyhead** [comment] 2016-03-10 06:59
> when the rotation of the encoder - reset -

It sounds very strange. Are you ok sticking with Version 1.0.2-1 for the time being? I cannot imagine what is combining on your system to cause such issues. All we can do is compare the old code and the new code, and try to isolate the changes that lead to instability. For my part, I am unable to reproduce any of the problems you describe using the latest `RCBugFix` code with my hardware.

**Comment by AnatoliyKube** [comment] 2016-03-10 07:39
if you run the g28, twitching  characters disappears,
but ,
after a while begins again(the latest RCBugFix)

**Comment by Blue-Marlin** [comment] 2016-03-10 08:42
That blinking xyz is a wanted change.
In the version before you have seen "---:" insdtead of numbers behind the XYZ when unhomed.
Stepper deactivation time after DEFAULT_STEPPER_DEACTIVE_TIME did not work at all.

Now you see alternating `XYZ` <-> `?` before homing and the relative to boot-position coordinate positions.
After homing static XYZ and position.
When DEFAULT_STEPPER_DEACTIVE pased by without a move the steppers are now deactivated.
The display shows then alternating `XYZ` <-> ` `.
You can stop stepper deactivation for all axes by setting`DEFAULT_STEPPER_DEACTIVE`to 0, or for every single axis with`DISABLE_INACTIVE_[XYZE]`to`false`.
If you want the stepper deactivation but not the blinking with ' 'you can define DISABLE_REDUCED_ACCURACY_WARNING.

**Comment by Blue-Marlin** [comment] 2016-03-10 08:49
@thinkyhead 
#3050 fixed xyz but not e and the z-move in manual homing.
Do you want to finalize your #3110 or should i try to extend my #3050?

**Comment by jbrazio** [comment] 2016-04-28 19:05
Thank you for your interest making Marlin better and reporting this issue but this topic has been open for a long period of time without any further development. Marlin has been under heavy development for the past couple of months and moving to it's last mile to finish the RC cycle and release **Marlin v1.1.0**. We suggest you to try out the latest [RCBugfix](https://github.com/MarlinFirmware/Marlin/archive/RCBugFix.zip) branch and reopening this issue if required.

**Closed as completed by jbrazio** 2016-04-28 19:05 UTC
Labels: Bug: Potential ?, Needs: More Data
