### ISSUE TITLE
Change Filament Menu Items Use First Preheat Setting

### ISSUE THREAD

**Issue by thisiskeithb** [MarlinFirmware/Marlin#20553] opened 2020-12-23 13:34 UTC
### Bug Description

All "Change Filament", "Load Filament", and "Unload Filament" options under the "Change Filament" menu use `PREHEAT_1_TEMP_HOTEND` instead of their defined `PREHEAT_*_TEMP_HOTEND` temperatures.

### Configuration Files

Any config with the steps listed below will work, but here's one of mine rebased to the latest `bugfix-2.0.x` (28440867721b5c614db604c6c6e82c4dd7ab41cb): https://github.com/thisiskeithb/Marlin/tree/myconfig/MK3S-BTT002-TMC2209

### Steps to Reproduce

1. Enable multiple preheat constants like:
    ```cpp
    // Preheat Constants
    #define PREHEAT_1_LABEL       "PLA"
    #define PREHEAT_1_TEMP_HOTEND 210
    #define PREHEAT_1_TEMP_BED     65
    #define PREHEAT_1_FAN_SPEED   255 // Value from 0 to 255

    #define PREHEAT_2_LABEL       "PETG"
    #define PREHEAT_2_TEMP_HOTEND 245
    #define PREHEAT_2_TEMP_BED     85
    #define PREHEAT_2_FAN_SPEED   255 // Value from 0 to 255

    #define PREHEAT_3_LABEL       "CF PC"
    #define PREHEAT_3_TEMP_HOTEND 290
    #define PREHEAT_3_TEMP_BED    105
    #define PREHEAT_3_FAN_SPEED   255 // Value from 0 to 255
    ```
2. Enable `M600`/Advanced Pause as well as `FILAMENT_LOAD_UNLOAD_GCODES` so the menu item "Change Filament" is enabled.
3. Go to "Change Filament" -> "Change Filament", "Load Filament", or "Unload Filament" and then select a preheat other than the first one.
4. Every "Change Filament", "Load Filament", or "Unload Filament" option will use `PREHEAT_1_TEMP_HOTEND` instead of the correct `PREHEAT_*_TEMP_HOTEND` setting.

**Expected behavior:**

All "Change Filament", "Load Filament", and "Unload Filament" options to use the correct `PREHEAT_*_TEMP_HOTEND` setting.

**Actual behavior:**

All "Change Filament", "Load Filament", and "Unload Filament"  options incorrectly use `PREHEAT_1_TEMP_HOTEND` setting.

#### Additional Information

Preheats under the "Temperature" menu work correctly.

**Comment by LinFor** [comment] 2020-12-24 10:06
Duplicate of #20534 ?

**Comment by thisiskeithb** [comment] 2020-12-24 11:11
> Duplicate of #20534 ?

Related, but this is on a single extruder builds.

**Comment by rhapsodyv** [comment] 2020-12-25 00:31
can you test this #20565 ?

**Comment by thisiskeithb** [comment] 2020-12-25 00:46
> can you test this #20565 ?

That fixed it.

**Closed as completed** 2020-12-25 15:38 UTC
Labels: Bug: Confirmed !, C: LCD & Controllers, C: Temperatures

**Comment by sjasonsmith** [comment] 2020-12-25 16:42
@thisiskeithb you don’t want to wait for a fix to actually merge before closing this?
