### ISSUE TITLE
board select

### ISSUE THREAD

**Issue by ta1dr** [MarlinFirmware/Marlin#1198] opened 2014-12-19 14:14 UTC
Hi All
how can I select board on board.h file ?
regards

**Comment by thinkyhead** [comment] 2015-01-02 16:33
I'll roll some of these adjustments into PRs for the Development branch pretty soon.

@gregrebholz On my Arduino IDE the list has no scrollbar, but mousing down to the bottom of the list makes it start to scroll. Either way, terrible UI. I always use an external editor.

**Comment by Lukelectro** [comment] 2015-01-03 23:43
Regarding arduino and the ide list not fitting on the screen and the ctrl-alt-arrow shortcut not working because it does workspace switching in Linux:

quote @nophead "The IDE is rubbish in this respect because if the drop down list doesn't fit on your screen you have to use a separate editor on Linux because the keyboard short cuts do something else."

Try ctrl-super-alt-arrows. Works for me (even though the super key is labelled with the windows flag).

**Comment by nophead** [comment] 2015-01-04 00:05
I don't have a Windows flag key on the keyboard attached to my Linux
machine or a Super key, whatever that is.

It should just scroll when you mouse to the bottom like normal menus.

**Comment by thinkyhead** [comment] 2015-01-04 07:01
I wouldn't mind having reliable __Build__ / __Upload__ commands for Sublime Text (whose bundles should also work with TextMate). Meanwhile, on other platforms here's a list of some alternatives - tools and plugins - that will allow you to invoke the builder: http://playground.arduino.cc/Main/DevelopmentTools – Probably none of them provide convenient __Board Select__ / __Serial Port__ sub-menus, but who knows...?

**Comment by thinkyhead** [comment] 2015-01-04 07:17
[UECIDE](http://uecide.org/download) looks particularly interesting. Implemented in Java, it appears, so it will look like a Java app on your platform. But, if you don't mind the retro look, it's a general-purpose IDE for embedded computing which can download plugins supporting specific hardware. I just used it to build and upload Marlin to my Arduino Mega2560 RAMPS, and it worked perfectly. I highly recommend having it in your toolbox!

**Comment by NarimaanV** [comment] 2015-01-04 17:52
^^^+1 @nophead Second that, downloaded it on Mac and it works pretty dang well. So far tested it on my Arduino Uno and it works great for writing, compiling, and uploading sketches to the Arduino just like with the Arduino IDE. An added bonus is having the option to always put .hex files in the sketch's folder so no more copying the path from the verbose output on the Arduino IDE. Definitely recommended! :D

**Comment by stv0g** [comment] 2015-01-08 19:24
:D This seems to become another issue where we run in circles :D

Just my 2c:
  - I don't like the mixing of capitalization the filenames
  - We should move all language headers in a separate folder
  - The Arduino IDE is simple not adequate for editing such a big project

**Comment by ErikZalm** [comment] 2015-01-08 20:08
Arduino should be the default IDE. It is far from perfect, but it is simple to download and install. And it does work.
You can use an other IDE if you want. I suggest emacs ;-).
It should compile with arduino.

**Comment by boelle** [comment] 2015-01-08 20:12
Major problem with arduino IDE i think is the way it handles when many files are open... it starts going left to right and at the very right it will make a drop down for the rest... some do not find them... 

maybe when we get along we can change the code so it fits better with arduino IDE?

but yeah i guess anyone can use whatever they like to do edits....

**Comment by Wurstnase** [comment] 2015-01-08 20:44
My 2cents: there should be one config-file. not three to look and find the necessary information.

**Comment by boelle** [comment] 2015-01-09 20:45
after talking with @stv0g i will close this one... its not a bug at all... its just a new way of doing things

**Comment by stv0g** [comment] 2015-01-09 20:49
but there are still things which could be done to improve the situation.
For example adding a link to: https://github.com/MarlinFirmware/Marlin/blob/Development/Documentation/Hardware.md

**Comment by boelle** [comment] 2015-01-09 20:51
yes but is this then a bug as such?

ie would the link be the fix?

**Comment by stv0g** [comment] 2015-01-09 20:51
Adding more comments to explain the new approach and a link maybe, yes.
It's not a bug, maybe more an improvement.

**Comment by ErikZalm** [comment] 2015-01-09 20:53
Can you add the boards to the Configuration.h file? Now people need to check other files.
(Not everyone is a programmer)
Can old configuration files be used?
My philosophy was that old config files should work. (New function should be default off)

**Comment by stv0g** [comment] 2015-01-09 20:55
Old configuration files still work, as the numeric board IDs are still valid.
`boards.h`only defined human readable descriptions for these IDs.
There for the source code is easier to read.

Exampe:

```
#if MOTHERBOARD == MELZI
   blabla
#endif
```

**Comment by thinkyhead** [comment] 2015-01-09 23:30
I tend to lean the other way. I think there should be a separate configuration file for Delta printers, for example, and any other switches that bring in a set of #defines (that otherwise would never be defined or used) should have an associated configuration file for it.

**Comment by stv0g** [comment] 2015-01-10 02:50
There's already a separate example configuration for delta and scara printers.
I would prefer, to remove the current Configuration.h from the Marlin directory. 
And place it in the example directory too.
Maybe called "cartesian".

**Comment by thinkyhead** [comment] 2015-01-10 04:49
And, perhaps RAMPS should be the default board.... It's an interesting thought. I think that it's good that there's a Configuration.h in the main folder if that's where it's meant to end up, and being able to compile the sketch out-of-the-box is an important feature – confidence-building if nothing else. (Makes troubleshooting the build environment easier, also.)

However, there has been some murmur - mostly myself - concerning a reform that would require bumping Marlin up to version 2. I think it would be fairly easy to make a transitional "Config_glue.h" file that would translate old Configuration.h and Configuration_adv.h files into the Version 2 system, but the idea is to make it easier, in the long run, to add support, especially for new hardware, in a more pluggable fashion. (Mind you, this is mostly just my own thinking.) This would prevent changes dealing with one platform from necessarily disrupting others.

All that said, Marlin isn't hugely-huge and is amazingly stable as it is, so I may be over-worried. My software project mind developed long before it became possible for something like GitHub to itself become the main source for a piece of software, so it's like "Who cares if we can make stripped-down source distributions? For who or what? The floppy version?" But still, I kind of want it to at least be … kind of pretty.

**Comment by boelle** [comment] 2015-05-31 13:50
will close this one... its merely a misunderstanding issue and not an issue as such...

**Closed by boelle** 2015-05-31 13:50 UTC
Labels: Improvement, On Hold During Bugfix
