### ISSUE TITLE
[FR] Menu Item to set / alter XYZ offsets for Dual-X Axis printers

### ISSUE THREAD

**Issue by bruce356** [MarlinFirmware/Marlin#10404] opened 2018-04-14 02:01 UTC
I meant to say Dual-X Carriage Printers
Hi all, regarding M218 command being available from GLCD Menu (RepRap Discount Full Graphic Smart Controller and others). 

Comment by thinkyhead:-
We are trying to keep the LCD menus from exploding with every possible setting, and this is a value that doesn't typically need to be changed often enough to merit a menu entry. A menu item has to either be there all the time, taking up PROGMEM on boards that may have very little, or requires yet another obscure configuration option to enable/disable.

I understand that a swollen menu system becomes a nightmare to use due to all the options and perhaps memory requirements, but why can it not be made optional like this one recently added:-
https://github.com/MarlinFirmware/Marlin/pull/10389
That way those who want it can use it and others can ignore.

I am not able to program so not familiar with difficulty or if there is any interest by anyone.
example images:-
![img_20180414_111140](https://user-images.githubusercontent.com/209844/38763276-2172a20a-3fd7-11e8-8a31-20376280e7b4.jpg)
![img_20180412_181312](https://user-images.githubusercontent.com/209844/38763277-24d203a0-3fd7-11e8-9361-4c47fb602618.jpg)
Thanks for your attention
Regards - bruce

**Comment by InsanityAutomation** [comment] 2019-10-15 19:45
@boelle @shitcreek duplicate of prior and also done.

**Closed as completed** 2019-10-15 19:46 UTC
Labels: T: Feature Request
