### ISSUE TITLE
[FR] Add mingda 301 board from official board support

### ISSUE THREAD

**Issue by kyon03** [MarlinFirmware/Marlin#22572] opened 2021-08-16 04:07 UTC
### Is your feature request related to a problem? Please describe.

i want the latest marlin but the board is not on official list im trying to add but i dont know how to program now i gave up hoping for some help thanks

### Are you looking for hardware support?

MINGDA rock 3 pro or rock 3 / MD301 board they are using old marlin custom firmware named 2.8.2 but not actually 2.8.2
this was the source
https://drive.google.com/file/d/1YFZfqlmPJfZtNUSB0eDPFQlMQoBwk-dE/view

### Describe the feature you want

the mingda printer hardware was good but they are lacking some support

**Comment by ellensp** [comment] 2021-08-16 04:12
Duplicate of https://github.com/MarlinFirmware/Marlin/issues/21981

**Closed as completed by ellensp** 2021-08-16 04:12 UTC
Labels: T: Feature Request
