### ISSUE TITLE
[BUG] POWER_LOSS_RECOVERY request on every completed print

### ISSUE THREAD

**Issue by 5a2v0** [MarlinFirmware/Marlin#17148] opened 2020-03-13 11:56 UTC
### Bug Description

I upgraded my Geeetech I3 ProB with marlin 2.0.4.4 version and with this upgrade when i finish 100% a print I got on the display a confirmation to resume or stop the print!
I did a eprom inizialization and then printed another object but I got same result.

### My Configurations

**Required:** Please include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
[config.zip](https://github.com/MarlinFirmware/Marlin/files/4329387/config.zip)

### Steps to Reproduce

1. Using marlin 2.0.4.4 start a print
2. Wait until finish
3. Read on lcd the request for resume the stopped print also if not power loss problem during print

**Expected behavior:** lcd shows 100% print status and time

**Actual behavior:** lcd shows a request for resume the stopped print also if not power loss 
problem during print

**Comment by thisiskeithb** [comment] 2020-03-13 13:24
Give the latest `bugfix-2.0.x` branch a try. Several bugs related to SD printing were squashed recently, so it may have been fixed.

**Comment by thinkyhead** [comment] 2020-03-14 04:31
Please test the [`bugfix-2.0.x` branch](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.0.x.zip) to see where it stands. If the problem has been resolved then we can close this issue. If the issue isn't resolved yet, then we should investigate further.

In your testing please enable `DEBUG_POWER_LOSS_RECOVERY`. This will print extra messages to the console for events like deleting the power-loss recovery file. Do a simple G-code file test, such as a file with just a bunch of `M300` and `M118` commands in it. If there are problems with the power-loss file handling then hopefully the extra logging will expose it.

**Comment by 5a2v0** [comment] 2020-03-14 06:50
Ok, tested with bugfix version and printed the same gcode that caused problem before on the 2.0.4.4 
Now the printer finished the job and LCD shows "Press a button" message at the end.
After i clicked once the encoder, lcd shows normal status info with 100% and printing time

So can We close the issue right?

**Comment by boelle** [comment] 2020-06-20 21:27
Lack of Activity
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.

**Closed as completed by boelle** 2020-06-20 21:27 UTC
Labels: Bug: Potential ?, Needs: Testing
