### ISSUE TITLE
[BUG] M25 Will Continue to next extruder command and then pause

### ISSUE THREAD

**Issue by terramir** [MarlinFirmware/Marlin#14158] opened 2019-05-27 22:39 UTC
Hi Folks,
I found an issue with M25 (the lcd print pause command)
If you want to change colors during an lcd print and maybe step away you have a big problem you might figure you could do this:
G0 X0 Y0 Z15
M25 
And the hot nozzle will park away from your print and not melt it right. Wrong this is not the behavior: What will happen is the printer will move to X0 Y0 Z15 and then return to the next print move location and then pause. hence it will start to melt your print.
Thinking that maybe it would just move one print move ahead I tried this:
G0 X0 Y0 Z15
M25 
G0 X10 Y0
but that did not do the trick it extruder moves to X0 y0 z15 then to X10 Y0 then back to the print and stops just before the next extruder move.
This is the work around I found 
M25
G0 X10 Y10 Z10
G1 F1500 E2819.16329 // The E position is the next Extruder move the number just an example
G0 F2000 X0 Y0 
G92 E2812.66329 // this is the previous extruder move number to reset it properly before resuming this is different for every file printed you have to go hunt above the "Break" to find this number.

Well that is my Bug report
terramir

**Comment by robbycandra** [comment] 2019-05-28 13:40
Its a wierd... 

Try this 
```
G90
M82
M106 S0
;M140 S60
;M190 S60
;M104 S200 T0
;M109 S200 T0
M204 P1000 T1500 
G28

G1 X160 Y160 F2000
G1 Z10 F3000
G1 X40 Y160 F2000
G1 X40 Y40 F2000
G1 X160 Y40 F2000
G1 X160 Y160 F2000

G1 Z15 F3000
G1 X40 Y160 F2000
G1 X40 Y40 F2000
M25
M24
G1 X160 Y40 F2000
G1 X160 Y160 F2000

G1 Z20 F3000
G1 X40 Y160 F2000
G1 X40 Y40 F2000
G1 X160 Y40 F2000
G1 X160 Y160 F2000
G28
```

**Comment by robbycandra** [comment] 2019-05-28 13:41
The printer should be paused at 40,40

**Comment by terramir** [comment] 2019-05-28 16:01
yeah it should stop at 40,40,15 but it continues to homing.
Anyone else can verify this?
terramir
PS: robbycandra on another note not everyone has z set to 0 
the first movement line to any code with movements should be Z15 I scratched my heated bed forgetting to add this no real damage I got lucky the glass bed clips just popped off.
terramir

**Comment by robbycandra** [comment] 2019-05-29 03:17
It the printer pause at 40,40 than there is no problem with M25.

**Comment by terramir** [comment] 2019-05-29 04:55
it did not pause that's the point marlin 1.19 rumba it goes all the way till the last homing command it will not stop unless there is a printing move. M25 don't work properly
terramir

**Comment by robbycandra** [comment] 2019-05-29 23:14
Use marlin 2.0

**Comment by terramir** [comment] 2019-05-30 23:44
huh I thought marlin 2.0 was only for arm?
and is it not still in beta? and not ready for release?

**Comment by InsanityAutomation** [comment] 2019-05-31 01:02
@terramir 2.0 covers everything, and most days is better than 1.1.9 by alot! Occasional breakages do come up though.

**Comment by InsanityAutomation** [comment] 2019-05-31 01:06
Reading through this thread, it really sounds like you need to enable parking which will don't the move for you and disable the stepper timeout. The method described above may lead to issues as any axis may drift. You can home x/y again but for z you're in a bit of trouble....

**Comment by boelle** [comment] 2019-07-21 12:35
Configurations, please
Please ZIP up your `Configuration.h` and `Configuration_adv.h` files (as
requested in the Issue template) and drop them into your next reply.
We'll check them over and see if anything is amiss.

**Comment by boelle** [comment] 2019-07-21 19:42
Lack of Activity
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.

**Comment by terramir** [comment] 2019-07-21 19:52
the issue is still there I got a workaround as for parking no need for it when your just changing filament since the motors do have a certain amount of holding torque, but that wasn't really the issue the issue was marlin 1.19 not pausing till the next extrude command instead of pausing right away. I have tried compiling 2.0 and it just pukes. too many errors to deal with honestly. I got the gcode workaround for now so I can use that for the forseeable future
but no it's not fixed in 1.19 and honestly 2.0 is not ready for prime time yet it's current release status on 8-bit doesn't deserve the title beta, it's alpha at best
PS: I have gone through three sets of electronics on this issue btw. an Anet board, a rumba board and now a ramps the anet and rumba dying are unrelated issues but this bug was and is present on the ramps as well

**Comment by robbycandra** [comment] 2019-09-24 16:10
Pause still have to run cached command. Issue still there but we cannot fixed now. (or there are no attempt / no urgent needs to make pause run imediately.)

**Comment by boelle** [comment] 2019-10-21 13:20
@terramir is the issue still there?

**Comment by boelle** [comment] 2019-10-30 21:53
given that @terramir has not replied back since 21 jul i will close this one 

if the bug is confirmed by multiple users of 2.0.x and each of the users attach their config we can reopen again

**Closed as completed by boelle** 2019-10-30 21:53 UTC
