### ISSUE TITLE
[FR] Options to configure when to switch on controller fan

### ISSUE THREAD

**Issue by hamster65** [MarlinFirmware/Marlin#17479] opened 2020-04-11 10:03 UTC
Many setups need cooling only for the stepper drivers, but not for the heated bed. Examples would be relais, mosfets or solid state relais with sufficient passive cooling etc.
It would be nice to have options to select when the controller fan should be active.

For example
#define CONTROLLER_FAN_ON_XYSTEPPERS    // With this option the controller fan switches on if stepper drivers X or Y are active
#define CONTROLLER_FAN_ON_ZSTEPPERS    // With this option the controller fan switches on if stepper drivers for Z are active
#define CONTROLLER_FAN_ON_ESTEPPERS    // With this option the controller fan switches on if stepper drivers for extruders are active
#define CONTROLLER_FAN_ON_BED    // With this option the controller fan switches on if the bed is heating

**Comment by thisiskeithb** [comment] 2023-03-22 10:32
Duplicate of https://github.com/MarlinFirmware/Marlin/issues/11253

**Closed as completed by thisiskeithb** 2023-03-22 10:32 UTC
Labels: T: Feature Request
