### ISSUE TITLE
[BUG] [Bugfix-2.0.x] Performance with the custom X/Y/Z_MIN pins on TMC2130

### ISSUE THREAD

**Issue by m-antonov** [MarlinFirmware/Marlin#11966] opened 2018-09-30 12:21 UTC
Dear community,
I'm using MKS SBASE + MKS TFT32 with the latest bugfix-2.0.x and faced with the following problem.
In addition to this configuration, I added external TMC2130 drivers which were connected to EXP1 and EXP2 sockets via two IDC connectors.

![alt text](http://oi63.tinypic.com/2af0c2.jpg)

In this way, all CS and CFG pins from X/Y/Z/E0/E1 drivers are defined accordingly to EXP sockets.

`#define X_CS_PIN         P0_09`
`#define Y_CS_PIN         P0_28`
`#define Z_CS_PIN         P0_07`
`#define E0_CS_PIN        P0_18`
`#define E1_CS_PIN        P1_31`

I also planned to use the SENSORLESS_HOMING and SENSORLESS_HOMING options.
So, in this way, the X_MIN_PIN, Y_MIN_PIN, and Z_MIN_PIN were replaced in pins_MKS_SBASE.h with the following arguments for the EXP2 socket.

`#define X_MIN_PIN          P3_26`
`#define Y_MIN_PIN          P3_25`
`#define Z_MIN_PIN          P0_08`

The described configuration works correctly when operating from the MKS TFT32 display and doesn't work with USB.
For example, left D1 LED blinks fast on the correct regular work but after connecting the cable to the computer, the blinking frequency of the LED is significantly reduced, and the performance of the board is reduced dramatically - processing of any commands for moving or reading statuses takes a massive amount of time.

![alt text](http://oi66.tinypic.com/dbs4z8.jpg)

At the same time immediately after disconnecting the cable, the system's speed is restored.

As an additional experiment, I reconnected X_MIN_PIN, Y_MIN_PIN, and Z_MIN_PIN to default pins and restored the following configuration in pins_MKS_SBASE.

`#define X_MIN_PIN          P1_24`
`#define Y_MIN_PIN          P1_26`
`#define Z_MIN_PIN          P1_28`

![alt text](http://oi68.tinypic.com/16byfsj.jpg)

In the latter case, the system works without jamming in both cases, either from the display or after connecting to a computer.

**Comment by tcm0116** [comment] 2018-10-02 12:41
@p3p - I have noticed that USB operations on LPC1768/9 have been causing slowdowns lately on my machine. At one point, we had lowered the priority of the USB interrupt to keep this from occurring. Could we have a regression?

**Comment by p3p** [comment] 2018-10-02 13:16
No the priority hasn't changed, nothing really has in the USB stack in bugfix-2.0.x at least for a long time, we are working on improving the USB but its only been pushed into the new [framework](https://github.com/p3p/Marlin/tree/pr_bf2_pulloutlpcframework) rather than Marlin atm, I'm not sure what problem you are having.

@gloomyandy did you see anything flooding the usb interrupts when you were working on the MSC improvements?

**Comment by gloomyandy** [comment] 2018-10-02 15:40
@p3p sort of the use of the interrupt on NAK feature (which is turned on in the current 2.0.x builds) generates a lot of interrupts and caused me to hit watchdog timeouts when testing the SD card. The new code has this option disabled and with that I saw no timeouts. Having said that I only saw the issue during startup when requests for SD card reads are not being serviced, I don't think that should be a problem with the release code, but the NAK interrupts certainly add a little load.

@lompal I'm not sure it was a good idea to use pin P0_08 as I think that is used for hardware SPI for the on-board SD card as is pin P0_07 and pin P0_09. All of these pins are directly connected to the SD card reader (as is pin P1_27) so they should probably not be used them for another purpose. When you plug in a USB cable the system may be trying to use SPI to talk to the SD card and that could be causing some of your issues. I wonder if you could use some of the endstop detect pins for CS for the TMC chips (I've not tried it BTW). Did you make sure that you have remapped to (like the ones used for BTN) are not defined for that purpose.

**Comment by boelle** [comment] 2019-02-21 19:20
@lompal problem solved?

**Comment by m-antonov** [comment] 2019-02-22 08:43
@boelle The problem was not solved completely. I don't insert an SD card when the printer is working after updating the Marlin firmware.
Without a connected SD card, data is exchanged via the USB interface without delays even when the USB cable is connected to a computer.
By the way, the original Smoothieware can be compiled with msd_disable which disables mass storage device on the board. As far as I know, Marlin firmware doesn't support this option.

**Comment by AnHardt** [comment] 2019-02-22 10:26
???
Are there exceptions where 
```
//#define SDSUPPORT
```
does not work?

**Comment by m-antonov** [comment] 2019-02-22 11:19
Earlier, I tried to use this exception, but it didn't give me a positive result.
The only thing that helped was the change in SPI transfer speed.
But the changes in speed did not completely solve the performance problem, and the latency was also felt.

I can re-test this problem on the latest version of the bugfix-2.0.x branch with my SBASE board later if you want.

**Comment by boelle** [comment] 2019-02-22 11:21
remember that bugfix 2.0 is both 8 bit and 32 bit so you can use almost any board

**Comment by gloomyandy** [comment] 2019-02-22 19:29
If you want to disable USB access to the onboard SD card you need to be sure that:
```
/#define USB_SD_DISABLED     // Disable host access to SD card as mass storage device through USB
```
is uncommented and that 
```
#define USB_SD_ONBOARD        // Enable host access to SD card as mass storage device through USB
```
is commented out. But even with USB access to the SD card disabled, the pins I mentioned above P0_07, P0_08, P0_09 and P1_27 are still connected to the onboard SD card reader. So trying to use them for another purpose will be asking for trouble, especially if an SD card is installed in the reader. There is no software fix for this, it is part of the boards hardware configuration.

**Comment by boelle** [comment] 2019-03-06 13:34
@lompal did you retest?

**Comment by boelle** [comment] 2019-03-13 20:40
@thinkyhead think we can close this one

**Comment by m-antonov** [comment] 2019-03-14 07:46
@boelle I currently have no opportunity to retest. I will try to do it soon.

**Comment by boelle** [comment] 2019-06-22 10:41
@thinkyhead Another one that needs to be closed. Sorry, I got bored.

**Comment by boelle** [comment] 2019-07-21 15:33
Lack of Activity
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.

**Comment by boelle** [comment] 2019-08-28 08:38
@lompal any news or still waiting for an opportunity to retest

**Comment by boelle** [comment] 2019-09-24 18:35
@lompal any news or still waiting for an opportunity to retest

**Comment by boelle** [comment] 2019-10-12 11:27
Lack of Activity
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.

**Closed as completed by boelle** 2019-10-12 11:27 UTC
