### ISSUE TITLE
Hotend temperature fluctuates and heating failed system stopped occurs

### ISSUE THREAD

**Issue by sriram135** [MarlinFirmware/Marlin#13515] opened 2019-03-28 13:44 UTC
### Description
Hello I have a DIY 3d printer which has E3d v6 hotend.. when I load file and give print in pronterface the printer starts but the hotend temperature never increase it simply fluctuates ( increases and Decreases) and then Error heating failed system stopped comes please help

### Steps to Reproduce

1. I start print
2. The printer homes itself every axis
3. And waits for temperature of hotend to increase...

**Expected behavior:** [What you expect to happen]: The hotend temperature must meet target temp and start the print...

**Actual behavior:** [What actually happens]: In reality it doesn't happen... Instead the temp reading fluctuates never reached the target temp and heating failed system stopped printer halted occurs...

#### Additional Information

* Include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
* Provide pictures or links to videos that clearly demonstrate the issue. Here are some pics of configs and screenshot of pronterface...
1.https://drive.google.com/file/d/1---vU92rWJeyIxtWrgcZuvIRUFaDJ0ft/view?usp=drivesdk
2. https://drive.google.com/file/d/1-06vC3CPZhJhV7fGfrHBdjY8K3Hx8akd/view?usp=drivesdk
3. https://drive.google.com/file/d/1-0f_janBNdFWqgDXiFbxFjtXyyv9DN8n/view?usp=drivesdk

* See [How Can I Contribute](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/contributing.md#how-can-i-contribute) for additional guidelines.

**Comment by J-charles-C** [comment] 2019-03-28 17:03
I,

Have you set hotend PID ?

https://reprap.org/wiki/PID_Tuning


best

**Comment by sriram135** [comment] 2019-03-28 17:56
Thanks for reply...No... I haven't set
 please help me out..😔

**Comment by J-charles-C** [comment] 2019-03-28 18:03
I my link you have the command to set it.

You can use octoprint, repetier, pronterface to launch the g-code (usb link) or activate the Pid Menu in Marlin to use it with your screen.

**Comment by sriram135** [comment] 2019-03-28 18:07
Is it required? Or without that is ok
Does activating pid autotune solve my problem?

**Comment by sriram135** [comment] 2019-03-28 18:12
I have previously tried uncommenting the pid open loop and everything of that stuff but agian it doesn't work

**Comment by J-charles-C** [comment] 2019-03-28 18:17
it is essential to have a stable temperature and to have no heating error or safety when the ventilation is active.

**Comment by sriram135** [comment] 2019-03-28 18:26
Okay it seems I have tried that earlier... Didn't work ..
But once again I would like to try that... I will inform you once I do...

**Comment by J-charles-C** [comment] 2019-03-29 11:30
I,

Don't forgot to save parameters in eeprom after PID set.

I have soo an E3D hotend. My parameters : 

// Hypercube E3D
  #define  DEFAULT_Kp 13.90
  #define  DEFAULT_Ki 0.93
  #define  DEFAULT_Kd 51.72


best

**Comment by sriram135** [comment] 2019-03-29 15:21
Should I use your kp ki kd ....
As I did pid autotune using m303 I got my own results... 
Kp 12.7
Ki.  0.65
Kd. 57.8
Is this ok or I should use urs?

**Comment by J-charles-C** [comment] 2019-03-30 05:47
I,

your values are comparable to mine.
Have you registered them in Marlin?

best

**Comment by sriram135** [comment] 2019-03-30 05:55
No...I have simply changed the previous default values to newly obtained values by pid autotune.... After doing this also didn't work for me... When I gave print it started heating slowly..i.e fluctuated and when I paused the print the temp started to raise very rapidly... Then when temp reached target(200) I resumed the print... The print started but the temp started falling down and never rose up... Here is the link for the latest pic of configs...
https://drive.google.com/file/d/1-DfcNebNaxUGWIuEouJILPEWCI4xdcer/view?usp=drivesdk

**Comment by J-charles-C** [comment] 2019-03-30 06:06
In terminal 👍 

M304 P12.7 I0.65 D57.8
M500

**Comment by sriram135** [comment] 2019-03-30 06:08
It is showing unknown command

**Comment by J-charles-C** [comment] 2019-03-30 06:13
M30**1** P12.7 I0.65 D57.8
M500

sorry

**Comment by sriram135** [comment] 2019-03-30 06:45
https://youtu.be/OsBx6u4L83E 

See this please... It will give you the better idea of the problem...

**Comment by Bob-the-Kuhn** [comment] 2019-03-30 07:13
If you don't mind getting back to basics …

Please ZIP the following files up and then drop them on your reply:
- configuration.h
- configuration_adv.h
- pins_YOUR-BOARD.h

What controller are you using?

Looks like you have a PT100 thermal sensor on the E3D.  Is that correct?

Does the hot end heat up?

With the hot end off, does the temperature reported by Pronterface increase when you hold the heater block?

What pin is your extruder fan connected to?

**Comment by sriram135** [comment] 2019-03-30 09:21
Thank you for responding... Here are my configs...
[CONFIGS.zip](https://github.com/MarlinFirmware/Marlin/files/3025291/CONFIGS.zip)

I m using Arduino Mega2560 with Ramps 1.4...
I m quiet not sure about the temp. sensor i have.... 
yes the hotend do heat up...(only when i separately heat it i.e setting pla temp in pronterface)
Yes with the hotend off when i hold it the temp do increase....
extruder fan is normally connected to two pins on ramps 1.4 i dont know which pins they are but fan works correct.

**Comment by Bob-the-Kuhn** [comment] 2019-03-30 11:18
On my system my extruder fan overwhelmed the heater. I could only get to 125C with the fan running at full speed all the time.

BEFORE TURNING ON THE FAN, stick something in the fan to keep the blades from turning.  Then turn on the heater and see if the temperature rises.  Turn it off before it gets to 100C.

**Comment by sriram135** [comment] 2019-03-30 11:51
Yep I will try that....

**Comment by Bob-the-Kuhn** [comment] 2019-03-30 12:16
From your configuration files it looks like your fan is tied to the D9 pins/connector.

If that's correct then try the following files.  The only change I made was to the configuration_adv.h file.
[Configuration_1-1-9.zip](https://github.com/MarlinFirmware/Marlin/files/3025428/Configuration_1-1-9.zip)

This should result in the extruder fan turning on at 50C and running at half speed.  If it doesn't turn on then you'll need to change line 247 in configuration_adv.h from 128 to 255.  All it means is your fan isn't designed to run at anything other than full speed.

---

I suggest strongly that you switch from Marlin 1.1.9 to Marlin's bugfix_2.0.x.  1.1.9 is not being updated.  2.0.x is the future. 

To help with the conversion I'm attaching the 2.0.x config files with your customizations included.  I only found a few.
[Configuration_2-0-x.zip](https://github.com/MarlinFirmware/Marlin/files/3025430/Configuration_2-0-x.zip)

**Comment by sriram135** [comment] 2019-03-30 12:33
Hey here is where I have connected fan... Check this pic...
https://drive.google.com/file/d/1-GY2gDU0qnWxMr2DTL6-VuBaCNHE0KD8/view?usp=drivesdk

**Comment by Bob-the-Kuhn** [comment] 2019-03-30 13:06
I think that's just 12V.  Does the fan run as soon as power is applied?

If you are running 12V steppers then move the orange wire to the + terminal on D9 and the white wire to the other terminal on D9.  That way you'll have control over the fan via the software.  If you have +24V then don't do this.  You can damage a 12V fan by running it on 24V.

**Comment by sriram135** [comment] 2019-03-30 13:11
Yes... As soon as power is on fan starts...
I m running 5V stepper motors... Shall I still connect as you told?

**Comment by Bob-the-Kuhn** [comment] 2019-03-30 13:18
You weren't kidding about home built.  In the picture I saw the piece of wood with a bearng and a rod through the bearing.  

How did you acquire this machine?

---

I added a 3D print head to my CNC machine several years ago.  It was low performance back then and it was down more than it was up.  I finally realized that I'd spent more on fixes & improvements than it would have cost to buy a low end printer.  The Creality Ender 3 would have saved me $$ and I'd have a better printer.  Finally put down some $$ on a mid range printer a month ago.

**Comment by Bob-the-Kuhn** [comment] 2019-03-30 13:20
5V motors??  There's not a 12V or 24V power supply?

What stepper drivers are you using?

**Comment by kAdonis** [comment] 2019-03-30 13:28
@Bob-the-Kuhn 
look at the above linked video
@sriram135 
What is your power source,? It is probably overloaded, you need at least 12V and 4A

**Comment by Bob-the-Kuhn** [comment] 2019-03-30 13:29
There is just +5V tied to the big power inputs on the RAMPS card?

If that's the case then go ahead and move the fan wires.

That also might explain the heating problem.  Unless you have something special the heater expects to see 12V or 24V.  If you're running a 12V heater from 5V then it's only seeing (5*5)/(12*12) = 17% of the power it was designed for.  It may not get hot enough to melt PLA even without the fan.

**Comment by Bob-the-Kuhn** [comment] 2019-03-30 13:54
I am amazed!!!

Do you actually have motors moving?  What motors do you have?

Those look like A4988 steppers.  They're only rated for 8V and above operation.  

___

If you're anything like me it won't be long before you'll be wanting faster printing and higher quality prints.  It's really easy to do 3-5 upgrades at $30 - $50 over the next 6 months.  That puts you close to the cost of an Ender 3.  Please seriously consider the Ender 3 rather than doing upgrades.  The Ender 3 has reasonable speed and produces prints that are as good as come from printers 3 times the cost.

**Comment by Bob-the-Kuhn** [comment] 2019-03-30 14:02
I agree on the power supply.  

I've only seen 30W and 40W heaters.  Even if you did find a 5V heater chances are excellent that you'll burn up the USB cable before you melted any plastic.

**Comment by sriram135** [comment] 2019-03-30 14:06
Hey nice suggestions @kAdonis and @Bob-the-kuhn.... I have built this printer at my house and the motors move just fine!! I m using A4988 drivers... The motors get a little hot after sometime.... But for smaller prints they are absolutely fine... The machine works perfectly as CNC the only problem is with hotend...😶
@Bob-the-kuhn I built this printer because I wanted to... I had no idea all this would happen...
Please I need your help in at least making it print.. Now I don't want to spend any money on buying a new one... Please help me with this... Its a kind request...
I use 12V 5A power supply...

**Comment by Bob-the-Kuhn** [comment] 2019-03-30 14:12
I'll stick with you as long as you're working on it.

Wow - another person that started with a CNC machine and decided to add 3D print capabilities.  We must be both geniuses.  My wife has a rather different opinion of what I've built and how I've been spending my time.  **☹️**

**Comment by Bob-the-Kuhn** [comment] 2019-03-30 14:16
OK - 12V power supply.  That's good.  That explains a lot.

I would suggest going to a better power cord.  I'm surprised that it hasn't already burned up.

Yes, it's OK to move the fan to the D9 connector.

**Comment by sriram135** [comment] 2019-03-30 14:22
Oh sir u are older than me I m a student studying engineering....
I daily sit infront of the printer dealing with problem and get up without solving it... 
Sir what shall I do now? Shall I connect fan to D9 port? Or shall I update the marlin and flash marlin 2.0 bugfix?
Sry sir I didn't see your comment as I was busy in typing... Ok I will move fan to D9...

**Comment by kAdonis** [comment] 2019-03-30 14:49
In the video, you could see the red led near the Hotend connector on the RAMPS flashing, indicating that the output is active, but **only for a split second**. It should be permanently on until the hotend temperature is nearly reached and then start pulsing.
I think your 12V power supply is switching off, because it is overloaded.
Your hotend might have a 24V heater cartridge or is shorted, could you measure the resistance?
And where is this beeping and clicking sound coming from?

**Comment by Bob-the-Kuhn** [comment] 2019-03-30 14:52
You'll need some cooling on the hot end or you'll melt plastic too far up the borden tube.  I ruined a heatsink trying to drill out a melted tube.

Let's stick with 1.1.9 and play with the fan to see if it can be throttled back far enough that you can melt plastic.

For a month or so I had a piece of cardboard partially covering my fan.   I eventually ordered one that could be throttled back.

**Comment by sriram135** [comment] 2019-03-30 17:08
@kAdonis the beeping and clicking sound is maybe from fan turning on and off ... Its a E3D V6 all metal hotend Wade extruder type... I think it maybe 12V heater cartridge....hmm I don't have multimeter right now to measure the resistance...😁

@Bob-the-kuhn throttle back means slowing it down or reversing the fan direction?

**Comment by kAdonis** [comment] 2019-03-30 17:38
> the beeping and clicking sound is maybe from fan turning on and off 

If you didn't change your connection yet, the fan is connected directly to 12V from your power supply, therefore it should run all the time the power supply is on.
For testing you could disconnect the heater from RAMPS and try to heat, the fan should stay on and the red led should light up (until heating failed error, of course)
If that works, we know its a problem with heater or power supply, if not we have to look further

**Comment by sriram135** [comment] 2019-03-30 17:45
Now I connected it to D9 and saw for first time the when I gave print the temp rose up to max 230  and kept stabilizaling it didn't resume the print at all... Then I disconnected and reconnected to pronterface then again I saw the beeping sound and clicking sound... And it gave thermal runaway error...

**Comment by sriram135** [comment] 2019-03-30 17:47
Now the red led is on only when temp is above 50 Celsius that too at half speed... As per Bob-the-kuhn

**Comment by kAdonis** [comment] 2019-03-30 17:58
What did you connect to D9, the fan or the heater?

**Comment by sriram135** [comment] 2019-03-30 17:58
The fan..

**Comment by kAdonis** [comment] 2019-03-30 18:02
are you using Bob-the-Kuhn's Configuration_1-1-9.zip?

**Comment by sriram135** [comment] 2019-03-30 18:03
Yes

**Comment by kAdonis** [comment] 2019-03-30 18:16
There are two leds on RAMPS for D9 and D10,
D9 should blink over 50 deg, thats fine 
Try now to disconnect the Heater from D10, let the printer cool down below 100deg and try to heat 
watch led 10, it should be on and no clicking and beeping

**Comment by sriram135** [comment] 2019-03-30 18:24
Should I heat it without the heater connected?

**Comment by kAdonis** [comment] 2019-03-30 18:25
yes
just a test

**Comment by sriram135** [comment] 2019-03-30 18:30
Yes it remained on i.e it started heating correctly... I.e no clicking and beeping

**Comment by kAdonis** [comment] 2019-03-30 18:41
That means software is working
You have either a faulty heater, a 24v heater- you need a multimeter to verify
or your power supply is not able to deliver enough current

From your picture I think your hotend is probably a clone, not a genuine E3d 
Genuine E3d hotends need thermistor 5, but i have seen clones that need thermistor 11
Sorry, I have to leave now, good luck with further troubleshooting

**Comment by sriram135** [comment] 2019-03-30 18:44
Oh okay thank you very much for spending your valuable time in trying to solve my problem...

**Comment by sriram135** [comment] 2019-03-30 18:46
@Bob-the-kuhn how do I know what kind of E3d I have whether it's clone or genuine... I purchased it for 800 INR..

**Comment by kAdonis** [comment] 2019-03-30 18:48
I forgot...
The Polyswitch fuse on your RAMPS could be faulty

Von meinem iPhone gesendet

**Comment by sriram135** [comment] 2019-03-30 18:52
Oh is it.... Should I replace it with new one?

**Comment by Bob-the-Kuhn** [comment] 2019-03-30 20:38
At that price it's sure to be a clone.  Most of the time they work OK.

Take a look at the link where you bought it.  It should state there if it's 12V or 24V.  The fan may say if it's 12 or 24V.

---

>  temp rose up to max 230 and kept stabilizaling it didn't resume the print at all... Then I disconnected and reconnected to pronterface then again I saw the beeping sound and clicking sound... And it gave thermal runaway error.

Thermal runaway error is declared by the Marlin software and reported by pronterface..  Once marlin declares a thermal problem then it kills the print and will not resume it.  You need to cool things down and then restart the print.

230C is the max set in configuration.h.  Marlin will not allow the temperature to go beyond that.

There may be a problem with the commands in the print file.  Please ZIP it up and post it.

I'd like you to manually set the extruder temperature and observe what happens.  

I'd like you to go to the line that says HEAT and then type in 75 into the box and then click set.  You should see the temperature rise to 75C and then stabilize there  The fan should come on at 50C.

If that goes well then type in 125, hit set and see what happens.

Then 175.

Then 215.

**Comment by sriram135** [comment] 2019-03-31 03:44
Yep I will do that....

**Comment by sriram135** [comment] 2019-03-31 04:23
How to zip commands in print file? Please tell me that...

**Comment by Bob-the-Kuhn** [comment] 2019-03-31 05:25
Just take the file itself & ZIP it.    It's just a text file.

**Comment by sriram135** [comment] 2019-03-31 06:00
Ok sure

**Comment by sriram135** [comment] 2019-03-31 11:53
[Anet_A8_extruder_relese_knob.zip](https://github.com/MarlinFirmware/Marlin/files/3026539/Anet_A8_extruder_relese_knob.zip)
Here is the zip

**Comment by Bob-the-Kuhn** [comment] 2019-03-31 19:44
There's nothing strange in the gcode file.  It sets the temperature to 200C.

**Comment by sriram135** [comment] 2019-04-01 02:12
Oh okay... Then I checked the temp .... First I set it to 75.. the fan started normal at 50 but heater went on climbing above 75! It didn't stop at 75...

**Comment by Bob-the-Kuhn** [comment] 2019-04-01 04:23
Did the LED for the heater turn off when it got to 75?

**Comment by kAdonis** [comment] 2019-04-01 11:53
I just checked your configs again,
make sure you changed the following settings back to this (default):
```cpp
#define PIDTEMP
#define BANG_MAX 255     // Limits current to nozzle while in bang-bang mode; 255=full current
#define PID_MAX BANG_MAX // Limits current to nozzle while PID is active (see PID_FUNCTIONAL_RANGE below); 255=full current
#define PID_K1 0.95      // Smoothing factor within any PID loop
#if ENABLED(PIDTEMP)
  //#define PID_AUTOTUNE_MENU // Add PID Autotune to the LCD "Temperature" menu to run M303 and apply the result.
  //#define PID_DEBUG // Sends debug data to the serial port.
  //#define PID_OPENLOOP 1 // Puts PID in open loop. M104/M140 sets the output power from 0 to PID_MAX
  //#define SLOW_PWM_HEATERS // PWM with very low frequency (roughly 0.125Hz=8s) and minimum state time of approximately 1s useful for heaters driven by a relay
  //#define PID_PARAMS_PER_HOTEND // Uses separate PID parameters for each extruder (useful for mismatched extruders)
                                  // Set/get with gcode: M301 E[extruder number, 0-2]
  #define PID_FUNCTIONAL_RANGE 10 // If the temperature difference between the target temperature and the actual temperature
                                  // is more than PID_FUNCTIONAL_RANGE then the PID will be shut off and the heater will be set to min/max.
```

**Comment by sriram135** [comment] 2019-04-01 13:01
Yep ... @Bob-the-kuhn didn't see that properly... I will check it once again... Wait

**Comment by sriram135** [comment] 2019-04-04 14:29
I m a little bit busy because of my college projects of engineering... I m sry for late reply... I will see it soon...

**Comment by sriram135** [comment] 2019-04-06 11:53
@KAdonis yes changed to that!..
@Bob-the-kuhn yes the LED turned off after reaching 75

**Comment by kAdonis** [comment] 2019-04-06 13:24
> yes the LED turned off after reaching 75

This is good. Did you try the other temperatures as Bob-the-Kuhn wrote above?

**Comment by sriram135** [comment] 2019-04-06 13:40
Yeah tried... The temp reached set temp and then LED turns off and then if temp goes below agian LED starts blinking and tries to comeback to same set temp...

**Comment by kAdonis** [comment] 2019-04-06 14:40
Does the temperature stabilize at the set temp? If it keeps oszillating you should run PID autotune again

**Comment by sriram135** [comment] 2019-04-06 14:53
Yes...means the value of set temperature nearly remains constant....

**Comment by kAdonis** [comment] 2019-04-06 15:08
Then you could try to print. 
I still dont trust your power supply, if the beeping and clicking should start again watch the LED

**Comment by sriram135** [comment] 2019-04-06 15:33
Yep I will try to print...

**Comment by sriram135** [comment] 2019-04-07 07:44
@KAdonis yes... It started beeping and clicking again ....

**Comment by kAdonis** [comment] 2019-04-07 11:29
Did the print fail again?
You need a better power supply
You might find an old ATX PSU from a scrap computer for free, these can be easily modified
just google: atx psu 3d printer

**Comment by sriram135** [comment] 2019-04-07 11:47
Okay I will try to get atx psu

**Comment by sriram135** [comment] 2019-04-07 11:49
What are specs of that psu?

**Comment by kAdonis** [comment] 2019-04-07 11:58
ATX PSUs are used in desktop computers, they deliver 3.3V, 5V and 12V
their specs vary
https://en.wikipedia.org/wiki/ATX
You dont need an ATX PSU (but it may be free) any PSU that is able to provide 12-15V DC and **real 5A** is fine for you
12V LED power supplies are fine also

**Comment by sriram135** [comment] 2019-04-07 12:00
Means I should buy 12V psu okay

**Comment by kAdonis** [comment] 2019-04-07 12:15
if you plan to upgrade your printer in the future with a heated bed, you should consider to buy a more powerful PSU with at least 300W

**Comment by sriram135** [comment] 2019-04-07 13:58
Okay... But can you tell me what is wrong with my psu?
Here is a pic of cover of my psu...
https://drive.google.com/file/d/1-Wql3fu9EhHSaHURX7oZVw5kccReXefL/view?usp=drivesdk

**Comment by kAdonis** [comment] 2019-04-07 15:04
From the specs on the label your PSU is fine,
But I dont believe it can really provide 5A
I think, at around 3A your PSU gets too hot internally and the protection circuit switches the PSU off, after a second the PSU is switched on, and immediatly off again (with a click)
the beeping could be the overload alarm, or the PSU is simply faulty
I would not be surprised, if it was produced as a 2-3A PSU, but someone relabeled it as 5A

**Comment by sriram135** [comment] 2019-04-08 06:39
Oh is it?... Can I check the output of it i.e output in amps

**Comment by kAdonis** [comment] 2019-04-08 11:45
> Can I check the output of it i.e output in amps

This is not an easy job, you need (expensive) special equipment and some experience
Its easier to find a more powerful power supply. My first printer from 2013 is still running with an ATX PSU I took from a scrap computer. 12V 20A for free
![image](https://user-images.githubusercontent.com/35379348/55721760-745afd80-5a04-11e9-81e4-3ffa89d6472c.png)

**Comment by sriram135** [comment] 2019-04-08 13:03
Yep searching for that psu....😀

**Comment by sriram135** [comment] 2019-04-08 14:01
Does it damage these 5v motors by connecting to 20A current?

**Comment by kAdonis** [comment] 2019-04-08 14:14
> Does it damage these 5v motors by connecting to 20A current?

No, there is no change. The printer draws the current it needs from the PSU. 
These 20A is just the maximum current the power source is able to deliver

**Comment by ManuelMcLure** [comment] 2019-04-08 16:19
A really good and inexpensive option for a power supply is the HP DPS-600PB server power supply. These provide 47A at 12.5V and are usually available on eBay for around $20 shipped. They don't need any special loads to give full power (many cheap ATX power supplies will not provide full power on the 12V rail unless you have a load on the 5V and 3.3V rails) and are very easy to get going (just connect pins 4, 6, 8 and 10 on the center connection for it to turn on).

One con of this power supply is that being a hot-swappable power supply the outputs are blades so you have to solder output wires to the blades. I spread the blades, insert 12 or 14AWG wire and flow plenty of solder to make a solid connection. Then I use heat shrink to insulate the joint.
The other con is that the fan runs even if the power supply is on standby (i.e. the PS_ON pin is not enabled). In my case I keep the PSU unplugged from the wall if I'm not printing so its not a big deal.

**Comment by sriram135** [comment] 2019-04-08 17:01
Thanks for your reply @ManuelMcLure yeah but will Atx psu be enough.?

**Comment by ManuelMcLure** [comment] 2019-04-08 17:21
Yes, as long as it is correctly configured. As I mentioned, some ATX PSUs need a decent load on the 5V and/or 3.3V rails to be able to provide full output on the 12V rail, and it's usually hard to determine whether this is the case without actually testing it. But if you have an unused ATX power supply around it's definitely worth testing and if it works without loading the 5V and 3.3V rails, great! You've saved some money.

**Comment by SRIRAM134** [comment] 2019-06-01 08:27
Hey @kAdonis check this atx psu...
https://drive.google.com/file/d/1-hE1BxfuF-h7PRtTkQl6DFwXopr6aumI/view?usp=drivesdk
I have brought it from an old store having desktop computers...

**Comment by kAdonis** [comment] 2019-06-01 12:06
Hey Sriram134
From the label your ATX PSU looks fine.
To use it, look at [this video](https://www.youtube.com/watch?v=SBhlHQbUaqs) or google for "ATX PSU for 3d Printer"
Be sure to properly isolate everything to prevent fire!

**Comment by SRIRAM134** [comment] 2019-06-01 12:22
Following steps like in video to use it  is enough right?

**Comment by kAdonis** [comment] 2019-06-01 12:35
Yes, I did this with three different ATX PSUs and it worked without problems

**Comment by SRIRAM134** [comment] 2019-06-01 12:39
Thanks i will try it out...

**Comment by SRIRAM134** [comment] 2019-06-01 15:05
Hey kAdonis.. I m controlling printer with my laptop... Is there any danger to it if I use atx psu?

**Comment by kAdonis** [comment] 2019-06-01 16:02
Not more danger as always with an 3d Printer. I never heard about a broken Laptop from a 3d printer but from printers going up in flames
Keep cables isolated and check there are no loose connections, then everything is fine.
But dont leave the printer unattended while printing

**Comment by SRIRAM134** [comment] 2019-06-02 11:31
Okay... Thanks a lot @kAdonis , @Bob-the-Kuhn , @J-charles-C , @ManuelMcLure  For all the support to fix my problem...and yes it is fixed!!! Now for fisrt time it printed correctly... Without any errors...Thank you soooo much guys... I will ask you if there are any problems in future...😊♥️

**Comment by kAdonis** [comment] 2019-06-02 15:46
I'm glad I could help
Dont forget to close the issue, if your problem is solved

**Comment by SRIRAM134** [comment] 2019-06-03 11:19
Yeah sure.....

**Comment by SRIRAM134** [comment] 2019-07-11 14:31
Hey kAdonis I have another problem. Its printing but the X axis motor (28byj-48) Motor is skipping steps while printing. Due to this the after first layer the second layer is offseted by some distance and third layer and so on... Resulting in side printing of layers... Please help...

**Closed as completed** 2019-07-11 15:26 UTC
