### ISSUE TITLE
[BUG] Add Preheat Menu Item

### ISSUE THREAD

**Issue by brunohenriquy** [MarlinFirmware/Marlin#23697] opened 2022-02-08 15:30 UTC
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

The Configuration.h file says:
//
// Preheat Constants - Up to 5 are supported without changes
//

But if you add another item it doesn't work. 

I tried to understand the code to see where it adds the preheat items but despite the two entries(PREHEAT_1_..., PREHEAT_2_...) in the  Configuration.h, it seems to be static(PLA and ABS)  in other parts of the code, not a dynamic code to look for other preheat configuration like 3 to 5.

A-Is it intentional? It's supposed to be only the 2 items, and if I want something else I have to use CUSTOM_MENU_MAIN/CUSTOM_MENU_CONFIG?
If that's the case, we should remove the comment "Up to 5 are supported without changes"

B-Or is it a bug and the code should be dynamic, so a user should just have to add new entries at Configuration.h and it works?

P.S.: If anybody could point me to the direction where it really adds the menu preheat items, I could code the fix. But I couldn't even change the "Preheat PLA" to "Preheat Blablabla". Is this value an image at Ender 3 V2 menu(DWIN_SET), or is this a string at some point of the code?

### Expected behavior

Add a configuration and see it on the LCD screen.
#define PREHEAT_3_LABEL       "PETG"
#define PREHEAT_3_TEMP_HOTEND 280
#define PREHEAT_3_TEMP_BED     80
#define PREHEAT_3_TEMP_CHAMBER 35
#define PREHEAT_3_FAN_SPEED   255 // Value from 0 to 255

### Actual behavior

It doesnt show up on the screen

### Version of Marlin Firmware

 bugfix-2.0.x

### Printer model

Creality Ender 3 V2

**Comment by borland1** [comment] 2022-02-08 18:25
In ultralcd.cpp, comment says "Initialized by settings.load()".   If you haven't re-initialized your EEPROM settings and reboot immediately after doing the firmware update upload, then it might not initialize these new LCD menu features. Just a guess.

```
#if PREHEAT_COUNT
  preheat_t MarlinUI::material_preset[PREHEAT_COUNT];  // Initialized by settings.load()
  PGM_P MarlinUI::get_preheat_label(const uint8_t m) {
    #ifdef PREHEAT_1_LABEL
      static PGMSTR(preheat_0_label, PREHEAT_1_LABEL);
    #endif
    #ifdef PREHEAT_2_LABEL
      static PGMSTR(preheat_1_label, PREHEAT_2_LABEL);
    #endif
    #ifdef PREHEAT_3_LABEL
      static PGMSTR(preheat_2_label, PREHEAT_3_LABEL);
    #endif
    #ifdef PREHEAT_4_LABEL
      static PGMSTR(preheat_3_label, PREHEAT_4_LABEL);
    #endif
    #ifdef PREHEAT_5_LABEL
      static PGMSTR(preheat_4_label, PREHEAT_5_LABEL);
    #endif

    #define _PLBL(N) preheat_##N##_label,
    static PGM_P const preheat_labels[PREHEAT_COUNT] PROGMEM = { REPEAT(PREHEAT_COUNT, _PLBL) };

    return (PGM_P)pgm_read_ptr(&preheat_labels[m]);
  }
#endif
```

**Comment by brunohenriquy** [comment] 2022-02-08 18:59
@borland1 Yes, I've re-initialized the EEPROM and rebooted. Maybe it's a CrealityUI(DWIN_CREALITY_LCD) bug.

**Comment by thisiskeithb** [comment] 2022-02-08 19:19
Duplicate of https://github.com/MarlinFirmware/Marlin/issues/21904

**Closed as completed by thisiskeithb** 2022-02-08 19:19 UTC

**Comment by brunohenriquy** [comment] 2022-02-08 19:29
Thanks @thisiskeithb I haven't seen this old issue!
