### ISSUE TITLE
Prusa Multiplexer - active_extruder should always be 0

### ISSUE THREAD

**Issue by mtm88001** [MarlinFirmware/Marlin#10573] opened 2018-04-30 04:04 UTC
### Description

I have built a custom 3d printer using a ramps based board and the Prusa Multiplexer.  I installed the latest Marlin 1.1.8 and changed only enough of the config to enable the MK2_MULTIPLEXER.  Printer works; however, I am only able to extrude from extruder 0.  I was able to change code in Marlin_main.cpp to fix the issue and wanted to get feedback on the code change.

bugfix 1.1.x seems to have the same code.

**Expected behavior:**
When switching extruders from Repetier-Host the Multiplexer should click indicating a switch and should be able to extrude from the selected extruder.
**Actual behavior:**
When switching extruders from Repetier-Host the Multiplexer does click indicating a switch and selecting any extruder except Extruder 0, the printer will not extrude.

#### Additional Information

Current code snippet:
`Marlin_main.cpp` (1.1.x)
```cpp
 #if ENABLED(MK2_MULTIPLEXER)
        if (tmp_extruder >= E_STEPPERS)
          return invalid_extruder_error(tmp_extruder);

        select_multiplexed_stepper(tmp_extruder);
      #endif

      // Set the new active extruder
      active_extruder = tmp_extruder;
```
AcroWD Fork
`Marlin_main.cpp` (1.1.8)
```cpp
#if ENABLED(MK2_MULTIPLEXER)
        if (tmp_extruder >= E_STEPPERS)
          return invalid_extruder_error(tmp_extruder);

        select_multiplexed_stepper(tmp_extruder);
        active_extruder = 0;
      #else
          // Set the new active extruder
          active_extruder = tmp_extruder;
      #endif
```

See https://github.com/mtm88001/Marlin/tree/AcroWD for reference.

Additionaly I found a code incosistency, not sure if on purpose or just got missed.  Should the for loop not reference s instead of e since s is the index?

`Marlin_main.cpp` (1.1.x)
```cpp
  /**
   * M702: Unload all extruders
   */
  inline void gcode_M702() {
    for (uint8_t s = 0; s < E_STEPPERS; s++) {
      select_multiplexed_stepper(e);
```
  
AcroWD Fork
`Marlin_main.cpp` (1.1.8)
```cpp
  /**
   * M702: Unload all extruders
   */
  inline void gcode_M702() {
    for (uint8_t s = 0; s < E_STEPPERS; s++) {
      select_multiplexed_stepper(s);
```

**Comment by thinkyhead** [comment] 2018-04-30 08:50
> I was able to change code in Marlin_main.cpp to fix the issue and wanted to get feedback on the code change.

Please actually test the `bugfix-1.1.x` (and/or `bugfix-2.0.x`) branch to see where it stands. If the problem has been resolved then we can close this issue. If the issue isn't resolved yet, then we can investigate further.

> Additionaly I found a code incosistency

We don't patch 1.1.x. That branch is for tagged releases only. You should look at the current `bugfix-1.1.x` and `bugfix-2.0.x` branches to see where current development is. The M702 lines you're displaying are no longer present in the latest code.

**Comment by revilor** [comment] 2018-05-09 01:18
Sounds like the `DISABLE_INACTIVE_EXTRUDER` issue which is fixed in the bugfix branches. For 1.1.8
```cpp
#define DISABLE_INACTIVE_EXTRUDER false
```
should resolve your issue.

**Comment by mtm88001** [comment] 2018-05-09 10:38
Thanks

**Closed as completed** 2018-05-10 01:17 UTC
Labels: Bug: Potential ?, Needs: More Data
