### ISSUE TITLE
STM32F103RET6_creality  FAILED

### ISSUE THREAD

**Issue by alorgi1** [MarlinFirmware/Marlin#23231] opened 2021-11-29 21:45 UTC
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

Marlin\src\HAL\STM32\fast_pwm.cpp: In function 'void set_pwm_frequency(pin_t, int)':
Marlin\src\HAL\STM32\fast_pwm.cpp:74:36: error: 'Instance' was not declared in this scope
   74 |   uint32_t index = get_timer_index(Instance);
      |                                    ^~~~~~~~
Marlin\src\HAL\STM32\fast_pwm.cpp:77:16: error: 'TEMP_TIMER_NUM' was not declared in this scope; did you mean 'TIMER_NUM'?
   77 |   if (index == TEMP_TIMER_NUM || index == STEP_TIMER_NUM
      |                ^~~~~~~~~~~~~~
      |                TIMER_NUM
Marlin\src\HAL\STM32\fast_pwm.cpp:77:43: error: 'STEP_TIMER_NUM' was not declared in this scope; did you mean 'TIMER_NUM'?
   77 |   if (index == TEMP_TIMER_NUM || index == STEP_TIMER_NUM
      |                                           ^~~~~~~~~~~~~~
      |                                           TIMER_NUM
*** [.pio\build\STM32F103RET6_creality\src\src\HAL\STM32\fast_pwm.cpp.o] Error 1

### Version of Marlin Firmware

Marlin-bugfix-2.0.x

### Printer model

Ender 3 pro V.4.2.7

**Comment by thisiskeithb** [comment] 2021-11-29 21:51
Duplicate of #23213

**Closed as completed by thisiskeithb** 2021-11-29 21:51 UTC
