### ISSUE TITLE
Skew Correction Feature?

### ISSUE THREAD

**Issue by sarf2k4** [MarlinFirmware/Marlin#5380] opened 2016-12-05 05:36 UTC
Hi, I recently found out that my printouts will produce skew and thus making a case isn't that great.

What I had in mind is to give a suggestion to add a feature of skew compensation/correction by keying in several options:

1. Users just key in how many degree offset, positive or negative.
2. Having marlin calculates based on sample size, which is marlin will calculate the degree offset of the skew issues

Explanations
1.
With this, users will have to calculate the angle themselves by having to print a big cube using Pythagorean theorem method of getting the skewed angle degree. For example the angle is x = -2', this would mean the cube are skewed to towards the min x axis, note the minus sign. The minus sign and positive sign will indicate the printout are skewed to which direction. In the picture, the red line indicates the skew angle along y (correct me on this) and it goes to the positive side (on x axis), while the orange are printed on x axis but the skew are towards to minus y axis.

2.
This method are easier for user without the need of using pythagorean theorem formula, instead marlin will do it, but they have to key in the sample length then marlin will be able to calculate, The reference point will always be at bottom left corner, which is x 0, y 0, taking reference from the picture on the red line, user will key in the length (in mm) from where it has skewed. It is just the same like the first option, positive is what depicted in the picture's red line, negative will be like in the orange line

Additions
I wouldn't mind going only for the first method only, but it would be great if the options can be changed from the eeprom and accessible directly from lcd panel,

![skew](https://cloud.githubusercontent.com/assets/9604217/20874470/40dc7c3a-baed-11e6-8b3a-fddd1911f472.png)

I hope this will give some head start or spark in making an even more precise print, thus making marlin even more great firmware to be used with most 3d printers out there

Regards
-Sarf

**Comment by thinkyhead** [comment] 2016-12-05 06:04
Duplicate of #4904 and #5116

**Closed as completed by thinkyhead** 2016-12-05 06:04 UTC
Labels: T: Feature Request, F: Calibration
