### ISSUE TITLE
Compile error when trying to compile Marlin bugfix2.0.x

### ISSUE THREAD

**Issue by bfrakes256** [MarlinFirmware/Marlin#11137] opened 2018-06-28 01:23 UTC
Here is the exact error:
```
Archiving built core (caching) in: C:\Users\<username>\AppData\Local\Temp\arduino_cache_366030\core\core_arduino_avr_mega_cpu_atmega2560_cc708c5a95af27b60b589ff2ba91974d.a
fork/exec C:\Users\<username>\AppData\Local\Arduino15\packages\arduino\tools\avr-gcc\4.9.2-atmel3.5.4-arduino2/bin/avr-gcc.exe: The filename or extension is too long.
Error compiling for board Arduino/Genuino Mega or Mega 2560.
```
Have updated all boards and libraries in the Arduino IDE  1.8.5

Please advise...

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

#### Additional Information

* Include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/contributing.md#how-can-i-contribute) for additional guidelines.

**Comment by crzcrz** [comment] 2018-06-28 06:34
This has been answered before: #8633

**Comment by thinkyhead** [comment] 2018-06-28 09:32
Duplicate of #8633

**Comment by thinkyhead** [comment] 2018-06-28 09:33
Arduino 1.9 is required to build Marlin 2.0.x.

**Closed as completed by thinkyhead** 2018-06-28 09:33 UTC
Labels: C: Build / Toolchain

**Comment by bfrakes256** [comment] 2018-06-28 09:52
I've downloaded and installing. 

Thanks....

**Comment by dobromyslov** [comment] 2020-08-14 02:21
Arduino 1.9 does not help to solve this issue.
Still getting 

`fork/exec D:\storage\arduino-PR-beta1.9-BUILD-119\hardware\tools\avr/bin/avr-gcc.exe: The filename or extension is too long`.

**Comment by ellensp** [comment] 2020-08-14 02:23
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
