### ISSUE TITLE
[BUG] Compilation error, missing "libmaple/usart.h" but using arduino IDE

### ISSUE THREAD

**Issue by ReuvenStahl** [MarlinFirmware/Marlin#19315] opened 2020-09-09 08:19 UTC
i'm trying to compile Bugfix for my MKS bored using the Arduino IDE.
and i'm having the same issue as :
https://github.com/MarlinFirmware/Marlin/issues/19305

any suggestions?

**Comment by AnHardt** [comment] 2020-09-09 08:35
> any suggestions?

Use VSCode.
Don't duplicate issues.
Follow the discussion in #19305 
Please close this issue.

**Closed as completed** 2020-09-09 08:36 UTC

**Comment by sjasonsmith** [comment] 2020-09-09 14:23
@ReuvenStahl a patch is already posted. Try making the changes you find here:
https://github.com/MarlinFirmware/Marlin/pull/19307

That will probably fix your issue. I do agree with the recommendation to use PlatformIO. Nobody doing any serious development in Marlin still uses Arduino IDE, so it is easy for breaks like this to happen. Arduino IDE might seem simpler, but it is also much easier for things to go wrong.

**Comment by sjasonsmith** [comment] 2020-09-09 14:24
Duplicate of #19305
