### ISSUE TITLE
[BUG] Unable to build a marlin firmware with STM32F103VE_longer_maple environment

### ISSUE THREAD

**Issue by rbora13** [MarlinFirmware/Marlin#25813] opened 2023-05-12 09:46 UTC
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem does not exist.

### Bug Description

Hello,
For 2 days, I and others have not been able to build a Marlin firmware with STM32F103VE_longer_maple environment and non bugfix releases. With the latest bugfix version, compilation is fine.
The problem is that I have many problems with the non maple environment  (reboot when X endstop is closed,...)
So, is there a way to build Marlin firmware with maple environment and reliable/not bugfix marlin sources?
Thanks for your help

### Bug Timeline

issue started 2 days ago. Before that day, with exactly the same sources (V2.1.2) everything was fine

### Expected behavior

I expected to build a Marlin firmware with maple environment

### Actual behavior

but I receive this error message:
 ```prolog
Building in release mode
RuntimeError: deque mutated during iteration:
  File "C:\Users\tr\.platformio\penv\lib\site-packages\platformio\builder\main.py", line 181:
    env.SConscript(env.GetExtraScripts("post"), exports="env")
  File "C:\Users\tr\.platformio\packages\tool-scons\scons-local-4.5.2\SCons\Script\SConscript.py", line 598:
    return _SConscript(self.fs, *files, **subst_kw)
  File "C:\Users\tr\.platformio\packages\tool-scons\scons-local-4.5.2\SCons\Script\SConscript.py", line 285:
    exec(compile(scriptdata, scriptname, 'exec'), call_stack[-1].globals)
  File "C:\tempMarlin\Marlin-2.1.x_20230512\buildroot\share\PlatformIO\scripts\custom_board.py", line 14:
    marlin.relocate_firmware(address)
  File "C:\tempMarlin\Marlin-2.1.x_20230512\buildroot\share\PlatformIO\scripts\marlin.py", line 26:
    replace_define("VECT_TAB_ADDR", address)
  File "C:\tempMarlin\Marlin-2.1.x_20230512\buildroot\share\PlatformIO\scripts\marlin.py", line 19:
    for define in env['CPPDEFINES']:
==================================================================================== [FAILED] Took 11.29 seconds ====================================================================================

Environment               Status    Duration
------------------------  --------  ------------
STM32F103VE_longer_maple  FAILED    00:00:11.293
=============================================================================== 1 failed, 0 succeeded in 00:00:11.293 ===============================================================================
```

### Steps to Reproduce

1. download Marlin v2.1.2 and config files for alfawise U20
2. choose STM32F103VE_longer_maple environment in platformio.ini file
3. build sources

### Version of Marlin Firmware

all versions except Marlin bugfix

### Printer model

alfawise U20 / longer LK1

### Electronics

stock 3d printer

### Add-ons

no add-ons

### Bed Leveling

None

### Your Slicer

IdeaMaker

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Marlin-2.1.2 standard U20 config files.zip](https://github.com/MarlinFirmware/Marlin/files/11461725/Marlin-2.1.2.standard.U20.config.files.zip)

**Comment by ellensp** [comment] 2023-05-12 12:16
Removed. Better fix below.

**Comment by rbora13** [comment] 2023-05-12 12:39
Thank you very much for your quick response. Now, I am able to build a firmware but, after flashing, unfortunately screen is blank :(

> Python is really hating the following

That's fair, I hate Python XD

**Comment by ellensp** [comment] 2023-05-12 13:30
previously reported https://github.com/MarlinFirmware/Marlin/issues/25698
As a test if you disable  #define SDSUPPORT   does it now boot?

**Comment by rbora13** [comment] 2023-05-12 17:19
Unfortunately, same result: no boot, with or without #define SDIO_SUPPORT disabled

**Comment by ellensp** [comment] 2023-05-12 17:25
#define SDSUPPORT != #define SDIO_SUPPORT

**Comment by rbora13** [comment] 2023-05-12 18:37
Of course ;-) I meant, I tried both : 1rst test SDSUPPORT disabled, 2nd test SDSUPPORT  **AND** SDIO_SUPPORT disabled  

Edit: Just a few remarks from a guy who is not a developer:
1- problem happened suddlenly 2 days ago, with exactly the same sources, \buildroot\share\PlatformIO\scripts\marlin.py file included
2- It is only possible to build a firmware with Marlin bugfix-2.1. x sources. It fails with Marlin 2.1.2 and Marlin 2.1.2 with bug fixes. With bugfix-2.1. x, the printer boots as expected.

**Comment by bulat1304** [comment] 2023-05-13 08:59
the same problem for version 2.0.x

**Comment by ellensp** [comment] 2023-05-16 09:27
Latest bugfix and platformio I can no longer replicate this issue. was fixed in https://github.com/MarlinFirmware/Marlin/commit/c2decc3e2e30c7cb0f517b7e40d8138a8c1d4a81

**Comment by thisiskeithb** [comment] 2023-05-17 23:13
> Latest bugfix and platformio I can no longer replicate this issue and code above is not changed

I can't reproduce it either. We also use this config in CI tests and those are passing.

**Closed as completed by thisiskeithb** 2023-05-17 23:13 UTC
Labels: S: Solved

**Comment by rbora13** [comment] 2023-05-18 20:38
Hi,
Of course the issue doesn't exist with the latest bugfix, that's the first sentence of my first message. The problem is that the latest bugfix version is full of bugs. So, if I understand correctly, I have to wait the next stable release?

**Comment by Q07707** [comment] 2023-05-25 01:14
I also encountered the same problem as you, how did I solve it?  My environment is  tronxy-stm32f446
Just replacing a portion of the source code in buildroot/share/PlatformIO/scripts/marlin.py?
But can the firmware run normally?

**Comment by rbora13** [comment] 2023-05-27 13:39
I’m pretty sure not. If I understand correctly, you have three options:

1. choose non maple environment
2. wait for the next stable release
3. move to klipper
Personally, I chose the 3rd one and everything is perfect! XD

**Comment by ellensp** [comment] 2023-05-29 00:23
This was fixed here. you can apply this to any that do not work.
https://github.com/MarlinFirmware/Marlin/commit/c2decc3e2e30c7cb0f517b7e40d8138a8c1d4a81

```DIFF
-    for define in env['CPPDEFINES']:
+    envdefs = env['CPPDEFINES'].copy()
+    for define in envdefs:
```

**Comment by Q07707** [comment] 2023-05-29 03:56
Thank you, I can compile successfully, the firmware runs normally.
