### ISSUE TITLE
Z drops down into part while printing

### ISSUE THREAD

**Issue by serhattural** [MarlinFirmware/Marlin#12030] opened 2018-10-07 14:32 UTC
I checked gcode. There is no lines about lower Z. But after some layers Z goes down. I added a gcode. 
[ZDownBug.zip](https://github.com/MarlinFirmware/Marlin/files/2453982/ZDownBug.zip)

**Comment by Ludy87** [comment] 2018-10-07 14:56
Try the new branch update https://github.com/MarlinFirmware/Marlin/tree/bugfix-2.0.x || https://github.com/MarlinFirmware/Marlin/tree/bugfix-1.1.x || https://github.com/MarlinFirmware/Marlin/tree/1.1.x

**Comment by thinkyhead** [comment] 2018-10-16 11:26
@serhattural — What slicer did you use to generate that G-code?

**Comment by thinkyhead** [comment] 2018-10-16 11:27
Please test the `bugfix-1.1.x` and/or `bugfix-2.0.x` branches to see whether it helps. If the problem has been resolved then we can close this issue. If the issue isn't resolved in either of those branches yet, then we should investigate further.

**Comment by boelle** [comment] 2019-02-21 19:23
@serhattural problem solved in bugfix 2.0?

**Closed as completed** 2019-05-16 23:16 UTC
Labels: T: Question
