### ISSUE TITLE
[BUG] Bed heating pid is broken

### ISSUE THREAD

**Issue by ErsaFap** [MarlinFirmware/Marlin#23275] opened 2021-12-07 15:16 UTC
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

Bed heating is off by 10 degress causing thermal protection cutoff.
Bang mode works correctly.

### Bug Timeline

Old

### Expected behavior

Bed heats to 100C

### Actual behavior

Bed heats to 90C

### Steps to Reproduce

1 Open repetier host
2 Turn on bed heating to any temperature 
3 The bed heats up to  (tset - 10deg) and stabilizes 
4 Thermal fault after 20 sec

### Version of Marlin Firmware

2.0.x, 2.0.x bugfix, 2.0.9

### Printer model

Flyingbear P902

### Electronics

Bigtreetech SKR 1.3

### Add-ons

RepRap discount smart controller

### Host Software

Repetier Host

### Additional information & file uploads

![Screenshot_5](https://user-images.githubusercontent.com/3918292/145055573-b6a90034-519d-4a58-9efc-a59fc660e749.png)

**Comment by ellensp** [comment] 2021-12-07 19:44
Do you have #define BED_MAXTEMP  90

**Comment by ErsaFap** [comment] 2021-12-07 20:00
> Do you have #define BED_MAXTEMP 90

I'm sad to read this. I am not imbecile. 
[config.zip](https://github.com/MarlinFirmware/Marlin/files/7671229/config.zip)

Here is my config, I hope it will be useful

**Comment by thisiskeithb** [comment] 2021-12-07 20:11
> I'm sad to read this. I am not imbecile.

No one said that.

You didn't include your configs in the original report like the issue template requested, so we can only guess as to what the issue could be.

**Comment by NezSez** [comment] 2021-12-07 20:17
> I'm sad to read this. I am not imbecile.

He didn't mean to imply that, it's just normal good tshooting practice to rule out obvious/simple fixes first especially when going on minimal information.

**Comment by ErsaFap** [comment] 2021-12-07 20:28
> > I'm sad to read this. I am not imbecile.
> 
> He didn't mean to imply that, it's just normal good tshooting practice to rule out obvious/simple fixes first especially when going on minimal information.

its ok. Don't worry about it .
I found this problem has been around for a long time. Possible since version 2.0.6, Im not sure.

**Comment by thisiskeithb** [comment] 2021-12-07 20:38
Duplicate of #21799

**Closed as completed by thisiskeithb** 2021-12-07 20:38 UTC
Labels: Bug: Potential ?, C: Temperatures

**Comment by ErsaFap** [comment] 2021-12-07 20:51
Its not duplicate (I think), the regulator is doing great but target temperature is incorrect. 
It heats up to 90 degrees in 6 minutes. Power is enough. But it should heat up to 100.
